### ISSUE TITLE
text_generation/vae-seq2seq can't launch training on gpu

### ISSUE THREAD

**Issue by neqkir** [PaddlePaddle/PaddleNLP#1040]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_generation/vae-seq2seq 

Using Python3.6, OS Ubuntu 3.8, system with 2 AMD GPUs

I do 

`root@mymachine:/root/vae/paddle-vae# export HIP_VISIBLE_DEVICES=0,1 
`
then

```
root@mymachine:/root/vae/paddle-vae# python3 train.py         --batch_size 32         --init_scale 0.1         --max_grad_norm 5.0         --dataset ptb         --model_path ptb_model        --device gpu         --max_epoch 50
Namespace(batch_size=32, beam_size=1, dataset='ptb', dec_dropout=0.5, device='gpu', embed_dim=256, enc_dropout=0.0, hidden_size=256, infer_output_file='infer_output.txt', init_from_ckpt=None, init_scale=0.1, kl_start=0.1, latent_size=32, learning_rate=0.001, log_freq=200, max_epoch=50, max_grad_norm=5.0, max_len=1280, model_path='ptb_model', num_layers=1, warm_up=10)
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    train(args)
  File "train.py", line 26, in train
    device = paddle.set_device(args.device)
  File "/usr/local/lib/python3.6/dist-packages/paddle/device.py", line 186, in set_device
    place = _convert_to_place(device)
  File "/usr/local/lib/python3.6/dist-packages/paddle/device.py", line 126, in _convert_to_place
    raise ValueError("The device should not be 'gpu', "
ValueError: The device should not be 'gpu', since PaddlePaddle is not compiled with CUDA

```

I tried the other multigpu commandlines with no success, since the flag --gpus is not recognized

```
python -m paddle.distributed.launch --gpus "0,1" train.py \
        --batch_size 32 \
        --embed_dim 512 \
        --hidden_size 550 \
        --init_scale 0.1 \
        --max_grad_norm 5.0 \
        --dataset yahoo \
        --model_path yahoo_model \
        --device gpu \
        --max_epoch 50 \
```

gives 

```
usage: launch.py [-h] [--log_dir LOG_DIR] [--nproc_per_node NPROC_PER_NODE]
                 [--run_mode RUN_MODE] [--ips IPS] [--servers SERVERS]
                 [--workers WORKERS] [--heter_workers HETER_WORKERS]
                 [--worker_num WORKER_NUM] [--server_num SERVER_NUM]
                 [--heter_worker_num HETER_WORKER_NUM] [--http_port HTTP_PORT]
                 training_script ...
launch.py: error: unrecognized arguments: --gpus
```

**Comment by ZeyuChen** [comment]
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/guides/09_hardware_support/rocm_docs/paddle_install_cn.html
You should install ROCM version GPU and try again. BTW this is still experimental version.
It would be better to try it on NVIDIA GPU with CUDA support.
@neqkir

**Comment by neqkir** [comment]
thanks! anything more up to date..?

```
/root/vae/paddle-vae# python -m pip install paddlepaddle-rocm==2.1.2.rocm401.miopen211 -f https://www.paddlepaddle.org.cn/whl/rocm/stable.whl
Looking in links: https://www.paddlepaddle.org.cn/whl/rocm/stable.whl
WARNING: Skipping page https://www.paddlepaddle.org.cn/whl/rocm/stable.whl because the HEAD request got Content-Type: text/plain;charset=UTF-8.The only supported Content-Type is text/html
ERROR: Could not find a version that satisfies the requirement paddlepaddle-rocm==2.1.2.rocm401.miopen211 (from versions: none)
ERROR: No matching distribution found for paddlepaddle-rocm==2.1.2.rocm401.miopen211

```

**Comment by neqkir** [comment]
this is i guess ? 

   ```
   <td>PR-CI-ROCM-Compile</td>
      <td> paddlepaddle/paddle:latest-dev-rocm4.0-miopen2.11</td>
```

yet
```

root/vae/paddle-vae# python -m pip install paddlepaddle-rocm==2.1.2.rocm4.0.miopen2.11 -f https://www.paddlepaddle.org.cn/whl/rocm/stable.whl
Looking in links: https://www.paddlepaddle.org.cn/whl/rocm/stable.whl
WARNING: Skipping page https://www.paddlepaddle.org.cn/whl/rocm/stable.whl because the HEAD request got Content-Type: text/plain;charset=UTF-8.The only supported Content-Type is text/html
ERROR: Could not find a version that satisfies the requirement paddlepaddle-rocm==2.1.2.rocm4.0.miopen2.11 (from versions: none)
ERROR: No matching distribution found for paddlepaddle-rocm==2.1.2.rocm4.0.miopen2.11
```

**Comment by ZeyuChen** [comment]
@neqkir https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/guides/09_hardware_support/rocm_docs/paddle_install_cn.html
You can try to install according to this document. As for the version it depends on your machine.

**Comment by ZeyuChen** [comment]
We recommend you to run this code on a NVIDIA GPU device.
