### ISSUE TITLE
[生产Bug]uwsgi多进程方式触发paddlenlp生产问题

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#1084]
当使用uwsgi多进程方式部署paddlenlp模型时， 所有worker被kill， 检查log时发现，当多个process同时发现'/root/.paddlenlp/datasets' 不存在时，去创建该目录时出现错误。

----------------------
\n
\n2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
\n1   paddle::framework::SignalHandle(char const*, int)
\n0   paddle::memory::allocation::MemoryMapFdSet::Clear()
\n  [TimeInfo: *** Aborted at 1632395519 (unix time) try "date -d @1632395519" if you are using GNU date ***]
\nFatalError: `Process abort signal` is detected by the operating system.
\n----------------------
\nError Message Summary:
\n--------------------------------------
\n
\n
\n
\n  [SignalInfo: *** SIGABRT (@0xc) received by PID 12 (TID 0x7fd7d709d600) from PID 12 ***]
\n0   paddle::memory::allocation::MemoryMapFdSet::Clear()
\n--------------------------------------
\nC++ Traceback (most recent call last):
\nError Message Summary:
\n----------------------
\n
\n2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
\n1   paddle::framework::SignalHandle(char const*, int)
\n  [SignalInfo: *** SIGABRT (@0xd) received by PID 13 (TID 0x7fd7d709d600) from PID 13 ***]
\n  [TimeInfo: *** Aborted at 1632395519 (unix time) try "date -d @1632395519" if you are using GNU date ***]
\nFatalError: `Process abort signal` is detected by the operating system.
\n----------------------
\nC++ Traceback (most recent call last):
\n--------------------------------------
\n
\n
\n
\n2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
\n1   paddle::framework::SignalHandle(char const*, int)
\n0   paddle::memory::allocation::MemoryMapFdSet::Clear()
\n--------------------------------------
\n----------------------
\nError Message Summary:
\n----------------------
\n
\nworker 2 buried after 1 seconds
\n
\n  [SignalInfo: *** SIGABRT (@0xb) received by PID 11 (TID 0x7fd7d709d600) from PID 11 ***]
\n  [TimeInfo: *** Aborted at 1632395519 (unix time) try "date -d @1632395519" if you are using GNU date ***]
\nFatalError: `Process abort signal` is detected by the operating system.
\nWSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x5590dd960b20 pid: 10 (default app)
\nworker 4 buried after 1 seconds
\nworker 3 buried after 1 seconds
\nThu Sep 23 11:12:05 2021 - worker 1 (pid: 10) is taking too much time to die...NO MERCY !!!
\ngoodbye to uWSGI.
\nworker 1 buried after 1 seconds
\nVACUUM: pidfile removed.
\n[uWSGI] getting INI configuration from /home/service/uwsgi.ini
\ncompiled with version: 7.5.0 on 23 September 2021 09:27:57
\n*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Sep 23 11:17:10 2021] ***
\nclock source: unix
\nmachine: x86_64
\nnodename: serve-1632311856048-d67cb8d7f-t2v82
\nos: Linux-3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020
\ndetected binary path: /usr/local/bin/uwsgi
\nwriting pidfile to /home/service/uwsgi.pid
\ncurrent working directory: /home/service
\ndetected number of CPU cores: 16
\nchdir() to /home/service
\n*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
\nuWSGI running as root, you can use --uid/--gid/--chroot options
\n!!! no internal routing support, rebuild with pcre support !!!
\nthunder lock: disabled (you can enable it with --thunder-lock)
\nlock engine: pthread robust mutexes
\ndetected max file descriptor number: 1048576
\nyour memory page size is 4096 bytes
\nyour processes number limit is 1048576
\n*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
\nuWSGI running as root, you can use --uid/--gid/--chroot options
\nuwsgi socket 0 bound to TCP address 127.0.0.1:39023 (port auto-assigned) fd 3
\nuWSGI http bound on 0.0.0.0:8021 fd 4
\n*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
\nuWSGI running as root, you can use --uid/--gid/--chroot options
\nPython main interpreter initialized at 0x560d7fffbb20
\nPython version: 3.7.10 (default, May  3 2021, 02:48:31)  [GCC 7.5.0]
\nmapped 521440 bytes (509 KB) for 16 cores
\nyour mercy for graceful operations on workers is 5 seconds
\nyour server socket listen backlog is limited to 100 connections
\npython threads support enabled
\nspawned uWSGI master process (pid: 9)
\n*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
\nuWSGI running as root, you can use --uid/--gid/--chroot options
\n*** Operational MODE: preforking+threaded ***
\nspawned uWSGI worker 4 (pid: 13, cores: 4)
\nspawned uWSGI worker 3 (pid: 12, cores: 4)
\nspawned uWSGI worker 2 (pid: 11, cores: 4)
\nspawned uWSGI worker 1 (pid: 10, cores: 4)
\n    import paddlenlp as ppnlp
\nTraceback (most recent call last):
  File "crisis_cls_client.py", line 10, in <module>
  File "crisis_cls_client.py", line 10, in <module>
\nTraceback (most recent call last):
  File "crisis_cls_client.py", line 10, in <module>
Traceback (most recent call last):
\nspawned uWSGI http 1 (pid: 14)
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/__init__.py", line 18, in <module>
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/__init__.py", line 18, in <module>
\n    import paddlenlp as ppnlp
\n    import paddlenlp as ppnlp
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/__init__.py", line 18, in <module>
\n    from . import datasets
\n    from . import datasets
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/datasets/__init__.py", line 15, in <module>
\n    from . import datasets
\n    from .dataset import *
\n    from .dataset import *
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/datasets/__init__.py", line 15, in <module>
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/datasets/__init__.py", line 15, in <module>
\n    from paddlenlp.utils.env import DATA_HOME
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/datasets/dataset.py", line 30, in <module>
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/datasets/dataset.py", line 30, in <module>
\n    from .dataset import *
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/datasets/dataset.py", line 30, in <module>
\n    from paddlenlp.utils.env import DATA_HOME
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/utils/env.py", line 53, in <module>
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/utils/env.py", line 53, in <module>
\n    from paddlenlp.utils.env import DATA_HOME
\n    DATA_HOME = _get_sub_home('datasets')
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/utils/env.py", line 46, in _get_sub_home
\n    DATA_HOME = _get_sub_home('datasets')
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/utils/env.py", line 53, in <module>
\n  File "/usr/lib/python3.7/os.py", line 223, in makedirs
\n    os.makedirs(home)
\n  File "/usr/lib/python3.7/os.py", line 223, in makedirs
\n    os.makedirs(home)
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/utils/env.py", line 46, in _get_sub_home
\n  File "/usr/lib/python3.7/os.py", line 223, in makedirs
\n    os.makedirs(home)
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/utils/env.py", line 46, in _get_sub_home
\n    DATA_HOME = _get_sub_home('datasets')
\n    mkdir(name, mode)
\nunable to load app 0 (mountpoint='') (callable not found or import error)
\nFileExistsError: [Errno 17] File exists: '/root/.paddlenlp/datasets'
\n    mkdir(name, mode)
\n*** no app loaded. GAME OVER ***
\nFileExistsError: [Errno 17] File exists: '/root/.paddlenlp/datasets'
\nFileExistsError: [Errno 17] File exists: '/root/.paddlenlp/datasets'
\n    mkdir(name, mode)
\n*** no app loaded. GAME OVER ***
\n*** no app loaded. GAME OVER ***
\nunable to load app 0 (mountpoint='') (callable not found or import error)
\nunable to load app 0 (mountpoint='') (callable not found or import error)
\n
\ngateway "uWSGI http 1" has been buried (pid: 14)
\nSIGINT/SIGQUIT received...killing workers...
\n--------------------------------------
\nC++ Traceback (most recent call last):
\n--------------------------------------
\n
\n
\n2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
\n1   paddle::framework::SignalHandle(char const*, int)
\n0   paddle::memory::allocation::MemoryMapFdSet::Clear()
\n----------------------
\nError Message Summary:
\n----------------------
\nFatalError: `Process abort signal` is detected by the operating system.
\n
\n
\n  [SignalInfo: *** SIGABRT (@0xa) received by PID 10 (TID 0x7f1d10fe8600) from PID 10 ***]
\n  [TimeInfo: *** Aborted at 1632395835 (unix time) try "date -d @1632395835" if you are using GNU date ***]
\n0   paddle::memory::allocation::MemoryMapFdSet::Clear()
\n--------------------------------------
\nC++ Traceback (most recent call last):
\n--------------------------------------
\n
\n----------------------
\n
\n2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
\n1   paddle::framework::SignalHandle(char const*, int)
\n  [TimeInfo: *** Aborted at 1632395835 (unix time) try "date -d @1632395835" if you are using GNU date ***]
\nFatalError: `Process abort signal` is detected by the operating system.
\n----------------------
\nError Message Summary:
\n--------------------------------------
\n
\n
\n
\n  [SignalInfo: *** SIGABRT (@0xc) received by PID 12 (TID 0x7f1d10fe8600) from PID 12 ***]
\n2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
\n1   paddle::framework::SignalHandle(char const*, int)
\n0   paddle::memory::allocation::MemoryMapFdSet::Clear()
\n--------------------------------------
\nC++ Traceback (most recent call last):
\n----------------------
\nError Message Summary:
\n----------------------
\n
\n
\n  [SignalInfo: *** SIGABRT (@0xb) received by PID 11 (TID 0x7f1d10fe8600) from PID 11 ***]
\n  [TimeInfo: *** Aborted at 1632395835 (unix time) try "date -d @1632395835" if you are using GNU date ***]
\nFatalError: `Process abort signal` is detected by the operating system.
\nThu Sep 23 11:17:21 2021 - worker 4 (pid: 13) is taking too much time to die...NO MERCY !!!
\nWSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x560d7fffbb20 pid: 13 (default app)
\nworker 3 buried after 1 seconds
\nworker 2 buried after 1 seconds
\nworker 1 buried after 1 seconds
\nVACUUM: pidfile removed.
\ngoodbye to uWSGI.
\nworker 4 buried after 1 seconds

**Comment by LangDaoAI** [comment]
与https://github.com/PaddlePaddle/VisualDL/issues/943 类似

**Comment by LangDaoAI** [comment]
import paddlenlp as ppnlp
\nTraceback (most recent call last):
  File "crisis_cls_client.py", line 10, in <module>
  File "crisis_cls_client.py", line 10, in <module>
  File "crisis_cls_client.py", line 10, in <module>
    import paddlenlp as ppnlp
\nTraceback (most recent call last):
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/__init__.py", line 19, in <module>
\n    import paddlenlp as ppnlp
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/__init__.py", line 19, in <module>
\n    from . import embeddings
\n    from . import embeddings
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/__init__.py", line 19, in <module>
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/embeddings/__init__.py", line 15, in <module>
\n    from . import embeddings
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/embeddings/__init__.py", line 15, in <module>
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/embeddings/token_embedding.py", line 30, in <module>
\n    from .token_embedding import *
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/embeddings/__init__.py", line 15, in <module>
\n    from .token_embedding import *
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/embeddings/token_embedding.py", line 30, in <module>
\n    from .token_embedding import *
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/utils/env.py", line 46, in _get_sub_home
\n    EMBEDDING_HOME = _get_sub_home('embeddings', parent_home=MODEL_HOME)
\n    EMBEDDING_HOME = _get_sub_home('embeddings', parent_home=MODEL_HOME)
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/embeddings/token_embedding.py", line 30, in <module>
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/utils/env.py", line 46, in _get_sub_home
\n    EMBEDDING_HOME = _get_sub_home('embeddings', parent_home=MODEL_HOME)
\n  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/utils/env.py", line 46, in _get_sub_home
\n    os.makedirs(home)
\n  File "/usr/lib/python3.7/os.py", line 223, in makedirs
\n    os.makedirs(home)
\n    mkdir(name, mode)
\n  File "/usr/lib/python3.7/os.py", line 223, in makedirs
\n  File "/usr/lib/python3.7/os.py", line 223, in makedirs
\n    os.makedirs(home)
\nFileExistsError: [Errno 17] File exists: '/root/.paddlenlp/models/embeddings'
\n    mkdir(name, mode)
\n    mkdir(name, mode)
\nunable to load app 0 (mountpoint='') (callable not found or import error)
\nFileExistsError: [Errno 17] File exists: '/root/.paddlenlp/models/embeddings'
\nFileExistsError: [Errno 17] File exists: '/root/.paddlenlp/models/embeddings'
\n*** no app loaded. GAME OVER ***
\n*** no app loaded. GAME OVER ***
\nunable to load app 0 (mountpoint='') (callable not found or import error)
\nunable to load app 0 (mountpoint='') (callable not found or import error)
\ngateway "uWSGI http 1" has been buried (pid: 14)
\nSIGINT/SIGQUIT received...killing workers...
\n*** no app loaded. GAME OVER ***
\n--------------------------------------
\n
\n
\n0   paddle::memory::allocation::MemoryMapFdSet::Clear()
\n--------------------------------------
\nC++ Traceback (most recent call last):
\n----------------------
\n
\n2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
\n1   paddle::framework::SignalHandle(char const*, int)
\nFatalError: `Process abort signal` is detected by the operating system.
\n----------------------
\nError Message Summary:
\n
\n  [SignalInfo: *** SIGABRT (@0xb) received by PID 11 (TID 0x7fa51e0d4600) from PID 11 ***]
\n  [TimeInfo: *** Aborted at 1632397751 (unix time) try "date -d @1632397751" if you are using GNU date ***]
\nC++ Traceback (most recent call last):
\n--------------------------------------
\n
\n
\n1   paddle::framework::SignalHandle(char const*, int)
\n0   paddle::memory::allocation::MemoryMapFdSet::Clear()
\n--------------------------------------
\nError Message Summary:
\n----------------------
\n
\n2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
\n  [TimeInfo: *** Aborted at 1632397751 (unix time) try "date -d @1632397751" if you are using GNU date ***]
\nFatalError: `Process abort signal` is detected by the operating system.
\n----------------------
\n
\n
\n  [SignalInfo: *** SIGABRT (@0xc) received by PID 12 (TID 0x7fa51e0d4600) from PID 12 ***]
\nC++ Traceback (most recent call last):
\n--------------------------------------
\n
\n1   paddle::framework::SignalHandle(char const*, int)
\n0   paddle::memory::allocation::MemoryMapFdSet::Clear()
\n--------------------------------------
\n
\n2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
\n----------------------
\nError Message Summary:
\n----------------------
\n  [SignalInfo: *** SIGABRT (@0xd) received by PID 13 (TID 0x7fa51e0d4600) from PID 13 ***]
\n  [TimeInfo: *** Aborted at 1632397751 (unix time) try "date -d @1632397751" if you are using GNU date ***]
\nFatalError: `Process abort signal` is detected by the operating system.
\n
\nworker 4 buried after 1 seconds
\nworker 3 buried after 1 seconds
\nworker 2 buried after 1 seconds
\nThu Sep 23 11:49:12 2021 - worker 1 (pid: 10) is taking too much time to die...NO MERCY !!!
\nVACUUM: pidfile removed.
\ngoodbye to uWSGI.
\nworker 1 buried after 1 seconds

**Comment by LangDaoAI** [comment]
'/root/.paddlenlp/models/embeddings'  同样也是这个问题
