### ISSUE TITLE
AttributeError: module 'paddlenlp' has no attribute 'losses'

### ISSUE THREAD

**Issue by flydragon2018** [PaddlePaddle/PaddleNLP#1095]
/example/text_matching/question_mathing

Traceback (most recent call last):
  File "train.py", line 218, in <module>
    do_train()
  File "train.py", line 142, in do_train
    model = QuestionMatching(pretrained_model, rdrop_coef=args.rdrop_coef)
  File "/home/aistudio/model.py", line 31, in __init__
    self.rdrop_loss = ppnlp.losses.RDropLoss()
AttributeError: module 'paddlenlp' has no attribute 'losses'

**Comment by flydragon2018** [comment]
my bad.  need to upgrade paddlenlp version to 2.08.
