### ISSUE TITLE
试图下载并且调用paddlenlp的skep_ernie_1.0_large_ch安装包，却出现了问题

### ISSUE THREAD

**Issue by FleetCommander004** [PaddlePaddle/PaddleNLP#1132]
最近我在试图下载paddlenlp的skep_ernie_1.0_large_ch安装包。
我的paddlenlp版本是2.0.8.
paddlepaddle版本是2.1.3.
我安装的时候似乎中途中断了一下，导致一些东西下载的不够顺畅。当我试图调用skep_ernie_1.0_large_ch的时候，出现了如下问题：
Traceback (most recent call last):
  File "C:\Users\karlf\Anaconda3\envs\paddle_env\lib\site-packages\paddle\framework\io.py", line 855, in load
    load_result = pickle.load(f) if six.PY2 else pickle.load(
_pickle.UnpicklingError: pickle data was truncated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\karlf\Anaconda3\envs\paddle_env\lib\site-packages\paddle\framework\io.py", line 881, in load
    tensor, _ = _load_selected_rows(path)
  File "C:\Users\karlf\Anaconda3\envs\paddle_env\lib\site-packages\paddle\framework\io.py", line 492, in _load_selected_rows
    _seek = core._load_selected_rows(temp_sr, file_name)
ValueError: (InvalidArgument) Only version 0 SelectedRows is supported.
  [Hint: Expected version == 0U, but received version:1904018304 != 0U:0.] (at C:\home\workspace\Paddle_release\paddle\fluid\framework\selected_rows.cc:139)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\karlf\Anaconda3\envs\paddle_env\lib\site-packages\paddle\framework\io.py", line 885, in load
    tensor, _ = _load_lod_tensor(path)
  File "C:\Users\karlf\Anaconda3\envs\paddle_env\lib\site-packages\paddle\framework\io.py", line 477, in _load_lod_tensor
    _seek = paddle.fluid.core._load_lod_tensor(temp_t, file_name)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 1904018304 found).
  [Hint: Expected version == 0U, but received version:1904018304 != 0U:0.] (at C:\home\workspace\Paddle_release\paddle\fluid\framework\lod_tensor.cc:329)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\karlf\Anaconda3\envs\paddle_env\lib\site-packages\paddle\framework\io.py", line 896, in load
    program = Program.parse_from_string(
  File "C:\Users\karlf\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\framework.py", line 4815, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\framework\program_desc.cc:103)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\karlf\Anaconda3\envs\paddle_env\lib\site-packages\paddlenlp\transformers\model_utils.py", line 323, in from_pretrained
    state_dict = paddle.load(weight_path)
  File "C:\Users\karlf\Anaconda3\envs\paddle_env\lib\site-packages\paddle\framework\io.py", line 900, in load
    raise ValueError(
ValueError: `paddle.load` can not parse the file:C:\Users\karlf\.paddlenlp\models\skep_ernie_1.0_large_ch\skep_ernie_1.0_large_ch.pdparams.

我当时调用的代码是 **paddlenlp.transformers.SkepForTokenClassification.from_pretrained('skep_ernie_1.0_large_ch')**。

**现在的问题是我如何删除掉这个有问题的模型再重新下载呢？**

**Comment by ZeyuChen** [comment]
`C:\Users\karlf.paddlenlp\models\`
可以试试删除你本地用户目录下的这个文件夹后再重新尝试。

**Comment by FleetCommander004** [comment]
> `C:\Users\karlf.paddlenlp\models\` 可以试试删除你本地用户目录下的这个文件夹后再重新尝试。

谢谢!下载成功了。
