### ISSUE TITLE
保存unimo-text静态图模型时，报错AttributeError: 'tuple' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by Stave604671** [PaddlePaddle/PaddleNLP#1169]
两个问题：
1、想要保存unimo-text的静态图模型，使用以下代码执行的时候报错。
2、如何保存unimo-text的结构信息然后可视化模型结构，visualdl无法读取，
![image](https://user-images.githubusercontent.com/59908449/137311603-0d16aa2e-349a-4ed3-bfad-a996fe5c84fd.png)

![image](https://user-images.githubusercontent.com/59908449/137311528-b5b081cf-408e-4388-8a22-372254e507bf.png)

- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.0.8，PaddlePaddle-gpu==2.1.0
2）系统环境：
系统类型，Windows，
python版本，3.8
复现代码如下，直接run运行即可：
from paddlenlp.transformers import UNIMOLMHeadModel,UNIMOTokenizer
import paddle

if __name__ == '__main__':
    model = UNIMOLMHeadModel.from_pretrained("unimo-text-1.0")
    tokenizer = UNIMOTokenizer.from_pretrained("unimo-text-1.0")
    paddle.save(model, "model.pdmodel")
    sources = "日前，方舟子发文直指林志颖旗下爱碧丽推销假保健品，引起哗然。调查发现，爱碧丽没有自己的生产加工厂。其胶原蛋白饮品无核心研发，全部代工生产。号称有“逆生长”功效的爱碧丽“梦幻奇迹限量组”售价高达1080元，实际成本仅为每瓶4元！"
    inputs = tokenizer.gen_encode(
        sources,
        max_seq_len=320,
        max_title_len=30,
        add_start_token_for_decoding=True,
        return_position_ids=True,
        return_tensors=True)
    shape_s = [inputs['input_ids'].astype("int64").shape,
               inputs['token_type_ids'].astype("int64").shape,
               inputs['position_ids'].astype("int64").shape,
               inputs['attention_mask'].shape]
    # param_info = paddle.summary(model, input_size=shape_s, dtypes="int64")
    model.eval()
    m = [
        paddle.static.InputSpec(
            shape=shape_s[0]),  # input_ids
        paddle.static.InputSpec(
            shape=shape_s[1]),  # segment_ids
        paddle.static.InputSpec(
            shape=shape_s[2]),  # input_ids
        paddle.static.InputSpec(
            shape=shape_s[3])  # segment_ids
    ]
    model = paddle.jit.to_static(
        model,
        input_spec=m)

    paddle.jit.save(model, "output")

**Comment by smallv0221** [comment]
This is caused by a bug of `paddle.jit.to_static`. We are working on it. Sorry for the inconvenience.

**Comment by SkipAngel** [comment]
请问一下能把unimo转成动态图弄成onnx模型吗

**Comment by SkipAngel** [comment]
dev_ds = load_dataset(
        'advertisegen', splits='dev', data_files="./phvm/phvm_test.jsonl")
    model = UNIMOLMHeadModel.from_pretrained("./table_log/checkpoints/model_15000")
    tokenizer = UNIMOTokenizer.from_pretrained("./table_log/checkpoints/model_15000")
    resource_files_names = "./table_log/checkpoints/model_15000/model_state.pdparams"
    dev_ds, dev_data_loader = create_data_loader(dev_ds, tokenizer, args,
                                                 'test')

    # 加载预训练模型参数
    model.set_dict(paddle.load(resource_files_names))

    # 将模型设置为评估状态
    model.eval()
    # paddle.save(model, "model.pdmodel")
    for step, inputs in enumerate(dev_data_loader, 1):
        input_ids, token_type_ids, position_ids, attention_mask = inputs
        break
    x_spec = paddle.static.InputSpec([None, 784], 'float32', 'x')

    shape_s = [input_ids.shape,
               token_type_ids.shape,
               position_ids.shape,
               attention_mask.shape]
    m = [
    paddle.static.InputSpec(
    shape_s[0],'int32'), # input_ids
    paddle.static.InputSpec(
    shape_s[1],'int32'), # segment_ids
    paddle.static.InputSpec(
    shape_s[2],'int32'), # input_ids
    paddle.static.InputSpec(
    shape_s[3],'float32') # segment_ids
    ]
    # param_info = paddle.summary(model, input_size=shape_s, dtypes="int64"

    # ONNX模型导出
    paddle.onnx.export(model, "./onnx_model", input_spec=m)

报错：AttributeError: 'tuple' object has no attribute 'dtype'

**Comment by Stave604671** [comment]
> ```
> dev_ds = load_dataset(
>     'advertisegen', splits='dev', data_files="./phvm/phvm_test.jsonl")
> model = UNIMOLMHeadModel.from_pretrained("./table_log/checkpoints/model_15000")
> tokenizer = UNIMOTokenizer.from_pretrained("./table_log/checkpoints/model_15000")
> resource_files_names = "./table_log/checkpoints/model_15000/model_state.pdparams"
> dev_ds, dev_data_loader = create_data_loader(dev_ds, tokenizer, args,
>                                              'test')
> 
> # 加载预训练模型参数
> model.set_dict(paddle.load(resource_files_names))
> 
> # 将模型设置为评估状态
> model.eval()
> # paddle.save(model, "model.pdmodel")
> for step, inputs in enumerate(dev_data_loader, 1):
>     input_ids, token_type_ids, position_ids, attention_mask = inputs
>     break
> x_spec = paddle.static.InputSpec([None, 784], 'float32', 'x')
> 
> shape_s = [input_ids.shape,
>            token_type_ids.shape,
>            position_ids.shape,
>            attention_mask.shape]
> m = [
> paddle.static.InputSpec(
> shape_s[0],'int32'), # input_ids
> paddle.static.InputSpec(
> shape_s[1],'int32'), # segment_ids
> paddle.static.InputSpec(
> shape_s[2],'int32'), # input_ids
> paddle.static.InputSpec(
> shape_s[3],'float32') # segment_ids
> ]
> # param_info = paddle.summary(model, input_size=shape_s, dtypes="int64"
> 
> # ONNX模型导出
> paddle.onnx.export(model, "./onnx_model", input_spec=m)
> ```
> 
> 报错：AttributeError: 'tuple' object has no attribute 'dtype'

感谢您的回复，但是我在windows和aistudio上都试了一下您的代码，还是在报那个错，，详细日志如下：
aistudio python3.7 
paddle2onnx            0.8.2          
paddlefsl              1.0.0          
paddlehub              2.0.4          
paddlenlp              2.1.0          
paddlepaddle-gpu       2.1.2.post101  
Traceback (most recent call last):
  File "toonnx.py", line 278, in <module>
    run(args)
  File "toonnx.py", line 155, in run
    paddle.onnx.export(model, "./onnx_model", input_spec=m)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/onnx/export.py", line 105, in export
    **configs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/convert.py", line 159, in dygraph2onnx
    output_spec)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/graph/paddle_graph.py", line 258, in build_from_dygraph
    layer, input_spec, output_spec)
  File "<decorator-gen-273>", line 2, in get_program
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/graph/dygraph_helper.py", line 65, in get_program
    concrete_program = layer.forward.concrete_program
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 453, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 491, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 705, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-64>", line 2, in from_func_spec
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 661, in from_func_spec
    error_data.raise_new_exception()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AttributeError: In transformed code:

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/unimo/modeling.py", line 446, in forward (* user code *)
	logits = self.lm_head(sequence_output, masked_positions)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/unimo/modeling.py", line 365, in forward (* user code *)
	hidden_states = self.transform(hidden_states)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 129, in forward
	x=input, weight=self.weight, bias=self.bias, name=self.name)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 1456, in linear
	dtype = x.dtype
    AttributeError: 'tuple' object has no attribute 'dtype'
########################
windows环境如下
paddle2onnx                       0.8.2
paddlenlp                         2.0.8
paddlepaddle-gpu                  2.1.0
windows报错如下
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Code/LCSTS_summary/run_gen.py", line 278, in <module>
    run(args)
  File "D:/Code/LCSTS_summary/run_gen.py", line 155, in run
    paddle.onnx.export(model, "./onnx_model", input_spec=m)
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\onnx\export.py", line 100, in export
    p2o.dygraph2onnx(
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle2onnx\convert.py", line 158, in dygraph2onnx
    paddle_graph = PaddleGraph.build_from_dygraph(layer, inner_input_spec,
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle2onnx\graph\paddle_graph.py", line 257, in build_from_dygraph
    program, feed_var_names, fetch_vars = dg_helper.get_program(
  File "<decorator-gen-279>", line 2, in get_program
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle2onnx\graph\dygraph_helper.py", line 65, in get_program
    concrete_program = layer.forward.concrete_program
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 454, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 487, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 698, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AttributeError: In transformed code:
    File "D:\Anaconda\envs\summ\lib\site-packages\paddlenlp\transformers\unimo\modeling.py", line 456, in forward (* user code *)
	logits = self.lm_head(sequence_output, masked_positions)
    File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "D:\Anaconda\envs\summ\lib\site-packages\paddlenlp\transformers\unimo\modeling.py", line 371, in forward (* user code *)
	hidden_states = self.transform(hidden_states)
    File "D:\Anaconda\envs\summ\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "D:\Anaconda\envs\summ\lib\site-packages\paddle\nn\layer\common.py", line 128, in forward
	out = F.linear(
    File "D:\Anaconda\envs\summ\lib\site-packages\paddle\nn\functional\common.py", line 1456, in linear
	dtype = x.dtype
    AttributeError: 'tuple' object has no attribute 'dtype'
请问是版本的问题吗？我和您那段代码现在仅有的不同就是我传参数使用的默认数据集lcsts_new和模型unimo-text-1.0了

**Comment by smallv0221** [comment]
paddle2onnx also use something like paddle.jit.to_static inside. So they encountered the same bug.

**Comment by SkipAngel** [comment]
> 两个问题： 1、想要保存unimo-text的静态图模型，使用以下代码执行的时候报错。 2、如何保存unimo-text的结构信息然后可视化模型结构，visualdl无法读取， ![image](https://user-images.githubusercontent.com/59908449/137311603-0d16aa2e-349a-4ed3-bfad-a996fe5c84fd.png)
> 
> ![image](https://user-images.githubusercontent.com/59908449/137311528-b5b081cf-408e-4388-8a22-372254e507bf.png)
> 
> * 版本、环境信息
>   1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.0.8，PaddlePaddle-gpu==2.1.0
>   2）系统环境：
>   系统类型，Windows，
>   python版本，3.8
>   复现代码如下，直接run运行即可：
>   from paddlenlp.transformers import UNIMOLMHeadModel,UNIMOTokenizer
>   import paddle
> 
> if **name** == '**main**': model = UNIMOLMHeadModel.from_pretrained("unimo-text-1.0") tokenizer = UNIMOTokenizer.from_pretrained("unimo-text-1.0") paddle.save(model, "model.pdmodel") sources = "日前，方舟子发文直指林志颖旗下爱碧丽推销假保健品，引起哗然。调查发现，爱碧丽没有自己的生产加工厂。其胶原蛋白饮品无核心研发，全部代工生产。号称有“逆生长”功效的爱碧丽“梦幻奇迹限量组”售价高达1080元，实际成本仅为每瓶4元！" inputs = tokenizer.gen_encode( sources, max_seq_len=320, max_title_len=30, add_start_token_for_decoding=True, return_position_ids=True, return_tensors=True) shape_s = [inputs['input_ids'].astype("int64").shape, inputs['token_type_ids'].astype("int64").shape, inputs['position_ids'].astype("int64").shape, inputs['attention_mask'].shape] # param_info = paddle.summary(model, input_size=shape_s, dtypes="int64") model.eval() m = [ paddle.static.InputSpec( shape=shape_s[0]), # input_ids paddle.static.InputSpec( shape=shape_s[1]), # segment_ids paddle.static.InputSpec( shape=shape_s[2]), # input_ids paddle.static.InputSpec( shape=shape_s[3]) # segment_ids ] model = paddle.jit.to_static( model, input_spec=m)
> 
> ```
> paddle.jit.save(model, "output")
> ```

https://gitee.com/paddlepaddle/Paddle2ONNX/blob/develop/examples/tutorial.ipynb   试试这个看看行不行。
