### ISSUE TITLE
使用自己制作的tsv数据集进行文本分类,训练的过程中得到如下报错,怎么破,

### ISSUE THREAD

**Issue by yizhipipixia** [PaddlePaddle/PaddleNLP#122]
项目链接:https://github.com/PaddlePaddle/models/tree/4d87afd6480737b64b5974c9c40a5b1c5a4600b3/PaddleNLP/examples/text_classification/rnn

训练命令:python train.py  --use_gpu=False --network=bilstm --lr=5e-4 --batch_size=64 --epochs=5 --save_dir='./checkpoints'

将C:\Users\Administrator\.paddlenlp\datasets\chnsenticorp目录下的train.tsv 与dev.tsv和test.tsv进行了替换,然后进行训练
训练了3步,然后就报错了,报错信息如下
step   10/4050 - loss: 0.6850 - acc: 0.5156 - 3s/step
step   20/4050 - loss: 0.6437 - acc: 0.5062 - 3s/step
step   30/4050 - loss: 0.5077 - acc: 0.5786 - 4s/step
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    save_dir=args.save_dir)
  File "F:\aanaa\lib\site-packages\paddle\hapi\model.py", line 1492, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "F:\aanaa\lib\site-packages\paddle\hapi\model.py", line 1799, in _run_one_epoch
    data[len(self._inputs):])
  File "F:\aanaa\lib\site-packages\paddle\hapi\model.py", line 940, in train_batch
    loss = self._adapter.train_batch(inputs, labels)
  File "F:\aanaa\lib\site-packages\paddle\hapi\model.py", line 654, in train_batch
    * [to_variable(x) for x in inputs])
  File "F:\aanaa\lib\site-packages\paddlenlp\models\senta.py", line 104, in forward
    logits = self.model(text, seq_len)
  File "F:\aanaa\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "F:\aanaa\lib\site-packages\paddlenlp\models\senta.py", line 186, in forward
    embedded_text = self.embedder(text)
  File "F:\aanaa\lib\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "F:\aanaa\lib\site-packages\paddle\nn\layer\common.py", line 1289, in forward
    name=self._name)
  File "F:\aanaa\lib\site-packages\paddle\nn\functional\input.py", line 202, in embedding
    'remote_prefetch', False, 'padding_idx', padding_idx)
ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 857580, but got 858057. Please check input value.
  [Hint: Expected ids[i] < row_number, but received ids[i]:858057 >= row_number:857580.] (at D:\2.0.0rc1\paddle\paddle/fluid/operators/lookup_table_v2_op.h:81)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < lookup_table_v2 > error]

**Comment by doubleyuhang** [comment]
> 你好！从报错信息来看，
> 
> > ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 857580, but got 858057. Please check input value.
> 
> 输入的word id超过了 词表范围，请检查输入word id。

ernie-1.0 模型的vacab_size与ernieTokenizer的vacab_size不一致导致embedding时出现lookup error，请问如何解决？
