### ISSUE TITLE
训练过程中常报错OSError: (External)  Cuda error(700), an illegal memory access was encountered.

### ISSUE THREAD

**Issue by rela0426** [PaddlePaddle/PaddleNLP#1238]
环境信息：
paddlepaddle2.1.2 
paddlenlp2.1.1
python3.7
linux环境

描述：
程序可以运行起来，但是在训练到一半时，常报以下错误，尤其是修改了batch_size的值。目前batch_size=1，只要修改这个值一定会报错误。有时修改别的参数，比如epoch也会报错，但有时也可以正常运行。GPU没有被占用，内存利用率也不高。我想知道是代码的问题、环境的问题还是服务器的问题，这个问题困扰我很久了，每次训练到一半都会被强制终止。
能否帮忙看一下，谢谢~
```powershell
train epoch: 2 - step: 1321 (total: 2340) - loss: 9.490997
Traceback (most recent call last):
  File "sequence_labeling.py", line 353, in <module>
    do_train()
  File "sequence_labeling.py", line 219, in do_train
    loss.backward()
  File "/data/env/conda3/envs/env1023/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/env/conda3/envs/env1023/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/env/conda3/envs/env1023/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/data/env/conda3/envs/env1023/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 239, in backward
    framework._dygraph_tracer())
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)

INFO 2021-10-26 19:01:38,701 launch_utils.py:327] terminate all the procs
ERROR 2021-10-26 19:01:38,702 launch_utils.py:584] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-10-26 19:01:41,705 launch_utils.py:327] terminate all the procs
```

**Comment by wawltor** [comment]
可以尝试把PaddlePaddle的版本升级一下，最好能升级到最新的版本

**Comment by ZHUI** [comment]
可以尝试使用 `cuda-memcheck python xxx.py` 来定位具体问题。不过这个跑起来很慢，最好是较少steps就能复现问题。

**Comment by allurelzh** [comment]
遇到同样的问题，请问解决了吗？

**Comment by rela0426** [comment]
> 遇到同样的问题，请问解决了吗？

没彻底解决呢！按照上面的办法，尝试了升级最新版本，也尝试使用cuda-memcheck，自己能力有限，没找到问题所在。昨天程序跑了一天，竟然奇迹般的没出任何问题。今天一早又重启跑了一下，就在刚才，又出现这个问题了，偶发性的，也没法贴代码复现。

**Comment by rela0426** [comment]
> 遇到同样的问题，请问解决了吗？

目前不清楚是paddle的问题，还是代码的问题。如果你找到原因，拜托一定要告诉我一下，多谢多谢~

**Comment by allurelzh** [comment]
发现问题，解决办法：https://github.com/PaddlePaddle/PaddleNLP/issues/743


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 中午1:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 训练过程中常报错OSError: (External)  Cuda error(700), an illegal memory access was encountered. (Issue #1238)





  
遇到同样的问题，请问解决了吗？
  
目前不清楚是paddle的问题，还是代码的问题。如果你找到原因，拜托一定要告诉我一下，多谢多谢~
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZHUI** [comment]
> 没彻底解决呢！按照上面的办法，尝试了升级最新版本，也尝试使用cuda-memcheck，自己能力有限，没找到问题所在。昨天程序跑了一天，竟然奇迹般的没出任何问题。今天一早又重启跑了一下，就在刚才，又出现这个问题了，偶发性的，也没法贴代码复现。

或者你加`FLAGS_benchmark=True`跑，应该比`cuda-memcheck`要快。偶发性问题，比较难定位。

**Comment by ZHUI** [comment]
@rela0426 可以说一下你使用的具体代码模型。一些输入的不合法都可能导致这种问题，可能跟上一位同学不是同一个问题。

**Comment by rela0426** [comment]
> @rela0426 可以说一下你使用的具体代码模型。一些输入的不合法都可能导致这种问题，可能跟上一位同学不是同一个问题。
paddlepaddle2.1.2
paddlenlp2.1.1
python3.7
batch_size=2

https://aistudio.baidu.com/studio/project/partial/verify/2538118/a466449d1ea141149090ede017178d1e

以上是aistudio地址，进入文件夹后的命令为
第一步：bash run_duee_1.sh data_prepare这一步没有问题

第二步：执行bash run_duee_1.sh trigger_train时，训练到step到几百的时候，报错cuda700。有时候代码执行好好的，有时候就一直报上面的错误。所以很困扰，不知道该从哪里查起。不知道能不能复现，帮忙看一下吧，多谢~~

**Comment by linonetwo** [comment]
我也遇到了

```
2|codegen  | [2022-10-12 13:26:30,159] [    INFO] - Request: {'prompt': '{\n  "name": "dewo",\n  "version": "0.1.0",\n  "private": true,\n  "scripts": {\n    "start": "craco start", ', 'stream': False}
2|codegen  | [2022-10-12 13:26:30,160] [    INFO] - Start generating code
2|codegen  | INFO:     10.200.97.73:49377 - "POST /v1/engines/codegen/completions HTTP/1.1" 500 Internal Server Error
2|codegen  | ERROR:    Exception in ASGI application
2|codegen  | Traceback (most recent call last):
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 725, in convert_to_tensors
2|codegen  |     tensor = as_tensor(value)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
2|codegen  |     return caller(func, *(extras + args), **kw)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
2|codegen  |     return wrapped_func(*args, **kwargs)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddle/fluid/framework.py", line 434, in __impl__
2|codegen  |     return func(*args, **kwargs)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddle/tensor/creation.py", line 184, in to_tensor
2|codegen  |     return paddle.Tensor(
2|codegen  | OSError: (External) CUDA error(700), an illegal memory access was encountered. 
2|codegen  |   [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:258)
2|codegen  | During handling of the above exception, another exception occurred:
2|codegen  | Traceback (most recent call last):
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
2|codegen  |     result = await app(self.scope, self.receive, self.send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
2|codegen  |     return await self.app(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
2|codegen  |     await super().__call__(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
2|codegen  |     await self.middleware_stack(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
2|codegen  |     raise exc
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
2|codegen  |     await self.app(scope, receive, _send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
2|codegen  |     raise exc
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
2|codegen  |     await self.app(scope, receive, sender)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2|codegen  |     raise e
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2|codegen  |     await self.app(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
2|codegen  |     await route.handle(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
2|codegen  |     await self.app(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
2|codegen  |     response = await func(request)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
2|codegen  |     raw_response = await run_endpoint_function(
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
2|codegen  |     return await dependant.call(**values)
2|codegen  |   File "/data00/home/-/repo/PaddleNLP/examples/code_generation/codegen/codegen_server.py", line 92, in gen
2|codegen  |     tokenized = tokenizer([item['prompt']],
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2233, in __call__
2|codegen  |     return self.batch_encode(
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2439, in batch_encode
2|codegen  |     return self._batch_encode_plus(
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 1128, in _batch_encode_plus
2|codegen  |     batch_outputs = self._batch_prepare_for_model(
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 1308, in _batch_prepare_for_model
2|codegen  |     batch_outputs = BatchEncoding(batch_outputs,
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 218, in __init__
2|codegen  |     self.convert_to_tensors(tensor_type=tensor_type,
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 734, in convert_to_tensors
2|codegen  |     raise ValueError(
2|codegen  | ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.
2|codegen  | ERROR 2022-10-12 13:26:30,169 h11_impl.py:369] Exception in ASGI application
2|codegen  | Traceback (most recent call last):
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 725, in convert_to_tensors
2|codegen  |     tensor = as_tensor(value)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
2|codegen  |     return caller(func, *(extras + args), **kw)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
2|codegen  |     return wrapped_func(*args, **kwargs)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddle/fluid/framework.py", line 434, in __impl__
2|codegen  |     return func(*args, **kwargs)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddle/tensor/creation.py", line 184, in to_tensor
2|codegen  |     return paddle.Tensor(
2|codegen  | OSError: (External) CUDA error(700), an illegal memory access was encountered. 
2|codegen  |   [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:258)
2|codegen  | During handling of the above exception, another exception occurred:
2|codegen  | Traceback (most recent call last):
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
2|codegen  |     result = await app(self.scope, self.receive, self.send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
2|codegen  |     return await self.app(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
2|codegen  |     await super().__call__(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
2|codegen  |     await self.middleware_stack(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
2|codegen  |     raise exc
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
2|codegen  |     await self.app(scope, receive, _send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
2|codegen  |     raise exc
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
2|codegen  |     await self.app(scope, receive, sender)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2|codegen  |     raise e
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2|codegen  |     await self.app(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
2|codegen  |     await route.handle(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
2|codegen  |     await self.app(scope, receive, send)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
2|codegen  |     response = await func(request)
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
2|codegen  |     raw_response = await run_endpoint_function(
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
2|codegen  |     return await dependant.call(**values)
2|codegen  |   File "/data00/home/-/repo/PaddleNLP/examples/code_generation/codegen/codegen_server.py", line 92, in gen
2|codegen  |     tokenized = tokenizer([item['prompt']],
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2233, in __call__
2|codegen  |     return self.batch_encode(
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2439, in batch_encode
2|codegen  |     return self._batch_encode_plus(
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 1128, in _batch_encode_plus
2|codegen  |     batch_outputs = self._batch_prepare_for_model(
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 1308, in _batch_prepare_for_model
2|codegen  |     batch_outputs = BatchEncoding(batch_outputs,
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 218, in __init__
2|codegen  |     self.convert_to_tensors(tensor_type=tensor_type,
2|codegen  |   File "/home/-/.local/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 734, in convert_to_tensors
2|codegen  |     raise ValueError(
2|codegen  | ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.
^C
➜  ~ pm2 start ~/tryPaddle.sh --name codegen             
➜  ~ nvidia-smi
Wed Oct 12 13:27:54 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:06.0 Off |                    0 |
| N/A   50C    P0    26W /  70W |  14046MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1712696      C   /usr/local/bin/python3.9        14043MiB |
+-----------------------------------------------------------------------------+
```

**Comment by linonetwo** [comment]
我是运行模型的时候，一开始几小时是好的，隔夜就不行了，一开始还以为是系统管理员会定期把GPU挪给别人复用导致的，但看来还是别的问题？

目前先通过每天凌晨重启解决 pm2 restart all --cron-restart="0 0 * * *"

---

这个报错出现很频繁，可能一小时就得重启一次了。

---

 CUDA failure: an illegal memory access was encountered​
​
可能原因：部分服务可能会配置有自动bathching的功能，pad默认一般是未初始化的内存，对于Transformer类模型可能会导致encoder出错。​
解决办法：可以尝试加入环境变量，QS_RUNTIME_PAD_INT_ZERO=1

**Comment by Tygors** [comment]
> 

请问你说的这个环境变量QS_RUNTIME_PAD_INT_ZERO怎么设置啊？

**Comment by Tygors** [comment]
> 我是运行模型的时候，一开始几小时是好的，隔夜就不行了，一开始还以为是系统管理员会定期把GPU挪给别人复用导致的，但看来还是别的问题？
> 
> 目前先通过每天凌晨重启解决 pm2 restart all --cron-restart="0 0 * * *"
> 
> 这个报错出现很频繁，可能一小时就得重启一次了。
> 
> CUDA failure: an illegal memory access was encountered​​可能原因：部分服务可能会配置有自动bathching的功能，pad默认一般是未初始化的内存，对于Transformer类模型可能会导致encoder出错。​解决办法：可以尝试加入环境变量，QS_RUNTIME_PAD_INT_ZERO=1

请问你说的这个环境变量QS_RUNTIME_PAD_INT_ZERO 怎么设置啊？在哪里设置

**Comment by linonetwo** [comment]
就在 shell 里 export

**Comment by michelle-chou25** [comment]
我刚装好paddlepaddle，就两行语句就出现了，百分百浮现
import paddle
paddle.utils.run_check()
环境ccentos7.9
python3.9
cudatoolkit 11.2
paddlepaddle 2.4.1 
conda install paddlepaddle-gpu==2.4.1 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 
崭新的conda环境，没有任何包冲突.
