### ISSUE TITLE
PaddleNLP/examples/text_generation/ernie-gen/训练出错

### ISSUE THREAD

**Issue by orlando1986** [PaddlePaddle/PaddleNLP#1252]
在使用example训练的时候出现崩溃

PaddlePaddle 2.1.2
paddlenlp 2.1.1

我设置了max encode length和max decode length都是512，batch=8，在186步的时候就报错了。把max encode length和max decode length都设500，batch=8，在604步报错

用aistudio上的教学代码就没问题，https://aistudio.baidu.com/aistudio/projectdetail/1339888
所以应该不是数据集的问题，请看一下github上的example是不是用不了？

我的aistudio项目在https://aistudio.baidu.com/aistudio/projectdetail/2510297?contributionType=1&shared=1

Traceback (most recent call last):
File "/home/aistudio/work/ernie_gen/train.py", line 271, in
train()
File "/home/aistudio/work/ernie_gen/train.py", line 242, in train
tgt_labels, tgt_pos)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in call
outputs = self.forward(*inputs, **kwargs)
File "/home/aistudio/work/ernie_gen/model.py", line 41, in forward
encode_only=True)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in call
outputs = self.forward(*inputs, **kwargs)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/ernie_gen/modeling.py", line 651, in forward
encoded, info = ErnieModel.forward(self, *args, **kwargs)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/ernie_gen/modeling.py", line 558, in forward
sent_embedded = self.sent_emb(sent_ids)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in call
outputs = self.forward(*inputs, **kwargs)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 1358, in forward
name=self._name)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/input.py", line 200, in embedding
'remote_prefetch', False, 'padding_idx', padding_idx)
OSError: (External) Cuda error(719), unspecified launch failure.
[Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)
[operator < lookup_table_v2 > error]
========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to "unspecified launch failure" on CUDA API call to cuModuleUnload.
========= Saved host backtrace up to driver entry point at error
========= Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuModuleUnload + 0x162) [0x25a722]
========= Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa87a0f]
========= Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa88d50]
========= Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa8dbf7]
========= Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa8e012]
========= Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa7f2b6]
========= Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa7fae5]
========= Host Frame:/lib/x86_64-linux-gnu/libc.so.6 [0x39ff8]
========= Host Frame:/lib/x86_64-linux-gnu/libc.so.6 [0x3a045]
========= Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf7) [0x20837]
========= Host Frame:python [0x1db062]

**Comment by ZHUI** [comment]
![image](https://user-images.githubusercontent.com/16911935/139393593-cced0ca2-b728-4ed9-a397-4b369d94c1b7.png)
要不QQ交流一下？

**Comment by orlando1986** [comment]
> ![image](https://user-images.githubusercontent.com/16911935/139393593-cced0ca2-b728-4ed9-a397-4b369d94c1b7.png) 要不QQ交流一下？

加了群了，但是不知道哪个是你，提问了也没人回答

**Comment by orlando1986** [comment]
> ![image](https://user-images.githubusercontent.com/16911935/139393593-cced0ca2-b728-4ed9-a397-4b369d94c1b7.png) 要不QQ交流一下？

大佬，你的项目能分享我一下吗，我看看和我的有什么不同，为什么你跑的就没问题我的就不行
