### ISSUE TITLE
Taskflow 情感分析官方例子报错

### ISSUE THREAD

**Issue by changaolee** [PaddlePaddle/PaddleNLP#1311]
## 版本、环境信息

1. PaddleNLP 和 PaddlePaddle版本：PaddleNLP 2.1.1，PaddlePaddle 2.2.0
2. 系统环境：MacOS 12.0.1，python 3.7

## 报错代码

```python
from paddlenlp import Taskflow

senta = Taskflow("sentiment_analysis")
senta("怀着十分激动的心情放映，可是看着看着发现，在放映完毕后，出现一集米老鼠的动画片")
```

## 报错信息

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    senta("怀着十分激动的心情放映，可是看着看着发现，在放映完毕后，出现一集米老鼠的动画片")
  File "venv/lib/python3.7/site-packages/paddlenlp/taskflow/taskflow.py", line 214, in __call__
    results = self.task_instance(inputs)
  File "venv/lib/python3.7/site-packages/paddlenlp/taskflow/task.py", line 167, in __call__
    outputs = self._run_model(inputs)
  File "venv/lib/python3.7/site-packages/paddlenlp/taskflow/sentiment_analysis.py", line 192, in _run_model
    probs = self.output_handle[1].copy_to_cpu().tolist()
IndexError: list index out of range
```

**Comment by changaolee** [comment]
补充：PaddleNlp 2.0.x 是可以跑通的，但由于需要 score 值做进一步处理，因此必须用 2.1.x 才可以

**Comment by linjieccc** [comment]
您好，这里应该是用到了2.0.x版本的情感分析静态图模型参数，
可以先删除`$HOME/.paddlenlp/taskflow/sentiment_analysis/bilstm/static`目录，
然后使用PaddleNLP 2.1.1重新初始化任务
```python
from paddlenlp import Taskflow

senta = Taskflow("sentiment_analysis")
```

**Comment by changaolee** [comment]
> 您好，这里应该是用到了2.0.x版本的情感分析静态图模型参数， 可以先删除`$HOME/.paddlenlp/taskflow/sentiment_analysis/bilstm/static`目录， 然后使用PaddleNLP 2.1.1重新初始化任务
> 
> ```python
> from paddlenlp import Taskflow
> 
> senta = Taskflow("sentiment_analysis")
> ```

确实是这个问题，正常运行啦~
