### ISSUE TITLE
导出模型后结果异常

### ISSUE THREAD

**Issue by fly2008begin** [PaddlePaddle/PaddleNLP#1394]
您好
环境：PaddleNLP 2.0.0  PaddlePaddle2.2.0  ubuntu18.04 rtx2080Ti  cuDNN Version: 7.6
在复现PaddleNLP/examples/information_extraction/waybill_ie “快递单信息抽取 (Waybill Information Extraction)”时遇到了导出模型不可用的情况，具体操作步骤如下：
```
python3 download.py
python3 run_bigru_crf.py
```
结果输出正常
```
('黑龙江省', 'A1')('双鸭山市', 'A2')('尖山区', 'A3')('八马路与东平行路交叉口北40米韦业涛', 'A4')('18600009172', 'T')
('广西壮族自治区', 'A1')('桂林市', 'A2')('雁山区', 'A3')('雁山镇西龙村老年活动中心', 'A4')('17610348888', 'T')('羊卓卫', 'P')
...
```
尝试将模型导出
```
python3 export_model.py --params_path bigru_crf_ckpt/model_80 --output_path=./output
python3 deploy/python/predict.py --model_dir ./output
```
结果输出变成了
```
('黑', 'O')('龙', 'O')('江', 'P')('省', 'O')('双鸭山', 'O')('市', 'O')('尖', 'T')('山区', 'A4')('八马', 'O')('路', 'O')('与', 'O')('东平', 'O')('行', 'O')('路', 'O')('交', 'O')('叉口', 'O')('北', 'O')('40米韦业涛1860000', 'O')('9172', 'O')
('广', 'O')('西壮族自治区', 'A1')('桂', 'A4')('林市', 'A4')('雁', 'A4')('山区', 'A4')('雁', 'P')('山镇西', 'O')('龙村', 'O')('老', 'O')('年活', 'O')('动中心17610348888', 'A4')('羊', 'O')('卓卫', 'O')
...
```
我是哪里做错了吗？
另外我用自己关注的信息标注了训练了同样的模型，导出后同样有问题。
我看deploy/python/predict.py 里面读的也是test.txt ,我想尝试用没有标注的句子改怎么办？工程使用时应该怎么嵌入我的项目中？有例子吗。

**Comment by joey12300** [comment]
@fly2008begin 您好，感谢关注PaddleNLP。这里主要是导出模型时模型参数路径有误，没有成功导入参数，导致参数随机初始化，应该输入完整的pdparams文件路径，如下图所示：
![image](https://user-images.githubusercontent.com/10826371/144954591-9d26e382-c6ec-4e77-989b-ed3bb7b58d9e.png)

导出的脚本确实没有足够的提示纠正错误输入，后面会添加warning提示用户正确输入参数文件路径问题。

**Comment by fly2008begin** [comment]
> @fly2008begin 您好，感谢关注PaddleNLP。这里主要是导出模型时模型参数路径有误，没有成功导入参数，导致参数随机初始化，应该输入完整的pdparams文件路径，如下图所示： ![image](https://user-images.githubusercontent.com/10826371/144954591-9d26e382-c6ec-4e77-989b-ed3bb7b58d9e.png)
> 
> 导出的脚本确实没有足够的提示纠正错误输入，后面会添加warning提示用户正确输入参数文件路径问题。

我尝试了使用
```
python3 export_model.py --params_path bigru_crf_ckpt/model_80/model_state.pdparams --output_path=./output
```
但感觉结果依旧不正确
```
python3 deploy/python/predict.py --model_dir ./output
```
```
('黑', 'T')('龙江', 'A1')('省双', 'A4')('鸭', 'A3')('山市', 'T')('尖', 'T')('山', 'T')('区八', 'T')('马', 'A1')('路', 'A3')('与东平行', 'T')('路', 'A3')('交', 'A3')('叉口', 'A3')('北', 'P')('40', 'A4')('米', 'P')('韦', 'T')('业', 'P')('涛', 'P')('1', 'P')('8', 'A3')('6', 'A3')('0', 'A3')('0', 'A3')('0', 'A3')('0', 'A3')('9', 'T')('1', 'P')('72', 'T')
...
```

**Comment by joey12300** [comment]
目前示例代码中deploy/python/predict.py只支持ernie作为backbone，里面使用的是Ernie的词表。如果想使用GRU做预测，需要修改词处理逻辑。可以参考run_bigru_crf.py的词处理逻辑。

**Comment by fly2008begin** [comment]
> 目前示例代码中deploy/python/predict.py只支持ernie作为backbone，里面使用的是Ernie的词表。如果想使用GRU做预测，需要修改词处理逻辑。可以参考run_bigru_crf.py的词处理逻辑。

上面的结果现象均为官方实例，并没有自己修改词表或训练集，在run_bigru_crf.py时结果观察正常，但deploy/python/predict.py就分的没法用。

**Comment by fly2008begin** [comment]
> 目前示例代码中deploy/python/predict.py只支持ernie作为backbone，里面使用的是Ernie的词表。如果想使用GRU做预测，需要修改词处理逻辑。可以参考run_bigru_crf.py的词处理逻辑。

好的 谢谢您 我去读一遍deploy/python/predict.py

**Comment by Eric-Zhang1990** [comment]
@joey12300  我用的run_ernie_crf.py训练的，训练完预测结果是对的
<img width="374" alt="121" src="https://user-images.githubusercontent.com/24602893/156280365-d6e7532d-209e-4f88-bd8c-04fad927c835.png">
但是本地用export_model.py导出静态模型后，用deploy/python/predict.py预测，结果错的
<img width="561" alt="122" src="https://user-images.githubusercontent.com/24602893/156280624-8f65b7ca-e4a1-4ac8-8b8b-e1cd7e5b85b4.png">
<img width="594" alt="123" src="https://user-images.githubusercontent.com/24602893/156280999-c585ca25-b6ee-4a3b-9c89-ca4d5eddc32b.png">

训练环境：paddlenlp==2.2.4  paddlepaddle-gpu==2.1.2.post112
测试环境：paddlenlp==2.2.4  paddlepaddle==2.1.2

**Comment by Eric-Zhang1990** [comment]
@joey12300  我用训练代码中的预测方式，直接加载model_state.pdparams（不用export_model导出），预测结果是对的，能帮忙排查一些export_model后用deploy/python/predict.py预测，结果是错的原因呢？谢谢
<img width="410" alt="125" src="https://user-images.githubusercontent.com/24602893/156289054-bd7221cb-788a-4555-8665-0fb231f81ad4.png">
<img width="459" alt="124" src="https://user-images.githubusercontent.com/24602893/156289063-6defc1c6-592f-464f-a8b3-da0f637ea261.png">

**Comment by joey12300** [comment]
@Eric-Zhang1990 您好，waybill目录下提供的export_model.py是一个示例，只支持`ErnieForTokenClassification`，即run_ernie.py所训练的模型；而您使用的run_ernie_crf.py，训练的是`ErnieCrfForTokenClassification`模型。如果想导出该模型，需要修改export_model.py，将`ErnieForTokenClassification`改为`ErnieCrfForTokenClassification`。

**Comment by Eric-Zhang1990** [comment]
@joey12300  您好，我把ErnieForTokenClassification改为ErnieCrfForTokenClassification：
model = ppnlp.transformers.ErnieForTokenClassification.from_pretrained(
        "ernie-1.0", num_classes=len(label_vocab))
    model = ErnieCrfForTokenClassification(model)
但是出现issue[https://github.com/PaddlePaddle/PaddleNLP/issues/911](url) 一样的问题，我按照这个issue修改：
    # model = paddle.jit.to_static(
    #     model,
    #     input_spec=[
    #         paddle.static.InputSpec(
    #             shape=[None, None], dtype="int64"),  # input_ids
    #         paddle.static.InputSpec(
    #             shape=[None, None], dtype="int64")  # segment_ids
    #     ])

    model = paddle.jit.to_static(
        model,
        input_spec=[
            paddle.static.InputSpec(
                shape=[None, None], dtype="int64"),  # input_ids
            paddle.static.InputSpec(
                shape=[None, None], dtype="int64"),  # segment_ids
            paddle.static.InputSpec(
                shape=[None], dtype="int64")  # length
        ])
还是出现错误：
Loaded parameters from ./ernie_crf_ckpt/model_160/model_state.pdparams
Traceback (most recent call last):
  File "D:/project/github/PaddleNLP/examples/information_extraction/waybill_ie/export_model.py", line 69, in <module>
    paddle.jit.save(model, save_path)
  File "<decorator-gen-66>", line 2, in save
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\jit.py", line 726, in save
    inner_input_spec)
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 491, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 705, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-64>", line 2, in from_func_spec
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 661, in from_func_spec
    error_data.raise_new_exception()
  File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AttributeError: In transformed code:

    File "C:\Users\zhangsfm\AppData\Local\Temp\tmphgzc7on_.py", line 32, in forward
	__return_value_0,))
    File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
	return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\project\github\PaddleNLP\examples\information_extraction\waybill_ie\model.py", line 90, in forward (* user code *)
	_, prediction = self.viterbi_decoder(logits, lengths)
    File "D:\software\miniconda3\envs\ppocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "D:\project\github\PaddleNLP\paddlenlp\layers\crf.py", line 385, in forward (* user code *)
	left_length = lengths.clone()
    AttributeError: 'NoneType' object has no attribute 'clone'

Process finished with exit code 1
麻烦帮忙解决一下，谢谢

**Comment by joey12300** [comment]
@Eric-Zhang1990 这里其实需要改两个地方，一个是export_model.py，一个是predict.py。

## 模型导出修改方法
![image](https://user-images.githubusercontent.com/10826371/156317385-f6ccde42-6822-44e7-8e99-956c1325cac9.png)

## 模型预测方法
![image](https://user-images.githubusercontent.com/10826371/156317320-f00d0197-d1d0-4314-a1de-74ca4f5c17eb.png)

**Comment by Eric-Zhang1990** [comment]
@joey12300  问题解决了，谢谢

**Comment by joey12300** [comment]
@Eric-Zhang1990 可以升级最新版本的Paddle，CRF解码部分在Paddle2.2之后得到比较大的性能提升
