### ISSUE TITLE
ChineseBERT Chn任务finetune报错，缺少pypinyin

### ISSUE THREAD

**Issue by LuckyyySTA** [PaddlePaddle/PaddleNLP#1521]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.2.1，PaddlePaddle-gpu 2.2.1
2）系统环境：Linux  python3.8
-问题报错：缺少pypinyin.pinyin
运行run_chn脚本报错如下：
Traceback (most recent call last):
  File "/users/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/utils/lazy_import.py", line 32, in try_import
    mod = importlib.import_module(module_name)
  File "/users/miniconda3/envs/paddle/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pypinyin.pinyin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_chn.py", line 147, in <module>
    train_data_loader = create_dataloader(
  File "/users/PaddleNLP/examples/language_model/chinesebert/utils.py", line 133, in create_dataloader
    dataset = dataset.map(trans_fn, lazy=False)
  File "/users/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/datasets/dataset.py", line 321, in map
    return self._map(fn, lazy=lazy, batched=batched)
  File "/users/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/datasets/dataset.py", line 329, in _map
    self.new_data = [
  File "/users/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/datasets/dataset.py", line 330, in <listcomp>
    fn(self.new_data[idx]) for idx in range(len(self.new_data))
  File "train_chn.py", line 119, in convert_example
    encoded_inputs = tokenizer(text=example["text"], max_seq_len=max_seq_length)
  File "/users/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 377, in __call__
    return self.encode(
  File "/users/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/chinesebert/tokenizer.py", line 314, in encode
    encoded_inputs["pinyin_ids"] = self.get_pinyin_ids(text, text_pair,
  File "/users/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/chinesebert/tokenizer.py", line 778, in get_pinyin_ids
    text_pinyin_locs = self.pinyin_locs_map(text)
  File "/users/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/chinesebert/tokenizer.py", line 734, in pinyin_locs_map
    pinyin = try_import("pypinyin.pinyin")
  File "/users/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/utils/lazy_import.py", line 40, in try_import
    raise ImportError(err_msg)
ImportError: Failed importing pypinyin.pinyin. This likely means that some paddle modules require additional dependencies that have to be manually installed (usually with `pip install pypinyin`). 

根据提示是chinesebert需要提前安装pypinyin，但是在运行之前我已经根据requirement.txt安装好了pypinyin，检查conda环境的pip list发现的确已经安装了

**Comment by LuckyyySTA** [comment]
debug之后发现，transformers库中chinesebert的tokenizer部分的以下两行代码（724、735行）在我电脑环境下没有起作用：
pinyin = try_import("pypinyin.pinyin")
Style = try_import("pypinyin.Style")
我加上from pypinyin import pinyin，Style之后好使了

**Comment by gongel** [comment]
你好，看你已经解决问题，那这边先关闭issue了哈，后续有问题可重开issue

**Comment by LuckyyySTA** [comment]
好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gongenlei ***@***.***&gt;
发送时间: 2021年12月30日 12:24
收件人: PaddlePaddle/PaddleNLP ***@***.***&gt;
抄送: init ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleNLP] ChineseBERT Chn任务finetune报错，缺少pypinyin (Issue #1521)





 
你好，看你已经解决问题，那这边先关闭issue了哈，后续有问题可重开issue
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ylggx** [comment]
666
