### ISSUE TITLE
t5模型运行示例代码出错

### ISSUE THREAD

**Issue by baidu-chenwenyu** [PaddlePaddle/PaddleNLP#1650]
测试代码
import paddle
from paddlenlp.transformers import T5Model, T5Tokenizer
tokenizer = T5Tokenizer.from_pretrained('t5-base')
model = T5Model.from_pretrained('t5-base')
inputs = tokenizer("Welcome to use PaddlePaddle and PaddleNLP!")
inputs = {k:paddle.to_tensor([v]) for (k, v) in inputs.items()}
outputs = model(**inputs)

报错信息
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    outputs = model(**inputs)
  File "/usr/local/lib64/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/paddlenlp/transformers/t5/modeling.py", line 1348, in forward
    decoder_outputs = self.decoder(
  File "/usr/local/lib64/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/paddlenlp/transformers/t5/modeling.py", line 908, in forward
    assert input_ids is not None, "input_ids can not be None"

代码版本
paddlenlp              2.2.0
paddlepaddle           2.2.2

**Comment by guoshengCS** [comment]
文档中的示例代码有些问题，抱歉造成困扰，T5的话还需要输入个`decoder_input_ids`，示例代码中只提供了`input_ids`，如果只说跑通的话将最后一句`outputs = model(**inputs)`改为`outputs = model(**inputs, decoder_input_ids= inputs["input_ids"])`就可以了，实际的T5使用示例还请参考这里 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/t5

**Comment by yingyibiao** [comment]
#1652  已修复～

**Comment by baidu-chenwenyu** [comment]
> 
decoder_input_ids在注释里面依然写的是optional，且有默认值None，如果下游必须有这个值，那么decoder_input_ids要么就应该能自动生成（而且注释中的确说了可以），要么的确需要用户提供这个参数，decoder_input_ids就不应该是optional的。
