### ISSUE TITLE
paddlenlp examples/language_model/bert/run_pretrain.py加载中途保存模型异常

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleNLP#177]
由于一些原因，中途训练断开了，最后一个保存的路径在model_240000中，有如下一些文件
model_config.json
model_state.pdparams
tokenizer_config.json
vocab.txt
model_state.pdopt

然后用run_pretrain.py加载继续训练，参数--model_name_or_path 无论是加载路径还是pdparams都不行

加载路径--model_name_or_path /home/aistudio/work/pretrained_models/model_240000的异常如下
Traceback (most recent call last):
  File "/home/aistudio/PaddleNLP-release-2.0-rc/examples/language_model/bert/run_pretrain.py", line 434, in <module>
    do_train(args)
  File "/home/aistudio/PaddleNLP-release-2.0-rc/examples/language_model/bert/run_pretrain.py", line 295, in do_train
    args.model_name_or_path]))
KeyError: '/home/aistudio/work/pretrained_models/model_240000/'
INFO 2021-03-22 11:46:07,231 launch_utils.py:307] terminate all the procs
ERROR 2021-03-22 11:46:07,231 launch_utils.py:545] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-03-22 11:46:10,234 launch_utils.py:307] terminate all the procs

加载模型--model_name_or_path /home/aistudio/work/pretrained_models/model_240000/model_state.pdparams 异常如下
Traceback (most recent call last):
  File "/home/aistudio/PaddleNLP-release-2.0-rc/examples/language_model/bert/run_pretrain.py", line 434, in <module>
    do_train(args)
  File "/home/aistudio/PaddleNLP-release-2.0-rc/examples/language_model/bert/run_pretrain.py", line 291, in do_train
    tokenizer = tokenizer_class.from_pretrained(args.model_name_or_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 337, in from_pretrained
    cls.__name__, cls.pretrained_init_configuration.keys()))
ValueError: Calling BertTokenizer.from_pretrained() with a model identifier or the path to a directory instead. The supported model identifiers are as follows: dict_keys(['bert-base-uncased', 'bert-large-uncased', 'bert-base-cased', 'bert-large-cased', 'bert-base-multilingual-uncased', 'bert-base-multilingual-cased', 'bert-base-chinese', 'bert-wwm-chinese', 'bert-wwm-ext-chinese'])
INFO 2021-03-22 11:46:53,729 launch_utils.py:307] terminate all the procs
ERROR 2021-03-22 11:46:53,729 launch_utils.py:545] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-03-22 11:46:56,732 launch_utils.py:307] terminate all the procs

这个似乎只能用预设好的model_name？如bert-large-uncased一类？

**Comment by wawltor** [comment]
您好，上诉的问题是我们的一处代码所致，目前已经修复合入最新的develop版本，抱歉给您使用的过程中带来困扰，具体的修复PR https://github.com/PaddlePaddle/PaddleNLP/pull/180 。您可以通过拉取最新的bert的示例代码即可修复上诉的问题。

**Comment by bbbxixixixi** [comment]
> 您好，上诉的问题是我们的一处代码所致，目前已经修复合入最新的develop版本，抱歉给您使用的过程中带来困扰，具体的修复PR #180 。您可以通过拉取最新的bert的示例代码即可修复上诉的问题。

这个稍微有点小问题，当加载某个保存路径下的模型，如果不存在.paddlenlp/models/xxx/xxx-vocab.txt的时候，还是会报异常

我重新进入aistudio，这时候的环境是初始状态，用--model_name_or_path /home/aistudio/work/pretrained_models/model_240000/加载模型，异常如下
Traceback (most recent call last):
  File "/home/aistudio/PaddleNLP-develop/examples/language_model/bert/run_pretrain.py", line 439, in <module>
    do_train(args)
  File "/home/aistudio/PaddleNLP-develop/examples/language_model/bert/run_pretrain.py", line 291, in do_train
    tokenizer = tokenizer_class.from_pretrained(args.model_name_or_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 370, in from_pretrained
    tokenizer = cls(*init_args, **init_kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/utils.py", line 83, in __impl__
    init_func(self, *args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/bert/tokenizer.py", line 317, in __init__
    .format(vocab_file))
ValueError: Can't find a vocabulary file at path '/home/aistudio/.paddlenlp/models/bert-wwm-ext-chinese/bert-wwm-ext-chinese-vocab.txt'. To load the vocabulary from a pretrained model please use `tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)`
INFO 2021-03-23 02:05:09,685 launch_utils.py:307] terminate all the procs
ERROR 2021-03-23 02:05:09,686 launch_utils.py:545] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-03-23 02:05:12,689 launch_utils.py:307] terminate all the procs

如果.paddlenlp存在vocab的话，就不会出现这种事。不过我看模型保存路径下已经存了一个vocab文件，这个时候按照习惯，似乎应该读取保存路径model_240000下的vocab，供参考

**Comment by wawltor** [comment]
嗯嗯 谢谢反馈这个问题， 我们内部如何处理这个问题，问题解决后再反馈给您！

**Comment by guoshengCS** [comment]
现在这个问题已经修复了哈 https://github.com/PaddlePaddle/PaddleNLP/pull/106

**Comment by bbbxixixixi** [comment]
> 现在这个问题已经修复了哈 #106

还有一个有问题的地方，今早去看训练情况，发现global step不是承接上次中断的地方一起的，上次从240000steps处继续，今早最后保存的是200000。不太确定lr之类的是不是也从0步开始计算了，建议在log中打印一下

**Comment by wawltor** [comment]
> > 现在这个问题已经修复了哈 #106
> 
> 还有一个有问题的地方，今早去看训练情况，发现global step不是承接上次中断的地方一起的，上次从240000steps处继续，今早最后保存的是200000。不太确定lr之类的是不是也从0步开始计算了，建议在log中打印一下
