### ISSUE TITLE
tokenizer batch和非batch对非法字符的处理不一致

### ISSUE THREAD

**Issue by baidu-chenwenyu** [PaddlePaddle/PaddleNLP#1775]
错误代码
from paddlenlp.transformers import ErnieTokenizer
tokenizer = ErnieTokenizer.from_pretrained("ernie-tiny")
a =  '\ue816'
res = tokenizer(a)
print(res)
a =  ['\ue816']
res = tokenizer(a)

第一个可以执行
第二个会报错

错误信息
{'input_ids': [3, 5], 'token_type_ids': [0, 0]}
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    res = tokenizer(a)
  File "/home/chenwenyu/miniconda3/envs/dev/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 613, in __call__
    return self.batch_encode(
  File "/home/chenwenyu/miniconda3/envs/dev/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 1701, in batch_encode
    self.encode(
  File "/home/chenwenyu/miniconda3/envs/dev/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 1362, in encode
    ids = get_input_ids(text)
  File "/home/chenwenyu/miniconda3/envs/dev/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 1358, in get_input_ids
    raise ValueError(
ValueError: Input is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.

环境 paddlenlp2.2.4

**Comment by smallv0221** [comment]
感谢您的反馈，很抱歉给您带来不便，我们会尽快修复这个bug

**Comment by smallv0221** [comment]
您好，这个bug现已修复，可以拉最新版本的develop试一下
