### ISSUE TITLE
[kunlun]运行paddlenlp中的bert程序时，报shape错误，具体如下：

### ISSUE THREAD

**Issue by 1chang37** [PaddlePaddle/PaddleNLP#1813]
```python
[root@localhost PaddleNLP]# ls
benchmark  build  dist  docs  examples  legacy  LICENSE  paddlenlp  paddlenlp.egg-info  README_en.md  README.md  requirements.txt  setup.py  tests  tutorials
[root@localhost PaddleNLP]# cd benchmark/bert/
[root@localhost bert]# ls
api_detail         data.py             one_pd_log  __pycache__  run_bert_finetune.sh  run_pretrain_multi.py  run_pretrain.sh
bert_finetune.log  get_kernel_time.py  op_debug    README.md    run_glue.py           run_pretrain.py        run_pretrain_single.py
[root@localhost bert]# bash run_bert_finetune.sh 
XPURT /usr/local/lib64/python3.7/site-packages/paddle/fluid/../libs/libxpurt.so loaded
[2022-03-22 08:22:27,397] [    INFO] - Found /root/.paddlenlp/models/bert-base-uncased/bert-base-uncased-vocab.txt
[2022-03-22 08:22:27,958] [    INFO] - Already cached /root/.paddlenlp/models/bert-base-uncased/bert-base-uncased.pdparams
/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for classifier.weight. classifier.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for classifier.bias. classifier.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib64/python3.7/site-packages/paddle/fluid/framework.py:744: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
/usr/local/lib64/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /usr/local/lib/python3.7/site-packages/paddlenlp/transformers/bert/modeling.py:58
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/lib64/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /usr/local/lib/python3.7/site-packages/paddlenlp/transformers/bert/modeling.py:67
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/lib64/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /usr/local/lib64/python3.7/site-packages/paddle/nn/layer/transformer.py:411
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/lib64/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /usr/local/lib64/python3.7/site-packages/paddle/nn/layer/transformer.py:587
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/lib64/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /usr/local/lib64/python3.7/site-packages/paddle/nn/layer/transformer.py:595
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/lib64/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /usr/local/lib64/python3.7/site-packages/paddle/metric/metrics.py:270
The behavior of expression A == B has been unified with equal(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use equal(X, Y, axis=0) instead of A == B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
W0322 08:22:37.696290  6339 device_context.cc:221] Please NOTE: xpu device: 0
Traceback (most recent call last):
  File "./run_glue.py", line 452, in <module>
    do_train(args)
  File "./run_glue.py", line 416, in do_train
    paddle.static.set_program_state(main_program, reset_state_dict)
  File "<decorator-gen-123>", line 2, in set_program_state
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/framework.py", line 238, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/io.py", line 2371, in set_program_state
    .format(orig_para_np.shape, para.name, new_para_np.shape)
AssertionError: Parameter's shape does not match, the Program requires a parameter with the shape of ((30522, 768)), while the loaded parameter (namely [ embedding_0.w_0 ]) has a shape of  (<bound method PyCapsule.shape of <paddle.fluid.core_noavx.LoDTensor object at 0xfffdc53bfa30>>).
[root@localhost bert]# 
```

**Comment by ZHUI** [comment]
```python
Traceback (most recent call last):
  File "./run_glue.py", line 452, in <module>
    do_train(args)
  File "./run_glue.py", line 416, in do_train
    paddle.static.set_program_state(main_program, reset_state_dict)
  File "<decorator-gen-123>", line 2, in set_program_state
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/framework.py", line 238, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/io.py", line 2371, in set_program_state
    .format(orig_para_np.shape, para.name, new_para_np.shape)
AssertionError: Parameter's shape does not match, the Program requires a parameter with the shape of ((30522, 768)), while the loaded parameter (namely [ embedding_0.w_0 ]) has a shape of  (<bound method PyCapsule.shape of <paddle.fluid.core_noavx.LoDTensor object at 0xfffdc53bfa30>>).
```
看起来是这里参数加载出现的问题:

1. 这个 finetune 的代码你修改过吗？尤其是这里`paddle.static.set_program_state(main_program, reset_state_dict)`
2. 直接跑 gpu 也会出现类似情况吗？
3. paddle的版本是不是比较老？换新一点的develop试一试？

**Comment by 1chang37** [comment]
谢谢！
1、没有修改过
2、只跑了xpu
3、paddle版本使用的2.2.0
还有啥其他的建议么？




> ```python
> Traceback (most recent call last):
>   File "./run_glue.py", line 452, in <module>
>     do_train(args)
>   File "./run_glue.py", line 416, in do_train
>     paddle.static.set_program_state(main_program, reset_state_dict)
>   File "<decorator-gen-123>", line 2, in set_program_state
>   File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
>     return wrapped_func(*args, **kwargs)
>   File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/framework.py", line 238, in __impl__
>     return func(*args, **kwargs)
>   File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/io.py", line 2371, in set_program_state
>     .format(orig_para_np.shape, para.name, new_para_np.shape)
> AssertionError: Parameter's shape does not match, the Program requires a parameter with the shape of ((30522, 768)), while the loaded parameter (namely [ embedding_0.w_0 ]) has a shape of  (<bound method PyCapsule.shape of <paddle.fluid.core_noavx.LoDTensor object at 0xfffdc53bfa30>>).
> ```
> 
> 看起来是这里参数加载出现的问题:
> 
> 1. 这个 finetune 的代码你修改过吗？尤其是这里`paddle.static.set_program_state(main_program, reset_state_dict)`
> 2. 直接跑 gpu 也会出现类似情况吗？
> 3. paddle的版本是不是比较老？换新一点的develop试一试？

**Comment by ZHUI** [comment]
1. 使用最新的 paddlenlp代码 和 最新paddle版本 试一下
2. 在GPU环境尝试，看是否也有这个问题。

就这两个吧
