### ISSUE TITLE
英文等小语种的地址如何标注BIO方式

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleNLP#1887]
场景是地址信息抽取。中文按照way_bill_ie例子data，我看了。但是英文这种怎么标注？street aa,district bb,state cc。是把一个单词一个单词的标注吗？空格是怎么处理？不处理空格，只把标点写成O吗？S-B S-I O D-B D-I O E-B E-I.

**Comment by gongel** [comment]
英文一般是按单词标注，空格可以预处理掉，也可以标O

**Comment by xiangfeidecao** [comment]
> 

谢谢回复，如果训练样本中空格都删除，那预测的时候也要把所有的空格删除吗？还有我在其他issue中看到说把空格变成\002来标注。

**Comment by gongel** [comment]
预测阶段和训练阶段保持一致，如果删除空格的话都删除

**Comment by xiangfeidecao** [comment]
> 预测阶段和训练阶段保持一致，如果删除空格的话都删除

再请教下，环境是 paddlepaddle 2.0.2,paddlenlp2.0.0-我自己标注了越南文的地址信息，在way_bill_ie下面直接更新了data,conf.但是训练时提示
/home/hk/.conda/envs/Paddle/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
W0406 17:19:43.988787 14034 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.0
W0406 17:19:43.991132 14034 device_context.cc:372] device: 0, cuDNN Version: 8.0.
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/10
2022-04-06 17:19:45,861 - WARNING - DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "run_bigru_crf.py", line 175, in <module>
    log_freq=1)
  File "/home/hk/.conda/envs/Paddle/lib/python3.7/site-packages/paddle/hapi/model.py", line 1495, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/home/hk/.conda/envs/Paddle/lib/python3.7/site-packages/paddle/hapi/model.py", line 1779, in _run_one_epoch
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/hk/.conda/envs/Paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/hk/.conda/envs/Paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hk/.conda/envs/Paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 346, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/home/hk/.conda/envs/Paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/hk/.conda/envs/Paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 330, in _thread_loop
    tmp.set(slot, core.CPUPlace())
ValueError: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:355)


    for step, data in enumerate(data_loader):
  File "/home/hk/.conda/envs/Paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
在paddlepaddle2.2,nlp2.2上面，也是差不多错误：
W0406 17:05:37.302388  6256 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.2
W0406 17:05:37.304059  6256 device_context.cc:465] device: 0, cuDNN Version: 7.6.
The loss value printed in the log is the current step, and the metric is the average value of previous steps.
Epoch 1/10
Traceback (most recent call last):
  File "run_bigru_crf.py", line 175, in <module>
    log_freq=1)
  File "/home/hz/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/hapi/model.py", line 1732, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/home/hz/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/hapi/model.py", line 2034, in _run_one_epoch
    for step, data in enumerate(data_loader):
  File "/home/hz/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 255, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/hz/anaconda3/envs/paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/hz/anaconda3/envs/paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hz/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 248, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/home/hz/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/hz/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 234, in _thread_loop
    tmp.set(slot, core.CPUPlace())
ValueError: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:411)

两个环境跑自带的way_bill_ie是没有问题的。请指导下，是我的数据有问题吗？
