### ISSUE TITLE
使用Taskflow会在Python多进程中卡死

### ISSUE THREAD

**Issue by HuStanding** [PaddlePaddle/PaddleNLP#1889]
环境：
paddlenlp==2.1.0

使用taskflow的配合Python的进程池使用的时候，会出现卡死的情况，请问这个该怎么解决？部分代码如下：
```python
def run_multiprocess(x):
    print(time.time())
    predictor = Predictor()
    return predictor.predict(x[1])

with Pool(worker_num) as p:
    res = p.map(run_multiprocess, multi_df)
    df = pd.concat(res, axis=0)
```

无报错信息，有的数据会卡死，有的数据又是正常执行，很奇怪

**Comment by linjieccc** [comment]
你好，可以升级PaddlePaddle和PaddleNLP到最新的版本再试下

**Comment by HuStanding** [comment]
> 

尝试升级到最新的release版本，还是同样的问题

**Comment by linjieccc** [comment]
能否提供下复现代码，我们尝试复现下问题

**Comment by HuStanding** [comment]
> 

多进程的代码如上，但是数据不方便外传，碰见过几次了，一直没找到原因

**Comment by hhxdestiny** [comment]
@linjieccc Hi，循环跑信息抽取任务时，GPU占用不高，我想充分利用GPU，开多线程效果不佳，然后多进程，也遇到了类似问题，运行环境BML V100单卡，paddlenlp最新版本，复现代码如下：
```python
from paddlenlp import Taskflow
import time
from multiprocessing import Process

schema = ['时间','人物','地点']

def fun(idx):
    ie = Taskflow("information_extraction", schema=schema, model='uie-nano')
    st = time.time()
    for i in range(0, 100):
        ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！")
    et = time.time()
    all_cost = int(round((et - st) * 1000))
    avr_cost = all_cost / 100
    print(f'pidx: {idx}, all cost: {all_cost} ms, avr cost: {avr_cost} ms')

def run_process():
    ps = []
    for i in range(0, 1):
        p = Process(target=fun, args=(i,))
        ps.append(p)

    [p.start() for p in ps]
    [p.join() for p in ps]

if __name__ =='__main__':
    run_process()
```
日志如下
```bash
[2022-07-08 11:31:24,211] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load '/home/aistudio/.paddlenlp/taskflow/information_extraction/uie-nano'.
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_352/438241955.py", line 7, in fun
    ie = Taskflow("information_extraction", schema=schema, model='uie-nano')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/taskflow/taskflow.py", line 330, in __init__
    **self.kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/taskflow/information_extraction.py", line 251, in __init__
    self._get_inference_model()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/taskflow/task.py", line 235, in _get_inference_model
    self._prepare_static_mode()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/taskflow/task.py", line 172, in _prepare_static_mode
    self.predictor = paddle.inference.create_predictor(self._config)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:243)
```

**Comment by HuStanding** [comment]
你加一个batch_size,调大一点，GPU利用率就上去了

**Comment by nullgogo** [comment]
> 

我也遇到了这个问题 请问解决了么

**Comment by linjieccc** [comment]
@hhxdestiny @ChuangqHu Hi,

可以试下多进程spawn的形式，参考代码如下：

```python
from paddlenlp import Taskflow
from multiprocessing import Pool, Process, set_start_method

set_start_method("spawn", force=True)

TASK = None

def get_task():
    global TASK
    if TASK is None:
        TASK = Taskflow("information_extraction", schema=['时间','人物','地点'], model='uie-nano')
    return TASK

def get_result(inputs):
    task = get_task()
    return task(inputs)

input_list = ["2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！" for i in range(100)]


if __name__ == "__main__":
    result = []
    multi_pool = Pool(processes=3)
    predictions = multi_pool.map(get_result, input_list)
    multi_pool.close()
    multi_pool.join()
    print(predictions)
```

**Comment by ItGirls** [comment]
只用小改一下就可以解决:

```
# from paddlenlp import Taskflow
import time
from multiprocessing import Process

schema = ['时间','人物','地点']

def fun(idx):
    from paddlenlp import Taskflow
    ie = Taskflow("information_extraction", schema=schema, model='uie-nano')
    st = time.time()
    for i in range(0, 100):
        ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！")
    et = time.time()
    all_cost = int(round((et - st) * 1000))
    avr_cost = all_cost / 100
    print(f'pidx: {idx}, all cost: {all_cost} ms, avr cost: {avr_cost} ms')

def run_process():
    ps = []
    for i in range(0, 1):
        p = Process(target=fun, args=(i,))
        ps.append(p)

    [p.start() for p in ps]
    [p.join() for p in ps]

if __name__ =='__main__':
    run_process()
```

当然不改也可以, 我个人使用情况与你的类似.具体情况: 如果使用cpu,那么多进程是没有问题的; 只有使用gpu才会有问题,且报错和你一致. 通过将taskflow的import语句放到进程内部就可以解决, 具体什么原因可以参考以下链接内容思考:
1. [python多进程卡死排查记录
](https://blog.csdn.net/weixin_40238625/article/details/119677718)
2. [paddlepaddle使用多进程报错“(External) CUDA error(3), initialization error.”的解决方法](https://blog.csdn.net/csdn1b/article/details/121678951)
