### ISSUE TITLE
paddlenlp.transformers系列模型转ONNX报错

### ISSUE THREAD

**Issue by 471417367** [PaddlePaddle/PaddleNLP#1890]
下的模型有5个文件：
model_config.json
model_state.pdparams
sentencepiece.bpe.model
tokenizer_config.json
training_args.bin

环境：
paddle2onnx==0.9.1
paddlenlp==2.2.4

运行命令：
paddle2onnx --model_dir PP-Layout_v1.0_ser_pretrained --model_filename sentencepiece.bpe.model --params_filename model_state.pdparams --save_file ser_pretrained.onnx --opset_version 12

报错：
Traceback (most recent call last):
File "/usr/local/bin/paddle2onnx", line 8, in
sys.exit(main())
File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/command.py", line 195, in main
input_shape_dict=input_shape_dict)
File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/command.py", line 120, in program2onnx
params_filename=params_filename)
File "", line 2, in load_inference_model
File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in impl
return wrapped_func(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 238, in impl
return func(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 1592, in load_inference_model
program = Program.parse_from_string(program_desc_str)
File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 5312, in parse_from_string
p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
[Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:103)

**Comment by yingyibiao** [comment]
您好，LayoutLM 系列模型我们还没有支持转 ONNX。

**Comment by 471417367** [comment]
谢谢

yingyibiao ***@***.***> 于2022年4月2日周六 20:16写道：

**Comment by shelleyyyyu** [comment]
> 您好，LayoutLM 系列模型我们还没有支持转 ONNX。

您好，有预计支持的计划吗
