### ISSUE TITLE
module 'paddlenlp' has no attribute 'ops'   请问这个问题怎么解决？

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#1932]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by ZHUI** [comment]
能否贴一下你的调用报错代码？

**Comment by jiweizhangxu** [comment]
```python
> 
Traceback (most recent call last):
  File "D:/project--pycham/PaddleNLP-develop/examples/information_extraction/DuEE/classifier.py", line 31, in <module>
    import paddlenlp as ppnlp
  File "D:\project--pycham\PaddleNLP-develop\paddlenlp\__init__.py", line 25, in <module>
    from . import ops
  File "D:\project--pycham\PaddleNLP-develop\paddlenlp\ops\__init__.py", line 15, in <module>
    from .faster_transformer.transformer.decoding import *
  File "D:\project--pycham\PaddleNLP-develop\paddlenlp\ops\faster_transformer\transformer\decoding.py", line 30, in <module>
    from paddlenlp.transformers.utils import fn_args_to_dict
  File "D:\project--pycham\PaddleNLP-develop\paddlenlp\transformers\__init__.py", line 15, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "D:\project--pycham\PaddleNLP-develop\paddlenlp\transformers\model_utils.py", line 30, in <module>
    import paddlenlp.ops.faster_transformer.transformer.decoding as ft_decoding
AttributeError: module 'paddlenlp' has no attribute 'ops'
```

**Comment by ZHUI** [comment]
你好，刚刚修复了这个问题 https://github.com/PaddlePaddle/PaddleNLP/pull/1896

可以clone一下最新的代码。

**Comment by guoshengCS** [comment]
已经修复，此issue先行关闭
