### ISSUE TITLE
文本纠错预测代码报错

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleNLP#1959]
**- 版本信息**

1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.2.5，PaddlePaddle 2.2.0
2）系统环境：Linux，Python 3.7.13

**- 问题**

运行文本纠错预测代码出现问题，地址：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_correction/ernie-csc/predict.py

Traceback (most recent call last):
  File "/text_correction/predict.py", line 136, in <module>
    results = predictor.predict(samples, batch_size=args.batch_size)
  File "/text_correction/predict.py", line 118, in predict
    self.max_seq_length)
  File "/text_correction/utils.py", line 117, in parse_decode
    corr_pred = corr_preds[1:1 + lengths].tolist()
IndexError: invalid index to scalar variable.

**Comment by wjddd** [comment]
已解决。
