### ISSUE TITLE
paddlenlp-篇章级事件抽取相关-paddlenlp-篇章级事件抽取相关

### ISSUE THREAD

**Issue by Mnanazi** [PaddlePaddle/PaddleNLP#1964]
在windows10下执行sh run_duee_fin.sh trigger_train后，在pycharm的terminal窗口出现“KeyError: 'B-亏损'”错误。
具体为：
[2022-04-16 15:39:19,559] [    INFO] - Already cached C:\Users\Administrator\.paddlenlp\models\ernie-1.0\vocab.txt
[2022-04-16 15:39:19,570] [    INFO] - Already cached C:\Users\Administrator\.paddlenlp\models\ernie-1.0\ernie_v1_chn_base.pdparams
W0416 15:39:19.571270 10532 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W0416 15:39:19.579270 10532 device_context.cc:465] device: 0, cuDNN Version: 7.6.
============start train==========
Exception in thread Thread-3:
Traceback (most recent call last):
  File "G:\User\Administrator\Anaconda3\envs\paddle2.2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "G:\User\Administrator\Anaconda3\envs\paddle2.2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "G:\User\Administrator\Anaconda3\envs\paddle2.2\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 213, in _thread_loop
    self._thread_done_event)
  File "G:\User\Administrator\Anaconda3\envs\paddle2.2\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "sequence_labeling.py", line 172, in <lambda>
    ): fn(list(map(trans_func, samples)))
  File "sequence_labeling.py", line 108, in convert_example_to_feature
    encoded_label = [label_vocab[x] for x in encoded_label]
  File "sequence_labeling.py", line 108, in <listcomp>
    encoded_label = [label_vocab[x] for x in encoded_label]
KeyError: 'B-亏损'

**Comment by LemonNoel** [comment]
可以提供下前边数据处理的步骤么，我这边尝试复现一下

**Comment by Mnanazi** [comment]
> 可以提供下前边数据处理的步骤么，我这边尝试复现一下

就只是按照read.me中的教程，先顺利执行了`sh run_duee_fin.sh data_prepare`，生成了一些标注数据。然后在执行`sh run_duee_fin.sh trigger_train`  时就出现了  KeyError: 'B-亏损'

**Comment by Mnanazi** [comment]
> 可以提供下前边数据处理的步骤么，我这边尝试复现一下

我实在pycharm中的terminal中执行的shell命令，项目结构是这样的的
![image](https://user-images.githubusercontent.com/75676487/163676254-3a5af923-4d27-4060-9743-4712d27d6fcb.png)

**Comment by LemonNoel** [comment]
我在windows10的python3.7测试了一下，在utils.py的32行中的open函数参数里添加encoding="utf8"就没有这个问题了，你可以试一下。

**Comment by Mnanazi** [comment]
>谢谢。
