### ISSUE TITLE
example中的lexical_analysis工程训练train.py在训练报错。

### ISSUE THREAD

**Issue by lylyone** [PaddlePaddle/PaddleNLP#198]
错误：
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/10
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    train(args)
  File "train.py", line 110, in train
    callbacks=callbacks)
  File "D:\Datalearn\lib\site-packages\paddle\hapi\model.py", line 1495, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "D:\Datalearn\lib\site-packages\paddle\hapi\model.py", line 1802, in _run_one_epoch
    data[len(self._inputs):])
  File "D:\Datalearn\lib\site-packages\paddle\hapi\model.py", line 941, in train_batch
    loss = self._adapter.train_batch(inputs, labels)
  File "D:\Datalearn\lib\site-packages\paddle\hapi\model.py", line 656, in train_batch
    * [to_variable(x) for x in inputs])
  File "E:\NLP学习\PaddleNLP\PaddleNLP\examples\lexical_analysis\model.py", line 93, in forward
    _, prediction = self.viterbi_decoder(emission, lengths)
  File "D:\Datalearn\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Datalearn\lib\site-packages\paddlenlp\layers\crf.py", line 355, in forward
    idxs = paddle.stack([batch_index, last_index], axis=1)
  File "D:\Datalearn\lib\site-packages\paddle\tensor\manipulation.py", line 443, in stack
    return layers.stack(x, axis, name)
  File "D:\Datalearn\lib\site-packages\paddle\fluid\layers\nn.py", line 10069, in stack
    return core.ops.stack(x, 'axis', axis)
ValueError: (InvalidArgument) The DataType of stack Op's duplicable Variable X must be consistent. The current variable type is (int),
 but the previous variable type is (int64_t). (at D:\v2.0.1\paddle\paddle\fluid\framework\operator.cc:1520)
  [operator < stack > error]
这个有跑通的吗？

**Comment by lylyone** [comment]
基于gru+lstm+crf的网络结构的训练。

**Comment by kinghuin** [comment]
您好，我这边没能复现出这一问题。请问运行的paddlepaddle，paddlenlp版本号是多少呢？是在CPU环境下运行的吗？这个报错是偶现还是必现的呢？

**Comment by lylyone** [comment]
> 您好，我这边没能复现出这一问题。请问运行的paddlepaddle，paddlenlp版本号是多少呢？是在CPU环境下运行的吗？这个报错是偶现还是必现的呢？

paddlenlp版本 是2.0.0rc14，paddlepaddle 版本是 2.0.1，在windows10，windows7，cpu环境下跑都报这个错误，应该是必现，我在aistudio跑通了。不知道怎么解决。我在model.fit(train_data=train_loader,
              eval_data=test_loader,
              batch_size=args.batch_size,
              epochs=args.epochs,
              eval_freq=1,
              log_freq=10,
              save_dir=args.model_save_dir,
              save_freq=1,
              shuffle=True,
              callbacks=callbacks)这一步就报这个错误。请问您那边的环境有什么要求吗？

**Comment by kinghuin** [comment]
您好，这可能是windows、linux对lengths变量的类型的处理不同导致的，类似：
https://github.com/PaddlePaddle/PaddleHub/pull/905/files#diff-378c03fe05a16640b08416826987722bc8c56beac28ad70e09b0b1913b09cf2dL374
我将在近日修复这一问题，如您着急可以尝试上面的修复方式（如您顺利解决这一问题，欢迎向我们提交PR）或者在windows平台使用WSL2

**Comment by kinghuin** [comment]
Hi，我们已修复这个问题，请使用develop分支example中的最新代码 ：）

**Comment by ZeyuChen** [comment]
This bug has already fixed. Issue close.
