### ISSUE TITLE
DuReader-robust

### ISSUE THREAD

**Issue by yinsuso** [PaddlePaddle/PaddleNLP#1980]
```python
File "dureader/run_du.py", line 358, in <module>
    run(args)
  File "dureader/run_du.py", line 231, in run
    return_list=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 336, in __init__
    "dataset should be subclass instance of paddle.io.Dataset"
AssertionError: dataset should be subclass instance of paddle.io.Dataset
INFO 2022-04-20 16:42:55,731 launch_utils.py:341] terminate all the procs
ERROR 2022-04-20 16:42:55,731 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-04-20 16:42:59,735 launch_utils.py:341] terminate all the procs
INFO 2022-04-20 16:42:59,736 launch.py:311] Local processes completed.
```

**Comment by smallv0221** [comment]
您好，建议您使用最新版本的paddlepaddle，这个问题在新版本中已经修复了

**Comment by yinsuso** [comment]
```python
Traceback (most recent call last):
  File "dureader/run_du.py", line 358, in <module>
    run(args)
  File "dureader/run_du.py", line 131, in run
    model = model_class.from_pretrained(args.model_name_or_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 324, in from_pretrained
    base_model = cls.base_model_class(*base_args, **base_kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/utils.py", line 86, in __impl__
    init_func(self, *args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/ernie_gram/modeling.py", line 222, in __init__
    type_vocab_size, pad_token_id, rel_pos_size, num_attention_heads)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/ernie_gram/modeling.py", line 47, in __init__
    vocab_size, emb_size, padding_idx=pad_token_id)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 1457, in __init__
    is_bias=False)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 423, in create_parameter
    default_initializer)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3533, in create_parameter
    initializer(param, self)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 567, in __call__
    self._seed, 'dtype', out_dtype)
OSError: (External) CUBLAS error(7). 
  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:390)
  [operator < uniform_random > error]
```
2.3.0rc0版本的paddle出现的问题

**Comment by ZHUI** [comment]
您好，看起来是 paddle 安装有些问题。可以使用 `paddle.untils.run_check()` 检查一下环境问题。

**Comment by yinsuso** [comment]
用ai studio的notebook直接包管理切换的paddle版本，提示module 'paddle' has no attribute 'untils'，包管理显示的是2.3.0rc0版本

**Comment by yinsuso** [comment]
```python
WARNING:root:You are using GPU version PaddlePaddle, but there is no GPU detected on your machine. Maybe CUDA devices is not set properly.
 Original Error is (External) CUDA error(35), CUDA driver version is insufficient for CUDA runtime version. 
  [Hint: 'cudaErrorInsufficientDriver'. This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:66)
```
用的ai studio，抛出来这个提示

**Comment by yinsuso** [comment]
@smallv0221 这个最新版本的paddlepaddle是指的2.2.2版本还是2.3.0rc0版本，2.3.0rc0版本ai studio带不起来,能不能更新个可以跑通的版本，现在DuReader-robust和SQuAD都跑不通

**Comment by ZHUI** [comment]
可以试试develop的paddle https://www.paddlepaddle.org.cn/
```shell
python -m pip install paddlepaddle-gpu==0.0.0.post102 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html 
```

**Comment by yinsuso** [comment]
> 可以试试开发的桨https://www.paddlepaddle.org.cn/
> 
> ```shell
> python -m pip install paddlepaddle-gpu==0.0.0.post102 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
> ```
这个版本动态库不行
```shell
The third-party dynamic library (libcuda.so) that Paddle depends on is not configured correctly. (error code is /usr/lib/x86_64-linux-gnu/libcuda.so: file too short)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
 ```

**Comment by ZHUI** [comment]
你检查一下 cuda 版本，下对应develop的版本。

**Comment by yinsuso** [comment]
> 你检查一下 cuda 版本，下对应develop的版本。

不折腾了，我发现用自带版本的paddle和paddlenlp可以跑通，只要有一个更新了就跑不通了
