### ISSUE TITLE
使用aistudio的脚本任务的时候，升级了paddlenlp导致import异常

### ISSUE THREAD

**Issue by jiuwuxiaohun** [PaddlePaddle/PaddleNLP#2044]
同样的代码在aistudio的BML Codelab上执行没有问题的。
======================

还原过程为：
https://aistudio.baidu.com/aistudio/usercenter
在这里新建一个脚本任务，python版本为3.7，paddlepaddle2.2.2
———————————
脚本任务里面 run.py 文件的内容为：
```
import paddlenlp
print(paddlenlp.__version__)
```
以上代码能正常运行。
———————————
但是因为脚本任务内置的paddlenlp版本太低了，我需要升级到2.2.6的paddlenlp版本。
run.sh 脚本如下：
```
pip uninstall -y paddlenlp
pip install paddlenlp
pip install --upgrade paddlenlp

python -m paddle.distributed.launch run.py

```
———————————
运行该shell后提示版本升级ok了，但现在上上方的python代码就无法执行了，报告错误为：
```

launch train in GPU mode!
launch proc_id:334 idx:0
/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 48, in <module>
    from ._check_build import check_build  # noqa
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 45, in <module>
    import paddlenlp
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlenlp/__init__.py", line 29, in <module>
    from . import metrics
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlenlp/metrics/__init__.py", line 16, in <module>
    from .chunk import ChunkEvaluator
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddlenlp/metrics/chunk.py", line 6, in <module>
    from seqeval.metrics.sequence_labeling import get_entities
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/seqeval/metrics/__init__.py", line 1, in <module>
    from seqeval.metrics.sequence_labeling import (accuracy_score,
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/seqeval/metrics/sequence_labeling.py", line 14, in <module>
    from seqeval.metrics.v1 import SCORES, _precision_recall_fscore_support
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/seqeval/metrics/v1.py", line 5, in <module>
    from sklearn.exceptions import UndefinedMetricWarning
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/sklearn/__init__.py", line 81, in <module>
    from . import __check_build  # noqa: F401
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 50, in <module>
    raise_build_error(e)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 43, in raise_build_error
    % (e, local_dir, "".join(dir_content).strip(), msg)
ImportError: dlopen: cannot load any more object with static TLS

```
所以错误为：2.2.6的paddlenlp版本在aistudio的脚本任务环境无法导入，请核查解决下哦。谢谢

**Comment by ZeyuChen** [comment]
@jiuwuxiaohun 请尝试下不用使用`python -m paddle.distributed.launch run.py`
使用
```
python run.py
```
启动脚本即可，看看是否还会有这个错误，可能是个环境问题不支持分布式的启动。

**Comment by jiuwuxiaohun** [comment]
我在这里开了一个公开项目，请执行下，谢谢哈。

https://aistudio.baidu.com/aistudio/clusterprojectdetail/3921081/trainTask

同时我也在aistudio论坛发帖了。
https://aistudio.baidu.com/paddle/forum/topic/show/1729292
---------

V100的机器多卡机器一直在排队，所以我用的是最低的配置运行的。

**Comment by luyaojie** [comment]
我最近在Aistudio的P40脚本程序中遇到过，可以尝试这样安装对应版本的sklean后解决。

```
python -m pip install --quiet paddlenlp==2.2.6 scikit-learn==0.20.3
```

**Comment by jiuwuxiaohun** [comment]
@luyaojie 你的方案有效，谢谢。
