### ISSUE TITLE
预测加速

### ISSUE THREAD

**Issue by lianlipen** [PaddlePaddle/PaddleNLP#2068]
在代码中加入  ‘use_faster=True ’时
```python
ids, scores = model.generate(
            use_faster=True,
            input_ids=input_ids,
            token_type_ids=token_type_ids,
            position_ids=position_ids,
            attention_mask=attention_mask,
            max_length=args.max_dec_len,
            min_length=args.min_dec_len,
            decode_strategy=args.decode_strategy,
            temperature=args.temperature,
            top_k=args.top_k,
            top_p=args.top_p,
            num_beams=args.num_beams,
            length_penalty=args.length_penalty,
            num_return_sequences=args.num_return_sequences,
            bos_token_id=tokenizer.cls_token_id,
            eos_token_id=tokenizer.mask_token_id)
```
报错信息：
FasterGeneration is not available, and the original version would be used instead.

**Comment by FrostML** [comment]
是什么模型？有更多的报错信息么？
加速有黑白名单的机制，在检测到不满足一定配置或者是本地环境自动编译加速相关的代码不成功都会有这个提示

**Comment by lianlipen** [comment]
模型：unimo-text-1.0

**Comment by lianlipen** [comment]
报错信息：
```python
[2022-05-06 15:35:57,292] [ WARNING] - FasterTransformer is not available due to build errors.
Traceback (most recent call last):
  File "FasterTransformer_setup.py", line 11, in <module>
    output_dir=r'/home/ubuntu/.paddlenlp/extensions/65e74f41b346ca7da76a81ea7368a3d1/FasterTransformer')
  File "/home/ubuntu/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 192, in build_extensions
    ext.build_with_command(self)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 170, in build_with_command
    raise e
  File "/home/ubuntu/.local/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 156, in build_with_command
    self).build_with_command(ext_builder)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 99, in build_with_command
    stderr=stdout)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/ubuntu/.local/lib/python3.7/site-packages/paddlenlp/ops', '-DPY_CMD=/usr/bin/python', '-DWITH_GPT=ON', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ubuntu/.paddlenlp/extensions/65e74f41b346ca7da76a81ea7368a3d1/FasterTransformer']' returned non-zero exit status 1.
[2022-05-06 15:35:57,640] [ WARNING] - Failed to run command: <built-in function compile>, errors: Command 'cd /home/ubuntu/.paddlenlp/extensions/65e74f41b346ca7da76a81ea7368a3d1/FasterTransformer && /usr/bin/python FasterTransformer_setup.py build' returned non-zero exit status 1.
[2022-05-06 15:35:57,641] [ WARNING] - FasterGeneration is not available, and the original version would be used instead.
```

**Comment by FrostML** [comment]
看上去是当前环境编译加速特性有些问题。
麻烦再提供下当前环境的信息吧，包括但不限于 cmake 版本，gcc 版本，cuda 版本，GPU，paddlenlp 版本，paddle 版本。

可以尝试删除 `/home/ubuntu/.paddlenlp/extensions/` 重新编译看下能否解决。

另外，如果上面的方式不能解决，也可以修改下 `/home/ubuntu/.local/lib/python3.7/site-packages/paddlenlp/transformers/generation_utils.py` 文件里，如下几行代码，再执行一次，看下具体的编译报错是什么：
<img width="831" alt="image" src="https://user-images.githubusercontent.com/7160927/167090634-d8f29577-5455-49d9-8830-9b5328d5e8d3.png">

**Comment by lianlipen** [comment]
嗯嗯，好的。谢谢！

**Comment by yinpeisu** [comment]
删除了 /home/ubuntu/.paddlenlp/extensions/ ，问下应该怎么重新编译呢
