### ISSUE TITLE
本地先通过Pre-training任务得到的一个预训练的模型，然后在Fine-tuning任务中加载自己生成的预训练模型的时候，模型加载失败

### ISSUE THREAD

**Issue by wangzhe0912** [PaddlePaddle/PaddleNLP#210]
在跑bert的benchmark的任务时候，先是通过Pre-training任务得到的一个预训练的模型，然后在Fine-tuning任务中加载自己生成的预训练模型的时候，模型加载失败了。
简单看了一下原因，应该是Pre-training任务保存的模型目录下没有model_state.pdparams这个文件，而Fine-tuning任务加载模型的时候找不到这个文件，所以启动失败了。
Traceback (most recent call last):
  File "./run_glue.py", line 413, in <module>
    do_train(args)
  File "./run_glue.py", line 331, in do_train
    args.model_name_or_path, num_classes=num_class)
  File "/ssd3/PaddleNLP_develop/paddlenlp/transformers/model_utils.py", line 165, in from_pretrained
    file_path, default_root)
  File "/ssd3/PaddleNLP_develop/paddlenlp/utils/downloader.py", line 154, in get_path_from_url
    assert is_url(url), "downloading from {} not a url".format(url)
AssertionError: downloading from /ssd3/PaddleNLP_develop/benchmark/bert/tmp_develop/model_100000/model_state.pdparams not a url

**Comment by wangzhe0912** [comment]
模型地址如下:
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/benchmark/bert

**Comment by wawltor** [comment]
您好，https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/bert/static  最新的代码已经兼容上面的热启训练
