### ISSUE TITLE
SimCSE网络构建中int64的问题

### ISSUE THREAD

**Issue by wenjin11** [PaddlePaddle/PaddleNLP#2115]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.2.6，PaddlePaddle2.2.2
2）系统环境：请您描述系统类型，Windows，python3.9
- 复现信息：如为报错，请给出复现环境、复现步骤
- 
sequence_output, cls_embedding = self.ptm(input_ids, token_type_ids,
                                                  position_ids, attention_mask)
这里报错InvalidArgumentError: The DataType of equal Op's duplicable Variable Y must be consistent. The current variable type is (int64_t), but the previous variable type is (int). (at C:\home\workspace\Paddle_release\paddle\fluid\framework\operator.cc:1604)
      [operator < equal > error]  [operator < run_program > error]

**Comment by wenjin11** [comment]
具体问题
Traceback (most recent call last):
  File "C:\lab\faq_system\train.py", line 212, in <module>
    do_train()
  File "C:\lab\faq_system\train.py", line 175, in do_train
    loss = model(
  File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 704, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\lab\faq_system\model.py", line 130, in forward
    query_cls_embedding = self.get_pooled_embedding(
  File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 376, in __call__
    error_data.raise_new_exception()
  File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "C:\lab\faq_system\model.py", line 64, in get_pooled_embedding
                             with_pooler=True):

        sequence_output, cls_embedding = self.ptm(input_ids, token_type_ids,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                                  position_ids, attention_mask)

    File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\666\AppData\Local\Temp\tmpk9lixs9z.py", line 92, in forward
	attention_mask = paddle.jit.dy2static.convert_ifelse(attention_mask is
    File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
	out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "C:\Users\666\anaconda3\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 484, in forward
	).astype(self.pooler.dense.weight.dtype) * -1e4,
    File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 342, in __impl__
	current_block(self).append_op(
    File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\framework.py", line 3178, in append_op
	op = Operator(
    File "C:\Users\666\anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
	for frame in traceback.extract_stack():

**Comment by w5688414** [comment]
@wenjin11  您好，目前没有32位的windows环境，我提供一种修改，先看看是否work。
data.py里面
```
return paddle.to_tensor(repetitied_input_ids), paddle.to_tensor(
        repetitied_token_type_ids)
```
改成：

```
return paddle.to_tensor(repetitied_input_ids, dtype='int64'), paddle.to_tensor(
        repetitied_token_type_ids, dtype='int64')
```
