### ISSUE TITLE
dist.spawn在多个num_workers下报错

### ISSUE THREAD

**Issue by ai-p0lar1s** [PaddlePaddle/PaddleNLP#2151]
当采用dist.spawn()时，num_workers大于0会报错
```
def worker():
    tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')

    def read():
        for _ in range(100):
            yield "你好"

    def convert_example(example, tokenizer):
        token = tokenizer(example, pad_to_max_seq_len=True, max_seq_len=32)
        return token['input_ids'], token['token_type_ids']


    map_ds = load_dataset(read, lazy=False)
    trans_func = partial(convert_example, tokenizer=tokenizer)
    batchify_fn = lambda samples, fn=Tuple(
        Pad(axis=0, pad_val=tokenizer.pad_token_id),
        Pad(axis=0, pad_val=tokenizer.pad_token_type_id)
    ): [data for data in fn(samples)]


    def create_dataloader(
        dataset,
        mode='train',
        batch_size=1,
        batchify_fn=None,
        num_workers=0,
        trans_fn=None
        ):

        if trans_fn:
            dataset = dataset.map(trans_fn)

        shuffle = True if mode == 'train' else False
        if mode == 'train':
            batch_sampler = DistributedBatchSampler(
                dataset, batch_size=batch_size, shuffle=shuffle)
        else:
            batch_sampler = BatchSampler(
                dataset, batch_size=batch_size, shuffle=shuffle)

        return DataLoader(
            dataset=dataset,
            batch_sampler=batch_sampler,
            collate_fn=batchify_fn,
            num_workers=num_workers,
            return_list=True)


    dataloader = create_dataloader(
        dataset=map_ds, 
        mode='train', 
        batch_size=4, 
        batchify_fn=batchify_fn, 
        num_workers=4, 
        trans_fn=trans_func
    )

    for step, batch in enumerate(tqdm(dataloader)):
        pass
    print('device {} OK'.format(dist.get_rank()))


if __name__ == '__main__':
    dist.spawn(worker)
```
部分错误日志如下：

```
  0%|                                                                                                                                                      | 0/9 [00:00<?, ?it/s]
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7fb301552560>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 708, in __del__
    self._try_shutdown_all()
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 499, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
Traceback (most recent call last):
  File "/data/wjc/paddle-qa/temp.py", line 76, in <module>
    dist.spawn(worker)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 565, in spawn
    while not context.join():
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 373, in join
    self._throw_exception(error_index)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 391, in _throw_exception
    raise Exception(msg)
Exception: 

----------------------------------------------
Process 2 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 322, in _func_wrapper
    result = func(*args)
  File "/data/wjc/paddle-qa/temp.py", line 70, in worker
    for step, batch in enumerate(tqdm(dataloader)):
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/fluid/reader.py", line 560, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 376, in __init__
    self._init_workers()
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 409, in _init_workers
    worker.start()
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'worker.<locals>.convert_example'
```

把num_workers设为0时，上述代码不会报错。另外，当改为paddle.distributed.launch方式运行时，不管num_workers是多少都不会报错。不知这是什么原因导致的，正确的做法是？

**Comment by LiuChiachi** [comment]
paddle.distributed.launch方式运行，不需要`dist.spawn(worker)`这样显示的调用，直接调用`worker()`即可，启动python脚本的时候，python -m paddle.distributed.launch --gpus "0,1,2" xxx.py 就行

**Comment by ai-p0lar1s** [comment]
> paddle.distributed.launch方式运行，不需要`dist.spawn(worker)`这样显示的调用，直接调用`worker()`即可，启动python脚本的时候，python -m paddle.distributed.launch --gpus "0,1,2" xxx.py 就行

没有这样用的。上面的代码是python xxx.py运行的，dataloader在num_workers大于0的时候会报上述错。如果改成launch运行（把worker和main去掉），不管num_workers是多少，都没有问题。现在就想确认一下如果我要通过dist.spawn()运行，那么怎么才能开多个num_workers。

**Comment by LiuChiachi** [comment]
您好，咨询了相关同学，这里定义了局部函数`convert_example`用`partial`调用，这个没法pickable，没法传递给子进程，多进程DataLoader的dataset需要继承`paddle.io.Dataset/IterableDataset`通过实现`__getitem__`或者`__iter__`方法来定义

相关文档：

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/spawn_cn.html#spawn

```
paddle.distributed.spawn(func, args=(), nprocs=- 1, join=True, daemon=False, **options)
```
- func (function) - 由 spawn 方法启动的进程所调用的目标函数。该目标函数需要能够被 pickled (序列化)，所以目标函数必须定义为模块的一级函数，不能是内部子函数或者类方法。

**Comment by ai-p0lar1s** [comment]
> 您好，咨询了相关同学，这里定义了局部函数`convert_example`用`partial`调用，这个没法pickable，没法传递给子进程，多进程DataLoader的dataset需要继承`paddle.io.Dataset/IterableDataset`通过实现`__getitem__`或者`__iter__`方法来定义
> 
> 相关文档：
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/spawn_cn.html#spawn
> 
> ```
> paddle.distributed.spawn(func, args=(), nprocs=- 1, join=True, daemon=False, **options)
> ```
> 
> * func (function) - 由 spawn 方法启动的进程所调用的目标函数。该目标函数需要能够被 pickled (序列化)，所以目标函数必须定义为模块的一级函数，不能是内部子函数或者类方法。

Hi，我改成`paddle.io.Dataset`试了一下：
```
class TestDataset(paddle.io.Dataset):
    def __init__(self):
        super().__init__()
        self.tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')
        self.corpus = ["您好" for _ in range(100)]
    
    def __len__(self):
        return len(self.corpus)
    
    def __getitem__(self, idx):
        sample = self.tokenizer(self.corpus[idx], pad_to_max_seq_len=True, max_seq_len=32)
        input_ids = paddle.to_tensor(sample["input_ids"])
        token_type_ids = paddle.to_tensor(sample["token_type_ids"])
        return input_ids, token_type_ids


def worker():
    dist.init_parallel_env()

    dataset = TestDataset()

    batch_sampler = DistributedBatchSampler(dataset, batch_size=4, shuffle=True)
    dataloader = DataLoader(
        dataset=dataset,
        batch_sampler=batch_sampler,
        num_workers=2
    )

    for _, batch in enumerate(tqdm(dataloader)):
        pass
    print('device {}: OK'.format(paddle.distributed.get_rank()))


if __name__ == '__main__':
    paddle.distributed.spawn(worker)
    print('Done')
```

依然报错：
```
----------------------------------------------
Process 2 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 322, in _func_wrapper
    result = func(*args)
  File "/data/wjc/paddle-qa/temp.py", line 110, in worker
    for _, batch in enumerate(tqdm(dataloader)):
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/fluid/reader.py", line 560, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 376, in __init__
    self._init_workers()
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 409, in _init_workers
    worker.start()
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/user/anaconda3/envs/mmt/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Vocab.__init__.<locals>.<lambda>'
```

看起来是tokenzier的问题。试了一下，tokenize需要放在collate_fn里面。
```
class TestDataset(paddle.io.Dataset):
    def __init__(self):
        super().__init__()
        self.corpus = ["您好" for _ in range(100)]
    
    def __len__(self):
        return len(self.corpus)
    
    def __getitem__(self, idx):
        sample = self.corpus[idx]
        return sample


def batchify_fn(batch):
    batch_input_ids = []
    batch_token_type_ids = []
    for text in batch:
        tokens = tokenizer(text)
        batch_input_ids.append(tokens['input_ids'])
        batch_token_type_ids.append(tokens['token_type_ids'])
    return paddle.to_tensor(batch_input_ids), paddle.to_tensor(batch_token_type_ids)


def worker():
    dist.init_parallel_env()

    dataset = TestDataset()

    batch_sampler = DistributedBatchSampler(dataset, batch_size=4, shuffle=True)
    dataloader = DataLoader(
        dataset=dataset,
        batch_sampler=batch_sampler,
        num_workers=2,
        collate_fn=batchify_fn
    )

    for _, batch in enumerate(tqdm(dataloader)):
        input_ids, token_type_ids = batch
    print('device {}: OK'.format(paddle.distributed.get_rank()))


if __name__ == '__main__':
    paddle.distributed.spawn(worker)
    print('Done')
```

这样没有问题。但是有没有方法也可以并行tokenize呢？
