### ISSUE TITLE
AssertionError: The task name:information_extraction is not in Taskflow list, please check your task name.

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#2186]
这个是版本问题吗？
Traceback (most recent call last):
  File "/usr/local/zx/uie/my_try/try_1.py", line 5, in <module>
    ie = Taskflow('information_extraction', schema=schema)
  File "/root/anaconda3/envs/ax/lib/python3.6/site-packages/paddlenlp/taskflow/taskflow.py", line 173, in __init__
    task)
AssertionError: The task name:information_extraction is not in Taskflow list, please check your task name.

**Comment by wawltor** [comment]
您好，UIE这个功能是2.3版本正式发版的，麻烦升级一下PaddleNLP `pip install paddlenlp --upgrade`
