### ISSUE TITLE
如下错误You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided []

### ISSUE THREAD

**Issue by byew** [PaddlePaddle/PaddleNLP#2244]
你好，在信息抽取时候报如下错误：Windows系统，最新版的paddlepaddle，paddlenlp。

Traceback (most recent call last):
  File "D:/fire/extract_summary/information_extract/base.py", line 20, in <module>
    result = ie(doc)
  File "D:\fire\extract_summary\information_extract\paddlenlp\taskflow\taskflow.py", line 314, in __call__
    results = self.task_instance(inputs)
  File "D:\fire\extract_summary\information_extract\paddlenlp\taskflow\task.py", line 293, in __call__
    outputs = self._run_model(inputs)
  File "D:\fire\extract_summary\information_extract\paddlenlp\taskflow\information_extraction.py", line 334, in _run_model
    results = self._multi_stage_predict(raw_inputs, schema_tree)
  File "D:\fire\extract_summary\information_extract\paddlenlp\taskflow\information_extraction.py", line 375, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "D:\fire\extract_summary\information_extract\paddlenlp\taskflow\information_extraction.py", line 236, in _single_stage_predict
    infer_ds = load_dataset(read, inputs=short_inputs, lazy=False)
  File "D:\fire\extract_summary\information_extract\paddlenlp\datasets\dataset.py", line 195, in load_dataset
    return reader_instance.read(**custom_kwargs)
  File "D:\fire\extract_summary\information_extract\paddlenlp\datasets\dataset.py", line 828, in read
    return MapDataset(list(examples))
  File "D:\fire\extract_summary\information_extract\paddlenlp\taskflow\information_extraction.py", line 219, in read
    return_dict=False)
  File "D:\fire\extract_summary\information_extract\paddlenlp\transformers\tokenizer_utils_base.py", line 2231, in __call__
    **kwargs)
  File "D:\fire\extract_summary\information_extract\paddlenlp\transformers\tokenizer_utils_base.py", line 2428, in batch_encode
    **kwargs, )
  File "D:\fire\extract_summary\information_extract\paddlenlp\transformers\tokenizer_utils.py", line 1128, in _batch_encode_plus
    **kwargs)
  File "D:\fire\extract_summary\information_extract\paddlenlp\transformers\tokenizer_utils.py", line 1284, in _batch_prepare_for_model
    return_attention_mask=return_attention_mask, )
  File "D:\fire\extract_summary\information_extract\paddlenlp\transformers\tokenizer_utils_base.py", line 2531, in pad
    "You should supply an encoding or a list of encodings to this method "
ValueError: You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided []

Process finished with exit code 1

**Comment by byew** [comment]
补充：
     中文数据。
代码如下：
       doc=‘我的文本数据，大约几千字’
        ie = Taskflow('information_extraction', schema=schema, task_path='./uie_base/')
        result = ie(doc)

**Comment by wawltor** [comment]
想问一下 uie_base这个模型是自己训练的吗？

**Comment by byew** [comment]
> 想问一下uie_base这个模型是自己的吗？

不是的，是官方提供的uie_base_v0.1，这个版本。

**Comment by byew** [comment]
> 想问一下 uie_base这个模型是自己训练的吗？
咱们这个uie_base这个模型对句长有限制么？

**Comment by wawltor** [comment]
您好，我这样是没有问题的  是不是 doc那个标点符号错了啊
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/16698950/169267172-977eacb1-04dd-4f3a-99cd-72d283b32c1c.png">

**Comment by byew** [comment]
> 您好，我这样是没有问题的 是不是 doc那个标点符号错了啊 

那个 doc 它是一个几千字的文章，太大。所以我就没放上去。（我的文本数据，大约几千字）这句话我就是修饰下。
要不我留个邮箱，咱们微信联系？
baiyang.top@gmail.com
谢谢大佬

**Comment by wawltor** [comment]
可以加一下群
<img width="369" alt="image" src="https://user-images.githubusercontent.com/16698950/169269529-db06eff4-8033-4a2c-ad9f-de24e9c07684.png">

**Comment by byew** [comment]
好嘞，谢谢。

**Comment by byew** [comment]
嗯嗯 好的 
> 
哈喽大佬，搞定了。
我数据有点脏，换行符有点多，我把换行符全部去掉就不报错了。

**Comment by wawltor** [comment]
嗯呢 好
