### ISSUE TITLE
ValueError: (InvalidArgument) unsqueeze2(): argument 'X' (position 0) must be Tensor, but got Tensor (at /paddle/paddle/fluid/pybind/op_function_common.cc:737)

### ISSUE THREAD

**Issue by clareliu1234** [PaddlePaddle/PaddleNLP#2248]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
Traceback (most recent call last):
  File "/home/liuhaomin/NER/ernie_3.0/run_training.py", line 291, in <module>
    train(model, train_iter, optimizer, hp)
  File "/home/liuhaomin/NER/ernie_3.0/run_training.py", line 77, in train
    loss = model.neg_log_likelihood(x, y)  # logits: (N, T, VOCAB), y: (N, T)
  File "/home/liuhaomin/NER/ernie_3.0/BertBilstmCrfNer.py", line 73, in neg_log_likelihood
    embedding = self._bert_enc(sentence)
  File "/home/liuhaomin/NER/ernie_3.0/BertBilstmCrfNer.py", line 63, in _bert_enc
    final_hidden_layer_of_encoder = self.bert(sentence, attention_mask=sentence)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddlenlp/transformers/ernie/modeling.py", line 522, in forward
    attention_mask, axis=[1, 2]).astype(paddle.get_default_dtype())
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddle/tensor/manipulation.py", line 1339, in unsqueeze
    return layers.unsqueeze(x, axis, name)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6572, in unsqueeze
    out, _ = _C_ops.unsqueeze2(input, 'axes', axes)
ValueError: (InvalidArgument) unsqueeze2(): argument 'X' (position 0) must be Tensor, but got Tensor (at /paddle/paddle/fluid/pybind/op_function_common.cc:737)
您好，可以帮助我解决一下这个问题吗？

**Comment by ZeyuChen** [comment]
请确定下使用paddlenlp和paddle的版本是否是最新的

**Comment by clareliu1234** [comment]
版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本

1)paddlenlp的版本是2.3.1，paddlepaddle版本是paddlepaddle-gpu=2.3.0
2)系统环境是Linux，cuda版本是102，python版本3.6
Traceback (most recent call last):
  File "/home/liuhaomin/NER/ernie_3.0_new/run_training.py", line 313, in <module>
    train(model,train_iter, optimizer, hp)
  File "/home/liuhaomin/NER/ernie_3.0_new/run_training.py", line 86, in train
    outputs = model(**inputs)  # logits: (N, T, VOCAB), y: (N, T)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liuhaomin/NER/ernie_3.0_new/BertBilstmCrfNer.py", line 142, in forward
    embedding = self._bert_enc(sentence)
  File "/home/liuhaomin/NER/ernie_3.0_new/BertBilstmCrfNer.py", line 68, in _bert_enc
    final_hidden_layer_of_encoder,_= self.bert(sentence, attention_mask=bertMask)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddlenlp/transformers/ernie/modeling.py", line 619, in forward
    attention_mask=attention_mask)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddlenlp/transformers/ernie/modeling.py", line 539, in forward
    attention_mask, axis=[1, 2]).astype(paddle.get_default_dtype())
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddle/tensor/manipulation.py", line 1339, in unsqueeze
    return layers.unsqueeze(x, axis, name)
  File "/home/liuhaomin/tutorial-env/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6572, in unsqueeze
    out, _ = _C_ops.unsqueeze2(input, 'axes', axes)
ValueError: (InvalidArgument) unsqueeze2(): argument 'X' (position 0) must be Tensor, but got Tensor (at /paddle/paddle/fluid/pybind/op_function_common.cc:737)

**Comment by clareliu1234** [comment]
> 请确定下使用paddlenlp和paddle的版本是否是最新的

paddle是paddlepaddle-gpu=2.3.0,paddlenlp是2.3.1

**Comment by clareliu1234** [comment]
> 请确定下使用paddlenlp和paddle的版本是否是最新的

paddle是paddlepaddle-gpu=2.3.0,paddlenlp是2.3.1
