### ISSUE TITLE
Finetuing uie时出现模型加载_pickle.UnpicklingError问题

### ISSUE THREAD

**Issue by leon-cas** [PaddlePaddle/PaddleNLP#2323]
paddle版本(GPU)： 2.3.0  安装方式： python -m pip install paddlepaddle-gpu==2.3.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
paddlenlp版本： 2.3.1   安装方式： pip
Python版本：3.7.4

具体报错信息如下：

[2022-05-26 14:15:23,761] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2022-05-26 14:15:23,761] [    INFO] - Already cached /root/.paddlenlp/models/ernie-3.0-base-zh/ernie_3.0_base_zh_vocab.txt
W0526 14:15:23.789427 62021 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.1
W0526 14:15:23.793360 62021 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/paddle/framework/io.py", line 954, in load
    load_result = pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: pickle data was truncated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/paddle/framework/io.py", line 980, in load
    tensor, _ = _load_selected_rows(path)
  File "/opt/conda/lib/python3.7/site-packages/paddle/framework/io.py", line 541, in _load_selected_rows
    _seek = core.load_selected_rows(temp_sr, file_name)
ValueError: (InvalidArgument) Only version 0 SelectedRows is supported.
  [Hint: Expected version == 0U, but received version:3029664896 != 0U:0.] (at /paddle/paddle/fluid/framework/selected_rows_utils.cc:68)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/paddle/framework/io.py", line 984, in load
    tensor, _ = _load_lod_tensor(path)
  File "/opt/conda/lib/python3.7/site-packages/paddle/framework/io.py", line 502, in _load_lod_tensor
    _seek = paddle.fluid.core.load_lod_tensor(temp_t, file_name)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 3029664896 found).
  [Hint: Expected version == 0U, but received version:3029664896 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:276)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/paddle/framework/io.py", line 996, in load
    program_desc_str)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/framework.py", line 5762, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:103)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "finetune.py", line 159, in <module>
    do_train()
  File "finetune.py", line 48, in do_train
    model = UIE.from_pretrained(args.model)
  File "/opt/conda/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 348, in from_pretrained
    state_dict = paddle.load(weight_path, return_numpy=load_state_as_np)
  File "/opt/conda/lib/python3.7/site-packages/paddle/framework/io.py", line 1001, in load
    path))
ValueError: `paddle.load` can not parse the file:uie-base/model_state.pdparams.

**Comment by wawltor** [comment]
看起来模型没有下载成功，建议把 ~/.paddlenlp整个目录删除，再重新使用
