### ISSUE TITLE
使用Pad对一维Tensor进行padding时报错

### ISSUE THREAD

**Issue by linjieccc** [PaddlePaddle/PaddleNLP#2334]
复现方法：
```python
import paddle
from paddlenlp.data import Pad

a = paddle.to_tensor([1, 2, 3])
b = paddle.to_tensor([4, 5])
Pad()([a, b])
```

报错信息：
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/data/collate.py", line 149, in __call__
    dtype=self._dtype if self._dtype is not None else np.int64)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

**Comment by guoshengCS** [comment]
这个主要是因为`paddlenlp.data`中的Pad这几个操作不支持传入Tensor，这里可否传入`numpy.ndarray`呢

**Comment by linjieccc** [comment]
多谢，应该是2.2.6之后对这个写法做了限制，已PR修复 #2333
