### ISSUE TITLE
KeyError: 'label' 运行ernie_matching 下的 官方train_pairwise.py脚本

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#2361]
我运行ernie_matching 下的 官方train_pairwise.py脚本，出现此问题：
脚本如下：
```python
python -u -m paddle.distributed.launch --gpus "0" train_pairwise.py --device gpu --batch_size 32 --learning_rate 2E-5 --eval_step 100 --train_file F:\\nlp_projects\\sample_text.csv --test_file F:\\nlp_projects\\sample_text.csv
```
报错：
```python
Traceback (most recent call last):
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_pairwise.py", line 240, in <module>
    do_train()
  File "train_pairwise.py", line 125, in do_train
    dev_ds = load_dataset(read_test, src_path=args.test_file, lazy=False)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddlenlp\datasets\dataset.py", line 110, in load_dataset
    return reader_instance.read(**custom_kwargs)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddlenlp\datasets\dataset.py", line 716, in read
    return MapDataset(list(examples))
  File "train_pairwise.py", line 110, in read_test
    label = row['label']
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\pandas\core\series.py", line 942, in __getitem__
    return self._get_value(key)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\pandas\core\series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'label'
INFO 2022-05-31 11:44:46,237 launch_utils.py:341] terminate all the procs
ERROR 2022-05-31 11:44:46,237 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-05-31 11:44:49,250 launch_utils.py:341] terminate all the procs
INFO 2022-05-31 11:44:49,250 launch.py:311] Local processes completed.
```

**Comment by tianxin1860** [comment]
是对代码做了什么修改吗？默认会加载 Lcqmc 数据集训练的。

**Comment by ArtificialZeng** [comment]
没有任何修改， 使用的官方代码。，官方数据

**Comment by ArtificialZeng** [comment]
> 

请问Lcqmc 是什么意思。  我用的官方 发布的 学术搜索数据

**Comment by ArtificialZeng** [comment]
> 是对代码做了什么修改吗？默认会加载 Lcqmc 数据集训练的。

知道Lcqmc的意思了。  现在还是报那个bug。 我的操作系统是win11.  其他的pp  ppnlp照着官网装的

**Comment by tianxin1860** [comment]
建议先不要用 AIStudio 学术搜索的数据来跑，先把 Examples 里的训练代码跑通，然后仿照 LCQMC 的数据格式替换成自己的业务数据，这样跑起来更容易一些。
