### ISSUE TITLE
运行in_batch_negative.py脚本报错：InvalidArgumentError: The DataType of equal Op's duplicable Variable Y must be consistent. The current variable type is (int64_t)

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#2367]
运行脚本：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/recall/in_batch_negative

cmd传参命令：
python -u -m paddle.distributed.launch --gpus "0" train_batch_neg.py --device gpu --save_dir F:\\迅雷下
载\\inbatch_model\\model_40\\ --batch_size 64 --learning_rate 5E-5 --epochs 3 --output_emb_size 256 --save_steps 10 --max_seq_length 64 --margin 0.2 --train_set_file E:\\google_download\\literature_search_data\\recall\\train.csv

报错如下：
```python 
 99%|█████████▊| 378M/383M [00:54<00:00, 6.51MB/s]
 99%|█████████▉| 379M/383M [00:54<00:00, 6.73MB/s]
 99%|█████████▉| 379M/383M [00:55<00:00, 6.60MB/s]
 99%|█████████▉| 381M/383M [00:55<00:00, 8.50MB/s]
100%|█████████▉| 382M/383M [00:55<00:00, 9.59MB/s]
100%|█████████▉| 383M/383M [00:55<00:00, 6.21MB/s]
100%|██████████| 383M/383M [00:55<00:00, 7.22MB/s]
W0531 15:50:48.425091 55964 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.0
W0531 15:50:48.453091 55964 device_context.cc:465] device: 0, cuDNN Version: 8.0.
[2022-05-31 15:51:12,228] [    INFO] - Weights from pretrained model not used in ErnieModel: ['cls.predictions.layer_norm.weight', 'cls.predictions.decoder_bias', 'cls.predictions.transform.bias', 'cls.predictions.transform.weight', 'cls.predictions.layer_norm.bias']
[2022-05-31 15:51:13,610] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/transformers/ernie/vocab.txt and saved to C:\Users\zazzy\.paddlenlp\models\ernie-1.0
[2022-05-31 15:51:13,610] [    INFO] - Downloading vocab.txt from https://bj.bcebos.com/paddlenlp/models/transformers/ernie/vocab.txt

  0%|          | 0.00/89.5k [00:00<?, ?B/s]
100%|██████████| 89.5k/89.5k [00:00<00:00, 3.39MB/s]
Traceback (most recent call last):
  File "train_batch_neg.py", line 177, in <module>
    do_train()
  File "train_batch_neg.py", line 154, in do_train
    title_token_type_ids=title_token_type_ids)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 704, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "F:\nlp_projects\ernie_matching\PaddleNLP\applications\neural_search\recall\in_batch_negative\batch_negative\model.py", line 50, in forward
    query_attention_mask)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 376, in __call__
    error_data.raise_new_exception()
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "F:\nlp_projects\ernie_matching\PaddleNLP\applications\neural_search\recall\in_batch_negative\base_model.py", line 53, in get_pooled_embedding
                             attention_mask=None):
        _, cls_embedding = self.ptm(input_ids, token_type_ids, position_ids,
                                    attention_mask)
                                    ~~~~~~~~~~~~~~~ <--- HERE

        if self.output_emb_size > 0:

    File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\zazzy\AppData\Local\Temp\tmpy7dda26p.py", line 94, in forward
        attention_mask,), (attention_mask,))
    File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
        out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 271, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 534, in forward
        ).astype(self.pooler.dense.weight.dtype) * -1e4,
    File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 347, in __impl__
        attrs={'axis': axis})
    File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\framework.py", line 3184, in append_op
        attrs=kwargs.get("attrs", None))
    File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
        for frame in traceback.extract_stack():

    InvalidArgumentError: The DataType of equal Op's duplicable Variable Y must be consistent. The current variable type is (int64_t), but the previous variable type is (int). (at ..\paddle\fluid\framework\operator.cc:1604)
      [operator < equal > error]  [operator < run_program > error]
INFO 2022-05-31 15:51:21,692 launch_utils.py:341] terminate all the procs
ERROR 2022-05-31 15:51:21,692 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-05-31 15:51:24,701 launch_utils.py:341] terminate all the procs
INFO 2022-05-31 15:51:24,701 launch.py:311] Local processes completed.
```

欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/2381
