### ISSUE TITLE
ner使用过程出现IndexError: list index out of range

### ISSUE THREAD

**Issue by EricHuang7** [PaddlePaddle/PaddleNLP#2389]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
版本信息:
  paddlenlp                     2.2.3
  paddlepaddle-gpu              2.3.0.post101
系统环境:
 Linux ; Python 3.7.12
复现:
from paddlenlp import Taskflow
ner = Taskflow("ner", entity_only=True)
ner("搞笑尼斯湖怪物玩蓝色风笛卡车司机帽")
ner("蜜蜡迷你蜂巢誓言蜡烛-4支蜡烛礼盒-森林图像")
报错:
Traceback (most recent call last):
  File "paddle_test.py", line 5, in <module>
    ner("蜜蜡迷你蜂巢誓言蜡烛-4支蜡烛礼盒-森林图像")
  File "/opt/conda/lib/python3.7/site-packages/paddlenlp/taskflow/taskflow.py", line 244, in __call__
    results = self.task_instance(inputs)
  File "/opt/conda/lib/python3.7/site-packages/paddlenlp/taskflow/task.py", line 171, in __call__
    results = self._postprocess(outputs)
  File "/opt/conda/lib/python3.7/site-packages/paddlenlp/taskflow/named_entity_recognition.py", line 145, in _postprocess
    inputs['all_pred_tags'])
  File "/opt/conda/lib/python3.7/site-packages/paddlenlp/taskflow/named_entity_recognition.py", line 87, in _decode
    tags_out.append(tag.split('-')[1])
IndexError: list index out of range

**Comment by wawltor** [comment]
建议升级到最新PaddleNLP的版本，看了一下这个bug已经修复了，谢谢您给我们指出问题！
pip install paddlenlp --upgrade

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。

**Comment by EricHuang7** [comment]
你好，你的邮件我已经收到，我将尽快回复，谢谢。
