### ISSUE TITLE
text_summarization bart 案例运行报错

### ISSUE THREAD

**Issue by chenchun0629** [PaddlePaddle/PaddleNLP#2397]
1）PaddleNLP和PaddlePaddle版本：paddlenlp==2.3.1，paddlepaddle-gpu==2.3.0
2）系统环境：linux
3)
```
%cd /content/PaddleNLP/examples/text_summarization/bart

!python run_summarization.py \
    --model_name_or_path=bart-base \
    --dataset_name=cnn_dailymail \
    --output_dir=output \
    --max_source_length=1024 \
    --max_target_length=142 \
    --learning_rate=1e-4 \
    --num_train_epochs=6 \
    --logging_steps=100 \
    --save_steps=1000 \
    --seed=42 \
    --train_batch_size=20 \
    --eval_batch_size=64 \
    --warmup_proportion=0.1 \
    --ignore_pad_token_for_loss=True \
    --device=gpu

/content/PaddleNLP/examples/text_summarization/bart
/usr/local/lib/python3.7/dist-packages/scipy/fft/__init__.py:97: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/usr/local/lib/python3.7/dist-packages/scipy/sparse/sputils.py:17: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
/usr/local/lib/python3.7/dist-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/lib/python3.7/dist-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
Namespace(adam_epsilon=1e-06, dataset_name='cnn_dailymail', device='gpu', eval_batch_size=64, ignore_pad_token_for_loss=True, learning_rate=0.0001, logging_steps=100, max_source_length=1024, max_steps=-1, max_target_length=142, min_target_length=0, model_name_or_path='bart-base', num_train_epochs=6, output_dir='output', save_steps=1000, scale_loss=32768, seed=42, train_batch_size=20, use_amp=False, warmup_proportion=0.1, warmup_steps=0, weight_decay=0.0)
[2022-06-02 07:39:10,156] [    INFO] - Already cached /root/.paddlenlp/models/bart-base/bart-base-vocab.json
[2022-06-02 07:39:10,157] [    INFO] - Already cached /root/.paddlenlp/models/bart-base/bart-base-merges.txt
[2022-06-02 07:39:10,384] [    INFO] - Already cached /root/.paddlenlp/models/bart-base/bart-base.pdparams
W0602 07:39:10.385138  1388 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 11.2, Runtime API Version: 10.2
W0602 07:39:10.388128  1388 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
[2022-06-02 07:39:19,476] [    INFO] - Loading train and dev dataset: cnn_dailymail
[2022-06-02 07:39:44,234] [    INFO] - Loaded train and dev dataset: cnn_dailymail
Epoch:   0% 0/6 [00:00<?, ?it/s]
Train step:   0% 0/14356 [00:00<?, ?it/s]Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 216, in _thread_loop
    self._thread_done_event)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/datasets/dataset.py", line 272, in __getitem__
    idx]) if self._transform_pipline else self.new_data[idx]
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/datasets/dataset.py", line 263, in _transform
    data = fn(data)
  File "/content/PaddleNLP/examples/text_summarization/bart/utils.py", line 37, in convert_example
    truncation=True)
TypeError: __call__() got an unexpected keyword argument 'max_length'


```

![image](https://user-images.githubusercontent.com/3328490/171581254-228e82a7-ca72-4c6f-a95c-e1aa2f9818ea.png)

**Comment by gongel** [comment]
你好， 用develop分支的代码可以的哈，或者等下今明天的PaddleNLP v2.3.2 版本。
