### ISSUE TITLE
运行ernie_matching训练时报错。

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#2432]
自建数据集，已经把特殊符号全删了。

0it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_pairwise.py", line 240, in <module>
    do_train()
  File "train_pairwise.py", line 125, in do_train
    dev_ds = load_dataset(read_test, src_path=args.test_file, lazy=False)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddlenlp\datasets\dataset.py", line 195, in load_dataset
    return reader_instance.read(**custom_kwargs)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\paddlenlp\datasets\dataset.py", line 828, in read
    return MapDataset(list(examples))
  File "train_pairwise.py", line 110, in read_test
    label = row['label']
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\pandas\core\series.py", line 942, in __getitem__
    return self._get_value(key)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\pandas\core\series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'label'
INFO 2022-06-07 17:51:26,078 launch_utils.py:343] terminate all the procs
INFO 2022-06-07 17:51:26,078 launch_utils.py:343] terminate all the procs
ERROR 2022-06-07 17:51:26,078 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2022-06-07 17:51:26,078 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-06-07 17:51:29,081 launch_utils.py:343] terminate all the procs
INFO 2022-06-07 17:51:29,081 launch_utils.py:343] terminate all the procs
INFO 2022-06-07 17:51:29,081 launch.py:402] Local processes completed.
INFO 2022-06-07 17:51:29,081 launch.py:402] Local processes completed.

**Comment by guoshengCS** [comment]
看着是`read_test`取数据时样本中没有label字段，这个可否再确认下，另外也可也提供下这个`read_test`的代码看下

**Comment by guoshengCS** [comment]
另外这个和 #2361 是一个问题不
