### ISSUE TITLE
ernie-3.0 token转换报错，该训练数据使用haggingface 的AutoTokenizer可以正常转换

### ISSUE THREAD

**Issue by thomaszheng** [PaddlePaddle/PaddleNLP#2433]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
环境：
paddlenlp                         2.3.2
paddlepaddle-gpu                  2.2.2.post111
datasets                          2.2.2

使用这个脚本加载自己的数据微调ner模型，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/run_token_cls.py

在训练数据转换token的预处理过程中出现这个报错

```
Reusing dataset ner_dataset (/root/.cache/huggingface/datasets/ner_dataset/Plain_text/1.0.0/6d2d18baeafd97084fd82aef64aca92760ebb8932648373ce3b74e6a40679352)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 328.04it/s]
dict_items([('train', Dataset({
    features: ['tokens', 'ner_tags'],
    num_rows: 642370
})), ('validation', Dataset({
    features: ['tokens', 'ner_tags'],
    num_rows: 38099
}))])
[2022-06-07 11:36:10,415] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.modeling.ErnieForTokenClassification'> to load 'ernie-3.0-medium-zh'.
[2022-06-07 11:36:10,415] [    INFO] - Already cached /root/.paddlenlp/models/ernie-3.0-medium-zh/ernie_3.0_medium_zh.pdparams
W0607 11:36:10.416649 2742750 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.1, Runtime API Version: 11.1
W0607 11:36:10.419196 2742750 device_context.cc:465] device: 0, cuDNN Version: 8.0.
W0607 11:36:12.182883 2742750 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.1, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Loading cached processed dataset at /root/.cache/huggingface/datasets/ner_dataset/Plain_text/1.0.0/6d2d18baeafd97084fd82aef64aca92760ebb8932648373ce3b74e6a40679352/cache-3c9404f50f23a55b.arrow
 35%|████████████████████████████████████████████████████████████████▋                                                                                                                       | 226/643 [00:43<01:19,  5.24ba/s]
Traceback (most recent call last):
  File "train_ner_pp.py", line 191, in <module>
    main()
  File "train_ner_pp.py", line 120, in main
    remove_columns=column_names)
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2364, in map
    desc=desc,
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 532, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 499, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/datasets/fingerprint.py", line 458, in wrapper
    out = func(self, *args, **kwargs)
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2738, in _map_single
    offset=offset,
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2614, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2306, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "train_ner_pp.py", line 40, in tokenize_and_align_labels
    return_length=True)
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2231, in __call__
    **kwargs)
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2428, in batch_encode
    **kwargs, )
  File "/datasetocr/dudaizhong/paddle_venv/lib/python3.6/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 1078, in _batch_encode_plus
    elif is_split_into_words and not isinstance(ids_or_pair_ids[0],
IndexError: list index out of range
```

报错代码的逻辑：

```
model_checkpoint = "ernie-3.0-medium-zh"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint, max_length=seq_max_length)

def tokenize_and_align_labels(examples, no_entity_id=0):
    tokenized_inputs = tokenizer(
        examples['tokens'],
        max_seq_len=seq_max_length,
        # We use this argument because the texts in our dataset are lists of words (with a label for each word).
        is_split_into_words=True,
        return_length=True)
    labels = []

    for i, label in enumerate(examples['ner_tags']):
        label_ids = label
        if len(tokenized_inputs['input_ids'][i]) - 2 < len(label_ids):  # 有词出现
            label_ids = label_ids[:len(tokenized_inputs['input_ids'][i]) - 2]
        label_ids = [no_entity_id] + label_ids + [no_entity_id]
        label_ids += [no_entity_id] * (len(tokenized_inputs['input_ids'][i]) - len(label_ids))

        labels.append(label_ids)
    tokenized_inputs["labels"] = labels
    return tokenized_inputs
```

**Comment by guoshengCS** [comment]
请问使用的具体的数据格式是怎样的呢，是和 [run_token_cls.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/run_token_cls.py) 中使用的 msra_ner 这样 `['谢', '谢', '各', '位', '！']` 的吗，可否提供来排查下，目前确实可能有些地方是和HF不完全一致的，另外想问下这个是部分数据有问题是吗，看着进度处理了一部分

**Comment by thomaszheng** [comment]
@guoshengCS 数据的格式是这样的`print(dataset['validation'][0:3])`:

```
{'tokens': [['【', '视', '频', '】', '站', '在', '沸', '水', '锅', '沿', '上', '的', '螃', '蟹'], ['兔', '子', '对', '一', '个', '小', '女', '孩', '有', '感', '觉'], ['还', '有', '姚', '晨', '的', '老', '公', '曹', '郁']], 'ner_tags': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4], [3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 2, 0, 0, 0, 1, 2]]}
```

报错主要是转换token时的报错：
```
dataset = load_dataset("./nerscript.py")  
print(dataset.items())
train_ds = dataset['train']
train_ds = train_ds.select(range(len(train_ds) - 1))
#数据转换为token时报错
train_ds = train_ds.map(tokenize_and_align_labels, batched=True, remove_columns=column_names)
```

同样的逻辑在训练数据`dataset['train']`上会报错，在验证集上可以`dataset['validation']`，可能是训练数据里面有脏数据。
这部分数据同hf的`AutoTokenizer` 是没有报错的，用法是:
`tokenized_inputs = tokenizer(examples["tokens"], truncation=True, is_split_into_words=True, max_length=seq_max_length)`

**Comment by guoshengCS** [comment]
可否把出错的数据提供些许case呢，我们用这些case来排查下问题

**Comment by thomaszheng** [comment]
可以，能否给我个邮箱之类的，我单独提供给你？

**Comment by thomaszheng** [comment]
@guoshengCS 定位到了，数据中有一个没有字符的句子
![image](https://user-images.githubusercontent.com/8412025/172532441-e9912df6-29f7-4391-99b5-c6ee4370e0fe.png)
加了个过滤逻辑就可以了
```
train_ds.filter(lambda example: example['tokens'] != []).map(tokenize_and_align_labels, batched=True, remove_columns=column_names)
```
