### ISSUE TITLE
paddlenlp 抽取问题

### ISSUE THREAD

**Issue by Han-YLun** [PaddlePaddle/PaddleNLP#2434]
环境如下：
paddlepaddle-gpu==2.3.0
paddlenlp==2.3.2
VERSION="18.04.5 LTS (Bionic Beaver)
使用的docker

代码如下：
```

@app.route('/nlp', methods=['post'])
def nlp():
    body = request.json
    schema = body.get('schema')
    keyword = body.get('keyword')
    if schema is None and keyword is not None:
        schema = keyword
    text = body.get('text')
    if schema is None or text is None:
        return jsonify({'status': 'false','msg':'keyword or text is not null'})

    ie = getTaskflow(schema)
    return jsonify(ie(text))

def getTaskflow(schema):
    strSchema = str(''.join(schema))
    ie = keyword2TaskflowMap.get(strSchema,None)
    if ie is None:
        ie = Taskflow('information_extraction', schema=schema)
        keyword2TaskflowMap[strSchema] = ie
        return ie
    return keyword2TaskflowMap[strSchema]
        

if __name__ == '__main__':
    PORT = int(os.environ.get('PORT', 32780))
    app.run(host='0.0.0.0', port=PORT)
```

通过接口对外暴漏,出现如下一些问题
1.
``` 
[2022-06-07 12:04:09,269] ERROR in app: Exception on /nlp [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/nlp-uie-rest/src/main.py", line 25, in nlp
    return jsonify(ie(text))
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/taskflow.py", line 314, in __call__
    results = self.task_instance(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/task.py", line 363, in __call__
    outputs = self._run_model(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 380, in _run_model
    results = self._multi_stage_predict(raw_inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 433, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 321, in _single_stage_predict
    self.input_mapping)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 367, in _auto_joiner
    for i in range(len(short_results[v])):
IndexError: list index out of range
```

2.抽取出来的数据由部分是这样的，并不是设置的schema,但是把text拿出来单独再请求，就没这么问题，是请求的太快了吗

<img width="499" alt="image" src="https://user-images.githubusercontent.com/44769070/172521103-321e2e77-20d3-449d-a8cb-2a2a9c819aca.png">

schema设置的是["疾病", "症状", "药品"]

**Comment by guoshengCS** [comment]
可否提供下第1个问题的case输入呢

**Comment by Han-YLun** [comment]
> 

text : 血栓恢复后是否可以用压力机泵压力泵可不可以用，下肢静脉血栓恢复后半年最好不要折腾！有时候会出现意想不到的问题和并发症。起码目前手上的疾病不会导致非常严重的后果！
[2022-06-08 02:48:27,839] ERROR in app: Exception on /nlp [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/nlp-uie-rest/src/main.py", line 26, in nlp
    return jsonify(ie(text))
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/taskflow.py", line 314, in __call__
    results = self.task_instance(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/task.py", line 363, in __call__
    outputs = self._run_model(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 380, in _run_model
    results = self._multi_stage_predict(raw_inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 433, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 321, in _single_stage_predict
    self.input_mapping)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 367, in _auto_joiner
    for i in range(len(short_results[v])):
IndexError: list index out of range
text : 体检阴道白带清洁度III、宫颈糜烂1度体检结果：阴道分泌物清洁度(白带清洁度)Ⅲ度，宫颈柱状上皮异位，去年B超，有盆腔积液，最近这两天腰很疼，是否与炎症和盆腔积液有关？因为一直在上班，去医院不方便，希望医生可以指导用药。咨询
[2022-06-08 02:48:27,949] ERROR in app: Exception on /nlp [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/nlp-uie-rest/src/main.py", line 26, in nlp
    return jsonify(ie(text))
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/taskflow.py", line 314, in __call__
    results = self.task_instance(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/task.py", line 363, in __call__
    outputs = self._run_model(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 380, in _run_model
    results = self._multi_stage_predict(raw_inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 433, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 321, in _single_stage_predict
    self.input_mapping)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 367, in _auto_joiner
    for i in range(len(short_results[v])):
IndexError: list index out of range

**Comment by Han-YLun** [comment]
我单独拿这些text去请求一遍，又是可以的

就是我说的这样
<img width="841" alt="image" src="https://user-images.githubusercontent.com/44769070/172521030-6f2abeae-dcd4-446d-bfff-73073634f2bb.png">

**Comment by Han-YLun** [comment]
第二个问题也是这样 抽取出来的内容是错误的，但是我再单独去请求一遍，就没问题了

**Comment by Han-YLun** [comment]
第二个问题的图片已经补充了

**Comment by Han-YLun** [comment]
我是使用go的gopool使用了100个协程池 我怀疑是不是请求的太快了

**Comment by Han-YLun** [comment]
[{Disease:[{Text:感染}] Symptom:[] Drug:[] BodyStructureInfoMap:[{Text:小便时，分泌物里有血丝你好,考虑感染等引起,局部卫生欠佳等引起.饮食清淡,多饮水,口服诺氟沙星,呋喃妥因和三金片.坚持服药一周,}]}]

text:小便时，分泌物里有血丝患者信息：女 22岁 病情描述：小便时，分泌物里有血丝你好,考虑感染等引起,局部卫生欠佳等引起.饮食清淡,多饮水,口服诺氟沙星,呋喃妥因和三金片.坚持服药一周,


在身体部位返回了text出现了问题,我重新用postman请求，就会正常
<img width="991" alt="image" src="https://user-images.githubusercontent.com/44769070/172527227-3bc0c10c-034e-4a53-b06d-704db27dfa33.png">

**Comment by Han-YLun** [comment]
可以能帮我先把抽取出来有问题的解决一下吗 就是第二个问题

**Comment by guoshengCS** [comment]
第一个问题 @linjieccc  可以帮忙看下吗 。第二个问题的话不太好确定，因为我们其实也不太了解您那边服务部署的情况

**Comment by Han-YLun** [comment]
第二个问题需要我提供更加详细的信息吗 我远程提供也行 

sudo nvidia-docker run -p 32780:32780 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=1 --name paddle_nlp -it  registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda11.4.1-cudnn8-gcc82 /bin/bash

我是使用了docker 启动 ，然后就是环境就上面的信息

**Comment by linjieccc** [comment]
@Han-YLun 第一个问题改成这个形式再试下呢，实例化一个Taskflow任务，通过set_schema来重置schema

```python
@app.route('/nlp', methods=['post'])
def nlp():
    body = request.json
    schema = body.get('schema')
    keyword = body.get('keyword')
    if schema is None and keyword is not None:
        schema = keyword
    text = body.get('text')
    if schema is None or text is None:
        return jsonify({'status': 'false','msg':'keyword or text is not null'})
    ie.set_schema(schema)
    return jsonify(ie(text))

ie = Taskflow('information_extraction', schema='')
```

**Comment by Han-YLun** [comment]
好的 我试试

第二个问题可以帮我看下嘛

**Comment by Han-YLun** [comment]
> @Han-YLun 第一个问题改成这个形式再试下呢，实例化一个Taskflow任务，通过set_schema来重置schema
> 
> ```python
> @app.route('/nlp', methods=['post'])
> def nlp():
>     body = request.json
>     schema = body.get('schema')
>     keyword = body.get('keyword')
>     if schema is None and keyword is not None:
>         schema = keyword
>     text = body.get('text')
>     if schema is None or text is None:
>         return jsonify({'status': 'false','msg':'keyword or text is not null'})
>     ie.set_schema(schema)
>     return jsonify(ie(text))
> 
> ie = Taskflow('information_extraction', schema='')
> ```

@linjieccc 设置了 还是会出现这个问题
```
text : 卵巢囊肿所就诊医院科室：上海普陀妇婴保健医院妇科可以考虑使用。对预防复发有一定作用，对治疗
  File "/projects/nlp-uie-rest/src/main.py", line 26, in nlp
    return jsonify(ie(text))
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/taskflow.py", line 314, in __call__
    results = self.task_instance(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/task.py", line 363, in __call__
    outputs = self._run_model(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 380, in _run_model
    results = self._multi_stage_predict(raw_inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 433, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 321, in _single_stage_predict
    self.input_mapping)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 367, in _auto_joiner
    for i in range(len(short_results[v])):
IndexError: list index out of range
```

改之后的代码:
```python
ie = Taskflow('information_extraction', schema='')
app = Flask(__name__)
@app.route('/ping', methods=['GET'])
def ping():
    return jsonify({'success': 'true'})

@app.route('/nlp', methods=['post'])
def nlp():
    body = request.json
    schema = body.get('schema')
    keyword = body.get('keyword')
    if schema is None and keyword is not None:
        schema = keyword
    text = body.get('text')
    if schema is None or text is None:
        return jsonify({'status': 'false','msg':'keyword or text is not null'})

    ie.set_schema(schema)
    print('text : ' + text)
    try:
        return jsonify(ie(text))
    except :
        traceback.print_exc()
        return jsonify({})
```

**Comment by linjieccc** [comment]
client端的代码能否也发下，我尝试复现下

**Comment by Han-YLun** [comment]
客户端用的go

```go

import (
	"encoding/json"
	"github.com/go-resty/resty/v2"
)

var (
	client = resty.New()
)
type NlpBody struct {
	Text   string   `json:"text"`
	Schema []string `json:"schema"`
}

func SendPaddleNlp(content string, schema []string) *resty.Response {
	if len(content) == 0 || len(schema) == 0 {
		return nil
	}

	nlpBody := NlpBody{Text: content, Schema: schema}
	b, _ := json.Marshal(nlpBody)
	response, err := client.R().
		SetHeader("Content-Type", "application/json").
		EnableTrace().
		SetBody(b).
		ForceContentType("application/json").
		Post(PADDLE_NLP_URL)

	if err != nil {
		return nil
	}
	return response
}

nlpQuestionRes := paddle.SendPaddleNlp(content, []string{"疾病", "症状", "药品", "身体部位"})

```

**Comment by linjieccc** [comment]
多线程情况下，如果只有一个Taskflow实例，一次只能有一个线程调用该实例。可以通过加锁的方式保证多个线程不会同时访问同一个实例

**Comment by tianchiguaixia** [comment]
可以使用 gunicorn -w 2 -b 0.0.0.0:10716 model_deploy:app
