### ISSUE TITLE
在本机一步步操作nlp的faq_system案例时，recall异常，生成向量异常

### ISSUE THREAD

**Issue by 65377692** [PaddlePaddle/PaddleNLP#2436]
版本信息如下:
paddlenlp          2.3.1,2.3.2,2.3.3
paddlepaddle       2.3.0
**设备1**：台式机
os：windows10
cpu：amd 5600g 6核12线程
mem：32g
python：3.8
**设备2**：笔记本
os：windows11 
cpu：amd 4750u 8核16线程
mem：40g
python：3.8
**设备3**：云服务器
os：centos8.3
cpu：intel 志强 2核
mem：8g
python：3.8

**问题一**：设备3上进行向量生成，内存满时被Kill退出，无论如何调参都降不了内存使用
参考命令：python3 ../feature_extract.py --device cpu --cpu_threads 2 --model_dir=./output --corpus_file "../data/corpus.csv"
从这个设备3上能看出一点，内存上升了的，说明在跑，也就是说内存足够的情况下，可能不会报错；

**问题二**：在设备1、2上，训练无问题，但是训练耗时是服务器2核cpu的3倍多，飞桨对amd框架支撑不足；
云服务器2c8g的设备是志强的2核cpu，两台本机都是amd的cpu；

**问题三**：设备1上训练出数据后，在其基础上进行recall，recall异常，报错信息如下：
(nlptest38) E:\nlp\PaddleNLP\applications\question_answering\faq_system>python -u -m paddle.distributed.launch --log_dir "recall_log/" recall.py  --device cpu --recall_result_dir "recall_result_dir" --recall_result_file "recall_result.txt" --params_path "checkpoints/model_189/model_state.pdparams" --hnsw_m 100 --hnsw_ef 100 --batch_size 64 --output_emb_size 256 --max_seq_length 64 --recall_num 10 --similar_text_pair "data/test_pair.csv" --corpus_file "data/corpus.csv"
LAUNCH INFO 2022-06-08 08:35:41,629 -----------  Configuration  ----------------------
LAUNCH INFO 2022-06-08 08:35:41,629 devices: None
LAUNCH INFO 2022-06-08 08:35:41,632 elastic_level: -1
LAUNCH INFO 2022-06-08 08:35:41,634 elastic_timeout: 30
LAUNCH INFO 2022-06-08 08:35:41,634 gloo_port: 6767
LAUNCH INFO 2022-06-08 08:35:41,634 host: None
LAUNCH INFO 2022-06-08 08:35:41,634 job_id: default
LAUNCH INFO 2022-06-08 08:35:41,634 legacy: False
LAUNCH INFO 2022-06-08 08:35:41,634 log_dir: recall_log/
LAUNCH INFO 2022-06-08 08:35:41,634 log_level: INFO
LAUNCH INFO 2022-06-08 08:35:41,634 master: None
LAUNCH INFO 2022-06-08 08:35:41,635 max_restart: 3
LAUNCH INFO 2022-06-08 08:35:41,635 nnodes: 1
LAUNCH INFO 2022-06-08 08:35:41,635 nproc_per_node: None
LAUNCH INFO 2022-06-08 08:35:41,635 rank: -1
LAUNCH INFO 2022-06-08 08:35:41,635 run_mode: collective
LAUNCH INFO 2022-06-08 08:35:41,635 server_num: None
LAUNCH INFO 2022-06-08 08:35:41,636 servers:
LAUNCH INFO 2022-06-08 08:35:41,636 trainer_num: None
LAUNCH INFO 2022-06-08 08:35:41,636 trainers:
LAUNCH INFO 2022-06-08 08:35:41,637 training_script: recall.py
LAUNCH INFO 2022-06-08 08:35:41,637 training_script_args: ['--device', 'cpu', '--recall_result_dir', 'recall_result_dir', '--recall_result_file', 'recall_result.txt', '--params_path', 'checkpoints/model_189/model_state.pdparams', '--hnsw_m', '100', '--hnsw_ef', '100', '--batch_size', '64', '--output_emb_size', '256', '--max_seq_length', '64', '--recall_num', '10', '--similar_text_pair', 'data/test_pair.csv', '--corpus_file', 'data/corpus.csv']
LAUNCH INFO 2022-06-08 08:35:41,637 with_gloo: 0
LAUNCH INFO 2022-06-08 08:35:41,638 --------------------------------------------------
LAUNCH INFO 2022-06-08 08:35:41,840 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2022-06-08 08:35:41,841 Run Pod: hguzeo, replicas 1, status ready
LAUNCH INFO 2022-06-08 08:35:41,848 Watching Pod: hguzeo, replicas 1, status running
[2022-06-08 08:35:44,256] [    INFO] - Already cached C:\Users\opens\.paddlenlp\models\rocketqa-zh-dureader-query-encoder\rocketqa-zh-dureader-vocab.txt
[2022-06-08 08:35:44,265] [    INFO] - Already cached C:\Users\opens\.paddlenlp\models\rocketqa-zh-dureader-query-encoder\rocketqa_zh_dureader_query_encoder.pdparams
[2022-06-08 08:35:53,357] [    INFO] - Loaded parameters from checkpoints/model_189/model_state.pdparams
[2022-06-08 08:35:53,380] [    INFO] - start build index..........
Traceback (most recent call last):
  File "recall.py", line 107, in <module>
    final_index = build_index(args, corpus_data_loader, inner_model)
  File "E:\nlp\PaddleNLP\applications\question_answering\faq_system\ann_util.py", line 52, in build_index
    for text_embeddings in model.get_semantic_embedding(data_loader):
  File "E:\nlp\PaddleNLP\applications\question_answering\faq_system\model.py", line 87, in get_semantic_embedding
    text_embeddings = self.get_pooled_embedding(
  File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 379, in __call__
    error_data.raise_new_exception()
  File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "E:\nlp\PaddleNLP\applications\question_answering\faq_system\model.py", line 65, in get_pooled_embedding
        # Note: cls_embedding is poolerd embedding with act tanh
        sequence_output, cls_embedding = self.ptm(input_ids, token_type_ids,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                                  position_ids, attention_mask)

    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
        return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
        outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\opens\AppData\Local\Temp\tmpeycqcksk.py", line 93, in forward
        attention_mask = paddle.jit.dy2static.convert_ifelse(attention_mask is
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
        out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 647, in forward
        ).astype(self.pooler.dense.weight.dtype) * -1e4,
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 342, in __impl__
        current_block(self).append_op(
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\framework.py", line 3615, in append_op
        op = Operator(
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\framework.py", line 2635, in __init__
        for frame in traceback.extract_stack():

    InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
      [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():5 != paddle::experimental::CppTypeToDataType<T>::Type():7.] (at C:\home\workspace\Paddle_release\paddle\phi\core\dense_tensor.cc:137)
      [operator < equal > error]  [operator < run_program > error]
LAUNCH INFO 2022-06-08 08:35:56,884 Pod failed
LAUNCH ERROR 2022-06-08 08:35:56,884 Container failed !!!
Container rank 0 status failed cmd ['D:\\anaconda3\\envs\\nlptest38\\python.exe', '-u', 'recall.py', '--device', 'cpu', '--recall_result_dir', 'recall_result_dir', '--recall_result_file', 'recall_result.txt', '--params_path', 'checkpoints/model_189/model_state.pdparams', '--hnsw_m', '100', '--hnsw_ef', '100', '--batch_size', '64', '--output_emb_size', '256', '--max_seq_length', '64', '--recall_num', '10', '--similar_text_pair', 'data/test_pair.csv', '--corpus_file', 'data/corpus.csv'] code 1 log recall_log/default.hguzeo.0.log
env {'ALLUSERSPROFILE': 'C:\\ProgramData', 'ANDROID_HOME': 'C:\\Users\\opens\\AppData\\Local\\Android\\Sdk', 'APPDATA': 'C:\\Users\\opens\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'DESKTOP-RN9IC69', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'CONDA_DEFAULT_ENV': 'nlptest38', 'CONDA_EXE': 'D:\\anaconda3\\condabin\\..\\Scripts\\conda.exe', 'CONDA_PREFIX': 'D:\\anaconda3\\envs\\nlptest38', 'CONDA_PROMPT_MODIFIER': '(nlptest38) ', 'CONDA_PYTHON_EXE': 'D:\\anaconda3\\python.exe', 'CONDA_SHLVL': '1', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'ES_HOME': 'E:\\elasticsearch-7.16.2', 'ES_JAVA_HOME': 'E:\\elasticsearch-7.16.2\\jdk', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'GOPATH': 'C:\\Users\\opens\\go', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\opens', 'JAVA_HOME': 'C:\\Program Files\\Java\\jdk1.8.0_261', 'LOCALAPPDATA': 'C:\\Users\\opens\\AppData\\Local', 'LOGONSERVER': '\\\\DESKTOP-RN9IC69', 'NUMBER_OF_PROCESSORS': '12', 'ONEDRIVE': 'C:\\Users\\opens\\OneDrive', 'ONEDRIVECONSUMER': 'C:\\Users\\opens\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'D:\\anaconda3\\envs\\nlptest38\\lib\\site-packages\\paddle\\fluid;D:\\anaconda3\\envs\\nlptest38\\lib\\site-packages\\paddle\\fluid\\..\\libs;D:\\anaconda3\\envs\\nlptest38;D:\\anaconda3\\envs\\nlptest38\\Library\\mingw-w64\\bin;D:\\anaconda3\\envs\\nlptest38\\Library\\usr\\bin;D:\\anaconda3\\envs\\nlptest38\\Library\\bin;D:\\anaconda3\\envs\\nlptest38\\Scripts;D:\\anaconda3\\envs\\nlptest38\\bin;D:\\anaconda3\\condabin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Git\\cmd;D:\\mysql-8.0.26-winx64\\bin;D:\\Program Files\\Go\\bin;C:\\Users\\opens\\AppData\\Local\\Android\\Sdk\\platform-tools;C:\\Users\\opens\\AppData\\Local\\Android\\Sdk\\tools;C:\\Program Files\\Java\\jdk1.8.0_261\\bin;F:\\nodejs;C:\\Program Files\\dotnet;D:\\Python\\Python310\\Scripts;D:\\Python\\Python310;C:\\Users\\opens\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Microsoft VS Code\\bin;C:\\Users\\opens\\go\\bin;D:\\anaconda3;D:\\anaconda3\\Library\\bin;D:\\anaconda3\\Scripts;C:\\Users\\opens\\AppData\\Roaming\\npm;C:\\Users\\opens\\.dotnet\\tools', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD', 'PROCESSOR_LEVEL': '25', 'PROCESSOR_REVISION': '5000', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PROMPT': '(nlptest38) $P$G', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\Windows', 'TEMP': 'C:\\Users\\opens\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\opens\\AppData\\Local\\Temp', 'USERDOMAIN': 'DESKTOP-RN9IC69', 'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-RN9IC69', 'USERNAME': 'opens', 'USERPROFILE': 'C:\\Users\\opens', 'VBOX_HWVIRTEX_IGNORE_SVM_IN_USE': '1', 'VBOX_MSI_INSTALL_PATH': 'C:\\Program Files\\Oracle\\VirtualBox\\', 'VS140COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\', 'WINDIR': 'C:\\Windows', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'PADDLE_MASTER': '192.168.56.1:52523', 'PADDLE_GLOBAL_SIZE': '1', 'PADDLE_LOCAL_SIZE': '1', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_TRAINER_ENDPOINTS': '192.168.56.1:52524', 'PADDLE_CURRENT_ENDPOINT': '192.168.56.1:52524', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_cpus': ''}
  File "E:\nlp\PaddleNLP\applications\question_answering\faq_system\model.py", line 87, in get_semantic_embedding
    text_embeddings = self.get_pooled_embedding(
  File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 379, in __call__
    error_data.raise_new_exception()
  File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "E:\nlp\PaddleNLP\applications\question_answering\faq_system\model.py", line 65, in get_pooled_embedding
        # Note: cls_embedding is poolerd embedding with act tanh
        sequence_output, cls_embedding = self.ptm(input_ids, token_type_ids,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                                  position_ids, attention_mask)

    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
        return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
        outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\opens\AppData\Local\Temp\tmpeycqcksk.py", line 93, in forward
        attention_mask = paddle.jit.dy2static.convert_ifelse(attention_mask is
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
        out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 647, in forward
        ).astype(self.pooler.dense.weight.dtype) * -1e4,
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 342, in __impl__
        current_block(self).append_op(
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\framework.py", line 3615, in append_op
        op = Operator(
    File "D:\anaconda3\envs\nlptest38\lib\site-packages\paddle\fluid\framework.py", line 2635, in __init__
        for frame in traceback.extract_stack():

    InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
      [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():5 != paddle::experimental::CppTypeToDataType<T>::Type():7.] (at C:\home\workspace\Paddle_release\paddle\phi\core\dense_tensor.cc:137)
      [operator < equal > error]  [operator < run_program > error]
LAUNCH INFO 2022-06-08 08:35:56,911 Exit code 1
**问题4**：拷贝设备3生成的output数据到设备1、2中，进行向量生成，内存未上升的情况下直接报如下异常：
(nlptest38) E:\nlp\PaddleNLP\applications\question_answering\faq_system>python feature_extract.py --device cpu --model_dir=output --corpus_file "data/corpus.csv"
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [matmul_v2_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]e[0m
I0608 09:02:55.956583 35736 fuse_pass_base.cc:57] ---  detected 74 subgraphs
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]e[0m
I0608 09:02:55.962445 35736 fuse_pass_base.cc:57] ---  detected 24 subgraphs
e[32m--- Running IR pass [matmul_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
I0608 09:02:56.168622 35736 fuse_pass_base.cc:57] ---  detected 74 subgraphs
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0608 09:02:56.333758 35736 analysis_predictor.cc:1007] ======= optimize end =======
I0608 09:02:56.334736 35736 naive_executor.cc:102] ---  skip [feed], feed -> token_type_ids
I0608 09:02:56.336690 35736 naive_executor.cc:102] ---  skip [feed], feed -> input_ids
I0608 09:02:56.343529 35736 naive_executor.cc:102] ---  skip [elementwise_div_2], fetch -> fetch
[2022-06-08 09:02:56,344] [    INFO] - Already cached C:\Users\opens\.paddlenlp\models\ernie-1.0\vocab.txt
  2%|███▍                                                                                                                                                                        | 99/5000 [00:00<00:01, 4405.27it/s]
Traceback (most recent call last):
  File "feature_extract.py", line 221, in <module>
    predictor.predict(corpus_list, tokenizer)
  File "feature_extract.py", line 187, in predict
    self.predictor.run()
ValueError: In user code:

    File "../export_model.py", line 63, in <module>
      paddle.jit.save(model, save_path)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 629, in wrapper
      func(layer, path, input_spec, **configs)
    File "/usr/local/python3/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 856, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/usr/local/python3/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/data/work/faq_system/model.py", line 65, in get_pooled_embedding
      sequence_output, cls_embedding = self.ptm(input_ids, token_type_ids,
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpg1fxnfae.py", line 93, in forward
      attention_mask = paddle.jit.dy2static.convert_ifelse(attention_mask is
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmpg1fxnfae.py", line 74, in true_fn_3
      ((input_ids == self.pad_token_id).astype)(self.pooler.dense.
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py", line 342, in __impl__
      current_block(self).append_op(
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3615, in append_op
      op = Operator(
    File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
      [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():5 != paddle::experimental::CppTypeToDataType<T>::Type():7.] (at C:\home\workspace\Paddle_release\paddle\phi\core\dense_tensor.cc:137)
      [operator < equal > error]

望大佬们给与指点，谢谢。

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/2482

您好，我无法复现您的问题，我尝试修复了一下，如果再有问题可以及时反馈

**Comment by yungongzi** [comment]
### 同样问题，复现步骤如下
**项目**：AiStudio上的教程项目**_动手搭建一套端到端文本语义检索系统_**
![image](https://user-images.githubusercontent.com/19431702/188480804-94b42c46-2257-4d48-88f5-b2e7fc34088e.png)

**设备**：台式机、win10和win11都试过
**环境**：CUDA10.1、cudnn7.6、python3.8、paddlenlp2.3.7、paddle-gpu2.3.2.post101
![image](https://user-images.githubusercontent.com/19431702/188479052-ea186d14-6bee-4294-b526-6d194673b36c.png)
**操作步骤**：
自顶向下 按教程一步步实现代码，在**召回模型**的**无监督语义索引**操作过程中，当进行到**模型训练**时
![image](https://user-images.githubusercontent.com/19431702/188479683-2172195f-af31-4c68-9151-0fb417cf7a87.png)
**报错：**
```
Traceback (most recent call last):
  File "E:/LearnSpace/PaddlePaddle/do2l_search/main.py", line 356, in <module>
    loss = model(
  File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:/LearnSpace/PaddlePaddle/do2l_search/main.py", line 253, in forward
    query_cls_embedding = self.get_pooled_embedding(
  File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 379, in __call__
    error_data.raise_new_exception()
  File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "E:/LearnSpace/PaddlePaddle/do2l_search/main.py", line 228, in get_pooled_embedding
        # Note: cls_embedding is poolerd embedding with act tanh
        sequence_output, cls_embedding = self.ptm(input_ids, token_type_ids,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                                  position_ids, attention_mask)

    File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\MRB26E~1.MON\AppData\Local\Temp\tmpgby28cma.py", line 195, in forward
	attention_mask = paddle.jit.dy2static.convert_ifelse(attention_mask is
    File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
	out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 977, in forward
	self.pooler.dense.weight.dtype) * -1e4,
    File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 342, in __impl__
	current_block(self).append_op(
    File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\framework.py", line 3615, in append_op
	op = Operator(
    File "E:\miniconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\framework.py", line 2635, in __init__
	for frame in traceback.extract_stack():

    InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
      [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():5 != paddle::experimental::CppTypeToDataType<T>::Type():7.] (at ..\paddle\phi\core\dense_tensor.cc:137)
      [operator < equal > error]  [operator < run_program > error]
```
是CUDA版本太低了吗？

**Comment by yungongzi** [comment]
### 已解决，数据类型不一致造成的
**修复**：
SimCSE模型构建时，input_ids、token_type_id、labels对应的数据类型为 int64
![image](https://user-images.githubusercontent.com/19431702/188486886-7a3034b3-b2d7-4eed-96e0-326bda5813c3.png)
![image](https://user-images.githubusercontent.com/19431702/188487064-8fafa610-974d-4362-8047-9e836862a4ad.png)
但在构建Dataloader时，返回的数据类型为int32
![image](https://user-images.githubusercontent.com/19431702/188487253-9f76e906-9611-4eb1-8bdb-52965c3df414.png)
![image](https://user-images.githubusercontent.com/19431702/188487275-81c877ba-31c2-44c7-9cff-817b7b283eb7.png)
需要把加载的数据类型改为int64
![image](https://user-images.githubusercontent.com/19431702/188487388-42707122-f1d4-4014-bc08-6b6f624eee32.png)

**这个BUG只在win上出现了，在Linux环境中未出现**

**Comment by UserShen-001** [comment]
您好，我在复现的时候也出现了：
问题三：设备1上训练出数据后，在其基础上进行recall，recall异常，出现了
LAUNCH INFO 2022-06-08 08:35:56,884 Pod failed
LAUNCH ERROR 2022-06-08 08:35:56,884 Container failed !!!
