### ISSUE TITLE
AttributeError: 'AlbertModel' object has no attribute 'pad_token_id'

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleNLP#2494]
- 版本、环境信息

```
Linux系统
Python 3.9.12
paddlenlp           2.2.5
paddlepaddle-gpu    2.2.0
```

- 问题

使用Sentence Transformers https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/sentence_transformers
训练albert-chinese-xlarge时出现报错

```python
Traceback (most recent call last):
  File "/home/train.py", line 229, in <module>
    do_train()
  File "/home/train.py", line 191, in do_train
    logits = model(
  File "/home/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lib/python3.9/site-packages/paddle/fluid/dygraph/parallel.py", line 701, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/home/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/model.py", line 37, in forward
    (query_input_ids != self.ptm.pad_token_id
  File "/home/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1110, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'AlbertModel' object has no attribute 'pad_token_id'
```

**Comment by ZHUI** [comment]
您好, albert 模型没有添加`pad_token_id `, 您可以参考下面pr添加
https://github.com/PaddlePaddle/PaddleNLP/pull/2495

**Comment by wjddd** [comment]
> 您好, albert 模型没有添加`pad_token_id `, 您可以参考下面pr添加 #2495

好的，感谢
