### ISSUE TITLE
model_config.json not exist after calling from_pretrained

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/PaddleNLP#2520]
## Description

If I load the model with `from_pretrained` method and copy the cache_dir(`/root/.paddlenlp/models/<model-name>`) to other dist or dir(eg, /path/to/model). Then, I load it with `from_pretrained` method. In this time, it will failed because of that there is no `model_config.json` file. 

You can use the following code to reproduce the problem:
```python
import shutil, os
from paddlenlp.transformers.model_utils import MODEL_HOME
from paddlenlp.transformers.bert.modeling import BertForPretraining

model_name = 'bert-base-uncased'
cache_dir = os.path.join(MODEL_HOME, model_name)
# keep the cache dir clean
shutil.rmtree(cache_dir, ignore_errors=True)

print('downloading bert weight file from server ...')
modle = BertForPretraining.from_pretrained(model_name)

print('loading bert weight from local dir ...')
BertForPretraining.from_pretrained(cache_dir)
```

the error trackstack info:

```shell
downloading bert weight file from server ...
[2022-06-15 06:30:01,097] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/transformers/bert-base-uncased.pdparams and saved to /root/.paddlenlp/models/bert-base-uncased
[2022-06-15 06:30:01,097] [    INFO] - Downloading bert-base-uncased.pdparams from https://bj.bcebos.com/paddlenlp/models/transformers/bert-base-uncased.pdparams
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 775M/775M [00:11<00:00, 72.2MB/s]
W0615 06:30:12.412072 25024 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0615 06:30:12.417645 25024 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
loading bert weight from local dir ...
[2022-06-15 06:30:36,430] [    INFO] - Downloading /root/.paddlenlp/models/bert-base-uncased/model_state.pdparams and saved to /root/.paddlenlp/models/bert-base-uncased
Traceback (most recent call last):
  File "a.py", line 14, in <module>
    BertForPretraining.from_pretrained(cache_dir)
  File "/root/project/paddle/PaddleNLP/paddlenlp/transformers/model_utils.py", line 253, in from_pretrained
    file_path, default_root)
  File "/root/project/paddle/PaddleNLP/paddlenlp/utils/downloader.py", line 156, in get_path_from_url
    assert is_url(url), "downloading from {} not a url".format(url)
AssertionError: downloading from /root/.paddlenlp/models/bert-base-uncased/model_state.pdparams not a url
```

I believe there are some issues in this method. 

## Environment

OS: `x86_64 GNU/Linux`

```shell
paddlefsl             1.1.0
paddlenlp             2.3.3
paddlepaddle-gpu      2.3.0
```

**Comment by wj-Mcat** [comment]
Fixed by https://github.com/PaddlePaddle/PaddleNLP/pull/2521
