### ISSUE TITLE
无法加载预训练权重

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleNLP#2533]
- 版本、环境信息

```
Linux Centos7
Python 3.9.12
paddlenlp           2.2.5
paddlepaddle-gpu    2.2.0
```

- 问题

该模型权重在[https://paddlenlp.readthedocs.io/zh/latest/model_zoo/transformers/ELECTRA/contents.html](url)中能找到，但是通过from_pretrained加载出现报错。
```
model_name = 'hfl/chinese-electra-180g-base-discriminator'
pretrained_model = ppnlp.transformers.AutoModel.from_pretrained(model_name)
tokenizer = ppnlp.transformers.AutoTokenizer.from_pretrained(model_name)
```

报错信息如下：

```
Traceback (most recent call last):
  File "/home/predict.py", line 23, in <module>
    pretrained_model = ppnlp.transformers.AutoModel.from_pretrained(model_name)
  File "/home/lib/python3.9/site-packages/paddlenlp/transformers/auto/modeling.py", line 299, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, task,
  File "/home/lib/python3.9/site-packages/paddlenlp/transformers/auto/modeling.py", line 194, in _from_pretrained
    raise RuntimeError(
RuntimeError: Can't load weights for 'hfl/chinese-electra-180g-base-discriminator'.
Please make sure that 'hfl/chinese-electra-180g-base-discriminator' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant modeling files(model_weights and model_config).

```

**Comment by yingyibiao** [comment]
您好，需要升级paddlenlp到2.3及之后的版本。

**Comment by yingyibiao** [comment]
![image](https://user-images.githubusercontent.com/52000032/173997636-1052b16e-6c68-4bd7-ad54-2ff6fdcdaf60.png)
我这边是能够正常加载的。

**Comment by wjddd** [comment]
> 您好，需要升级paddlenlp到2.3及之后的版本。

已解决，感谢。
