### ISSUE TITLE
语义搜索demo代码中，缺少代码问题以及预训练模型下载问题。

### ISSUE THREAD

**Issue by jlnguo** [PaddlePaddle/PaddleNLP#2538]
python = 3.6
paddlenlp = 2.2.1
paddlepaddle-gpu =2.2
在使用paddlenlp中的语义搜索模型的时候，把训练数据换成了自己的数据，进行[ERNIE 1.0](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/neural_search/recall/domain_adaptive_pretraining)的无监督训练，已经把自己的训练集更改成了要求的格式.
1---原始数据转换 jsonl 格式成功
2---数据ID化成功
3---由于Ernie预训练开始中没有run_static.sh文件，所以我在没有下载下面的ernie模型的前提下直接运行了脚本代码
```python
sh scripts/run_pretrain_static.sh。
![image](https://user-images.githubusercontent.com/59594041/174021903-ed73b089-29b7-4a8c-aad8-3163a33c075f.png)
然后得到了如下所示的错误，请问这个错误是否意味着是网上的模型被删除了？
**[2022-06-16 15:10:30,079] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/transformers/community/ernie-1.0-base-zh/vocab.txt and saved to /root/.paddlenlp/models/ernie-1.0-base-zh
[2022-06-16 15:10:30,079] [    INFO] - Downloading vocab.txt from https://bj.bcebos.com/paddlenlp/models/transformers/community/ernie-1.0-base-zh/vocab.txt
[2022-06-16 15:10:30,124] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/ernie-1.0-base-zh/vocab.txt failed with code 404!
Traceback (most recent call last):
  File "/root/anaconda3/envs/py36paddle/lib/python3.6/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 543, in from_pretrained
    file_path, default_root)
  File "/root/anaconda3/envs/py36paddle/lib/python3.6/site-packages/paddlenlp/utils/downloader.py", line 163, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "/root/anaconda3/envs/py36paddle/lib/python3.6/site-packages/paddlenlp/utils/downloader.py", line 200, in _download
    "{}!".format(url, req.status_code))
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/ernie-1.0-base-zh/vocab.txt failed with code 404!**
```

**Comment by ZHUI** [comment]
您好，可以升级一下您的 paddlenlp 版本`pip install paddlenlp --upgrade`

**Comment by shanliqiu** [comment]
nb
