### ISSUE TITLE
使用ErnieTiny文本近似度匹配模型转换失败

### ISSUE THREAD

**Issue by deep-rooteddz** [PaddlePaddle/PaddleNLP#254]
我是想在PaddleServing下部署，在模型推理时可以返回两种模式的内容，
因此修改了text_matching/sentence_transformers/model.py的forward()函数，具体如下：

```
def forward(self,
            query_input_ids,
            query_token_type_ids=None,
            title_mean=None,
            query_position_ids=None,
            query_attention_mask=None,
            ):
    query_token_embedding, _ = self.ptm(
        query_input_ids, query_token_type_ids, query_position_ids,
        query_attention_mask)
    query_token_embedding = self.dropout(query_token_embedding)
    query_attention_mask = paddle.unsqueeze(
        (query_input_ids != self.ptm.pad_token_id
            ).astype(self.ptm.pooler.dense.weight.dtype),
        axis=2)
    # Set token embeddings to 0 for padding tokens
    query_token_embedding = query_token_embedding * query_attention_mask
    query_sum_embedding = paddle.sum(query_token_embedding, axis=1)
    query_sum_mask = paddle.sum(query_attention_mask, axis=1)
    query_mean = query_sum_embedding / query_sum_mask

    if isinstance(title_mean, paddle.static.InputSpec) and title_mean.shape == (1,1024):
        sub = paddle.abs(paddle.subtract(query_mean, title_mean))
        projection = paddle.concat([query_mean, title_mean, sub], axis=-1)
        logits = self.classifier(projection)
        probs = F.softmax(logits)

        return probs
    else:
        return query_mean
```
用export_model.py转换模型，

```
# ErnieTinyTokenizer is special for ernie-tiny pretained model.
tokenizer = ppnlp.transformers.ErnieTinyTokenizer.from_pretrained(
    'ernie-tiny')

pretrained_model = ppnlp.transformers.ErnieModel.from_pretrained(
    "ernie-tiny")
model = SentenceTransformer(pretrained_model)

if args.params_path and os.path.isfile(os.path.join(__dir__, args.params_path)):
    state_dict = paddle.load(os.path.join(__dir__, args.params_path))
    model.set_dict(state_dict)
    print("Loaded parameters from %s" % args.params_path)
model.eval()

# Convert to static graph with specific input description
model = paddle.jit.to_static(
    model,
    input_spec=[
        paddle.static.InputSpec(
            shape=[None, None], dtype="int64"),     # query_input_ids
        paddle.static.InputSpec(
            shape=[None, None], dtype="int64"),     # query_token_type_ids
        paddle.static.InputSpec(
            shape=[None, None], dtype="float32")    # title_mean
    ])
# Save in static graph model.
paddle.jit.save(model, args.output_path)
# also save tokenizer for inference usage
tokenizer.save_pretrained(os.path.dirname(os.path.join(__dir__, args.output_path)))
```
但转换时报错：
![image](https://user-images.githubusercontent.com/76727820/114529435-866b7880-9c7c-11eb-80ab-0780868da12f.png)

如果model.py中的判断语句反过来写，可以正常转换，但是部署后并没有如预期那样，分两个不同分支返回正确结果，感觉判断语句并没有奏效。
比如当title_mean.shape为(1,3)时，PaddleServing返回的推理结果仍为probs而不是query_mean

```
if isinstance(title_mean, paddle.static.InputSpec) and title_mean.shape == (1,3):
    return query_mean
else:    
    sub = paddle.abs(paddle.subtract(query_mean, title_mean))
    projection = paddle.concat([query_mean, title_mean, sub], axis=-1)
    logits = self.classifier(projection)
    probs = F.softmax(logits)

    return probs
```

想请问上述情况要如何修改才能符合预期，非常感谢~

**Comment by TeslaZhao** [comment]
请问是哪个步骤执行错误？

**Comment by deep-rooteddz** [comment]
> 请问是哪个步骤执行错误？

运行python3 export_model.py时，在paddle.jit.save(model, args.output_path)这里报错
```
Traceback (most recent call last):
  File "export_model.py", line 67, in <module>
    paddle.jit.save(model, args.output_path)
  File "<decorator-gen-60>", line 2, in save
  File "/home/workspace/ObjectDetection/NLP/PaddleNLP/venv/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/workspace/ObjectDetection/NLP/PaddleNLP/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/workspace/ObjectDetection/NLP/PaddleNLP/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/jit.py", line 763, in save
    program_only=configs._program_only)
  File "<decorator-gen-79>", line 2, in save_inference_model
  File "/home/workspace/ObjectDetection/NLP/PaddleNLP/venv/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/workspace/ObjectDetection/NLP/PaddleNLP/venv/lib/python3.6/site-packages/paddle/fluid/framework.py", line 234, in __impl__
    return func(*args, **kwargs)
  File "/home/workspace/ObjectDetection/NLP/PaddleNLP/venv/lib/python3.6/site-packages/paddle/fluid/io.py", line 1382, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "/home/workspace/ObjectDetection/NLP/PaddleNLP/venv/lib/python3.6/site-packages/paddle/fluid/io.py", line 1171, in prepend_feed_ops
    i=i, name=name))
ValueError: The feeded_var_names[2]: 'title_mean' doesn't exist in pruned inference program. Please check whether 'title_mean' is a valid feed_var name, or remove it from feeded_var_names if 'title_mean' is not involved in the target_vars calculation.
```

**Comment by ZeyuChen** [comment]
@deep-rooteddz 为什么你需要分两个分支进行预测？

**Comment by jeff41404** [comment]
isinstance(title_mean, paddle.static.InputSpec) 会返回 False，如果要判断title_mean的存在性，最好用 is not None。
第1个paddle.jit.save报错的问题，因如上原因走到else分支返回query_mean，而query_mean的计算过程中没有用到title_mean，所以报错 'title_mean' is not involved in the target_vars calculation.
关于“感觉判断语句并没有奏效。比如当title_mean.shape为(1,3)时，PaddleServing返回的推理结果仍为probs而不是query_mean”的问题，也是因如上原因走到了else分支，能正确转换模型，但不是预期的分支

查看当前最新的代码，forward 已经更新，不用再传入title_mean，其中包含了计算title_mean的逻辑并返回probs，使用export_model.py能正常转换

**Comment by deep-rooteddz** [comment]
> isinstance(title_mean, paddle.static.InputSpec) 会返回 False，如果要判断title_mean的存在性，最好用 is not None。
> 第1个paddle.jit.save报错的问题，因如上原因走到else分支返回query_mean，而query_mean的计算过程中没有用到title_mean，所以报错 'title_mean' is not involved in the target_vars calculation.
> 关于“感觉判断语句并没有奏效。比如当title_mean.shape为(1,3)时，PaddleServing返回的推理结果仍为probs而不是query_mean”的问题，也是因如上原因走到了else分支，能正确转换模型，但不是预期的分支
> 
> 查看当前最新的代码，forward 已经更新，不用再传入title_mean，其中包含了计算title_mean的逻辑并返回probs，使用export_model.py能正常转换

好的，我明白啦，非常感谢~~已经换了思路成功实现了想要的功能

**Comment by deep-rooteddz** [comment]
> @deep-rooteddz 为什么你需要分两个分支进行预测？

如#239问题所说，想实现以下功能，
“给定 query 在海量 title 库中进行 ANN 检索，先基于 ERNIE_tiny 模型热启，然后进行 query、title 双塔结构的训练，然后通过对 title 端进行 ANN 建库，返回top10的检索结果”
之前的解决方案是
在使用PaddingServing部署时，传入query通过model的第一个分支计算出query_mean，query_mean结合预先计算好的title_mean通过ANN进行近邻检索，得到top10近似结果；最后将query_mean和top10的title_mean通过model的第二个分支计算相似概率probs。

最新的办法是，不分成两个分支去做了，把query_mean和probs都返回，暂时解决了这个问题。
不知道总体的思路有没有什么误区，还望赐教~~

**Comment by ZeyuChen** [comment]
> > @deep-rooteddz 为什么你需要分两个分支进行预测？
> 
> 如#239问题所说，想实现以下功能，
> “给定 query 在海量 title 库中进行 ANN 检索，先基于 ERNIE_tiny 模型热启，然后进行 query、title 双塔结构的训练，然后通过对 title 端进行 ANN 建库，返回top10的检索结果”
> 之前的解决方案是
> 在使用PaddingServing部署时，传入query通过model的第一个分支计算出query_mean，query_mean结合预先计算好的title_mean通过ANN进行近邻检索，得到top10近似结果；最后将query_mean和top10的title_mean通过model的第二个分支计算相似概率probs。
> 
> 最新的办法是，不分成两个分支去做了，把query_mean和probs都返回，暂时解决了这个问题。
> 不知道总体的思路有没有什么误区，还望赐教~~

我们会在下个月底的正式版，新增PaddleNLP语义索引方向的完整最佳实践，Staytune. 
@tianxin1860

**Comment by tianxin1860** [comment]
@deep-rooteddz 可以参考下我们新增的 PaddleNLP [语义索引 ](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/semantic_indexing) 解决方案
