### ISSUE TITLE
预训练模型，出TypeError错误：运行applications/neural_search/recall/domain_adaptive_pretraining

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#2557]
```python
 > building sapmles index mapping for train ...
make: 进入目录“/media/reclab/新加卷1/nlp_projects/ernie_matching/PaddleNLP/applications/neural_search/recall/domain_adaptive_pretraining/data_tools”
make: 对“default”无需做任何事。
make: 离开目录“/media/reclab/新加卷1/nlp_projects/ernie_matching/PaddleNLP/applications/neural_search/recall/domain_adaptive_pretraining/data_tools”
    using uint32 for data mapping...
    using:
     number of documents:            9
     sentences range:                [0, 33)
     total number of sentences:      33
     number of epochs:               2147483646
     maximum number of samples:      3200
     maximum sequence length:        509
     short sequence probability:     0.1
     short sequence ration (1/prob): 10
     seed:                           1234
    reached 3200 samples after 244 epochs ...
   number of empty documents: 0
   number of documents with one sentence: 0
   number of documents with long sentences: 0
   will create mapping for 3206 samples
 > done building sapmles index maping
 > saved the index mapping in ./data/baike_sample_train_indexmap_3200mns_509msl_0.10ssp_1234s.npy
 > elasped time to build and save samples mapping (seconds): 0.024965
 > loading indexed mapping from ./data/baike_sample_train_indexmap_3200mns_509msl_0.10ssp_1234s.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 3206
Traceback (most recent call last):
  File "run_pretrain_static.py", line 676, in <module>
    do_train(config)
  File "run_pretrain_static.py", line 388, in do_train
    current_step=global_step)
  File "run_pretrain_static.py", line 142, in create_pretrained_dataset
    data_world_size)
  File "run_pretrain_static.py", line 127, in loader
    consumed_samples=consumed_samples)
  File "/home/reclab/anaconda3/envs/pp230_gpu/lib/python3.7/site-packages/paddlenlp/utils/batch_sampler.py", line 120, in __init__
    self.num_samples = int(math.ceil(len(self.dataset) * 1.0 / self.nranks))
TypeError: object of type 'NoneType' has no len()
```
照着您说的，每个文档至少两行，编辑索引显示成功了。但是TypeError: object of type 'NoneType' has no len()

**Comment by ArtificialZeng** [comment]
照着您说的，每个文档至少两行，编辑索引显示成功了。但是TypeError: object of type 'NoneType' has no len()

**Comment by ArtificialZeng** [comment]
```python
python -u  -m paddle.distributed.launch \
    --gpus "0" \
    --log_dir "output/$task_name/log" \
    run_pretrain_static.py \
    --model_type "ernie" \
    --model_name_or_path "ernie-1.0-base-zh" \
    --input_dir "./data" \
    --output_dir "output/$task_name" \
    --max_seq_len 512 \
    --micro_batch_size 1 \
    --sharding_degree 1\
    --dp_degree 1 \
    --use_sharding false \
    --use_amp true \
    --use_recompute false \
    --max_lr 0.0001 \
    --min_lr 0.00001 \
    --max_steps 200 \
    --save_steps 5 \
    --checkpoint_steps 50 \
    --decay_steps 10 \
    --weight_decay 0.01\
    --warmup_rate 0.01 \
    --grad_clip 1.0 \
    --num_workers 1 \
    --logging_freq 20\
    --eval_freq 1000 \
    --device "gpu"
```
这是我的运行命令。 复制的你的，只是把批次 step改小了

**Comment by ArtificialZeng** [comment]
官方的数据 baike.txt 也跑不通

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0. 可以使用最新版

**Comment by ArtificialZeng** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0. 可以使用最新版

domain_adaptive_pretraining 是用不了吗

**Comment by ArtificialZeng** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0. 可以使用最新版

那基于domain_adaptive 后续怎么弄， 比如说 他这个任务本来是基于 ernie-gram-zh的

**Comment by ArtificialZeng** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0. 可以使用最新版

```python
 > building sapmles index mapping for valid ...
make: 进入目录“/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/model_zoo/ernie-1.0/data_tools”
make: 对“default”无需做任何事。
make: 离开目录“/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/model_zoo/ernie-1.0/data_tools”
    using uint32 for data mapping...
    using:
     number of documents:            13
     sentences range:                [981, 1033)
     total number of sentences:      52
     number of epochs:               2147483646
     maximum number of samples:      640640
     maximum sequence length:        509
     short sequence probability:     0.1
     short sequence ration (1/prob): 10
     seed:                           1234
    reached 640640 samples after 40297 epochs ...
   number of empty documents: 0
   number of documents with one sentence: 0
   number of documents with long sentences: 0
   will create mapping for 640654 samples
 > done building sapmles index maping
 > saved the index mapping in /media/reclab/新加卷/nlp_projects/ernie_matching/PaddleNLP/applications/neural_search/recall/domain_adaptive_pretraining/data/baike_sample_valid_indexmap_640640mns_509msl_0.10ssp_1234s.npy
 > elasped time to build and save samples mapping (seconds): 0.122083
 > loading indexed mapping from /media/reclab/新加卷/nlp_projects/ernie_matching/PaddleNLP/applications/neural_search/recall/domain_adaptive_pretraining/data/baike_sample_valid_indexmap_640640mns_509msl_0.10ssp_1234s.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 640654
Traceback (most recent call last):
  File "run_pretrain.py", line 615, in <module>
    do_train(config)
  File "run_pretrain.py", line 403, in do_train
    current_step=global_step)
  File "run_pretrain.py", line 133, in create_pretrained_dataset
    test_dl = loader(test_ds, 0)
  File "run_pretrain.py", line 119, in loader
    consumed_samples=consumed_samples)
  File "/home/reclab/anaconda3/envs/pp230_gpu/lib/python3.7/site-packages/paddlenlp/utils/batch_sampler.py", line 120, in __init__
    self.num_samples = int(math.ceil(len(self.dataset) * 1.0 / self.nranks))
TypeError: object of type 'NoneType' has no len()
INFO 2022-06-20 10:49:37,372 launch_utils.py:343] terminate all the procs
```

**Comment by ZHUI** [comment]
你好，您打印一下，这里的 self.dataset 是 None，建议加一个 --split 8,1,1 的参数
