### ISSUE TITLE
Ernie预训练，报错，用的官方baike.txt数据。 TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#2572]
> building sapmles index mapping for valid ...
make: 进入目录“/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/model_zoo/ernie-1.0/data_tools”
make: 对“default”无需做任何事。
make: 离开目录“/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/model_zoo/ernie-1.0/data_tools”
    using uint32 for data mapping...
    using:
     number of documents:            7
     sentences range:                [750, 785)
     total number of sentences:      35
     number of epochs:               2147483646
     maximum number of samples:      640640
     maximum sequence length:        509
     short sequence probability:     0.1
     short sequence ration (1/prob): 10
     seed:                           1234
    reached 640640 samples after 89587 epochs ...
   number of empty documents: 0
   number of documents with one sentence: 0
   number of documents with long sentences: 0
   will create mapping for 640640 samples
 > done building sapmles index maping
 > saved the index mapping in /media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/model_zoo/ernie-1.0/data_tools/data/baike_sample_valid_indexmap_640640mns_509msl_0.10ssp_1234s.npy
 > elasped time to build and save samples mapping (seconds): 0.136406
 > loading indexed mapping from /media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/model_zoo/ernie-1.0/data_tools/data/baike_sample_valid_indexmap_640640mns_509msl_0.10ssp_1234s.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 640640
Traceback (most recent call last):
  File "run_pretrain.py", line 615, in <module>
    do_train(config)
  File "run_pretrain.py", line 403, in do_train
    current_step=global_step)
  File "run_pretrain.py", line 133, in create_pretrained_dataset
    test_dl = loader(test_ds, 0)
  File "run_pretrain.py", line 119, in loader
    consumed_samples=consumed_samples)
  File "/home/reclab/anaconda3/envs/pp230_gpu/lib/python3.7/site-packages/paddlenlp/utils/batch_sampler.py", line 120, in __init__
    self.num_samples = int(math.ceil(len(self.dataset) * 1.0 / self.nranks))
TypeError: object of type 'NoneType' has no len()
INFO 2022-06-20 11:08:20,152 launch_utils.py:343] terminate all the procs
INFO 2022-06-20 11:08:20,152 launch_utils.py:343] terminate all the procs
ERROR 2022-06-20 11:08:20,152 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2022-06-20 11:08:20,152 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-06-20 11:08:24,156 launch_utils.py:343] terminate all the procs
INFO 2022-06-20 11:08:24,156 launch_utils.py:343] terminate all the procs
INFO 2022-06-20 11:08:24,156 launch.py:402] Local processes completed.
INFO 2022-06-20 11:08:24,156 launch.py:402] Local processes completed.

欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by ArtificialZeng** [comment]
[baike.txt](https://github.com/PaddlePaddle/PaddleNLP/files/8937246/baike.txt)
wget baike那个数据， 处理成npy npz了

**Comment by ZHUI** [comment]
你可以就使用一个 issue，不然信息很乱。上个isssue已经回复过你了。建议加一个 --split 8,1,1 的参数

**Comment by ArtificialZeng** [comment]
> 你可以就使用一个 issue，不然信息很乱。上个isssue已经回复过你了。建议加一个 --split 8,1,1 的参数

加了此参数能训练了， 那原来预训练是放在 neural_search/recall 里面的却炮不了。 之前是默认用ernie-gram-zh 不知能用起来否？

run_pretrain_static.py

**Comment by ArtificialZeng** [comment]
> 你可以就使用一个 issue，不然信息很乱。上个isssue已经回复过你了。建议加一个 --split 8,1,1 的参数

 > building dataset index ...
Traceback (most recent call last):
  File "run_pretrain_static.py", line 682, in <module>
    do_train(config)
  File "run_pretrain_static.py", line 394, in do_train
    current_step=global_step)
  File "run_pretrain_static.py", line 86, in create_pretrained_dataset
    dataset_type='ernie')
  File "/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/applications/neural_search/recall/domain_adaptive_pretraining/data_tools/dataset_utils.py", line 524, in build_train_valid_test_datasets
    dataset_type=dataset_type)
  File "/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/applications/neural_search/recall/domain_adaptive_pretraining/data_tools/dataset_utils.py", line 545, in _build_train_valid_test_datasets
    indexed_dataset = get_indexed_dataset_(data_prefix, None, skip_warmup)
  File "/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/applications/neural_search/recall/domain_adaptive_pretraining/data_tools/dataset_utils.py", line 641, in get_indexed_dataset_
    indexed_dataset = make_indexed_dataset(data_prefix, data_impl, skip_warmup)
  File "/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/applications/neural_search/recall/domain_adaptive_pretraining/data_tools/dataset_utils.py", line 118, in make_indexed_dataset
    return MMapIndexedDataset(data_prefix)
  File "/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/applications/neural_search/recall/domain_adaptive_pretraining/data_tools/dataset_utils.py", line 57, in __init__
    self._pointers = process_datas["sents"]
  File "/home/reclab/anaconda3/envs/pp230_gpu/lib/python3.7/site-packages/numpy/lib/npyio.py", line 260, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'sents is not a file in the archive'

如果我用 run_pretrain_static.py 脚本 报错

**Comment by ZHUI** [comment]
如沟通`ernie-gram-zh`预训练暂不支持
