### ISSUE TITLE
ernie-tiny tokenizer can't save the special_tokens_map.json file when it exists

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/PaddleNLP#2577]
## Introduciton

when  loading ErnieTinyTokenizer instance `from_pretrained('ernie-tiny')`, and there is already resouce file in cache dir, eg: `special_tokens_map.json`, it will raise the following exception:

```shell
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2022-06-20 05:40:50,305] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/transformers/ernie_tiny/vocab.txt and saved to /root/.paddlenlp/models/ernie-tiny
[2022-06-20 05:40:50,306] [    INFO] - Downloading vocab.txt from https://bj.bcebos.com/paddlenlp/models/transformers/ernie_tiny/vocab.txt
100%|██████████████████████████████████████████████████████████████████████████████| 459k/459k [00:00<00:00, 26.4MB/s]
[2022-06-20 05:40:50,377] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/transformers/ernie_tiny/spm_cased_simp_sampled.model and saved to /root/.paddlenlp/models/ernie-tiny
[2022-06-20 05:40:50,377] [    INFO] - Downloading spm_cased_simp_sampled.model from https://bj.bcebos.com/paddlenlp/models/transformers/ernie_tiny/spm_cased_simp_sampled.model
100%|████████████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 31.7MB/s]
[2022-06-20 05:40:50,448] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/transformers/ernie_tiny/dict.wordseg.pickle and saved to /root/.paddlenlp/models/ernie-tiny
[2022-06-20 05:40:50,449] [    INFO] - Downloading dict.wordseg.pickle from https://bj.bcebos.com/paddlenlp/models/transformers/ernie_tiny/dict.wordseg.pickle
100%|██████████████████████████████████████████████████████████████████████████████| 158M/158M [00:02<00:00, 71.2MB/s]
[2022-06-20 05:40:58,054] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/ernie-tiny/tokenizer_config.json
[2022-06-20 05:40:58,054] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/ernie-tiny/special_tokens_map.json
Traceback (most recent call last):
  File "cli.py", line 49, in <module>
    ernie_tiny()
  File "cli.py", line 45, in ernie_tiny
    tokenizer = ErnieTinyTokenizer.from_pretrained('ernie-tiny')
  File "/root/project/paddle/PaddleNLP/paddlenlp/transformers/tokenizer_utils_base.py", line 1694, in from_pretrained
    tokenizer.save_pretrained(default_root)
  File "/root/project/paddle/PaddleNLP/paddlenlp/transformers/tokenizer_utils_base.py", line 1789, in save_pretrained
    filename_prefix=filename_prefix,
  File "/root/project/paddle/PaddleNLP/paddlenlp/transformers/tokenizer_utils_base.py", line 1814, in _save_pretrained
    self.save_resources(save_directory)
  File "/root/project/paddle/PaddleNLP/paddlenlp/transformers/ernie/tokenizer.py", line 599, in save_resources
    shutil.copyfile(source_path, save_path)
  File "/root/miniconda3/envs/paddle2.3/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/root/.paddlenlp/models/ernie-tiny/spm_cased_simp_sampled.model' and '/root/.paddlenlp/models/ernie-tiny/spm_cased_simp_sampled.model' are the same file
```

## environment

```shell
paddlenlp             2.3.3
paddlepaddle-gpu      2.3.0
```

## Anaysis

I wanted to test how big the impact with https://github.com/PaddlePaddle/PaddleNLP/pull/2521, so I do some experiments with the following code:

```python
TokenizerClasses = [
    BertTokenizer, GPTTokenizer, ErnieTokenizer, ErnieTinyTokenizer, AlbertTokenizer, BartTokenizer
]
result = []
for TokenizerClass in tqdm(TokenizerClasses):
    resource_names = list(TokenizerClass.pretrained_resource_files_map['vocab_file'].keys())
    for resource_name in tqdm(resource_names):
        if 'large' in resource_name:
            continue
        cache_dir = f'/root/.paddlenlp/models/{resource_name}'
        try:
            TokenizerClass.from_pretrained(resource_name, verbose=False)
            result.append([get_class_name(TokenizerClass), resource_name, True])
        except:
            result.append([get_class_name(TokenizerClass),resource_name, False])
        shutil.rmtree(cache_dir, ignore_errors=True)

print(tabulate(result, headers=['bert-class', 'resouce', 'result'], tablefmt='grid'))
```

the result is :

```shell
+--------------------+------------------------------------+----------+
| bert-class         | resouce                            | result   |
+====================+====================================+==========+
| BertTokenizer      | bert-base-uncased                  | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | bert-base-cased                    | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | bert-base-multilingual-uncased     | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | bert-base-multilingual-cased       | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | bert-base-chinese                  | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | bert-wwm-chinese                   | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | bert-wwm-ext-chinese               | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | macbert-base-chinese               | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | simbert-base-chinese               | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | uer/chinese-roberta-base           | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | uer/chinese-roberta-medium         | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | uer/chinese-roberta-6l-768h        | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | uer/chinese-roberta-small          | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | uer/chinese-roberta-mini           | True     |
+--------------------+------------------------------------+----------+
| BertTokenizer      | uer/chinese-roberta-tiny           | True     |
+--------------------+------------------------------------+----------+
| GPTTokenizer       | gpt3-175B-en                       | True     |
+--------------------+------------------------------------+----------+
| GPTTokenizer       | gpt3-89B-en                        | True     |
+--------------------+------------------------------------+----------+
| GPTTokenizer       | gpt3-13B-en                        | True     |
+--------------------+------------------------------------+----------+
| GPTTokenizer       | gpt3-1.3B-en                       | True     |
+--------------------+------------------------------------+----------+
| GPTTokenizer       | gpt2-xl-en                         | True     |
+--------------------+------------------------------------+----------+
| GPTTokenizer       | gpt2-medium-en                     | True     |
+--------------------+------------------------------------+----------+
| GPTTokenizer       | gpt2-en                            | True     |
+--------------------+------------------------------------+----------+
| GPTTokenizer       | gpt2-small-en                      | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-1.0                          | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-1.0-base-zh                  | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-tiny                         | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-2.0-base-zh                  | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-2.0-base-en                  | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-2.0-base-en-finetuned-squad  | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-gen-base-en                  | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | rocketqa-zh-dureader-query-encoder | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | rocketqa-zh-dureader-para-encoder  | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | rocketqa-v1-marco-query-encoder    | False    |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | rocketqa-v1-marco-para-encoder     | False    |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | rocketqa-zh-dureader-cross-encoder | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | rocketqa-v1-marco-cross-encoder    | False    |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-3.0-base-zh                  | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-3.0-xbase-zh                 | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-3.0-medium-zh                | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-3.0-mini-zh                  | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-3.0-micro-zh                 | True     |
+--------------------+------------------------------------+----------+
| ErnieTokenizer     | ernie-3.0-nano-zh                  | True     |
+--------------------+------------------------------------+----------+
| ErnieTinyTokenizer | ernie-tiny                         | False    |
+--------------------+------------------------------------+----------+
| AlbertTokenizer    | albert-base-v1                     | True     |
+--------------------+------------------------------------+----------+
| AlbertTokenizer    | albert-base-v2                     | True     |
+--------------------+------------------------------------+----------+
| AlbertTokenizer    | albert-chinese-tiny                | True     |
+--------------------+------------------------------------+----------+
| AlbertTokenizer    | albert-chinese-small               | True     |
+--------------------+------------------------------------+----------+
| AlbertTokenizer    | albert-chinese-base                | True     |
+--------------------+------------------------------------+----------+
| BartTokenizer      | bart-base                          | True     |
+--------------------+------------------------------------+----------+
```

**Comment by wj-Mcat** [comment]
There are some failures shown at above table. So I start to get the reason:

```python
tokenizer = ErnieTokenizer.from_pretrained('rocketqa-v1-marco-cross-encoder')
```

it will raise the following exception:

```shell
[2022-06-20 06:36:34,110] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/transformers/rocketqa/rocketqa-v1-marco-vocab.txt and saved to /root/.paddlenlp/models/rocketqa-v1-marco-cross-encoder
[2022-06-20 06:36:37,588] [    INFO] - Downloading rocketqa-v1-marco-vocab.txt from https://bj.bcebos.com/paddlenlp/models/transformers/rocketqa/rocketqa-v1-marco-vocab.txt
[2022-06-20 06:41:27,254] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/rocketqa/rocketqa-v1-marco-vocab.txt failed with code 404!
Traceback (most recent call last):
  File "/root/project/paddle/PaddleNLP/paddlenlp/transformers/tokenizer_utils_base.py", line 1555, in from_pretrained
    file_path, default_root)
  File "/root/project/paddle/PaddleNLP/paddlenlp/utils/downloader.py", line 164, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "/root/project/paddle/PaddleNLP/paddlenlp/utils/downloader.py", line 201, in _download
    "{}!".format(url, req.status_code))
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/rocketqa/rocketqa-v1-marco-vocab.txt failed with code 404!
```

## Conclusion

the vocab_file configured in [code]() doesn't exist.  and all of `rocketqa-v1-marco-query-encoder`, `rocketqa-v1-marco-para-encoder`, `rocketqa-v1-marco-cross-encoder   ` hold the same reason. 

files not founding:

* https://bj.bcebos.com/paddlenlp/models/transformers/rocketqa/rocketqa-v1-marco-vocab.txt

**Comment by wj-Mcat** [comment]
I have tested all of tokenzier in paddlenlp with all configured model name to do `from_pretrained`.  you can use the following code to reproduce the issue:

```python
def get_all_tokenzier():
    import importlib
    module = importlib.import_module('paddlenlp.transformers')
    classes = []
    for name in dir(module):
        if name.startswith('__') or name in ['AutoTokenizer']:
            continue
        if name.endswith('Tokenizer'):
            classes.append(
                getattr(module, name)
            )
    return classes
    

def tokenizer():

    TokenizerClasses = get_all_tokenzier()
    result = []
    for TokenizerClass in tqdm(TokenizerClasses):
        if not hasattr(TokenizerClass, 'pretrained_resource_files_map'):
            continue
        if not TokenizerClass.pretrained_resource_files_map.get('vocab_file', None):
            continue
        resource_names = list(TokenizerClass.pretrained_resource_files_map['vocab_file'].keys())
        for resource_name in tqdm(resource_names):
            if 'large' in resource_name:
                continue
            cache_dir = f'/root/.paddlenlp/models/{resource_name}'
            try:
                TokenizerClass.from_pretrained(resource_name, verbose=False)
                # result.append([get_class_name(TokenizerClass), resource_name, True])
            except:
                result.append([get_class_name(TokenizerClass),resource_name, False])
            shutil.rmtree(cache_dir, ignore_errors=True)

    print(tabulate(result, headers=['bert-class', 'resouce', 'result'], tablefmt='grid'))
```

the result is:

```shell
+-----------------------+------------------------------------------------------+----------+
| bert-class            | resouce                                              | result   |
+=======================+======================================================+==========+
| BertJapaneseTokenizer | cl-tohoku/bert-base-japanese                         | False    |
+-----------------------+------------------------------------------------------+----------+
| BertJapaneseTokenizer | cl-tohoku/bert-base-japanese-whole-word-masking      | False    |
+-----------------------+------------------------------------------------------+----------+
| BertJapaneseTokenizer | cl-tohoku/bert-base-japanese-char                    | False    |
+-----------------------+------------------------------------------------------+----------+
| BertJapaneseTokenizer | cl-tohoku/bert-base-japanese-char-whole-word-masking | False    |
+-----------------------+------------------------------------------------------+----------+
| CTRLTokenizer         | ctrl                                                 | False    |
+-----------------------+------------------------------------------------------+----------+
| CTRLTokenizer         | sshleifer-tiny-ctrl                                  | False    |
+-----------------------+------------------------------------------------------+----------+
| ChineseBertTokenizer  | ChineseBERT-base                                     | False    |
+-----------------------+------------------------------------------------------+----------+
| ErnieTokenizer        | rocketqa-v1-marco-query-encoder                      | False    |
+-----------------------+------------------------------------------------------+----------+
| ErnieTokenizer        | rocketqa-v1-marco-para-encoder                       | False    |
+-----------------------+------------------------------------------------------+----------+
| ErnieTokenizer        | rocketqa-v1-marco-cross-encoder                      | False    |
+-----------------------+------------------------------------------------------+----------+
| LukeTokenizer         | luke-base                                            | False    |
+-----------------------+------------------------------------------------------+----------+
| XLMTokenizer          | xlm-mlm-en-2048                                      | False    |
+-----------------------+------------------------------------------------------+----------+
| XLMTokenizer          | xlm-mlm-ende-1024                                    | False    |
+-----------------------+------------------------------------------------------+----------+
| XLMTokenizer          | xlm-mlm-enfr-1024                                    | False    |
+-----------------------+------------------------------------------------------+----------+
| XLMTokenizer          | xlm-mlm-enro-1024                                    | False    |
+-----------------------+------------------------------------------------------+----------+
| XLMTokenizer          | xlm-mlm-tlm-xnli15-1024                              | False    |
+-----------------------+------------------------------------------------------+----------+
| XLMTokenizer          | xlm-mlm-xnli15-1024                                  | False    |
+-----------------------+------------------------------------------------------+----------+
| XLMTokenizer          | xlm-clm-enfr-1024                                    | False    |
+-----------------------+------------------------------------------------------+----------+
| XLMTokenizer          | xlm-clm-ende-1024                                    | False    |
+-----------------------+------------------------------------------------------+----------+
| XLMTokenizer          | xlm-mlm-17-1280                                      | False    |
+-----------------------+------------------------------------------------------+----------+
| XLMTokenizer          | xlm-mlm-100-1280                                     | False    |
+-----------------------+------------------------------------------------------+----------+
```

**Comment by wj-Mcat** [comment]
When I use the `paddlenlp` package which don't contains the https://github.com/PaddlePaddle/PaddleNLP/pull/2521 feature, and the result is :

```shell
+-----------------------+------------------------------------------------------+----------+
| bert-class            | resouce                                              | result   |
+=======================+======================================================+==========+
| BertJapaneseTokenizer | cl-tohoku/bert-base-japanese                         | False    |
+-----------------------+------------------------------------------------------+----------+
| BertJapaneseTokenizer | cl-tohoku/bert-base-japanese-whole-word-masking      | False    |
+-----------------------+------------------------------------------------------+----------+
| BertJapaneseTokenizer | cl-tohoku/bert-base-japanese-char                    | False    |
+-----------------------+------------------------------------------------------+----------+
| BertJapaneseTokenizer | cl-tohoku/bert-base-japanese-char-whole-word-masking | False    |
+-----------------------+------------------------------------------------------+----------+
| ChineseBertTokenizer  | ChineseBERT-base                                     | False    |
+-----------------------+------------------------------------------------------+----------+
| ErnieTokenizer        | rocketqa-v1-marco-query-encoder                      | False    |
+-----------------------+------------------------------------------------------+----------+
| ErnieTokenizer        | rocketqa-v1-marco-para-encoder                       | False    |
+-----------------------+------------------------------------------------------+----------+
| ErnieTokenizer        | rocketqa-v1-marco-cross-encoder                      | False    |
+-----------------------+------------------------------------------------------+----------+
```

## Conclusion

there are some tokenizer influenced by https://github.com/PaddlePaddle/PaddleNLP/pull/2521 maaaaay be, and I will do more experiments on it.

**Comment by wj-Mcat** [comment]
XLM requires additional dependency package, so it failured when tested.  you can refer to the [source code](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/xlm/tokenizer.py#L653)

```python
from paddlenlp.transformers.xlm.tokenizer import XLMTokenizer 
tokenizer = XLMTokenizer.from_pretrained('xlm-mlm-en-2048')
```
