### ISSUE TITLE
LukeTokenizer object has no attribute '_entity_file'

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/PaddleNLP#2581]
## Introduction

When I try to save pretrained tokenizer, there are some issues described below. 

## Simple Code

```python
from paddlenlp.transformers.luke.tokenizer import LukeTokenizer 
tokenizer = LukeTokenizer.from_pretrained('luke-base')

tokenizer.save_pretrained('./luke-base')
```

here is my error stacktrace info:

```shell
[2022-06-20 07:57:18,719] [    INFO] - Already cached /root/.paddlenlp/models/luke-base/vocab.json
[2022-06-20 07:57:18,720] [    INFO] - Already cached /root/.paddlenlp/models/luke-base/merges.txt
[2022-06-20 07:57:18,720] [    INFO] - Already cached /root/.paddlenlp/models/luke-base/entity_vocab.json
[2022-06-20 07:57:19,303] [    INFO] - tokenizer config file saved in ./luke-base/tokenizer_config.json
[2022-06-20 07:57:19,303] [    INFO] - Special tokens file saved in ./luke-base/special_tokens_map.json
Traceback (most recent call last):
  File "notebooK_cli.py", line 72, in <module>
    ernie_tiny()
  File "notebooK_cli.py", line 69, in ernie_tiny
    tokenizer.save_pretrained('./luke-base')
  File "/root/miniconda3/envs/paddle2.3/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 1784, in save_pretrained
    filename_prefix=filename_prefix, )
  File "/root/miniconda3/envs/paddle2.3/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 1808, in _save_pretrained
    self.save_resources(save_directory)
  File "/root/miniconda3/envs/paddle2.3/lib/python3.7/site-packages/paddlenlp/transformers/gpt/tokenizer.py", line 513, in save_resources
    shutil.copyfile(getattr(self, "_%s" % name), save_path)
AttributeError: 'LukeTokenizer' object has no attribute '_entity_file'
```

**Comment by guoshengCS** [comment]
Maybe we should not allow `getattr(self, "_%s" % name)` to be `None` in https://github.com/PaddlePaddle/PaddleNLP/pull/2578 , and add these not existing attributes. Otherwise, these resource files would not be saved.

**Comment by wj-Mcat** [comment]
Fixed by merged PR: https://github.com/PaddlePaddle/PaddleNLP/pull/2631, so I will close it.
