### ISSUE TITLE
ChineseBertTokenizer got an unexpected keyword argument 'tokenizer_class'

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/PaddleNLP#2584]
## Introduction

When I init the ChineseBertTokenizer, it raise the exception with the following code:

* reproduction code
```python
from paddlenlp.transformers.chinesebert.tokenizer import ChineseBertTokenizer
tokenizer = ChineseBertTokenizer.from_pretrained('ChineseBERT-base')
```

* exception

```shell
[2022-06-20 09:38:52,656] [    INFO] - Already cached /root/.paddlenlp/models/ChineseBERT-base/vocab.txt
[2022-06-20 09:38:52,656] [    INFO] - Already cached /root/.paddlenlp/models/ChineseBERT-base/tokenizer_config.json
Traceback (most recent call last):
  File "notebooK_cli.py", line 76, in <module>
    ernie_tiny()
  File "notebooK_cli.py", line 72, in ernie_tiny
    tokenizer = ChineseBertTokenizer.from_pretrained('ChineseBERT-base')
  File "/root/miniconda3/envs/paddle2.3/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 1626, in from_pretrained
    tokenizer = cls(*init_args, **init_kwargs)
  File "/root/miniconda3/envs/paddle2.3/lib/python3.7/site-packages/paddlenlp/transformers/utils.py", line 86, in __impl__
    init_func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'tokenizer_class'
```

**Comment by guoshengCS** [comment]
There is some bug to be fixed.
