### ISSUE TITLE
neural_search/ranking/ernie_matching 用ernie-3.0-medium-zh来代替原来的ernie-gram-zh模型报错

### ISSUE THREAD

**Issue by yrg5101** [PaddlePaddle/PaddleNLP#2589]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP 2.3.0.dev，PaddlePaddle2.3.0
2）系统环境：Windows，python：3.7

PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/ranking/ernie_matching/ 使用这个进行排序，
现在想用ernie-3.0-medium-zh来代替原来的ernie-gram-zh模型， 在export_model.py中进行动态模型导出静态模型，做的修改如下：

原来：
if __name__ == "__main__":
    # If you want to use ernie1.0 model, plesace uncomment the following code
    # tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')
    # pretrained_model = ppnlp.transformers.ErnieModel.from_pretrained("ernie-1.0")

    pretrained_model = ppnlp.transformers.ErnieGramModel.from_pretrained(
        'ernie-gram-zh')
    tokenizer = ppnlp.transformers.ErnieGramTokenizer.from_pretrained(
        'ernie-gram-zh')
    model = PairwiseMatching(pretrained_model)

修改之后：
if __name__ == "__main__":
    # If you want to use ernie1.0 model, plesace uncomment the following code
    # tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')
    # pretrained_model = ppnlp.transformers.ErnieModel.from_pretrained("ernie-1.0")

    pretrained_model = ppnlp.transformers.ErnieGramModel.from_pretrained(
        'ernie-gram-zh')
    tokenizer = ppnlp.transformers.ErnieGramTokenizer.from_pretrained(
        'ernie-3.0-medium-zh')
    model = PairwiseMatching(pretrained_model)

报错：
[2022-06-20 22:57:05,782] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/ernie-3.0-medium-zh\model_state.pdparams and saved to C:\Users\Administrator\.paddlenlp\models\ernie-3.0-medium-zh
[2022-06-20 22:57:05,783] [    INFO] - Downloading model_state.pdparams from https://bj.bcebos.com/paddlenlp/models/community/ernie-3.0-medium-zh\model_state.pdparams
[2022-06-20 22:57:05,998] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/community/ernie-3.0-medium-zh\model_state.pdparams failed with code 404!
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\tx\PaddleNLP\paddlenlp\transformers\model_utils.py", line 253, in from_pretrained
    file_path, default_root)
  File "C:\Users\Administrator\Desktop\tx\PaddleNLP\paddlenlp\utils\downloader.py", line 164, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "C:\Users\Administrator\Desktop\tx\PaddleNLP\paddlenlp\utils\downloader.py", line 201, in _download
    "{}!".format(url, req.status_code))
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community/ernie-3.0-medium-zh\model_state.pdparams failed with code 404!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/tx/PaddleNLP/applications/neural_search/ranking/ernie_matching/export_model.py", line 40, in <module>
    'ernie-3.0-medium-zh')
  File "C:\Users\Administrator\Desktop\tx\PaddleNLP\paddlenlp\transformers\model_utils.py", line 257, in from_pretrained
    f"Can't load weights for '{pretrained_model_name_or_path}'.\n"
RuntimeError: Can't load weights for 'ernie-3.0-medium-zh'.
Please make sure that 'ernie-3.0-medium-zh' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant modeling files(model_weights and model_config).

**Comment by guoshengCS** [comment]
ernie-3.0-medium-zh 需要使用 `ErnieModel` 和 `ErnieTokenizer` 来`from_pretrained`创建使用，或者更推荐通过`AutoModel`和`AutoTokenizer` 来使用以减少切换出错的可能

**Comment by yrg5101** [comment]
谢谢 已经解决

**Comment by ArtificialZeng** [comment]
> 谢谢 已经解决

怎么解决的
