### ISSUE TITLE
git提供的部署按提示装faster_tokenizers反而报错

### ISSUE THREAD

**Issue by flymushroom** [PaddlePaddle/PaddleNLP#2596]
在用uie下方提供的部署方式时（predictor），会提示warning，安装faster_tokenizers,安装之后反而报错，卸掉就又好了。
如下：
```python
[2022-06-21 17:50:47,894] [ WARNING] - Can't find the faster_tokenizers package, please ensure install faster_tokenizers correctly. You can install faster_tokenizers by `pip install faster_tokenizers`(Currently only work for linux platform).
安装后报错：
2022-06-21 17:47:00.073 | ERROR    | __main__:pre:86 - Traceback (most recent call last):
  File "fastapi_uie_server.py", line 82, in pre
    res = predictor.predict([t.text])
  File "/root/fastapi_uie/uie_predictor.py", line 461, in predict
    results = self._multi_stage_predict(input_data)
  File "/root/fastapi_uie/uie_predictor.py", line 402, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "/root/fastapi_uie/uie_predictor.py", line 169, in _single_stage_predict
    return_dict=False)
  File "/root/miniconda3/envs/fastapi_uie/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2231, in __call__
    **kwargs)
  File "/root/miniconda3/envs/fastapi_uie/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2428, in batch_encode
    **kwargs, )
TypeError: _batch_encode_plus() got an unexpected keyword argument 'max_seq_len'

2022-06-21 17:47:00.073 | ERROR    | __main__:pre:87 - _batch_encode_plus() got an unexpected keyword argument 'max_seq_len'
```

**Comment by joey12300** [comment]
您好，这里paddlenlp版本是多少呢？可以更新到最新版本的paddlenlp，并且安装faster_tokenizer试试 `pip install faster_tokenizer`

**Comment by flymushroom** [comment]
> 您好，这里paddlenlp版本是多少呢？可以更新到最新版本的paddlenlp，并且安装faster_tokenizer试试 `pip install faster_tokenizer`

昨天现装的，都是最新版

**Comment by xiaojinwhu** [comment]
同样的问题
