### ISSUE TITLE
INVALID_ARGUMENT : Failed to load model with error: Unknown model file format version.

### ISSUE THREAD

**Issue by leon-cas** [PaddlePaddle/PaddleNLP#2602]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：paddlenlp 2.3.1, paddlepaddle-gpu 2.3.0.post101, paddlepaddle 2.2.0, onnx 1.6.0, onnxruntime-gpu 1.3.0
2）系统环境：linux, python3, cudnn 7.6, Cuda 10.1.243
- 复现信息：如为报错，请给出复现环境、复现步骤
1. 导出onnx模型成功
2. 但部署模型时，报如下错误信息：
[Paddle2ONNX] Start to parse PaddlePaddle model(model file: ./checkpoint/goods/export/inference.pdmodel, parameters file: ./checkpoint/goods/export/inference.pdiparams
[Paddle2ONNX] Model loaded, start to converting...
[Paddle2ONNX] Use opset_version = 12 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
>>> [InferBackend] Use GPU to inference ...
Traceback (most recent call last):
  File "deploy/python/infer_gpu.py", line 89, in <module>
    main()
  File "deploy/python/infer_gpu.py", line 62, in main
    predictor = UIEPredictor(args)
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 134, in __init__
    args.model_path_prefix, device=args.device, use_fp16=args.use_fp16)
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 88, in __init__
    onnx_model, sess_options=sess_options, providers=providers)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: Unknown model file format version.

从网上相关资料发现往往是onnx和onnxruntime的版本不对，尝试按照onnx， onnxrutime，以及cuda的版本进行onnx和onnxrutime的版本对齐，但还是报上述错误信息。
--cuda和onnx版本对应关系：https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements   
<img width="713" alt="image" src="https://user-images.githubusercontent.com/5744496/174809955-cbb78fdd-fcb1-4f29-a7df-5e0881cfc9dc.png">

-onnx和onnx runtime版本对应：https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md
<img width="853" alt="image" src="https://user-images.githubusercontent.com/5744496/174809880-168bd639-7ed5-4e7a-9e81-45720f1a50ef.png">

**Comment by jiangjiajun** [comment]
Hi, @leon-cas  

在导出ONNX格式时，使用了最新的IR，而此IR只有最新的ONNXRuntime支持。

看你上面提到是要在GPU上部署， 最新的ONNXRuntime依赖cuda11

因此建议你升级cuda到11.4， 同时升级到最新的onnxruntime

**Comment by leon-cas** [comment]
@jiangjiajun 

升级onnx:1.9.0,  onnxruntime-gpu:1.11.1

导出onnx:  
W0622 17:32:42.767597 36414 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.1
W0622 17:32:42.771904 36414 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.

部署onnx:
>>> [InferBackend] Creating Engine ...
[Paddle2ONNX] Start to parse PaddlePaddle model(model file: ./checkpoint/goods/export/inference.pdmodel, parameters file: ./checkpoint/goods/export/inference.pdiparams
[Paddle2ONNX] Model loaded, start to converting...
[Paddle2ONNX] Use opset_version = 15 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
>>> [InferBackend] Use GPU to inference ...
2022-06-22 17:34:06.141657533 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:552 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
provider1 ['CUDAExecutionProvider']
provider2 ['CPUExecutionProvider']
2022-06-22 17:34:07.665592335 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:552 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
provider3 ['CPUExecutionProvider']
Traceback (most recent call last):
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 97, in __init__
    assert 'CUDAExecutionProvider' in self.predictor.get_providers()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deploy/python/infer_gpu.py", line 89, in <module>
    main()
  File "deploy/python/infer_gpu.py", line 62, in main
    predictor = UIEPredictor(args)
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 134, in __init__
    args.model_path_prefix, device=args.device, use_fp16=args.use_fp16)
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 100, in __init__
    f"The environment for GPU inference is not set properly. "
AssertionError: The environment for GPU inference is not set properly. A possible cause is that you had installed both onnxruntime and onnxruntime-gpu. Please run the following commands to reinstall: 
 1) pip uninstall -y onnxruntime onnxruntime-gpu 
 2) pip install onnxruntime-gpu

但系统中只安装了onnxruntime-gpu，并未安装onnxruntime； 从打印信息看provider中没有创建CUDAExecutionProvider， 只有CPUExecutionProvider

**Comment by jiangjiajun** [comment]
只安装onnxruntime-gpu 无需再安装onnxruntime
两个同时安装会出现覆盖的情况，
```
pip uninstall onnxruntime
pip uninstall onnxruntime-gpu
```
然后
```
pip install onnxruntime-gpu --upgrade
```

**Comment by leon-cas** [comment]
@jiangjiajun hi, 系统中并未安装onnxruntime。 刚刚也重新尝试了你提到的重新卸载、安装。错误和上面一样，
>>> [InferBackend] Creating Engine ...
[Paddle2ONNX] Start to parse PaddlePaddle model(model file: ./checkpoint/goods/export/inference.pdmodel, parameters file: ./checkpoint/goods/export/inference.pdiparams
[Paddle2ONNX] Model loaded, start to converting...
[Paddle2ONNX] Use opset_version = 15 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
>>> [InferBackend] Use GPU to inference ...
2022-06-22 19:17:00.189311529 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:552 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
provider1 ['CUDAExecutionProvider']
provider2 ['CPUExecutionProvider']
2022-06-22 19:17:01.712151993 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:552 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
provider3 ['CPUExecutionProvider']
Traceback (most recent call last):
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 97, in __init__
    assert 'CUDAExecutionProvider' in self.predictor.get_providers()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deploy/python/infer_gpu.py", line 89, in <module>
    main()
  File "deploy/python/infer_gpu.py", line 62, in main
    predictor = UIEPredictor(args)
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 134, in __init__
    args.model_path_prefix, device=args.device, use_fp16=args.use_fp16)
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 100, in __init__
    f"The environment for GPU inference is not set properly. "
AssertionError: The environment for GPU inference is not set properly. A possible cause is that you had installed both onnxruntime and onnxruntime-gpu. Please run the following commands to reinstall: 
 1) pip uninstall -y onnxruntime onnxruntime-gpu 
 2) pip install onnxruntime-gpu

**Comment by jiangjiajun** [comment]
你可以按照这里的命令来执行一下吗
pip uninstall onnxruntime
pip uninstall onnxruntime-gpu

分别执行uninstall

**Comment by leon-cas** [comment]
1.卸载onnxruntime: pip uninstall onnxruntime
WARNING: Skipping onnxruntime as it is not installed.

2.卸载onnxruntime-gpu: pip uninstall onnxruntime-gpu
Found existing installation: onnxruntime-gpu 1.11.1
Uninstalling onnxruntime-gpu-1.11.1:
  Would remove:
    /opt/conda/bin/onnxruntime_test
    /opt/conda/lib/python3.7/site-packages/onnxruntime/*
    /opt/conda/lib/python3.7/site-packages/onnxruntime_gpu-1.11.1.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled onnxruntime-gpu-1.11.1

3.安装onnxruntime-gpu: pip install onnxruntime-gpu --upgrade
Requirement already satisfied: protobuf in /opt/conda/lib/python3.7/site-packages (from onnxruntime-gpu) (3.19.0)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.7/site-packages (from onnxruntime-gpu) (1.21.6)
Requirement already satisfied: flatbuffers in /opt/conda/lib/python3.7/site-packages (from onnxruntime-gpu) (2.0)
Installing collected packages: onnxruntime-gpu
Successfully installed onnxruntime-gpu-1.11.1

4. 重新导出onnx: python export_model.py --model_path=./checkpoint/goods/model_best --output_path=./checkpoint/goods/export
W0623 10:11:30.565337 36995 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.1
W0623 10:11:30.569659 36995 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
load model from: ./checkpoint/goods/model_best/model_state.pdparams

5.重新部署：python deploy/python/infer_gpu.py --model_path_prefix ./checkpoint/goods/export/inference
>>> [InferBackend] Creating Engine ...
[Paddle2ONNX] Start to parse PaddlePaddle model(model file: ./checkpoint/goods/export/inference.pdmodel, parameters file: ./checkpoint/goods/export/inference.pdiparams
[Paddle2ONNX] Model loaded, start to converting...
[Paddle2ONNX] Use opset_version = 15 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
>>> [InferBackend] Use GPU to inference ...
2022-06-23 10:12:16.356604341 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:552 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
providers: ['CUDAExecutionProvider']
get_providers: ['CPUExecutionProvider']
Traceback (most recent call last):
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 97, in __init__
    assert 'CUDAExecutionProvider' in self.predictor.get_providers()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deploy/python/infer_gpu.py", line 89, in <module>
    main()
  File "deploy/python/infer_gpu.py", line 62, in main
    predictor = UIEPredictor(args)
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 134, in __init__
    args.model_path_prefix, device=args.device, use_fp16=args.use_fp16)
  File "/home/qingyun/dev/kg/concept/uie/deploy/python/uie_predictor.py", line 100, in __init__
    f"The environment for GPU inference is not set properly. "
AssertionError: The environment for GPU inference is not set properly. A possible cause is that you had installed both onnxruntime and onnxruntime-gpu. Please run the following commands to reinstall: 
 1) pip uninstall -y onnxruntime onnxruntime-gpu 
 2) pip install onnxruntime-gpu

**Comment by jiangjiajun** [comment]
可能你先检查下onnxruntime的安装问题哈，这个看起来跟paddlenlp的代码无关。

onnxruntime-gpu最新版本依赖cuda-11，这个也需要满足

**Comment by leon-cas** [comment]
@jiangjiajun  谢谢，升级cuda-11后，问题fix了
