### ISSUE TITLE
DuIE代码运行在evaluate方法的报错，主要显示为生成的predict_eval.json的spo_list为空，请大神帮忙看一下原因？

### ISSUE THREAD

**Issue by weihua1379** [PaddlePaddle/PaddleNLP#2636]
paddle版本：paddlenlp 2.3.1
平台：windows10

![image](https://user-images.githubusercontent.com/54572449/175458894-b621067f-cae1-40d7-96e3-c416fb5b9065.png)
在这段代码中，生成spo_list始终为初始的空列表，大家有遇到这样的情况吗？是怎么回事？
100%|██████████| 125/125 [05:35<00:00,  2.68s/it]
Traceback (most recent call last):
  File "K:/项目代码/paddlenlp/examples/information_extraction/DuIE/run_duie.py", line 349, in <module>
    precision, recall, f1 = evaluate(model, criterion, test_data_loader, eval_file_path,
  File "K:\项目代码\daily_learn\venv\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "K:\项目代码\daily_learn\venv\lib\site-packages\paddle\fluid\dygraph\base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "K:/项目代码/paddlenlp/examples/information_extraction/DuIE/run_duie.py", line 139, in evaluate
    precision, recall, f1 = get_precision_recall_f1(file_path,
  File "K:\项目代码\paddlenlp\examples\information_extraction\DuIE\utils.py", line 179, in get_precision_recall_f1
    f1 = float(
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by weihua1379** [comment]
由于生成的predict_eval.json文件中"spo_list": []，导致后面就报错'NoneType' object has no attribute 'group'，而"spo_list": []的主要原因为在decoding函数中生成的list(set(flatten_predictions))只有0和1，帮忙看一下啥问题啊
![image](https://user-images.githubusercontent.com/54572449/175459686-7a0c4b49-9625-4d58-9ab1-013ba789406b.png)

**Comment by LemonNoel** [comment]
``spo_list=[]``可能是模型没有收敛导致没有预测正确的spo。如果``get_precision_recall_f1``函数代码没有修改的话，这里报错应该是[re_official_evaluation.py](https://github.com/PaddlePaddle/PaddleNLP/blob/03dcbeff745fb18f230c5bc07a2e3c0d23b8617a/examples/information_extraction/DuIE/re_official_evaluation.py#L215-L231)中文件读取失败导致的，可以打印下``ret_info``，贴下更多的报错信息吗？

**Comment by weihua1379** [comment]
> 文件读取失败导致的，可以打印下`ret_info`，贴下更多的报错信息吗
但是re_official_evaluation.py返回的是评估信息，而我的生成的predict_eval.json文件已经在上面粘贴出来了，spo_list是[]，也就是出问题应该在之前把，我看了一下代码，好像问题在我第一张截图的地方，生成的flatten_predictions只有[0,1],导致在if 1 < cls_label <= 56 and (cls_label + 55) in flatten_predictions:这里进不去，最后subject_id_list为[],也就spo_list为空了

**Comment by weihua1379** [comment]
> `spo_list=[]`可能是模型没有收敛导致没有预测正确的spo。如果`get_precision_recall_f1`函数代码没有修改的话，这里报错应该是[re_official_evaluation.py](https://github.com/PaddlePaddle/PaddleNLP/blob/03dcbeff745fb18f230c5bc07a2e3c0d23b8617a/examples/information_extraction/DuIE/re_official_evaluation.py#L215-L231)中文件读取失败导致的，可以打印下`ret_info`，贴下更多的报错信息吗？

re_official_evaluation.py文件报错信息如下：
Traceback (most recent call last):
  File "K:/项目代码/paddlenlp/examples/information_extraction/DuIE/re_official_evaluation.py", line 286, in <module>
    ret_info = calc_pr(predict_filename, alias_filename, predict_filename)
  File "K:/项目代码/paddlenlp/examples/information_extraction/DuIE/re_official_evaluation.py", line 222, in calc_pr
    ret_code, golden_dict = load_test_dataset(golden_filename)
  File "K:/项目代码/paddlenlp/examples/information_extraction/DuIE/re_official_evaluation.py", line 129, in load_test_dataset
    for line in gf:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 12: invalid continuation byte

**Comment by LemonNoel** [comment]
predictions是用argwhere取的下标，并不全是0/1。看报错是文件读取时解码的问题，我这边没有windows系统，可以搜下windows平台下的解决方案看看。
