### ISSUE TITLE
viterbi_decode无法转换成onnx，请问有什么办法处理吗？

### ISSUE THREAD

**Issue by Macxy2018** [PaddlePaddle/PaddleNLP#2696]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
- 使用AIStudio GPU
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.4，PaddlePaddle 2.2.2.post101
2）系统环境：python3.7.4
- 复现信息：如为报错，请给出复现环境、复现步骤
- 维特比解码无法转换成onnx
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/command.py", line 224, in main
    auto_update_opset=args.enable_auto_update_opset)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/command.py", line 148, in program2onnx
    auto_update_opset)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/command.py", line 210, in program2onnx
    output_names=output_names)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/convert.py", line 80, in program2onnx
    operator_export_type, auto_update_opset, **configs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/convert.py", line 102, in program2onnx
    output_names=output_names)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/convert.py", line 37, in export_onnx
    auto_update_opset)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 327, in build
    auto_update_opset=auto_update_opset)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 85, in __init__
    self.update_opset_version()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 203, in update_opset_version
    node_map, self.opset_version)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/op_mapper/op_mapper.py", line 142, in get_recommend_opset_version
    node_map, opset_version, True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/op_mapper/op_mapper.py", line 188, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 1 ops are not supported yet
=========== viterbi_decode ===========
请问有什么办法处理吗？

**Comment by joey12300** [comment]
@Macxy2018 您好，请问你是在什么场景下使用viterbi_decode呢？如果转ONNX的话，可以使用该接口完成转换：

`from paddlenlp.layers.crf import ViterbiDecoder`

**Comment by Macxy2018** [comment]
是在命名实体识别场景下用的，使用的是paddlenlp中快递单信息抽取中的代码，ERNIE + CRF模型，原代码使用的是paddle.text中的维特比解码，我试一下改成paddlenlp中的维特比解码

**Comment by wawltor** [comment]
> 是在命名实体识别场景下用的，使用的是paddlenlp中快递单信息抽取中的代码，ERNIE + CRF模型，原代码使用的是paddle.text中的维特比解码，我试一下改成paddlenlp中的维特比解码

想问一下导出成onnx模型，具体是想部署在什么硬件设备上了？

**Comment by Macxy2018** [comment]
刚刚试了一下paddlenlp中的，也还是不行的。
2022-07-01 16:47:46 [WARNING]   [Deprecated] `paddle2onnx.command.program2onnx` will be deprecated in the future version, the recommended usage is `paddle2onnx.export`
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/onnx/mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/command.py", line 224, in main
    auto_update_opset=args.enable_auto_update_opset)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/command.py", line 148, in program2onnx
    auto_update_opset)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/command.py", line 210, in program2onnx
    output_names=output_names)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/convert.py", line 80, in program2onnx
    operator_export_type, auto_update_opset, **configs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/convert.py", line 102, in program2onnx
    output_names=output_names)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/convert.py", line 37, in export_onnx
    auto_update_opset)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 327, in build
    auto_update_opset=auto_update_opset)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 85, in __init__
    self.update_opset_version()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 203, in update_opset_version
    node_map, self.opset_version)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/op_mapper/op_mapper.py", line 142, in get_recommend_opset_version
    node_map, opset_version, True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/op_mapper/op_mapper.py", line 188, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 6 ops are not supported yet
=========== write_to_array ===========
=========== while ===========
=========== lod_array_length ===========
=========== conditional_block ===========
=========== select_input ===========
=========== tensor_array_to_tensor ===========

**Comment by Macxy2018** [comment]
是希望部署在华硕的tinker board2s上，目前在板子上使用的docker，在docker(基础镜像是ubuntu 18.04 aarch64)中使用
