### ISSUE TITLE
ernie-3.0-medium-zh  模型加载失败

### ISSUE THREAD

**Issue by jackerlzy** [PaddlePaddle/PaddleNLP#2738]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

paddlepaddle-gpu  2.2.1
paddlenlp 2.2.3
win10  
python 3.9.7

报错信息如下：

E:\ProgramData\Anaconda3\envs\tt\lib\site-packages\paddlenlp\transformers\funnel\modeling.py:31: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
[2022-07-05 20:58:22,634] [    INFO] - Downloading tokenizer_config.json from https://bj.bcebos.com/paddlenlp/models/transformers/community/ernie-3.0-medium-zh\tokenizer_config.json
[2022-07-05 20:58:22,847] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/ernie-3.0-medium-zh\tokenizer_config.json failed with code 404!
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\tt\lib\site-packages\paddlenlp\transformers\auto\tokenizer.py", line 196, in from_pretrained
    resolved_vocab_file = get_path_from_url(community_config_path,
  File "E:\ProgramData\Anaconda3\envs\tt\lib\site-packages\paddlenlp\utils\downloader.py", line 164, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "E:\ProgramData\Anaconda3\envs\tt\lib\site-packages\paddlenlp\utils\downloader.py", line 200, in _download
    raise RuntimeError("Downloading from {} failed with code "
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/ernie-3.0-medium-zh\tokenizer_config.json failed with code 404!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\workspace\pycharm\MyPractice\PaddleNLP\demo.py", line 4, in <module>
    tokenizer = AutoTokenizer.from_pretrained("ernie-3.0-medium-zh")
  File "E:\ProgramData\Anaconda3\envs\tt\lib\site-packages\paddlenlp\transformers\auto\tokenizer.py", line 200, in from_pretrained
    raise RuntimeError(
RuntimeError: Can't load tokenizer for 'ernie-3.0-medium-zh'.
Please make sure that 'ernie-3.0-medium-zh' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant tokenizer files.

在调试过程中发现，是模型下载地址没有包含  ernie-3.0-medium-zh 的，猜测应该是代码中的下载地址没有更新

**Comment by 1649759610** [comment]
请更新paddlenlp至最新版本试试：pip install paddlenlp==2.3.4

**Comment by engineer1109** [comment]
also 404 for develop branch
