### ISSUE TITLE
报错：IndexError: basic_string

### ISSUE THREAD

**Issue by weichen12345** [PaddlePaddle/PaddleNLP#2755]
Traceback (most recent call last):
  File "/Users/mac/code/uie/demo.py", line 8, in <module>
    ie = Taskflow('information_extraction', schema=schema)
  File "/Users/mac/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/taskflow.py", line 302, in __init__
    self.task_instance = task_class(
  File "/Users/mac/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/information_extraction.py", line 131, in __init__
    self._get_inference_model()
  File "/Users/mac/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/task.py", line 171, in _get_inference_model
    self._prepare_static_mode()
  File "/Users/mac/opt/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/task.py", line 145, in _prepare_static_mode
    self.predictor = paddle.inference.create_predictor(self._config)
IndexError: basic_string

**Comment by linjieccc** [comment]
@weichen12345 麻烦提供下paddlenlp和paddlepaddle的版本信息

**Comment by weichen12345** [comment]
> @weichen12345 麻烦提供下paddlenlp和paddlepaddle的版本信息
@linjieccc 
mac os 1.1
paddlenlp版本 2.3.0
paddlepaddle版本 2.3.1
python版本 3.8
谢谢了

**Comment by wawltor** [comment]
建议更新一下PaddleNLP的版本到最新2.3.4版本，同时把~/.paddlenlp目录删除，再重新尝试一下代码

**Comment by weichen12345** [comment]
> 建议更新一下PaddleNLP的版本到最新2.3.4版本，同时把~/.paddlenlp目录删除，再重新尝试一下代码

删除~/.paddlenlp目录  解决问题了。谢谢！！

**Comment by wawltor** [comment]
您好，目前的问题已经解决，我们将关闭issue，如有问题可以继续给我们提issue！
