### ISSUE TITLE
在自定义数据集时出现assert lazy is not None, "lazy can not be None in custom mode."

### ISSUE THREAD

**Issue by Otiss-pang** [PaddlePaddle/PaddleNLP#2781]
准备用paddleNLP的bert实现一个文本二分类任务，在处理自定义数据集时出现了assert lazy is not None, "lazy can not be None in custom mode."的报错，请问这个问题如何解决呢？
具体报错代码如下
```
Traceback (most recent call last):
  File "/home/fzuir/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/fzuir/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/fzuirdata/yht/textDeepLearning/BERT/train.py", line 30, in <module>
    train_ds = load_dataset(read,data_path = '/home/fzuirdata/yht/textDeepLearning/data/test_nospace.csv',Lazy=False)
  File "/home/fzuirdata/anaconda3/envs/pyf_paddle/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 186, in load_dataset
python-BaseException
    assert lazy is not None, "lazy can not be None in custom mode."
AssertionError: lazy can not be None in custom mode.

```
系统为centos，paddlepaddle版本为2.3.1，paddleNLP版本为2.3.4

**Comment by wawltor** [comment]
能提供一下具体的代码？ 同时在文本分类方向我们做了一个应用工具，可以按照具体的数据格式来组织文本数据就可以训练预测部署，具体可以看 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class

**Comment by Otiss-pang** [comment]
> 能提供一下具体的代码？ 同时在文本分类方向我们做了一个应用工具，可以按照具体的数据格式来组织文本数据就可以训练预测部署，具体可以看 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class

谢谢你的回复，问题解决了，在代码中不小心把lazy写为了Lazy。我也会尝试一下这个分类工具，再次感谢QAQ
