### ISSUE TITLE
ernie-3.0-nano-zh 和 ernie-3.0-micro-zh是不是没有发布？

### ISSUE THREAD

**Issue by nlper-77** [PaddlePaddle/PaddleNLP#2787]
>>> AutoModelForTokenClassification.from_pretrained(pretrained_model_name_or_path="ernie-3.0-nano-zh", num_classes=2)
[2022-07-12 20:11:05,019] [    INFO] - Downloading model_config.json from https://bj.bcebos.com/paddlenlp/models/community/ernie-3.0-nano-zh/model_config.json
[2022-07-12 20:11:05,173] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/community/ernie-3.0-nano-zh/model_config.json failed with code 404!
Traceback (most recent call last):
  File "/home/liuts/.conda/envs/liuts/lib/python3.7/site-packages/paddlenlp/transformers/auto/modeling.py", line 257, in _from_pretrained
    default_root)
  File "/home/liuts/.conda/envs/liuts/lib/python3.7/site-packages/paddlenlp/utils/downloader.py", line 162, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "/home/liuts/.conda/envs/liuts/lib/python3.7/site-packages/paddlenlp/utils/downloader.py", line 199, in _download
    "{}!".format(url, req.status_code))
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community/ernie-3.0-nano-zh/model_config.json failed with code 404!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liuts/.conda/envs/liuts/lib/python3.7/site-packages/paddlenlp/transformers/auto/modeling.py", line 527, in from_pretrained
    **kwargs)
  File "/home/liuts/.conda/envs/liuts/lib/python3.7/site-packages/paddlenlp/transformers/auto/modeling.py", line 261, in _from_pretrained
    f"Can't load weights for '{pretrained_model_name_or_path}'.\n"
RuntimeError: Can't load weights for 'ernie-3.0-nano-zh'.
Please make sure that 'ernie-3.0-nano-zh' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant modeling files(model_weights and model_config).

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/modeling.py#L470-L471 

有的，您升级 paddlenlp 版本试试 
```
pip install paddlenlp==2.3.4
```

**Comment by nlper-77** [comment]
是的 版本问题 我刚刚也发现了 。。。谢谢
