### ISSUE TITLE
uie 部署

### ISSUE THREAD

**Issue by AnitaSherry** [PaddlePaddle/PaddleNLP#2833]
- 版本PaddleNLP 2.3.4 PaddlePaddle-gpu 2.3.1
- 环境信息Windows10
- python版本3.9.6
- 复现信息
TypeError: 'pad_token_type_id' is an invalid keyword argument for this function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "PaddleNLP-develop\model_zoo\uie\deploy\python\infer_gpu.py", line 102, in <module>
    main()
  File "PaddleNLP-develop\model_zoo\uie\deploy\python\infer_gpu.py", line 78, in main
    outputs = predictor.predict(texts)
  File "PaddleNLP-develop\model_zoo\uie\deploy\python\uie_predictor.py", line 460, in predict
    results = self._multi_stage_predict(input_data)
  File "PaddleNLP-develop\model_zoo\uie\deploy\python\uie_predictor.py", line 401, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "PaddleNLP-develop\model_zoo\uie\deploy\python\uie_predictor.py", line 159, in _single_stage_predict
    encoded_inputs = self._tokenizer(text=prompts,
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddlenlp\transformers\tokenizer_utils_base.py", line 2226, in __call__
    return self.batch_encode(
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddlenlp\transformers\tokenizer_utils_base.py", line 2428, in batch_encode
    return self._batch_encode_plus(
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddlenlp\transformers\tokenizer_utils_faster.py", line 360, in _batch_encode_plus
    self.set_truncation_and_padding(
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddlenlp\transformers\tokenizer_utils_faster.py", line 324, in set_truncation_and_padding
    self._tokenizer.enable_padding(**target)
SystemError: <built-in method enable_padding of Tokenizer object at 0x000002AA6DD92D00> returned a result with an error set

centos7服务器不报错，windows报错

**Comment by linjieccc** [comment]
@AnitaSherry 您好，Fast Tokenizer目前还不支持windows，

当前windows下执行可以先替换为普通Tokenizer

替换方式：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/deploy/python/uie_predictor.py#L91
```python
self._tokenizer = AutoTokenizer.from_pretrained("ernie-3.0-base-zh", use_faster=True)
```
修改为：
```python
self._tokenizer = AutoTokenizer.from_pretrained("ernie-3.0-base-zh")
```

**Comment by AnitaSherry** [comment]
感谢，问题已解决

**Comment by linjieccc** [comment]
不客气~预计下周我们会发布一个新版本，到时候fast_tokenizer可以适配windows
