### ISSUE TITLE
偶尔正常，偶尔会出现 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized

### ISSUE THREAD

**Issue by huangdacheng** [PaddlePaddle/PaddleNLP#2912]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.0，PaddlePaddle-gpu 2.3.0
2）系统环境：，例如Linux ，python版本 3.7。  GPU是   2080 有 多张卡,   并没有安装NCCL
- 复现信息：如为报错，请给出复现环境、复现步骤
偶尔正常，偶尔会出现
Traceback (most recent call last):
  File "run_seq_cls.py", line 490, in <module>
    do_train(args)
  File "run_seq_cls.py", line 289, in do_train
    paddle.set_device(args.device)
  File "/home/dacheng.hdc/miniconda3/envs/my_paddlenlp/lib/python3.7/site-packages/paddle/device/__init__.py", line 313, in set_device
    place = _convert_to_place(device)
  File "/home/dacheng.hdc/miniconda3/envs/my_paddlenlp/lib/python3.7/site-packages/paddle/device/__init__.py", line 204, in _convert_to_place
    place = core.CUDAPlace(ParallelEnv().dev_id)
OSError: (External) CUDA error(3), initialization error.
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:66)

另外在终端上 import paddle时
偶尔会报W0728 15:20:19.274510 17263 init.cc:179] Compiled with WITH, but no GPU found in runtime.的错，但实际上我是有8张卡的

**Comment by wawltor** [comment]
如微信沟通，在新的conda环境下安装paddle之后，问题不再复现。

**Comment by wawltor** [comment]
> 如微信沟通，在新的conda环境下安装paddle之后，问题不再复现。

线下定位是机器被多人使用的问题，暂时关闭issue，后续有问题，可以再次打开该issue。
