### ISSUE TITLE
尝试将unimo_text_toknerizer加载数据的方法使用于GPT模型训练上报错

### ISSUE THREAD

**Issue by ZeyuTeng96** [PaddlePaddle/PaddleNLP#3084]
尝试将unimo_text_toknerizer加载数据的方法使用于GPT模型训练上报错

报错信息如下：
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.707 seconds.
Prefix dict has been built successfully.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/tmp/ipykernel_12006/3560309570.py", line 19, in batchify_fn
    input_ids = pad_func([example['input_ids'] for example in batch_examples])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/data/collate.py", line 158, in __call__
    dtype=arrs[0].dtype if self._dtype is None else self._dtype)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/numeric.py", line 315, in full
    multiarray.copyto(a, fill_value, casting='unsafe')
  File "<__array_function__ internals>", line 6, in copyto
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

gen_encode(), batchify_fn()函数均复制黏贴于训练unimo_text的gen_utils脚本。但是一组batch就报错，请大佬看看https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_generation/unimo-text/gen_utils.py

aistudio链接：

我发现了一篇高质量的实训项目，使用免费算力即可一键运行，还能额外获取8小时免费GPU运行时长，快来Fork一下体验吧。
 gpt：https://aistudio.baidu.com/aistudio/projectdetail/4441886?sUid=2543831&shared=1&ts=1660816062848

**Comment by gongel** [comment]
你好，可以检查下这里面是否有空值：`example['input_ids'] for example in batch_examples]`

**Comment by ZeyuTeng96** [comment]
> 你好，可以检查下这里面是否有空值：`example['input_ids'] for example in batch_examples]`

大佬，GPT的tokenizer怎么加token呢，没有pad和cls怎么办

**Comment by gongel** [comment]
已在微信回复，closed
