### ISSUE TITLE
CPU使用Taskflow进行文本纠错报错

### ISSUE THREAD

**Issue by hmwdt** [PaddlePaddle/PaddleNLP#3090]
paddlenlp==2.3.4
paddlepaddle==2.3.0

CPU使用Taskflow进行文本纠错报错

from paddlenlp import Taskflow
        tc = Taskflow("text_correction")

首次运行日志如下：
[2022-08-19 09:08:11,930] [    INFO] - Already cached /root/.paddlenlp/models/ernie-1.0/ernie_v1_chn_base.pdparams
[2022-08-19 09:08:23,190] [    INFO] - Weights from pretrained model not used in ErnieModel: ['cls.predictions.layer_norm.weight', 'cls.predictions.decoder_bias', 'cls.predictions.transform.bias', 'cls.predictions.transform.weight', 'cls.predictions.layer_norm.bias']
[2022-08-19 09:08:28,170] [    INFO] - Converting to the inference model cost a little time.
Killed
**此处脚本直接就自动结束了，无其他报错**

第二次运行日志如下:
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    NlpService.text_correction('123')
  File "/data/www/serivces/nlp_service.py", line 23, in text_correction
    tc = Taskflow("text_correction")
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/taskflow.py", line 330, in __init__
    **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/text_correction.py", line 95, in __init__
    self._get_inference_model()
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/task.py", line 235, in _get_inference_model
    self._prepare_static_mode()
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/task.py", line 172, in _prepare_static_mode
    self.predictor = paddle.inference.create_predictor(self._config)
ValueError: (InvalidArgument) tensor version 3439597808 is not supported, Only version 0 is supported
  [Hint: Expected version == 0U, but received version:3439597808 != 0U:0.] (at /paddle/paddle/fluid/framework/tensor_util.cc:1245)
  [operator < load_combine > error]

在MAC OS及LINUX下都报错，百分百复现

**Comment by linjieccc** [comment]
应该是内存不足被kill了，请问运行机器的内存多大

**Comment by hmwdt** [comment]
运行机器内存8G，确实应该是内存不够，使用了更大内存的服务器后不再报错
