### ISSUE TITLE
examples.text_to_sql.RAT-SQL  runtime error .  please check it.

### ISSUE THREAD

**Issue by cuixiaojun** [PaddlePaddle/PaddleNLP#3093]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
在百度的aistudio上，新建的项目，跑的脚本是按照https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_sql/RAT-SQL 的指南执行的。

paddlepaddle2.3.1
Python3  3.7.4
paddlenlp,使用pip3 install -r requirements.txt获得

最后一步报错：
!cd t2s && python ./evaluation/text2sql_evaluation.py \
        -g data/DuSQL/gold_dev.sql \
        -t data/DuSQL/db_schema.json \
        -d DuSQL \
        -p output/dusql_dev_infer_result.sql
Traceback (most recent call last):
  File "./evaluation/text2sql_evaluation.py", line 1921, in <module>
    dataset=args.dataset)
  File "./evaluation/text2sql_evaluation.py", line 1886, in evaluate
    single_equal=True)
  File "./evaluation/text2sql_evaluation.py", line 1853, in evaluate_complex
    scores[k]['acc'] + scores[k]['rec'])
ZeroDivisionError: float division by zero

2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
百度aistudio，
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

如还有问题可以到 PaddleNLP github 主页面的**[社区交流](https://github.com/PaddlePaddle/PaddleNLP#%E7%A4%BE%E5%8C%BA%E4%BA%A4%E6%B5%81)**扫描加入微信群，相关值班同学将会为您解答！
祝你好运吧。

**Comment by cuixiaojun** [comment]
aistudio地址是https://aistudio.baidu.com/aistudio/projectdetail/4438049
