### ISSUE TITLE
FasterTransformer is not available due to build errors

### ISSUE THREAD

**Issue by xk503775229** [PaddlePaddle/PaddleNLP#3175]
No such file or directory: 'cmake': 'cmake'
问题如下：
[2022-09-01 12:00:58,650] [ WARNING] - FasterTransformer is not available due to build errors.
error: [Errno 2] No such file or directory: 'cmake': 'cmake'
[2022-09-01 12:00:58,861] [ WARNING] - Failed to run command: <built-in function compile>, errors: Command 'cd /home/miniconda3/envs/OCR/lib/python3.7/site-packages/paddlenlp/ops/extenstions &&  /home/miniconda3/envs/OCR/bin/python FasterTransformer_setup.py build' returned non-zero exit status 1.
[2022-09-01 12:00:58,861] [ WARNING] - FasterGeneration is not available, and the original version would be used instead.

paddlenlp                 2.2
paddlepaddle-gpu==2.3.2

欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

如还有问题可以到 PaddleNLP github 主页面的**[社区交流](https://github.com/PaddlePaddle/PaddleNLP#%E7%A4%BE%E5%8C%BA%E4%BA%A4%E6%B5%81)**扫描加入微信群，相关值班同学将会为您解答！

**Comment by FrostML** [comment]
看到你的报错：
`error: [Errno 2] No such file or directory: 'cmake': 'cmake'`

因使用加速，需要根据当前环境重新编译，所以需要用到 `cmake` 可以确认下，当前环境下是否有 `cmake`。

**Comment by xk503775229** [comment]
>好的，已经安装了cmake  3.22版本，但是又出现以下问题：
aokang/miniconda3/envs/OCR/bin/python FasterTransformer_setup.py build
running build
running build_ext
CMake Error at /home/xiaokang/miniconda3/envs/OCR/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:226 (message):
  Couldn't find CUDA library root.
Call Stack (most recent call first):
  CMakeLists.txt:15 (project)

**Comment by xk503775229** [comment]
2022-09-01 13:01:20,231 - INFO - execute command: cd /home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddlenlp/ops/extenstions && /home/xi               aokang/miniconda3/envs/OCR/bin/python FasterTransformer_setup.py build
running build
running build_ext
CMake Error at /home/xiaokang/miniconda3/envs/OCR/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:226 (message):
  Couldn't find CUDA library root.
Call Stack (most recent call first):
  CMakeLists.txt:15 (project)


-- Configuring incomplete, errors occurred!
See also "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddlenlp/ops/extenstions/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log               ".
[2022-09-01 13:01:21,588] [ WARNING] - FasterTransformer is not available due to build errors.
Traceback (most recent call last):
  File "FasterTransformer_setup.py", line 11, in <module>
    output_dir=r'/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddlenlp/ops/extenstions/FasterTransformer')
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 165, in build_extensions
    ext.build_with_command(self)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 146, in build_with_command
    raise e
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 135, in build_with_command
    self).build_with_command(ext_builder)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 95, in build_with_command
    stderr=stdout)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddlenlp/ops', '-DPY_CMD=/home/xiaokan               g/miniconda3/envs/OCR/bin/python', '-DWITH_GPT=ON', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/xiaokang/miniconda3/envs/OCR/li               b/python3.7/site-packages/paddlenlp/ops/extenstions/FasterTransformer']' returned non-zero exit status 1.

**Comment by FrostML** [comment]
`Couldn't find CUDA library root.`
当前环境下有装 CUDA 么？

**Comment by xk503775229** [comment]
已经安装，默认在/usr/local下面， 是需要在环境里面指明路径嘛？

**Comment by xk503775229** [comment]
配置完环境变量后该问题仍然出现。
环境变量：\
![image](https://user-images.githubusercontent.com/18070856/187877836-c285f551-060a-4374-8dc1-2ffcf8be1a1c.png)

出现：
![image](https://user-images.githubusercontent.com/18070856/187877615-639e52a2-7538-4a47-b12e-406eb1832682.png)

**Comment by xk503775229** [comment]
最终只能使用官方的镜像了

**Comment by xk503775229** [comment]
使用镜像解决
