### ISSUE TITLE
loss_fct函数报错，请问是什么问题？

### ISSUE THREAD

**Issue by liu120945561** [PaddlePaddle/PaddleNLP#318]
Traceback (most recent call last):
  File "/Users/liudaowen/python/machine learning/PaddleNLP/examples/information_extraction/msra_ner/train.py", line 218, in <module>
    do_train(args)
  File "/Users/liudaowen/python/machine learning/PaddleNLP/examples/information_extraction/msra_ner/train.py", line 198, in do_train
    loss = loss_fct(logits, labels)
  File "/Users/liudaowen/opt/anaconda3/envs/ml36/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/liudaowen/opt/anaconda3/envs/ml36/lib/python3.6/site-packages/paddle/nn/layer/loss.py", line 417, in forward
    name=self.name)
  File "/Users/liudaowen/opt/anaconda3/envs/ml36/lib/python3.6/site-packages/paddle/nn/functional/loss.py", line 1403, in cross_entropy
    'use_softmax', use_softmax)
IndexError: (OutOfRange) label value should less than the shape of axis dimension when label value(6) not equal to ignore_index(-100), But received label value as 6 and shape of axis dimension is 1
  [Hint: Expected lbl < axis_dim, but received lbl:6 >= axis_dim:1.] (at /home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/math/cross_entropy.cc:75)
  [operator < softmax_with_cross_entropy > error]

**Comment by wawltor** [comment]
您好，看上面的报错看起来softmax_with_cross_entropy 出错，看起来是logits的维度和labels的维度设置有问题，可以尝试将softmax_with_cross_entropy中soft_label设置成False试试，具体的API使用可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/softmax_with_cross_entropy_cn.html#softmax-with-cross-entropy

**Comment by AaronsyA** [comment]
> 您好，看上面的报错看起来softmax_with_cross_entropy 出错，看起来是logits的维度和labels的维度设置有问题，可以尝试将softmax_with_cross_entropy中soft_label设置成False试试，具体的API使用可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/softmax_with_cross_entropy_cn.html#softmax-with-cross-entropy



您好，我也遇到同样的问题了，试了不同的模型（paddle seg/paddle NLP）,都是这个loss_fct在计算logits和lable的交叉熵出现问题，具体就是loss = loss_fct(logits, labels) 这行。按您说的将soft_label已经设置为false了，还是不行

**Comment by wawltor** [comment]
> > 您好，看上面的报错看起来softmax_with_cross_entropy 出错，看起来是logits的维度和labels的维度设置有问题，可以尝试将softmax_with_cross_entropy中soft_label设置成False试试，具体的API使用可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/softmax_with_cross_entropy_cn.html#softmax-with-cross-entropy
> 
> 您好，我也遇到同样的问题了，试了不同的模型（paddle seg/paddle NLP）,都是这个loss_fct在计算logits和lable的交叉熵出现问题，具体就是loss = loss_fct(logits, labels) 这行。按您说的将soft_label已经设置为false了，还是不行

您好，刚看到你的问题了，请问一下问题解决了吗？如果没有解决，能不能提供一下以下信息了，有了这些信息我们可以快速排查
1） 运行环境，操作系统，cuda & cudnn版本，以及 PaddlePaddle版本
2）出现的代码
