### ISSUE TITLE
WINDOWS环境下因为没有Linux命令而无法搭建端到端语义检索系统

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleNLP#3241]
我在学习[WINDOWS环境下搭建端到端语义检索系统](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/examples/semantic-search/Install_windows.md)，但是Win下没有`export`和`unset`命令，所以该例程可能需要修改。

**Comment by w5688414** [comment]
我尝试写了一下设置命令，需要powershell
cpu:
```
$env:CUDA_VISIBLE_DEVICES=""
```
gpu:
```
$env:CUDA_VISIBLE_DEVICES=“0” 
```
如果安装cpu版本的paddlepaddle，直接运行cpu的命令是没问题的，不需要这些环境变量设置。
如果安装gpu版本的paddlepaddle，直接安装gpu的命令是没问题的，不需要设置环境变量。

**Comment by w5688414** [comment]
cpu:
```
$env:CUDA_VISIBLE_DEVICES=""
```
gpu:
```
$env:CUDA_VISIBLE_DEVICES=“0” 
```
如果安装cpu版本的paddlepaddle，直接运行cpu的命令是没问题的，不需要这些环境变量设置。
如果安装gpu版本的paddlepaddle，直接安装gpu的命令是没问题的，不需要设置环境变量。

**Comment by w5688414** [comment]
请参考安装教学视频。 https://www.bilibili.com/video/BV1DY4y1M7HE?zw

**Comment by ghost** [comment]
设置`$env:CUDA_VISIBLE_DEVICES="0"`后运行`python examples/semantic-search/semantic_search_example.py --device gpu`，出现了如下报错：
```shell
[2022-09-11 17:21:11,434] [    INFO] - Already cached C:\Users\刘源东\.paddlenlp\models\rocketqa-zh-nano-query-encoder\rocketqa-zh-nano-query-encoder.pdparams
W0911 17:21:11.434460 14720 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W0911 17:21:11.452337 14720 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "examples/semantic-search/semantic_search_example.py", line 139, in <module>
    semantic_search_tutorial()
  File "examples/semantic-search/semantic_search_example.py", line 107, in semantic_search_tutorial
    embed_title=False,
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\pipelines\nodes\retriever\dense.py", line 154, in __init__
    passage_embedding_model)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\paddlenlp\transformers\semantic_search\modeling.py", line 90, in __init__
    query_model_name_or_path)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\paddlenlp\transformers\model_utils.py", line 348, in from_pretrained
    base_model = cls.base_model_class(*base_args, **base_kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\paddlenlp\transformers\utils.py", line 159, in __impl__
    init_func(self, *args, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 846, in __init__
    task_id, use_task_id)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 62, in __init__
    weight_attr=weight_attr)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\paddle\nn\layer\common.py", line 1457, in __init__
    is_bias=False)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\paddle\fluid\dygraph\layers.py", line 424, in create_parameter
    default_initializer)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\paddle\fluid\layer_helper_base.py", line 381, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\paddle\fluid\framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\paddle\fluid\initializer.py", line 474, in __call__
    'std', self._std_dev, 'seed', self._seed)
SystemError: (Fatal) Operator truncated_gaussian_random raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:307)
```
已经安装了cudatoolkit 10.2。

**Comment by w5688414** [comment]
cuda版本不太匹配，您的cuda驱动是11.4，请升级，比如试试11.2是否ok

```

conda install paddlepaddle-gpu==2.3.2 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 
```
请确保下面的命令能够执行成功。

安装完成后您可以使用 python 或 python3 进入python解释器，输入import paddle ，再输入 paddle.utils.run_check()

如果出现PaddlePaddle is installed successfully!，说明您已成功安装。

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/windows-conda.html
