### ISSUE TITLE
如何解决requests.exceptions.MissingSchema

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleNLP#3250]
参考[WINDOWS环境下搭建端到端语义检索系统](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/examples/semantic-search/Install_windows.md)，走到最后一步出现错误了。
```shell
(ml) PS C:\Users\刘源东\Desktop\PaddleNLP\pipelines> python -m streamlit run ui/webapp_semantic_search.py --server.port 8503

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8503
  Network URL: http://192.168.111.97:8503

2022-09-13 14:27:24.972 Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
Traceback (most recent call last):
  File "ui\utils.py", line 42, in pipelines_is_ready
    if requests.get(url).status_code < 400:
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
2022-09-13 14:27:24.980 Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
Traceback (most recent call last):
  File "ui\utils.py", line 42, in pipelines_is_ready
    if requests.get(url).status_code < 400:
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
2022-09-13 14:27:26.008 Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
Traceback (most recent call last):
  File "C:\Users\刘源东\Desktop\PaddleNLP\pipelines\ui\webapp_semantic_search.py", line 173, in main
    top_k_retriever=top_k_retriever)
  File "ui\utils.py", line 158, in semantic_search
    response_raw = requests.post(url, json=req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
2022-09-13 14:27:26.008 Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
Traceback (most recent call last):
  File "C:\Users\刘源东\Desktop\PaddleNLP\pipelines\ui\webapp_semantic_search.py", line 173, in main
    top_k_retriever=top_k_retriever)
  File "ui\utils.py", line 158, in semantic_search
    response_raw = requests.post(url, json=req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
2022-09-13 14:27:31.586 Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
Traceback (most recent call last):
  File "ui\utils.py", line 42, in pipelines_is_ready
    if requests.get(url).status_code < 400:
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
2022-09-13 14:27:32.593 Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
Traceback (most recent call last):
  File "C:\Users\刘源东\Desktop\PaddleNLP\pipelines\ui\webapp_semantic_search.py", line 173, in main
    top_k_retriever=top_k_retriever)
  File "ui\utils.py", line 158, in semantic_search
    response_raw = requests.post(url, json=req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
2022-09-13 14:28:58.647 Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
Traceback (most recent call last):
  File "ui\utils.py", line 42, in pipelines_is_ready
    if requests.get(url).status_code < 400:
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
2022-09-13 14:28:59.658 Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
Traceback (most recent call last):
  File "C:\Users\刘源东\Desktop\PaddleNLP\pipelines\ui\webapp_semantic_search.py", line 173, in main
    top_k_retriever=top_k_retriever)
  File "ui\utils.py", line 158, in semantic_search
    response_raw = requests.post(url, json=req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
2022-09-13 14:29:53.742 Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
Traceback (most recent call last):
  File "ui\utils.py", line 42, in pipelines_is_ready
    if requests.get(url).status_code < 400:
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
2022-09-13 14:29:54.756 Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
Traceback (most recent call last):
  File "C:\Users\刘源东\Desktop\PaddleNLP\pipelines\ui\webapp_semantic_search.py", line 173, in main
    top_k_retriever=top_k_retriever)
  File "ui\utils.py", line 158, in semantic_search
    response_raw = requests.post(url, json=req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
2022-09-13 14:31:09.467 Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
Traceback (most recent call last):
  File "ui\utils.py", line 42, in pipelines_is_ready
    if requests.get(url).status_code < 400:
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
2022-09-13 14:31:10.491 Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
Traceback (most recent call last):
  File "C:\Users\刘源东\Desktop\PaddleNLP\pipelines\ui\webapp_semantic_search.py", line 173, in main
    top_k_retriever=top_k_retriever)
  File "ui\utils.py", line 158, in semantic_search
    response_raw = requests.post(url, json=req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
2022-09-13 14:37:55.078 Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
Traceback (most recent call last):
  File "ui\utils.py", line 42, in pipelines_is_ready
    if requests.get(url).status_code < 400:
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
2022-09-13 14:37:56.103 Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
Traceback (most recent call last):
  File "C:\Users\刘源东\Desktop\PaddleNLP\pipelines\ui\webapp_semantic_search.py", line 173, in main
    top_k_retriever=top_k_retriever)
  File "ui\utils.py", line 158, in semantic_search
    response_raw = requests.post(url, json=req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
2022-09-13 14:38:14.539 Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
Traceback (most recent call last):
  File "ui\utils.py", line 42, in pipelines_is_ready
    if requests.get(url).status_code < 400:
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/initialized': No scheme supplied. Perhaps you meant http://None/initialized?
2022-09-13 14:38:15.561 Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
Traceback (most recent call last):
  File "C:\Users\刘源东\Desktop\PaddleNLP\pipelines\ui\webapp_semantic_search.py", line 173, in main
    top_k_retriever=top_k_retriever)
  File "ui\utils.py", line 158, in semantic_search
    response_raw = requests.post(url, json=req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "D:\Programs\miniconda3\envs\ml\lib\site-packages\requests\models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None/query': No scheme supplied. Perhaps you meant http://None/query?
```

**Comment by w5688414** [comment]
Hi, @Ywandung-Lyou 
Please make sure environment variables work out.

for windows powershell:
```
$env:PIPELINE_YAML_PATH='rest_api/pipeline/semantic_search.yaml'

$env:API_ENDPOINT='http://127.0.0.1:8891'
```
