### ISSUE TITLE
[Bug]: Mac CPU 环境下 codegeneration 示例报错 (NotFound) There are no kernels which are registered in the unsqueeze2 operator.

### ISSUE THREAD

**Issue by linonetwo** [PaddlePaddle/PaddleNLP#3265]
@gongel 

### 软件环境

```Markdown
paddle-bfloat      0.1.7
paddle2onnx        1.0.0
paddlefsl          1.1.0
paddlenlp          2.4.0
paddlepaddle       2.3.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

测试 example https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/code_generation/codegen#%E6%B5%8B%E8%AF%95%E6%9C%8D%E5%8A%A1 时报错

```
INFO:     Uvicorn running on http://0.0.0.0:8978 (Press CTRL+C to quit)
INFO 2022-09-14 15:14:01,346 server.py:206] Uvicorn running on http://0.0.0.0:8978 (Press CTRL+C to quit)
[2022-09-14 15:20:21,718] [    INFO] - Request: {'prompt': 'def hello', 'stream': False}
[2022-09-14 15:20:21,724] [    INFO] - Start generating code
[2022-09-14 15:20:21,796] [ WARNING] - FasterTransformer is not available because CUDA can not be found.
[2022-09-14 15:20:21,796] [ WARNING] - 
[2022-09-14 15:20:21,796] [ WARNING] - FasterGeneration is not available, and the original version would be used instead.
INFO:     127.0.0.1:59261 - "POST /v1/engines/codegen/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/lindongwu/Desktop/github/PaddleNLP/examples/code_generation/codegen/codegen_server.py", line 94, in gen
    output, _ = model.generate(
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/paddlenlp/transformers/generation_utils.py", line 838, in generate
    "attention_mask"] = self.prepare_attention_mask_for_generation(
  File "/usr/local/lib/python3.9/site-packages/paddlenlp/transformers/generation_utils.py", line 307, in prepare_attention_mask_for_generation
    return paddle.unsqueeze(attention_mask, axis=[1, 2])
  File "/usr/local/lib/python3.9/site-packages/paddle/tensor/manipulation.py", line 1339, in unsqueeze
    return layers.unsqueeze(x, axis, name)
  File "/usr/local/lib/python3.9/site-packages/paddle/fluid/layers/nn.py", line 6572, in unsqueeze
    out, _ = _C_ops.unsqueeze2(input, 'axes', axes)
RuntimeError: (NotFound) There are no kernels which are registered in the unsqueeze2 operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /home/Paddle/paddle/fluid/imperative/prepared_operator.cc:341)
  [operator < unsqueeze2 > error]
ERROR 2022-09-14 15:20:21,829 h11_impl.py:369] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/lindongwu/Desktop/github/PaddleNLP/examples/code_generation/codegen/codegen_server.py", line 94, in gen
    output, _ = model.generate(
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/paddlenlp/transformers/generation_utils.py", line 838, in generate
    "attention_mask"] = self.prepare_attention_mask_for_generation(
  File "/usr/local/lib/python3.9/site-packages/paddlenlp/transformers/generation_utils.py", line 307, in prepare_attention_mask_for_generation
    return paddle.unsqueeze(attention_mask, axis=[1, 2])
  File "/usr/local/lib/python3.9/site-packages/paddle/tensor/manipulation.py", line 1339, in unsqueeze
    return layers.unsqueeze(x, axis, name)
  File "/usr/local/lib/python3.9/site-packages/paddle/fluid/layers/nn.py", line 6572, in unsqueeze
    out, _ = _C_ops.unsqueeze2(input, 'axes', axes)
RuntimeError: (NotFound) There are no kernels which are registered in the unsqueeze2 operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /home/Paddle/paddle/fluid/imperative/prepared_operator.cc:341)
  [operator < unsqueeze2 > error]
```

### 稳定复现步骤 & 代码

按 https://github.com/PaddlePaddle/PaddleNLP/discussions/3264 启动示例，然后按 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/code_generation/codegen#%E6%B5%8B%E8%AF%95%E6%9C%8D%E5%8A%A1 尝试请求服务，第一步，还在试用中

**Comment by linonetwo** [comment]
考虑到 Mac 没有 GPU 功能，将脚本里和 GPU 加速相关的配置关闭即可（不过关了的确比较慢）

```py
    use_faster = False
```

而其它可以保持原状：

```py
    load_state_as_np = True
    use_faster = False
    use_fp16_decoding = True
```

@oncall助手 /solve

**Comment by gongel** [comment]
感谢反馈哈，这个服务最好还是要配合GPU+FasterGeneration来使用，否则速度较慢，因为模型较大，推理速度会慢些，另外在该场景下对推理速度要求较严格。GPU+FasterGeneration会加速10几倍，这个我们有Perf：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/faster_generation/README.md

**Comment by linonetwo** [comment]
那还是需要等 paddlepaddle 为 Mac 版提供 GPU 支持了，祝越来越好！
