### ISSUE TITLE
事件抽取基线系统，网络修改后，运行报 AttributeError: 'tuple' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by rela0426** [PaddlePaddle/PaddleNLP#331]
网络的修改按照官网的说明修改的
`
```
import paddle.nn as nn
from paddlenlp.transformers import ErnieModel
from paddlenlp.layers import LinearChainCrf, LinearChainCrfLoss, ViterbiDecoder


class ErnieModelNew(ErnieModel):
    def __init__(self, ernie, num_classes=2, dropout=None, gru_hidden_size=128):
        super(ErnieModelNew, self).__init__(vocab_size=200)
        self.num_classes = num_classes
        # allow ernie to be config
        self.ernie = ernie
        self.dropout = nn.Dropout(dropout if dropout is not None else
                                  self.ernie.config["hidden_dropout_prob"])
        # add bi-gru
        self.gru = nn.GRU(
            input_size=self.ernie.config["hidden_size"],
            hidden_size=gru_hidden_size,
            direction='bidirect')
        self.fc = nn.Linear(
            in_features=gru_hidden_size * 2,
            out_features=num_classes)
        # add crf
        self.crf = LinearChainCrf(
            num_classes,
            with_start_stop_tag=False)
        self.crf_loss = LinearChainCrfLoss(self.crf)
        self.viterbi_decoder = ViterbiDecoder(
            self.crf.transitions,
            with_start_stop_tag=False)

```

    def forward(self,
                input_ids,
                token_type_ids=None,
                labels=None,
                position_ids=None,
                attention_mask=None):
        sequence_output, _ = self.ernie(
            input_ids,
            token_type_ids=token_type_ids,
            position_ids=position_ids,
            attention_mask=attention_mask)
        sequence_output = self.dropout(sequence_output)
        bigru_output, _ = self.gru(sequence_output)
        emission = self.fc(bigru_output)
        lengths = []
        for i,e in enumerate(emission):
            lengths.append(len(e))
        import paddle
        lengths = paddle.to_tensor(lengths, dtype='int64')
        _, prediction = self.viterbi_decoder(emission, lengths) # lengths 是batch size的大小
        # return prediction
        if labels is not None:
            loss = self.crf_loss(emission, lengths, prediction, labels)
            return loss, lengths, prediction, labels
        else:
            return input_ids, lengths, prediction
`
在sequence_labeling.py文件中，我的调用如下：

`model = ErnieModelNew.from_pretrained("ernie-1.0", num_classes=len(label_map))`
运行时在190行左右报错：
```
model.train()
    for epoch in range(args.num_epoch):
        for idx, (input_ids, token_type_ids, seq_lens, labels) in enumerate(train_loader):
            logits = model(input_ids, token_type_ids).reshape(
                [-1, train_ds.label_num])
```
![image](https://user-images.githubusercontent.com/73818025/116641841-24ab4e00-a9a0-11eb-8933-851e5ea8d209.png)
如果将tuple改为数组，用array（）方法强制转换为数组，同样的一句话就会报另外一个错误：
![image](https://user-images.githubusercontent.com/73818025/116641899-40165900-a9a0-11eb-852c-43c5319bf0cf.png)
有什么解决办法吗？

**Comment by wawltor** [comment]
model输出的应该有多个输出的，例如label不为None的时候，输出是 loss, lengths, prediction, labels , 例如想对prediction进行reshape，可以参考
```python
    logits = model(input_ids, token_type_ids)[2].reshape(
                [-1, train_ds.label_num])
`

**Comment by white55** [comment]
您好兄台，该问题解决了嘛？

**Comment by rela0426** [comment]
> model输出的应该有多个输出的，例如label不为None的时候，输出是 loss, lengths, prediction, labels , 例如想对prediction进行reshape，可以参考
> 
> ```python
>     logits = model(input_ids, token_type_ids)[2].reshape(
>                 [-1, train_ds.label_num])
> `
> ```

您好，按照您的建议进行了修改，无论索引是0，1，2，3都报错。其中索引 [0]和索引 [1]报错为
```
Traceback (most recent call last):
  File "sequence_labeling.py", line 286, in <module>
    do_train()
  File "sequence_labeling.py", line 198, in do_train
    [-1, train_ds.label_num])
  File "/home/gaolu/miniconda3/envs/paddle_env2/lib/python3.6/site-packages/paddle/tensor/manipulation.py", line 1550, in reshape
    return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
  File "/home/gaolu/miniconda3/envs/paddle_env2/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6135, in reshape
    out, _ = core.ops.reshape2(x, None, 'shape', shape)
ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [16], X's size = 16, 'shape' is [-1, 131], known capacity of 'shape' is -131.
  [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:0 != -in_size:-16.] (at /paddle/paddle/fluid/operators/reshape_op.cc:208)
  [operator < reshape2 > error]
INFO 2021-05-10 15:41:16,561 launch_utils.py:307] terminate all the procs
ERROR 2021-05-10 15:41:16,562 launch_utils.py:545] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-05-10 15:41:19,565 launch_utils.py:307] terminate all the procs
end DuEE1.0 trigger train

```
索引 [2]和索引 [3]报错为
```
Traceback (most recent call last):
  File "sequence_labeling.py", line 286, in <module>
    do_train()
  File "sequence_labeling.py", line 198, in do_train
    [-1, train_ds.label_num])
  File "/home/gaolu/miniconda3/envs/paddle_env2/lib/python3.6/site-packages/paddle/tensor/manipulation.py", line 1550, in reshape
    return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
  File "/home/gaolu/miniconda3/envs/paddle_env2/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6135, in reshape
    out, _ = core.ops.reshape2(x, None, 'shape', shape)
ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [16, 300], X's size = 4800, 'shape' is [-1, 131], known capacity of 'shape' is -131.
  [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-4716 != -in_size:-4800.] (at /paddle/paddle/fluid/operators/reshape_op.cc:208)
  [operator < reshape2 > error]
INFO 2021-05-10 15:39:53,921 launch_utils.py:307] terminate all the procs
ERROR 2021-05-10 15:39:53,921 launch_utils.py:545] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-05-10 15:39:56,925 launch_utils.py:307] terminate all the procs
end DuEE1.0 trigger train


```
这个该怎么办？

**Comment by rela0426** [comment]
> 您好兄台，该问题解决了嘛？

没解决呢

**Comment by Steffy-zxf** [comment]
@rela0426 是否可以公开aistudio项目代码，我们调试看看。
