### ISSUE TITLE
《『NLP经典项目集』10：使用预训练模型优化快递单信息抽取》在线的notebook能跑通，但本地机器(Win10 64位、Python 3.79 64位）就不行

### ISSUE THREAD

**Issue by Newbies2021** [PaddlePaddle/PaddleNLP#334]
《『NLP经典项目集』10：使用预训练模型优化快递单信息抽取》网址：
[https://aistudio.baidu.com/aistudio/projectdetail/1329361](https://aistudio.baidu.com/aistudio/projectdetail/1329361)

在线的notebook能跑通，但本地机器(Win10 64位、Python 3.79 64位）就不行.
错误提示如下：
——————————————————————————————————————————————
[2021-05-01 08:48:02,678] [    INFO] - Found C:\Users\d\.paddlenlp\models\ernie-1.0\vocab.txt
[2021-05-01 08:48:02,695] [    INFO] - Already cached C:\Users\d\.paddlenlp\models\ernie-1.0\ernie_v1_chn_base.pdparams
C:\Program Files\Python3.7.9\lib\site-packages\paddle\fluid\dygraph\layers.py:1303: UserWarning: Skip loading for classifier.weight. classifier.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
C:\Program Files\Python3.7.9\lib\site-packages\paddle\fluid\dygraph\layers.py:1303: UserWarning: Skip loading for classifier.bias. classifier.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
Traceback (most recent call last):
  File "d:/WorkSpace/6.使用PaddleNLP语义预训练模型ERNIE完成快递单信息抽取.py", line 98, in <module>     
    loss = paddle.mean(loss_fn(logits, labels))
  File "C:\Program Files\Python3.7.9\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__    
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Program Files\Python3.7.9\lib\site-packages\paddle\nn\layer\loss.py", line 417, in forward
    name=self.name)
  File "C:\Program Files\Python3.7.9\lib\site-packages\paddle\nn\functional\loss.py", line 1403, in cross_entropy
    'use_softmax', use_softmax)
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at D:\v2.0.2\paddle\paddle/fluid/framework/tensor_impl.h:33)
  [operator < softmax_with_cross_entropy > error]
——————————————————————————————————————————————

最后一行的【 D:\v2.0.2\paddle\paddle/fluid/framework/tensor_impl.h】，本地机器并没有，不知道哪里冒出来的。

飞桨PaddlePaddle 交流Q群里面，管理员答复：
【这个报错是因为Windows下Numpy默认是int32，而Linux下是int64】
【一般需要对int数据用Numpy做个astype("int64")】
【如果不清楚怎么做这个操作，还是提个issue让他们帮你修改一下吧】

谢谢！

**Comment by wawltor** [comment]
您好，相应的问题已经修复完成，具体的修复信息可以参考 https://github.com/PaddlePaddle/PaddleNLP/issues/322 ， 您可以下载最新的develop版本，然后进行paddlenlp安装即可解决问题。

**Comment by Newbies2021** [comment]
> 您好，相应的问题已经修复完成，具体的修复信息可以参考 #322 ， 您可以下载最新的develop版本，然后进行paddlenlp安装即可解决问题。

非常感谢！专业！高效！
