### ISSUE TITLE
[Question]: 使用paddlenlp的文本纠错项目想增加训练数据新训练一个预训练模型，但是发现加载nlp的load_dataset, MapDataset出现问题

### ISSUE THREAD

**Issue by xuhongtian** [PaddlePaddle/PaddleNLP#3344]
### 请提出你的问题

使用paddlenlp的文本纠错项目想增加训练数据新训练一个预训练模型，但是发现加载nlp的load_dataset, MapDataset出现问题，我确定我增加的新训练数据格式是没问题的，请问下这个我可以怎么解决啊？
Traceback (most recent call last):
  File "/home/xtjc/ecard/test_nlp_word/train.py", line 230, in <module>
    do_train(args)
  File "/home/xtjc/ecard/test_nlp_word/train.py", line 117, in do_train
    ds = load_dataset(read_train_ds,
  File "/home/xtjc/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 196, in load_dataset
    return reader_instance.read(**custom_kwargs)
  File "/home/xtjc/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 833, in read
    return MapDataset(list(examples))
  File "/home/xtjc/ecard/test_nlp_word/utils.py", line 15, in read_train_ds
    source, target = line.strip('\n').split('\t')[0:2]
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by LiuChiachi** [comment]
你可以尝试这样debug：
`source, target = line.strip('\n').split('\t')[0:2]`
改成
````
source  = line.strip('\n').split('\t')[0:2]
print(source)
```

看下数据有什么不符合预期的地方
