### ISSUE TITLE
windows环境下pipelines的quesion-answering、semantic-search运行出现Segmentation fault

### ISSUE THREAD

**Issue by butear** [PaddlePaddle/PaddleNLP#3398]
### 软件环境

```Markdown
-win10
-python 3.7
-CUDA 11.2  
-cudnn 8.4.0
-paddlepaddle-gpu 2.3
-paddlenlp 2.4.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "D:\Aaron\PaddleNLP\pipelines\ui\webapp_question_answering.py", line 178, in main
    top_k_retriever=top_k_retriever)
  File "D:\Aaron\PaddleNLP\pipelines\ui\utils.py", line 94, in query
    response_raw = requests.post(url, json=req)
  File "C:\Dev\Python\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Dev\Python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Dev\Python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Dev\Python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Dev\Python\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主了一个现有的连接。', None, 10054, None))


INFO:     Application startup complete.
09/30/2022 09:18:57 AM Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8891 (Press CTRL+C to quit)
09/30/2022 09:18:57 AM Uvicorn running on http://0.0.0.0:8891 (Press CTRL+C to quit)
INFO:     127.0.0.1:65016 - "GET /hs_version HTTP/1.1" 200 OK
INFO:     127.0.0.1:65017 - "GET /initialized HTTP/1.1" 200 OK
Segmentation fault
```

### 稳定复现步骤 & 代码

export PIPELINE_YAML_PATH=rest_api/pipeline/dense_qa.yaml
python rest_api/application.py 8891

unset http_proxy && unset https_proxy
export API_ENDPOINT=http://127.0.0.1:8891
python -m streamlit run ui/webapp_question_answering.py --server.port 8502

**Comment by w5688414** [comment]
看上去是cuda版本不匹配。

Please follow this windows README.md. https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/examples/question-answering/Install_windows.md

and the windows video tutorial, please refer to this link. https://www.bilibili.com/video/BV1DY4y1M7HE/?zw

**Comment by butear** [comment]
在以下环境问题解决：
-win10 
-python 3.7
-CUDA 11.2  
-cudnn 8.2.1
-paddlepaddle-gpu 2.2.2
-paddlenlp 2.4.0
