### ISSUE TITLE
[Question]: 运行example中transformer显示报错

### ISSUE THREAD

**Issue by xiaohangguo** [PaddlePaddle/PaddleNLP#3400]
### 请提出你的问题

系统：Ubuntu22.04
python:3.8 
Error: Can not import avx core while this file exists: /home/hang/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    import paddle
  File "/home/hang/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/hang/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/hang/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/hang/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/hang/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/hang/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/home/hang/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /home/hang/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

搜了一下好像是paddle不支持22.04，是这样吗？怎么解决呢？

**Comment by ZeyuChen** [comment]
应该是paddle框架的安装不太正确，或者匹配的版本不对。
检查下cuda版本匹配等问题或者重新安装试试。
@xiaohangguo

**Comment by xiaohangguo** [comment]
> 应该是paddle框架的安装不太正确，或者匹配的版本不对。 检查下cuda版本匹配等问题或者重新安装试试。 @xiaohangguo
我本机是cudatoolkit==11.7 按理说 api接口低于11.7都能安装。 

@ZeyuChen 
不知道paddle是怎么回事，但是我用了这个命令解决了，你们也可以采纳一下
`pip install paddlepaddle==2.4.0rc0`
