### ISSUE TITLE
[Bug]: CUBLAS_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/PaddleNLP#3416]
### 软件环境

```Markdown
paddlenlp                   2.3.0
paddleocr                   2.6         /home/model-server/PaddleOCR
paddlepaddle-gpu            2.2.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
2022-10-09T05:37:08,861 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddlenlp/taskflow/taskflow.py", line 314, in __call__
2022-10-09T05:37:08,861 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     results = self.task_instance(inputs)
2022-10-09T05:37:08,861 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddlenlp/taskflow/task.py", line 293, in __call__
2022-10-09T05:37:08,861 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     outputs = self._run_model(inputs)
2022-10-09T05:37:08,861 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddlenlp/taskflow/information_extraction.py", line 334, in _run_model
2022-10-09T05:37:08,861 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     results = self._multi_stage_predict(raw_inputs, schema_tree)
2022-10-09T05:37:08,862 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddlenlp/taskflow/information_extraction.py", line 375, in _multi_stage_predict
2022-10-09T05:37:08,862 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     result_list = self._single_stage_predict(examples)
2022-10-09T05:37:08,862 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddlenlp/taskflow/information_extraction.py", line 251, in _single_stage_predict
2022-10-09T05:37:08,862 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     self.predictor.run()
2022-10-09T05:37:08,862 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG - OSError: (External) CUBLAS error(14). 
2022-10-09T05:37:08,862 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   [Hint: 'CUBLAS_STATUS_INTERNAL_ERROR'.  An internal cuBLAS operation failed. This error is usually caused by a cudaMemcpyAsync() failure.  To correct: check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.  ] (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:35)
2022-10-09T05:37:08,862 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   [operator < fc > error]
```

### 稳定复现步骤 & 代码

None

**Comment by jack-gits** [comment]
![image](https://user-images.githubusercontent.com/30545972/194741846-22b5e623-2415-4238-878a-43b6574e6b39.png)

**Comment by wawltor** [comment]
是不是显存爆了  
<img width="820" alt="image" src="https://user-images.githubusercontent.com/16698950/194746978-c39ec619-405e-4d43-aa2d-991496da728b.png">

**Comment by jack-gits** [comment]
2022-10-09T06:05:43,981 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG - Invoking custom service failed.
2022-10-09T06:05:43,981 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG - Traceback (most recent call last):
2022-10-09T06:05:43,982 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/service.py", line 102, in predict
2022-10-09T06:05:43,982 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     ret = self._entry_point(input_batch, self.context)
2022-10-09T06:05:43,982 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/torch_handler/base_handler.py", line 222, in handle
2022-10-09T06:05:43,982 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     output = self.inference(data_preprocess)
2022-10-09T06:05:43,982 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/model-server/tmp/models/7bc610457a414430914af6f92e92be3d/inference-handler.py", line 55, in inference
2022-10-09T06:05:43,982 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     results = self.model(content)
2022-10-09T06:05:43,982 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddlenlp/taskflow/taskflow.py", line 314, in __call__
2022-10-09T06:05:43,982 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     results = self.task_instance(inputs)
2022-10-09T06:05:43,983 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddlenlp/taskflow/task.py", line 293, in __call__
2022-10-09T06:05:43,983 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     outputs = self._run_model(inputs)
2022-10-09T06:05:43,983 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddlenlp/taskflow/information_extraction.py", line 334, in _run_model
2022-10-09T06:05:43,983 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     results = self._multi_stage_predict(raw_inputs, schema_tree)
2022-10-09T06:05:43,983 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddlenlp/taskflow/information_extraction.py", line 375, in _multi_stage_predict
2022-10-09T06:05:43,983 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     result_list = self._single_stage_predict(examples)
2022-10-09T06:05:43,983 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddlenlp/taskflow/information_extraction.py", line 251, in _single_stage_predict
2022-10-09T06:05:43,984 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -     self.predictor.run()
2022-10-09T06:05:43,984 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG - OSError: (External) CUBLAS error(14). 
2022-10-09T06:05:43,984 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   [Hint: 'CUBLAS_STATUS_INTERNAL_ERROR'.  An internal cuBLAS operation failed. This error is usually caused by a cudaMemcpyAsync() failure.  To correct: check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.  ] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
2022-10-09T06:05:43,984 [INFO ] W-9000-uie-cro_vl_ba_vin_snapshot-2022-10-10-stdout MODEL_LOG -   [operator < fc > error]

**Comment by jack-gits** [comment]
![image](https://user-images.githubusercontent.com/30545972/194754840-7f237960-1fc4-43dd-acf6-c70667eee940.png)

显存降下来后还是报错

**Comment by jack-gits** [comment]
paddle-gpu也升级到2.3.0了

paddlenlp                   2.3.0
paddleocr                   2.6         /home/model-server/PaddleOCR
paddlepaddle-gpu            2.3.0

**Comment by jack-gits** [comment]
@wawltor 有什么建议吗？
