### ISSUE TITLE
[Question]: 离线环境下（没有git access）如何编译FasterGeneration？

### ISSUE THREAD

**Issue by BenfengXu** [PaddlePaddle/PaddleNLP#3433]
如题，云端服务器没有git access，编译失败，报错如下：

```
Cloning into 'fastertransformer'...
fatal: unable to access 'https://gitee.com/paddlepaddle/FasterTransformer.git/': Failed to connect to gitee.com port 443: Connection timed out
Cloning into 'fastertransformer'...
fatal: unable to access 'https://gitee.com/paddlepaddle/FasterTransformer.git/': Failed to connect to gitee.com port 443: Connection timed out
Cloning into 'fastertransformer'...
fatal: unable to access 'https://gitee.com/paddlepaddle/FasterTransformer.git/': Failed to connect to gitee.com port 443: Connection timed out
-- Had to git clone more than once:
          3 times.
CMake Error at /root/.paddlenlp/extensions/f7f6547e0d59428b8b3e61c4a9fd3a01/FasterTransformer/build/temp.linux-x86_64-3.7/third-party/tmp/extern_fastertransformer-gitclone.cmake:31 (message):
  Failed to clone repository:
  'https://gitee.com/paddlepaddle/FasterTransformer.git'


CMakeFiles/extern_fastertransformer.dir/build.make:90: recipe for target 'third-party/src/extern_fastertransformer-stamp/extern_fastertransformer-download' failed
make[2]: *** [third-party/src/extern_fastertransformer-stamp/extern_fastertransformer-download] Error 1
CMakeFiles/Makefile2:144: recipe for target 'CMakeFiles/extern_fastertransformer.dir/all' failed
make[1]: *** [CMakeFiles/extern_fastertransformer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
[2022-10-11 15:41:09,300] [ WARNING] - FasterTransformer is not available due to build errors.
```

是否有work around可以解决？比如我提前下载好FasterTransformer的git repo，并把它手动上传到服务器的某个位置？

**Comment by guoshengCS** [comment]
可以按照以下步骤尝试完成：

1. 下载 FasterTransformer git repo 到 `xxx` 目录，并切换到`nccl_dependent_refine`分支，上传切换分支后的文件夹离线使用

```
cd xxx
git clone https://gitee.com/paddlepaddle/FasterTransformer.git fastertransformer
cd fastertransformer
git fetch origin nccl_dependent_refine:nccl_dependent_refine
git checkout nccl_dependent_refine
```

2. 修改下使用的paddlenlp包中的 `paddlenlp/ops/CMakeLists.txt` 文件，对应github中的[这个](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/ops/CMakeLists.txt)文件，将407行开始的下面代码

```
set(FT_UPDATE_COMMAND git checkout nccl_dependent_refine && git checkout . && ${FT_PATCH_COMMAND})

ExternalProject_Add(
  extern_${THIRD_PARTY_NAME}
  GIT_REPOSITORY    https://gitee.com/paddlepaddle/FasterTransformer.git
  GIT_TAG           nccl_dependent_refine
  PREFIX            ${THIRD_PATH}
  SOURCE_DIR        ${THIRD_PATH}/source/${THIRD_PARTY_NAME}
  UPDATE_COMMAND    ${FT_UPDATE_COMMAND}  # PATCH_COMMAND     ${FT_PATCH_COMMAND}
  BINARY_DIR        ${THIRD_PATH}/build/${THIRD_PARTY_NAME}
  INSTALL_COMMAND   ""
  CMAKE_ARGS        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DSM=${SM} -DBUILD_PD=ON -DBUILD_ENCODER=${WITH_ENCODER} -DPY_CMD=${PY_CMD} -DON_INFER=${ON_INFER} -DPADDLE_LIB=${PADDLE_LIB} -DWITH_MKL=${WITH_MKL} -DWITH_STATIC_LIB=${WITH_STATIC_LIB} -DBUILD_GPT=${WITH_PARALLEL} -DWITH_ONNXRUNTIME=${WITH_ONNXRUNTIME}
)
```

修改为如下代码（新增两行+注释两行）：

```
########## 新增如下两行，xxx/fastertransformer 为第1步中下载的repo路径
set(LOCAL_FT_PATH xxx/fastertransformer)
execute_process(COMMAND cp -r ${LOCAL_FT_PATH} ${CMAKE_BINARY_DIR}/${THIRD_PATH}/source/)
##########
set(FT_UPDATE_COMMAND git checkout nccl_dependent_refine && git checkout . && ${FT_PATCH_COMMAND})

ExternalProject_Add(
  extern_${THIRD_PARTY_NAME}
  ########### 注释如下两行
  # GIT_REPOSITORY    https://gitee.com/paddlepaddle/FasterTransformer.git
  # GIT_TAG           nccl_dependent_refine
  ##########
  PREFIX            ${THIRD_PATH}
  SOURCE_DIR        ${THIRD_PATH}/source/${THIRD_PARTY_NAME}
  UPDATE_COMMAND    ${FT_UPDATE_COMMAND}  # PATCH_COMMAND     ${FT_PATCH_COMMAND}
  BINARY_DIR        ${THIRD_PATH}/build/${THIRD_PARTY_NAME}
  INSTALL_COMMAND   ""
  CMAKE_ARGS        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DSM=${SM} -DBUILD_PD=ON -DBUILD_ENCODER=${WITH_ENCODER} -DPY_CMD=${PY_CMD} -DON_INFER=${ON_INFER} -DPADDLE_LIB=${PADDLE_LIB} -DWITH_MKL=${WITH_MKL} -DWITH_STATIC_LIB=${WITH_STATIC_LIB} -DBUILD_GPT=${WITH_PARALLEL} -DWITH_ONNXRUNTIME=${WITH_ONNXRUNTIME}
)
```

**Comment by guoshengCS** [comment]
另外也想请问下您那边是什么任务场景，希望使用哪个模型做加速呢

**Comment by BenfengXu** [comment]
> 另外也想请问下您那边是什么任务场景，希望使用哪个模型做加速呢

感谢回复！

目前做的是prompt learning相关的学术研究，使用的是gpt和opt

**Comment by mymynew** [comment]
@guoshengCS 
PaddleNLP2.5.2离线镜像部署，按你说的改了CMakeLists.txt。但是，报如下的错，可以看看什么原因不
```java
[2023-06-30 17:27:39,435] [ WARNING] - Accessing `no_repeat_ngram_size` through `model.no_repeat_ngram_size` will be deprecated after v2.6.0. Instead, do `model.config.no_repeat_ngram_size`
2023-06-30 17:27:39,494 - INFO - Using Python interpreter: /usr/bin/python, version: Python 3.7.13
Compiling user custom op, it will cost a few seconds.....
2023-06-30 17:27:39,495 - INFO - execute command: cd /root/.paddlenlp/extensions/f7f6547e0d59428b8b3e61c4a9fd3a01/FastGeneration && /usr/bin/python FastGeneration_setup.py build
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
running build
running build_ext
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- The CUDA compiler identification is NVIDIA 11.2.142
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found suitable version "11.2", minimum required is "10.1")
-- Assign GPU architecture (sm=60)
-- BOOST_TAR: boost_1_41_0, BOOST_URL: /home/testwork/paddlenlp/boost_1_41_0.tar.gz
-- Add DCUDA11_MODE
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
-- PADDLE_VERSION: 2.4.2

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
-- Configuring done
-- Generating done
-- Build files have been written to: /root/.paddlenlp/extensions/f7f6547e0d59428b8b3e61c4a9fd3a01/FastGeneration/build/temp.linux-x86_64-3.7
Scanning dependencies of target extern_boost
[  2%] Creating directories for 'extern_boost'
[  4%] Performing download step (verify and extract) for 'extern_boost'
CMake Warning at extern_boost-stamp/verify-extern_boost.cmake:15 (message):
  File will not be verified since no URL_HASH specified


-- extracting...
     src='/home/testwork/paddlenlp/boost_1_41_0.tar.gz'
     dst='/root/.paddlenlp/extensions/f7f6547e0d59428b8b3e61c4a9fd3a01/FastGeneration/build/temp.linux-x86_64-3.7/third-party/source/boost/src/extern_boost'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  6%] No patch step for 'extern_boost'
[  8%] No update step for 'extern_boost'
[ 10%] No configure step for 'extern_boost'
[ 12%] No build step for 'extern_boost'
[ 14%] No install step for 'extern_boost'
[ 17%] Completed 'extern_boost'
[ 17%] Built target extern_boost
Scanning dependencies of target extern_fastertransformer
[ 19%] Creating directories for 'extern_fastertransformer'
[ 21%] No download step for 'extern_fastertransformer'
[ 23%] No patch step for 'extern_fastertransformer'
[ 25%] Performing update step for 'extern_fastertransformer'
fatal: not a git repository (or any of the parent directories): .git
CMakeFiles/extern_fastertransformer.dir/build.make:94: recipe for target 'third-party/src/extern_fastertransformer-stamp/extern_fastertransformer-update' failed
make[2]: *** [third-party/src/extern_fastertransformer-stamp/extern_fastertransformer-update] Error 128
CMakeFiles/Makefile2:144: recipe for target 'CMakeFiles/extern_fastertransformer.dir/all' failed
make[1]: *** [CMakeFiles/extern_fastertransformer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
[2023-06-30 17:28:00,722] [ WARNING] - FastGeneration is not available due to build errors.
Traceback (most recent call last):
  File "FastGeneration_setup.py", line 11, in <module>
    output_dir=r'/root/.paddlenlp/extensions/f7f6547e0d59428b8b3e61c4a9fd3a01/FastGeneration')
  File "/usr/local/lib/python3.7/dist-packages/setuptools-50.3.2-py3.7.egg/setuptools/__init__.py", line 153, in setup
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools-50.3.2-py3.7.egg/setuptools/command/build_ext.py", line 79, in run
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/ext_utils.py", line 198, in build_extensions
    ext.build_with_command(self)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/ext_utils.py", line 176, in build_with_command
    raise e
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/ext_utils.py", line 165, in build_with_command
    super(FasterTransformerExtension, self).build_with_command(ext_builder)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/ext_utils.py", line 116, in build_with_command
    ["cmake", "--build", "."] + build_args, cwd=ext_builder.build_temp, stdout=stdout, stderr=stdout
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
[2023-06-30 17:28:01,287] [ WARNING] - Failed to run command: <built-in function compile>, errors: Command 'cd /root/.paddlenlp/extensions/f7f6547e0d59428b8b3e61c4a9fd3a01/FastGeneration && /usr/bin/python FastGeneration_setup.py build' returned non-zero exit status 1.
[2023-06-30 17:28:01,289] [ WARNING] - FastGeneration is not available, and the original version would be used instead.
```
