### ISSUE TITLE
[Question]: faq_finance 在启动 Pipeline Server后在哪里修改Tokenizer？另外python web_service.py后会报错，想知道是什么原因

### ISSUE THREAD

**Issue by eikoor11** [PaddlePaddle/PaddleNLP#3467]
### 请提出你的问题

运行web_service.py的报错
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path      
    main_content = runpy.run_path(main_path,
  File "D:\anaconda\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\anaconda\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\PaddleNLP-develop\applications\question_answering\faq_finance\deploy\python\web_service.py", line 82, in <module>
    ernie_service.run_service()
  File "D:\anaconda\lib\site-packages\paddle_serving_server\web_service.py", line 69, in run_service
    self._server.run_server()
  File "D:\anaconda\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 314, in run_server
    PipelineServicer(self._name, self._response_op, self._conf),
  File "D:\anaconda\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 57, in __init__
    raise CustomException(CustomExceptionCode.INIT_ERROR, "pipeline server init error")
paddle_serving_server.pipeline.error_catch.CustomException:
        exception_code: 3003
        exception_type: INIT_ERROR
        error_msg: pipeline server init error
        is_send_to_user: False

**Comment by eikoor11** [comment]
更新成paddle-serving-server-gpu==0.9.0.post112后运行web_service.py的报错
config use_encryption model here None
config use_encryption model here None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path      
    main_content = runpy.run_path(main_path,
  File "D:\anaconda\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\anaconda\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\PaddleNLP-develop\applications\question_answering\faq_finance\deploy\python\web_service.py", line 82, in <module>
    ernie_service.run_service()
  File "D:\anaconda\lib\site-packages\paddle_serving_server\web_service.py", line 69, in run_service
    self._server.run_server()
  File "D:\anaconda\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 314, in run_server
    PipelineServicer(self._name, self._response_op, self._conf),
  File "D:\anaconda\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 57, in __init__
    raise CustomException(CustomExceptionCode.INIT_ERROR, "pipeline server init error")    
paddle_serving_server.pipeline.error_catch.CustomException:
        exception_code: 3003
        exception_type: INIT_ERROR
        error_msg: pipeline server init error
        is_send_to_user: False

**Comment by w5688414** [comment]
请贴一下您的paddle serving的环境，这是我测试的环境，没啥问题

```
paddle-serving-app             0.9.0
paddle-serving-client          0.9.0
paddle-serving-server          0.9.0
```

**Comment by eikoor11** [comment]
python:3.9.12
cuda:10.2
Name: paddlepaddle-gpu Version: 2.3.2
Name: paddle-serving-client Version: 0.8.3
Name: paddle-serving-app Version: 0.8.3
Name: paddle-serving-server Version: 0.8.3
0.9.0好像在3.9.12版本的python里面找不到
另外想问您启动pipelines服务时，服务端运行脚本run_server.sh和客户端界面脚本run_client.sh应该如何修改，我可能pipelines没有成功给本项目启动，十分麻烦您！

**Comment by eikoor11** [comment]
> 请贴一下您的paddle serving的环境，这是我测试的环境，没啥问题
> 
> ```
> paddle-serving-app             0.9.0
> paddle-serving-client          0.9.0
> paddle-serving-server          0.9.0
> ```



> 请贴一下您的paddle serving的环境，这是我测试的环境，没啥问题
> 
> ```
> paddle-serving-app             0.9.0
> paddle-serving-client          0.9.0
> paddle-serving-server          0.9.0
> ```

python:3.9.12
cuda:10.2
Name: paddlepaddle-gpu Version: 2.3.2
Name: paddle-serving-client Version: 0.8.3
Name: paddle-serving-app Version: 0.8.3
Name: paddle-serving-server Version: 0.8.3
0.9.0好像在3.9.12版本的python里面找不到
另外想问您启动pipelines服务时，服务端运行脚本run_server.sh和客户端界面脚本run_client.sh应该如何修改，我可能pipelines没有成功给本项目启动，十分麻烦您！

**Comment by eikoor11** [comment]
> 请贴一下您的paddle serving的环境，这是我测试的环境，没啥问题
> 
> ```
> paddle-serving-app             0.9.0
> paddle-serving-client          0.9.0
> paddle-serving-server          0.9.0
> ```

python:3.9.12
cuda:10.2
Name: paddlepaddle-gpu Version: 2.3.2
Name: paddle-serving-client Version: 0.8.3
Name: paddle-serving-app Version: 0.8.3
Name: paddle-serving-server Version: 0.8.3
0.9.0好像在3.9.12版本的python里面找不到
另外想问您启动pipelines服务时，服务端运行脚本run_server.sh和客户端界面脚本run_client.sh应该如何修改，我可能pipelines没有成功给本项目启动，十分麻烦您！

**Comment by w5688414** [comment]
@eikoor11 
这里的pipeline是Paddle Serving的Pipline，不是paddlenlp发布的pipelines哈

另外，我测了0.9版本，没啥问题，0.8.3运行有问题没？

**Comment by eikoor11** [comment]
> @eikoor11 这里的pipeline是Paddle Serving的Pipline，不是paddlenlp发布的pipelines哈
> 
> 另外，我测了0.9版本，没啥问题，0.8.3运行有问题没？
将版本换成了0.9.0版本，还是报一样的错

**Comment by eikoor11** [comment]
@w5688414 

> @eikoor11 这里的pipeline是Paddle Serving的Pipline，不是paddlenlp发布的pipelines哈
> 
> 另外，我测了0.9版本，没啥问题，0.8.3运行有问题没？

将版本升级成0.9版本，还是会报一样的错，不知道咋回事qaq

**Comment by w5688414** [comment]
@eikoor11 

请参考这个pr的实现，支持了windows. https://github.com/PaddlePaddle/PaddleNLP/pull/3491
