### ISSUE TITLE
[Bug]: uie训练代码中utils.py文件中result变量未定义

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3488]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.3.0
- paddlenlp: 2.4
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "./finetune.py", line 167, in <module>
    do_train()
  File "./finetune.py", line 51, in do_train
    train_ds = load_dataset(reader,
  File "/home/ma-user/work/name_ner/uie_slim/paddlenlp/datasets/dataset.py", line 196, in load_dataset
    return reader_instance.read(**custom_kwargs)
  File "/home/ma-user/work/name_ner/uie_slim/paddlenlp/datasets/dataset.py", line 833, in read
    return MapDataset(list(examples))
  File "/home/ma-user/work/name_ner/uie_slim/utils.py", line 225, in reader
    if result['end'] - result['start'] > max_content_len:
UnboundLocalError: local variable 'result' referenced before assignment
```

### 稳定复现步骤 & 代码

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/utils.py
第225行，result变量未定义

**Comment by westfish** [comment]
已修复，见PR：Bug fix uie utils #3490
