### ISSUE TITLE
[Bug]: 文本分类few-shot离线部署报错

### ISSUE THREAD

**Issue by FFinchR** [PaddlePaddle/PaddleNLP#3504]
### 软件环境

```Markdown
- paddle-bfloat         0.1.7          
- paddle2onnx           1.0.0          
- paddlefsl             1.1.0          
- paddlenlp             2.4.1          
- paddleocr             2.6.0.1        
- paddlepaddle-gpu      2.3.2.post112
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
文本分类多标签few-shot离线部署报错
```

### 稳定复现步骤 & 代码

按照[few-shot](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/few-shot)的步骤进行训练与部署，在离线部署时报错：
指令：
`python infer.py --model_path_prefix checkpoints/export/model --data_dir ./data --batch_size 32 --device gpu --device_id 0`
报错：
```
2022-10-19 03:38:33.285240768 [E:onnxruntime:, sequential_executor.cc:368 Execute] Non-zero status code returned while running Mul node. Name:'p2o.Mul.118' Status Message: p2o.Mul.118: right operand cannot broadcast on dim 1 LeftShape: {10,128,768}, RightShape: {10,127,1}
Traceback (most recent call last):
  File "infer.py", line 212, in <module>
    predictor.predict(text_list)
  File "infer.py", line 149, in predict
    infer_result = self.infer_batch(encoded_inputs)
  File "infer.py", line 166, in infer_batch
    results = self._infer(input_dict)
  File "infer.py", line 155, in _infer
    infer_data = self.inference_backend.infer(input_dict)
  File "infer.py", line 129, in infer
    result = self.predictor.run(None, input_dict)
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Mul node. Name:'p2o.Mul.118' Status Message: p2o.Mul.118: right operand cannot broadcast on dim 1 LeftShape: {10,128,768}, RightShape: {10,127,1}
```

**Comment by LemonNoel** [comment]
请问paddle版本是多少呢？可以试下安装`pip install paddlepaddle-gpu==2.4rc`，然后重新导出模型再部署。

**Comment by FFinchR** [comment]
> 请问paddle版本是多少呢？可以试下安装`pip install paddlepaddle-gpu==2.4rc`，然后重新导出模型再部署。

我更新paddle版本为2.4rc后可以正常部署，感谢。
