### ISSUE TITLE
[Bug]: ValueError: parameter name [conv1_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

### ISSUE THREAD

**Issue by wn1652400018** [PaddlePaddle/PaddleNLP#3511]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu:  2.3.2 
- paddlenlp: 2.4.1
```

### 重复问题

- [ ] I have searched the existing issues

### 错误描述

```Markdown
执行这一行代码：ErnieLayoutForTokenClassification.from_pretrained('ernie-layoutx-base-uncased', num_classes=2)报错：
Traceback (most recent call last):
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-4a05e53adfe6>", line 1, in <module>
    ErnieLayoutForTokenClassification.from_pretrained('ernie-layoutx-base-uncased', num_classes=2)
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\paddlenlp\transformers\model_utils.py", line 348, in from_pretrained
    base_model = cls.base_model_class(*base_args, **base_kwargs)
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\paddlenlp\transformers\utils.py", line 159, in __impl__
    init_func(self, *args, **kwargs)
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\paddlenlp\transformers\ernie_layout\modeling.py", line 697, in __init__
    self.visual = VisualBackbone(config)
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\paddlenlp\transformers\ernie_layout\modeling.py", line 624, in __init__
    self.backbone = ResNet(layers=101)
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\paddlenlp\transformers\ernie_layout\visual_backbone.py", line 200, in __init__
    self.conv = ConvBNLayer(num_channels=self.input_image_channel,
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\paddlenlp\transformers\ernie_layout\visual_backbone.py", line 37, in __init__
    self._conv = Conv2D(in_channels=num_channels,
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\paddle\nn\layer\conv.py", line 644, in __init__
    super(Conv2D, self).__init__(
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\paddle\nn\layer\conv.py", line 133, in __init__
    self.weight = self.create_parameter(
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\paddle\fluid\dygraph\layers.py", line 423, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "C:\Users\16524\.conda\envs\torch10\lib\site-packages\paddle\fluid\layer_helper_base.py", line 371, in create_parameter
    raise ValueError(
ValueError: parameter name [conv1_weights] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers
```

### 稳定复现步骤 & 代码

ErnieLayoutForTokenClassification.from_pretrained('ernie-layoutx-base-uncased', num_classes=2)

**Comment by wn1652400018** [comment]
这个问题还没解决吗

**Comment by linjieccc** [comment]
你好，感谢反馈问题

这里因为ResNet组网中固定了参数名，所以在模型重复实例化的时候会有上面这个问题，我们会在下个版本修复这个问题
参考这里：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie_layout/visual_backbone.py#L43

当前版本如果有重复实例化模型的需求，可以在执行
```python
model = ErnieLayoutForTokenClassification.from_pretrained('ernie-layoutx-base-uncased', num_classes=2)
```
之前加上这两行代码
```python
paddle.enable_static()
paddle.disable_static()
```
