### ISSUE TITLE
[Question]: ValueError: all input arrays must have the same shape

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/PaddleNLP#3525]
## 1.代码
代码很简单，加载训练好的模型，然后预测，最后一条报错
```python
 prompt = ['犯罪嫌疑人情况','被害人','被害人类型','犯罪嫌疑人交通工具','犯罪嫌疑人交通工具情况','被害人交通工具情况','犯罪嫌疑人责任认定','被害人责任认定','事故发生地','被害人交通工具'] 
                ie = Taskflow(task='information_extraction', schema=prompt, task_path='checkpoint/model_best')           
                for line in task_data_list:
                    try:
                        p_lab={}          
                        result = ie(line[tq_name].strip('\n').strip())
                        print(line['id'], result)
                        for entity_type in prompt:
                            p_lab[entity_type] = []
                            if entity_type not in result[0]:
                                p_lab[entity_type].append([])
                                continue
                            for samp in result[0][entity_type]:
                                p_lab[entity_type].append([samp['start'], samp['end']])  
                    except:
                        continue                      
                    output.write(json.dumps({'id':line['id'], 'data':line[tq_name], 'task':line['task'], 'label':p_lab}, ensure_ascii=False)+'\n')
```

## 2.错误信息
前面的预测都好，最后一条报错，但是也不对应自己写的代码。
```bash
'end': 41, 'probability': 0.9971743849990844}], '犯罪嫌疑人责任认定': [{'text': '主要责任', 'start': 157, 'end': 161, 'probability': 0.999251083222795}], '被害人责任认定': [{'text': '次要责任', 'start': 169, 'end': 173, 'probability': 0.8207608798398383}], '事故发生地': [{'text': '金谷嘉园小区门前东侧路段', 'start': 61, 'end': 73, 'probability': 0.9882963176557382}]}]
[2022-10-20 18:00:10,274] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'checkpoint/model_best'.
Exception in thread Thread-1219:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 138, in fetch
    data = self.collate_fn(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 77, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 77, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

**Comment by livingbody** [comment]
经排查，发现句子中带[sep] 就报错了。
去掉就好了。

```
from paddlenlp import Taskflow

prompt="'刑档': '[一档,二档,三档]"
ie = Taskflow(task='information_extraction', schema=prompt, task_path='checkpoint/model_best')
# data="交通肇事罪[SEP]江苏省[SEP]本院认为，被告人李腾夜间驾驶超载的机动车上道路行驶，因观察疏忽，发生重大交通事故，致一人死亡，承担事故主要责任，其行为已构成交通肇事罪，依法应判处三年以下有期徒刑或者拘役。被告人李腾主动报警，如实供述犯罪事实，系自首，依法可以从轻或者减轻处罚；赔偿丧葬费用，酌情从轻处罚。公诉机关指控被告人李腾犯交通肇事罪事实清楚，证据确实、充分，指控的罪名正确，本院予以采纳。关于辩护人提出被告人李腾具有自首情节、赔偿了丧葬费用以及所驾驶车辆投保了相关保险等请求从轻处罚的辩护意见，经查属实，予以采纳。据此，[SEP]经审理查明：2019年8月10日3时许，被告人李腾驾驶苏C号重型普通货车沿505省道由西向东行驶至XX地段时，因观察疏忽与同向前方机动车道内袁某骑行的电动自行车及谢某甲驾驶的无号牌正三轮摩托车发生事故，致袁某当场死亡，谢某甲受伤，三车损坏。经新沂市公安局物证鉴定室法医学尸体检验，袁某符合交通事故致胸腹腔脏器损伤死亡。经新沂市公安局交通警察大队道路交通事故认定，被告人李腾承担事故主要责任。事故发生后，被告人李腾主动拨打电话报警，并在现场等候交警处理，归案后如实供述犯罪事实，并自愿认罪认罚；且已赔偿丧葬费3万元。"
data="交通肇事罪江苏省本院认为，被告人李腾夜间驾驶超载的机动车上道路行驶，因观察疏忽，发生重大交通事故，致一人死亡，承担事故主要责任，其行为已构成交通肇事罪，依法应判处三年以下有期徒刑或者拘役。被告人李腾主动报警，如实供述犯罪事实，系自首，依法可以从轻或者减轻处罚；赔偿丧葬费用，酌情从轻处罚。公诉机关指控被告人李腾犯交通肇事罪事实清楚，证据确实、充分，指控的罪名正确，本院予以采纳。关于辩护人提出被告人李腾具有自首情节、赔偿了丧葬费用以及所驾驶车辆投保了相关保险等请求从轻处罚的辩护意见，经查属实，予以采纳。据此，经审理查明：2019年8月10日3时许，被告人李腾驾驶苏C号重型普通货车沿505省道由西向东行驶至XX地段时，因观察疏忽与同向前方机动车道内袁某骑行的电动自行车及谢某甲驾驶的无号牌正三轮摩托车发生事故，致袁某当场死亡，谢某甲受伤，三车损坏。经新沂市公安局物证鉴定室法医学尸体检验，袁某符合交通事故致胸腹腔脏器损伤死亡。经新沂市公安局交通警察大队道路交通事故认定，被告人李腾承担事故主要责任。事故发生后，被告人李腾主动拨打电话报警，并在现场等候交警处理，归案后如实供述犯罪事实，并自愿认罪认罚；且已赔偿丧葬费3万元。"
result = ie(data)
result
```


```
[{"'刑档': '[一档,二档,三档]": [{'text': '一档', 'probability': 0.36714996014665147}]}]
```

**Comment by wawltor** [comment]
您好，我们先关闭该issue，如果有问题的话可以再次打开。
