### ISSUE TITLE
[Bug]: multi-class裁剪报错

### ISSUE THREAD

**Issue by FFinchR** [PaddlePaddle/PaddleNLP#3530]
### 软件环境

```Markdown
- paddle-bfloat         0.1.7           
- paddle2onnx           1.0.1           
- paddlefsl             1.1.0           
- paddlenlp             2.4.1           
- paddleocr             2.6.0.1         
- paddlepaddle-gpu      2.4.0rc0.post112
- paddleslim            2.3.4
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
多分类模型裁剪报错
```

### 稳定复现步骤 & 代码

参考[multi_class](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class)的裁剪时报错。
指令：
```shell
python prune.py \
    --device "gpu" \
    --dataset_dir "data" \
    --output_dir "prune" \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 32 \
    --num_train_epochs 10 \
    --max_seq_length 128 \
    --logging_steps 5 \
    --save_steps 100 \
    --width_mult_list '3/4' '2/3' '1/2'
```
报错信息：
```
Traceback (most recent call last):
  File "prune.py", line 112, in <module>
    main()
  File "prune.py", line 108, in main
    trainer.compress()
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/trainer_compress.py", line 63, in compress
    _dynabert(self, self.model, args.output_dir)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/trainer_compress.py", line 123, in _dynabert
    ofa_model, teacher_model = _dynabert_init(self, model, eval_dataloader)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/trainer_compress.py", line 265, in _dynabert_init
    custom_dynabert_calc_loss=self.custom_dynabert_calc_loss)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/ofa_utils.py", line 348, in compute_neuron_head_importance
    loss = calc_loss(loss_fct, model, batch, head_mask)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/ofa_utils.py", line 269, in calc_loss
    attention_mask=[None, head_mask])
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/ernie/modeling.py", line 1131, in forward
    return_dict=return_dict)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/trainer_compress.py", line 671, in auto_model_forward
    embedding_output = self.embeddings(**embedding_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/ernie/modeling.py", line 119, in forward
    embeddings = self.layer_norm(embeddings)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddleslim/nas/ofa/layers.py", line 1186, in forward
    out, _, _, = _C_ops.final_state_layer_norm(
AttributeError: module 'paddle.fluid.libpaddle.eager.ops' has no attribute 'final_state_layer_norm'
```

**Comment by LiuChiachi** [comment]
您好，感谢您关注。
我这边没有直接复现这样的问题。请问您的paddlepaddle环境和paddlenlp的版本是？如果您跑的是仓库里原本的代码，可能是环境依赖的原因，建议升级试试～

**Comment by LiuChiachi** [comment]
您好，请问您对原本的裁减代码有做一些修改吗？您的数据在fine-tuning时是正常的吗？

**Comment by FFinchR** [comment]
> 您好，请问您对原本的裁减代码有做一些修改吗？您的数据在fine-tuning时是正常的吗？

没有修改，就是直接按multi-class的README.md一步步做下来的，finetune的时候是正常的，想做裁剪的时候出问题了。

**Comment by LiuChiachi** [comment]
您好，我使用您提供的版本复现了问题，更新成最新版本的paddleslim可以避免这个问题：
```
pip uninstall paddleslim
git clone https://github.com/PaddlePaddle/PaddleSlim.git & cd PaddleSlim
python setup.py install
```

**Comment by FFinchR** [comment]
> 您好，我使用您提供的版本复现了问题，更新成最新版本的paddleslim可以避免这个问题：
> 
> ```
> pip uninstall paddleslim
> git clone https://github.com/PaddlePaddle/PaddleSlim.git & cd PaddleSlim
> python setup.py install
> ```

你好，我按照以上步骤更新了最新版本的paddleslim后，遇到了如下报错：
> WARNING:root:No module named 'parl'
> 2022-11-04 03:12:49,210-WARNING: Some functions fail to import, please update PaddlePaddle version to 2.4+

但是我的paddlepaddle-gpu版本已经是https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html 上能找到的最新版本。
> Name: paddlepaddle-gpu
> Version: 2.4.0rc0.post112

还有更新的版本吗？

**Comment by LiuChiachi** [comment]
PaddlePaddle版本应该没有问题，而且这个warning应该不会影响运行。您还遇到其他问题了吗

**Comment by FFinchR** [comment]
> PaddlePaddle版本应该没有问题，而且这个warning应该不会影响运行。您还遇到其他问题了吗

不好意思，是我之前操作失误，把训练和裁剪放在一个gpu，导致显存不足；
又因使用的gunicorn部署，没有报出显存不足的错误就跳出。
暂时没有其他问题了，谢谢。
