### ISSUE TITLE
将lexical_analysis模型从动态图转换为静态图失败

### ISSUE THREAD

**Issue by yanzhelee** [PaddlePaddle/PaddleNLP#359]
按照 PaddleNLP/examples/lexical_analysis 中提供的demo可以训练网络模型，但是无法将动态图转换为静态图。
目前尝试了 paddle.jit.save, paddle.jit.to_static, TracedLayer.trace 等方法，但是均失败。
报错信息如下：

```python
Traceback (most recent call last):
  File "/Users/liyanzhe/Library/Application Support/IntelliJIdea2019.2/python/helpers/pydev/pydevd.py", line 2066, in <module>
    main()
  File "/Users/liyanzhe/Library/Application Support/IntelliJIdea2019.2/python/helpers/pydev/pydevd.py", line 2060, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/liyanzhe/Library/Application Support/IntelliJIdea2019.2/python/helpers/pydev/pydevd.py", line 1411, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Users/liyanzhe/Library/Application Support/IntelliJIdea2019.2/python/helpers/pydev/pydevd.py", line 1418, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/liyanzhe/Library/Application Support/IntelliJIdea2019.2/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/liyanzhe/code/baidupy/contact_ner_full/save_infer_model.py", line 124, in <module>
    save(args)
  File "/Users/liyanzhe/code/baidupy/contact_ner_full/save_infer_model.py", line 110, in save
    path="./infer_model"
  File "<decorator-gen-167>", line 2, in save
  File "/Users/liyanzhe/bin/anaconda3/envs/paddle20/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/Users/liyanzhe/bin/anaconda3/envs/paddle20/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/Users/liyanzhe/bin/anaconda3/envs/paddle20/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 686, in save
    concrete_program = static_forward.concrete_program
  File "/Users/liyanzhe/bin/anaconda3/envs/paddle20/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/Users/liyanzhe/bin/anaconda3/envs/paddle20/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 493, in concrete_program_specify_input_spec
    format(self._function_spec))
ValueError: No valid transformed program for function: forward(inputs,lengths), input_spec: None.
	    Please specific `input_spec` in `@paddle.jit.to_static` or feed input tensor to call the decorated function at once.

```

**Comment by wawltor** [comment]
您好 这个问题我们正在解决，有结果之后反馈给您！

**Comment by yanzhelee** [comment]
> 您好 这个问题我们正在解决，有结果之后反馈给您！

**Comment by yanzhelee** [comment]
debug了一下源码，问题应该是出在 ViterbiDecoder上，forward函数中含有 tolist，tensor转numpy的操作。

**Comment by yanzhelee** [comment]
嗯嗯 是的 to_tensor和一些for循环对动转静都有影响
> > 您好 这个问题我们正在解决，有结果之后反馈给您！

debug了一下源码，问题应该是出在 ViterbiDecoder上，forward函数中含有 tolist，tensor转numpy的操作。

**Comment by wawltor** [comment]
> 嗯嗯 是的 to_tensor和一些for循环对动转静都有影响
> 
> > > 您好 这个问题我们正在解决，有结果之后反馈给您！
> 
> debug了一下源码，问题应该是出在 ViterbiDecoder上，forward函数中含有 tolist，tensor转numpy的操作。

嗯嗯 是的，主要是在一些to_tensor 和 for循环之类的转换有问题

**Comment by yanzhelee** [comment]
@ZeyuChen 还有一个问题就是动态图中的LinearChainCrf的参数transitions的shape和静态图中的linear_chain_crf的参数的shape不一致。
在with_start_stop_tag=True的情况下,LinearChainCrf.transitions.shape=[num_labels+2, num_labels+2],
在with_start_stop_tag=False的情况下,LinearChainCrf.transitions.shape=[num_labels, num_labels]，
而 linear_chain_crf.transitions.shape=[num_labels+2, num_label]。
所以将训练好的参数也没有办法统一转换。

**Comment by wawltor** [comment]
> @ZeyuChen 还有一个问题就是动态图中的LinearChainCrf的参数transitions的shape和静态图中的linear_chain_crf的参数的shape不一致。
> 在with_start_stop_tag=True的情况下,LinearChainCrf.transitions.shape=[num_labels+2, num_labels+2],
> 在with_start_stop_tag=False的情况下,LinearChainCrf.transitions.shape=[num_labels, num_labels]，
> 而 linear_chain_crf.transitions.shape=[num_labels+2, num_label]。
> 所以将训练好的参数也没有办法统一转换。

嗯嗯 好的，这个问题我们记录下来了，在修复版本中我们会对这个flag的True or False的动转静都进行测试。

**Comment by wawltor** [comment]
您好，最新的LAC的动转静的修复PR已经合入了，具体的使用方法可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/lexical_analysis  @yanzhelee

<img width="1210" alt="图片" src="https://user-images.githubusercontent.com/16698950/118497306-86690780-b757-11eb-86ef-6b0de06e79a8.png">

**Comment by ZeyuChen** [comment]
Issues resolved.
