### ISSUE TITLE
[Bug]: uie模型部署报错，显示GPU不可用CUDAExecutionProvider，CPU可以用

### ISSUE THREAD

**Issue by done520** [PaddlePaddle/PaddleNLP#3599]
### 软件环境

```Markdown
paddle-bfloat        0.1.7
paddle2onnx          1.0.1
paddlefsl            1.1.0
paddlenlp            2.4.2
paddlepaddle-gpu     2.3.2.post101
onnx                 1.12.2
onnxconverter-common 1.12.2
onnxruntime-gpu      1.13.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
PaddlePaddle-gpu可用，但是paddlenlp无法使用gpu:
----------------------------------------
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle 
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W1028 14:25:17.988360 10222 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.1
W1028 14:25:18.120314 10222 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>>> 
-----------------------------------
参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie#%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2
导出uie模型，然后使用：python deploy/python/infer_gpu.py --model_path_prefix export/inference --use_fp16 --device_id 0 报错：
2022-10-28 14:30:49,033] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2022-10-28 14:30:49,033] [    INFO] - Already cached /home/user/.paddlenlp/models/ernie-3.0-base-zh/ernie_3.0_base_zh_vocab.txt
[2022-10-28 14:30:49,088] [    INFO] - tokenizer config file saved in /home/user/.paddlenlp/models/ernie-3.0-base-zh/tokenizer_config.json
[2022-10-28 14:30:49,089] [    INFO] - Special tokens file saved in /home/user/.paddlenlp/models/ernie-3.0-base-zh/special_tokens_map.json
>>> [InferBackend] Creating Engine ...
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: export/inference.pdmodel
[Paddle2ONNX] Paramters file path: export/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 13 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
>>> [InferBackend] Use GPU to inference ...
2022-10-28 14:31:01.979889643 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
Traceback (most recent call last):
  File "deploy/python/infer_gpu.py", line 101, in <module>
    main()
  File "deploy/python/infer_gpu.py", line 74, in main
    predictor = UIEPredictor(args)
  File "/data/1_qunosen/project/key_pharse/uie/deploy/python/uie_predictor.py", line 103, in __init__
    device_id=args.device_id)
  File "/data/1_qunosen/project/key_pharse/uie/deploy/python/uie_predictor.py", line 67, in __init__
    assert 'CUDAExecutionProvider' in self.predictor.get_providers(), f"The environment for GPU inference is not set properly. " \
AssertionError: The environment for GPU inference is not set properly. A possible cause is that you had installed both onnxruntime and onnxruntime-gpu. Please run the following commands to reinstall: 
 1) pip uninstall -y onnxruntime onnxruntime-gpu 
 2) pip install onnxruntime-gpu

另外，尝试将onnx降级为1.9.0，Gpu推理仍是相同的错误
```

### 稳定复现步骤 & 代码

CPU可用：python deploy/python/infer_cpu.py --model_path_prefix export/inference

GPU不可用：python deploy/python/infer_gpu.py --model_path_prefix export/inference

**Comment by linjieccc** [comment]
@done520 你好，可以尝试安装与驱动CUDA版本对应的paddle再试下

```shell
python -m pip install paddlepaddle-gpu==2.3.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```

**Comment by done520** [comment]
你好，我的cuda为10.1，驱动为11.2，按照如上按照后，出现相同的错误：
$ python deploy/python/infer_gpu.py --model_path_prefix export/inference 
[2022-10-28 15:30:30,305] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2022-10-28 15:30:30,305] [    INFO] - Already cached /home/user/.paddlenlp/models/ernie-3.0-base-zh/ernie_3.0_base_zh_vocab.txt
[2022-10-28 15:30:30,339] [    INFO] - tokenizer config file saved in /home/user/.paddlenlp/models/ernie-3.0-base-zh/tokenizer_config.json
[2022-10-28 15:30:30,339] [    INFO] - Special tokens file saved in /home/user/.paddlenlp/models/ernie-3.0-base-zh/special_tokens_map.json
>>> [InferBackend] Creating Engine ...
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: export/inference.pdmodel
[Paddle2ONNX] Paramters file path: export/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 13 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
>>> [InferBackend] Use GPU to inference ...
2022-10-28 15:30:40.500922902 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
Traceback (most recent call last):
  File "deploy/python/infer_gpu.py", line 101, in <module>
    main()
  File "deploy/python/infer_gpu.py", line 74, in main
    predictor = UIEPredictor(args)
  File "/data/1_qunosen/project/key_pharse/uie/deploy/python/uie_predictor.py", line 103, in __init__
    device_id=args.device_id)
  File "/data/1_qunosen/project/key_pharse/uie/deploy/python/uie_predictor.py", line 67, in __init__
    assert 'CUDAExecutionProvider' in self.predictor.get_providers(), f"The environment for GPU inference is not set properly. " \
AssertionError: The environment for GPU inference is not set properly. A possible cause is that you had installed both onnxruntime and onnxruntime-gpu. Please run the following commands to reinstall: 
 1) pip uninstall -y onnxruntime onnxruntime-gpu 
 2) pip install onnxruntime-gpu
(paddlenlp)

**Comment by linjieccc** [comment]
检查下环境里面是否已卸载onnxruntime并且安装了onnxruntime-gpu

**Comment by wawltor** [comment]
> 检查下环境里面是否已卸载onnxruntime并且安装了onnxruntime-gpu

cuda版本确保是11.x版本，以及安装的paddle的版本是cuda 11.x版本

**Comment by done520** [comment]
@linjieccc 已卸载onnxruntime并且安装了onnxruntime-gpu，依然gpu无法推理。
@wawltor 驱动是11.2， paddle是paddlepaddle-gpu==2.3.2.post112

请问， 有什么方法解决吗？

**Comment by wawltor** [comment]
> @linjieccc 已卸载onnxruntime并且安装了onnxruntime-gpu，依然gpu无法推理。 @wawltor 驱动是11.2， paddle是paddlepaddle-gpu==2.3.2.post112
> 
> 请问， 有什么方法解决吗？

是怎么安装paddlepaddle-gpu==2.3.2.post112 是pip还是conda ？

**Comment by done520** [comment]
pip install xxx , 按官方教程

**Comment by wawltor** [comment]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/16698950/198539569-2cf1884e-4848-44e4-8ae4-37185b6b9f5f.png">
https://www.paddlepaddle.org.cn/  建议conda方式安装，同时环境最好是一个新的conda环境

**Comment by done520** [comment]
好的，我试一下

**Comment by done520** [comment]
@wawltor 好像GPU还是不行呀

**Comment by wawltor** [comment]
```python
import paddle
paddle.utils.run_check()
```
可以用这里的代码试一下 check paddle是否安装成功

**Comment by done520** [comment]
@wawltor 测试显示paddlepaddle-gpu已经可以使用了，但是paddlenlp还是不能使用gpu.
