### ISSUE TITLE
[Question]: RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community/Salesforce/codegen-350M-mono\vocab.json failed with code 404!

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/PaddleNLP#3614]
## 如下，taskflow下载模型在windows下失败，url拼写错误。

```
(p2) PS I:\livingbody\PaddleNLP-develop\examples\code_generation\codegen> python .\codegen_server.py
[2022-10-31 13:23:56,007] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/Salesforce/codegen-350M-mono\vocab.json and saved to C:\Users\Administrator\.paddlenlp\models\Salesforce/codegen-350M-mono
[2022-10-31 13:23:56,008] [    INFO] - Downloading vocab.json from https://bj.bcebos.com/paddlenlp/models/community/Salesforce/codegen-350M-mono\vocab.json
[2022-10-31 13:23:56,544] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/community/Salesforce/codegen-350M-mono\vocab.json failed with code 404!
Traceback (most recent call last):
  File "C:\miniconda3\envs\p2\lib\site-packages\paddlenlp\transformers\tokenizer_utils_base.py", line 1560, in from_pretrained
    file_path, default_root)
  File "C:\miniconda3\envs\p2\lib\site-packages\paddlenlp\utils\downloader.py", line 164, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "C:\miniconda3\envs\p2\lib\site-packages\paddlenlp\utils\downloader.py", line 201, in _download
    "{}!".format(url, req.status_code))
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community/Salesforce/codegen-350M-mono\vocab.json failed with code 404!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\codegen_server.py", line 64, in <module>
    tokenizer = CodeGenTokenizer.from_pretrained(generate_config.model_name_or_path)
  File "C:\miniconda3\envs\p2\lib\site-packages\paddlenlp\transformers\tokenizer_utils_base.py", line 1567, in from_pretrained
    f"Can't load tokenizer for '{pretrained_model_name_or_path}'.\n"
RuntimeError: Can't load tokenizer for 'Salesforce/codegen-350M-mono'.
Please make sure that 'Salesforce/codegen-350M-mono' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant tokenizer files.
```

**Comment by gongel** [comment]
你好，我这边linux上测试paddlenlp==2.4.1和2.4.2都没有问题。Windows我们排查下。

**Comment by gongel** [comment]
你好，经测试，确实会存在该问题：Windows平台下载生态模型会存在网址拼接错误的情况，已通过该PR：#3640 修复，感谢你的反馈，我们也同步增加更多的测试。
