### ISSUE TITLE
[Question]: 模型微調 使用英文模型報錯

### ISSUE THREAD

**Issue by coolinstar** [PaddlePaddle/PaddleNLP#3657]
### 请提出你的问题

Error msg : finetune.py: error: argument --model: invalid choice: 'uie-base-en' (choose from 'uie-base', 'uie-tiny', 'uie-medium', 'uie-mini', 'uie-micro', 'uie-nano')

請問目前微型微調是否並未支持英文模型?
未來對於英文模型的支持是否有計畫?

According to the error message above, finetune is not working for English model.
Is there any plan for supporting English in the future?

**Comment by wawltor** [comment]
请拉取最新的PaddleNLP UIE的代码，最新的代码支持 uie-base-en

**Comment by coolinstar** [comment]
> 请拉取最新的PaddleNLP UIE的代码，最新的代码支持 uie-base-en

感謝告知，更新之後，uie-base-en已可實驗。

測試使用 uie-m-base則報錯如下
[2022-11-03 16:36:12,776] [    INFO] - We are using <class 'paddlenlp.transformers.ernie_m.tokenizer.ErnieMTokenizer'> to load 'uie-m-base'.
Traceback (most recent call last):
  File "C:\Users\workspace\vs_workspace\study_zone\paddle\finetune.py", line 287, in <module>
    main()
  File "C:\Users\workspace\vs_workspace\study_zone\paddle\finetune.py", line 138, in main
    model = UIE.from_pretrained(model_args.model_name_or_path)
  File "C:\Users\anaconda3\envs\padpy39\lib\site-packages\paddlenlp\transformers\model_utils.py", line 316, in from_pretrained
    assert arg.pop(
AssertionError: pretrained base model should be ErnieModel

**Comment by coolinstar** [comment]
> 请拉取最新的PaddleNLP UIE的代码，最新的代码支持 uie-base-en
@wawltor   敬請知悉如下


運行  
python finetune.py --device cpu --logging_steps 10 --save_steps 100 --eval_steps 100 --seed 42 
                               --model_name_or_path uie-m-base --output_dir $finetuned_model --train_path data/train.txt 
                               --dev_path data/dev.txt --max_seq_length 512 --per_device_eval_batch_size 16 
                               --per_device_train_batch_size  16 --num_train_epochs 100 --learning_rate 1e-5 
                               --label_names 'start_positions' 'end_positions' --do_train --do_eval --do_export 
                               --export_model_dir $finetuned_model --overwrite_output_dir --disable_tqdm True 
                               --metric_for_best_model eval_f1 --load_best_model_at_end  True --save_total_limit 1 
                               --multilingual True



報錯如下


[2022-11-06 17:57:04,716] [    INFO] -
Training completed.

[2022-11-06 17:57:04,729] [    INFO] - train_runtime: 3249.3458, train_samples_per_second: 0.043, train_steps_per_second: 0.003, train_loss: 0.004191704839468002, epoch: 5.0
[2022-11-06 17:57:04,751] [    INFO] - Saving model checkpoint to $finetuned_model
[2022-11-06 17:57:23,296] [    INFO] - tokenizer config file saved in $finetuned_model\tokenizer_config.json
[2022-11-06 17:57:23,302] [    INFO] - Special tokens file saved in $finetuned_model\special_tokens_map.json
[2022-11-06 17:57:23,438] [    INFO] - ***** train metrics *****
[2022-11-06 17:57:23,442] [    INFO] -   epoch                    =        5.0
[2022-11-06 17:57:23,443] [    INFO] -   train_loss               =     0.0042
[2022-11-06 17:57:23,445] [    INFO] -   train_runtime            = 0:54:09.34
[2022-11-06 17:57:23,445] [    INFO] -   train_samples_per_second =      0.043
[2022-11-06 17:57:23,446] [    INFO] -   train_steps_per_second   =      0.003
[2022-11-06 17:57:23,483] [    INFO] - ***** Running Evaluation *****
[2022-11-06 17:57:23,484] [    INFO] -   Num examples = 6
[2022-11-06 17:57:23,485] [    INFO] -   Pre device batch size = 16
[2022-11-06 17:57:23,486] [    INFO] -   Total Batch size = 16
[2022-11-06 17:57:23,486] [    INFO] -   Total prediction steps = 1
Traceback (most recent call last):
  File "C:\Usersc\workspace\vs_workspace\study_zone\paddle\finetune.py", line 287, in <module>
    main()
  File "C:\Usersc\workspace\vs_workspace\study_zone\paddle\finetune.py", line 218, in main
    eval_metrics = trainer.evaluate()
  File "C:\Usersc\anaconda3\envs\padpy39\lib\site-packages\paddlenlp\trainer\trainer_base.py", line 1336, in evaluate
    output = self.evaluation_loop(
  File "C:\Usersc\anaconda3\envs\padpy39\lib\site-packages\paddlenlp\trainer\trainer_base.py", line 1439, in evaluation_loop
    loss, logits, labels = self.prediction_step(model,
  File "C:\Usersc\anaconda3\envs\padpy39\lib\site-packages\paddlenlp\trainer\trainer_base.py", line 1624, in prediction_step
    outputs = model(**inputs)
  File "C:\Usersc\anaconda3\envs\padpy39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Usersc\anaconda3\envs\padpy39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
TypeError: forward() got an unexpected keyword argument 'start_positions'

**Comment by wawltor** [comment]
麻烦安装develop版本的PaddleNLP，同时使用最新的文档命令

**Comment by coolinstar** [comment]
> 麻烦安装develop版本的PaddleNLP，同时使用最新的文档命令

目前使用anaconda 環境管理版本
根據建議，透過pip 重新安裝paddlenlp 
版本為
paddlenlp                 2.4.1.dev0
運算仍然報與上面相同錯

已確認是使用最新UIE目錄下的finetune相關文檔與指令

請問 @wawltor   您所指的develop版本為此? 是否哪裡仍需要更新?

**Comment by coolinstar** [comment]
@wawltor  
目前無論CPU  GPU  透過paddlenlp 2.4.1 dev0  運行最新指令 都是報同一個錯誤。
![image](https://user-images.githubusercontent.com/9428499/201439840-5dd71fe7-09fd-4430-a831-e2e8871cf5da.png)

回報提供參考

**Comment by wj-Mcat** [comment]
建议直接用git clone获取最新代码来体验，而不是用pip install。

**Comment by coolinstar** [comment]
> 建议直接用git clone获取最新代码来体验，而不是用pip install。
.......................

是用git clone 回來之後配置進去的

![image](https://user-images.githubusercontent.com/9428499/201460531-1a8bcc4c-9e8f-4c50-8298-2fb09f3af853.png)

**Comment by coolinstar** [comment]
> File "C:\Usersc\anaconda3\envs\padpy39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
> outputs = self.forward(*inputs, **kwargs)
> TypeError: forward() got an unexpected keyword argument 'start_positions'

@wawltor   hi，回報測試的進展。

而且追蹤錯誤堆疊，可以看到報錯的位置在paddle 的dygraph裡面，這個部分只有在觸發ERNIEM model的時候才發生，跟paddlenlp關係大嗎??

File "C:\Usersc\anaconda3\envs\padpy39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
outputs = self.forward(*inputs, **kwargs)
TypeError: forward() got an unexpected keyword argument 'start_positions'

**Comment by coolinstar** [comment]
同樣的版本，同樣的指令
改成使用uie-base  訓練中文就不會報錯
回報提供參考

**Comment by coolinstar** [comment]
@wawltor   請問對於上述的情境，有無任何建議或看法? 謝謝。

**Comment by coolinstar** [comment]
@wawltor 請問對於上述的情境，有無任何建議或看法? 謝謝。

**Comment by coolinstar** [comment]
@wawltor  @linjieccc 
此問題跟著之前的討論
調整過的develop版本仍然報錯

另建虛擬環境2.4.3 可運行
請問2.4.3的更新是否除了release note之外
還有其他更動?
