### ISSUE TITLE
[Question]: pegasus模型执行export_model.py在windows和linux环境下，均报错，帮忙看下是啥原因？

### ISSUE THREAD

**Issue by LouisHeck** [PaddlePaddle/PaddleNLP#3681]
### 请提出你的问题

**1. 问题：pegasus模型执行export_model.py在windows和linux环境下，均报错，在windows和linux环境报错如下：**
**2.1 windows环境报错如下：**
  
```
C:\ProgramData\Miniconda3\envs\pp\python.exe C:/Users/Administrator/Downloads/Compressed/PaddleNLP-develop/applications/text_summarization/pegasus/export_model.py
Namespace(decoding_strategy='beam_search', diversity_rate=0.0, inference_model_dir='./inference_model', length_penalty=0.0, max_out_len=64, min_out_len=1, model_name_or_path='IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese', num_beams=4, num_return_sequence=1, num_return_sequences=1, temperature=1.0, topk=4, topp=1.0, use_fp16_decoding=False)
[2022-11-04 19:47:59,642] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\model_state.pdparams and saved to C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese
[2022-11-04 19:47:59,642] [    INFO] - Found C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\model_state.pdparams
[2022-11-04 19:47:59,644] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\model_config.json and saved to C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese
[2022-11-04 19:47:59,644] [    INFO] - Found C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\model_config.json
W1104 19:47:59.645128  4752 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 11.0
W1104 19:47:59.654131  4752 gpu_context.cc:306] device: 0, cuDNN Version: 8.0.
[2022-11-04 19:48:12,922] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\vocab.txt and saved to C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese
[2022-11-04 19:48:12,922] [    INFO] - Found C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\vocab.txt
[2022-11-04 19:48:12,923] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\added_tokens.json and saved to C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese
[2022-11-04 19:48:12,924] [    INFO] - Downloading added_tokens.json from https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\added_tokens.json
[2022-11-04 19:48:13,070] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\special_tokens_map.json and saved to C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese
[2022-11-04 19:48:13,070] [    INFO] - Found C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\special_tokens_map.json
[2022-11-04 19:48:13,071] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\tokenizer_config.json and saved to C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese
[2022-11-04 19:48:13,071] [    INFO] - Found C:\Users\Administrator\.paddlenlp\models\IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese\tokenizer_config.json
Compiling user custom op, it will cost a few seconds.....
2022-11-04 19:48:13,169 - INFO - Using Python interpreter: C:\ProgramData\Miniconda3\envs\pp\python.exe, version: Python 3.7.13
2022-11-04 19:48:13,169 - INFO - execute command: cd /d C:\Users\Administrator\.paddlenlp\extensions\8491a797af4144e99a1389a18deb0e19\FasterTransformer && C:\ProgramData\Miniconda3\envs\pp\python.exe FasterTransformer_setup.py build
running build
running build_ext
Traceback (most recent call last):
  File "FasterTransformer_setup.py", line 11, in <module>
    output_dir=r'C:\Users\Administrator\.paddlenlp\extensions\8491a797af4144e99a1389a18deb0e19\FasterTransformer')
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\_distutils\dist.py", line 985, in run_command
    cmd_obj.ensure_finalized()
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\_distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\paddle\utils\cpp_extension\cpp_extension.py", line 365, in finalize_options
    super(BuildExtension, self).finalize_options()
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\setuptools\command\build_ext.py", line 157, in finalize_options
    filename = ext._file_name = self.get_ext_filename(fullname)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\paddle\utils\cpp_extension\cpp_extension.py", line 598, in get_ext_filename
    len(name_items))
AssertionError: Expected len(name_items) > 2, but received 2
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1148, in run_cmd
    command, shell=True, stderr=subprocess.STDOUT)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /d C:\Users\Administrator\.paddlenlp\extensions\8491a797af4144e99a1389a18deb0e19\FasterTransformer && C:\ProgramData\Miniconda3\envs\pp\python.exe FasterTransformer_setup.py build' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator/Downloads/Compressed/PaddleNLP-develop/applications/text_summarization/pegasus/export_model.py", line 160, in <module>
    do_predict(args)
  File "C:/Users/Administrator/Downloads/Compressed/PaddleNLP-develop/applications/text_summarization/pegasus/export_model.py", line 105, in do_predict
    trans_out=True)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\paddlenlp\transformers\utils.py", line 159, in __impl__
    init_func(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\paddlenlp\ops\faster_transformer\transformer\faster_transformer.py", line 1672, in __init__
    hidden_act=model.pegasus.config['activation_function'])
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\paddlenlp\ops\faster_transformer\transformer\decoding.py", line 2997, in __init__
    load("FasterTransformer", verbose=True)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\paddlenlp\utils\file_lock.py", line 113, in _impl
    func(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\paddlenlp\ops\ext_utils.py", line 310, in load
    _jit_compile(file_path, verbose)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1112, in _jit_compile
    run_cmd(compile_cmd, verbose)
  File "C:\ProgramData\Miniconda3\envs\pp\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1154, in run_cmd
    compile, error))
RuntimeError: Failed to run command: <built-in function compile>, errors: Command 'cd /d C:\Users\Administrator\.paddlenlp\extensions\8491a797af4144e99a1389a18deb0e19\FasterTransformer && C:\ProgramData\Miniconda3\envs\pp\python.exe FasterTransformer_setup.py build' returned non-zero exit status 1.

Process finished with exit code 1

```

**2.2 linux环境报错如下：**
```
         ssh://tongna@192.168.10.196:22/home/tongna/anaconda3/envs/UIE/bin/python3.8 -u /home/tongna/PythonCode/zhangxu/tmp/paddlenlp_series_summarization/export_model.py
cuda_home:  None
Namespace(decoding_strategy='beam_search', diversity_rate=0.0, inference_model_dir='./inference_model', length_penalty=0.0, max_out_len=968, min_out_len=1, model_name_or_path='output/pegeaus_model_3000', num_beams=4, num_return_sequence=1, num_return_sequences=1, temperature=1.0, topk=4, topp=1.0, use_fp16_decoding=False)
2022-11-04 20:11:02,354 - INFO - Using Python interpreter: /home/tongna/anaconda3/envs/UIE/bin/python3.8, version: Python 3.8.13
Compiling user custom op, it will cost a few seconds.....
2022-11-04 20:11:02,355 - INFO - execute command: cd /home/tongna/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer && /home/tongna/anaconda3/envs/UIE/bin/python3.8 FasterTransformer_setup.py build
cuda_home:  None
running build
running build_ext
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/tongna/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_69031/fast && /usr/bin/make -f CMakeFiles/cmTC_69031.dir/build.make CMakeFiles/cmTC_69031.dir/build
    make[1]: 进入目录“/home/tongna/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp”
    Building CUDA object CMakeFiles/cmTC_69031.dir/main.cu.o
    /usr/bin/nvcc     -x cu -c /home/tongna/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_69031.dir/main.cu.o
    cc1plus: fatal error: cuda_runtime.h: 没有那个文件或目录
    compilation terminated.
    make[1]: *** [CMakeFiles/cmTC_69031.dir/build.make:66：CMakeFiles/cmTC_69031.dir/main.cu.o] 错误 1
    make[1]: 离开目录“/home/tongna/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp”
    make: *** [Makefile:121：cmTC_69031/fast] 错误 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:15 (project)


-- Configuring incomplete, errors occurred!
See also "/home/tongna/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
See also "/home/tongna/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
[2022-11-04 20:11:03,675] [ WARNING] - FasterTransformer is not available due to build errors.
Traceback (most recent call last):
  File "FasterTransformer_setup.py", line 4, in <module>
    setup(
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 193, in build_extensions
    ext.build_with_command(self)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 171, in build_with_command
    raise e
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 157, in build_with_command
    super(FasterTransformerExtension,
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 97, in build_with_command
    subprocess.check_call(["cmake", self.source_dir] + cmake_args,
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddlenlp/ops', '-DPY_CMD=/home/tongna/anaconda3/envs/UIE/bin/python3.8', '-DWITH_GPT=ON', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/tongna/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1148, in run_cmd
    return subprocess.check_call(
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /home/tongna/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer && /home/tongna/anaconda3/envs/UIE/bin/python3.8 FasterTransformer_setup.py build' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tongna/PythonCode/zhangxu/tmp/paddlenlp_series_summarization/export_model.py", line 159, in <module>
    do_predict(args)
  File "/home/tongna/PythonCode/zhangxu/tmp/paddlenlp_series_summarization/export_model.py", line 103, in do_predict
    pegasus = FasterPegasus(model=model,
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 159, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddlenlp/ops/faster_transformer/transformer/faster_transformer.py", line 1668, in __init__
    self.decoding = InferPegasusDecoding(
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 2997, in __init__
    load("FasterTransformer", verbose=True)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddlenlp/utils/file_lock.py", line 113, in _impl
    func(*args, **kwargs)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 310, in load
    _jit_compile(file_path, verbose)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1113, in _jit_compile
    run_cmd(compile_cmd, verbose)
  File "/home/tongna/anaconda3/envs/UIE/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1154, in run_cmd
    raise RuntimeError("Failed to run command: {}, errors: {}".format(
RuntimeError: Failed to run command: <built-in function compile>, errors: Command 'cd /home/tongna/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer && /home/tongna/anaconda3/envs/UIE/bin/python3.8 FasterTransformer_setup.py build' returned non-zero exit status 1.

Process finished with exit code 1
```
**3. 我看linux环境报错提示，cuda路径可能有问题，所以我单独进入~/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer目录下，执行命令python FasterTransformer_setup.py build，在linux报错如下：**

```
(PaddleNLP_latest) tongna@node1:~/.paddlenlp/extensions/d976e2288794ad4441b97e89a8176760/FasterTransformer$ python FasterTransformer_setup.py build
running build
running build_ext
[2022-11-04 20:32:32,003] [ WARNING] - FasterTransformer is not available because CUDA can not be found.
Traceback (most recent call last):
  File "FasterTransformer_setup.py", line 4, in <module>
    setup(
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 193, in build_extensions
    ext.build_with_command(self)
  File "/home/tongna/anaconda3/envs/PaddleNLP_latest/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 146, in build_with_command
    raise NotImplementedError
NotImplementedError
```
请帮忙查看一下问题，感谢大佬！！！

**Comment by guoshengCS** [comment]
这个应该是您上面说的cuda路径的问题，您那边nvcc是能够正常使用的吗，CUDA路径是什么呢

**Comment by gongel** [comment]
你好，windows上暂不支持export_model。Linux可以看下cuda环境：输入nvcc -V看看。方便的话也可以直接拉docker构建环境：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

**Comment by LouisHeck** [comment]
> 这个应该是您上面说的cuda路径的问题，您那边nvcc是能够正常使用的吗，CUDA路径是什么呢

1. 查看~/.bashrc文件，CUDA路径如下：
```
   # <<< conda initialize <<<
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2/lib64
  export PATH=$PATH:/usr/local/cuda-11.2/bin
  export CUDA_HOME=$CUDA_HOME:/usr/local/cuda-11.2
```
2. /usr/local目录下，有两个cuda配置变量是cuda-11.2这个。
```
    (UIE) tongna@node1:/usr/local$ ls ./ | grep cuda.*
    cuda
    cuda-11.2
```
3. 执行nvcc -V结果：
```
   (UIE) tongna@node1:~/PythonCode/zhangxu/tmp/paddlenlp_series_summarization$ nvcc -V
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2021 NVIDIA Corporation
    Built on Sun_Feb_14_21:12:58_PST_2021
    Cuda compilation tools, release 11.2, V11.2.152
    Build cuda_11.2.r11.2/compiler.29618528_0
```

**Comment by LouisHeck** [comment]
> 你好，windows上暂不支持export_model。Linux可以看下cuda环境：输入nvcc -V看看。方便的话也可以直接拉docker构建环境：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

1. nvcc 环境变量我回复上面朋友贴出来了。
2. 我执行了下gcc --version
   ```
 (UIE) tongna@node1:/usr/local$ gcc --version
  gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  Copyright (C) 2019 Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.  There is NO
  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
3. 我昨天在AIstudio试了下确实可以编译，安装FastTransformer，导出了静态模型文件和参数文件。
4. 我后面再尝试下docker版本的paddlenlp。
5. 有空再帮忙解答下，CUDA_HOME该怎么配置才好呢？能够执行用GPU执行finetune，但导出有问题。如果还需要其他系统环境信息，我再提供？感谢帮助~

**Comment by LouisHeck** [comment]
> 你好，windows上暂不支持export_model。Linux可以看下cuda环境：输入nvcc -V看看。方便的话也可以直接拉docker构建环境：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

使用paddlepaddle Docker版本环境，可以正常使用。

**Comment by baihuajun24** [comment]
> 你好，windows上暂不支持export_model。Linux可以看下cuda环境：输入nvcc -V看看。方便的话也可以直接拉docker构建环境：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

请问下现在windows可以export_model了么？我想跑这个把动态图转化成静态图，但是有CUDA没安装的报错
FastGeneration is not available because CUDA can not be found.
，但我装了CUDA
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_summarization/finetune/export_model.py
