### ISSUE TITLE
ppdiffusers微调text to image模型中的太乙模型时，下载失败，烦请核实模型路径是否错误。

### ISSUE THREAD

**Issue by kq-cheng** [PaddlePaddle/PaddleNLP#3690]
### 请提出你的问题

[2022-11-07 14:10:50,061] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1/tokenizer/vocab.json failed with code 404!
Traceback (most recent call last):
  File "/opt/conda/envs/paddlenlp/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 1559, in from_pretrained
    resolved_vocab_files[file_id] = get_path_from_url(
  File "/opt/conda/envs/paddlenlp/lib/python3.8/site-packages/paddlenlp/utils/downloader.py", line 164, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "/opt/conda/envs/paddlenlp/lib/python3.8/site-packages/paddlenlp/utils/downloader.py", line 200, in _download
    raise RuntimeError("Downloading from {} failed with code "
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1/tokenizer/vocab.json failed with code 404!

**Comment by JunnYu** [comment]
你好，请问你跑的是什么代码？这主要是因为tokenizer使用错了，太乙这个tokenizer用的是bert，bert的词表不是vocab.json而是txt。
然后建议更新一下`pip install -U ppdiffusers`

**Comment by kq-cheng** [comment]
哦哦，收到。
