### ISSUE TITLE
[Question]: 使用UIE微调按照文档执行报错。

### ISSUE THREAD

**Issue by Alone749-i** [PaddlePaddle/PaddleNLP#3700]
### 请提出你的问题

Traceback (most recent call last):
  File "finetune.py", line 287, in <module>
    main()
  File "finetune.py", line 255, in main
    if training_args.do_compress:
AttributeError: 'CompressionArguments' object has no attribute 'do_compress'

**Comment by wawltor** [comment]
UIE压缩对设备的要求比较高，可以选择跳过该步骤；

如需要进行UIE压缩，需要升级UIE Paddle到2.4rc0版本，同时安装develop版本PaddleNLP

**Comment by zhangxu33** [comment]
Traceback (most recent call last):
  File "finetune.py", line 287, in <module>
    main()
  File "finetune.py", line 255, in main
    if training_args.do_compress:
AttributeError: 'CompressionArguments' object has no attribute 'do_compress'

**Comment by zhangxu33** [comment]
我也出现这种问题，用gpu进行uie微调报错
