### ISSUE TITLE
[Question]: 使用paddlenlp的一键预测能力 Taskflow API报错 mkdir failed!

### ISSUE THREAD

**Issue by xmweijh** [PaddlePaddle/PaddleNLP#3709]
## 问题描述

使用Taskflow API报错

## 允许代码如下
```python
from paddlenlp import Taskflow

tag = Taskflow("pos_tagging")
```

## 报错内容
```
Traceback (most recent call last):
  File "D:/机器学习/paddlenlp/test.py", line 3, in <module>
    tag = Taskflow("pos_tagging")
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 572, in __init__
    **self.kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddlenlp\taskflow\pos_tagging.py", line 53, in __init__
    super().__init__(task=task, model=model, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddlenlp\taskflow\lexical_analysis.py", line 121, in __init__
    self._get_inference_model()
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddlenlp\taskflow\task.py", line 247, in _get_inference_model
    self._convert_dygraph_to_static()
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddlenlp\taskflow\task.py", line 268, in _convert_dygraph_to_static
    paddle.jit.save(static_model, save_path)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\jit.py", line 631, in wrapper
    func(layer, path, input_spec, **configs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\jit.py", line 993, in save
    clip_extra=configs.clip_extra)
  File "D:\anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 443, in __impl__
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 1460, in save_inference_model
    save_persistables(executor, save_dirname, main_program, params_filename)
  File "D:\anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 425, in __impl__
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 737, in save_persistables
    filename=filename)
  File "D:\anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 425, in __impl__
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 376, in save_vars
    filename=filename)
  File "D:\anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 425, in __impl__
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 431, in save_vars
    executor.run(save_program)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1299, in run
    six.reraise(*sys.exc_info())
  File "D:\anaconda3\envs\paddle\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1295, in run
    return_merged=return_merged)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1464, in _run_impl
    return new_exe.run(list(feed.keys()), fetch_list, return_numpy)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 547, in run
    tensors = self._new_exe.run(feed_names, fetch_list)._move_to_list()
RuntimeError: C:\Users\*** mkdir failed!
```

**Comment by wawltor** [comment]
麻烦提供一下Paddle和PaddleNLP的版本

**Comment by xmweijh** [comment]
paddlenlp                 2.4.2                    pypi_0 
paddlepaddle-gpu          2.3.2           py37_gpu_cuda11.2_windows

**Comment by wawltor** [comment]
> paddlenlp 2.4.2 pypi_0 paddlepaddle-gpu 2.3.2 py37_gpu_cuda11.2_windows

麻烦再尝试一下其他Taskflow的任务是否有问题，还是单独pos_tagging有问题

**Comment by xmweijh** [comment]
测试了其他的任务，全都是报的这个错误。会不会因为是系统用户名是中文啊？

**Comment by wawltor** [comment]
可以尝试设置一下home_path，这样可以改成英文目录试试，如果不行的话 可以加一下我们的微信群 我们帮忙排查一下
 tag = Taskflow("pos_tagging", home_path="xxxx")

**Comment by xmweijh** [comment]
好了。感谢！ 居然真的是中文用户名的原因，win11害人TAT

**Comment by wawltor** [comment]
> 好了。感谢！ 居然真的是中文用户名的原因，win11害人TAT

嗯嗯 解决就好
