### ISSUE TITLE
[Question]: text_summarization下载模型报错

### ISSUE THREAD

**Issue by QQR1** [PaddlePaddle/PaddleNLP#3740]
### 请提出你的问题

`from pprint import pprint
from paddlenlp import Taskflow

sum = Taskflow('text_summarization')
pprint(sum("飞桨自然语言处理核心开发库，拥有覆盖多场景的模型库、简洁易用的全流程API与动静统一的高性能分布式训练能力，旨在为飞桨开发者提升文本领域建模效率，并提供基于PaddlePaddle 2.0的NLP领域最佳实践。"))
`
[2022-11-11 23:14:22,241] [    INFO] - Downloading tokenizer_config.json from https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese\tokenizer_config.json
[2022-11-11 23:14:22,425] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese\tokenizer_config.json failed with code 404!
Traceback (most recent call last):
  File "E:\Users\renqi\anaconda3\envs\paddle\lib\site-packages\paddlenlp\transformers\auto\tokenizer.py", line 289, in from_pretrained
    resolved_vocab_file = get_path_from_url(community_config_path,
  File "E:\Users\renqi\anaconda3\envs\paddle\lib\site-packages\paddlenlp\utils\downloader.py", line 164, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "E:\Users\renqi\anaconda3\envs\paddle\lib\site-packages\paddlenlp\utils\downloader.py", line 200, in _download
    raise RuntimeError("Downloading from {} failed with code "
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community/IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese\tokenizer_config.json failed with code 404!

During handling of the above exception, another exception occurred:

**Comment by wawltor** [comment]
这个建议使用最新develop版本下载，目前这个问题已经在develop版本修复
