### ISSUE TITLE
[Question]: run the ppdiffusers/example/dreambooth issue

### ISSUE THREAD

**Issue by godlockin** [PaddlePaddle/PaddleNLP#3768]
### 请提出你的问题

env: aistudio
issue: command line param can't be load in script, 命令行参数没法被程序加载
question: how to run dreambooth to fine tuning the model
```bash
aistudio@jupyter-2437222-5014788:~/PaddleNLP/ppdiffusers/examples/dreambooth$ bash run_single.sh 
Traceback (most recent call last):
  File "train_dreambooth.py", line 703, in <module>
    args = parse_args()
TypeError: parse_args() missing 1 required positional argument: 'input_args'
```

[invoke code link](https://github.com/PaddlePaddle/PaddleNLP/blob/010fcd87e7510b1f1987ba9c3aff604d88d489c5/ppdiffusers/examples/dreambooth/train_dreambooth.py#L703)
[method code link](https://github.com/PaddlePaddle/PaddleNLP/blob/010fcd87e7510b1f1987ba9c3aff604d88d489c5/ppdiffusers/examples/dreambooth/train_dreambooth.py#L42)
[method code link2](https://github.com/PaddlePaddle/PaddleNLP/blob/010fcd87e7510b1f1987ba9c3aff604d88d489c5/ppdiffusers/examples/dreambooth/train_dreambooth.py#L235)

```python
if __name__ == "__main__":
    args = parse_args()
    main(args)
```

processes：
1. git clone paddleNlp
```bash
aistudio@jupyter-2437222-5014788:~$ git clone xxx
aistudio@jupyter-2437222-5014788:~$ ls -ltr /home/aistudio/
总用量 16389
drwxr-xr-x 149 aistudio aistudio     4096 11月 11 17:47 external-libraries
-rw-r--r--   1 aistudio aistudio 16632529 11月 14 16:04 wukong_test.csv
-rw-r--r--   1 aistudio aistudio     2989 11月 14 17:12 download_source_images.ipynb
-rwxr-xr-x   1 aistudio aistudio      511 11月 15 11:14 run_single.sh
-rw-r--r--   1 aistudio aistudio      543 11月 15 11:34 test.py
drwxr-xr-x   1 aistudio aistudio     4096 11月 15 13:47 PaddleNLP
-rw-r--r--   1 aistudio aistudio    29493 11月 15 14:14 train_dreambooth.py
drwxr-xr-x  10 aistudio aistudio     4096 11月 15 16:15 Dreambooth-Stable-Diffusion
drwxrwxrwx   2 aistudio aistudio     4096 11月 15 17:07 data
drwxr-xr-x   1 aistudio aistudio     4096 11月 15 18:18 work
-rw-r--r--   1 aistudio aistudio    93945 11月 15 18:18 main.ipynb
```

2. prepare train dataset
 
3. modify `run_single.sh`
```bash
aistudio@jupyter-2437222-5014788:~/PaddleNLP/ppdiffusers/examples/dreambooth$ cat run_single.sh 
#export MODEL_NAME="CompVis/stable-diffusion-v1-4"
#export INSTANCE_DIR="./dream_image"
#export OUTPUT_DIR="./dream_outputs"

export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export INSTANCE_DIR="~/data/images"
export OUTPUT_DIR="~/data/output"

python -u train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks billy" \
  --height=512 \
  --width=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=400
```

4. run the script & get the issue
```bash
aistudio@jupyter-2437222-5014788:~/PaddleNLP/ppdiffusers/examples/dreambooth$ bash run_single.sh 
Traceback (most recent call last):
  File "train_dreambooth.py", line 703, in <module>
    args = parse_args()
TypeError: parse_args() missing 1 required positional argument: 'input_args'
```

**Comment by JunnYu** [comment]
@godlockin  感谢指出，我将立刻修复！
你可以先这样使用一下，改一下代码`def parse_args(input_args=None):` 
或者这样
```python
if __name__ == "__main__":
    args = parse_args(None)
    main(args)
```

**Comment by godlockin** [comment]
> @godlockin 感谢指出，我将立刻修复！ 你可以先这样使用一下，改一下代码`def parse_args(input_args=None):` 或者这样
> 
> ```python
> if __name__ == "__main__":
>     args = parse_args(None)
>     main(args)
> ```

cheers~ but new issue happens, seems like some object (maybe namespace) not be initialized successfully. 新的报错出现了，似乎有些东西没初始化成功，可能是 namespace?



1. do env prepare
```bash
aistudio@jupyter-2437222-5014788:~/PaddleNLP/ppdiffusers/examples/dreambooth$ pip install --upgrade ppdiffusers
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
....
Successfully installed ftfy-6.1.1 paddlefsl-1.1.0 paddlenlp-2.4.2 ppdiffusers-0.6.2 regex-2022.10.31 wcwidth-0.2.5

[notice] A new release of pip available: 22.1.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
```

2. modify the code
```python
if __name__ == "__main__":
    args = parse_args(None)
    main(args)
```

3. run the job
```bash
aistudio@jupyter-2437222-5014788:~/PaddleNLP/ppdiffusers/examples/dreambooth$ bash run_single.sh 
[2022-11-16 21:54:43,338] [    INFO] - Downloading tokenizer_config.json from https://bj.bcebos.com/paddlenlp/models/community/runwayml/stable-diffusion-v1-5/tokenizer/tokenizer_config.json
...
Traceback (most recent call last):
  File "train_dreambooth.py", line 704, in <module>
    main(args)
  File "train_dreambooth.py", line 431, in main
    os.path.join(args.pretrained_model_name_or_path, "text_encoder"))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/auto/modeling.py", line 407, in from_pretrained
    *model_args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/auto/modeling.py", line 331, in _from_pretrained
    pretrained_model_name_or_path, *model_args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 333, in from_pretrained
    base_args = base_arg.pop("init_args", ())
AttributeError: 'NoneType' object has no attribute 'pop'
```

**Comment by JunnYu** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/7a4355c467d3c4f5c1c0bd4407619e64feb37b3c/ppdiffusers/examples/dreambooth/train_dreambooth.py#L430-L431
可以先这么改一下！这是另一个问题导致的
```python
from paddlenlp.transformers import CLIPTextModel
text_encoder = CLIPTextModel.from_pretrained( 
     os.path.join(args.pretrained_model_name_or_path, "text_encoder")) 
```

**Comment by JunnYu** [comment]
你好，现在这里的代码已经修复了！

**Comment by godlockin** [comment]
响应真快，感谢
