### ISSUE TITLE
[Question]: ernie-layout 推理部署

### ISSUE THREAD

**Issue by shawn-AI-Tech** [PaddlePaddle/PaddleNLP#3773]
### 请提出你的问题

目前我正在进行文档视觉问答任务，已经用taskflow进行了推理，但速度过慢，想要使用自行部署来推理。

目前的问题是找不到可以用 PaddleNLP/model_zoo/ernie-layout/deploy/python/infer.py  加载的 ernie-layoutx模型。

PaddleNLP/model_zoo/ernie-layout/deploy/python/README_ch.md中没有说应该在哪里下载模型，只有提供了taskflow的使用方式和测试图片的下载地址。

**Comment by linjieccc** [comment]
Hi, @zhang0227 

deploy/python/infer.py加载的模型是通过微调+静态图导出得到的，具体分为以下步骤

1）基于DocVQA-ZH数据集微调模型
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/README_ch.md#42-%E6%96%87%E6%A1%A3%E8%A7%86%E8%A7%89%E9%97%AE%E7%AD%94%E4%BB%BB%E5%8A%A1
2）微调后的模型导出为静态图参数
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/README_ch.md#51-%E9%9D%99%E6%80%81%E5%9B%BE%E5%AF%BC%E5%87%BA

得到静态图模型后可用deploy/python/infer.py执行推理

**Comment by shawn-AI-Tech** [comment]
你好 @linjieccc 
我想知道这个微调后的模型应该是和taskflow中的模型效果会有较大区别吗？
由于机器性能原因训练需要很长时间，我想问是否有其他方式去使用直接提供的预训练模型进行推理

**Comment by linjieccc** [comment]
效果上会有一些区别，DocPrompt训练用到的VQA数据更多些且模型尺寸更大。
请问下你的设备环境是？可以试试把batch_size调大些，DocPrompt是prompt并行推理的

**Comment by NaivePawn** [comment]
您好！能将DocPrompt的模型转成可用deploy/python/infer.py执行推理的模型吗

**Comment by wickai** [comment]
您好~  我同样在使用ernie-layoutx的deploy/python/infer.py脚本推理模型，我想测试一下ner预测自己的图片，我使用了taskflow自动下载的模型，大约2g左右，启动脚本如下
```shell
python infer.py \
    --model_path_prefix static/inference \
    --task_type ner \
    --lang "ch" \
    --batch_size 8
```
会报错
```
Traceback (most recent call last):
  File "infer.py", line 70, in <module>
    main()
  File "infer.py", line 63, in main
    outputs = predictor.predict(docs)
  File "/home/weikai/workspace/github/PaddleNLP/model_zoo/ernie-layout/deploy/python/predictor.py", line 879, in predict
    output = self.infer(input_dict)
  File "/home/weikai/workspace/github/PaddleNLP/model_zoo/ernie-layout/deploy/python/predictor.py", line 855, in infer
    return self.inference_backend.infer(data)
  File "/home/weikai/workspace/github/PaddleNLP/model_zoo/ernie-layout/deploy/python/predictor.py", line 66, in infer
    self.predictor.run()
ValueError: In user code:

    File "models/save_infermodel.py", line 32, in <module>
      phase="infer")
    File "./src/multi_task_models/extract_model.py", line 154, in create_model
      body_feats_feature = model.net(image)
    File "./src/model/image_model/resnet.py", line 69, in net
      data_format=data_format)
    File "./src/model/image_model/resnet.py", line 145, in conv_bn_layer
      data_format=data_format)
    File "/home/work/zhangdan20/opensource/DocPrompt/py37/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1714, in conv2d
      "data_format": data_format,
    File "/home/work/zhangdan20/opensource/DocPrompt/py37/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/work/zhangdan20/opensource/DocPrompt/py37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3582, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/work/zhangdan20/opensource/DocPrompt/py37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2596, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: input and filter data type should be consistent, but received input data type is int64_t and filter type is float
      [Hint: Expected input_data_type == filter_data_type, but received input_data_type:3 != filter_data_type:5.] (at /paddle/paddle/fluid/operators/conv_op.cc:209)
      [operator < conv2d > error]
```
不知道哪里出错了
环境：
```
paddle2onnx==1.0.3
paddlefsl==1.1.0
paddlenlp==2.4.1.dev0
paddleocr==2.6.1.0
paddlepaddle-gpu @ file:///package/paddlepaddle_gpu-2.3.2.post116-cp38-cp38-linux_x86_64.whl
```

**Comment by wickai** [comment]
@linjieccc

**Comment by xinsheng44** [comment]
> 

老哥解决了吗，我也是这个问题
