### ISSUE TITLE
[Question]: memory leak during model fine-tuning in aistudio

### ISSUE THREAD

**Issue by godlockin** [PaddlePaddle/PaddleNLP#3834]
### 请提出你的问题

env: aistudio
lab: paddlenlp ppdiffusers
processes:
1. prepare some images
```bash
aistudio@jupyter-2437222-5014788:~/PaddleNLP/ppdiffusers/examples/dreambooth$ ls -ltr ~/work/billyImages
总用量 89700
-rw-r--r-- 1 aistudio aistudio 156725 11月 18 17:44 PE867584.jpg
-rw-r--r-- 1 aistudio aistudio 187953 11月 18 17:44 PE867823.jpg
-rw-r--r-- 1 aistudio aistudio 128939 11月 18 17:44 PH169462.jpg
...

aistudio@jupyter-2437222-5014788:~/PaddleNLP/ppdiffusers/examples/dreambooth$ du -kh ~/work/billyImages
1.3M    /home/aistudio/work/billyImages/.ipynb_checkpoints
89M     /home/aistudio/work/billyImages

aistudio@jupyter-2437222-5014788:~/PaddleNLP/ppdiffusers/examples/dreambooth$ ls -ltr ~/work/billyImages | wc -l
535
```
2. modify the training script and do training
```bash
aistudio@jupyter-2437222-5014788:~/PaddleNLP/ppdiffusers/examples/dreambooth$ cat run_single.sh 

export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export INSTANCE_DIR="/home/aistudio/work/billyImages"
export OUTPUT_DIR="/home/aistudio/data/output"

python -u train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks billy wardrobe" \
  --height=512 \
  --width=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=400
```

3. the 1st time we do training it works, but if we do the 2nd training or images prompt generation, OOM exception happens (without memory release)
```bash
aistudio@jupyter-2437222-5014788:~/PaddleNLP/ppdiffusers/examples/dreambooth$ bash run_single.sh 
[2022-11-21 13:10:28,062] [    INFO] - Found /home/aistudio/.paddlenlp/models/runwayml/stable-diffusion-v1-5/tokenizer/tokenizer_config.json
[2022-11-21 13:10:28,063] [    INFO] - We are using <class 'paddlenlp.transformers.clip.tokenizer.CLIPTokenizer'> to load 'runwayml/stable-diffusion-v1-5/tokenizer'.
[2022-11-21 13:10:28,063] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/runwayml/stable-diffusion-v1-5/tokenizer/vocab.json
[2022-11-21 13:10:28,063] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/runwayml/stable-diffusion-v1-5/tokenizer/merges.txt
[2022-11-21 13:10:28,063] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/runwayml/stable-diffusion-v1-5/tokenizer/added_tokens.json
[2022-11-21 13:10:28,063] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/runwayml/stable-diffusion-v1-5/tokenizer/special_tokens_map.json
[2022-11-21 13:10:28,063] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/runwayml/stable-diffusion-v1-5/tokenizer/tokenizer_config.json
[2022-11-21 13:10:28,167] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/runwayml/stable-diffusion-v1-5/text_encoder/model_state.pdparams
[2022-11-21 13:10:28,167] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/runwayml/stable-diffusion-v1-5/text_encoder/model_config.json
W1121 13:10:28.169200  2721 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W1121 13:10:28.173153  2721 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "train_dreambooth.py", line 708, in <module>
    main(args)
  File "train_dreambooth.py", line 435, in main
    os.path.join(args.pretrained_model_name_or_path, "text_encoder"))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 492, in from_pretrained
    model = cls(*base_args, **base_kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/clip/modeling.py", line 1119, in __init__
    normalize_before=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/clip/modeling.py", line 640, in __init__
    act_dropout=0)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/transformer.py", line 537, in __init__
    bias_attr=bias_attrs[0])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/transformer.py", line 183, in __init__
    bias_attr=bias_attr)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 161, in __init__
    is_bias=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 447, in create_parameter
    default_initializer)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 379, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3778, in create_parameter
    initializer(param, self)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 56, in __call__
    return self.forward(param, block)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 616, in forward
    _current_expected_place())
OSError: (External) CUDA error(2), out of memory. 
  [Hint: Please search for the error code(2) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/core/cuda_stream.h:73)
```

**Comment by godlockin** [comment]
i've tried close the alive tab (include jupyter and terminal), restart kernel .etc but nothing works but stop and start the project again

**Comment by JunnYu** [comment]
你可以注释这两行代码，我总感觉这个释放GPU显存的代码不太对劲，在aistudio上有时候可以用，有时候就一直出错
https://github.com/PaddlePaddle/PaddleNLP/blob/19c4ca3110991b814c2d40ce3a5ae79328114e0d/ppdiffusers/examples/dreambooth/train_dreambooth.py#L416-L417

**Comment by godlockin** [comment]
update the [train_dreambooth.py] and do the same change on the code in my testing env, we will see what happens then

**Comment by godlockin** [comment]
> 你可以注释这两行代码，我总感觉这个释放GPU显存的代码不太对劲，在aistudio上有时候可以用，有时候就一直出错
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/19c4ca3110991b814c2d40ce3a5ae79328114e0d/ppdiffusers/examples/dreambooth/train_dreambooth.py#L416-L417

注释掉了也不行哦，依然溢出…目前没啥好解法，只有整个项目重启一条路吗

**Comment by godlockin** [comment]
reproduce process:
1. fine tuning model by any function in terminal
2. load & do image generation in jupyter workspace
3. do some changes and fine tuning model again
4. oom exception raises
