### ISSUE TITLE
[Bug]: AttributeError: 'BertConfig' object has no attribute 'get'

### ISSUE THREAD

**Issue by Yam0214** [PaddlePaddle/PaddleNLP#3844]
### 软件环境

```Markdown
- paddlepaddle: 2.3.2
- paddlepaddle-gpu: 2.3.2
- paddlenlp: 2.4.0.dev
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
当使用`config.get()`时报错`'BertConfig' object has no attribute 'get'`
```

### 稳定复现步骤 & 代码

```bash
$ python
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from paddlenlp.transformers import BertConfig
>>> config = BertConfig()
>>> config.get("hidden_size")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/oyhy/Yam0214/PaddleNLP/paddlenlp/transformers/configuration_utils.py", line 419, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'BertConfig' object has no attribute 'get'
>>> 
```

**Comment by wj-Mcat** [comment]
you can get `hidden_size` attribute with the following code:

```python
config.hidden_size

# or 
config['hidden_size']
```

**Comment by FrostML** [comment]
出于兼容考虑，可以补充下这个方法
