### ISSUE TITLE
[Bug]: centos7 python3.6.8 安装paddlenlp 2.3.5之后所有版本报错

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleNLP#3845]
### 软件环境

```Markdown
- paddlenlp: paddlenlp 2.3.7及以后版本都报错
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9d/2d/233c79d5b4e5ab1dbf111242299153f3caddddbb691219f363ad55ce783d/seqeval-1.2.2.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 221kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-aglcx40k/seqeval/setup.py", line 56, in <module>
        'Programming Language :: Python :: Implementation :: PyPy'
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib64/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
        return self.resolve()
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pip-build-aglcx40k/seqeval/.eggs/setuptools_scm-7.0.5-py3.6.egg/setuptools_scm/__init__.py", line 5
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aglcx40k/seqeval/
```

### 稳定复现步骤 & 代码

pip3 install paddlenlp==2.3.7  -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by wawltor** [comment]
需要升级python的版本到3.7+

**Comment by yangy996** [comment]
> 需要升级python的版本到3.7+

官方文档，写的是>=3.6
![image](https://user-images.githubusercontent.com/15188456/203024978-4a62d631-e34b-40dd-ae27-8efcfb6083a3.png)

**Comment by w5688414** [comment]
Hi, @yangy996 Please refer to this link. https://blog.csdn.net/Ajdidfj/article/details/122889534

**Comment by wawltor** [comment]
抱歉，我们修改一下版本依赖，底层的版本依赖发生了一些变化。
