### ISSUE TITLE
[Question]: Pipeline中语义检索服务启动报错

### ISSUE THREAD

**Issue by riddle911** [PaddlePaddle/PaddleNLP#3883]
### 请提出你的问题

pipeline中语义检索示例运行报错。
运行python rest_api/application.py 8891后，报错：

```query_qa_pairs
11/23/2022 11:12:07 PM YAML version (1.1.0) does not match with pipelines version (0.1.0a0). Issues may occur during loading. To fix this warning, save again this pipeline with the current pipelines version using Pipeline.save_to_yaml(), or downgrade to pipelines version 0.1.0a0.
Traceback (most recent call last):
  File "C:\Users\riddle\code\PaddleNLP\pipelines\rest_api\application.py", line 35, in <module>
    from rest_api.controller.router import router as api_router
  File ".\rest_api\controller\router.py", line 17, in <module>
    from rest_api.controller import file_upload, search, feedback, document
  File ".\rest_api\controller\search.py", line 45, in <module>
    QA_PAIR_PIPELINE = Pipeline.load_from_yaml(Path(PIPELINE_YAML_PATH),
  File "C:\ProgramData\Miniconda3\envs\pipl\lib\site-packages\paddle_pipelines-0.1.0a0-py3.9.egg\pipelines\pipelines\base.py", line 274, in load_from_yaml
    return cls.load_from_config(
  File "C:\ProgramData\Miniconda3\envs\pipl\lib\site-packages\paddle_pipelines-0.1.0a0-py3.9.egg\pipelines\pipelines\base.py", line 820, in load_from_config
    pipeline_definition = get_pipeline_definition(
  File "C:\ProgramData\Miniconda3\envs\pipl\lib\site-packages\paddle_pipelines-0.1.0a0-py3.9.egg\pipelines\pipelines\config.py", line 51, in get_pipeline_definition
    raise KeyError(
KeyError: "Cannot find any pipeline with name 'query_qa_pairs' declared in the YAML file."
```

环境：
Windows10
CPU版本
paddle：2.3.2
python：3.9.1

**Comment by w5688414** [comment]
please refer to this pr. https://github.com/PaddlePaddle/PaddleNLP/pull/3864

https://github.com/PaddlePaddle/PaddleNLP/pull/3864/files#diff-94255faa97c19cf211aebf24ee69352dbf3a9c2e85add003baefacaacfa00546

Add try exceptions:

```
try:
    QA_PAIR_PIPELINE = Pipeline.load_from_yaml(
        Path(PIPELINE_YAML_PATH), pipeline_name=QUERY_QA_PAIRS_NAME)
except Exception as e:
    logger.warning(f"Request pipeline ('{QUERY_QA_PAIRS_NAME}: is null'). ")
```
