### ISSUE TITLE
[Bug]: ERNIE-Doc运行语义匹配任务时adamw报错

### ISSUE THREAD

**Issue by chenqianhe** [PaddlePaddle/PaddleNLP#3894]
### 软件环境

```Markdown
- paddle-bfloat                  0.1.7
- paddle2onnx                    1.0.0
- paddlefsl                      1.1.0
- paddlehub                      2.3.0
- paddlenlp                      2.2.6
- paddlepaddle-gpu               2.4.0rc0.post112
- tb-paddle                      0.3.6
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "run_semantic_matching.py", line 369, in <module>
    do_train(args)
  File "run_semantic_matching.py", line 316, in do_train
    optimizer.step()
  File "<decorator-gen-294>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 300, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-292>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 509, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 580, in step
    params_grads=params_grads)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 1015, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 813, in _create_optimization_pass
    param_and_grad)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 451, in _append_optimize_op
    find_master, False)
ValueError: (InvalidArgument) adamw_(): argument (position 13) must be double, but got NoneType (at /paddle/paddle/fluid/pybind/op_function_common.cc:211)
```
```


### 稳定复现步骤 & 代码

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-doc/README.md

```
python run_semantic_matching.py  --batch_size 6 --learning_rate 2e-5
```

paddlenlp 2.2.6版本需要修改layerwise_lr_decay引入为：
```
from paddlenlp.ops.optimizer.adamwdl import layerwise_lr_decay
```

**Comment by chenqianhe** [comment]
@lugimzzz 能帮忙看看问题在哪里嘛

**Comment by lugimzzz** [comment]
> 

好的，我稍晚看一下这个问题

**Comment by chenqianhe** [comment]
> > 
> 
> 好的，我稍晚看一下这个问题

您好，请问有定位到是什么问题吗

**Comment by lugimzzz** [comment]
建议使用最新版本paddlenlp，就没有这个问题。在版本2.2.6确实会出现这个问题，应该是adamw版本之前的不同。

**Comment by chenqianhe** [comment]
升级后成功跑通
