### ISSUE TITLE
[Bug]: GPT导出模型后，推理报错

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/PaddleNLP#3908]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.2.0~2.4.0均出现
- paddlenlp: develop
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "deploy/python/inference.py", line 129, in <module>
    main()
  File "deploy/python/inference.py", line 121, in main
    outs = predictor.predict(dataset)
  File "deploy/python/inference.py", line 89, in predict
    output = self.predict_batch(data)
  File "deploy/python/inference.py", line 80, in predict_batch
    self.predictor.run()
RuntimeError: In user code:

    File "export_model.py", line 84, in <module>
      main()
    File "export_model.py", line 78, in main
      paddle.jit.save(model, args.output_path)
    File "<decorator-gen-123>", line 2, in save
      
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 649, in wrapper
      func(layer, path, input_spec, **configs)
    File "<decorator-gen-122>", line 2, in save
      
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
      return func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 928, in save
      inner_input_spec, with_hook=with_hook)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in concrete_program_specify_input_spec
      is_train=self._is_train_mode())
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 485, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 955, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 944, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-119>", line 2, in from_func_spec
      
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
      return func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 888, in from_func_spec
      outputs = static_func(*inputs)
    File "/home/aistudio/PaddleNLP/paddlenlp/transformers/gpt/modeling.py", line 1050, in forward
      output, cached_kvs = self.model(input_ids, use_cache=True, cache=None)
    File "/home/aistudio/PaddleNLP/paddlenlp/transformers/gpt/modeling.py", line 1021, in model
      outputs = self.gpt(input_ids,
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 950, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 935, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/aistudio/PaddleNLP/paddlenlp/transformers/gpt/modeling.py", line 813, in forward
      if position_ids is None:
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 324, in convert_ifelse
      return_name_ids)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 380, in _run_py_ifelse
      py_outs = true_fn() if pred else false_fn()
    File "/home/aistudio/PaddleNLP/paddlenlp/transformers/gpt/modeling.py", line 823, in forward
      position_ids = paddle.expand_as(position_ids, input_ids)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 3270, in expand_as
      outputs={'Out': out},
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4023, in append_op
      attrs=kwargs.get("attrs", None),
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2858, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:111)
      [operator < expand_as_v2 > error]
```
```


### 稳定复现步骤 & 代码

导出的时候没有问题。

```sh
python export_model.py --model_type=gpt \
    --model_path=gpt2-medium-en \
    --output_path=./infer_model/model
```

推理的时候，报了上面的错误。

```sh
python deploy/python/inference.py --model_type gpt \
    --model_path ./infer_model/model
```

**Comment by ZHUI** [comment]
你好
1. 对目前发版的paddle，可以尝试 https://github.com/PaddlePaddle/PaddleNLP/pull/3884/files 切换回，原来的expand_as, 对于低版本的paddle
2. 使用最新的 develop ，这个pr修复了问题，https://github.com/PaddlePaddle/Paddle/pull/48336
