### ISSUE TITLE
rvl_cdip_sampled数据集没有找到

### ISSUE THREAD

**Issue by yysirs** [PaddlePaddle/PaddleNLP#3923]
### 问题描述

基于ernie-layout进行rvl_cdip_sampled分类任务，下载rvl_cdip_sampled失败
```
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/2.4.0/datasets/rvl_cdip_sampled/rvl_cdip_sampled.py (ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))))
```
huggingface上面也没有找到相应的数据集
![image](https://user-images.githubusercontent.com/43271630/204179624-96031365-a937-424e-a6b9-503c685607ae.png)

**Comment by LemonNoel** [comment]
这里实现可能有点问题，可以先将文件中 `from datasets import load_dataset` 替换为 `from paddlenlp.datasets import load_dataset` 读取数据，晚点我们修复一下。

**Comment by yysirs** [comment]
> 这里实现可能有点问题，可以先将文件中 `from datasets import load_dataset` 替换为 `from paddlenlp.datasets import load_dataset` 读取数据，晚点我们修复一下。
修改完之后，
```
ModuleNotFoundError: No module named 'paddlenlp.datasets.rvl_cdip_sampled'
```

**Comment by LemonNoel** [comment]
分类任务的话，文件中[这一行](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/run_cls.py#L26)前边加上一行`import paddlenlp`，`rvl_cdip_sampled`是数据集名，并不是方法。

**Comment by yysirs** [comment]
> 分类任务的话，文件中[这一行](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/run_cls.py#L26)前边加上一行`import paddlenlp`，`rvl_cdip_sampled`是数据集名，并不是方法。
已经增加了
![image](https://user-images.githubusercontent.com/43271630/204210072-0653f791-a093-4c49-845f-c0ac826a3c9e.png)
但是报错了，刚才没有贴出来完整的错误信息
```
Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 198, in load_dataset
    reader_cls = import_main_class(path_or_read_func)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 97, in import_main_class
    module = importlib.import_module(module_path)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'paddlenlp.datasets.rvl_cdip_sampled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_cls.py", line 223, in <module>
    main()
  File "run_cls.py", line 62, in main
    data_args.dataset_name, split=["train", "validation", "test"])
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 201, in load_dataset
    path_or_read_func, name=name, splits=splits, **kwargs)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 117, in load_from_hf
    hf_datasets = load_hf_dataset(path, name=name, split=splits, **kwargs)
KeyError: 'split'
```

**Comment by yysirs** [comment]
> 
好的，刚才那个报错信息没有贴完整，已经解决了

**Comment by yysirs** [comment]
> 分类任务的话，文件中[这一行](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/run_cls.py#L26)前边加上一行`import paddlenlp`，`rvl_cdip_sampled`是数据集名，并不是方法。

代码修改成
![image](https://user-images.githubusercontent.com/43271630/204213113-02aeda87-a872-4b22-b6a1-86c64be27ff7.png)
但是还是报错找不到
```
Traceback (most recent call last):
  File "run_cls.py", line 223, in <module>
    main()
  File "run_cls.py", line 62, in main
    data_args.dataset_name, splits=["train", "validation", "test"])
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 201, in load_dataset
    path_or_read_func, name=name, splits=splits, **kwargs)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 117, in load_from_hf
    hf_datasets = load_hf_dataset(path, name=name, split=splits, **kwargs)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 58, in load_from_ppnlp
    return origin_load_dataset(path, *args, **kwargs)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/datasets/load.py", line 1734, in load_dataset
    **config_kwargs,
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/datasets/load.py", line 1506, in load_dataset_builder
    data_files=data_files,
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/datasets/load.py", line 1247, in dataset_module_factory
    raise e1 from None
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/datasets/load.py", line 1182, in dataset_module_factory
    dynamic_modules_path=dynamic_modules_path,
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/datasets/load.py", line 475, in get_module
    local_path = self.download_loading_script(revision)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/datasets/load.py", line 455, in download_loading_script
    return cached_path(file_path, download_config=download_config)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 197, in cached_path
    download_desc=download_config.download_desc,
  File "/home/ps/anaconda3/envs/paddle/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 533, in get_from_cache
    raise ConnectionError(f"Couldn't reach {url} ({repr(head_error)})")
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/2.4.0/datasets/rvl_cdip_sampled/rvl_cdip_sampled.py (ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))))
```

**Comment by LemonNoel** [comment]
检查下paddlenlp是不是最新版本，然后再测下之前说的两种方法：
第一种，把[原来导入的这行](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/run_cls.py#L26)改为
```
from paddlenlp.datasets import load_dataset
from datasets import load_metric
```
第二种，在[原来导入load_dataset](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/run_cls.py#L26)前加上`import paddlenlp`，也就是
```
import paddlenlp
from datasets import load_dataset, load_metric
```

**Comment by yysirs** [comment]
> 检查下paddlenlp是不是最新版本，然后再测下之前说的两种方法： 第一种，把[原来导入的这行](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/run_cls.py#L26)改为
> 
> ```
> from paddlenlp.datasets import load_dataset
> from datasets import load_metric
> ```
> 
> 第二种，在[原来导入load_dataset](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/run_cls.py#L26)前加上`import paddlenlp`，也就是
> 
> ```
> import paddlenlp
> from datasets import load_dataset, load_metric
> ```

升级了2.4.3版本，可以了
