### ISSUE TITLE
[Bug]:下载预训练模型时报错404

### ISSUE THREAD

**Issue by zcg-joker** [PaddlePaddle/PaddleNLP#3926]
### 软件环境

```Markdown
- paddlepaddle: 2.4.0rc0
- paddlepaddle-gpu:  /
- paddlenlp:  2.4.3
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
加载refomer预训练语言模型时，下载报错。
报错如下：
[2022-11-27 18:23:00,098] [    INFO] - We are using <class 'paddlenlp.transformers.roformer.tokenizer.RoFormerTokenizer'> to load 'roformer-chinese-base'.
[2022-11-27 18:23:00,098] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/transformers/roformer/roformer-chinese-base/vocab.txt and saved to /home/aistudio/.paddlenlp/models/roformer-chinese-base
[2022-11-27 18:23:00,099] [    INFO] - Downloading vocab.txt from https://bj.bcebos.com/paddlenlp/models/transformers/roformer/roformer-chinese-base/vocab.txt
100%|████████████████████████████████████████| 365k/365k [00:00<00:00, 28.9MB/s]
[2022-11-27 18:23:00,270] [    INFO] - tokenizer config file saved in /home/aistudio/.paddlenlp/models/roformer-chinese-base/tokenizer_config.json
[2022-11-27 18:23:00,270] [    INFO] - Special tokens file saved in /home/aistudio/.paddlenlp/models/roformer-chinese-base/special_tokens_map.json
[2022-11-27 18:23:00,271] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community//roformer-chinese-base/model_state.pdparams and saved to /home/aistudio/.paddlenlp/models/roformer-chinese-base
[2022-11-27 18:23:00,309] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/community//roformer-chinese-base/model_state.pdparams failed with code 404!
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 428, in from_pretrained
    file_path, default_root)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/utils/download.py", line 159, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum, method=method)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/utils/download.py", line 262, in _download
    if not _download_methods[method](url, fullname):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/utils/download.py", line 184, in _get_download
    "{}!".format(url, req.status_code))
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community//roformer-chinese-base/model_state.pdparams failed with code 404!
```

### 稳定复现步骤 & 代码

from paddlenlp.transformers import AutoTokenizer
from model import UIE

tokenizer = AutoTokenizer.from_pretrained("roformer-chinese-base")
model = UIE.from_pretrained("roformer-chinese-base")

**Comment by wawltor** [comment]
```python
from paddlenlp.transformers import AutoMode
AutoModel.from_pretrained('roformer-chinese-base')
```
不是从UIE model 来from_pretrained
