### ISSUE TITLE
please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:549)

### ISSUE THREAD

**Issue by liuliuNLP** [PaddlePaddle/PaddleNLP#3995]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.0rc0
- paddlenlp: 2.4.3
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
[2022-12-02 11:27:54,609] [   DEBUG] - 0: main local process completed dev dataset map pre-processing, releasing all replicas
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 724, in convert_to_tensors
    tensor = as_tensor(value)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/tensor/creation.py", line 469, in to_tensor
    return _to_tensor_non_static(data, dtype, place, stop_gradient)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/tensor/creation.py", line 344, in _to_tensor_non_static
    stop_gradient=stop_gradient)
ValueError: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:549)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 138, in fetch
    data = self.collate_fn(data)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddlenlp/data/data_collator.py", line 396, in __call__
    return_tensors=return_tensors,
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2642, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 218, in __init__
    prepend_batch_axis=prepend_batch_axis)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 734, in convert_to_tensors
    "Unable to create tensor, you should probably activate truncation and/or padding "
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.
```

### 稳定复现步骤 & 代码

用自己的数据集直接跑的https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_summarization/pegasus 希望帮忙看一下

**Comment by gongel** [comment]
你好，应该是数据问题，可以检查下数据是否有空的。另外这里也提供一份demo数据集，你跑下是否有问题：https://github.com/PaddlePaddle/PaddleNLP/blob/8a7f95a97653fcb421d5c819f32165fce329f967/applications/text_summarization/pegasus/run_prepare.py#L18

**Comment by liuliuNLP** [comment]
> 你好，应该是数据问题，可以检查下数据是否有空的。另外这里也提供一份demo数据集，你跑下是否有问题：
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/8a7f95a97653fcb421d5c819f32165fce329f967/applications/text_summarization/pegasus/run_prepare.py#L18

Traceback (most recent call last):
  File "run_summarization.py", line 339, in <module>
    do_train(args)
  File "run_summarization.py", line 290, in do_train
    lm_logits, new_cache, loss = model(**batch)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddlenlp/transformers/pegasus/modeling.py", line 654, in forward
    labels.reshape((-1, )))
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/nn/layer/loss.py", line 404, in forward
    name=self.name)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 2393, in cross_entropy
    label_min.item()))
ValueError: Target 0 is out of lower bound.
LAUNCH INFO 2022-12-02 16:22:46,249 Exit code -15
出现这个问题

**Comment by daidaiJ** [comment]
我看了一下是paddleNLP tokenizer 没有截断和最大文本长度的参数，需要补齐转换后token长度
