### ISSUE TITLE
Target 0 is out of lower bound.

### ISSUE THREAD

**Issue by liuliuNLP** [PaddlePaddle/PaddleNLP#4007]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.02.4.0rc0
- paddlenlp: 2.4.3
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "run_summarization.py", line 339, in <module>
    do_train(args)
  File "run_summarization.py", line 290, in do_train
    lm_logits, new_cache, loss = model(**batch)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddlenlp/transformers/pegasus/modeling.py", line 654, in forward
    labels.reshape((-1, )))
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/nn/layer/loss.py", line 404, in forward
    name=self.name)
  File "/home/nlper/anaconda3/envs/tf24/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 2393, in cross_entropy
    label_min.item()))
ValueError: Target 0 is out of lower bound.
LAUNCH INFO 2022-12-05 10:09:01,228 Exit code -15
```

### 稳定复现步骤 & 代码

用咱们给的数据集直接跑的https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_summarization/pegasus 希望帮忙看一下

**Comment by gongel** [comment]
你好，请问这是跑到第几步呢？我们CI测试没问题。

**Comment by liuliuNLP** [comment]
> ```gfm
>   lm_logits, new_cache, loss = model(**batch)
> ```

  lm_logits, new_cache, loss = model(**batch)

**Comment by gongel** [comment]
你好，经过测试，确实没有复现你的问题。Paddle安装2.3.2/ 2.4.1试下？另外可以debug看下这步的label和logits具体输出是啥？https://github.com/PaddlePaddle/PaddleNLP/blob/c9c5c15a661f7a7274a303009c0812df43ec43c4/paddlenlp/transformers/pegasus/modeling.py#L651
