### ISSUE TITLE
[Bug]: 运行事件抽取蒸馏时产生了几个疑问：

### ISSUE THREAD

**Issue by 996-icu-FuJian** [PaddlePaddle/PaddleNLP#4038]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.0.post116
- paddlenlp: 2.4.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
1) labelmap.json中的relation2id和entity2id是不是弄反了？
2) student_data中的train.json如果教师模型的预测结果不包含labelmap中所有值会有keyerror报错。
```

### 稳定复现步骤 & 代码

Traceback (most recent call last):
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 275, in __getitem__
    return self._transform(
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 267, in _transform
    data = fn(data)
  File "/workspace/PaddleNLP-release-2.4/model_zoo/uie-ext/data_distill/utils.py", line 138, in tokenize_and_align_train_labels
    p = label_maps["relation2id"][r["predicate"]]
KeyError: '结婚'

**Comment by linjieccc** [comment]
@996-icu-FuJian Hi，

1）relation2id和entity2id是根据schema来构造的
2）因为是封闭域蒸馏，即标签类别已知且固定的情况，可以check下标注数据（doccano_ext.json）中的所有标签类型在step 2离线蒸馏阶段的schema定义中都有包含
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/data_distill/data_distill.py#L117

**Comment by 996-icu-FuJian** [comment]
> @996-icu-FuJian Hi，
> 
> 1）relation2id和entity2id是根据schema来构造的 2）因为是封闭域蒸馏，即标签类别已知且固定的情况，可以check下标注数据（doccano_ext.json）中的所有标签类型在step 2离线蒸馏阶段的schema定义中都有包含 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/data_distill/data_distill.py#L117

Hi~
实体识别中我的数据标签和schema中并没有“object”这个类型，在数据蒸馏的时候还是会产生“object”这个类型的数据。

**Comment by linjieccc** [comment]
@996-icu-FuJian Hi, 关系抽取中客体在封闭域蒸馏中会统一打上``object``这一类标签表示，因为我们其实并不需要关注客体的类别

**Comment by 996-icu-FuJian** [comment]
> @996-icu-FuJian Hi, 关系抽取中客体在封闭域蒸馏中会统一打上`object`这一类标签表示，因为我们其实并不需要关注客体的类别

Hi~，感谢您的解答~
但是在蒸馏训练中会报“keyerror 在label_maps.json中无法找到'object'”的错，对于这个问题，我应该在label_maps.json中加上object类别吗？在实体抽取的问题上，蒸馏训练还会出现梯度消失的问题，我又应该如何去解决呢？

**Comment by Viserion-nlper** [comment]
我也遇到了同样的keyError：‘object'问题
