### ISSUE TITLE
unimo-text使用FastTransformer

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#4045]
### 请提出你的问题

环境：
cuda10.2
cudnn:7
paddlepaddle:2.3.2

使用FastTransformer报错

copying build/temp.linux-x86_64-3.7/lib/libboost.a -> /root/.paddlenlp/extensions/6e658a31a925a6f37c505cb133faedf9/FasterTransformer
copying build/temp.linux-x86_64-3.7/lib/libdecoding_op.so -> /root/.paddlenlp/extensions/6e658a31a925a6f37c505cb133faedf9/FasterTransformer
Traceback (most recent call last):
  File "export_model.py", line 101, in <module>
    do_predict(args)
  File "export_model.py", line 58, in do_predict
    trans_out=True)
  File "/home/share_space/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/share_space/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddlenlp/ops/faster_transformer/transformer/faster_transformer.py", line 1148, in __init__
    hidden_act=self._hidden_act)
  File "/home/share_space/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 2046, in __init__
    need_parallel=not get_ft_para_conf().no_para)
  File "/home/share_space/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddlenlp/utils/file_lock.py", line 113, in _impl
    func(*args, **kwargs)
  File "/home/share_space/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 314, in load
    ops = load_op_meta_info_and_register_op(lib_filepath)
  File "/home/share_space/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 134, in load_op_meta_info_and_register_op
    core.load_op_meta_info_and_register_op(lib_filename)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (/root/.paddlenlp/extensions/6e658a31a925a6f37c505cb133faedf9/FasterTransformer/libdecoding_op.so) that Paddle depends on is not configured correctly. (error code is /root/.paddlenlp/extensions/6e658a31a925a6f37c505cb133faedf9/FasterTransformer/libdecoding_op.so: undefined symbol: _ZN6paddle17OpMetaInfoBuilderC1EOSsm)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:303)

**Comment by gongel** [comment]
你好，PaddlePaddle重新安装下，cuda、cudnn的版本需要对应，可参考：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html。
如果还没配置好，可考虑使用docker镜像。

**Comment by ZTurboX** [comment]
> 你好，PaddlePaddle重新安装下，cuda、cudnn的版本需要对应，可参考：[https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html。](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html%E3%80%82) 如果还没配置好，可考虑使用docker镜像。

用了docker
环境registry.baidubce.com/paddlepaddle/paddle 2.4.1-gpu-cuda11.2-cudnn8.2-trt8.0

copying build/temp.linux-x86_64-3.7/lib/libdecoding_op.so -> /root/.paddlenlp/extensions/f7f6547e0d59428b8b3e61c4a9fd3a01/FasterTransformer
copying build/temp.linux-x86_64-3.7/lib/libboost.a -> /root/.paddlenlp/extensions/f7f6547e0d59428b8b3e61c4a9fd3a01/FasterTransformer
Traceback (most recent call last):
File "export_model.py", line 101, in
do_predict(args)
File "export_model.py", line 58, in do_predict
trans_out=True)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/utils.py", line 170, in impl
init_func(self, *args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/faster_transformer.py", line 1148, in init
hidden_act=self._hidden_act)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 2057, in init
restore_data=True)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 1115, in convert_params
model.apply(convert)
File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 268, in apply
layer.apply(fn)
File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 268, in apply
layer.apply(fn)
File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 270, in apply
fn(self)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 1044, in convert
params["slf_q_weight"].append((w, False))
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 992, in append
restore_data=restore_data)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 836, in transfer_param
new_p = type(p)(shape=param_shape, dtype=dtype, is_bias=is_bias)
RuntimeError: (PreconditionNotMet) Could not parse args and kwargs successfully, please check your input first and makesure you are on the right way. The expected arguments as follow: (value, place, persistable, zero_copy, name, stop_gradient, dims, dtype, type)
[Hint: Expected flag == true, but received flag:0 != true:1.] (at /paddle/paddle/fluid/pybind/eager.cc:638)
