### ISSUE TITLE
[Question]: UIE模型推理时报错

### ISSUE THREAD

**Issue by briup1** [PaddlePaddle/PaddleNLP#4059]
### 请提出你的问题

Traceback (most recent call last):
  File "infer_cpu.py", line 103, in <module>
    main()
  File "infer_cpu.py", line 79, in main
    outputs = predictor.predict(texts)
  File "/zhangxuejie373/ren857/PaddleNLP-develop/model_zoo/uie/deploy/python/uie_predictor.py", line 461, in predict
    results = self._multi_stage_predict(input_data)
  File "/zhangxuejie373/ren857/PaddleNLP-develop/model_zoo/uie/deploy/python/uie_predictor.py", line 402, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "/zhangxuejie373/ren857/PaddleNLP-develop/model_zoo/uie/deploy/python/uie_predictor.py", line 192, in _single_stage_predict
    start_prob, end_prob = self._infer(input_dict)
  File "/zhangxuejie373/ren857/PaddleNLP-develop/model_zoo/uie/deploy/python/uie_predictor.py", line 458, in _infer
    return self.inference_backend.infer(data)
  File "/zhangxuejie373/ren857/PaddleNLP-develop/model_zoo/uie/deploy/python/uie_predictor.py", line 80, in infer
    result = self.predictor.run(None, input_dict)
  File "/zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'p2o.Gather.0' Status Message: indices element out of data bounds, idx=37366 must be within the inclusive range [-30522,30521]

UIE模型推理时报错

**Comment by linjieccc** [comment]
@briup1 Hi，

辛苦提供一下复现代码以及版本信息

**Comment by briup1** [comment]
@linjieccc HI,

朋友，PaddleNLP-develop/model_zoo/uie/deploy/python/infer_cpu.py 和infer_gpu.py,代码执行都会产生这个问题。
版本信息:
Name: paddlenlp
Version: 2.4.3
Summary: Easy-to-use and powerful NLP library with Awesome model zoo, supporting wide-range of NLP tasks from research to industrial applications, including Neural Search, Question Answering, Information Extraction and Sentiment Analysis end-to-end system.
Home-page: https://github.com/PaddlePaddle/PaddleNLP
Author: PaddleNLP Team
Author-email: paddlenlp@baidu.com
License: Apache 2.0
Location: /zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/site-packages
Requires: colorama, colorlog, datasets, dill, jieba, multiprocess, paddle2onnx, paddlefsl, protobuf, sentencepiece, seqeval, tqdm, visualdl
Required-by:

**Comment by briup1** [comment]
@linjieccc 经过实验；引发上述问题的直接原因是uie_predictor.py 99行写死了，或许应该暴露出一个参数循序非中文模型传入，另外；infer_gpu.py 执行可能会引起下面的报错，涉及[nvidia-container-toolkit]暂无法解决  T -T

AssertionError: The environment for GPU inference is not set properly. A possible cause is that you had installed both onnxruntime and onnxruntime-gpu. Please run the following commands to reinstall: 
 1) pip uninstall -y onnxruntime onnxruntime-gpu 
 2) pip install onnxruntime-gpu

**Comment by linjieccc** [comment]
@briup1 Hi, 可以参考这里check下CUDA、cuDNN的版本是否满足要求：https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements
