### ISSUE TITLE
unimo-text使用FastTransformer模型导出报错

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#4069]
### 请提出你的问题

docker环境registry.baidubce.com/paddlepaddle/paddle 2.4.1-gpu-cuda11.2-cudnn8.2-trt8.0

copying build/temp.linux-x86_64-3.7/lib/libdecoding_op.so -> /root/.paddlenlp/extensions/f7f6547e0d59428b8b3e61c4a9fd3a01/FasterTransformer
copying build/temp.linux-x86_64-3.7/lib/libboost.a -> /root/.paddlenlp/extensions/f7f6547e0d59428b8b3e61c4a9fd3a01/FasterTransformer
Traceback (most recent call last):
File "export_model.py", line 101, in
do_predict(args)
File "export_model.py", line 58, in do_predict
trans_out=True)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/utils.py", line 170, in impl
init_func(self, *args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/faster_transformer.py", line 1148, in init
hidden_act=self._hidden_act)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 2057, in init
restore_data=True)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 1115, in convert_params
model.apply(convert)
File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 268, in apply
layer.apply(fn)
File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 268, in apply
layer.apply(fn)
File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 270, in apply
fn(self)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 1044, in convert
params["slf_q_weight"].append((w, False))
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 992, in append
restore_data=restore_data)
File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/decoding.py", line 836, in transfer_param
new_p = type(p)(shape=param_shape, dtype=dtype, is_bias=is_bias)
RuntimeError: (PreconditionNotMet) Could not parse args and kwargs successfully, please check your input first and makesure you are on the right way. The expected arguments as follow: (value, place, persistable, zero_copy, name, stop_gradient, dims, dtype, type)
[Hint: Expected flag == true, but received flag:0 != true:1.] (at /paddle/paddle/fluid/pybind/eager.cc:638)

**Comment by gongel** [comment]
你好，可以尝试PaddlePaddle降级到2.3.2试试看。

**Comment by ZTurboX** [comment]
> 你好，可以尝试PaddlePaddle降级到2.3.2试试看。

换成2.3.2后，使用inference.py
Infer begin...
Traceback (most recent call last):
  File "inference.py", line 285, in <module>
    infer(args, predictor, data_loader, tokenizer)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "inference.py", line 237, in infer
    predictor.run()
ValueError: In user code:

    File "export_model.py", line 101, in <module>
      do_predict(args)
    File "export_model.py", line 93, in do_predict
      os.path.join(args.inference_model_dir, "unimo_text"))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 861, in save
      inner_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
      *desired_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/faster_transformer.py", line 1238, in forward
      model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/faster_transformer.py", line 1149, in prepare_inputs_for_generation
      attention_mask = paddle.cast(attention_mask == 0, dtype="float16" if self._use_fp16_decoding else "float32")
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
      attrs={'axis': axis})
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
      [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():12 != paddle::experimental::CppTypeToDataType<T>::Type():13.] (at /paddle/paddle/phi/core/dense_tensor.cc:137)
      [operator < equal > error]
