### ISSUE TITLE
examples\question_generation\unimo-text\deploy中报错

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#4072]
### 请提出你的问题

Infer begin...
Traceback (most recent call last):
  File "inference.py", line 285, in <module>
    infer(args, predictor, data_loader, tokenizer)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "inference.py", line 237, in infer
    predictor.run()
ValueError: In user code:

    File "export_model.py", line 101, in <module>
      do_predict(args)
    File "export_model.py", line 93, in do_predict
      os.path.join(args.inference_model_dir, "unimo_text"))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 861, in save
      inner_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
      *desired_input_spec, with_hook=with_hook)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/faster_transformer.py", line 1238, in forward
      model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddlenlp/ops/faster_transformer/transformer/faster_transformer.py", line 1149, in prepare_inputs_for_generation
      attention_mask = paddle.cast(attention_mask == 0, dtype="float16" if self._use_fp16_decoding else "float32")
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
      attrs={'axis': axis})
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
      [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():10 != paddle::experimental::CppTypeToDataType<T>::Type():13.] (at /paddle/paddle/phi/core/dense_tensor.cc:137)
      [operator < equal > error]

**Comment by westfish** [comment]
升级新paddle新版本后可能会遇到该问题，目前问题已解决，请参考fix bug unimo fp16 infer error #4166
