### ISSUE TITLE
[Question]: 请问Taskflow("dependency_parsing")的from_segments输入分词列表的长度是否有限制呢？

### ISSUE THREAD

**Issue by shtdbb** [PaddlePaddle/PaddleNLP#4096]
### 请提出你的问题

我将一个句子通过 Taskflow("word_segmentation", mode="accurate") 精确模式分词，得到分词列表；
之后将分词列表通过 from_segments 来做 Taskflow("dependency_parsing") 任务，之后得到报错信息：
`RecursionError: maximum recursion depth exceeded in comparison`
请问是分词列表超过限制了吗？我的这个句子有2416个字符。

以下是完整的报错信息：
```
Traceback (most recent call last):
  File "process_PaddleNLP.py", line 127, in <module>
    dep = ddp.from_segments([tokens])[0]   # 依存句法分析，返回 [{}]
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/taskflow.py", line 576, in from_segments
    results = self.task_instance.from_segments(inputs)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 204, in from_segments
    outputs = self._run_model(inputs)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 315, in _run_model
    arc_preds, rel_preds = decode(arc_preds, rel_preds, s_arc, mask, self.tree)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 507, in decode
    arc_preds[bad] = eisner(s_arc[bad], mask[bad])
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 580, in eisner
    backtrack(p_i[i], p_c[i], heads, 0, length, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 632, in backtrack
    backtrack(p_i, p_c, heads, j, r + 1, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 627, in backtrack
    backtrack(p_i, p_c, heads, r, j, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 631, in backtrack
    backtrack(p_i, p_c, heads, i, r, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 627, in backtrack
    backtrack(p_i, p_c, heads, r, j, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 627, in backtrack
    backtrack(p_i, p_c, heads, r, j, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 627, in backtrack
    backtrack(p_i, p_c, heads, r, j, True)
  [Previous line repeated 4 more times]
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 632, in backtrack
    backtrack(p_i, p_c, heads, j, r + 1, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 622, in backtrack
    if i == j:
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by fengyunzaidushi** [comment]
```
  [Previous line repeated 4 more times]
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 632, in backtrack
    backtrack(p_i, p_c, heads, j, r + 1, True)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 626, in backtrack
    backtrack(p_i, p_c, heads, i, r, False)
  File "/usr/local/Anaconda3/lib/python3.8/site-packages/paddlenlp/taskflow/dependency_parsing.py", line 622, in backtrack
    if i == j:
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by linjieccc** [comment]
@shtdbb Hi，

你可以试试设置一下系统的递归限制：

```python
import sys
sys.setrecursionlimit(5000)
```

另外句法分析比较适合句子级的输入，长文本的处理效果可能不会很理想

**Comment by shtdbb** [comment]
好的谢谢！
