### ISSUE TITLE
在windos中用cpu环境运行web_service.py，但是报错了，麻烦请问该如何解决呢，谢谢

### ISSUE THREAD

**Issue by ZhuXiang-tuxing** [PaddlePaddle/PaddleNLP#4107]
在笔记本电脑上用CPU运行启动服务，结果出现这个问题，不知道要怎么改

❯ python web_service.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\admin\.conda\envs\paddle\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\admin\.conda\envs\paddle\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\admin\.conda\envs\paddle\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\admin\.conda\envs\paddle\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\admin\.conda\envs\paddle\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\admin\.conda\envs\paddle\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\admin\.conda\envs\paddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PycharmProjectsWork\paddleocr-id_card_db\deploy\pdserving\web_service.py", line 45, in <module>
    uci_service.run_service()
  File "C:\Users\admin\.conda\envs\paddle\lib\site-packages\paddle_serving_server\web_service.py", line 69, in run_service
    self._server.run_server()
  File "C:\Users\admin\.conda\envs\paddle\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 314, in run_server
    PipelineServicer(self._name, self._response_op, self._conf),
  File "C:\Users\admin\.conda\envs\paddle\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 57, in __init__
    raise CustomException(CustomExceptionCode.INIT_ERROR, "pipeline server init error")
paddle_serving_server.pipeline.error_catch.CustomException: 
	exception_code: 3003
	exception_type: INIT_ERROR
	error_msg: pipeline server init error
	is_send_to_user: False

**Comment by w5688414** [comment]
请问您使用的是哪份代码？
windows运行paddle serving，请参考代码：

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/question_answering/faq_finance/deploy/python/web_service_windows.py
