### ISSUE TITLE
[Question]: windows cpu 环境调用uie-x-base模型提取信息报错

### ISSUE THREAD

**Issue by BessieNhl** [PaddlePaddle/PaddleNLP#4108]
### 请提出你的问题

完整报错信息：
Traceback (most recent call last):
  File "F:/python_workspace/paddlenlp/info_extract.py", line 10, in <module>
    ie = Taskflow("information_extraction", schema=schema, model="uie-x-base", device_id=-1)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 540, in __init__
    model=self.model, task=self.task, priority_path=self.priority_path, from_hf_hub=from_hf_hub, **self.kwargs
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 413, in __init__
    self._get_inference_model()
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddlenlp\taskflow\task.py", line 283, in _get_inference_model
    self._construct_model(self.model)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 452, in _construct_model
    model_instance = MODEL_MAP[self._init_class].from_pretrained(self._task_path)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddlenlp\transformers\model_utils.py", line 525, in from_pretrained
    base_model = cls.base_model_class(*base_args, **base_kwargs)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddlenlp\transformers\utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddlenlp\transformers\ernie_layout\modeling.py", line 656, in __init__
    self.embeddings = ErnieLayoutEmbeddings(config)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddlenlp\transformers\ernie_layout\modeling.py", line 122, in __init__
    self.register_buffer("position_ids", paddle.arange(config["max_position_embeddings"]).expand((1, -1)))
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddle\tensor\manipulation.py", line 3401, in expand
    return _C_ops.expand(x, shape)
OSError: Invalid enum backend type `64`.
  [C:\home\workspace\Paddle\paddle/phi/common/backend.h:140]

**Comment by linjieccc** [comment]
@BessieNhl Hi，请提供一下paddle版本信息

**Comment by BessieNhl** [comment]
你好，这是paddle相关的版本；
paddle-bfloat==0.1.7
paddle2onnx==1.0.5
paddlefsl==1.1.0
paddlenlp==2.4.5
paddleocr==2.6.1.1
paddlepaddle-gpu==2.4.1

上面问题中的报错是之前paddlepaddle安装的cpu版本，改成GPU版本会报错:
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddlenlp\transformers\ernie_layout\modeling.py", line 122, in __init__
    self.register_buffer("position_ids", paddle.arange(config["max_position_embeddings"]).expand((1, -1)))
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddle\tensor\manipulation.py", line 3397, in expand
    return _C_ops.expand(x, shape)
OSError: Invalid enum backend type `63`.
  [..\paddle/phi/common/backend.h:140]

**Comment by linjieccc** [comment]
@BessieNhl 我们在windows环境没有复现出这个问题，你的python版本是多少？

**Comment by BessieNhl** [comment]
python 3.7

**Comment by BessieNhl** [comment]
python 3.8也试过，一样的错误

**Comment by linjieccc** [comment]
可以先看看是不是paddle的安装的问题
```python
import paddle 
paddle.utils.run_check()
```

**Comment by BessieNhl** [comment]
运行报同类错误
W1215 10:17:07.802500 16832 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.7, Runtime API Version: 10.2
W1215 10:17:07.819489 16832 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "F:/python_workspace/paddlenlp/info_extract.py", line 21, in <module>
    paddle.utils.run_check()
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddle\utils\install_check.py", line 270, in run_check
    _run_dygraph_single(use_cuda, use_xpu, use_npu)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddle\utils\install_check.py", line 136, in _run_dygraph_single
    linear_out = linear(input_tensor)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddle\nn\layer\common.py", line 175, in forward
    out = F.linear(
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\paddle\nn\functional\common.py", line 1882, in linear
    return _C_ops.linear(x, weight, bias)
OSError: Invalid enum backend type `63`.
  [..\paddle/phi/common/backend.h:140]

**Comment by linjieccc** [comment]
安装一下这个版本的paddle试试

```shell
python -m pip install paddlepaddle-gpu==2.4.1.post117 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
```

另外你的cuDNN应该需要升级到v8.4.1，参考 [cuDNN安装](https://docs.nvidia.com/deeplearning/cudnn/install-guide/)

**Comment by BessieNhl** [comment]
确实是paddle的问题，2.4以上版本不知道哪里不兼容，我换了一台电脑运行成功了，非常感谢！
