### ISSUE TITLE
[Bug]:  export_model() missing 1 required positional argument: 'input_spec' 的错误

### ISSUE THREAD

**Issue by liruixue** [PaddlePaddle/PaddleNLP#4147]
### 软件环境

```Markdown
paddle-bfloat         0.1.7           
paddle2onnx           1.0.3           
paddlefsl             1.1.0           
paddlenlp             2.4.3           
paddleocr             2.6.1.0         
paddlepaddle-gpu      2.4.0rc0.post112
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

GPU环境下，按照‘小样本场景下的多标签层次分类任务指南’，
测试给定的events数据，整个训练过程可以跑完，但是在导出步骤，也即执行
```
python train.py --do_export --data_dir ./data --output_dir ./export_checkpoint --resume_from_checkpoint ./checkponts/
```
这个命令时，会出现TypeError: export_model() missing 1 required positional argument: 'input_spec'的错误提示

### 稳定复现步骤 & 代码

GPU机器，已满足paddlepaddle及paddleNlp/paddle2onnx的版本要求，按照‘小样本场景下的多标签层次分类任务指南’，见这个链接
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/hierarchical/few-shot#readme

测试给定的events数据，整个训练过程可以跑完，但是在导出模型的步骤，无法通过。也即执行：
```bash
python train.py --do_export --data_dir ./data --output_dir ./export_checkpoint --resume_from_checkpoint ./checkponts/
```
这个命令时，会出现以下错误提示：
```
[2022-12-17 14:27:50,017] [    INFO] - Loading model from ./checkpoints/ .
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 129, in main
    trainer.export_model(export_path,  export_type=model_args.export_type)
TypeError: export_model() missing 1 required positional argument: 'input_spec'
```

**Comment by LemonNoel** [comment]
develop 版本代码将 input_spec 的构造内置到了Trainer中，可将[这段代码](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/prompt/prompt_model.py#L125-L141)复制到 [train.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_classification/multi_label/few-shot/train.py#L129) 中自定义 input_spec 以暂时解决 develop 版本和 2.4.3 版本间的 diff，也就是 train.py 129行替换为

```
from paddle.static import InputSpec

template_keywords = template.extract_template_keywords(template.prompt)
input_spec = [
    InputSpec(shape=[None, None], dtype="int64", name="input_ids"),
    InputSpec(shape=[None, None], dtype="int64", name="token_type_ids"),
    InputSpec(shape=[None, None], dtype="int64", name="position_ids"),
    InputSpec(shape=[None, None, None, None], dtype="float32", name="attention_mask"),
]
if "mask" in template_keywords:
    input_spec.append(InputSpec(shape=[None], dtype="int64", name="masked_positions"))
if "soft" in template_keywords:
    # Add placeholder for argument `masked_positions` if not exists.
    if "mask" not in template_keywords:
        input_spec.append(None)
        input_spec.append(InputSpec(shape=[None, None], dtype="int64", name="soft_token_ids"))
        if "encoder" in template_keywords:
            input_spec.append(InputSpec(shape=[None, None], dtype="int64", name="encoder_ids"))
trainer.export_model(export_path, input_spec=input_spec, export_type=model_args.export_type)
```

**Comment by liruixue** [comment]
感谢，已解决
