### ISSUE TITLE
[Bug]: TypeError: forward() got an unexpected keyword argument 'pos_ids'

### ISSUE THREAD

**Issue by xiaohuqi** [PaddlePaddle/PaddleNLP#4200]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.0.post112
- paddlenlp: 2.4.5
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "finetune.py", line 245, in <module>
    main()
  File "finetune.py", line 184, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/work/anaconda3/envs/uie_env/lib/python3.8/site-packages/paddlenlp/trainer/trainer.py", line 614, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/work/anaconda3/envs/uie_env/lib/python3.8/site-packages/paddlenlp/trainer/trainer.py", line 1253, in training_step
    loss = self.compute_loss(model, inputs)
  File "/work/anaconda3/envs/uie_env/lib/python3.8/site-packages/paddlenlp/trainer/trainer.py", line 1215, in compute_loss
    outputs = model(**inputs)
  File "/work/anaconda3/envs/uie_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
TypeError: forward() got an unexpected keyword argument 'pos_ids'
```

### 稳定复现步骤 & 代码

python finetune.py  \
    --device gpu \
    --logging_steps 10 \
    --save_steps 10 \
    --eval_steps 10 \
    --seed 42 \
    --model_name_or_path uie-base \
    --output_dir ./checkpoint/model_best \
    --train_path ./train.txt \
    --dev_path ./dev.txt  \
    --max_seq_length 512  \
    --per_device_eval_batch_size 5 \
    --per_device_train_batch_size  5 \
    --num_train_epochs 5 \
    --learning_rate 1e-5 \
    --label_names 'start_positions' 'end_positions' \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir ./checkpoint/model_best \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/4176 可以看一下这个issue
