### ISSUE TITLE
[Bug]: 当文本中存在emoji时，使用tokenizer获取offset_mapping会出现list越界问题

### ISSUE THREAD

**Issue by 1649759610** [PaddlePaddle/PaddleNLP#4241]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 2.4.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
当文本中存在emoji时，使用tokenizer获取offset_mapping会出现list越界问题。报错信息如下。


Traceback (most recent call last):
  File "/wangqinghui/mynlp/PaddleNLP/test_taskflow.py", line 28, in <module>
    encoded_inputs = tokenizer(text=text, text_pair=prompt,truncation=True,
  File "/wangqinghui/mynlp/PaddleNLP/paddlenlp/transformers/tokenizer_utils_base.py", line 2209, in __call__
    return self.encode(
  File "/wangqinghui/mynlp/PaddleNLP/paddlenlp/transformers/tokenizer_utils_base.py", line 2286, in encode
    return self._encode_plus(
  File "/wangqinghui/mynlp/PaddleNLP/paddlenlp/transformers/tokenizer_utils.py", line 985, in _encode_plus
    return self.prepare_for_model(
  File "/wangqinghui/mynlp/PaddleNLP/paddlenlp/transformers/tokenizer_utils_base.py", line 2768, in prepare_for_model
    token_offset_mapping = self.get_offset_mapping(text)
  File "/wangqinghui/mynlp/PaddleNLP/paddlenlp/transformers/tokenizer_utils.py", line 1362, in get_offset_mapping
    return self._get_bert_like_offset_mapping(text)
  File "/wangqinghui/mynlp/PaddleNLP/paddlenlp/transformers/tokenizer_utils.py", line 1338, in _get_bert_like_offset_mapping
    token_mapping.append((char_mapping[start], char_mapping[end - 1] + 1))
IndexError: list index out of range
```
```


### 稳定复现步骤 & 代码

from paddlenlp.transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("ernie-1.0")
text = "好👌🏻"
prompt = '评价维度'
encoded_inputs = tokenizer(text=text, text_pair=prompt, runcation=True,pad_to_max_seq_len=True, return_attention_mask=True, return_position_ids=True, return_offsets_mapping=True,)

print(encoded_inputs)

**Comment by wj-Mcat** [comment]
经过文本分析可知：
* "好👌🏻"并非是两个字符，而是三个字符
* 经过 tokenize 之后会有两个 unk 连续出现，此时会导致 offset-mapping 的计算出现问题
* 第二个字符是：👌🏻，第三个字符是'🏻'，ASCII 数值为：127995，这种特殊字符存在于emoji 之中。


为了解决这个问题，可临时性为这个特殊字符打上补丁，可是还是需要完善[normalize_chars](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/tokenizer_utils.py#L216)从而支持更多的字符移除。 不知道 @1649759610  是否有相关的资料能够支持检测出更多的特殊字符。

**Comment by wj-Mcat** [comment]
在你的 case 当中，emoji 所占据的字符数不同，通常一个 emoji 只占据一个字符，可是你的占据了两个，导致两个 unk 连续出现。

参考链接：https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by 1649759610** [comment]
当前没有太多字符示例，这里还有个字符：text = "。❌❌ "

这种情况在语料中还是比较普遍的，是否可以系统地整理一边emoji字符的生成和组合形式尝试解决。

**Comment by wj-Mcat** [comment]
我目前在 https://github.com/PaddlePaddle/PaddleNLP/pull/4557 中处理了多个 emoji 连续出现的情况，你可以 clone 我的分支来看看你的问题是否还存在，或者你给出示例代码（给定输入和期望输出等）来测试一下。

**Comment by wj-Mcat** [comment]
在你上面的示例中，属于简单 emoji 字符，本身为单个 Unicode 字符，容易被识别，可是在transformers 和 paddlenlp 中针对于这个字符的处理还有些不同：

测试代码为：

```python

from transformers import BertTokenizer
from paddlenlp.transformers import BertTokenizer
tokenizer: BertTokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
text = "。❌❌"
print(tokenizer.tokenize(text))
print(len(text))

result = tokenizer(
    text,
    return_offset_mapping=True
)
print(result["input_ids"])
```

* transformers 将其作为单个unk来处理
* paddlenlp 将其作为两个连续的 unk 来处理

从文本上面看来，paddlenlp 的处理貌似更贴近原始文本，可是在这个 special case 上面看来，功能上没有跟 hf 对齐。
