### ISSUE TITLE
层次分类模型裁剪出错

### ISSUE THREAD

**Issue by wfs420100** [PaddlePaddle/PaddleNLP#4287]
### 请提出你的问题

层级分类进行模型裁剪训练时报错
python prune.py \
    --device "gpu" \
    --dataset_dir "data" \
    --output_dir "prune" \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 32 \
    --num_train_epochs 10 \
    --max_seq_length 128 \
    --logging_steps 5 \
    --save_steps 100 \
    --width_mult_list '3/4' '2/3' '1/2'

Traceback (most recent call last):
  File "prune.py", line 124, in <module>
    main()
  File "prune.py", line 120, in main
    trainer.compress(custom_dynabert_evaluate=dynabert_evaluate)
TypeError: compress() got an unexpected keyword argument 'custom_dynabert_evaluate'

paddle-bfloat            0.1.7
paddle2onnx              1.0.3
paddlefsl                1.1.0
paddlenlp                2.4.3
paddlepaddle-gpu         2.4.1.post117
paddleslim               2.4.0

**Comment by wawltor** [comment]
建议升级2.4.7版本再试试

**Comment by wfs420100** [comment]
> 
paddle-bfloat            0.1.7
paddle2onnx              1.0.3
paddlefsl                1.1.0
paddlenlp                2.4.7
paddlepaddle-gpu         2.4.1.post117
paddleslim               2.4.0

更新版本后（且代码是在git新拉取的），原问题仍然存在，

**Comment by LiuChiachi** [comment]
把`custom_dynabert_evaluate`改成`custom_evaluate`试试呢

**Comment by wfs420100** [comment]
> 
进行更改后，出现新的问题

Traceback (most recent call last):
  File "prune.py", line 124, in <module>
    main()
  File "prune.py", line 120, in main
    trainer.compress(custom_evaluate=dynabert_evaluate)
  File "/home/weifengshun/weifengshun/Environment/miniconda3/envs/main/lib/python3.8/site-packages/paddlenlp/trainer/trainer_compress.py", line 70, in compress
    _dynabert(self, self.model, args.output_dir)
  File "/home/weifengshun/weifengshun/Environment/miniconda3/envs/main/lib/python3.8/site-packages/paddlenlp/trainer/trainer_compress.py", line 138, in _dynabert
    ofa_model = _dynabert_training(
  File "/home/weifengshun/weifengshun/Environment/miniconda3/envs/main/lib/python3.8/site-packages/paddlenlp/trainer/trainer_compress.py", line 407, in _dynabert_training
    evaluate(self, teacher_model, eval_dataloader)
  File "/home/weifengshun/weifengshun/Environment/miniconda3/envs/main/lib/python3.8/site-packages/paddlenlp/trainer/trainer_compress.py", line 304, in evaluate
    return self.custom_evaluate(self, model, data_loader)
  File "/home/weifengshun/weifengshun/Environment/miniconda3/envs/main/lib/python3.8/site-packages/decorator.py", line 231, in fun
    args, kw = fix(args, kw, sig)
  File "/home/weifengshun/weifengshun/Environment/miniconda3/envs/main/lib/python3.8/site-packages/decorator.py", line 203, in fix
    ba = sig.bind(*args, **kwargs)
  File "/home/weifengshun/weifengshun/Environment/miniconda3/envs/main/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/home/weifengshun/weifengshun/Environment/miniconda3/envs/main/lib/python3.8/inspect.py", line 2958, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments

**Comment by wfs420100** [comment]
train.py 训练所保存的模型结果文件config的文件名称与analysis/evaluate.py内验证文件是否存在时，抛出异常
![image](https://user-images.githubusercontent.com/64070362/209943683-9f535717-a9a6-4835-8c17-f86958bdbe1a.png)

**Comment by chinesejunzai12** [comment]
你好这个问题你解决了吗, 我也出现同样的问题

**Comment by lugimzzz** [comment]
> 你好这个问题你解决了吗, 我也出现同样的问题

后一个问题可以使用最新develop代码解决

**Comment by chinesejunzai12** [comment]
> 
你说的是 把custom_dynabert_evaluate改成custom_evaluate之后报
<img width="436" alt="image" src="https://user-images.githubusercontent.com/103180175/215400908-8361f343-58bb-4a0a-9e9a-e3fa31f27e1d.png">
这个错误可以解决是么?

**Comment by lugimzzz** [comment]
> > 
> 
> 你说的是 把custom_dynabert_evaluate改成custom_evaluate之后报 <img alt="image" width="436" src="https://user-images.githubusercontent.com/103180175/215400908-8361f343-58bb-4a0a-9e9a-e3fa31f27e1d.png"> 这个错误可以解决是么?

**Comment by lugimzzz** [comment]
> > > 
> > 
> > 
> > 你说的是 把custom_dynabert_evaluate改成custom_evaluate之后报 <img alt="image" width="436" src="https://user-images.githubusercontent.com/103180175/215400908-8361f343-58bb-4a0a-9e9a-e3fa31f27e1d.png"> 这个错误可以解决是么?

这是因为压缩api变动，对应的代码没有兼容，我们已经修复。你可以参考一下这个pr修改一下代码，或待pr合入后拉取develop分支代码使用 https://github.com/PaddlePaddle/PaddleNLP/pull/4567

**Comment by chinesejunzai12** [comment]
我目前的解决方式是: trainer.compress(custom_dynabert_evaluate=dynabert_evaluate)中的参数去掉trainer.compress(), 可以生产对应的修剪模型, 但是不清楚这个是否导出的模型正确?

**Comment by lugimzzz** [comment]
> 我目前的解决方式是: trainer.compress(custom_dynabert_evaluate=dynabert_evaluate)中的参数去掉trainer.compress(), 可以生产对应的修剪模型, 但是不清楚这个是否导出的模型正确?

是去掉`custom_dynabert_evaluate=dynabert_evaluate`吗？
这时候评价指标应该就是用准确率，而非f1了，也可以运行但还是推荐用f1作为评价指标
