### ISSUE TITLE
调用paddleNLP中内置的crf，将维特比算法写在前向计算中时，在进行反向计算会出现报错

### ISSUE THREAD

**Issue by Wakp** [PaddlePaddle/PaddleNLP#438]
我本想将viterbi算法解析出的结果做其它模型的输入，然后再求loss做反向传播，但发现当前向计算中加入viterbi后就会报错

环境：
paddlenlp          2.0.1
paddlepaddle       2.1.0

demo代码如下：
```
import paddle
import paddle.nn as nn
from paddlenlp.layers import crf

paddle.set_device("cpu")

class MutilErnieCrf(nn.Layer):
    def __init__(self, out_num=8, dropout=None):
        super(MutilErnieCrf, self).__init__()
        self.linear = nn.Linear(1, 8)
        self.crf = crf.LinearChainCrf(out_num, crf_lr=0.1, with_start_stop_tag=False)
        self.crf_loss = crf.LinearChainCrfLoss(self.crf)
        self.viterbi = crf.ViterbiDecoder(self.crf.transitions, with_start_stop_tag=False)
        self.relu = nn.ReLU6()
        self.dropout = nn.Dropout(dropout if dropout is not None else 0.1)

    def forward(self, X, lengths):
        feature_linear = self.linear(X)
        res_feature = self.relu(feature_linear)
        scores, path = self.viterbi(res_feature, lengths)
        return path

    def compute_loss(self, inputs, lengths, labels, old_version_labels=None):
        loss = self.crf_loss(inputs, lengths, labels, old_version_labels=None)
        return loss

model=MutilErnieCrf()

x = paddle.randn((2, 128, 1), dtype="float32")
lengths = paddle.to_tensor([128, 128], dtype='int64')
Y = model(x, lengths)
print(Y)
Y.backward()
```

报错信息如下：
````
Traceback (most recent call last):
  File "F:/main/0_work_file/niht-algorithm/EMR/Info_Extract_2.0/all_test.py", line 33, in <module>
    Y.backward()
  File "<decorator-gen-123>", line 2, in backward
  File "D:\Anaconda\envs\paddle_2.0\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Anaconda\envs\paddle_2.0\lib\site-packages\paddle\fluid\framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\paddle_2.0\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 236, in backward
    framework._dygraph_tracer())
NotImplementedError: (Unimplemented) Gradient accumulation of data type (int64_t) on place (CPUPlace) is not supported in imperative mode (at C:\home\workspace\Paddle_release\paddle\fluid\imperative\gradient_accumulator.cc:222)
```

**Comment by Wakp** [comment]
> 我本想将viterbi算法解析出的结果做其它模型的输入，然后再求loss做反向传播，但发现当前向计算中加入viterbi后就会报错
> demo代码如下：
> 
> ```
> import paddle
> import paddle.nn as nn
> from paddlenlp.layers import crf
> 
> paddle.set_device("cpu")
> 
> class MutilErnieCrf(nn.Layer):
>     def __init__(self, out_num=8, dropout=None):
>         super(MutilErnieCrf, self).__init__()
>         self.linear = nn.Linear(1, 8)
>         self.crf = crf.LinearChainCrf(out_num, crf_lr=0.1, with_start_stop_tag=False)
>         self.crf_loss = crf.LinearChainCrfLoss(self.crf)
>         self.viterbi = crf.ViterbiDecoder(self.crf.transitions, with_start_stop_tag=False)
>         self.relu = nn.ReLU6()
>         self.dropout = nn.Dropout(dropout if dropout is not None else 0.1)
> 
>     def forward(self, X, lengths):
>         feature_linear = self.linear(X)
>         res_feature = self.relu(feature_linear)
>         scores, path = self.viterbi(res_feature, lengths)
>         return path
> 
>     def compute_loss(self, inputs, lengths, labels, old_version_labels=None):
>         loss = self.crf_loss(inputs, lengths, labels, old_version_labels=None)
>         return loss
> 
> model=MutilErnieCrf()
> 
> x = paddle.randn((2, 128, 1), dtype="float32")
> lengths = paddle.to_tensor([128, 128], dtype='int64')
> Y = model(x, lengths)
> print(Y)
> Y.backward()
> ```
> 
> 报错信息如下：
> 
> ```
> Traceback (most recent call last):
>   File "F:/main/0_work_file/niht-algorithm/EMR/Info_Extract_2.0/all_test.py", line 33, in <module>
>     Y.backward()
>   File "<decorator-gen-123>", line 2, in backward
>   File "D:\Anaconda\envs\paddle_2.0\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
>     return wrapped_func(*args, **kwargs)
>   File "D:\Anaconda\envs\paddle_2.0\lib\site-packages\paddle\fluid\framework.py", line 225, in __impl__
>     return func(*args, **kwargs)
>   File "D:\Anaconda\envs\paddle_2.0\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 236, in backward
>     framework._dygraph_tracer())
> NotImplementedError: (Unimplemented) Gradient accumulation of data type (int64_t) on place (CPUPlace) is not supported in imperative mode (at C:\home\workspace\Paddle_release\paddle\fluid\imperative\gradient_accumulator.cc:222)
> ```
> ```
paddlenlp          2.0.1
paddlepaddle       2.1.0

**Comment by joey12300** [comment]
@Wakp 你好，一般来说viterbi解码得到的结果是int类型的label，用于预测场景，并不参与训练时loss的计算。而且Paddle不支持int值的tensor直接进行backward。可将viterbi预测得到的label计算一个loss，再求backward。关于如何使用CRF模型与其他模型组合，可参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/information_extraction/waybill_ie/model.py

**Comment by Wakp** [comment]
感谢您耐心的答复，我想做一个多层次信息抽取，我希望第二层次会参考第一层的结果，所以想可这个写法。由于我对paddlepaddle不是很熟，我又写了一个demo,请您帮忙再看看有没有什么方法可避免该问题。
```
import paddle
import paddle.nn as nn
from paddlenlp.layers import crf

paddle.set_device("cpu")

class MultiCrf(nn.Layer):
    def __init__(self, label_nums=[], dropout=None):
        super(MultiCrf, self).__init__()
        assert label_nums is not []
        self.label_num = len(label_nums)
        self.linear_to_label = [nn.Linear(2 if i > 0 else 1, label_nums[i]) for i in range(self.label_num)]
        self.linear_res_to_label = [nn.Linear(1, 768) for i in range(self.label_num)]
        self.crf_list = [crf.LinearChainCrf(label_nums[i], crf_lr=0.1, with_start_stop_tag=False) for i in range(self.label_num)]
        self.crf_loss = [crf.LinearChainCrfLoss(self.crf_list[i]) for i in range(self.label_num)]
        self.viterbi = [crf.ViterbiDecoder(self.crf_list[i].transitions, with_start_stop_tag=False) for i in range(self.label_num)]
        self.relu = [nn.ReLU6() for i in range(self.label_num)]
        self.dropout = [nn.Dropout(dropout if dropout is not None else 0.1) for _ in range(self.label_num)]

    def forward(self, X, lengths, Labels):
        self.out = []
        self.loss = []
        multi_feature = []
        for i in range(self.label_num):
            if i == 0:
                feature_drop = self.dropout[i](X)
                feature_linear = self.linear_to_label[i](feature_drop)
            else:
                feature = paddle.concat([X, last], axis=-1)
                feature_drop = self.dropout[i](feature)
                feature_linear = self.linear_to_label[i](feature_drop)
            res_feature = self.relu[i](feature_linear)
            loss = self.crf_loss[i](res_feature, lengths, Labels[i])
            multi_feature.append(res_feature)
            scores, batch_path = self.viterbi[i](res_feature, lengths)
            last = paddle.unsqueeze(batch_path, -1)
            last = last.astype("float32")
            self.loss.append(loss)
            self.out.append(batch_path)
        return self.out, multi_feature, self.loss



cur_label_nums = [8, 10]
model = MultiCrf(cur_label_nums)
x = paddle.randn([2, 128, 1], dtype="float32")
lengths = paddle.to_tensor([128, 128], dtype='int64')
label = [paddle.randint(0, 7, [2, 128], dtype="int64") for i in range(len(cur_label_nums))]
_, _, loss = model(x, lengths, label)
total_loss = 0
for l in loss:
    total_loss += l
avg_loss = total_loss/len(cur_label_nums)
print(avg_loss)
avg_loss.backward()
```

**Comment by joey12300** [comment]
@Wakp 您好，viterbi解码的结果不能参与反向梯度更新，所以要添加一行代码：
`last.stop_gradient=True`。
直接使用label结果作为参数比较奇怪，可以考虑尝试使用viterbi结果中的scores作为参数。

完整代码如下：
```python
import paddle
import paddle.nn as nn
from paddlenlp.layers import crf

paddle.set_device("cpu")

class MultiCrf(nn.Layer):
    def __init__(self, label_nums=[], dropout=None):
        super(MultiCrf, self).__init__()
        assert label_nums is not []
        self.label_num = len(label_nums)
        self.linear_to_label = [nn.Linear(2 if i > 0 else 1, label_nums[i]) for i in range(self.label_num)]
        self.linear_res_to_label = [nn.Linear(1, 768) for i in range(self.label_num)]
        self.crf_list = [crf.LinearChainCrf(label_nums[i], crf_lr=0.1, with_start_stop_tag=False) for i in range(self.label_num)]
        self.crf_loss = [crf.LinearChainCrfLoss(self.crf_list[i]) for i in range(self.label_num)]
        self.viterbi = [crf.ViterbiDecoder(self.crf_list[i].transitions, with_start_stop_tag=False) for i in range(self.label_num)]
        self.relu = [nn.ReLU6() for i in range(self.label_num)]
        self.dropout = [nn.Dropout(dropout if dropout is not None else 0.1) for _ in range(self.label_num)]

    def forward(self, X, lengths, Labels):
        self.out = []
        self.loss = []
        multi_feature = []
        for i in range(self.label_num):
            if i == 0:
                feature_drop = self.dropout[i](X)
                feature_linear = self.linear_to_label[i](feature_drop)
            else:
                feature = paddle.concat([X, last], axis=-1)
                feature_drop = self.dropout[i](feature)
                feature_linear = self.linear_to_label[i](feature_drop)
            res_feature = self.relu[i](feature_linear)
            loss = self.crf_loss[i](res_feature, lengths, Labels[i])
            multi_feature.append(res_feature)
            scores, batch_path = self.viterbi[i](res_feature, lengths)
            last = paddle.unsqueeze(batch_path, -1)
            last = last.astype("float32")
            # last 不能参与反向梯度更新
            last.stop_gradient=True
            self.loss.append(loss)
            self.out.append(batch_path)
        return self.out, multi_feature, self.loss



cur_label_nums = [8, 10]
model = MultiCrf(cur_label_nums)
x = paddle.randn([2, 128, 1], dtype="float32")
lengths = paddle.to_tensor([128, 128], dtype='int64')
label = [paddle.randint(0, 7, [2, 128], dtype="int64") for i in range(len(cur_label_nums))]
_, _, loss = model(x, lengths, label)
total_loss = 0
for l in loss:
    total_loss += l
avg_loss = total_loss/len(cur_label_nums)
print(avg_loss)
avg_loss.backward()

```

**Comment by Wakp** [comment]
好的，感谢
