### ISSUE TITLE
[Bug]: finetune.py多卡微调报PretrainedConfig instance not found in the arguments, you can set it as args or kwargs with config field

### ISSUE THREAD

**Issue by LANSEYOUYUMOWANG** [PaddlePaddle/PaddleNLP#4381]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1.post112 
- paddlenlp: 2.4.9
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
使用一下命令：
python -u -m paddle.distributed.launch --gpus "0,1" finetune.py   --device gpu  --logging_steps 10 --save_steps 100 --eval_steps 100  --seed 42  --model_name_or_path uie-base --output_dir ./checkpoint/model_best --train_path data/train.txt --dev_path data/dev.txt --max_seq_length 512  
进行多卡微调时，报如下错误
Traceback (most recent call last):
  File "finetune.py", line 250, in <module>
    main()
  File "finetune.py", line 125, in main
    model = UIE.from_pretrained(model_args.model_name_or_path)
  File "/home/zkzy/anaconda3/envs/paddlenlp_test/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 440, in from_pretrained
    return cls.from_pretrained_v2(pretrained_model_name_or_path, from_hf_hub=from_hf_hub, *args, **kwargs)
  File "/home/zkzy/anaconda3/envs/paddlenlp_test/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 1261, in from_pretrained_v2
    model = cls(config, *init_args, **model_kwargs)
  File "/home/zkzy/anaconda3/envs/paddlenlp_test/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/zkzy/PaddleNLP-develop/model_zoo/uie/model.py", line 22, in __init__
    super(UIE, self).__init__()
  File "/home/zkzy/anaconda3/envs/paddlenlp_test/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/zkzy/anaconda3/envs/paddlenlp_test/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/zkzy/anaconda3/envs/paddlenlp_test/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 261, in __init__
    raise ValueError(
ValueError: PretrainedConfig instance not found in the arguments, you can set it as args or kwargs with config field
```

### 稳定复现步骤 & 代码

环境如下：
![image](https://user-images.githubusercontent.com/36221128/211230431-d9d9b6d4-7388-47eb-a24f-63dd34f1527a.png)
使用python -u -m paddle.distributed.launch --gpus "0,1" finetune.py   --device gpu  --logging_steps 10 --save_steps 100 --eval_steps 100  --seed 42  --model_name_or_path uie-base --output_dir ./checkpoint/model_best --train_path data/train.txt --dev_path data/dev.txt --max_seq_length 512  命令进行多卡微调

**Comment by linjieccc** [comment]
@LANSEYOUYUMOWANG Hi，

可以拉取最新的develop分支代码试下

**Comment by LANSEYOUYUMOWANG** [comment]
拉取到最新的develop分支代码，运行结果如下：
![image](https://user-images.githubusercontent.com/36221128/211474293-c518e262-cea6-4b02-8752-6db72364cf3a.png)
