### ISSUE TITLE
[Bug]: Paddle Inference运行预测示例程序mobilenetv1_full_api.py报错：ValueError: Unsupported backend: .

### ISSUE THREAD

**Issue by sweetboxwwy** [PaddlePaddle/PaddleNLP#4391]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 
- CUDA 10.2
- DOCKER
- UBUNTU 18.04
- paddlelite 2.8
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
运行预测示例程序mobilenetv1_full_api.py报错：ValueError: Unsupported backend: .

python mobilenetv1_full_api.py --model_dir=./mobilenet_v1

Traceback (most recent call last):
File "mobilenetv1_full_api.py", line 237, in <module>
RunModel(args)
File "mobilenetv1_full_api.py", line 184, in RunModel
raise ValueError("Unsupported backend: %s." % args.backend)
ValueError: Unsupported backend: .
```

### 稳定复现步骤 & 代码

https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/demo/python/mobilenetv1_full_api.py

**Comment by wawltor** [comment]
看起来这个是PaddleLite的部署的问题，建议到 https://github.com/PaddlePaddle/Paddle-Lite  提一下issue哈

**Comment by wawltor** [comment]
您好，我们将暂时该issue，如有疑问可以再次打开该issue。
