### ISSUE TITLE
[Question]: ValueError: no signature found for builtin <paddle.fluid.dygraph.dygraph_to_static.program_translator.StaticFunction object at 0x7f3937aed400>

### ISSUE THREAD

**Issue by Isfate** [PaddlePaddle/PaddleNLP#4405]
### 请提出你的问题

我在使用最新版uie进行训练并同时在训练结束时同时进行压缩, 但是报了下边的错误
似乎我的使用方法有些问题, 但是没有找到这个程序进行压缩的教程
我的环境:
paddlenlp 2.4.9
paddlepaddle-gpu  2.4.1
python 3.8.15

[01-10 17:35:38 MainThread @logger.py:242] Argv: /data/zhb/zyl/uie2.4.9/finetune.py --device gpu --logging_steps 10 --save_steps 100 --eval_steps 100 --seed 42 --max_seq_length 512 --per_device_eval_batch_size 32 --per_device_train_batch_size 32 --num_train_epochs 1 --learning_rate 1e-5 --do_train --do_eval --do_export --overwrite_output_dir --disable_tqdm True --metric_for_best_model eval_f1 --load_best_model_at_end True --save_total_limit 1 --output_dir checkpoint/rebine/logs
[01-10 17:35:38 MainThread @utils.py:73] paddlepaddle version: 2.4.1.
[01-10 17:35:39 MainThread @__init__.py:42] PARL detects two backend frameworks: paddle, torch. Use paddle by default.
[01-10 17:35:39 MainThread @__init__.py:43] To use torch as backend, `export PARL_BACKEND=torch` before running the scripts.
WARNING:root:cannot import name 'layers' from 'parl' (/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/site-packages/parl/__init__.py)
Tue Jan 10 17:35:56 Dynamic-to-Static INFO: (Level -1) Not recommend to deepcopy 'UIE' decorated with @to_static, it has side effect that will rollback into original state before @to_static. Please deepcopy 'UIE' before applying @to_static.
Traceback (most recent call last):
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/inspect.py", line 1135, in getfullargspec
    sig = _signature_from_callable(func,
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/inspect.py", line 2308, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/inspect.py", line 2119, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <paddle.fluid.dygraph.dygraph_to_static.program_translator.StaticFunction object at 0x7f3937aed400>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/zhb/.vscode-server/extensions/ms-python.python-2022.6.0/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/data/zhb/.vscode-server/extensions/ms-python.python-2022.6.0/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/data/zhb/.vscode-server/extensions/ms-python.python-2022.6.0/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/zhb/zyl/uie2.4.9/finetune.py", line 430, in <module>
    main()
  File "/data/zhb/zyl/uie2.4.9/finetune.py", line 426, in main
    trainer.compress(custom_evaluate=custom_evaluate)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/site-packages/paddlenlp/trainer/trainer_compress.py", line 70, in compress
    _dynabert(self, self.model, args.output_dir)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/site-packages/paddlenlp/trainer/trainer_compress.py", line 153, in _dynabert
    ofa_model, teacher_model = _dynabert_init(self, model, eval_dataloader)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/site-packages/paddlenlp/trainer/trainer_compress.py", line 267, in _dynabert_init
    teacher_model = copy.deepcopy(model)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 695, in __deepcopy__
    self.rollback()
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 648, in rollback
    setattr(self._class_instance, func_name,
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 907, in __setattr__
    value = adapt_stale_fwd_patch(self, name, value)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 75, in adapt_stale_fwd_patch
    (spec_args, spec_varargs, spec_varkw, spec_defaults, _, _, _) = inspect.getfullargspec(self.forward)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/inspect.py", line 1144, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable

**Comment by imempty** [comment]
问题解决了吗，我也遇到这个问题了
