### ISSUE TITLE
PaddleNLP-develop\applications\information_extraction\document\deploy 部署连接后预测值为空

### ISSUE THREAD

**Issue by Eddyzhangpan** [PaddlePaddle/PaddleNLP#4411]
### 请提出你的问题

Name: paddlenlp
Version: 2.4.9
相关代码：
1,
server.py
from paddlenlp import SimpleServer, Taskflow

# The schema changed to your defined schema
schema = ['开票日期', '名称', '纳税人识别号', '开户行及账号', '金额', '价税合计', 'No', '税率', '地址、电话', '税额' ]
# The task path changed to your best model path
uie = Taskflow(
    "information_extraction",
    schema=schema,
    #task_path="C:/NLPtest/checkpoint/model_best",
)
# If you want to define the finetuned uie service
app = SimpleServer()
app.register_taskflow("taskflow/uie", uie)

2.client.py
import requests
import json
from paddlenlp.utils.doc_parser import DocParser

# Define the docuemnt parser
doc_parser = DocParser()

image_paths = ['C:/Users/Administrator/Desktop/images/b2.jpg']
image_base64_docs = []

# Get the image base64 to post
for image_path in image_paths:
    req_dict = {}
    doc = doc_parser.parse({"doc": image_path}, do_ocr=False)
    base64 = doc['image']
    req_dict['doc'] = base64
    image_base64_docs.append(req_dict)

url = "http://192.168.1.11:8189/taskflow/uie"
headers = {"Content-Type": "application/json"}
data = {'data': image_base64_docs}

# Post the requests
r = requests.post(url=url, headers=headers, data=json.dumps(data))
#print("最后结果：",data)
datas = json.loads(r.text)
print(datas)

运行结果：
(doccano) C:\NLPtest\document\deploy\simple_serving>client.py
{'result': {}}

我试了TEXT的抽取部署，一样结果也为空

**Comment by wawltor** [comment]
修复PR： https://github.com/PaddlePaddle/PaddleNLP/pull/4414  你可以拉取最新的client.py使用即可

**Comment by wawltor** [comment]
您好，我们先关闭该issue，如有问题，可以再次打开该issue。

**Comment by Eddyzhangpan** [comment]
又出现新问题，麻烦有空帮我看看，谢谢
Server.py这边报错如下
[2023-01-12 16:40:42,615] [    INFO] - The predictor id: 0 is selected by running the taskflow.
INFO:     192.168.1.11:51356 - "POST /taskflow/uie HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\server\http_router\router.py", line 104, in predict
    result = self._app._taskflow_manager.predict(inference_request.data, inference_request.parameters)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\server\taskflow_manager.py", line 40, in predict
    return self._handler_func(self._task[task_index], data, parameters)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\server\handlers\taskflow_handler.py", line 34, in process
    return predictor(text)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 592, in __call__
    results = self.task_instance(inputs)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\taskflow\task.py", line 434, in __call__
    inputs = self._preprocess(*args)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 506, in _preprocess
    inputs = self._check_input_text(inputs)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 535, in _check_input_text
    data = self._parser_map[self._ocr_lang_choice].parse(
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\utils\doc_parser.py", line 64, in parse
    ocr_result = self.ocr(image)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\utils\doc_parser.py", line 118, in ocr
    ocr_result = self.ocr_infer_model.ocr(image, det, rec, cls)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\paddleocr.py", line 555, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 271, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 240, in __call__
    boxes, scores = self.boxes_from_bitmap(pred[batch_index], mask,
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 131, in boxes_from_bitmap
    score = self.box_score_fast(pred, points.reshape(-1, 2))
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 188, in box_score_fast
    xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
[2023-01-12 16:40:44,071] [   ERROR] h11_impl.py:376 - Exception in ASGI application
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\server\http_router\router.py", line 104, in predict
    result = self._app._taskflow_manager.predict(inference_request.data, inference_request.parameters)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\server\taskflow_manager.py", line 40, in predict
    return self._handler_func(self._task[task_index], data, parameters)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\server\handlers\taskflow_handler.py", line 34, in process
    return predictor(text)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 592, in __call__
    results = self.task_instance(inputs)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\taskflow\task.py", line 434, in __call__
    inputs = self._preprocess(*args)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 506, in _preprocess
    inputs = self._check_input_text(inputs)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 535, in _check_input_text
    data = self._parser_map[self._ocr_lang_choice].parse(
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\utils\doc_parser.py", line 64, in parse
    ocr_result = self.ocr(image)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddlenlp\utils\doc_parser.py", line 118, in ocr
    ocr_result = self.ocr_infer_model.ocr(image, det, rec, cls)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\paddleocr.py", line 555, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 271, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 240, in __call__
    boxes, scores = self.boxes_from_bitmap(pred[batch_index], mask,
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 131, in boxes_from_bitmap
    score = self.box_score_fast(pred, points.reshape(-1, 2))
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 188, in box_score_fast
    xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)
  File "D:\ProgramData\Anaconda3\envs\doccano\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
client.py这边报错如下
(doccano) C:\NLPtest\document\deploy\simple_serving>client.py
Traceback (most recent call last):
  File "C:\NLPtest\document\deploy\simple_serving\client.py", line 41, in <module>
    datas = json.loads(r.text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lcneyc** [comment]
请问您解决了吗？我也遇到了同样的问题，谢谢！
