### ISSUE TITLE
[Question]: import paddlenlp失败

### ISSUE THREAD

**Issue by ACbccc** [PaddlePaddle/PaddleNLP#4412]
### 请提出你的问题

安装环境：
系统：                     Ubuntu 16
gpu：                      2080Ti×2
显卡驱动：              460.56
CUDA：                  10.2
cudnn：                   8.7
主要依赖：
paddle2onnx           1.0.5                  
paddlefsl                 1.1.0                    
paddlenlp                2.4.9                   
paddlepaddle-gpu   2.4.1 
python                     3.7               
------------------------
错误问题：可以import paddle，但import paddlenlp报错

错误代码：
```shell
>>> import paddlenlp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/think/anaconda3/envs/mrc/lib/python3.7/site-packages/paddlenlp/__init__.py", line 29, in <module>
    from . import (
  File "/home/think/anaconda3/envs/mrc/lib/python3.7/site-packages/paddlenlp/data/__init__.py", line 16, in <module>
    from .data_collator import *
  File "/home/think/anaconda3/envs/mrc/lib/python3.7/site-packages/paddlenlp/data/data_collator.py", line 23, in <module>
    from ..transformers.tokenizer_utils_base import BatchEncoding, PretrainedTokenizerBase, PaddingStrategy
  File "/home/think/anaconda3/envs/mrc/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py", line 16, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "/home/think/anaconda3/envs/mrc/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 46, in <module>
    from paddlenlp.utils.downloader import (
  File "/home/think/anaconda3/envs/mrc/lib/python3.7/site-packages/paddlenlp/utils/__init__.py", line 17, in <module>
    from .import_utils import install_package, uninstall_package
  File "/home/think/anaconda3/envs/mrc/lib/python3.7/site-packages/paddlenlp/utils/import_utils.py", line 23, in <module>
    import pip
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "/home/think/.local/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 74, in find_spec
    return method()
  File "/home/think/.local/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 95, in spec_for_pip
    if self.pip_imported_during_build():
  File "/home/think/.local/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 108, in pip_imported_during_build
    for frame, line in traceback.walk_stack(None)
  File "/home/think/.local/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 108, in <genexpr>
    for frame, line in traceback.walk_stack(None)
KeyError: '__file__'
```

**Comment by wj-Mcat** [comment]
从上面的错误看来是由于你本地的`pip`包的问题，你可以尝试以下方法：

* 更新本地虚拟环境中的 pip 

```shell
python -m pip install --upgrade pip
```

* 创建一个新的虚拟环境

```shell
conda create -n mrc-new python=3.7

# 安装 paddle 版本
python -m pip install paddlepaddle-gpu==2.4.1 -i https://pypi.tuna.tsinghua.edu.cn/simple

# 安装 paddlenlp 的版本
pip install paddlenlp
```

从上述 error log中看来，如果你能够解决: `import pip`的问题，就可以解决 `import paddlenlp`的问题。

**Comment by wj-Mcat** [comment]
@ACbccc  请问你的问题解决了吗？
