### ISSUE TITLE
[Question]: 文本分类few-shot中, 模型导出的时候发生错误

### ISSUE THREAD

**Issue by chinesejunzai12** [PaddlePaddle/PaddleNLP#4420]
### 请提出你的问题

Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 129, in main
    trainer.export_model(export_path, export_type=model_args.export_type)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddlenlp/prompt/prompt_trainer.py", line 297, in export_model
    export_model(self.model, input_spec, export_path, export_type)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddlenlp/transformers/export.py", line 59, in export_model
    paddle.jit.save(model, save_path)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 629, in wrapper
    func(layer, path, input_spec, **configs)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/decorator-5.1.1-py3.7.egg/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 857, in save
    inner_input_spec, with_hook=with_hook)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
    *desired_input_spec, with_hook=with_hook)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
    **cache_key.kwargs)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/decorator-5.1.1-py3.7.egg/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddlenlp/prompt/prompt_model.py", line 85, in forward
        logits = self.verbalizer.process_outputs(model_outputs.logits, input_dict["masked_positions"])
    File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddlenlp/prompt/verbalizer.py", line 356, in process_outputs
        outputs = super(SoftVerbalizer, self).process_outputs(outputs, masked_positions)
    File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddlenlp/prompt/verbalizer.py", line 162, in process_outputs
        outputs = paddle.gather(outputs, masked_positions)
        print('outputs66666====:', outputs.shape)
        outputs = outputs.reshape([batch_size, -1, num_pred])
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        print('outputs222222====:', outputs.shape)
        return outputs

    File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 2139, in reshape
        return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
    File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 6439, in reshape
        attrs["shape"] = get_attr_shape(shape)
    File "/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 6415, in get_attr_shape
        % dim_idx)

    AssertionError: Only one dimension value of 'shape' in reshape can be -1. But received shape[1] is also -1.

        # N = x.shape()[2]              # N is an int. (NOT recommend under @to_static)
        N = paddle.shape(x)[2]          # N is a Tensor. (Recommend)
        z = paddle.reshape([N, -1, 4])  # z.shape is [-1, -1, 4]

    If your target shape in Reshape represents dynamic shape, please turn it into a Tensor under @to_static. See above example for details.

**Comment by chinesejunzai12** [comment]
这个主要的shape转化问题, 但是是源码中出现的, 这里只是在微调, 有知道如何进行修改的吗

**Comment by sijunhe** [comment]
@chinesejunzai12 你好，这个应该是paddlepaddle的版本过低造成的。升级至paddlepaddle 2.4.1 应该可以解决这个问题

**Comment by chinesejunzai12** [comment]
> @chinesejunzai12 你好，这个应该是paddlepaddle的版本过低造成的。升级至paddlepaddle 2.4.1 应该可以解决这个问题

嗯嗯, 已经解决, 非常感谢
