### ISSUE TITLE
[Question]:使用uie的doccnao.py时遇到TypeError: function() argument 1 must be code, not str错误 

### ISSUE THREAD

**Issue by BEILOP** [PaddlePaddle/PaddleNLP#4483]
### 请提出你的问题

Traceback (most recent call last):
  File "E:/PycharmProjects/HKNER/doccano.py", line 22, in <module>
    from paddlenlp.utils.log import logger
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\paddlenlp\__init__.py", line 25, in <module>
    from . import datasets
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\paddlenlp\datasets\__init__.py", line 15, in <module>
    from .dataset import *
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\paddlenlp\datasets\dataset.py", line 27, in <module>
    import datasets
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\datasets\__init__.py", line 37, in <module>
    from .arrow_dataset import Dataset, concatenate_datasets
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\datasets\arrow_dataset.py", line 62, in <module>
    from .arrow_reader import ArrowReader
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\datasets\arrow_reader.py", line 29, in <module>
    from .download.download_config import DownloadConfig
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\datasets\download\__init__.py", line 10, in <module>
    from .streaming_download_manager import StreamingDownloadManager
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\datasets\download\streaming_download_manager.py", line 17, in <module>
    from aiohttp.client_exceptions import ClientError
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\aiohttp\client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\aiohttp\http.py", line 7, in <module>
    from .http_parser import (
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\aiohttp\http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\aiohttp\helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 1 must be code, not str

**Comment by BEILOP** [comment]
已通过升级最新paddlenlp版本解决
