### ISSUE TITLE
[Bug]: GPT模型升级后文图生成模型调用报错

### ISSUE THREAD

**Issue by linjieccc** [PaddlePaddle/PaddleNLP#4493]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/recompute/PaddleNLP/paddlenlp/transformers/auto/modeling.py", line 1052, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/workspace/recompute/PaddleNLP/paddlenlp/transformers/auto/modeling.py", line 296, in _from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/workspace/recompute/PaddleNLP/paddlenlp/transformers/model_utils.py", line 477, in from_pretrained
    return cls.from_pretrained_v2(pretrained_model_name_or_path, from_hf_hub=from_hf_hub, *args, **kwargs)
  File "/workspace/recompute/PaddleNLP/paddlenlp/transformers/model_utils.py", line 1298, in from_pretrained_v2
    **kwargs,
  File "/workspace/recompute/PaddleNLP/paddlenlp/transformers/configuration_utils.py", line 734, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/workspace/recompute/PaddleNLP/paddlenlp/transformers/configuration_utils.py", line 756, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/workspace/recompute/PaddleNLP/paddlenlp/transformers/configuration_utils.py", line 827, in _get_config_dict
    raise FileNotFoundError(f"configuration file<{CONFIG_NAME}> or <{LEGACY_CONFIG_NAME}> not found")
FileNotFoundError: configuration file<config.json> or <model_config.json> not found
```

### 稳定复现步骤 & 代码

```python
from paddlenlp.transformers import AutoModelForImageGeneration

model = AutoModelForImageGeneration.from_pretrained("pai-painter-painting-base-zh")`
```

**Comment by MooTong123** [comment]
您好，请问还没有修复好吗？我调用taskflow也是一样的错误。

![image](https://user-images.githubusercontent.com/44767255/217194937-ae0b7c54-3f77-40ac-9a5e-722d5a177b19.png)

**Comment by wenziheng777** [comment]
raise FileNotFoundError(f"configuration file<{CONFIG_NAME}> or <{LEGACY_CONFIG_NAME}> not found")
FileNotFoundError: configuration file<config.json> or <model_config.json> not found

我也遇到一样的问题

**Comment by JunnYu** [comment]
@MooTong123 @wenziheng777 哈喽，如果想要体验文生图功能，建议使用ppdiffusers，未来taskflow里面关于文生图的内容会进行废弃
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers
![image](https://user-images.githubusercontent.com/50394665/219276597-0b0f0e21-b939-45bb-b3d7-5856dbf658e7.png)

**Comment by yanchaoguo** [comment]
> ppdiffusers

用的就是ppdiffusers ，上述问题由老版本升级到新版后 百分百复现， 看了下代码是下载的模型文件地址不对了 你们可以debug一下 @JunnYu
