### ISSUE TITLE
[Bug]: elmo训练报错

### ISSUE THREAD

**Issue by USTCKAY** [PaddlePaddle/PaddleNLP#4495]
### 软件环境

```Markdown
- paddlepaddle:0.0.0
- paddlepaddle-gpu: 0.0.0.post102
- paddlenlp: 2.4.0.dev0/2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
elmo模型训练时报如下错误：

Traceback (most recent call last):
  File "run_pretrain.py", line 123, in <module>
    train(args)
  File "run_pretrain.py", line 52, in train
    char_vocab_size=vocab.char_size,
  File "/paddle/PaddleNLP/examples/language_model/elmo/elmo.py", line 67, in __init__
    char_vocab_size, char_embed_dim, projection_dim, num_highways, cnn_filters, max_characters_per_token
  File "/paddle/PaddleNLP/examples/language_model/elmo/elmo.py", line 182, in __init__
    self._char_embedding_layer.weight[0, :] = 0
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 845, in __setitem__
    return self.__setitem_eager_tensor__(item, value)
ValueError: (InvalidArgument) Leaf Tensor (embedding_0.w_0) that doesn't stop gradient can't use inplace strategy.
  [Hint: Expected egr::egr_utils_api::IsLeafTensor(self->tensor) && !egr::EagerUtils::autograd_meta(&self->tensor)->StopGradient() == false, but received egr::egr_utils_api::IsLeafTensor(self->tensor) && !egr::EagerUtils::autograd_meta(&self->tensor)->StopGradient():1 != false:0.] (at /paddle/paddle/fluid/pybind/eager_method.cc:1128)
```

在https://github.com/PaddlePaddle/PaddleNLP/blob/d9a485568074d12b3382441f2b6f9f318b0f67a5/examples/language_model/elmo/elmo.py#L182
之前将weight的stop_gradient属性置为True，这行之后再将stop_gradient属性置为False模型可以正常运行。
```

### 稳定复现步骤 & 代码

unset CUDA_VISIBLE_DEVICES
python -m paddle.distributed.launch --gpus '0' run_pretrain.py --train_data_path='./1-billion-word/training-tokenized-shuffled/*' --vocab_file='./1-billion-word/vocab-15w.txt' --save_dir='./checkpoints' --device='gpu'

**Comment by JunnYu** [comment]
嗯嗯，谢谢指出问题，您可以提个PR解决这个问题~ 这样就可以了
```python
with paddle.no_grad():
    self._char_embedding_layer.weight[0, :] = 0 
```

**Comment by USTCKAY** [comment]
> 嗯嗯，谢谢指出问题，您可以提个PR解决这个问题~ 这样就可以了
> 
> ```python
> with paddle.no_grad():
>     self._char_embedding_layer.weight[0, :] = 0 
> ```

已经提了PR #4501  ，还要麻烦您帮忙review一下了，多谢！

**Comment by USTCKAY** [comment]
已在PR #4501 中解决了该问题
