### ISSUE TITLE
[Question]: 使用uie训练时报错'LogWriter' object has no attribute 'add_text'

### ISSUE THREAD

**Issue by qjing666** [PaddlePaddle/PaddleNLP#4506]
### 请提出你的问题

使用uie训练时报错：
`Traceback (most recent call last):
  File "finetune.py", line 245, in <module>
    main()
  File "finetune.py", line 184, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/jingqinghe/miniconda3/envs/py38/lib/python3.8/site-packages/paddlenlp/trainer/trainer.py", line 591, in train
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "/home/jingqinghe/miniconda3/envs/py38/lib/python3.8/site-packages/paddlenlp/trainer/trainer_callback.py", line 355, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/home/jingqinghe/miniconda3/envs/py38/lib/python3.8/site-packages/paddlenlp/trainer/trainer_callback.py", line 396, in call_event
    result = getattr(callback, event)(
  File "/home/jingqinghe/miniconda3/envs/py38/lib/python3.8/site-packages/paddlenlp/trainer/integrations.py", line 93, in on_train_begin
    self.vdl_writer.add_text("args", args.to_json_string())
AttributeError: 'LogWriter' object has no attribute 'add_text'`

**Comment by qjing666** [comment]
问题原因为visualdl版本不对，更新为visualdl-2.4.2后报错解决。
