### ISSUE TITLE
[Bug]: 从huggingface hub上加载tokenizer的时候报错

### ISSUE THREAD

**Issue by lugimzzz** [PaddlePaddle/PaddleNLP#4525]
### 软件环境

```Markdown
- paddlepaddle: None
- paddlepaddle-gpu: 2.4.1
- paddlenlp: develop
- fast-tokenizer-python：1.0.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
从hub上加载的分词模型并不支持fast tokenizer，安装了fast tokenizer的环境下从hub加载分词器会报错没有'BertFastTokenizer'。逻辑缺少在init_class为None（也即从hub加载tokenizer）的情况下，环境支持fast tokenizer，但分词器不支持的情况进行判断。

应该优化此处代码：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/auto/tokenizer.py#L185

报错内容：
[2023-01-19 08:59:08,320] [    INFO] - We use pattern recognition to recognize the Tokenizer class.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/PaddleNLP/paddlenlp/transformers/auto/tokenizer.py", line 262, in from_pretrained
    pretrained_model_name_or_path, config_file, use_fast
  File "/workspace/PaddleNLP/paddlenlp/transformers/auto/tokenizer.py", line 194, in _get_tokenizer_class_from_config
    tokenizer_class = getattr(import_class, init_class)
AttributeError: module 'paddlenlp.transformers.bert.tokenizer' has no attribute 'BertFastTokenizer'
```

### 稳定复现步骤 & 代码

在安装fast tokenizer的环境下执行：
```
from paddlenlp.transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased", from_hf_hub=True, use_fast=False)
```

**Comment by joey12300** [comment]
该bug需要与下面这个问题一起系统性解决：Potential issue https://github.com/PaddlePaddle/PaddleNLP/pull/3786#discussion_r102468981

**Comment by sijunhe** [comment]
@joey12300 我理解的话，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/auto/tokenizer.py#L185 这个else branch缺乏fast tokenizer逻辑。补上和上面if类似的逻辑即可
