### ISSUE TITLE
[Bug]: 加载 BertForMultipleChoice，'BertConfig' 缺失参数'num_choices'

### ISSUE THREAD

**Issue by lugimzzz** [PaddlePaddle/PaddleNLP#4526]
### 软件环境

```Markdown
- paddlepaddle:None
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 2.5.0/develop
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
加载 Multiple Choice缺少一个'BertConfig' 缺失'num_choices'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/PaddleNLP/paddlenlp/transformers/auto/modeling.py", line 694, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/workspace/PaddleNLP/paddlenlp/transformers/auto/modeling.py", line 296, in _from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/workspace/PaddleNLP/paddlenlp/transformers/model_utils.py", line 478, in from_pretrained
    return cls.from_pretrained_v2(pretrained_model_name_or_path, from_hf_hub=from_hf_hub, *args, **kwargs)
  File "/workspace/PaddleNLP/paddlenlp/transformers/model_utils.py", line 1335, in from_pretrained_v2
    model = cls(config, *init_args, **model_kwargs)
  File "/workspace/PaddleNLP/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/workspace/PaddleNLP/paddlenlp/transformers/bert/modeling.py", line 1154, in __init__
    self.num_choices = config.num_choices
  File "/workspace/PaddleNLP/paddlenlp/transformers/configuration_utils.py", line 485, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'BertConfig' object has no attribute 'num_choices'
```

### 稳定复现步骤 & 代码

```
from paddlenlp.transformers import AutoModelForMultipleChoice
model = AutoModelForMultipleChoice.from_pretrained("bert-base-uncased")
model = AutoModelForMultipleChoice.from_pretrained("bert-base-uncased", from_hf_hub=True)
```

**Comment by wj-Mcat** [comment]
这类的问题后续有时间要统一调整
