### ISSUE TITLE
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.   [Hint: Please search for the error code(8) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/kernels/gpudnn/conv_kernel.cu:376)

### ISSUE THREAD

**Issue by lichuantao6626** [PaddlePaddle/PaddleNLP#4653]
### 请提出你的问题

在运行https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/examples/textual_inversion这个微调模型时，遇到问题：
Train Steps:   0%|                                                                                   | 0/3000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_textual_inversion.py", line 672, in <module>
    main()
  File "train_textual_inversion.py", line 597, in main
    latents = vae.encode(batch["pixel_values"]).latent_dist.sample()
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/ppdiffusers/models/vae.py", line 572, in encode
    h = self.encoder(x)
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/ppdiffusers/models/vae.py", line 133, in forward
    sample = self.conv_in(sample)
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 712, in forward
    out = F.conv._conv_nd(
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 140, in _conv_nd
    pre_bias = _C_ops.conv2d(
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
  [Hint: Please search for the error code(8) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/kernels/gpudnn/conv_kernel.cu:376)

Train Steps:   0%|  

模型微调执行的命令：
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
# 这里需要输入刚才下载的图片所保存的文件目录
export DATA_DIR="cat_toy_images"

python -u train_textual_inversion.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$DATA_DIR \
  --learnable_property="object" \
  --placeholder_token="<cat-toy>" --initializer_token="toy" \
  --height=512 \
  --width=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --max_train_steps=3000 \
  --learning_rate=5.0e-04 \
  --scale_lr \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --seed 42 \
  --output_dir="textual_inversion_cat"
硬件环境：
![image](https://user-images.githubusercontent.com/102787771/216878040-ac509d0a-cea4-4c3d-be29-dc5f3fb5838f.png)
请问，这个问题是哪里引起，怎么解决，感谢！

**Comment by wawltor** [comment]
1. 首先排查一下 paddle是否安装成功 
  ```python
  import paddle
  paddle.utils.run_check()
  ```
2. 看看训练显存是否有溢出

**Comment by JunnYu** [comment]
@lichuantao6626 看你的GPU当前已经使用了约18G显存，实际可用只有6G不到，可能会出现错误，建议把显存都释放了单独跑这个程序试试
