### ISSUE TITLE
[Bug]: uie文档抽取，索引越界

### ISSUE THREAD

**Issue by shiyun123456789** [PaddlePaddle/PaddleNLP#4656]
### 软件环境

```Markdown
paddle-bfloat                  0.1.7
paddle2onnx                    1.0.1
paddleclas                     2.4.3
paddledet                      2.5.0
paddlefsl                      1.1.0
paddlehub                      2.1.0
paddlelabel                    0.5.0
paddlenlp                      2.5.0
paddleocr                      2.6.1.0
paddlepaddle                   2.4.0
paddleslim                     2.4.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
在进行uie文档抽取测试时，索引越界
报错信息：
Traceback (most recent call last):
  File "D:\tools\PyCharm 2022.2.3\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\tools\PyCharm 2022.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\project\python\ocr\uie.py", line 15, in <module>
    results = ie({"doc":doc_path})
  File "D:\tools\anaconda\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 603, in __call__
    results = self.task_instance(inputs)
  File "D:\tools\anaconda\lib\site-packages\paddlenlp\taskflow\task.py", line 439, in __call__
    outputs = self._run_model(inputs)
  File "D:\tools\anaconda\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 941, in _run_model
    results = self._multi_stage_predict(_inputs)
  File "D:\tools\anaconda\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 1086, in _multi_stage_predict
    results = self._add_bbox_info(results, data)
  File "D:\tools\anaconda\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 1133, in _add_bbox_info
    result = _add_bbox(result, char_boxes)
  File "D:\tools\anaconda\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 1096, in _add_bbox
    cur_box = char_boxes[i][1]
IndexError: list index out of range
```

### 稳定复现步骤 & 代码

from pprint import pprint
from paddlenlp import Taskflow
from paddlenlp.utils.doc_parser import DocParser
schema = ['收货人名称','收货地点','发货地点','供煤地点','发站','到站','交货地点','含税单价（元/吨）','不含税单价（元/吨）','合同价（元/吨）','数量（吨）','运输方式','标煤单价（元/吨）','单价']
ie = Taskflow('information_extraction', schema=schema,model='uie-x-base')
doc_path = "C:/Users/Administrator/Desktop/1675663754789.jpg"
results = ie({"doc":doc_path})

图片：
![1675663754789](https://user-images.githubusercontent.com/31406086/216900525-9b3892f6-8ce0-4a5a-8a96-2f93cf0625f3.jpg)

**Comment by linjieccc** [comment]
UIE-X tokenzer 将"℃"拆开处理，导致offset_mapping与原始文本无法对应，

```python
from paddlenlp.transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("uie-x-base")
tokenizer("≥1350℃", return_offsets_mapping=True)
'''
{'input_ids': [0, 220884, 88622, 2389, 7236, 441, 2], 'offset_mapping': [(0, 0), (0, 1), (1, 4), (4, 5), (5, 6), (5, 6), (0, 0)]}
'''
```
