### ISSUE TITLE
[Bug]: luke模型加载报错

### ISSUE THREAD

**Issue by USTCKAY** [PaddlePaddle/PaddleNLP#4665]
### 软件环境

```Markdown
- paddlepaddle:0.0.0
- paddlepaddle-gpu: 0.0.0.post102
- paddlenlp: 2.5.0.post0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
在SQuAD1.1数据集上训练luke时模型加载报错，报错信息如下：
Traceback (most recent call last):
  File "run_squad.py", line 358, in <module>
    run(args)
  File "run_squad.py", line 248, in run
    model = model_class.from_pretrained(args.model_name_or_path)
  File "/workspace/PaddleNLP/paddlenlp/transformers/model_utils.py", line 617, in from_pretrained
    base_model = cls.base_model_class(*base_args, **base_kwargs)
  File "/workspace/PaddleNLP/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/workspace/PaddleNLP/paddlenlp/transformers/luke/modeling.py", line 620, in __init__
    hidden_dropout_prob=hidden_dropout_prob,
  File "/workspace/PaddleNLP/paddlenlp/transformers/luke/modeling.py", line 186, in __init__
    pad_token_id=pad_token_id,
TypeError: __init__() got an unexpected keyword argument 'vocab_size'
```

### 稳定复现步骤 & 代码

训练指令：
`python run_squad.py --model_type luke --device gpu --learning_rate 15e-6     --num_train_epochs 2     --batch_size 8     --do_predict     --do_train     --model_name_or_path luke-large `

**Comment by michelleqyhqyh** [comment]
How do you fix this issure?

**Comment by USTCKAY** [comment]
> How do you fix this issure?

I have not fix it at present.

**Comment by wyqnumber** [comment]
降低版本，2.5版本的Config有问题
