### ISSUE TITLE
[Bug]: ChineseBert训练报错

### ISSUE THREAD

**Issue by USTCKAY** [PaddlePaddle/PaddleNLP#4666]
### 软件环境

```Markdown
- paddlepaddle:0.0.0
- paddlepaddle-gpu: 0.0.0.post102
- paddlenlp:2.5.0.post0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
报错信息如下：
Traceback (most recent call last):
  File "train_chn.py", line 81, in <module>
    model = ChineseBertForSequenceClassification.from_pretrained("ChineseBERT-large", num_classes=2)
  File "/workspace/PaddleNLP/paddlenlp/transformers/model_utils.py", line 617, in from_pretrained
    base_model = cls.base_model_class(*base_args, **base_kwargs)
  File "/workspace/PaddleNLP/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/workspace/PaddleNLP/paddlenlp/transformers/chinesebert/modeling.py", line 391, in __init__
    self.pooler = BertPooler(hidden_size, pool_act)
TypeError: __init__() takes 2 positional arguments but 3 were given
阅读ChineseBert的模型组网代码看到调用了Bert的BertPooler，但是提供的初始化参数却不是BertConfig类型的，似乎是这个原因导致的报错。
```

### 稳定复现步骤 & 代码

训练指令：
`python train_chn.py \
--data_path './data/ChnSentiCorp' \
--device 'gpu' \
--epochs 10 \
--max_seq_length 512 \
--batch_size 8 \
--learning_rate 2e-5 \
--weight_decay 0.0001 \
--warmup_proportion 0.1 \
--seed 2333 \
--save_dir 'outputs/chn' | tee outputs/train_chn.log`

**Comment by sijunhe** [comment]
#4683 修复了模型相关的问题，不过tokenizer仍然有问题。请 @wj-Mcat 有空修复一下
