### ISSUE TITLE
[Bug]: load_torch 序列化加载失败

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/PaddleNLP#4699]
### 软件环境

```Markdown
develop
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
wget https://huggingface.co/microsoft/markuplm-base/blob/main/pytorch_model.bin 
python -c "from paddlenlp.utils.serialization import load_torch;load_torch('pytorch_model.bin')"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/ssd2/zhonghui03/Datasets/PaddleNLP/paddlenlp/utils/serialization.py", line 256, in load_torch
    stage1_key_to_tensor[key] = np_buffer.reshape(tensor_meta.size, order=order)
ValueError: cannot reshape array of size 138221680 into shape (2,)
```

### 稳定复现步骤 & 代码

```shell
wget https://huggingface.co/microsoft/markuplm-base/blob/main/pytorch_model.bin 
python -c "from paddlenlp.utils.serialization import load_torch;load_torch('pytorch_model.bin')"
```

**Comment by wj-Mcat** [comment]
目前针对于torch模型加载的问题，后续会通过safetensor来完成，所以这个问题暂时在paddlenlp中不解决

**Comment by ZHUI** [comment]
这是个存量的问题，不是说切 safetensor 就没有问题了，大量的老的ckpt，甚至第三方上传的新ckpt都可能有问题。 @sijunhe 看要不做个torch load的兜底。

**Comment by sijunhe** [comment]
> 这是个存量的问题，不是说切 safetensor 就没有问题了，大量的老的ckpt，甚至第三方上传的新ckpt都可能有问题。 @sijunhe 看要不做个torch load的兜底。

我觉得torch load兜底肯定是不能接受的，因为paddlenlp肯定不能去依赖torch。因为使用paddle加载torch ckpt其实是一个底层功能，这个能力是应该由框架那边来解决的，之前 @wj-Mcat 也对接过。当前这个api可以理解成我们在框架补足这个能力之前暂时用来顶上的，不会很鲁棒
