### ISSUE TITLE
[Question]: 文本分类使用paddleserving进行部署时，遇到错误该如何解决？

### ISSUE THREAD

**Issue by MooTong123** [PaddlePaddle/PaddleNLP#4710]
### 请提出你的问题

版本：
paddlepaddle 2.3.2
paddlenlp  2.4.0
paddle-serving-app     0.9.0
paddle-serving-client    0.9.0
paddle-serving-server    0.9.0

1. 文本分类使用paddleserving进行部署时，根据文档进行试验（https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/deploy/paddle_serving）
2. 运行命令，遇到错误：
![image](https://user-images.githubusercontent.com/44767255/217713272-92167ab8-3363-4d24-8525-b1989c4b3206.png)

3. 查看自动生成的PipelineServingLogs，报错日志：
3.1 错误1：AttributeError: Can't pickle local object 'PipelineProcSyncManager.<locals>.PipelineManager'
ERROR 2023-02-09 11:37:34,765 [error_catch.py:125] 
Log_id: 0
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\error_catch.py", line 163, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\dag.py", line 520, in init_helper
    self._manager = PipelineProcSyncManager()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\util.py", line 142, in PipelineProcSyncManager
    m.start()
  File "D:\python\anaconda3\envs\paddleserving\lib\multiprocessing\managers.py", line 554, in start
    self._process.start()
  File "D:\python\anaconda3\envs\paddleserving\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\python\anaconda3\envs\paddleserving\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\python\anaconda3\envs\paddleserving\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\python\anaconda3\envs\paddleserving\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'PipelineProcSyncManager.<locals>.PipelineManager'

3.2 错误2：AttributeError: 'DAG' object has no attribute '_manager'
ERROR 2023-02-09 11:37:34,768 [error_catch.py:125] 
Log_id: 0
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\error_catch.py", line 163, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 51, in init_helper
    self._dag_executor = dag.DAGExecutor(response_op, dag_conf, worker_idx)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\dag.py", line 94, in __init__
    unpack_rpc_func) = self._dag.build()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\dag.py", line 828, in build
    unpack_func) = self._build_dag(self._response_op)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\dag.py", line 756, in _build_dag
    channel = self._gen_channel(channel_name_gen)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\paddle_serving_server\pipeline\dag.py", line 583, in _gen_channel
    self._manager,
AttributeError: 'DAG' object has no attribute '_manager'
Classname: PipelineServicer.__init__.<locals>.init_helper
FunctionName: init_helper

4. 完整日志如下：
[pipeline.log](https://github.com/PaddlePaddle/PaddleNLP/files/10693350/pipeline.log)

**Comment by lugimzzz** [comment]
paddleserving暂时不支持Windows，服务端部署QPS要求不高可以用simple serving，如果要求高可以用triton部署。paddleserving之后将不持续维护了

**Comment by MooTong123** [comment]
> paddleserving暂时不支持Windows，服务端部署QPS要求不高可以用simple serving，如果要求高可以用triton部署。paddleserving之后将不持续维护了

好的，请问有simple serving的详细文档吗？

**Comment by lugimzzz** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/deploy/simple_serving
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md

**Comment by MooTong123** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/deploy/simple_serving https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md

您好，请问下，如果不在当前目录启动server.py，比如在它的上级目录，那该如何书写命令？比如server.py 在./code 目录下，那该如何启动？

paddlenlp server ./code/server:app --host 0.0.0.0 --port 8189 --workers 1

还是通过 --app_dir？
paddlenlp server server:app --host 0.0.0.0 --port 8189 --workers 1 --app_dir ./code/

这么写都报错了

**Comment by wawltor** [comment]
是可以通过 --app_dir ./code/ 来实现，但是这里的模型路径要和--app_dir路径匹配

**Comment by MooTong123** [comment]
> 是可以通过 --app_dir ./code/ 来实现，但是这里的模型路径要和--app_dir路径匹配

还有一个问题想要问一下，现在部署成功后，返回的label是0,1,2,3等等，是否可以在哪里设置，直接返回对应的label名字，而不是序号？
![image](https://user-images.githubusercontent.com/44767255/218043802-efec91e3-2714-42c8-89cc-0f141c219c51.png)

**Comment by lugimzzz** [comment]
建议重写一下MultiClassificationPostHandler，或你做一些后处理映射一下
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/server/handlers/cls_post_handler.py

**Comment by MooTong123** [comment]
> 

好的，谢谢回答
