### ISSUE TITLE
无监督demo报错

### ISSUE THREAD

**Issue by zhangwei911** [PaddlePaddle/PaddleNLP#4712]
### 请提出你的问题

```
E:\Workspace\Python\PaddleNLP\applications\question_answering\unsupervised_qa>python run_pipelines_example.py --device gpu --source_file data/source_file.txt --doc_dir data/my_data --index_name faiss_index --retriever_batch_size 16
E:\SoftWare\Python\lib\site-packages\paddle\fluid\layers\utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
E:\SoftWare\Python\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
E:\SoftWare\Python\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
E:\SoftWare\Python\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
E:\SoftWare\Python\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
E:\SoftWare\Python\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
E:\SoftWare\Python\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
E:\SoftWare\Python\lib\site-packages\skimage\morphology\_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
E:\SoftWare\Python\lib\site-packages\skimage\morphology\_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
E:\SoftWare\Python\lib\site-packages\skimage\feature\_orb_descriptor_positions.py:8: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  POS = np.loadtxt(os.path.join(this_dir, "orb_descriptor_positions.txt"),
Traceback (most recent call last):
  File "run_pipelines_example.py", line 19, in <module>
    from pipelines.document_stores import FAISSDocumentStore
  File "E:\SoftWare\Python\lib\site-packages\pipelines\__init__.py", line 37, in <module>
    from pipelines import pipelines, utils
  File "E:\SoftWare\Python\lib\site-packages\pipelines\pipelines\__init__.py", line 15, in <module>
    from pipelines.pipelines.base import Pipeline, RootNode
  File "E:\SoftWare\Python\lib\site-packages\pipelines\pipelines\base.py", line 55, in <module>
    from pipelines.nodes.base import BaseComponent
  File "E:\SoftWare\Python\lib\site-packages\pipelines\nodes\__init__.py", line 15, in <module>
    from pipelines.utils.import_utils import safe_import  # isort: skip
  File "E:\SoftWare\Python\lib\site-packages\pipelines\utils\__init__.py", line 26, in <module>
    from pipelines.utils.export_utils import (print_answers, print_documents,
  File "E:\SoftWare\Python\lib\site-packages\pipelines\utils\export_utils.py", line 24, in <module>
    from pipelines.document_stores.sql import DocumentORM
  File "E:\SoftWare\Python\lib\site-packages\pipelines\document_stores\__init__.py", line 38, in <module>
    MilvusDocumentStore = safe_import("pipelines.document_stores.milvus2", "Milvus2DocumentStore", "milvus")
  File "E:\SoftWare\Python\lib\site-packages\pipelines\utils\import_utils.py", line 39, in safe_import
    module = importlib.import_module(import_path)
  File "E:\SoftWare\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\SoftWare\Python\lib\site-packages\pipelines\document_stores\milvus2.py", line 24, in <module>
    from pymilvus import FieldSchema, CollectionSchema, Collection, connections, utility
  File "E:\SoftWare\Python\lib\site-packages\pymilvus\__init__.py", line 13, in <module>
    from .client.stub import Milvus
  File "E:\SoftWare\Python\lib\site-packages\pymilvus\client\stub.py", line 3, in <module>
    from .grpc_handler import GrpcHandler
  File "E:\SoftWare\Python\lib\site-packages\pymilvus\client\grpc_handler.py", line 11, in <module>
    from ..grpc_gen import milvus_pb2_grpc
  File "E:\SoftWare\Python\lib\site-packages\pymilvus\grpc_gen\milvus_pb2_grpc.py", line 5, in <module>
    from . import common_pb2 as common__pb2
  File "E:\SoftWare\Python\lib\site-packages\pymilvus\grpc_gen\common_pb2.py", line 21, in <module>
    _ERRORCODE = DESCRIPTOR.enum_types_by_name['ErrorCode']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'
```

**Comment by westfish** [comment]
你好请问你安装的pipelines的版本是多少呀

**Comment by zhangwei911** [comment]
pip list|findstr pipelines
paddle-pipelines                   0.4.0

**Comment by zhangwei911** [comment]
pipelines是0.0.4,安装新版本报上面的错,是不是不支持win11
```
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/39/ca/1db6ebefdde0a7b5fb639ebc0527d8aab1cdc6119a8e4ac7c1c0cc222ec5/sh-1.11.tar.gz (36 kB)
          raise ImportError("sh %s is currently only supported on linux and osx. \
      ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
      [end of output]
```

**Comment by zhangwei911** [comment]
我换的linux下面了,运行就直接killed
```
(base) [root@VM-4-5-centos pipelines]# python examples/unsupervised-question-answering/unsupervised_question_answering_example.py --device cpu --source_file data/source_file.txt --doc_dir data/my_data
[2023-02-10 20:40:15,414] [    INFO] - loading configuration file /root/.paddlenlp/pipelines/unsupervised_question_answering/uie-base-answer-extractor/config.json
[2023-02-10 20:40:15,417] [    INFO] - Model config ErnieConfig {
  "architectures": [
    "UIE"
  ],
  "attention_probs_dropout_prob": 0.1,
  "enable_recompute": false,
  "fuse": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 2048,
  "model_type": "ernie",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "paddlenlp_version": null,
  "pool_act": "tanh",
  "task_id": 0,
  "task_type_vocab_size": 3,
  "type_vocab_size": 4,
  "use_task_id": true,
  "vocab_size": 40000
}

Killed
```
