### ISSUE TITLE
[Question]: 加载训练好的模型，出现严重问题

### ISSUE THREAD

**Issue by Amazing-J** [PaddlePaddle/PaddleNLP#4724]
### 请提出你的问题

/root/miniconda3/envs/paddle/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-02-09 17:02:08,571] [ WARNING] - Detected that datasets module was imported before paddlenlp. This may cause PaddleNLP datasets to be unavalible in intranet. Please import paddlenlp before datasets module to avoid download issues
Namespace(batch_size=128, decode_strategy='greedy_search', device='gpu', diversity_rate=0.0, early_stopping=False, faster=False, init_checkpoint_dir='/data/generation/summary/pegasus_out', length_penalty=0.6, logging_steps=100, max_source_length=512, max_target_length=64, min_target_length=0, num_beams=1, output_path='generate.txt', prefict_file='/data/generation/data/test_phrase_1/LCSTS_new/test_summary_1.json', seed=42, top_k=2, top_p=1.0, use_fp16_decoding=False)
W0209 17:02:09.057334 2335915 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.4
W0209 17:02:09.061172 2335915 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Using custom data configuration default-94c500f995f77272
Found cached dataset json (/root/.cache/huggingface/datasets/json/default-94c500f995f77272/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-94c500f995f77272/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-6b56910183f7fcfb.arrow
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/miniconda3/envs/paddle/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/paddle/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 138, in fetch
    data = self.collate_fn(data)
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/data/data_collator.py", line 383, in __call__
    decoder_input_ids = self.model.prepare_decoder_input_ids_from_labels(labels=features["labels"])
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/pegasus/modeling.py", line 675, in prepare_decoder_input_ids_from_labels
    return shift_tokens_right(labels, self.pegasus.pad_token_id, self.pegasus.config["decoder_start_token_id"])
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/pegasus/modeling.py", line 39, in shift_tokens_right
    shifted_input_ids[:, 1:] = input_ids[:, :-1].clone()
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 797, in __setitem__
    return self.__setitem_eager_tensor__(item, value)
RuntimeError: (NotFound) There are no kernels which are registered in the set_value operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:347)
  [operator < set_value > error]

**Comment by lugimzzz** [comment]
麻烦提供可复现代码、环境
