### ISSUE TITLE
[Bug]: 单卡训练uie保错FileNotFoundError: configuration file<config.json> or <model_config.json> not found

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#4726]
### 软件环境

```Markdown
- paddlepaddle:2.3.0
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
有些参数如训练集和测试集等设置为默认参数了，问下如题的原因
```

### 稳定复现步骤 & 代码

/root/anaconda3/envs/paddle_fei/bin/python3.9 finetune.py --device gpu --logging_steps 10 --save_steps 200 --eval_steps 200 --seed 42 --output_dir "./for_12345_address_checkpoint" --per_device_eval_batch_size 4 --per_device_train_batch_size 4 --num_train_epochs 100 --learning_rate 1e-5 --do_train --do_eval --do_export --export_model_dir "./for_12345_large_checkpoint" --label_names 'start_positions' 'end_positions' --overwrite_output_dir --disable_tqdm True --metric_for_best_model eval_f1 --load_best_model_at_end True --save_total_limit 1 --multilingual
/root/anaconda3/envs/paddle_fei/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-02-09 17:07:28,407] [ WARNING] - evaluation_strategy reset to IntervalStrategy.STEPS for do_eval is True. you can also set evaluation_strategy='epoch'.
[2023-02-09 17:07:28,407] [    INFO] - The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
[2023-02-09 17:07:28,407] [    INFO] - ============================================================
[2023-02-09 17:07:28,408] [    INFO] -      Model Configuration Arguments      
[2023-02-09 17:07:28,408] [    INFO] - paddle commit id              :4743cc8b9a8d77ea47e08a42a16246b538bda56f
[2023-02-09 17:07:28,408] [    INFO] - export_model_dir              :./for_12345_large_checkpoint
[2023-02-09 17:07:28,408] [    INFO] - model_name_or_path            :uie-base
[2023-02-09 17:07:28,408] [    INFO] - multilingual                  :True
[2023-02-09 17:07:28,409] [    INFO] - 
[2023-02-09 17:07:28,409] [    INFO] - ============================================================
[2023-02-09 17:07:28,409] [    INFO] -       Data Configuration Arguments      
[2023-02-09 17:07:28,409] [    INFO] - paddle commit id              :4743cc8b9a8d77ea47e08a42a16246b538bda56f
[2023-02-09 17:07:28,409] [    INFO] - dev_path                      :../data_for1234/data_for_address/dev.txt
[2023-02-09 17:07:28,409] [    INFO] - max_seq_length                :128
[2023-02-09 17:07:28,410] [    INFO] - train_path                    :../data_for1234/data_for_address/train.txt
[2023-02-09 17:07:28,410] [    INFO] - 
[2023-02-09 17:07:28,410] [ WARNING] - Process rank: -1, device: gpu, world_size: 1, distributed training: False, 16-bits training: False
[2023-02-09 17:07:28,410] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'uie-base'.
[2023-02-09 17:07:28,411] [    INFO] - Already cached /root/.paddlenlp/models/uie-base/ernie_3.0_base_zh_vocab.txt
[2023-02-09 17:07:28,452] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/uie-base/tokenizer_config.json
[2023-02-09 17:07:28,453] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/uie-base/special_tokens_map.json
Traceback (most recent call last):
  File "/usr/local/zx/uie/uie_new_2yue9ri/finetune.py", line 250, in <module>
    main()
  File "/usr/local/zx/uie/uie_new_2yue9ri/finetune.py", line 123, in main
    model = UIEM.from_pretrained(model_args.model_name_or_path)
  File "/root/anaconda3/envs/paddle_fei/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py", line 477, in from_pretrained
    return cls.from_pretrained_v2(pretrained_model_name_or_path, from_hf_hub=from_hf_hub, *args, **kwargs)
  File "/root/anaconda3/envs/paddle_fei/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py", line 1292, in from_pretrained_v2
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/root/anaconda3/envs/paddle_fei/lib/python3.9/site-packages/paddlenlp/transformers/configuration_utils.py", line 734, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/paddle_fei/lib/python3.9/site-packages/paddlenlp/transformers/configuration_utils.py", line 756, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/paddle_fei/lib/python3.9/site-packages/paddlenlp/transformers/configuration_utils.py", line 827, in _get_config_dict
    raise FileNotFoundError(f"configuration file<{CONFIG_NAME}> or <{LEGACY_CONFIG_NAME}> not found")
FileNotFoundError: configuration file<config.json> or <model_config.json> not found

**Comment by linjieccc** [comment]
@jiweizhangxu 你好，如果使用的是uie-base不需要指定``--multilingual``

**Comment by byy-git** [comment]
I got the same error. It's just that the model I'm using is uie-x-base. How do I solve this problem?

**Comment by laoding1974** [comment]
python tools/eval.py评估模型时也抱着错误，请问一下怎么解决
