### ISSUE TITLE
[Bug]: 安装报错: module 'cv2' has no attribute 'INTER_NEAREST'

### ISSUE THREAD

**Issue by puppyjuan** [PaddlePaddle/PaddleNLP#4734]
### 软件环境

```Markdown
- paddlepaddle: 
- paddlepaddle-gpu: 2.4.1.post117
- paddlenlp: 
python=3.8
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
按照WINDOWS环境下搭建端到端语义检索系统步骤执行到 python utils/offline_ann.py --index_name dureader_robust_query_encoder --doc_dir data/dureader_dev报错：

C:\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\anaconda3\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
C:\anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
C:\anaconda3\lib\site-packages\skimage\morphology\_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
C:\anaconda3\lib\site-packages\skimage\morphology\_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
Traceback (most recent call last):
  File "utils/offline_ann.py", line 17, in <module>
    from pipelines.document_stores import ElasticsearchDocumentStore, MilvusDocumentStore
  File "C:\anaconda3\lib\site-packages\pipelines\__init__.py", line 37, in <module>
    from pipelines import pipelines, utils
  File "C:\anaconda3\lib\site-packages\pipelines\pipelines\__init__.py", line 15, in <module>
    from pipelines.pipelines.base import Pipeline, RootNode
  File "C:\anaconda3\lib\site-packages\pipelines\pipelines\base.py", line 55, in <module>
    from pipelines.nodes.base import BaseComponent
  File "C:\anaconda3\lib\site-packages\pipelines\nodes\__init__.py", line 15, in <module>
    from pipelines.utils.import_utils import safe_import  # isort: skip
  File "C:\anaconda3\lib\site-packages\pipelines\utils\__init__.py", line 15, in <module>
    from pipelines.utils.preprocessing import convert_files_to_dicts, tika_convert_files_to_dicts
  File "C:\anaconda3\lib\site-packages\pipelines\utils\preprocessing.py", line 21, in <module>
    from pipelines.nodes.file_converter import BaseConverter, DocxToTextConverter, PDFToTextConverter, TextConverter, ImageToTextConverter
  File "C:\anaconda3\lib\site-packages\pipelines\nodes\file_converter\__init__.py", line 23, in <module>
    ImageToTextConverter = safe_import("pipelines.nodes.file_converter.image",
  File "C:\anaconda3\lib\site-packages\pipelines\utils\import_utils.py", line 39, in safe_import
    module = importlib.import_module(import_path)
  File "C:\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\anaconda3\lib\site-packages\pipelines\nodes\file_converter\image.py", line 22, in <module>
    from paddleocr import PaddleOCR
  File "C:\anaconda3\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "C:\anaconda3\lib\site-packages\paddleocr\paddleocr.py", line 37, in <module>
    from tools.infer import predict_system
  File "C:\anaconda3\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 33, in <module>
    import tools.infer.predict_det as predict_det
  File "C:\anaconda3\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 31, in <module>
    from ppocr.data import create_operators, transform
  File "C:\anaconda3\lib\site-packages\paddleocr\ppocr\data\__init__.py", line 35, in <module>
    from ppocr.data.imaug import transform, create_operators
  File "C:\anaconda3\lib\site-packages\paddleocr\ppocr\data\imaug\__init__.py", line 19, in <module>
    from .iaa_augment import IaaAugment
  File "C:\anaconda3\lib\site-packages\paddleocr\ppocr\data\imaug\iaa_augment.py", line 24, in <module>
    import imgaug
  File "C:\anaconda3\lib\site-packages\imgaug\__init__.py", line 7, in <module>
    from imgaug.imgaug import *  # pylint: disable=redefined-builtin
  File "C:\anaconda3\lib\site-packages\imgaug\imgaug.py", line 53, in <module>
    cv2.INTER_NEAREST, cv2.INTER_LINEAR, cv2.INTER_AREA, cv2.INTER_CUBIC]
AttributeError: module 'cv2' has no attribute 'INTER_NEAREST'
(base) PS C:\projects\PaddleNLP-develop\pipelines>
```

### 稳定复现步骤 & 代码

conda create -n nlp python=3.8
conda activate nlp
git clone https://github.com/tvst/htbuilder.git
cd htbuilder/
python setup install
python -m pip install paddlepaddle-gpu==2.4.1.post117 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
cd ${HOME}/PaddleNLP/pipelines/
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
python setup.py install
把文件config\elasticsearch.yml 里添加xpack.security.enabled: false, 然后直接双击bin目录下的elasticsearch.bat即可启动。

执行 python utils/offline_ann.py --index_name dureader_robust_query_encoder --doc_dir data/dureader_dev
报错

**Comment by w5688414** [comment]
用pip list查看，并贴一下您的python包的信息
