### ISSUE TITLE
[Question]: 文本分类的时候，分类标签有7051个，训练的时候直接报错

### ISSUE THREAD

**Issue by netidol** [PaddlePaddle/PaddleNLP#4757]
### 请提出你的问题

环境：Ubuntu 18.04、gpu、cuda 10.2、paddlenlp2.5.0
文本分类的时候，分类标签有7051个，训练的时候直接报错
训练命令：
python3 train.py     --model_name_or_path ernie-3.0-medium-zh     --data_dir ../data/     --output_dir checkpoint     --device gpu     --learning_rate 3e-5     --early_stopping_patience 4     --max_seq_length 128     --per_device_eval_batch_size 32     --per_device_train_batch_size 32     --num_train_epochs 100     --do_train     --do_eval     --metric_for_best_model accuracy     --load_best_model_at_end     --evaluation_strategy epoch     --save_strategy epoch     --save_total_limit 1
日志：
/root/anaconda3/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-02-11 12:44:33,272] [    INFO] - The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
[2023-02-11 12:44:33,272] [    INFO] - ============================================================
[2023-02-11 12:44:33,272] [    INFO] -      Model Configuration Arguments      
[2023-02-11 12:44:33,273] [    INFO] - paddle commit id              :4743cc8b9a8d77ea47e08a42a16246b538bda56f
[2023-02-11 12:44:33,273] [    INFO] - model_name_or_path            :ernie-3.0-medium-zh
[2023-02-11 12:44:33,273] [    INFO] - 
[2023-02-11 12:44:33,273] [    INFO] - ============================================================
[2023-02-11 12:44:33,273] [    INFO] -       Data Configuration Arguments      
[2023-02-11 12:44:33,273] [    INFO] - paddle commit id              :4743cc8b9a8d77ea47e08a42a16246b538bda56f
[2023-02-11 12:44:33,273] [    INFO] - data_dir                      :../data/
[2023-02-11 12:44:33,274] [    INFO] - early_stopping_patience       :4
[2023-02-11 12:44:33,274] [    INFO] - max_seq_length                :128
[2023-02-11 12:44:33,274] [    INFO] - 
True
False
Traceback (most recent call last):
  File "/usbdata/PaddleNLP/applications/text_classification/multi_class/train.py", line 137, in <module>
    main()
  File "/usbdata/PaddleNLP/applications/text_classification/multi_class/train.py", line 81, in main
    train_ds = load_dataset(
  File "/root/anaconda3/lib/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 190, in load_dataset
    return reader_instance.read(**custom_kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 772, in read
    return MapDataset(list(examples))
  File "/usbdata/PaddleNLP/applications/text_classification/multi_class/utils.py", line 53, in read_local_dataset
    yield {"text": sentence, "label": label_list[label]}
KeyError: '0 PASS'

**Comment by netidol** [comment]
补充一下，减少数量的话是正常的,所以否定环境的问题

**Comment by netidol** [comment]
找到问题了，是一个文本是只有数字0，看来代码的鲁棒性还需要加强
