### ISSUE TITLE
[Question]: SKEP模型，转换静态图export_model.py报错

### ISSUE THREAD

**Issue by MooTong123** [PaddlePaddle/PaddleNLP#4762]
### 请提出你的问题

1. 在skep模型里，用export_model.py转成静态图失败，报错。https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/sentiment_analysis/skep/export_model.py

2. 报错信息为：TypeError: float() argument must be a string or a number, not 'tuple'，我在源代码上print了一下报错位置：
![image](https://user-images.githubusercontent.com/44767255/218366477-06024a5b-ae52-46b4-a857-0cbc11f616f9.png)

3. 报错完整信息：

D:\python\anaconda3\envs\paddleserving\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
  
---------print报错------------------
value=0.0
type:<class 'float'>
value=(var layer_norm_97.tmp_2_slice_0 : LOD_TENSOR.shape(-1, 1024).dtype(float32).stop_gradient(False), var tanh_2.tmp_0 : LOD_TENSOR.shape(1024,).dtype(float32).stop_gradient(False))
type:<class 'tuple'>
---------print报错------------------

Traceback (most recent call last):
  File "D:\a1-workdir\workdir\notebook\python\SAI\SAI_function\deploy_model\nlp\utils\sentiment_analysis\export_model.py", line 45, in <module>
    paddle.jit.save(model, save_path)
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\dygraph\jit.py", line 631, in wrapper
    func(layer, path, input_spec, **configs)
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\dygraph\jit.py", line 860, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 527, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
TypeError: In transformed code:

    File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddlenlp\transformers\skep\modeling.py", line 572, in forward
	outputs = self.skep(input_ids,
    File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddlenlp\transformers\skep\modeling.py", line 462, in forward
        pooled_output = self.pooler(sequence_output)
        if not return_dict:
            return (sequence_output, pooled_output) + encoder_outputs[1:]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return BaseModelOutputWithPoolingAndCrossAttentions(
            last_hidden_state=sequence_output,

    File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 315, in __impl__
	other_var = create_scalar(
    File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 100, in create_scalar
	return create_tensor(block, value, dtype, shape=[1])
    File "D:\python\anaconda3\envs\paddleserving\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 84, in create_tensor
	value = float(value)

    TypeError: float() argument must be a string or a number, not 'tuple'


4. paddlepaddle=2.3.2, paddlenlp=2.4.4

**Comment by wawltor** [comment]
您好，你试试将PaddleNLP的版本升级到最新的2.5.0版本

**Comment by MooTong123** [comment]
> 您好，你试试将PaddleNLP的版本升级到最新的2.5.0版本

谢谢，升级到2.5就成功了。

**Comment by wawltor** [comment]
好的，我们暂时先关闭该issue，如有问题可以再打开该issue。
