### ISSUE TITLE
milvus.client.exceptions.NotConnectError: Cannot check server version: Error occurred. unknown service milvus.grpc.MilvusService

### ISSUE THREAD

**Issue by lichuantao6626** [PaddlePaddle/PaddleNLP#4799]
### 请提出你的问题

我在根据官方文档提供的文档搭建faq_system问答系统时，在向Milvus 系统插入向量时包了如下的错误：
(paddle_env2) [root@d53f1185523a faq_system]# python vector_insert.py
(5000, 256)
5000

Addr [192.168.11.219:19530] _cmd
Rpc error: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown service milvus.grpc.MilvusService"
	debug_error_string = "{"created":"@1676422543.942405670","description":"Error received from peer ipv4:192.168.11.219:19530","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"unknown service milvus.grpc.MilvusService","grpc_status":12}"
>
	{'API start': '2023-02-15 00:55:43.940495', 'RPC start': '2023-02-15 00:55:43.941239', 'RPC error': '2023-02-15 00:55:43.942671'}
Traceback (most recent call last):
  File "vector_insert.py", line 46, in <module>
    vector_insert(file_path)
  File "vector_insert.py", line 26, in vector_insert
    client = VecToMilvus()
  File "/opt/data/paddle20230203/PaddleNLP-develop/applications/question_answering/supervised_qa/faq_system/milvus_util.py", line 31, in __init__
    self.client = Milvus(host=MILVUS_HOST, port=MILVUS_PORT)
  File "/opt/data/anaconda3_0203/envs/paddle_env2/lib/python3.8/site-packages/milvus/client/stub.py", line 98, in __init__
    self._pool = SingletonThreadPool(pool_uri, **pool_kwargs)
  File "/opt/data/anaconda3_0203/envs/paddle_env2/lib/python3.8/site-packages/milvus/client/pool.py", line 226, in __init__
    self._prepare()
  File "/opt/data/anaconda3_0203/envs/paddle_env2/lib/python3.8/site-packages/milvus/client/pool.py", line 235, in _prepare
    raise NotConnectError("Cannot check server version: {}".format(status.message))
milvus.client.exceptions.NotConnectError: Cannot check server version: Error occurred. unknown service milvus.grpc.MilvusService

通过百度查阅了不少资料没找到解决问题的方法，请问这个问题怎么解决，感谢！

**Comment by w5688414** [comment]
1. faq system对应的是milvus 1.1.1，相应的pymilvus版本请参考链接：

https://github.com/milvus-io/pymilvus

2.检查一下是否用了代理。
