### ISSUE TITLE
[Bug]: ocr_process.py ocr结果处理异常

### ISSUE THREAD

**Issue by DayTimeDreamer** [PaddlePaddle/PaddleNLP#4801]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "/home/zhengzhenhong/paddlenlp/applications/document_intelligence/doc_vqa/OCR_process/ocr_process.py", line 277, in <module>
    process_input(ocr_results, tokenizer, save_path)
  File "/home/zhengzhenhong/paddlenlp/applications/document_intelligence/doc_vqa/OCR_process/ocr_process.py", line 240, in process_input
    ocr_reses = tokenize_ocr_res(ocr_reses)
  File "/home/zhengzhenhong/paddlenlp/applications/document_intelligence/doc_vqa/OCR_process/ocr_process.py", line 203, in tokenize_ocr_res
    x_min, y_min = [int(min(idx)) for idx in zip(*text_box)]
  File "/home/zhengzhenhong/paddlenlp/applications/document_intelligence/doc_vqa/OCR_process/ocr_process.py", line 203, in <listcomp>
    x_min, y_min = [int(min(idx)) for idx in zip(*text_box)]
TypeError: '<' not supported between instances of 'str' and 'list'

以下是para的打印数据：
{'text': [[288.0, 303.0], [638.0, 303.0], [638.0, 382.0], [288.0, 382.0]], 'bbox': [[[2530.0, 105.0], [2654.0, 105.0], [2654.0, 171.0], [2530.0, 171.0]], ('解锁', 0.993677020072937)]}
```

### 稳定复现步骤 & 代码

cd OCR_process/
python3 ocr_process.py
cd ..

**Comment by 1649759610** [comment]
感谢反馈，经排查，是由paddleOCR升级带来的不兼容问题，后续将进行升级。如急着使用，可以安装2.5版本的paddleOCR:

pip install paddleocr==2.5 -i https://pypi.tuna.tsinghua.edu.cn/simple/
