### ISSUE TITLE
[Docs]: docs/trainer.md

### ISSUE THREAD

**Issue by kehuo** [PaddlePaddle/PaddleNLP#4809]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 2.5.0
```

### 详细描述

```Markdown
paddlenlp trainer 目前支持 stage=3 的 Sharding 吗？
我看到 [trainer.md文档](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/trainer.md) 里写着目前不可用: "NOTICE： stage3 is temporarily unavaliable."

而且我自己训练NLP模型时，也确实在 loss.backward() 处遇到了如下报错。


Traceback (most recent call last):
  File "./example/run_train_model.py", line 183, in <module>
    main()
  File "./examples/run_train_model.py", line 176, in main
    trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/trainer.py", line 661, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/trainer.py", line 1324, in training_step
    loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 557, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 333, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
RuntimeError: (PermissionDenied) Tensor '' used in gradient computation has been modified by an inplace operation. Its version is 1 but the expected version is 0. Please fix your code to void calling an inplace operator after using the Tensor which will used in gradient computation.
  [Hint: Expected tensor_version == wrapper_version_snapshot, but received tensor_version:1 != wrapper_version_snapshot:0.] (at /paddle/paddle/fluid/eager/tensor_wrapper.h:214)



请PaddleNLP同学帮忙解答：
【1】目前trainer是否支持 stage3？如果支持，请问是否有示例代码？
【2】开启 sharding=stage3以后训练模型，出现以上报错是否正常？（注：相同代码，开启state2可以训练，但是换成stage3就失败了）。是否有排查建议？

期待回复
```

**Comment by ZHUI** [comment]
请PaddleNLP同学帮忙解答：
【1】目前trainer是否支持 stage3？如果支持，请问是否有示例代码？

目前初步接入了，还没有验证正确性，收敛性的，部分机制存在问题。预计下周看可以抽空验证一下。

【2】开启 sharding=stage3以后训练模型，出现以上报错是否正常？（注：相同代码，开启state2可以训练，但是换成stage3就失败了）。是否有排查建议？

建议先使用stage2。看报错，确实有有些用法可能存在问题，但也可能和Paddle版本有关。

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/4930 

做了一定完善，参见上面PR。 

> 其中 exclude_layer 设置 GroupNorm

上面报错是由于部分层不可以被 stage3 策略切分。参见这里的 exclude_layer 的例子。
