### ISSUE TITLE
[Bug]: TypeError: __init__() got an unexpected keyword argument 'num_choices'

### ISSUE THREAD

**Issue by scuyjzh** [PaddlePaddle/PaddleNLP#4818]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.3.1.post116
- paddlenlp: 2.5.0.post1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 478, in from_pretrained
    return cls.from_pretrained_v2(pretrained_model_name_or_path, from_hf_hub=from_hf_hub, *args, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 1335, in from_pretrained_v2
    model = cls(config, *init_args, **model_kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_choices'
```

### 稳定复现步骤 & 代码

from paddlenlp.transformers import BertForMultipleChoice

model = BertForMultipleChoice.from_pretrained("bert-base-chinese", num_choices=4)

**Comment by scuyjzh** [comment]
@wj-Mcat
