### ISSUE TITLE
动态图转静态图做预测时报错的问题

### ISSUE THREAD

**Issue by justiceeem** [PaddlePaddle/PaddleNLP#483]
模型转换代码：
```
    tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')
    pretrained_model = ppnlp.transformers.ErnieModel.from_pretrained(
        "ernie-1.0")

    model = Model(
        pretrained_model, output_emb_size=args.output_emb_size)

    if args.params_path and os.path.isfile(args.params_path):
        state_dict = paddle.load(args.params_path)
        model.set_dict(state_dict)
        print("Loaded parameters from %s" % args.params_path)
    model.eval()
    model = paddle.jit.to_static(
        model,
        input_spec=[
            paddle.static.InputSpec(
                shape=[None, None], dtype="int64"),  # input_ids
            paddle.static.InputSpec(
                shape=[None, None], dtype="int64")]  # segment_ids
    )

    paddle.jit.save(model, './models/static_graph')
```
模型：
```
class Model(SemanticIndexBase):
    def __init__(self,
                 pretrained_model,
                 dropout=None,
                 output_emb_size=None):
        super().__init__(pretrained_model, dropout, output_emb_size)

    def forward(self,
                query_input_ids,
                query_token_type_ids=None,
                query_position_ids=None,
                query_attention_mask=None,
                ):
        query_cls_embedding = self.get_pooled_embedding(
            query_input_ids, query_token_type_ids, query_position_ids,
            query_attention_mask)

        return query_cls_embedding
```
推理部分：
```
class Predictor(object):
    def __init__(self, model_file, params_file, device, max_seq_length):
        self.max_seq_length = max_seq_length

        config = paddle.inference.Config(model_file, params_file)
        if device == "gpu":
            # set GPU configs accordingly
            config.enable_use_gpu(100, 0)
        elif device == "cpu":
            # set CPU configs accordingly,
            # such as enable_mkldnn, set_cpu_math_library_num_threads
            config.disable_gpu()
        elif device == "xpu":
            # set XPU configs accordingly
            config.enable_xpu(100)
        config.switch_use_feed_fetch_ops(False)
        self.predictor = paddle.inference.create_predictor(config)

        self.input_handles = [
            self.predictor.get_input_handle(name)
            for name in self.predictor.get_input_names()
        ]

        self.output_handle = self.predictor.get_output_handle(
            self.predictor.get_output_names()[0])

    def predict(self, query, tokenizer, batch_size=1):
        embedding = []
        trans_func = partial(
            convert_example,
            tokenizer=tokenizer,
            max_seq_length=args.max_seq_length)

        batchify_fn = lambda samples, fn=Tuple(
            Pad(axis=0, pad_val=tokenizer.pad_token_id),  # text_input
            Pad(axis=0, pad_val=tokenizer.pad_token_type_id),  # text_segment
        ): [data for data in fn(samples)]

        query_ds = MapDataset(query)

        query_data_loader = create_dataloader(
            query_ds,
            mode='predict',
            batch_size=batch_size,
            batchify_fn=batchify_fn,
            trans_fn=trans_func)

        for batch_data in query_data_loader:
            input_ids, token_type_ids = batch_data
            input_ids = paddle.to_tensor(input_ids)
            token_type_ids = paddle.to_tensor(token_type_ids)
            self.input_handles[0].copy_from_cpu(input_ids)
            self.input_handles[1].copy_from_cpu(token_type_ids)
            self.predictor.run()
            query_embedding = self.output_handle.copy_to_cpu()

            embedding.append(query_embedding)

        return embedding

if __name__ == "__main__":
    predictor = Predictor(args.model_file, args.params_file, args.device, args.max_seq_length)

    tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')

    query = [{'text': '这里有bug！'}]

    embeddings = predictor.predict(query, tokenizer)

```
报错信息：
```
W0603 18:19:06.033704 16036 analysis_predictor.cc:677] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0603 18:19:06.034703 16036 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.
(NotFound) Cannot open file D:\models\static_graph.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at D:\v2.0.2\paddle\paddle\fluid\inference\api\analysis_predictor.cc:915)

Traceback (most recent call last):
  File "D:/tests/ex2.py", line 106, in <module>
    predictor = Predictor(args.model_file, args.params_file, args.device, args.max_seq_length)
  File "D:/tests/ex2.py", line 60, in __init__
    self.predictor = paddle.inference.create_predictor(config)
RuntimeError: Unknown exception
```
想要请教一下这种问题是不是因为模型转换的问题呢？有什么解决思路呢？谢谢！！

**Comment by wawltor** [comment]
看报错可能是模型路径不对了，
<img width="872" alt="图片" src="https://user-images.githubusercontent.com/16698950/120649011-dca3ad80-c4ae-11eb-9b65-b27d09d74547.png">

**Comment by justiceeem** [comment]
检查路径过后，能正确加载了。但是出现了新的报错，报错如下：
```
Traceback (most recent call last):
  File "D:/tests/ex2.py", line 112, in <module>
    embeddings = predictor.predict(query, tokenizer)
  File "D:/tests/ex2.py", line 95, in predict
    self.input_handles[0].copy_from_cpu(input_ids)
NotImplementedError: (Unimplemented) Invalid dimension to be accessed. Now only supports access to dimension 0 to 9, but received dimension is 32. (at D:\v2.0.2\paddle\paddle/fluid/framework/ddim.h:54)

```
@wawltor

**Comment by Steffy-zxf** [comment]
@justiceeem 你好！`NotImplementedError: (Unimplemented) Invalid dimension to be accessed. Now only supports access to dimension 0 to 9, but received dimension is 32.` 从错误信息看，应该是在数据在组batch的时候 维度出错了。需要具体看下 `convert_example()`函数的代码。

静态图预测参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/pretrained_models/deploy/python

**Comment by justiceeem** [comment]
convert_example代码如下：
```
def convert_example(example, tokenizer, max_seq_length=512):
    
    result = []
    for key, text in example.items():
        encoded_inputs = tokenizer(text=text, max_seq_len=max_seq_length)
        input_ids = encoded_inputs["input_ids"]
        token_type_ids = encoded_inputs["token_type_ids"]
        result += [input_ids, token_type_ids]
    return result
```
@Steffy-zxf 
不知道问题出在哪里...

**Comment by Steffy-zxf** [comment]
`convert_example()`返回有误，参考实现 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/deploy/python/predict.py#L37

**Comment by justiceeem** [comment]
谢谢！ @Steffy-zxf
