### ISSUE TITLE
[Question]: 使用SimpleServing部署UIE-X报错

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleNLP#4837]
### 请提出你的问题

paddlenlp 2.5.0
paddle 2.4.1
替换训练好的版面分析模型报错，在aistudio这个版面分析可以正常使用，使用SimpleServing后会出现下面的问题
`客户端错误`
PS D:\PythonCode\paddle> python client.py
C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "client.py", line 41, in <module>
    datas = json.loads(r.text)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\10613\.conda\envs\paddle_env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`服务端错误`
[2023-02-16 17:02:24,445] [    INFO] - The predictor id: 0 is selected by running the taskflow.
INFO:     127.0.0.1:9112 - "POST /taskflow/uie HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\starlette\applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddlenlp\server\http_router\router.py", line 104, in predict
    result = self._app._taskflow_manager.predict(inference_request.data, inference_request.parameters)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddlenlp\server\taskflow_manager.py", line 40, in predict
    return self._handler_func(self._task[task_index], data, parameters)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddlenlp\server\handlers\taskflow_handler.py", line 34, in process
    return predictor(text)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 603, in __call__
    results = self.task_instance(inputs)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddlenlp\taskflow\task.py", line 438, in __call__
    inputs = self._preprocess(*args)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 506, in _preprocess
    inputs = self._check_input_text(inputs)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 535, in _check_input_text
    data = self._parser_map[self._ocr_lang_choice].parse(
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddlenlp\utils\doc_parser.py", line 64, in parse
    ocr_result = self.ocr(image)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddlenlp\utils\doc_parser.py", line 126, in ocr
    layout_result = self.layout_analysis_engine(image)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddleocr\paddleocr.py", line 645, in __call__
    res, _ = super().__call__(
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 112, in __call__
    layout_res, elapse = self.layout_predictor(img)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddleocr\ppstructure\layout\predict_layout.py", line 100, in __call__
    post_preds = self.postprocess_op(ori_im, img, preds)
  File "C:\Users\10613\.conda\envs\paddle_env\lib\site-packages\paddleocr\ppocr\postprocess\picodet_postprocess.py", line 247, in __call__
    label = self.labels[clsid]
IndexError: list index out of range

**Comment by 1061302569** [comment]
已解决忘记修改lalbel文件了

**Comment by 1061302569** [comment]
已解决忘记修改lalbel文件了

**Comment by 1061302569** [comment]
已解决忘记修改lalbel文件了
