### ISSUE TITLE
[Question]: UIEX模型调优后，实体抽取没问题，但关系抽取时报错。

### ISSUE THREAD

**Issue by WangShunzhiDQ** [PaddlePaddle/PaddleNLP#4855]
### 请提出你的问题

schema = {
    '组': [
        '段',
        '底深',
        '厚度'
    ]
}
few_ie = Taskflow('information_extraction', schema=schema, task_path="./uie-x-base/model_best/checkpoint-225")
doc_path = "C:/Users/wangshunzhi/data/View (1).png"
res = few_ie({"doc": doc_path})
pprint(res)

from paddlenlp.utils.doc_parser import DocParser
DocParser.write_image_with_results(
        doc_path,
        result=res[0],
        save_path="./data/数据表标注后_show.png")

from PIL import Image
import matplotlib.pyplot as plt
img=Image.open("./data/数据表标注后_show.png")
plt.imshow(img)
plt.show()

错误：
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/wangshunzhi/PycharmProjects/pythonProject/Uie_demo.py", line 21, in <module>
    res = few_ie({"doc": doc_path})
  File "C:\ProgramData\Anaconda3\envs\pythonProject_UIE\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 592, in __call__
    results = self.task_instance(inputs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject_UIE\lib\site-packages\paddlenlp\taskflow\task.py", line 435, in __call__
    outputs = self._run_model(inputs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject_UIE\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 941, in _run_model
    results = self._multi_stage_predict(_inputs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject_UIE\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 1039, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "C:\ProgramData\Anaconda3\envs\pythonProject_UIE\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 851, in _single_stage_predict
    self.predictor.run()
RuntimeError: could not create a primitive descriptor for a reorder primitive

**Comment by WangShunzhiDQ** [comment]
![微信图片_20230217162012](https://user-images.githubusercontent.com/125637861/219592037-87c57c2e-37c8-4bf3-adee-a283b01b5dcb.PNG)
