### ISSUE TITLE
[Question]: 用自己的英文语料库预训练ernie1.0 报错

### ISSUE THREAD

**Issue by yhongzu** [PaddlePaddle/PaddleNLP#4949]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/preprocess/README.md
**按文档的要求准备好数据集后，训练时出现以下错误:**
```python
Traceback (most recent call last):
  File "run_pretrain_static.py", line 747, in <module>
    do_train(args)
  File "run_pretrain_static.py", line 588, in do_train
    ret = exe.run(main_program, feed=batch, fetch_list=fetchs, use_program_cache=True)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1699, in _run_impl
    return self._run_parallel(program._graph,
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1254, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
ValueError: In user code:

    File "run_pretrain_static.py", line 747, in <module>
      do_train(args)
    File "run_pretrain_static.py", line 440, in do_train
      prediction_scores, seq_relationship_score = model(
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 950, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 935, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddlenlp/transformers/ernie/modeling.py", line 904, in forward
      prediction_scores, seq_relationship_score = self.cls(sequence_output, pooled_output, masked_positions)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 950, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 935, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddlenlp/transformers/ernie/modeling.py", line 783, in forward
      prediction_scores = self.predictions(sequence_output, masked_positions)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 950, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 935, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddlenlp/transformers/ernie/modeling.py", line 764, in forward
      hidden_states = self.transform(hidden_states)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 950, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 935, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 175, in forward
      out = F.linear(
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 1907, in linear
      helper.append_op(
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/framework.py", line 4017, in append_op
      op = Operator(
    File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2858, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The Input(X) dims size must not be equal 0, but reviced dims size is 0. 
      [Hint: Expected phi::product(x.dims()) != 0, but received phi::product(x.dims()):0 == 0:0.] (at /paddle/paddle/phi/kernels/impl/matmul_kernel_impl.h:499)
      [operator < matmul_v2 > error]
```
**环境**
系统：Ubuntu 20.04
python: 3.8
paddlenlp: 2.5.0

**Comment by ZHUI** [comment]
好像数据维度不太对，你试试切换动态图版本的训练脚本呢？

**Comment by yhongzu** [comment]
三个训练脚本都试过了每次都会运行几百步，就出现这个错误。我用官网给出的悟道的小样本规模的数据集，也会出现同样的错误。

**Comment by ZHUI** [comment]
辛苦贴一下动态图的报错看一下？

**Comment by yhongzu** [comment]
```python
[32m[2023-02-23 09:46:24,800] [    INFO][0m - ***** Running training *****[0m
[32m[2023-02-23 09:46:24,800] [    INFO][0m -   Num examples = 1486822[0m
[32m[2023-02-23 09:46:24,800] [    INFO][0m -   Num Epochs = 1[0m
[32m[2023-02-23 09:46:24,800] [    INFO][0m -   Instantaneous batch size per device = 1[0m
[32m[2023-02-23 09:46:24,800] [    INFO][0m -   Total train batch size (w. parallel, distributed & accumulation) = 1[0m
[32m[2023-02-23 09:46:24,800] [    INFO][0m -   Gradient Accumulation steps = 1[0m
[32m[2023-02-23 09:46:24,800] [    INFO][0m -   Total optimization steps = 1000000[0m
[32m[2023-02-23 09:46:24,800] [    INFO][0m -   Total num train samples = 1000000[0m
[32m[2023-02-23 09:46:24,804] [    INFO][0m -   Number of trainable parameters = 118578498[0m
[32m[2023-02-23 09:46:27,311] [    INFO][0m - loss: 10.70859375, learning_rate: 2e-07, global_step: 20, interval_runtime: 2.5065, interval_samples_per_second: 7.979, interval_steps_per_second: 7.979, epoch: 0.0[0m
[32m[2023-02-23 09:46:28,399] [    INFO][0m - loss: 10.84414062, learning_rate: 4e-07, global_step: 40, interval_runtime: 1.0883, interval_samples_per_second: 18.378, interval_steps_per_second: 18.378, epoch: 0.0[0m
[32m[2023-02-23 09:46:29,453] [    INFO][0m - loss: 10.84101563, learning_rate: 6e-07, global_step: 60, interval_runtime: 1.0542, interval_samples_per_second: 18.972, interval_steps_per_second: 18.972, epoch: 0.0[0m
[32m[2023-02-23 09:46:30,501] [    INFO][0m - loss: 10.50703125, learning_rate: 8e-07, global_step: 80, interval_runtime: 1.0478, interval_samples_per_second: 19.087, interval_steps_per_second: 19.087, epoch: 0.0001[0m
[32m[2023-02-23 09:46:31,582] [    INFO][0m - loss: 10.43330078, learning_rate: 1e-06, global_step: 100, interval_runtime: 1.0811, interval_samples_per_second: 18.499, interval_steps_per_second: 18.499, epoch: 0.0001[0m
[32m[2023-02-23 09:46:32,639] [    INFO][0m - loss: 10.6453125, learning_rate: 1.2e-06, global_step: 120, interval_runtime: 1.0562, interval_samples_per_second: 18.935, interval_steps_per_second: 18.935, epoch: 0.0001[0m
[32m[2023-02-23 09:46:33,707] [    INFO][0m - loss: 10.04433594, learning_rate: 1.4e-06, global_step: 140, interval_runtime: 1.0688, interval_samples_per_second: 18.713, interval_steps_per_second: 18.713, epoch: 0.0001[0m
[32m[2023-02-23 09:46:34,795] [    INFO][0m - loss: 10.41367188, learning_rate: 1.6e-06, global_step: 160, interval_runtime: 1.088, interval_samples_per_second: 18.382, interval_steps_per_second: 18.382, epoch: 0.0001[0m
[32m[2023-02-23 09:46:35,865] [    INFO][0m - loss: 10.63085938, learning_rate: 1.8e-06, global_step: 180, interval_runtime: 1.0699, interval_samples_per_second: 18.693, interval_steps_per_second: 18.693, epoch: 0.0001[0m
[32m[2023-02-23 09:46:36,952] [    INFO][0m - loss: 10.36445313, learning_rate: 2e-06, global_step: 200, interval_runtime: 1.0869, interval_samples_per_second: 18.4, interval_steps_per_second: 18.4, epoch: 0.0001[0m
[32m[2023-02-23 09:46:38,002] [    INFO][0m - loss: 9.9234375, learning_rate: 2.2e-06, global_step: 220, interval_runtime: 1.0503, interval_samples_per_second: 19.043, interval_steps_per_second: 19.043, epoch: 0.0001[0m
[32m[2023-02-23 09:46:39,053] [    INFO][0m - loss: 9.54453125, learning_rate: 2.4e-06, global_step: 240, interval_runtime: 1.0508, interval_samples_per_second: 19.033, interval_steps_per_second: 19.033, epoch: 0.0002[0m
[32m[2023-02-23 09:46:40,114] [    INFO][0m - loss: 9.72851562, learning_rate: 2.6e-06, global_step: 260, interval_runtime: 1.0603, interval_samples_per_second: 18.862, interval_steps_per_second: 18.862, epoch: 0.0002[0m
[32m[2023-02-23 09:46:41,208] [    INFO][0m - loss: 9.20048828, learning_rate: 2.8e-06, global_step: 280, interval_runtime: 1.0941, interval_samples_per_second: 18.28, interval_steps_per_second: 18.28, epoch: 0.0002[0m
[32m[2023-02-23 09:46:42,294] [    INFO][0m - loss: 9.99453125, learning_rate: 3e-06, global_step: 300, interval_runtime: 1.0859, interval_samples_per_second: 18.417, interval_steps_per_second: 18.417, epoch: 0.0002[0m
[32m[2023-02-23 09:46:43,382] [    INFO][0m - loss: 9.8796875, learning_rate: 3.2e-06, global_step: 320, interval_runtime: 1.0881, interval_samples_per_second: 18.38, interval_steps_per_second: 18.38, epoch: 0.0002[0m
[32m[2023-02-23 09:46:44,451] [    INFO][0m - loss: 9.40332031, learning_rate: 3.4e-06, global_step: 340, interval_runtime: 1.0691, interval_samples_per_second: 18.707, interval_steps_per_second: 18.707, epoch: 0.0002[0m
[32m[2023-02-23 09:46:45,525] [    INFO][0m - loss: 9.5953125, learning_rate: 3.6e-06, global_step: 360, interval_runtime: 1.0742, interval_samples_per_second: 18.619, interval_steps_per_second: 18.619, epoch: 0.0002[0m
[32m[2023-02-23 09:46:46,589] [    INFO][0m - loss: 9.84960938, learning_rate: 3.8e-06, global_step: 380, interval_runtime: 1.0635, interval_samples_per_second: 18.806, interval_steps_per_second: 18.806, epoch: 0.0003[0m
[32m[2023-02-23 09:46:47,672] [    INFO][0m - loss: 9.59394531, learning_rate: 4e-06, global_step: 400, interval_runtime: 1.0837, interval_samples_per_second: 18.455, interval_steps_per_second: 18.455, epoch: 0.0003[0m
[32m[2023-02-23 09:46:48,773] [    INFO][0m - loss: 9.59257812, learning_rate: 4.2e-06, global_step: 420, interval_runtime: 1.1006, interval_samples_per_second: 18.172, interval_steps_per_second: 18.172, epoch: 0.0003[0m
[32m[2023-02-23 09:46:49,837] [    INFO][0m - loss: 9.00585938, learning_rate: 4.4e-06, global_step: 440, interval_runtime: 1.0645, interval_samples_per_second: 18.788, interval_steps_per_second: 18.788, epoch: 0.0003[0m
[32m[2023-02-23 09:46:50,926] [    INFO][0m - loss: 9.64042969, learning_rate: 4.6e-06, global_step: 460, interval_runtime: 1.0882, interval_samples_per_second: 18.379, interval_steps_per_second: 18.379, epoch: 0.0003[0m
[32m[2023-02-23 09:46:52,005] [    INFO][0m - loss: 9.02529297, learning_rate: 4.8e-06, global_step: 480, interval_runtime: 1.0789, interval_samples_per_second: 18.537, interval_steps_per_second: 18.537, epoch: 0.0003[0m
[32m[2023-02-23 09:46:53,065] [    INFO][0m - loss: 9.453125, learning_rate: 5e-06, global_step: 500, interval_runtime: 1.0602, interval_samples_per_second: 18.864, interval_steps_per_second: 18.864, epoch: 0.0003[0m
[32m[2023-02-23 09:46:54,121] [    INFO][0m - loss: 9.01054687, learning_rate: 5.2e-06, global_step: 520, interval_runtime: 1.0557, interval_samples_per_second: 18.946, interval_steps_per_second: 18.946, epoch: 0.0003[0m
[32m[2023-02-23 09:46:55,152] [    INFO][0m - loss: 8.55976563, learning_rate: 5.4e-06, global_step: 540, interval_runtime: 1.0316, interval_samples_per_second: 19.387, interval_steps_per_second: 19.387, epoch: 0.0004[0m
[32m[2023-02-23 09:46:56,237] [    INFO][0m - loss: 8.87089844, learning_rate: 5.6e-06, global_step: 560, interval_runtime: 1.0848, interval_samples_per_second: 18.437, interval_steps_per_second: 18.437, epoch: 0.0004[0m
[32m[2023-02-23 09:46:57,300] [    INFO][0m - loss: 8.93085938, learning_rate: 5.8e-06, global_step: 580, interval_runtime: 1.0633, interval_samples_per_second: 18.809, interval_steps_per_second: 18.809, epoch: 0.0004[0m
Traceback (most recent call last):
  File "run_pretrain_trainer.py", line 482, in <module>
    main()
  File "run_pretrain_trainer.py", line 469, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddlenlp/trainer/trainer.py", line 661, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddlenlp/trainer/trainer.py", line 1316, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddlenlp/trainer/trainer.py", line 1278, in compute_loss
    outputs = model(**inputs)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddlenlp/transformers/ernie/modeling.py", line 904, in forward
    prediction_scores, seq_relationship_score = self.cls(sequence_output, pooled_output, masked_positions)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddlenlp/transformers/ernie/modeling.py", line 783, in forward
    prediction_scores = self.predictions(sequence_output, masked_positions)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddlenlp/transformers/ernie/modeling.py", line 764, in forward
    hidden_states = self.transform(hidden_states)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 175, in forward
    out = F.linear(
  File "/home/yhongzu/anaconda3/envs/ernie1.0/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 1882, in linear
    return _C_ops.linear(x, weight, bias)
ValueError: (InvalidArgument) The Input(X) dims size must not be equal 0, but reviced dims size is 0. 
  [Hint: Expected phi::product(x.dims()) != 0, but received phi::product(x.dims()):0 == 0:0.] (at /paddle/paddle/phi/kernels/impl/matmul_kernel_impl.h:499)
  [operator < linear > error]
```

**Comment by ZHUI** [comment]
可以batch size弄大些吗？估计是有很短的句子，没有用对应的mask

**Comment by yhongzu** [comment]
可以运行了 谢谢。
我还有一个问题，就是ernie3.0论文上说是嵌入了知识图谱，但是我没有找到相应的代码。我想知道知识图谱是如何嵌入到模型的，我有一些本体，我想把本体放到ernie3.0上训练。

**Comment by ZHUI** [comment]
这步是在分词阶段做了。你可以用知识图谱构建相关的训练语料。保证你的实体都分词，切分在一起mask即可。

**Comment by yhongzu** [comment]
好的 明白了 谢谢！

**Comment by tiesanguaixia** [comment]
> 可以batch size弄大些吗？估计是有很短的句子，没有用对应的mask

您好！可以请教下ERNIE 1.0的phrase&named entity知识增强masking策略有开源实现的代码吗？是哪个文件呀
