### ISSUE TITLE
[Question]:ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by Han-YLun** [PaddlePaddle/PaddleNLP#4980]
error_info:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/workspace/main.py", line 3, in <module>
    from paddlenlp import Taskflow
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/__init__.py", line 45, in <module>
    from .server import SimpleServer
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/server/__init__.py", line 15, in <module>
    from .server import SimpleServer
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/server/server.py", line 16, in <module>
    from fastapi import FastAPI
  File "/usr/local/lib/python3.7/dist-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 15, in <module>
    from fastapi import routing
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/usr/local/lib/python3.7/dist-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 40, in init pydantic.dataclasses
ImportError: cannot import name dataclass_transform
```
version:
```
paddleocr==2.3.0.2
paddlenlp==2.4.9
paddlepaddle-gpu==2.3.2
```

**Comment by lugimzzz** [comment]
你是运行什么代码出现的问题？

**Comment by Han-YLun** [comment]
使用 Flask 开发的web接口项目

**Comment by wawltor** [comment]
可以参考这个issue https://github.com/ray-project/ray/issues/31227

**Comment by Han-YLun** [comment]
> 可以参考这个issue [ray-project/ray#31227](https://github.com/ray-project/ray/issues/31227)

目前这个问题解决了，现在我只使用了ocr的服务，然后出现这个日志

```
[2023-02-27 11:56:21 +0800] [296] [INFO] Booting worker with pid: 296
[2023-02-27 11:56:25,424] [ WARNING] - The schema has not been set yet, please set a schema via set_schema(). More details about the setting of schema please refer to https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/taskflow_text.md
[2023-02-27 11:56:28,693] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load './checkpoint/model_best'.
[2023/02/27 11:56:28] root WARNING: version PP-OCRv2 not support cls models, auto switch to version PP-OCR
WARNING 2023-02-27 11:56:28,727 paddleocr.py:269] version PP-OCRv2 not support cls models, auto switch to version PP-OCR
```
