### ISSUE TITLE
[Bug]: AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processors'. Did you mean: 'set_attn_processor'?

### ISSUE THREAD

**Issue by Yam0214** [PaddlePaddle/PaddleNLP#5019]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.4.1.post117
- paddlenlp: 2.5.1
- ppdiffusers: 0.11.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ouyanghongyu/anaconda3/envs/paddle2.4/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 1144, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processors'. Did you mean: 'set_attn_processor'?
```

### 稳定复现步骤 & 代码

[源码](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/ppdiffusers/models/unet_2d_condition.py#L291-L292)里存在 `attn_processors`属性，但是：

```python
>>> from ppdiffusers import UNet2DConditionModel
>>>
>>> unet = UNet2DConditionModel()
>>> unet.attn_processors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/paddle2.4/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1144, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processors'
```

而 HF 的 diffusers 中

```python
>>> from diffusers import UNet2DConditionModel
>>>
>>> unet = UNet2DConditionModel()
>>> unet.attn_processors
{'down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6e7fdc0>, 'down_blocks.0.attentions.0.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed40a0>, 'down_blocks.0.attentions.1.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed4550>, 'down_blocks.0.attentions.1.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed47f0>, 'down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed4df0>, 'down_blocks.1.attentions.0.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed5090>, 'down_blocks.1.attentions.1.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed5540>, 'down_blocks.1.attentions.1.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed57e0>, 'down_blocks.2.attentions.0.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed5de0>, 'down_blocks.2.attentions.0.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed6080>, 'down_blocks.2.attentions.1.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed6530>, 'down_blocks.2.attentions.1.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed67d0>, 'up_blocks.1.attentions.0.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec054130>, 'up_blocks.1.attentions.0.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec0543d0>, 'up_blocks.1.attentions.1.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec054940>, 'up_blocks.1.attentions.1.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec054be0>, 'up_blocks.1.attentions.2.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec055150>, 'up_blocks.1.attentions.2.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec0553f0>, 'up_blocks.2.attentions.0.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec055a80>, 'up_blocks.2.attentions.0.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec055d20>, 'up_blocks.2.attentions.1.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec056290>, 'up_blocks.2.attentions.1.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec056530>, 'up_blocks.2.attentions.2.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec056aa0>, 'up_blocks.2.attentions.2.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec056d40>, 'up_blocks.3.attentions.0.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec0573d0>, 'up_blocks.3.attentions.0.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec057670>, 'up_blocks.3.attentions.1.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec057be0>, 'up_blocks.3.attentions.1.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cec057e80>, 'up_blocks.3.attentions.2.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0c29fec430>, 'up_blocks.3.attentions.2.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0c29fec6d0>, 'mid_block.attentions.0.transformer_blocks.0.attn1.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed70d0>, 'mid_block.attentions.0.transformer_blocks.0.attn2.processor': <diffusers.models.cross_attention.CrossAttnProcessor object at 0x7f0cf6ed7370>}
```

**Comment by JunnYu** [comment]
@Yam0214 你好，这个功能是develop里面才有的，您当前看的代码都是develop里面的，0.11.0里面是没有 attn_processors 这个功能
