### ISSUE TITLE
[Question]: UIE-X 在 GPU 上 finetune 后，使用 CPU 加载出错

### ISSUE THREAD

**Issue by ViewWholeWorld** [PaddlePaddle/PaddleNLP#5038]
使用服务器上的 GPU 进行 Finetune 后，保存的模型参数可以正常在 GPU 加载预测出结果，但是将微调后的模型参数下载至本地使用 CPU加载，出现如下错误:
```
[2023-03-01 16:00:31,325] [    INFO] - We are using <class 'paddlenlp.transformers.ernie_layout.tokenizer.ErnieLayoutTokenizer'> to load './checkpoint/model_best'.
Traceback (most recent call last):
  File "/Users/mac/Documents/python/uie/text_uie.py", line 13, in <module>
    my_ie = Taskflow(
  File "/Users/mac/venv-repo/uie/lib/python3.8/site-packages/paddlenlp/taskflow/taskflow.py", line 590, in __init__
    self.task_instance = task_class(
  File "/Users/mac/venv-repo/uie/lib/python3.8/site-packages/paddlenlp/taskflow/information_extraction.py", line 445, in __init__
    self._construct_tokenizer()
  File "/Users/mac/venv-repo/uie/lib/python3.8/site-packages/paddlenlp/taskflow/information_extraction.py", line 496, in _construct_tokenizer
    self._tokenizer = AutoTokenizer.from_pretrained(
  File "/Users/mac/venv-repo/uie/lib/python3.8/site-packages/paddlenlp/transformers/auto/tokenizer.py", line 314, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/Users/mac/venv-repo/uie/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 1576, in from_pretrained
    tokenizer = cls(*init_args, **init_kwargs)
  File "/Users/mac/venv-repo/uie/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/Users/mac/venv-repo/uie/lib/python3.8/site-packages/paddlenlp/transformers/ernie_layout/tokenizer.py", line 96, in __init__
    self.sp_model.Load(sentencepiece_model_file)
  File "/Users/mac/venv-repo/uie/lib/python3.8/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/Users/mac/venv-repo/uie/lib/python3.8/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: /Users/runner/work/sentencepiece/sentencepiece/src/sentencepiece_processor.cc(1102) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
Process finished with exit code 1
```

服务器系统：CentOS Linux release 7.5.1804 (Core)，paddlepaddle-gpu==2.4.1.post112，paddlenlp==2.5.0
本地系统：MacOS 11.5.2, paddlepaddle==2.4.1，paddlenlp==2.5.0

加载模型代码如下：
```python
from paddlenlp import Taskflow
schema = ["证书类型"]
doc_path = "./03.png"
my_ie = Taskflow(
    "information_extraction",
    schema=schema,
    task_path="./checkpoint/model_best"
)
results = my_ie({"doc": doc_path})
print(results)
```

**Comment by linjieccc** [comment]
@ViewWholeWorld 你好，可以排查下是否是checkpoint/model_best/目录下的tokenizer相关文件有损坏呢

**Comment by ViewWholeWorld** [comment]
> @ViewWholeWorld 你好，可以排查下是否是checkpoint/model_best/目录下的tokenizer相关文件有损坏呢

感谢您的回复，我去检查了一下文件的sha1 值，确实是因为文件在传输过程中损坏了，tabby 这个 terminal 直接使用 sz 下载就会导致这个问题，改用 sz -8be 文件的 sha1 值就一致了
