### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jiyuwangbupt** [PaddlePaddle/PaddleNLP#5043]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 2.5.1
Tesla p40, cuda10.2, cudnn7.6.5
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
seg = Taskflow("word_segmentation")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luban/anaconda3/envs/smoking/lib/python3.8/site-packages/paddlenlp/taskflow/taskflow.py", line 696, in __init__
    self.task_instance = task_class(
  File "/home/luban/anaconda3/envs/smoking/lib/python3.8/site-packages/paddlenlp/taskflow/word_segmentation.py", line 121, in __init__
    super().__init__(task=task, model="lac", **kwargs)
  File "/home/luban/anaconda3/envs/smoking/lib/python3.8/site-packages/paddlenlp/taskflow/lexical_analysis.py", line 120, in __init__
    self._get_inference_model()
  File "/home/luban/anaconda3/envs/smoking/lib/python3.8/site-packages/paddlenlp/taskflow/task.py", line 329, in _get_inference_model
    self._prepare_static_mode()
  File "/home/luban/anaconda3/envs/smoking/lib/python3.8/site-packages/paddlenlp/taskflow/task.py", line 211, in _prepare_static_mode
    self.predictor = paddle.inference.create_predictor(self._config)
OSError: (External) CUDA error(709), context is destroyed.
  [Hint: Please search for the error code(709) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/fluid/platform/device/gpu/gpu_info.cc:142)
```

### 稳定复现步骤 & 代码

![image](https://user-images.githubusercontent.com/37127150/222096141-9a0884f0-26f5-47ae-b549-74be25f2e03c.png)

**Comment by wawltor** [comment]
这个是PaddlePaddle的GPU版本安装有问题，建议使用conda来安装 
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/16698950/222101341-b9ef9c77-f227-41d3-8d18-62f89a1e52ed.png">

**Comment by jiyuwangbupt** [comment]
> 这个是PaddlePaddle的GPU版本安装有问题，建议使用conda来安装 <img alt="image" width="1019" src="https://user-images.githubusercontent.com/16698950/222101341-b9ef9c77-f227-41d3-8d18-62f89a1e52ed.png">

重新安装试了，很奇怪，第一次没问题，第二次运行就报这个错误。
![image](https://user-images.githubusercontent.com/37127150/222153516-3a4c9005-ce5c-4cef-9c46-7b921d790441.png)
![image](https://user-images.githubusercontent.com/37127150/222153871-0dd91b59-2283-4003-818d-8b6c28e607c9.png)

**Comment by wawltor** [comment]
看看是不是显存不够？

**Comment by jiyuwangbupt** [comment]
> 看看是不是显存不够？
非常的神奇。。一会儿可以一会儿不可以。看着不像是显存不够。
![image](https://user-images.githubusercontent.com/37127150/222155398-08c8ea4c-ebd1-444f-b793-78f71eeb6fe8.png)
![image](https://user-images.githubusercontent.com/37127150/222155539-97432129-7573-4398-b30f-5dc782b9c4e9.png)

**Comment by jiyuwangbupt** [comment]
> 看看是不是显存不够？
显存12G
![image](https://user-images.githubusercontent.com/37127150/222155859-96eafc29-d3f5-4c96-929a-bebe0d1bba83.png)

**Comment by jiyuwangbupt** [comment]
> 看看是不是显存不够？

额。前两条命令失败了ie = Taskflow('information_extraction', schema=schema)
tag = Taskflow("pos_tagging")
第三条ner = Taskflow("ner")成功了之后
ie = Taskflow('information_extraction', schema=schema)又成功了。。
![image](https://user-images.githubusercontent.com/37127150/222158440-c17a4ac3-b8ff-4d0d-9f72-856bc7377eb2.png)
![image](https://user-images.githubusercontent.com/37127150/222158590-c5bb3823-d039-4398-926e-a5e7588e1b7c.png)
