### ISSUE TITLE
[Question]: zero_shot_text_classification任务使用定制模型一键预测错误

### ISSUE THREAD

**Issue by Graduo** [PaddlePaddle/PaddleNLP#5142]
### 请提出你的问题

使用时taskflow报错
预测代码
```
from pprint import pprint
from paddlenlp import Taskflow
schema = ["病情诊断", "治疗方案", "病因分析", "指标解读", "就医建议", "疾病表述", "后果表述", "注意事项", "功效作用", "医疗费用", "其他"]
my_cls = Taskflow("zero_shot_text_classification", model="utc-base", schema=schema, task_path='./checkpoint/model_best/plm', precision="fp16")
pprint(my_cls("中性粒细胞比率偏低"))
```
报错信息
```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2804: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2804: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.7/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-03-08 01:26:30,860] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'utc-base'.
[2023-03-08 01:26:30,861] [    INFO] - Already cached /root/.paddlenlp/models/utc-base/utc-base/utc_base_vocab.txt
[2023-03-08 01:26:30,889] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/utc-base/utc-base/tokenizer_config.json
[2023-03-08 01:26:30,889] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/utc-base/utc-base/special_tokens_map.json
[2023-03-08 01:26:30,890] [    INFO] - Assigning ['[O-MASK]'] to the additional_special_tokens key of the tokenizer
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./checkpoint/model_best/plm/static/inference.pdmodel
[Paddle2ONNX] Paramters file path: ./checkpoint/model_best/plm/static/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,select_input,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)
```
使用包的版本
paddlenlp            2.5.1
paddlepaddle-gpu     2.3.0.post112
paddle2onnx          1.0.5
onnx                 1.13.1
onnxconverter-common 1.13.0
onnxruntime-gpu      1.14.1
docker 版本 paddlecloud/paddlenlp:develop-gpu-cuda11.2-cudnn8-latest

**Comment by LemonNoel** [comment]
paddlepaddle版本请更新到最新版本2.4.2，然后重新导出模型

**Comment by Graduo** [comment]
> paddlepaddle版本

好的，我试一下

**Comment by Graduo** [comment]
> paddlepaddle版本请更新到最新版本2.4.2，然后重新导出模型
您好，升级到2.4.2后报如下错误
'''
[2023-03-17 11:54:06,510] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'utc-base'.
[2023-03-17 11:54:06,510] [    INFO] - Already cached /root/.paddlenlp/models/utc-base/utc-base/utc_base_vocab.txt
[2023-03-17 11:54:06,537] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/utc-base/utc-base/tokenizer_config.json
[2023-03-17 11:54:06,538] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/utc-base/utc-base/special_tokens_map.json
[2023-03-17 11:54:06,539] [    INFO] - Assigning ['[O-MASK]'] to the additional_special_tokens key of the tokenizer
2023-03-17 11:54:09.108197568 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer 'p2o.helper.constant.323'. It is not used by any node and should be removed from the model.
2023-03-17 11:54:09.108244078 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer 'p2o.helper.constant.314'. It is not used by any node and should be removed from the model.
2023-03-17 11:54:09.153486735 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence can't constant fold Mul node 'p2o.Mul.0'
2023-03-17 11:54:09.209863018 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence can't constant fold Mul node 'p2o.Mul.0'
2023-03-17 11:54:09.252723491 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence can't constant fold Mul node 'p2o.Mul.0'
2023-03-17 11:54:09.340085562 [W:onnxruntime:, session_state.cc:1136 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-03-17 11:54:09.340105312 [W:onnxruntime:, session_state.cc:1138 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
Traceback (most recent call last):
  File "/root/utc_test.py", line 20, in <module>
    pprint(my_cls("中性粒细胞比率偏低"))
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/taskflow.py", line 709, in __call__
    results = self.task_instance(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/task.py", line 468, in __call__
    results = self._postprocess(outputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/zero_shot_text_classification.py", line 398, in _postprocess
    if class_score > self._pred_threshold:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
'''

**Comment by Graduo** [comment]
> paddlepaddle版本请更新到最新版本2.4.2，然后重新导出模型

您好，已解决
