### ISSUE TITLE
[Bug]: mt5-base报错

### ISSUE THREAD

**Issue by Amy234543** [PaddlePaddle/PaddleNLP#5158]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.3.2.post112
- paddlenlp: 是git clone的最新版git clone https://github.com/PaddlePaddle/PaddleNLP.git
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "mt5_test.py", line 5, in <module>
    model = MT5ForConditionalGeneration.from_pretrained(model_name)
  File "/var/www/translate_mt5_paddle/paddlenlp/PaddleNLP/paddlenlp/transformers/model_utils.py", line 485, in from_pretrained
    pretrained_model_name_or_path, from_hf_hub=from_hf_hub, subfolder=subfolder, *args, **kwargs
  File "/var/www/translate_mt5_paddle/paddlenlp/PaddleNLP/paddlenlp/transformers/model_utils.py", line 1326, in from_pretrained_v2
    **kwargs,
  File "/var/www/translate_mt5_paddle/paddlenlp/PaddleNLP/paddlenlp/transformers/configuration_utils.py", line 735, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/var/www/translate_mt5_paddle/paddlenlp/PaddleNLP/paddlenlp/transformers/configuration_utils.py", line 762, in get_config_dict
    pretrained_model_name_or_path, cache_dir=cache_dir, from_hf_hub=from_hf_hub, **kwargs
  File "/var/www/translate_mt5_paddle/paddlenlp/PaddleNLP/paddlenlp/transformers/configuration_utils.py", line 836, in _get_config_dict
    raise FileNotFoundError(f"configuration file<{CONFIG_NAME}> or <{LEGACY_CONFIG_NAME}> not found")
FileNotFoundError: configuration file<config.json> or <model_config.json> not found
```

### 稳定复现步骤 & 代码

from paddlenlp.transformers import MT5ForConditionalGeneration, T5Tokenizer
model_name = "google/mt5-base"

model = MT5ForConditionalGeneration.from_pretrained(model_name)
model.eval()

**Comment by gongel** [comment]
你好，已定位问题，我们正在上传mt5-base的权重哈。

**Comment by gongel** [comment]
已解决

**Comment by Amy234543** [comment]
@gongel  mt5-base模型什么时候能加速呢

**Comment by gongel** [comment]
@Amy234543 mt5和t5结构完全一致，可以参考t5修改一下。

**Comment by Amy234543** [comment]
@gongel  t5支持动转静了吗？我试了报错，mt5自己写加速  ops/fast_transformer/transformer/fast_transformer.py 中加一个FasterMT5 class      在decoding.py中加InferMT5Decoding class  还有哪些需要加呀  generation_utils.py 里加速没生效，动转静报错没有self.slf_ln_weight 属性

**Comment by Amy234543** [comment]
![108cc1eb5305797fa90b49cd8f41f8f](https://user-images.githubusercontent.com/107381937/227179793-9d9f7854-cb93-4377-ae8a-90093b4a54e4.png)
mt5  fastgeneration 的加速按照t5的实现，现在报这个错，指定什么原因吗 @gongel

**Comment by gongel** [comment]
> ![108cc1eb5305797fa90b49cd8f41f8f](https://user-images.githubusercontent.com/107381937/227179793-9d9f7854-cb93-4377-ae8a-90093b4a54e4.png) mt5 fastgeneration 的加速按照t5的实现，现在报这个错，指定什么原因吗 @gongel

收到，你方便提个PR上来不？我看下你的代码，可参考t5的PR：https://github.com/PaddlePaddle/PaddleNLP/pull/3763 @Amy234543
