### ISSUE TITLE
[Question]: 数据蒸馏使用doccano标注的数据无法运行

### ISSUE THREAD

**Issue by adatwfx** [PaddlePaddle/PaddleNLP#5176]
### 请提出你的问题

使用doccano标注完数据后，导出的数据格式如下：
{"id": 1, "data": "xxxxxx", "label": [[0, 2, "schema1"], [15, 18, "schema2"], [19, 23, "schema3"]]}
用data_distill.py进行第一步处理时，代码中解析数据的格式跟上面列出的不一致。
参考页面：
https://github.com/PaddlePaddle/PaddleNLP/tree/a13e8776d2032f8e1fbac0958a7d2109fe61b10c/applications/information_extraction/text/data_distill

**Comment by linjieccc** [comment]
@adatwfx 你好，请尝试下执行`data_distill.py`时加上`--platform doccano`

**Comment by adatwfx** [comment]
> @adatwfx 你好，请尝试下执行`data_distill.py`时加上`--platform doccano`

我一开始就加了没用，应该是因为doccano平台各个版本导出的数据格式不一样，所以我在本地改了
https://github.com/PaddlePaddle/PaddleNLP/blob/a13e8776d2032f8e1fbac0958a7d2109fe61b10c/applications/information_extraction/text/data_distill/utils.py#L387
![1](https://user-images.githubusercontent.com/109333832/224237226-b92ffc9f-6f67-4234-acf3-59646630817c.png)

这个方法的代码，可以解析成功了。现在我已经跑通了老师模型的评估，在进行老师模型评估时，我传递的--model_path参数是我之前训练好的模型（https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie 用的这里的UIE小样本定制训练，基于uie-nano）下面是老师模型的评估结果：
![image](https://user-images.githubusercontent.com/109333832/224237165-29350ce3-1139-47c6-a841-03cd694ea895.png)

。但在后续的学生模型训练时，--encoder 参数我继续传入 uie-nano，却遇到下面的错误：
![image](https://user-images.githubusercontent.com/109333832/224237837-3f6ab567-11fe-4bc7-ac42-320ab8e55aea.png)
经查找相关代码后，我发现是下面的代码出了问题：
![image](https://user-images.githubusercontent.com/109333832/224238195-a955d405-723b-459e-870a-4d840417af07.png)
这里读取我本地uie-nano模型的配置文件，配置文件内容如下：
{"init_args": [{"attention_probs_dropout_prob": 0.1, "hidden_act": "gelu", "hidden_dropout_prob": 0.1, "hidden_size": 312, "intermediate_size": 1248, "initializer_range": 0.02, "max_position_embeddings": 2048, "num_attention_heads": 12, "num_hidden_layers": 4, "task_type_vocab_size": 16, "type_vocab_size": 4, "use_task_id": true, "vocab_size": 40000, "init_class": "ErnieModel"}], "init_class": "UIE"}
代码直接读取了外层的"init_class": "UIE" 去动态匹配类名，结果没有匹配到任何类名，导致model_name变量没有被赋值。请问是这个模型配置文件有问题吗？（这是自动下载下来的）
还是这里训练学生模型时，不支持uie-nano？

**Comment by linjieccc** [comment]
UIE目前还不支持使用AutoModel加载，如果使用UIE作为学生模型，这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/data_distill/train.py#L74

需要修改为：

```
from paddlenlp.transformers import UIE

encoder = UIE.from_pretrained(args.encoder)
```

**Comment by adatwfx** [comment]
> UIE目前还不支持使用AutoModel加载，如果使用UIE作为学生模型，这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/data_distill/train.py#L74
> 
> 需要修改为：
> 
> ```python
> from paddlenlp.transformers import UIE
> 
> encoder = UIE.from_pretrained(args.encoder)
> ```

多谢解答。问题已解决

**Comment by adatwfx** [comment]
数据蒸馏后的模型如何使用fastdeploy方式进行服务化部署？参考了下面文档，没有看到跟fastdeploy相关的特定说明
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/text/uie/serving

**Comment by adatwfx** [comment]
> UIE目前还不支持使用AutoModel加载，如果使用UIE作为学生模型，这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/data_distill/train.py#L74
> 
> 需要修改为：
> 
> ```python
> from paddlenlp.transformers import UIE
> 
> encoder = UIE.from_pretrained(args.encoder)
> ```
我使用paddle2.4版本时，`from paddlenlp.transformers import UIE ` 出错，这个版本的包没有UIE，所以我将paddle升级到了2.5.2版本，但是训练学生模型时，出现下面的错误：
`Traceback (most recent call last):
  File "train.py", line 191, in <module>
    do_train()
  File "train.py", line 112, in do_train
    logits = model(input_ids, attention_masks)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddlenlp\layers\globalpointer.py", line 90, in forward
    entity_output = self.entity_output(last_hidden_state, attention_mask)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddlenlp\layers\globalpointer.py", line 52, in forward
    inputs = self.dense1(inputs)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddle\nn\layer\common.py", line 176, in forward
    x=input, weight=self.weight, bias=self.bias, name=self.name
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddle\nn\functional\common.py", line 1886, in linear
    return _C_ops.linear(x, weight, bias)
ValueError: (InvalidArgument) Input(Y) has error dim.Y'dims[0] must be equal to 132But received Y'dims[0] is 312
  [Hint: Expected y_dims[y_ndim - 2] == K, but received y_dims[y_ndim - 2]:312 != K:132.] (at ..\paddle/phi/kernels/impl/matmul_kernel_impl.h:314)
  [operator < linear > error]`
请问这是什么原因导致的？

**Comment by adatwfx** [comment]
> UIE目前还不支持使用AutoModel加载，如果使用UIE作为学生模型，这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/data_distill/train.py#L74
> 
> 需要修改为：
> 
> ```python
> from paddlenlp.transformers import UIE
> 
> encoder = UIE.from_pretrained(args.encoder)
> ```

按照你的修改办法，我修改了代码，但是运行时出现下面错误：
```
Traceback (most recent call last):
  File "D:/PycharmProjects/address_uie/data_distill/train.py", line 191, in <module>
    do_train()
  File "D:/PycharmProjects/address_uie/data_distill/train.py", line 77, in do_train
    model = GlobalPointerForEntityExtraction(encoder, label_maps)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddlenlp\layers\globalpointer.py", line 82, in __init__
    hidden_size = encoder.config["hidden_size"]
KeyError: 'hidden_size'
```
paddlenlp 版本 2.4.5
paddlepaddle 版本 2.4.0
@linjieccc

**Comment by linjieccc** [comment]
更新paddlenlp到最新版本再试下呢

**Comment by adatwfx** [comment]
我把paddlenlp升级到了最新的2.5.2版本，同样有错误
```
[2023-03-14 10:25:13,067] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'uie-nano'.
[2023-03-14 10:25:13,067] [    INFO] - Already cached C:\Users\admin\.paddlenlp\models\uie-nano\ernie_3.0_nano_zh_vocab.txt
[2023-03-14 10:25:13,078] [    INFO] - tokenizer config file saved in C:\Users\admin\.paddlenlp\models\uie-nano\tokenizer_config.json
[2023-03-14 10:25:13,088] [    INFO] - Special tokens file saved in C:\Users\admin\.paddlenlp\models\uie-nano\special_tokens_map.json
[2023-03-14 10:25:13,088] [    INFO] - Model config ErnieConfig {
  "attention_probs_dropout_prob": 0.1,
  "enable_recompute": false,
  "fuse": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 312,
  "initializer_range": 0.02,
  "intermediate_size": 1248,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 2048,
  "model_type": "ernie",
  "num_attention_heads": 12,
  "num_hidden_layers": 4,
  "pad_token_id": 0,
  "paddlenlp_version": null,
  "pool_act": "tanh",
  "task_id": 0,
  "task_type_vocab_size": 16,
  "type_vocab_size": 4,
  "use_task_id": true,
  "vocab_size": 40000
}

[2023-03-14 10:25:15,514] [    INFO] - All model checkpoint weights were used when initializing UIE.

[2023-03-14 10:25:15,514] [    INFO] - All the weights of UIE were initialized from the model checkpoint at uie-nano.
If your task is similar to the task the model of the checkpoint was trained on, you can already use UIE for predictions without further training.
Traceback (most recent call last):
  File "D:/PycharmProjects/address_uie/data_distill/train.py", line 191, in <module>
    do_train()
  File "D:/PycharmProjects/address_uie/data_distill/train.py", line 112, in do_train
    logits = model(input_ids, attention_masks)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddlenlp\layers\globalpointer.py", line 90, in forward
    entity_output = self.entity_output(last_hidden_state, attention_mask)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddlenlp\layers\globalpointer.py", line 52, in forward
    inputs = self.dense1(inputs)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddle\nn\layer\common.py", line 176, in forward
    x=input, weight=self.weight, bias=self.bias, name=self.name
  File "D:\PycharmProjects\address_uie\venv\lib\site-packages\paddle\nn\functional\common.py", line 1882, in linear
    return _C_ops.linear(x, weight, bias)
ValueError: (InvalidArgument) Input(Y) has error dim.Y'dims[0] must be equal to 132But received Y'dims[0] is 312
  [Hint: Expected y_dims[y_ndim - 2] == K, but received y_dims[y_ndim - 2]:312 != K:132.] (at C:\home\workspace\Paddle\paddle/phi/kernels/impl/matmul_kernel_impl.h:314)
  [operator < linear > error]
```

**Comment by linjieccc** [comment]
确认了下，2.5.2版本可以直接AutoModel.from_pretrained(args.encoder)来加载uie-nano，我这边验证了没有问题~

**Comment by adatwfx** [comment]
> 确认了下，2.5.2版本可以直接AutoModel.from_pretrained(args.encoder)来加载uie-nano，我这边验证了没有问题~

确实可以，现在学生模型已经可以训练了。
还有一个问题请解答一下，蒸馏后的模型如何通过fastdeploy进行服务化部署？我参考了下面的文档，但是里面都需要传递schema参数，而蒸馏后的模型是不需要传递schema参数的。
[UIE fastdeploy部署示例](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/text/uie/serving/README_CN.md)

**Comment by linjieccc** [comment]
你好，Global Pointer目前还不支持FastDeploy部署

**Comment by adatwfx** [comment]
GlobalPointerForEntityExtraction 这个我不明白它的作用，经过UIE小样本训练的模型可以直接部署到fastdeploy，为什么蒸馏后就不能了呢？不明白其中的逻辑，能否解释一下？后期Global Pointer是否会支持FastDeploy部署呢？
