### ISSUE TITLE
关于paddlenlp 中uie模型压缩的出错

### ISSUE THREAD

**Issue by song4875343** [PaddlePaddle/PaddleNLP#5233]
环境 win10 paddlepaddle-gpu    2.4.2.post112   paddleslim    2.4.1 paddlenlp 2.5.1 cuda11.2 parl     2.2.1（最新版）__inint__.py没找到
import name 'layers' from 'parl'
单纯uie微调没有问题，增加- -do_compress - -strategy 'dynabert+qat+embeddings'用于压缩量化时，会出错
WARNING:root:cannot import name 'layers' from 'parl' (D:\ProgramData\Anaconda3\envs\nlp_gpu\lib\site-packages\parl\__init__.py)
2023-03-14 12:00:09,949-WARNING: post-quant-hpo is not support in system other than linux
Tue Mar 14 12:00:09 Dynamic-to-Static INFO: (Level -1) Not recommend to deepcopy 'UIE' decorated with @to_static, it has side effect that will rollback into original state before @to_static. Please deepcopy 'UIE' before applying @to_static.
难道压缩量化不能在windows环境吗？

**Comment by LiuChiachi** [comment]
你好，这个warning不会影响功能，我们这里不会用到post-quant-hpo

**Comment by song4875343** [comment]
这个是完整的错误
To use torch as backend, `export PARL_BACKEND=torch` before running the scripts.
WARNING:root:cannot import name 'layers' from 'parl' (d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\site-packages\parl\__init__.py)
2023-03-14 18:51:09,975-WARNING: post-quant-hpo is not support in system other than linux
Tue Mar 14 18:51:09 Dynamic-to-Static INFO: (Level -1) Not recommend to deepcopy 'UIE' decorated with @to_static, it has side effect that will rollback into original state before @to_static. Please deepcopy 'UIE' before applying @to_static.
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\inspect.py", line 1135, in getfullargspec
    sig = _signature_from_callable(func,
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\inspect.py", line 2308, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\inspect.py", line 2119, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <paddle.fluid.dygraph.dygraph_to_static.program_translator.StaticFunction object at 0x00000270B90AF370>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "finetune.py", line 228, in <module>
    main()
  File "finetune.py", line 224, in main
    trainer.compress(custom_evaluate=custom_evaluate)
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\site-packages\paddlenlp\trainer\trainer_compress.py", line 71, in compress
    model = copy.deepcopy(self.model)
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 695, in __deepcopy__
    self.rollback()
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 648, in rollback
    setattr(self._class_instance, func_name,
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\site-packages\paddlenlp\transformers\model_utils.py", line 968, in __setattr__
    value = adapt_stale_fwd_patch(self, name, value)
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\site-packages\paddlenlp\transformers\utils.py", line 75, in adapt_stale_fwd_patch
    (spec_args, spec_varargs, spec_varkw, spec_defaults, _, _, _) = inspect.getfullargspec(self.forward)
  File "d:\ProgramData\Anaconda3\envs\nlp_gpu\lib\inspect.py", line 1144, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable

**Comment by song4875343** [comment]
@linjieccc @linjieccc  有什么能帮到我的消息吗？

**Comment by linjieccc** [comment]
@LiuChiachi 辛苦再帮忙看下这个问题

**Comment by yycoolsam** [comment]
系统环境：win10 
包版本：
paddlepaddle-gpu  2.4.2.post117 
paddleslim  2.4.1 
paddlenlp  2.5.2
cuda  11.7
单纯uie微调没有问题，增加 --do_compress用于压缩时报错，压缩的base模型。
完整的输出信息：
```
[2023-05-15 10:45:15,992] [    INFO] - ***** eval metrics *****
[2023-05-15 10:45:15,992] [    INFO] -   epoch                   =        1.0
[2023-05-15 10:45:15,993] [    INFO] -   eval_f1                 =     0.8602
[2023-05-15 10:45:15,993] [    INFO] -   eval_loss               =     0.0002
[2023-05-15 10:45:15,993] [    INFO] -   eval_precision          =     0.8889
[2023-05-15 10:45:15,993] [    INFO] -   eval_recall             =     0.8333
[2023-05-15 10:45:15,993] [    INFO] -   eval_runtime            = 0:00:53.33
[2023-05-15 10:45:15,993] [    INFO] -   eval_samples_per_second =     89.302
[2023-05-15 10:45:15,994] [    INFO] -   eval_steps_per_second   =     11.174
[2023-05-15 10:45:15,995] [    INFO] - Exporting inference model to model/paddlepaddle/model_best\model
[2023-05-15 10:45:19,740] [    INFO] - Inference model exported.
[2023-05-15 10:45:19,741] [    INFO] - tokenizer config file saved in model/paddlepaddle/model_best\tokenizer_config.json
[2023-05-15 10:45:19,742] [    INFO] - Special tokens file saved in model/paddlepaddle/model_best\special_tokens_map.json
WARNING:root:No module named 'parl'
2023-05-15 10:45:22,003-WARNING: post-quant-hpo is not support in system other than linux
Mon May 15 10:45:22 Dynamic-to-Static INFO: (Level -1) Not recommend to deepcopy 'UIE' decorated with @to_static, it has side effect that will rollback into original state before @to_static. Please deepcopy 'UIE' before applying @to_static.
Traceback (most recent call last):
  File "D:\Program Files\Python\Python38\lib\inspect.py", line 1135, in getfullargspec
    sig = _signature_from_callable(func,
  File "D:\Program Files\Python\Python38\lib\inspect.py", line 2308, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "D:\Program Files\Python\Python38\lib\inspect.py", line 2119, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <paddle.fluid.dygraph.dygraph_to_static.program_translator.StaticFunction object at 0x000001F1580DC970>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "finetune.py", line 276, in <module>
    main()
  File "finetune.py", line 272, in main
    trainer.compress(custom_evaluate=custom_evaluate)
  File "E:\api_server_office_win\venv\lib\site-packages\paddlenlp\trainer\trainer_compress.py", line 71, in compress
    model = copy.deepcopy(self.model)
  File "D:\Program Files\Python\Python38\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Program Files\Python\Python38\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Program Files\Python\Python38\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "D:\Program Files\Python\Python38\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Program Files\Python\Python38\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
  File "E:\api_server_office_win\venv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 695, in __deepcopy__
    self.rollback()
  File "E:\api_server_office_win\venv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 648, in rollback
    setattr(self._class_instance, func_name,
  File "E:\api_server_office_win\venv\lib\site-packages\paddlenlp\transformers\model_utils.py", line 962, in __setattr__
    value = adapt_stale_fwd_patch(self, name, value)
  File "E:\api_server_office_win\venv\lib\site-packages\paddlenlp\transformers\utils.py", line 75, in adapt_stale_fwd_patch
    (spec_args, spec_varargs, spec_varkw, spec_defaults, _, _, _) = inspect.getfullargspec(self.forward)
  File "D:\Program Files\Python\Python38\lib\inspect.py", line 1144, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable
```

是不是压缩量化不能在windows环境？

**Comment by wanshichenguang** [comment]
你解决了吗，我也遇到这个问题了

**Comment by imempty** [comment]
问题解决了吗，我也遇到这个问题了
