### ISSUE TITLE
[Bug]: 安装失败

### ISSUE THREAD

**Issue by xuyouqian** [PaddlePaddle/PaddleNLP#5245]
### 软件环境

```Markdown
paddle-bfloat        0.1.7
paddlepaddle-gpu     2.4.2.post112
centos 7.6   cuda 版本11.4
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
安装命令
pip install --upgrade paddlenlp>=2.0.0rc -i https://pypi.org/simple

报错如下：
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
      ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
      ERROR: No matching distribution found for setuptools_scm
      /root/miniconda3/envs/ejd/lib/python3.8/site-packages/setuptools/dist.py:770: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
        warnings.warn(
      /root/miniconda3/envs/ejd/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "/root/miniconda3/envs/ejd/lib/python3.8/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/root/miniconda3/envs/ejd/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/root/miniconda3/envs/ejd/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpm_9z8__x', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'setuptools_scm']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-s1vhcm_0/seqeval_74df51e292d6471ab33337696781dbd3/setup.py", line 27, in <module>
          setup(
        File "/root/miniconda3/envs/ejd/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/root/miniconda3/envs/ejd/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/root/miniconda3/envs/ejd/lib/python3.8/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/root/miniconda3/envs/ejd/lib/python3.8/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/root/miniconda3/envs/ejd/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/root/miniconda3/envs/ejd/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/root/miniconda3/envs/ejd/lib/python3.8/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/root/miniconda3/envs/ejd/lib/python3.8/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/root/miniconda3/envs/ejd/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpm_9z8__x', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'setuptools_scm']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### 稳定复现步骤 & 代码

pip install --upgrade paddlenlp>=2.0.0rc -i https://pypi.org/simple

**Comment by LiuChiachi** [comment]
```
pip install --upgrade paddlenlp
```
这样会有问题吗

**Comment by xuyouqian** [comment]
还是有问题  感觉应该是跟pytorch 不兼容。
我又重新建了虚拟环境安装。
单独安装paddnle 现在能正常安装了了。
但是再安装 pytorch 和transformer 就会崩掉：

我是用的mindconda 3.8 版本 
先安装pdddle nlp
conda install paddlepaddle-gpu==2.3.1 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge

pip install --upgrade paddlenlp==2.3.4
能正常安装
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
但是transformer 再安装就有问题
pip install transformers==4.7.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by 21888** [comment]
你问题解决了吗,我跟你一模一样的错误

**Comment by huishaowangzhe** [comment]
我也有同样问题，请问你解决了嘛
