### ISSUE TITLE
[Bug]: Ernie1.0官方部署案例报错：RuntimeError: Invalid enum data type `255`

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/PaddleNLP#5259]
### 软件环境

```Markdown
paddlenlp                      2.5.2
paddlepaddle-gpu               2.4.2.post112
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
在AIStudio环境中，
Ernie部署执行报错：

!cd ~/PaddleNLP/model_zoo/ernie-1.0/finetune/ && python deploy/seq_cls_infer.py --model_dir 

Traceback (most recent call last):
  File "/home/aistudio/PaddleNLP/model_zoo/ernie-1.0/finetune/deploy/seq_cls_infer.py", line 21, in <module>
    from paddlenlp.datasets import load_dataset
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlenlp/__init__.py", line 33, in <module>
    import paddle
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 52, in <module>
    from . import io
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/io.py", line 31, in <module>
    from paddle.fluid import layers
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/layers/__init__.py", line 29, in <module>
    from . import math_op_patch
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/layers/math_op_patch.py", line 24, in <module>
    from paddle.fluid.dygraph.base import in_declarative_mode
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/__init__.py", line 35, in <module>
    from . import checkpoint
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/checkpoint.py", line 26, in <module>
    from paddle.fluid.dygraph.jit import _SaveLoadConfig
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py", line 34, in <module>
    from paddle.fluid.dygraph.dygraph_to_static import logging_utils
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/__init__.py", line 29, in <module>
    from . import program_translator
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 38, in <module>
    from paddle.fluid.dygraph.dygraph_to_static.partial_program import partial_program_from
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/partial_program.py", line 36, in <module>
    from paddle.fluid.contrib.mixed_precision.decorator import (
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/contrib/__init__.py", line 31, in <module>
    from . import mixed_precision
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/contrib/mixed_precision/__init__.py", line 17, in <module>
    from . import decorator
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 22, in <module>
    from . import fp16_utils
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 23, in <module>
    from .fp16_lists import AutoMixedPrecisionLists
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/contrib/mixed_precision/fp16_lists.py", line 186, in <module>
    _, _, _sys_unsupported_fp16_list = core.op_supported_infos(
RuntimeError: Invalid enum data type `255`.
  [/paddle/paddle/phi/common/data_type.h:210]
```

### 稳定复现步骤 & 代码

参考官方手册 [ERNIE 1.0 模型 Python 部署示例](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/finetune/deploy/README.md)

 开始finetune训练并导出模型
dataset="chnsenticorp_v2"
!cd ~/PaddleNLP/model_zoo/ernie-1.0/finetune && python run_seq_cls.py \
    --do_train \
    --do_eval \
    --do_predict \
    --do_export \
    --model_name_or_path ernie-1.0-base-zh \
    --dataset $dataset \
    --output_dir ./tmp/$dataset \
    --eval_steps 200 \
    --save_steps 200 \
    --metric_for_best_model "eval_accuracy" \
    --load_best_model_at_end \
    --save_total_limit 3 \

 部署推理
!cd ~/PaddleNLP/model_zoo/ernie-1.0/finetune/ && python deploy/seq_cls_infer.py --model_dir tmp/chnsenticorp_v2/export/ --device gpu --backend paddle

环境复现在这个公开项目中：https://aistudio.baidu.com/aistudio/projectdetail/5573295
第五部分：Ernie部署

用默认的飞桨2.4.1和飞桨2.4.2都测试过，报错信息基本相同。

**Comment by skywalk163** [comment]
有什么进展不？

**Comment by ZeyuTeng96** [comment]
同样遇到这个问题，但是不是跑的相同例子 @joey12300 @skywalk163

**Comment by cqray1990** [comment]
> 同样遇到这个问题，但是不是跑的相同例子 @joey12300 @skywalk163
@skywalk163 @joey12300 @ZeyuTeng96  这个问题不解决？
