### ISSUE TITLE
[Question]: 使用UTC-BASE训练自定义数据时出现 No module named 'fast_tokenizer'

### ISSUE THREAD

**Issue by lai-serena** [PaddlePaddle/PaddleNLP#5263]
### 请提出你的问题

环境：linux
paddlepaddle-gpu=2.4.2.post112
paddlenlp= 2.5.2.post0
python=3.7.17

启动命令：
python applications/zero_shot_text_classification/run_train.py      --device gpu --single_label true     --logging_steps 10     --save_steps 100     --eval_steps 100     --seed 1000     --model_name_or_path utc-base     --output_dir ./checkpoint_labels2/model_best     --dataset_path ./label2/ --train_file train_utc.txt --dev_file test_utc.txt     --max_seq_length 512      --per_device_train_batch_size 8     --per_device_eval_batch_size 8     --gradient_accumulation_steps 8     --num_train_epochs 100     --learning_rate 1e-5     --do_train     --do_eval     --overwrite_output_dir     --disable_tqdm True     --metric_for_best_model macro_f1     --load_best_model_at_end  True     --save_total_limit 1     --save_plm

出现问题：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.7/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "applications/zero_shot_text_classification/run_train.py", line 21, in <module>
    from utils import UTCLoss, read_local_dataset
  File "/home/PaddleNLP/applications/zero_shot_text_classification/utils.py", line 22, in <module>
    from paddlenlp.utils.log import logger
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/__init__.py", line 35, in <module>
    from . import (
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/data/__init__.py", line 16, in <module>
    from .data_collator import *
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/data/data_collator.py", line 25, in <module>
    from ..transformers import BertTokenizer
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/__init__.py", line 28, in <module>
    from .tokenizer_utils_fast import PretrainedFastTokenizer
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/tokenizer_utils_fast.py", line 22, in <module>
    from fast_tokenizer import Encoding as FastEncoding
ModuleNotFoundError: No module named 'fast_tokenizer'

**Comment by lugimzzz** [comment]
安装一下fast tokenizer
`pip install --upgrade fast_tokenizer`

**Comment by lai-serena** [comment]
> 安装一下fast tokenizer `pip install --upgrade fast_tokenizer`

这个问题安装之后解决了，但是又有新的问题

[2023-03-16 07:10:22,597] [    INFO] -   Number of trainable parameters = 118026368
W0316 07:10:23.053583  1494 gpu_resources.cc:217] WARNING: device: . The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
[2023-03-16 07:10:58,562] [    INFO] - loss: 3.48792915, learning_rate: 9.947e-06, global_step: 10, interval_runtime: 35.9637, interval_samples_per_second: 17.796, interval_steps_per_second: 0.278, epoch: 0.5096
[2023-03-16 07:11:35,444] [    INFO] - loss: 3.01756592, learning_rate: 9.895e-06, global_step: 20, interval_runtime: 36.8824, interval_samples_per_second: 17.352, interval_steps_per_second: 0.271, epoch: 1.051
[2023-03-16 07:12:11,220] [    INFO] - loss: 2.67419949, learning_rate: 9.842e-06, global_step: 30, interval_runtime: 35.7759, interval_samples_per_second: 17.889, interval_steps_per_second: 0.28, epoch: 1.5605
[2023-03-16 07:12:50,609] [    INFO] - loss: 2.78982544, learning_rate: 9.789e-06, global_step: 40, interval_runtime: 39.3885, interval_samples_per_second: 16.248, interval_steps_per_second: 0.254, epoch: 2.1019
[2023-03-16 07:13:26,611] [    INFO] - loss: 2.43100681, learning_rate: 9.737e-06, global_step: 50, interval_runtime: 36.0024, interval_samples_per_second: 17.777, interval_steps_per_second: 0.278, epoch: 2.6115
[2023-03-16 07:14:05,800] [    INFO] - loss: 2.49378204, learning_rate: 9.684e-06, global_step: 60, interval_runtime: 39.1886, interval_samples_per_second: 16.331, interval_steps_per_second: 0.255, epoch: 3.1529
[2023-03-16 07:14:41,284] [    INFO] - loss: 2.25644169, learning_rate: 9.632e-06, global_step: 70, interval_runtime: 35.4844, interval_samples_per_second: 18.036, interval_steps_per_second: 0.282, epoch: 3.6624
[2023-03-16 07:15:19,672] [    INFO] - loss: 2.29859104, learning_rate: 9.579e-06, global_step: 80, interval_runtime: 38.3873, interval_samples_per_second: 16.672, interval_steps_per_second: 0.261, epoch: 4.2038
[2023-03-16 07:15:55,493] [    INFO] - loss: 1.94286594, learning_rate: 9.526e-06, global_step: 90, interval_runtime: 35.8213, interval_samples_per_second: 17.866, interval_steps_per_second: 0.279, epoch: 4.7134
[2023-03-16 07:16:33,212] [    INFO] - loss: 1.9372118, learning_rate: 9.474e-06, global_step: 100, interval_runtime: 37.719, interval_samples_per_second: 16.968, interval_steps_per_second: 0.265, epoch: 5.2548
[2023-03-16 07:16:33,212] [    INFO] - ***** Running Evaluation *****
[2023-03-16 07:16:33,212] [    INFO] -   Num examples = 305
[2023-03-16 07:16:33,212] [    INFO] -   Total prediction steps = 39
[2023-03-16 07:16:33,212] [    INFO] -   Pre device batch size = 8
[2023-03-16 07:16:33,213] [    INFO] -   Total Batch size = 8
[2023-03-16 07:16:39,886] [    INFO] - eval_loss: 2.1365926265716553, eval_accuracy: 0.5672131147540984, eval_runtime: 6.6728, eval_samples_per_second: 45.708, eval_steps_per_second: 5.845, epoch: 5.2548
[2023-03-16 07:16:39,886] [    INFO] - Saving model checkpoint to ./checkpoint_labels2/model_best/checkpoint-100
[2023-03-16 07:16:39,886] [    INFO] - Trainer.model is not a `PretrainedModel`, only saving its state dict.
[2023-03-16 07:16:40,773] [    INFO] - tokenizer config file saved in ./checkpoint_labels2/model_best/checkpoint-100/tokenizer_config.json
[2023-03-16 07:16:40,774] [    INFO] - Special tokens file saved in ./checkpoint_labels2/model_best/checkpoint-100/special_tokens_map.json
[2023-03-16 07:16:40,776] [    INFO] - Configuration saved in ./checkpoint_labels2/model_best/checkpoint-100/plm/config.json
Traceback (most recent call last):
  File "applications/zero_shot_text_classification/run_train.py", line 154, in <module>
    main()
  File "applications/zero_shot_text_classification/run_train.py", line 133, in main
    train_results = trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/trainer.py", line 714, in train
    self._maybe_log_save_evaluate(tr_loss, model, epoch, ignore_keys_for_eval, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/trainer.py", line 849, in _maybe_log_save_evaluate
    self._save_checkpoint(model, metrics=metrics)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/trainer.py", line 1392, in _save_checkpoint
    metric_value = metrics[metric_to_check]
KeyError: 'eval_macro_f1'

**Comment by LemonNoel** [comment]
开启`single_label`时需要将运行脚本中的 `metric_for_best_model` 参数改为`accuracy`

**Comment by wn1652400018** [comment]
为什么我执行pip install --upgrade fast_tokenizer时，显示：
ERROR: Could not find a version that satisfies the requirement fast_tokenizer (from versions: none)
ERROR: No matching distribution found for fast_tokenizer

**Comment by lugimzzz** [comment]
> 

python3 -m pip install fast-tokenizer-python
