### ISSUE TITLE
[Question]: 使用Taskflow 加载 官方以及自己训练出来的uie-m-large模型都报错

### ISSUE THREAD

**Issue by 526872163** [PaddlePaddle/PaddleNLP#5301]
### 请提出你的问题

Traceback (most recent call last):
  File "C:\tender\main.py", line 43, in <module>
    ie = Taskflow('information_extraction', schema=schema, position_prob=0.3,
  File "C:\Users\Administrator\anaconda3\envs\tender\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 837, in __init__
    self.task_instance = task_class(
  File "C:\Users\Administrator\anaconda3\envs\tender\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 536, in __init__
    self._get_inference_model()
  File "C:\Users\Administrator\anaconda3\envs\tender\lib\site-packages\paddlenlp\taskflow\task.py", line 366, in _get_inference_model
    self._prepare_static_mode()
  File "C:\Users\Administrator\anaconda3\envs\tender\lib\site-packages\paddlenlp\taskflow\task.py", line 221, in _prepare_static_mode
    self.predictor = paddle.inference.create_predictor(self._config)
RuntimeError: (Unavailable) An error occurred while loading model parameters. Please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(*buffer) == true, but received static_cast<bool>(*buffer):0 != true:1.] (at ..\paddle/fluid/operators/load_combine_op.h:86)
  [operator < load_combine > error]

Process finished with exit code 1

报错如上，使用了两台电脑测试遇到一样的问题，win10系统，paddlepadle-gpu 试过2.4以及2.32，cuda11.7和11.6，paddlenlp版本2.5.2 post0，内存一台32G，一台128G，显卡：3090

**Comment by 526872163** [comment]
使用uie-base模型是正常的

**Comment by FlyDut** [comment]
有解决方法吗？
