### ISSUE TITLE
[Question]: from paddlenlp.embeddings import TokenEmbedding报错

### ISSUE THREAD

**Issue by Aadedd** [PaddlePaddle/PaddleNLP#5302]
### 请提出你的问题

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from paddlenlp.embeddings import TokenEmbedding
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/paddlenlp/__init__.py", line 51, in <module>
    from .server import SimpleServer
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/paddlenlp/server/__init__.py", line 15, in <module>
    from .server import SimpleServer
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/paddlenlp/server/server.py", line 16, in <module>
    from fastapi import FastAPI
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 48, in init pydantic.dataclasses
    
  File "pydantic/main.py", line 120, in init pydantic.main
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'

**Comment by wawltor** [comment]
PaddleNLP的版本是什么了？
