### ISSUE TITLE
[Question]: how to infer the ernie-gen model ?

### ISSUE THREAD

**Issue by ucas010** [PaddlePaddle/PaddleNLP#5315]
### 请提出你的问题

official project :https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-gen
how to get the inference of the ernie-gen model ?
is there a script for this project ?
thx

**Comment by gongel** [comment]
hi, you can refer to  herer: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-gen#%E6%A8%A1%E5%9E%8B%E9%A2%84%E6%B5%8B

**Comment by ucas010** [comment]
```
>>> test_batch_sampler
<paddle.fluid.dataloader.batch_sampler.BatchSampler object at 0x7ff1b4022dc0>
>>> data_loader = DataLoader(dataset=wm2, batch_sampler=test_batch_sampler, collate_fn=batchify_fn, num_workers=0, return_list=True)
>>> for data in data_loader:
...     print(data)
... 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/data/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/data/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/data/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/data/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "/data/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 260, in __getitem__
    return self._transform(self.new_data[idx]) if self._transform_pipline else self.new_data[idx]
  File "/data/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 252, in _transform
    data = fn(data)
  File "/data/encode.py", line 32, in warpper
    tokens = example["tokens"]
TypeError: string indices must be integers
```

测试中，这个进程咋不会死。。。。。。一直等着等到啥时候？？？

**Comment by gongel** [comment]
dataloader 中途退出会有这个问题，可以手动kill掉。

**Comment by ucas010** [comment]
ctrl+C,啥的都干不掉，只有关了这个界面。。。

**Comment by ucas010** [comment]
这个可以预测出来多个么？请问在哪里改参数啊？
输入一句话，输出多句话供选择。

**Comment by ucas010** [comment]
这个可以预测出来多个么？请问在哪里改参数啊？
输入一句话，输出多句话供选择。

**Comment by ucas010** [comment]
Rouge-1: 19.30703 ,Rouge-2: 3.71217
这个指标是越大越好么？还是有一定范围，哪个范围比较好呢？
