### ISSUE TITLE
[Bug]: 模型自动下载到默认root盘下，然后改变其位置，重新加载就报错

### ISSUE THREAD

**Issue by ucas010** [PaddlePaddle/PaddleNLP#5319]
### 软件环境

```Markdown
paddle-bfloat         0.1.7
paddle2onnx           1.0.5
paddlefsl             1.1.0
paddlehub             2.3.1
paddlenlp             2.5.0.post0
paddleocr             2.5.0.3
paddlepaddle-gpu      2.4.1.post116
此模型：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-gen
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
model = ErnieForGeneration.from_pretrained("ernie-1.0")
我把下载的文件全部放在/data/model/ 下面，重新加载
model = ErnieForGeneration.from_pretrained("/data/model/")
```

### 稳定复现步骤 & 代码

```
2023-03-20 19:27:56,274] [    INFO] - Downloading /data/model/model_state.pdparams and saved to /data/model/
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/site-packages/paddlenlp/transformers/ernie_gen/modeling.py", line 317, in from_pretrained
    resolved_resource_files[file_id] = get_path_from_url(file_path, default_root)
  File "ite-packages/paddle/utils/download.py", line 148, in get_path_from_url
    assert is_url(url), "downloading from {} not a url".format(url)
AssertionError: downloading from /data/model/model_state.pdparams not a url
```

**Comment by qiuwenbogdut** [comment]
遇到了相同的问题 请问这个问题有解决方案了吗? @ucas010
