### ISSUE TITLE
[Question]: 使用label_studio脚本对数据进行划分出错

### ISSUE THREAD

**Issue by heyuqi1970** [PaddlePaddle/PaddleNLP#5324]
### 请提出你的问题

对label_studio导出的json进行训练数据划分时，提示如下错误：
```
!python label_studio.py \
--label_studio_file="/home/aistudio/data/project-5-at-2023-03-21-01-22-a6ca9094.json"\
--splits 0.8 0.1 0.1\
--task_type ext
```

```
/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/sklearn/utils/multiclass.py:14: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
  from scipy.sparse.base import spmatrix
[2023-03-21 09:23:34,420] [    INFO] - Converting annotation data...
  0%|                                                     | 0/3 [00:00<?, ?it/s][2023-03-21 09:23:34,422] [    INFO] - Parsing image file contract.jpg ...
  0%|                                                     | 0/3 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/aistudio/label_studio.py", line 139, in <module>
    do_convert()
  File "/home/aistudio/label_studio.py", line 94, in do_convert
    train_examples = data_converter.convert_ext_examples(raw_examples[:p1])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlenlp/utils/tools.py", line 510, in convert_ext_examples
    items = self.process_image_tag(line, task_type="ext")
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlenlp/utils/tools.py", line 429, in process_image_tag
    "type": r["labels"][0],
KeyError: 'labels'
```

**Comment by heyuqi1970** [comment]
是没有标注完整的关系label
