### ISSUE TITLE
[Question]: openai.error.APIError: Invalid response object from API: '{"detail":"Not Found"}'

### ISSUE THREAD

**Issue by xiaochengxinyizhan** [PaddlePaddle/PaddleNLP#5345]
### 请提出你的问题

【readme】https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/code_generation/codegen#%E4%BB%A3%E7%A0%81%E7%94%9F%E6%88%90

【问题】代码生成测试服务中，每次都是返回404
INFO:     127.0.0.1:50703 - "POST /engines/codegen/completions HTTP/1.1" 404 Not Found

【环境codegen_server启动成功，环境配置MAC M1芯片 ，CPU运行】
INFO:     Started server process [11867]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8978 (Press CTRL+C to quit)

【代码】
import openai
openai.api_key = 'dummy'
openai.api_base = 'http://0.0.0.0:8978'
result = openai.Completion.create(
    engine='codegen', prompt='def hello', max_tokens=16, temperature=0.1)
print(result)
'''
<OpenAIObject text_completion id=cmpl-dmhoeHmcw9DJ4NeqOJDQVKv3iivJ0 at 0x7fe7a81d42c0> JSON: {
  "id": "cmpl-dmhoeHmcw9DJ4NeqOJDQVKv3iivJ0",
  "choices": [
    {
      "text": "_world():\n    print(\"Hello World!\")\n\n\n#",
      "index": 0,
      "finish_reason": "stop",
      "logprobs": null,

    }
  ],
  "usage": {
    "completion_tokens": null,
    "prompt_tokens": null,
    "total_tokens": null
  }
}
'''
【返回异常信息】
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_codegen.py", line 4, in <module>
    result = openai.Completion.create(
  File "/Users/liuxiaocheng/Library/Python/3.8/lib/python/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/liuxiaocheng/Library/Python/3.8/lib/python/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/liuxiaocheng/Library/Python/3.8/lib/python/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/liuxiaocheng/Library/Python/3.8/lib/python/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/liuxiaocheng/Library/Python/3.8/lib/python/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
  File "/Users/liuxiaocheng/Library/Python/3.8/lib/python/site-packages/openai/api_requestor.py", line 333, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"detail":"Not Found"}' (HTTP response code was 404)

**Comment by gongel** [comment]
openai的版本是多少呢？

**Comment by xiaochengxinyizhan** [comment]
我解决了该问题，因为框架code_server代码路径自带版本号，干掉就可以了

**Comment by zhixue123456** [comment]
> 

我也遇到了这个问题，但是我的路径都是英文路径，并没有发现版本号呢？

**Comment by guccang** [comment]
我也遇到这个问题，不清楚什么原因，是否有详细日志指向错误原因呢？

**Comment by guccang** [comment]
原因是codegen_server.py中的路由配置如下
@app.post("/v1/engines/codegen/completions", status_code=200)
async def gen(item: Input)
报错显示的路径是/engines/codegen/completions
因此可以将/v1删除，重启服务器就可以了。
或者调用的接口修改添加路由路径/v1
