### ISSUE TITLE
在UIEX finetune时出现错误 

### ISSUE THREAD

**Issue by heyuqi1970** [PaddlePaddle/PaddleNLP#5350]
### 请提出你的问题

finetune时提示 KeyError: 'eval_f1'

```
!python finetune.py  \
    --device gpu \
    --logging_steps 5 \
    --save_steps 25 \
    --eval_steps 25 \
    --seed 42 \
    --model_name_or_path uie-x-base \
    --output_dir ./checkpoint/model_best \
    --train_path data/train.txt \
    --dev_path data/dev.txt  \
    --max_seq_len 512  \
    --per_device_train_batch_size  8 \
    --per_device_eval_batch_size 8 \
    --num_train_epochs 10 \
    --learning_rate 1e-5 \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir ./checkpoint/model_best \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1
```
```
[2023-03-22 09:03:06,917] [    INFO] - ***** Running Evaluation *****
[2023-03-22 09:03:06,917] [    INFO] -   Num examples = 0
[2023-03-22 09:03:06,917] [    INFO] -   Total prediction steps = 0
[2023-03-22 09:03:06,917] [    INFO] -   Pre device batch size = 8
[2023-03-22 09:03:06,918] [    INFO] -   Total Batch size = 8
[2023-03-22 09:03:06,921] [    INFO] - eval_runtime: 0.0035, eval_samples_per_second: 0.0, eval_steps_per_second: 0.0, epoch: 0.3125
[2023-03-22 09:03:06,921] [    INFO] - Saving model checkpoint to ./checkpoint/model_best/checkpoint-25
[2023-03-22 09:03:06,923] [    INFO] - Configuration saved in ./checkpoint/model_best/checkpoint-25/config.json
[2023-03-22 09:03:16,594] [    INFO] - tokenizer config file saved in ./checkpoint/model_best/checkpoint-25/tokenizer_config.json
[2023-03-22 09:03:16,595] [    INFO] - Special tokens file saved in ./checkpoint/model_best/checkpoint-25/special_tokens_map.json
Traceback (most recent call last):
  File "/home/aistudio/finetune.py", line 167, in <module>
    main()
  File "/home/aistudio/finetune.py", line 137, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 716, in train
    self._maybe_log_save_evaluate(tr_loss, model, epoch, ignore_keys_for_eval, inputs=inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 851, in _maybe_log_save_evaluate
    self._save_checkpoint(model, metrics=metrics)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 1413, in _save_checkpoint
    metric_value = metrics[metric_to_check]
KeyError: 'eval_f1'
```

**Comment by linjieccc** [comment]
@heyuqi1970 你好，跑的是哪个AIStudio项目呢 可以尝试下更新paddlenlp的版本

**Comment by heyuqi1970** [comment]
@linjieccc 

我是跑一个我自己标注的表格数据，用的是label studio标注的，数据转换用的label_studio.py。我尝试了paddlenlp 2.5.1和2.5.2都显示同样的错误。
如果需要我可以吧训练数据发你。

**Comment by linjieccc** [comment]
方便的话可以分享一下AIStudio项目地址

**Comment by heyuqi1970** [comment]
@linjieccc 

https://aistudio.baidu.com/studio/project/partial/verify/5701321/eb403274640c444d94904b2b511cf78d

**Comment by linjieccc** [comment]
@heyuqi1970 hi，项目链接好像失效呢。你可以先参考这个项目的流程试试，替换一下自己的标注json文件 https://aistudio.baidu.com/aistudio/projectdetail/5261592

**Comment by heyuqi1970** [comment]
@linjieccc 运行了那个连接的项目，出现同样的错误。
这个应该是metric_for_best_model的中没有eval_f1。
“metrics” 的值目前有几个？

**Comment by heyuqi1970** [comment]
@linjieccc 
我debug了一下，发现metrics的值是{'eval_runtime': 0.0061, 'eval_samples_per_second': 0.0, 'eval_steps_per_second': 0.0, 'epoch': 1.7857}，没有'eval_f1'这个key， 这应该是nlp升级后的bug吧。

**Comment by LJY6356** [comment]
你好，我也遇到这个问题，你解决了吗

**Comment by heyuqi1970** [comment]
@LJY6356 解决了。在分配训练集时比例splits 0.8 0.2 0.0，最后一定要时0。

**Comment by dongfeicui** [comment]
dev.txt 数据集为空，所以在做验证指标时会报错
