### ISSUE TITLE
[Question]: 使用paddlenlp提供的源码 加载inference model报错

### ISSUE THREAD

**Issue by coolge** [PaddlePaddle/PaddleNLP#5359]
### 请提出你的问题

用的paddlenlp提供的源码把模型打包，同样使用paddlenlp提供的源码进行inference推理时，运行到load函数报错。报错的行为：https://github.com/PaddlePaddle/PaddleNLP/blob/aafd5a9178e1e780a9fbbaa42820eda4fca31d52/applications/text_summarization/deploy/paddle_inference/inference_unimo_text.py#L41
报错如下：
Traceback (most recent call last):
  File "./deploy/paddle_inference/inference_unimo_text.py", line 158, in <module>
    predictor = setup_predictor(args)
  File "./deploy/paddle_inference/inference_unimo_text.py", line 41, in setup_predictor
    load("FasterTransformer", verbose=True)
  File "/home/work/wangshuai11/package/python38_trt_cuda10/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 53, in _impl
    func(*args, **kwargs)
  File "/home/work/wangshuai11/package/python38_trt_cuda10/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 283, in load
    extension = get_extension_maker(name)(name, **kwargs)
  File "/home/work/wangshuai11/package/python38_trt_cuda10/lib/python3.8/site-packages/paddle/utils/cpp_extension/cpp_extension.py", line 254, in CppExtension
    return setuptools.Extension(name, sources, *args, **kwargs)
  File "/home/work/wangshuai11/package/python38_trt_cuda10/lib/python3.8/site-packages/setuptools/extension.py", line 37, in __init__
    _Extension.__init__(self, name, sources, *args, **kw)
  File "/home/work/wangshuai11/package/python38_trt_cuda10/lib/python3.8/distutils/extension.py", line 107, in __init__
    raise AssertionError("'sources' must be a list of strings")
AssertionError: 'sources' must be a list of strings

**Comment by FrostML** [comment]
`setuptools` 版本是？使用的是 python2.7？

**Comment by coolge** [comment]
> `setuptools` 版本是？使用的是 python2.7？
setuptools  版本是 58.0.4；使用的python 3.8
paddle版本是2.4.2，cuda 10.2，cudnn 7.6.5

**Comment by FrostML** [comment]
可以尝试升级下 `setuptools` 版本

**Comment by coolge** [comment]
把load代码改成 load("FastGeneration", verbose=True) 之后，报错如下：
[2023-03-22 15:54:35,713] [   DEBUG] - skipping 'FastGeneration' extension (up-to-date) build
Traceback (most recent call last):
  File "./deploy/paddle_inference/inference_unimo_text.py", line 150, in <module>
    predictor = setup_predictor(args)
  File "./deploy/paddle_inference/inference_unimo_text.py", line 42, in setup_predictor
    load("FastGeneration", verbose=True)
  File "/home/work/wangshuai11/package/python38_trt_cuda10/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 53, in _impl
    func(*args, **kwargs)
  File "/home/work/wangshuai11/package/python38_trt_cuda10/lib/python3.8/site-packages/paddlenlp/ops/ext_utils.py", line 300, in load
    ops = load_op_meta_info_and_register_op(lib_filepath)
  File "/home/work/wangshuai11/package/python38_trt_cuda10/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 134, in load_op_meta_info_and_register_op
    core.load_op_meta_info_and_register_op(lib_filename)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (/root/.paddlenlp/extensions/9f0cdca070e2f7b83f83c61bd6e0ee3f/FastGeneration/libdecoding_op.so) that Paddle depends on is not configured correctly. (error code is core_avx.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:305)

**Comment by coolge** [comment]
最下面的报错的原因应该是paddle安装的问题。把paddle版本换成2.3.2解决了
