### ISSUE TITLE
[Bug]: 使用taskflow和uie-x-base预测的时候，如果机器有多张gpu，除了一张外其他都是满的，推理的时候会由于其他gpu无法使用报错

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/PaddleNLP#5365]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.3.1.post112
- paddlenlp: 2.5.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
设置 
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "1" 无效
如果机器有多张gpu，除了一张外其他都是满的，推理的时候会由于其他gpu无法使用报错，预测时报错：
 ExternalError: CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED. 
      [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this may indicate an internal error/bug in the library.  ] (at /paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:373)
      [operator < conv2d_fusion > error]
```

### 稳定复现步骤 & 代码

from pprint import pprint
from paddlenlp import Taskflow
from paddlenlp.utils.doc_parser import DocParser
import os

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
schema = ['名称', '纳税人识别号', '开户行及账号', '金额', '价税合计', 'No', '税率', '地址、电话', '税额']
my_ie = Taskflow("information_extraction", model="uie-x-base", schema=schema, task_path='./checkpoint/model_best', precision='fp32',device_id=1)

result = my_ie({"doc":"./p0/data/images/b0.jpg"})

**Comment by linjieccc** [comment]
@zhiyongLiu1114 你好，试下不设置CUDA_VISIBLE_DEVICES环境变量，直接通过`device_id`来控制gpu卡号

**Comment by zhiyongLiu1114** [comment]
> @zhiyongLiu1114 你好，试下不设置CUDA_VISIBLE_DEVICES环境变量，直接通过`device_id`来控制gpu卡号

你好，上述方法已经试过，不可行，原因如下：
1. 设置CUDA_VISIBLE_DEVICES环境变量 无效
2. device_id 在模型加载时有效，以上错误是模型推理时报错，也就是device_id 对于模型推理无效

**Comment by linjieccc** [comment]
执行一下``paddle.utils.run_check()``看看paddle安装的正确性

**Comment by zhiyongLiu1114** [comment]
> 执行一下`paddle.utils.run_check()`看看paddle安装的正确性
你好，以下是执行细节：

λ da338ee893f7 /home python
Python 3.7.0 (default, May  7 2022, 07:55:29) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0323 08:53:25.492139 35668 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W0323 08:53:25.503839 35668 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/utils/install_check.py", line 269, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/utils/install_check.py", line 173, in _run_static_single
    exe.run(startup_prog)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1459, in run
    return_merged=return_merged)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1662, in _run_impl
    return_numpy)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/executor.py", line 632, in run
    fetch_list)._move_to_list()
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/utils/install_check.py", line 36, in _simple_network
      attr=paddle.ParamAttr(initializer=paddle.nn.initializer.Constant(0.1)))
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 153, in create_parameter
      default_initializer)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 385, in create_parameter
      **attr._to_kwargs(with_initializer=True))
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3965, in create_parameter
      initializer(param, self)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 56, in __call__
      return self.forward(param, block)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 193, in forward
      stop_gradient=True)
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4023, in append_op
      attrs=kwargs.get("attrs", None),
    File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2858, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDA error(2), out of memory. 
      [Hint: Please search for the error code(2) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/core/cuda_stream.h:73)
      [operator < fill_constant > error]
>>> exit()

以下是GPU情况：
![image](https://user-images.githubusercontent.com/47651345/227148595-eb20f089-4556-4557-94e4-781a7df4dc02.png)

**Comment by simplew2011** [comment]
同问题，paddle.utils.run_check()是正常的
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/66729924/7b15a7d1-af15-4ce6-9e5e-e2555a7e7fab)

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/66729924/ceb6e110-f7e3-4a38-8dd2-a90a434c34cb)
