### ISSUE TITLE
[Question]: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (5.1.0)/charset_normalizer (3.1.0) doesn't match a supported version!  ImportError cannot import name 'inference' from 'paddle' 

### ISSUE THREAD

**Issue by MonCac** [PaddlePaddle/PaddleNLP#5421]
### 请提出你的问题

/Library/Python/3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (5.1.0)/charset_normalizer (3.1.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/Users/moncheri/Downloads/PaddleNLP-develop/applications/question_answering/unsupervised_qa/run_pipelines_example.py", line 19, in <module>
    from pipelines.document_stores import FAISSDocumentStore
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/pipelines/__init__.py", line 39, in <module>
    from pipelines import pipelines, utils
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/pipelines/pipelines/__init__.py", line 15, in <module>
    from pipelines.pipelines.base import Pipeline, RootNode
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/pipelines/pipelines/base.py", line 52, in <module>
    from pipelines.nodes.base import BaseComponent  # isort: skip
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/pipelines/nodes/__init__.py", line 15, in <module>
    from pipelines.utils.import_utils import safe_import  # isort: skip
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/pipelines/utils/__init__.py", line 15, in <module>
    from pipelines.utils.preprocessing import convert_files_to_dicts, tika_convert_files_to_dicts
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/pipelines/utils/preprocessing.py", line 21, in <module>
    from pipelines.nodes.file_converter import (
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/pipelines/nodes/file_converter/__init__.py", line 36, in <module>
    from pipelines.nodes.file_converter.image import ImageToTextConverter
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/pipelines/nodes/file_converter/image.py", line 21, in <module>
    from paddleocr import PaddleOCR
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/paddleocr/paddleocr.py", line 37, in <module>
    from tools.infer import predict_system
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/paddleocr/tools/infer/predict_system.py", line 31, in <module>
    import tools.infer.utility as utility
  File "/Users/moncheri/Library/Python/3.9/lib/python/site-packages/paddleocr/tools/infer/utility.py", line 24, in <module>
    from paddle import inference
ImportError: cannot import name 'inference' from 'paddle' (/Users/moncheri/Library/Python/3.9/lib/python/site-packages/paddle/__init__.py)

**Comment by w5688414** [comment]
我测了一下没啥问题：
<img width="544" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/12107462/3123e9b2-7eb2-4433-8a32-defe62b05566">

请升级一下paddle版本试一下
