### ISSUE TITLE
[Bug]: UnboundLocalError: local variable 'paddle2onnx' referenced before assignment

### ISSUE THREAD

**Issue by sunetic** [PaddlePaddle/PaddleNLP#5433]
### 软件环境

```Markdown
paddle-bfloat                  0.1.7
paddle-serving-app             0.8.3
paddle-serving-client          0.8.3
paddle2onnx                    1.0.5
paddleaudio                    1.1.0
paddleclas                     2.5.1
paddlefsl                      1.1.0
paddlehub                      2.3.1
paddlenlp                      2.5.2
paddleocr                      2.6.1.1
paddlepaddle-gpu               2.4.1.post112
paddleslim                     2.3.4
paddlespeech                   1.3.0
paddlespeech-ctcdecoders       0.2.1
paddlespeech-feat              0.1.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
按照文档操作：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/document

得到报错：


W0328 00:23:38.642962 21812 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0328 00:23:38.739926 21812 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[2023-03-28 00:23:39,621] [    INFO] - All model checkpoint weights were used when initializing UIEX.

[2023-03-28 00:23:39,621] [    INFO] - All the weights of UIEX were initialized from the model checkpoint at ./checkpoint/model_best.
If your task is similar to the task the model of the checkpoint was trained on, you can already use UIEX for predictions without further training.
[2023-03-28 00:23:39,622] [    INFO] - Converting to the inference model cost a little time.
[2023-03-28 00:23:54,592] [    INFO] - The inference model save in the path:./checkpoint/model_best/static/inference
[2023-03-28 00:23:54,592] [ WARNING] - The inference precision is change to 'fp32', please install the dependencies that required for 'fp16' inference, pip install onnxruntime-gpu onnx onnxconverter-common
Traceback (most recent call last):
  File "predict.py", line 6, in <module>
    my_ie = Taskflow("information_extraction", model="uie-x-base", schema=schema, task_path='./checkpoint/model_best', precision='fp16')
  File "/opt/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/taskflow.py", line 837, in __init__
    self.task_instance = task_class(
  File "/opt/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/information_extraction.py", line 536, in __init__
    self._get_inference_model()
  File "/opt/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/task.py", line 368, in _get_inference_model
    self._prepare_onnx_mode()
  File "/opt/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/task.py", line 246, in _prepare_onnx_mode
    onnx_model = paddle2onnx.command.c_paddle_to_onnx(
UnboundLocalError: local variable 'paddle2onnx' referenced before assignment
```

### 稳定复现步骤 & 代码

```
from pprint import pprint
from paddlenlp import Taskflow
from paddlenlp.utils.doc_parser import DocParser

schema = ['os_al','os_k','od_al','od_k']
my_ie = Taskflow("information_extraction", model="uie-x-base", schema=schema, task_path='./checkpoint/model_best', precision='fp16')

doc_path = "/tmp/WechatIMG8337.jpeg"
results = my_ie({"doc": doc_path})
pprint(results)

DocParser.write_image_with_results(
    doc_path,
    result=results[0],
    save_path="./image_show.png")
```

**Comment by zhuqiang00099** [comment]
怎么解决的？

**Comment by zhuqiang00099** [comment]
请问怎么解决的 @sunzhaoyang

**Comment by sunetic** [comment]
@zhuqiang00099 你看下输出，有几个 onnx 的包需要安装

```
pip install onnxruntime-gpu onnx onnxconverter-common
```

**Comment by hheyang** [comment]
去掉precision='fp16'
