### ISSUE TITLE
[Question]: 官方docker部署后运行paddlenlp报错ModuleNotFoundError: No module named 'paddle.distributed.fleet.layers'

### ISSUE THREAD

**Issue by XYZliang** [PaddlePaddle/PaddleNLP#5495]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/59312540/229082299-a4df875c-54f5-4c2c-afc8-3dcba86c75fa.png)
使用最新的docker镜像paddlecloud/paddlenlp:develop-gpu-cuda10.2-cudnn7-latest

**Comment by chanlong** [comment]
me too

**Comment by w5688414** [comment]
请试试这个paddle的镜像：

```
nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.4.2-gpu-cuda10.2-cudnn7.6-trt7.0
```
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

**Comment by AlphaHinex** [comment]
使用 `paddlecloud/paddlenlp:develop-gpu-cuda11.2-cudnn8-e72fb9` 镜像，也有这个问题：

```bash
>>> from paddlenlp import Taskflow
/usr/local/lib/python3.7/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/PaddleNLP/paddlenlp/__init__.py", line 35, in <module>
    from . import (
  File "/home/PaddleNLP/paddlenlp/data/__init__.py", line 16, in <module>
    from .data_collator import *
  File "/home/PaddleNLP/paddlenlp/data/data_collator.py", line 25, in <module>
    from ..transformers import BertTokenizer
  File "/home/PaddleNLP/paddlenlp/transformers/__init__.py", line 88, in <module>
    from .ernie_ctm.modeling import *
  File "/home/PaddleNLP/paddlenlp/transformers/ernie_ctm/modeling.py", line 25, in <module>
    from paddlenlp.layers.crf import LinearChainCrf, LinearChainCrfLoss
  File "/home/PaddleNLP/paddlenlp/layers/__init__.py", line 21, in <module>
    from .lora import *
  File "/home/PaddleNLP/paddlenlp/layers/lora.py", line 25, in <module>
    from paddle.distributed.fleet.layers.mpu import mp_ops
ModuleNotFoundError: No module named 'paddle.distributed.fleet.layers'
```

在容器里把 `paddlepaddle-gpu` 从 `2.3.0` 升级到 `2.4.2`（注意 cuda 版本，如 `python -m pip install paddlepaddle-gpu==2.4.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`）后，就没有这个问题了
