### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by zxcvbnm29** [PaddlePaddle/PaddleNLP#5506]
### 请提出你的问题

在运行train.py有以下问题，有那位大神指点一下

 r/special_tokens_map.json
Traceback (most recent call last):
  File "train.py", line 244, in <module>
    do_train()
  File "train.py", line 216, in do_train
    loss.backward()
AttributeError: 'NoneType' object has no attribute 'backward'

**Comment by westfish** [comment]
请参考别的issue提供更多信息
