### ISSUE TITLE
No module named 'paddle.utils.cpp_extension'

### ISSUE THREAD

**Issue by greathelin** [PaddlePaddle/PaddleNLP#551]
Traceback (most recent call last):
  File "D:/HelinFiles/Study/Study-PaddleNLP/code/Text-Similarity-Matching/test/test01.py", line 8, in <module>
    import paddlenlp
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlenlp\__init__.py", line 20, in <module>
    from . import ops
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlenlp\ops\__init__.py", line 15, in <module>
    from .transformer.decoding import *
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlenlp\ops\transformer\decoding.py", line 24, in <module>
    from paddlenlp.ops.ext_utils import load
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddlenlp\ops\ext_utils.py", line 25, in <module>
    from paddle.utils.cpp_extension import load_op_meta_info_and_register_op
ModuleNotFoundError: No module named 'paddle.utils.cpp_extension'

**Comment by guoshengCS** [comment]
这个可能是paddle的版本低了，可以试下使用Paddle 2.1.0 版本

**Comment by greathelin** [comment]
的确是版本太低的原因，已经从2.0更新到2.1了
