### ISSUE TITLE
[Question]: Pegasus模型转换为静态图后不启用FastGeneration直接使用GPU推理报错

### ISSUE THREAD

**Issue by loveandbeepbrother** [PaddlePaddle/PaddleNLP#5512]
### 加载FastGeneration可以正常推理，注释掉load("FastGeneration", verbose=True)直接采用GPU推理时报错

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_7031/1011285127.py in <module>
      1 args = setup_args()
----> 2 predictor = setup_predictor(args)
      3 tokenizer = PegasusChineseTokenizer.from_pretrained("pegasus_out")

/tmp/ipykernel_7031/4132981211.py in setup_predictor(args)
     27     config.disable_glog_info()
     28 
---> 29     predictor = inference.create_predictor(config)
     30     return predictor
     31 

RuntimeError: (NotFound) Operator (fusion_pegasus_decoding) is not registered.
  [Hint: op_info_ptr should not be null.] (at /paddle/paddle/fluid/framework/op_info.h:151)

**Comment by gongel** [comment]
你好，这个是静态图推理，已经适配了FastGeneration，暂时不能去除FastGeneration。如果需要动态图的预测，可以参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_summarization/finetune/predict.py

**Comment by wanglaiqi** [comment]
基于pegasus模型的动态图转静态图不成功。 报以下错误
/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
INFO:__main__:/home/wanglaiqi/mywork/AbstractModel/pegasus
W0522 08:10:19.204491 3028112 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0522 08:10:19.208184 3028112 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
2023-05-22 08:10:29,606 - INFO - Using Python interpreter: /home/wanglaiqi/miniconda3/envs/pytorch_env/bin/python3, version: Python 3.7.13
INFO:utils.cpp_extension:Using Python interpreter: /home/wanglaiqi/miniconda3/envs/pytorch_env/bin/python3, version: Python 3.7.13
2023-05-22 08:10:29,607 - INFO - execute command: cd /home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration && /home/wanglaiqi/miniconda3/envs/pytorch_env/bin/python3 FastGeneration_setup.py build
INFO:utils.cpp_extension:execute command: cd /home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration && /home/wanglaiqi/miniconda3/envs/pytorch_env/bin/python3 FastGeneration_setup.py build
running build
running build_ext
-- Assign GPU architecture (sm=70,75,80)
-- BOOST_TAR: boost_1_41_0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- Add DCUDA11_MODE
-- PADDLE_VERSION: 2.3.2

-- Configuring done
-- Generating done
-- Build files have been written to: /home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37
[  2%] Performing update step for 'extern_fastertransformer'
Already on 'nccl_dependent_refine'
M	CMakeLists.txt
M	fastertransformer/CMakeLists.txt
M	fastertransformer/bert_encoder_transformer.h
M	fastertransformer/cuda/attention_kernels.cu
M	fastertransformer/cuda/attention_kernels.cuh
M	fastertransformer/cuda/cuda_kernels.cu
M	fastertransformer/cuda/cuda_kernels.h
M	fastertransformer/cuda/decoding_kernels.cu
M	fastertransformer/cuda/masked_multihead_attention.cu
M	fastertransformer/cuda/masked_multihead_attention.h
M	fastertransformer/cuda/masked_multihead_attention_utils.h
M	fastertransformer/cuda/online_softmax_beamsearch_kernels.cu
M	fastertransformer/cuda/open_attention.cu
M	fastertransformer/cuda/open_attention.h
M	fastertransformer/cuda/open_decoder.cu
M	fastertransformer/cuda/open_decoder.cuh
M	fastertransformer/cuda/topk_kernels.cu
M	fastertransformer/cuda/topk_kernels.cuh
M	fastertransformer/cuda/transformer_kernels.cu
M	fastertransformer/cuda/transformer_kernels.cuh
M	fastertransformer/decoding_beamsearch.h
M	fastertransformer/decoding_sampling.h
M	fastertransformer/gpt.h
M	fastertransformer/open_decoder.h
M	fastertransformer/standard_encoder.h
M	fastertransformer/utils/allocator.h
M	fastertransformer/utils/arguments.h
M	fastertransformer/utils/common.h
M	fastertransformer/utils/common_structure.h
Your branch is up to date with 'origin/nccl_dependent_refine'.
Updated 29 paths from the index
[  4%] Performing configure step for 'extern_fastertransformer'
-- Add DCUDA11_MODE
-- Assign GPU architecture (sm=70,75,80)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/build/fastertransformer
[  6%] Performing build step for 'extern_fastertransformer'
Scanning dependencies of target topk
[  2%] Building CUDA object fastertransformer/cuda/CMakeFiles/topk.dir/topk_kernels.cu.o
[  4%] Linking CUDA device code CMakeFiles/topk.dir/cmake_device_link.o
[  6%] Linking CUDA static library ../../lib/libtopk.a
[  6%] Built target topk
Scanning dependencies of target nccl_utils
[  8%] Building CXX object fastertransformer/utils/CMakeFiles/nccl_utils.dir/nccl_utils.cpp.o
[ 11%] Linking CUDA device code CMakeFiles/nccl_utils.dir/cmake_device_link.o
[ 13%] Linking CXX static library ../../lib/libnccl_utils.a
[ 13%] Built target nccl_utils
Scanning dependencies of target transformer_kernels
[ 15%] Building CUDA object fastertransformer/cuda/CMakeFiles/transformer_kernels.dir/transformer_kernels.cu.o
[ 17%] Linking CUDA device code CMakeFiles/transformer_kernels.dir/cmake_device_link.o
[ 20%] Linking CUDA static library ../../lib/libtransformer_kernels.a
[ 20%] Built target transformer_kernels
Scanning dependencies of target attention_kernels
[ 22%] Building CUDA object fastertransformer/cuda/CMakeFiles/attention_kernels.dir/attention_kernels.cu.o
[ 24%] Linking CUDA device code CMakeFiles/attention_kernels.dir/cmake_device_link.o
[ 26%] Linking CUDA static library ../../lib/libattention_kernels.a
[ 26%] Built target attention_kernels
Scanning dependencies of target cuda_kernels
[ 28%] Building CUDA object fastertransformer/cuda/CMakeFiles/cuda_kernels.dir/cuda_kernels.cu.o
[ 31%] Linking CUDA device code CMakeFiles/cuda_kernels.dir/cmake_device_link.o
[ 33%] Linking CUDA static library ../../lib/libcuda_kernels.a
[ 33%] Built target cuda_kernels
[ 40%] Built target nvtx_utils
Scanning dependencies of target decoder
[ 42%] Building CUDA object fastertransformer/cuda/CMakeFiles/decoder.dir/open_decoder.cu.o
[ 44%] Building CUDA object fastertransformer/cuda/CMakeFiles/decoder.dir/masked_multihead_attention.cu.o
[ 46%] Linking CUDA device code CMakeFiles/decoder.dir/cmake_device_link.o
[ 48%] Linking CXX static library ../../lib/libdecoder.a
[ 48%] Built target decoder
Scanning dependencies of target online_softmax_beamsearch
[ 51%] Building CUDA object fastertransformer/cuda/CMakeFiles/online_softmax_beamsearch.dir/online_softmax_beamsearch_kernels.cu.o
[ 53%] Linking CUDA device code CMakeFiles/online_softmax_beamsearch.dir/cmake_device_link.o
[ 55%] Linking CUDA static library ../../lib/libonline_softmax_beamsearch.a
[ 55%] Built target online_softmax_beamsearch
Scanning dependencies of target encoder_gemm_func
[ 57%] Building CXX object fastertransformer/gemm_test/CMakeFiles/encoder_gemm_func.dir/encoder_gemm_func.cc.o
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc: In function ‘int fastertransformer::printPerfStructure(int, int, int, int, int, int, int, const fastertransformer::customMatmulPerf_t&, FILE*, int, int)’:
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:36:56: error: ‘CUBLASLT_ALGO_CONFIG_STAGES_ID’ was not declared in this scope; did you mean ‘CUBLASLT_ALGO_CONFIG_TILE_ID’?
   36 |     cublasLtMatmulAlgoConfigGetAttribute( matmulAlgo,  CUBLASLT_ALGO_CONFIG_STAGES_ID, &stages, sizeof(stages), NULL);
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                        CUBLASLT_ALGO_CONFIG_TILE_ID
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc: In function ‘int fastertransformer::LtHgemmCustomFind(cublasLtHandle_t, int, int, int, int, int, int, int, const T*, const T*, const T*, const T*, T*, void*, size_t, FILE*, fastertransformer::customMatmulPerf_t*, int)’:
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:192:5: error: ‘cublasComputeType_t’ was not declared in this scope; did you mean ‘cublasDataType_t’?
  192 |     cublasComputeType_t computeType;
      |     ^~~~~~~~~~~~~~~~~~~
      |     cublasDataType_t
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:200:7: error: ‘computeType’ was not declared in this scope
  200 |       computeType = CUBLAS_COMPUTE_32F;
      |       ^~~~~~~~~~~
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:200:21: error: ‘CUBLAS_COMPUTE_32F’ was not declared in this scope
  200 |       computeType = CUBLAS_COMPUTE_32F;
      |                     ^~~~~~~~~~~~~~~~~~
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:207:7: error: ‘computeType’ was not declared in this scope
  207 |       computeType = CUBLAS_COMPUTE_16F;
      |       ^~~~~~~~~~~
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:207:21: error: ‘CUBLAS_COMPUTE_16F’ was not declared in this scope
  207 |       computeType = CUBLAS_COMPUTE_16F;
      |                     ^~~~~~~~~~~~~~~~~~
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:216:55: error: ‘computeType’ was not declared in this scope
  216 |     status = cublasLtMatmulDescCreate(&operationDesc, computeType, scaleType); //  creates a matrix multiply descriptor
      |                                                       ^~~~~~~~~~~
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:263:50: error: ‘CUBLASLT_ALGO_CAP_STAGES_IDS’ was not declared in this scope; did you mean ‘CUBLASLT_ALGO_CAP_TILE_IDS’?
  263 |         cublasLtMatmulAlgoCapGetAttribute(&algo, CUBLASLT_ALGO_CAP_STAGES_IDS, NULL, 0, &sizeWritten);
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  CUBLASLT_ALGO_CAP_TILE_IDS
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:267:26: error: ‘CUBLASLT_MATMUL_STAGES_UNDEFINED’ was not declared in this scope; did you mean ‘CUBLASLT_MATMUL_TILE_UNDEFINED’?
  267 |             stagesA[0] = CUBLASLT_MATMUL_STAGES_UNDEFINED;
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          CUBLASLT_MATMUL_TILE_UNDEFINED
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:286:57: error: ‘CUBLASLT_ALGO_CONFIG_STAGES_ID’ was not declared in this scope; did you mean ‘CUBLASLT_ALGO_CONFIG_TILE_ID’?
  286 |             cublasLtMatmulAlgoConfigSetAttribute(&algo, CUBLASLT_ALGO_CONFIG_STAGES_ID, &stagesA[stagesIdx], sizeof(stagesA[stagesIdx]));
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                         CUBLASLT_ALGO_CONFIG_TILE_ID
make[5]: *** [fastertransformer/gemm_test/CMakeFiles/encoder_gemm_func.dir/build.make:63: fastertransformer/gemm_test/CMakeFiles/encoder_gemm_func.dir/encoder_gemm_func.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:552: fastertransformer/gemm_test/CMakeFiles/encoder_gemm_func.dir/all] Error 2
make[3]: *** [Makefile:84: all] Error 2
make[2]: *** [CMakeFiles/extern_fastertransformer.dir/build.make:112: third-party/src/extern_fastertransformer-stamp/extern_fastertransformer-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/extern_fastertransformer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
[33m[2023-05-22 08:35:29,295] [ WARNING][0m - FastGeneration is not available due to build errors.[0m
Traceback (most recent call last):
  File "FastGeneration_setup.py", line 11, in <module>
    output_dir=r'/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration')
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 198, in build_extensions
    ext.build_with_command(self)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 176, in build_with_command
    raise e
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 165, in build_with_command
    super(FasterTransformerExtension, self).build_with_command(ext_builder)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 116, in build_with_command
    ["cmake", "--build", "."] + build_args, cwd=ext_builder.build_temp, stdout=stdout, stderr=stdout
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
Namespace(decoding_strategy='beam_search', diversity_rate=0.0, export_output_dir='./model_inference/pegasus_base', length_penalty=0.0, max_out_len=200, min_out_len=1, model_name_or_path='./model_output/pegasus_base', num_beams=4, num_return_sequence=1, num_return_sequences=1, temperature=1.0, topk=4, topp=1.0, use_fp16_decoding=False)
Compiling user custom op, it will cost a few seconds.....
Traceback (most recent call last):
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1148, in run_cmd
    command, shell=True, stderr=subprocess.STDOUT)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration && /home/wanglaiqi/miniconda3/envs/pytorch_env/bin/python3 FastGeneration_setup.py build' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_model.py", line 131, in <module>
    do_predict(args)
  File "export_model.py", line 75, in do_predict
    pegasus = FasterPegasus(model=model, use_fp16_decoding=args.use_fp16_decoding, trans_out=True)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/fast_transformer/transformer/fast_transformer.py", line 1818, in __init__
    hidden_act=model.pegasus.config["activation_function"],
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/fast_transformer/transformer/decoding.py", line 4316, in __init__
    load("FastGeneration", verbose=True)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 53, in _impl
    func(*args, **kwargs)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 307, in load
    _jit_compile(file_path, verbose)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1112, in _jit_compile
    run_cmd(compile_cmd, verbose)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1154, in run_cmd
    compile, error))
RuntimeError: Failed to run command: <built-in function compile>, errors: Command 'cd /home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration && /home/wanglaiqi/miniconda3/envs/pytorch_env/bin/python3 FastGeneration_setup.py build' returned non-zero exit status 1.
