### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by whalefa1I** [PaddlePaddle/PaddleNLP#5576]
### 软件环境

```Markdown
paddle-bfloat            0.1.7
paddle2onnx              1.0.6
paddlefsl                1.1.0
paddlenlp                2.5.2.post0
paddlepaddle-gpu         2.4.2.post112
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述
使用
[GLM-10b](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/glm/README.md#large-%E6%A8%A1%E5%9E%8B%E5%A4%9A%E5%8D%A1%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC%E6%A8%A1%E5%9E%8B%E5%B9%B6%E8%A1%8C%E7%AD%96%E7%95%A5)训练lora后，在推理时报错：
```Markdown

Traceback (most recent call last):
  File "/opt/anaconda3/envs/glm-10b/lib/python3.8/site-packages/paddlenlp/layers/lora.py", line 763, in __getattr__
    return super().__getattr__(name)  # defer to nn.Layer's logic
  File "/opt/anaconda3/envs/glm-10b/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1234, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'LoRAModel' object has no attribute 'infer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/glm-10b/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 521, in __getattr__
    return super(PretrainedModel, self).__getattr__(name)
  File "/opt/anaconda3/envs/glm-10b/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1234, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'GLMForConditionalGeneration' object has no attribute 'infer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 3, in predict
  File "<stdin>", line 2, in infer
  File "/opt/anaconda3/envs/glm-10b/lib/python3.8/site-packages/paddlenlp/layers/lora.py", line 765, in __getattr__
    return getattr(self.model, name)
  File "/opt/anaconda3/envs/glm-10b/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 523, in __getattr__
    result = getattr(self.config, name)
  File "/opt/anaconda3/envs/glm-10b/lib/python3.8/site-packages/paddlenlp/transformers/configuration_utils.py", line 487, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'GLMConfig' object has no attribute 'infer'
```

### 稳定复现步骤 & 代码

```
from paddlenlp.transformers import AutoModelForConditionalGeneration,AutoTokenizer
from paddlenlp.layers import LoRAConfig, LoRAModel
model = AutoModelForConditionalGeneration.from_pretrained("THUDM/glm-10b-chinese",output_predict=True,parallel_output=True,load_state_as_np=True)
tokenizer = AutoTokenizer.from_pretrained("THUDM/glm-10b-chinese")
lora_config = LoRAConfig(target_modules=[".*query_key_value.*"],r=4,lora_alpha=8,merge_weights=True,enable_lora_list=[[True, False, True]],)
runtime = LoRAModel.from_pretrained(model, lora_config)
runtime.eval()
all_texts = ["答案：年基准利率4.35%，上下文：从实际看,贷款的基本条件是: 一是中国大陆居民,年龄在60岁以下; 二是有稳定的住址和工作或经营地点; 三是有稳定的收入来源; 四是无不良信用记录,贷款用途不能作为炒股,赌博等行为; 五是具有完全民事行为能力。在已知答案的前提下，问题：","答案：U系列，上下文：U系列是最好的，采用国际顶尖技术（由格力自主研发）双级变频压缩机，提高压缩机运转效率，制冷制热能力更强劲；1赫兹变频技术，使空调相当于一个15 W电灯泡，更加节能省电；送风面积广，风力大；生态风，净化空气。非常不错，现在国美在做活动，可以了解一下。在已知答案的前提下，问题：",]

def preprocess(input_text):
    input_text = [text.strip() + "[gMASK]" for text in input_text]
    inputs = tokenizer(
        input_text,
        return_tensors="np",
        add_special_tokens=True,
        padding=True,
        max_length=500,
        truncation=True,
        truncation_side="left",
    )
    inputs = tokenizer.build_inputs_for_generation(inputs, max_gen_length=20)
    return inputs

def infer(input_map):
    results = runtime.infer(dict(input_map))
    return results

def postprocess(infer_data):
    result = []
    for x in infer_data[0].tolist():
        print(tokenizer.all_special_ids)
        res = tokenizer.decode(x, skip_special_tokens=True)
        result.append(res)
    out_dict = {"result": result}
    return out_dict

def predict(texts):
    input_map = preprocess(texts)
    infer_result = infer(input_map)
    output = postprocess(infer_result)
    return output

batch_texts = batchfy_text(all_texts, batch_size)
for bs, texts in enumerate(batch_texts):
    outputs = predict(texts)
    for text, result in zip(texts, outputs["result"]):
        print("{} \n {}".format(text, result))
```

**Comment by xieyu0214** [comment]
@whalefa1I 请问您在加载训练GLM-10b-chinese模型时 显存占用多少啊？ 我这里做finetune时 显存占用才9G ，感觉很奇怪

**Comment by lugimzzz** [comment]
def infer(input_map):
    results = runtime.infer(dict(input_map))
    return results
这个用法有问题啊，model肯定没有infer这个函数，应该是model.generate,可以参考predict_generation.py中用法

**Comment by RileyShe** [comment]
> @whalefa1I 请问您在加载训练GLM-10b-chinese模型时 显存占用多少啊？ 我这里做finetune时 显存占用才9G ，感觉很奇怪

我的这个问题 能给解答一下吗 @lugimzzz
