### ISSUE TITLE
[Question]: UIE 启动微调训练报错

### ISSUE THREAD

**Issue by atczyh** [PaddlePaddle/PaddleNLP#5582]
### 请提出你的问题

python finetune.py   --train_path ./data/train.txt  --dev_path ./data/dev.txt  --output_dir I://NLPcheckpoint4//  --learning_rate 1e-5  --per_device_train_batch_size 3 --per_device_eval_batch_size 3     --save_steps 200 --model_name_or_path uie-base   --device gpu  --do_train --do_eval --num_train_epochs 100
[2023-04-09 20:56:47,126] [    INFO] - ***** Running training *****
[2023-04-09 20:56:47,128] [    INFO] -   Num examples = 5474
[2023-04-09 20:56:47,130] [    INFO] -   Num Epochs = 100
[2023-04-09 20:56:47,135] [    INFO] -   Instantaneous batch size per device = 3
[2023-04-09 20:56:47,137] [    INFO] -   Total train batch size (w. parallel, distributed & accumulation) = 3
[2023-04-09 20:56:47,140] [    INFO] -   Gradient Accumulation steps = 1
[2023-04-09 20:56:47,142] [    INFO] -   Total optimization steps = 182500.0
[2023-04-09 20:56:47,146] [    INFO] -   Total num train samples = 547400.0
[2023-04-09 20:56:47,237] [    INFO] -   Number of trainable parameters = 117946370
Traceback (most recent call last):
  File "finetune.py", line 263, in <module>
    main()
  File "finetune.py", line 194, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "D:\Program Files\Python\Python38\lib\site-packages\paddlenlp\trainer\trainer.py", line 599, in train
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "D:\Program Files\Python\Python38\lib\site-packages\paddlenlp\trainer\trainer_callback.py", line 355, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "D:\Program Files\Python\Python38\lib\site-packages\paddlenlp\trainer\trainer_callback.py", line 396, in call_event
    result = getattr(callback, event)(
  File "D:\Program Files\Python\Python38\lib\site-packages\paddlenlp\trainer\integrations.py", line 94, in on_train_begin
    self._init_summary_writer(args, log_dir)
  File "D:\Program Files\Python\Python38\lib\site-packages\paddlenlp\trainer\integrations.py", line 85, in _init_summary_writer
    self.vdl_writer = self._LogWriter(logdir=log_dir)
  File "D:\Program Files\Python\Python38\lib\site-packages\visualdl\writer\writer.py", line 108, in __init__
    self._get_file_writer()
  File "D:\Program Files\Python\Python38\lib\site-packages\visualdl\writer\writer.py", line 123, in _get_file_writer
    self._file_writer = RecordFileWriter(
  File "D:\Program Files\Python\Python38\lib\site-packages\visualdl\writer\record_writer.py", line 89, in __init__
    if not bfile.exists(logdir):
  File "D:\Program Files\Python\Python38\lib\site-packages\visualdl\io\bfile.py", line 691, in exists
    return default_file_factory.get_filesystem(path).exists(path)
  File "D:\Program Files\Python\Python38\lib\site-packages\visualdl\io\bfile.py", line 80, in get_filesystem
    raise ValueError("No recognized filesystem for prefix %s" % prefix)
ValueError: No recognized filesystem for prefix I

**Comment by atczyh** [comment]
--output_dir I://NLPcheckpoint4// 路径无法识别，改成 --output_dir I:/NLPcheckpoint4/ 正常运行
