### ISSUE TITLE
[Question]: GLM-10b-Chinese模型 有20G大小，单卡加载训练时 只占显存9G，这正常吗？？

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#5600]
### 请提出你的问题

在使用 ..example / glm/ finetune_generation.py  脚本进行 finetune glm-10b-chinese模型是，只占9个G显存， 这正常吗？？ 在 finetune glm-2b模型时 就占至少了20个G。

paddlenlp                2.5.2.post0
paddlepaddle-gpu         0.0.0.post117

**Comment by lugimzzz** [comment]
不正常，你正常训练起来了吗，有打印出相关的log吗

**Comment by xieyu0214** [comment]
> 不正常，你正常训练起来了吗，有打印出相关的log吗

训练起来了 ，loss 也正常下降，没有报错信息

**Comment by xieyu0214** [comment]
> > 不正常，你正常训练起来了吗，有打印出相关的log吗
> 
> 训练起来了 ，loss 也正常下降，没有报错信息



> 不正常，你正常训练起来了吗，有打印出相关的log吗

可以正常训练，loss也下降， 最后模型保存报错了

Traceback (most recent call last):
  File ".../tasks/glm/finetune_generation.py", line 172, in <module>
    main()
  File ".../tasks/glm/finetune_generation.py", line 161, in main
    trainer.save_model(merge_tensor_parallel=training_args.tensor_parallel_degree > 1)
TypeError: save_model() got an unexpected keyword argument 'merge_tensor_parallel'

@lugimzzz

**Comment by lugimzzz** [comment]
一个指标参考：
双卡+lora+fp16+recompute (bs=16，src_length=512, tgt_length=25,    min_tgt_length=8)
GLM-10b-Chinese 每张卡显存占用 23913MiB

**Comment by lugimzzz** [comment]
要用develop版本的paddlenlp，你拉取最新的代码

**Comment by xieyu0214** [comment]
> 要用develop版本的paddlenlp，你拉取最新的代码

[2023-04-11 16:32:51,672] [    INFO] - We are using <class 'paddlenlp.transformers.glm.tokenizer.GLMChineseTokenizer'> to load '.../pretrained_models/THUDM_glm/glm-10b-chinese'.
[2023-04-11 16:32:51,700] [    INFO] - Adding <|startoftext|> to the vocabulary
[2023-04-11 16:32:51,701] [    INFO] - Adding <|endoftext|> to the vocabulary
[2023-04-11 16:32:51,701] [    INFO] - Adding [SEP] to the vocabulary
[2023-04-11 16:32:51,701] [    INFO] - Adding [CLS] to the vocabulary
[2023-04-11 16:32:51,701] [    INFO] - Adding [MASK] to the vocabulary
[2023-04-11 16:32:51,701] [    INFO] - Adding <|startofpiece|> to the vocabulary
[2023-04-11 16:32:51,701] [    INFO] - Adding <|endofpiece|> to the vocabulary
[2023-04-11 16:32:51,701] [    INFO] - Adding [gMASK] to the vocabulary
[2023-04-11 16:32:51,701] [    INFO] - Adding [sMASK] to the vocabulary
[2023-04-11 16:32:51,701] [    INFO] - Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[2023-04-11 16:32:54,968] [    INFO] - Using half precision
[2023-04-11 16:32:54,986] [    INFO] - ============================================================
[2023-04-11 16:32:54,987] [    INFO] -     Training Configuration Arguments
[2023-04-11 16:32:54,987] [    INFO] - paddle commit id              :58d5af008b9365150fbd51a9d2d18b2d9748ca22
[2023-04-11 16:32:54,987] [    INFO] - _no_sync_in_gradient_accumulation:True
[2023-04-11 16:32:54,987] [    INFO] - adam_beta1                    :0.9
[2023-04-11 16:32:54,987] [    INFO] - adam_beta2                    :0.999
[2023-04-11 16:32:54,987] [    INFO] - adam_epsilon                  :1e-08
[2023-04-11 16:32:54,987] [    INFO] - bf16                          :False
[2023-04-11 16:32:54,987] [    INFO] - bf16_full_eval                :False
[2023-04-11 16:32:54,987] [    INFO] - current_device                :gpu:0
[2023-04-11 16:32:54,988] [    INFO] - data_parallel_rank            :0
[2023-04-11 16:32:54,988] [    INFO] - dataloader_drop_last          :False
[2023-04-11 16:32:54,988] [    INFO] - dataloader_num_workers        :0
[2023-04-11 16:32:54,988] [    INFO] - dataset_rank                  :0
[2023-04-11 16:32:54,988] [    INFO] - dataset_world_size            :1
[2023-04-11 16:32:54,988] [    INFO] - device                        :gpu
[2023-04-11 16:32:54,988] [    INFO] - disable_tqdm                  :False
[2023-04-11 16:32:54,988] [    INFO] - do_eval                       :False
[2023-04-11 16:32:54,988] [    INFO] - do_export                     :False
[2023-04-11 16:32:54,988] [    INFO] - do_predict                    :False
[2023-04-11 16:32:54,988] [    INFO] - do_train                      :True
[2023-04-11 16:32:54,988] [    INFO] - eval_accumulation_steps       :None
[2023-04-11 16:32:54,988] [    INFO] - eval_batch_size               :2
[2023-04-11 16:32:54,988] [    INFO] - eval_steps                    :4
[2023-04-11 16:32:54,989] [    INFO] - evaluation_strategy           :IntervalStrategy.NO
[2023-04-11 16:32:54,989] [    INFO] - flatten_param_grads           :False
[2023-04-11 16:32:54,989] [    INFO] - fp16                          :True
[2023-04-11 16:32:54,989] [    INFO] - fp16_full_eval                :False
[2023-04-11 16:32:54,989] [    INFO] - fp16_opt_level                :O1
[2023-04-11 16:32:54,989] [    INFO] - gradient_accumulation_steps   :8
[2023-04-11 16:32:54,989] [    INFO] - greater_is_better             :None
[2023-04-11 16:32:54,989] [    INFO] - ignore_data_skip              :False
[2023-04-11 16:32:54,989] [    INFO] - label_names                   :None
[2023-04-11 16:32:54,989] [    INFO] - label_smoothing               :0.1
[2023-04-11 16:32:54,989] [    INFO] - lazy_data_processing          :True
[2023-04-11 16:32:54,989] [    INFO] - learning_rate                 :3e-05
[2023-04-11 16:32:54,989] [    INFO] - load_best_model_at_end        :False
[2023-04-11 16:32:54,989] [    INFO] - local_process_index           :0
[2023-04-11 16:32:54,990] [    INFO] - local_rank                    :-1
[2023-04-11 16:32:54,990] [    INFO] - log_level                     :-1
[2023-04-11 16:32:54,990] [    INFO] - log_level_replica             :-1
[2023-04-11 16:32:54,990] [    INFO] - log_on_each_node              :True
[2023-04-11 16:32:54,990] [    INFO] - logging_dir                   :./checkpoints/glm-10b-chinese/runs/Apr11_16-31-59_localhost.localdomain
[2023-04-11 16:32:54,990] [    INFO] - logging_first_step            :False
[2023-04-11 16:32:54,990] [    INFO] - logging_steps                 :100
[2023-04-11 16:32:54,990] [    INFO] - logging_strategy              :IntervalStrategy.STEPS
[2023-04-11 16:32:54,990] [    INFO] - lr_decay_ratio                :0.1
[2023-04-11 16:32:54,990] [    INFO] - lr_scheduler_type             :SchedulerType.LINEAR
[2023-04-11 16:32:54,990] [    INFO] - max_grad_norm                 :1.0
[2023-04-11 16:32:54,990] [    INFO] - max_steps                     :-1
[2023-04-11 16:32:54,990] [    INFO] - metric_for_best_model         :None
[2023-04-11 16:32:54,990] [    INFO] - minimum_eval_times            :None
[2023-04-11 16:32:54,991] [    INFO] - no_cuda                       :False
[2023-04-11 16:32:54,991] [    INFO] - num_train_epochs              :3.0
[2023-04-11 16:32:54,991] [    INFO] - optim                         :OptimizerNames.ADAMW
[2023-04-11 16:32:54,991] [    INFO] - optimizer_name_suffix         :None
[2023-04-11 16:32:54,991] [    INFO] - output_dir                    :./checkpoints/glm-10b-chinese
[2023-04-11 16:32:54,991] [    INFO] - overwrite_output_dir          :False
[2023-04-11 16:32:54,991] [    INFO] - past_index                    :-1
[2023-04-11 16:32:54,991] [    INFO] - per_device_eval_batch_size    :2
[2023-04-11 16:32:54,991] [    INFO] - per_device_train_batch_size   :2
[2023-04-11 16:32:54,991] [    INFO] - prediction_loss_only          :False
[2023-04-11 16:32:54,991] [    INFO] - process_index                 :0
[2023-04-11 16:32:54,991] [    INFO] - recompute                     :True
[2023-04-11 16:32:54,992] [    INFO] - remove_unused_columns         :True
[2023-04-11 16:32:54,992] [    INFO] - report_to                     :['visualdl']
[2023-04-11 16:32:54,992] [    INFO] - resume_from_checkpoint        :None
[2023-04-11 16:32:54,992] [    INFO] - run_name                      :./checkpoints/glm-10b-chinese
[2023-04-11 16:32:54,992] [    INFO] - save_on_each_node             :False
[2023-04-11 16:32:54,992] [    INFO] - save_steps                    :10
[2023-04-11 16:32:54,992] [    INFO] - save_strategy                 :IntervalStrategy.STEPS
[2023-04-11 16:32:54,992] [    INFO] - save_total_limit              :None
[2023-04-11 16:32:54,992] [    INFO] - scale_loss                    :32768
[2023-04-11 16:32:54,993] [    INFO] - seed                          :42
[2023-04-11 16:32:54,993] [    INFO] - sharding                      :[]
[2023-04-11 16:32:54,993] [    INFO] - sharding_degree               :-1
[2023-04-11 16:32:54,993] [    INFO] - sharding_parallel_degree      :-1
[2023-04-11 16:32:54,993] [    INFO] - sharding_parallel_rank        :0
[2023-04-11 16:32:54,993] [    INFO] - should_log                    :True
[2023-04-11 16:32:54,993] [    INFO] - should_save                   :True
[2023-04-11 16:32:54,993] [    INFO] - skip_memory_metrics           :True
[2023-04-11 16:32:54,993] [    INFO] - tensor_parallel_degree        :-1
[2023-04-11 16:32:54,993] [    INFO] - tensor_parallel_rank          :0
[2023-04-11 16:32:54,993] [    INFO] - train_batch_size              :2
[2023-04-11 16:32:54,993] [    INFO] - use_hybrid_parallel           :False
[2023-04-11 16:32:54,994] [    INFO] - warmup_ratio                  :0.06
[2023-04-11 16:32:54,994] [    INFO] - warmup_steps                  :0
[2023-04-11 16:32:54,994] [    INFO] - weight_decay                  :0.1
[2023-04-11 16:32:54,994] [    INFO] - weight_name_suffix            :None
[2023-04-11 16:32:54,994] [    INFO] - world_size                    :1
[2023-04-11 16:32:54,994] [    INFO] -
[2023-04-11 16:32:54,996] [    INFO] - ***** Running training *****
[2023-04-11 16:32:54,997] [    INFO] -   Num examples = 23668
[2023-04-11 16:32:54,997] [    INFO] -   Num Epochs = 3
[2023-04-11 16:32:54,997] [    INFO] -   Instantaneous batch size per device = 2
[2023-04-11 16:32:54,997] [    INFO] -   Total train batch size (w. parallel, distributed & accumulation) = 16
[2023-04-11 16:32:54,997] [    INFO] -   Gradient Accumulation steps = 8
[2023-04-11 16:32:54,997] [    INFO] -   Total optimization steps = 4437.0
[2023-04-11 16:32:54,997] [    INFO] -   Total num train samples = 71004.0
[2023-04-11 16:32:55,007] [    INFO] -   Number of trainable parameters = 355659776 (per device)
  0%|▏                                                                              | 10/4437 [00:32<3:49:03,  3.10s/it][2023-04-11 16:33:27,424] [    INFO] - Saving model checkpoint to ./checkpoints/glm-10b-chinese/checkpoint-10
[2023-04-11 16:33:27,434] [    INFO] - Configuration saved in ./checkpoints/glm-10b-chinese/checkpoint-10/config.json
[2023-04-11 16:33:29,661] [    INFO] - tokenizer config file saved in ./checkpoints/glm-10b-chinese/checkpoint-10/tokenizer_config.json
[2023-04-11 16:33:29,661] [    INFO] - Special tokens file saved in ./checkpoints/glm-10b-chinese/checkpoint-10/special_tokens_map.json
[2023-04-11 16:33:29,661] [    INFO] - added tokens file saved in ./checkpoints/glm-10b-chinese/checkpoint-10/added_tokens.json
  0%|▎                                                                              | 20/4437 [01:10<3:54:26,  3.18s/it][2023-04-11 16:34:05,204] [    INFO] - Saving model checkpoint to ./checkpoints/glm-10b-chinese/checkpoint-20
[2023-04-11 16:34:05,217] [    INFO] - Configuration saved in ./checkpoints/glm-10b-chinese/checkpoint-20/config.json
[2023-04-11 16:34:07,181] [    INFO] - tokenizer config file saved in ./checkpoints/glm-10b-chinese/checkpoint-20/tokenizer_config.json
[2023-04-11 16:34:07,182] [    INFO] - Special tokens file saved in ./checkpoints/glm-10b-chinese/checkpoint-20/special_tokens_map.json
[2023-04-11 16:34:07,182] [    INFO] - added tokens file saved in ./checkpoints/glm-10b-chinese/checkpoint-20/added_tokens.json
  1%|▌                                                                              | 30/4437 [01:47<3:53:17,  3.18s/it][2023-04-11 16:34:42,795] [    INFO] - Saving model checkpoint to ./checkpoints/glm-10b-chinese/checkpoint-30
[2023-04-11 16:34:42,808] [    INFO] - Configuration saved in ./checkpoints/glm-10b-chinese/checkpoint-30/config.json
[2023-04-11 16:34:45,237] [    INFO] - tokenizer config file saved in ./checkpoints/glm-10b-chinese/checkpoint-30/tokenizer_config.json
[2023-04-11 16:34:45,238] [    INFO] - Special tokens file saved in ./checkpoints/glm-10b-chinese/checkpoint-30/special_tokens_map.json
[2023-04-11 16:34:45,238] [    INFO] - added tokens file saved in ./checkpoints/glm-10b-chinese/checkpoint-30/added_tokens.json
  1%|▋                                                                              | 40/4437 [02:25<3:52:58,  3.18s/it][2023-04-11 16:35:20,565] [    INFO] - Saving model checkpoint to ./checkpoints/glm-10b-chinese/checkpoint-40
[2023-04-11 16:35:20,575] [    INFO] - Configuration saved in ./checkpoints/glm-10b-chinese/checkpoint-40/config.json
[2023-04-11 16:35:22,997] [    INFO] - tokenizer config file saved in ./checkpoints/glm-10b-chinese/checkpoint-40/tokeni


@lugimzzz  刚拉下来最新develop代码，paddlepaddle-GPU 也是 develop 版本， 依然是在单张3090卡 占显存9G 训练中。。。
能不能看得出问题在哪呀

**Comment by lugimzzz** [comment]
你确定一下加载是10b模型参数吗

**Comment by xieyu0214** [comment]
> 你确定一下加载是10b模型参数吗

是10b模型，模型是在你们官网下载的 `https://paddlenlp.bj.bcebos.com/models/community/THUDM/glm-10b-chinese.pdparams` 

看上面的日志信息 “[2023-04-11 16:32:55,007] [ INFO] - Number of trainable parameters = 355659776 (per device)” ， 但是我只设置的1张卡（ CUDA_VISIBLE_DEVICES="2" sh train.sh）。 
@lugimzzz 
有没有可能是你们官网的模型 不是完整的模型呢？

**Comment by lugimzzz** [comment]
你看一下模型权重大小，
![image](https://user-images.githubusercontent.com/63761690/231151041-c1f3fc9f-dd3e-4ed8-af65-0b5715664b31.png)
![image](https://user-images.githubusercontent.com/63761690/231152144-108574a2-9503-47e7-9967-c3c43d5e94fd.png)

**Comment by lugimzzz** [comment]
```
from paddlenlp.transformers import  GLMForConditionalGeneration
model_name = "THUDM/glm-10b-chinese"
model = GLMForConditionalGeneration.from_pretrained(model_name,output_predict=True,parallel_output=True,load_state_as_np=True,low_cpu_mem_usage=True,dtype="float16")
```
只加载模型至少也要19799MiB

**Comment by xieyu0214** [comment]
我下载下来的模型也是19G, 而且代码也是用你们的脚本。

我看原来加载的方式：
    model = AutoModelForConditionalGeneration.from_pretrained(
        model_args.model_name_or_path,
        output_predict=True,
        parallel_output=True,
        load_state_as_np=True,
        # low_cpu_mem_usage=True, # todo enable low_cpu_mem_usage=True
        dtype=dtype,  # todo enable set dtype to avoid additional mem usage
        tensor_parallel_degree=training_args.tensor_parallel_degree,
        tensor_parallel_rank=training_args.tensor_parallel_rank,
    )
 
@lugimzzz    用你上面回复的方式也试了，依然用9G显存在训练了 。。

**Comment by xieyu0214** [comment]
> 我下载下来的模型也是19G, 而且代码也是用你们的脚本。
> 
> 我看原来加载的方式： model = AutoModelForConditionalGeneration.from_pretrained( model_args.model_name_or_path, output_predict=True, parallel_output=True, load_state_as_np=True, # low_cpu_mem_usage=True, # todo enable low_cpu_mem_usage=True dtype=dtype, # todo enable set dtype to avoid additional mem usage tensor_parallel_degree=training_args.tensor_parallel_degree, tensor_parallel_rank=training_args.tensor_parallel_rank, )
> 
> @lugimzzz 用你上面回复的方式也试了，依然用9G显存在训练了 。。



发现有 warning：[2023-04-12 09:45:23,875] [ WARNING] - Some weights of the model checkpoint at /root/nlp/xieyu/pretrained_models/THUDM_glm/glm-10b-chinese were not used when initializing GLMForConditionalGeneration: ['glm.transformer.layers.41.input_layernorm.bias', 'glm.transformer.layers.39.attention.query_key_value.bias', 'glm.transformer.layers.38.mlp.dense_4h_to_h.weight', 'glm.transformer.layers.39.attention.query_key_value.weight', 'glm.transformer.layers.35.input_layernorm.weight', 'glm.transformer.layers.24.mlp.dense_4h_to_h.weight', 'glm.transformer.layers.32.post_attention_layernorm.bias', 'glm.transformer.layers.44.post_attention_layernorm.weight', 'glm.transformer.layers.29.mlp.dense_4h_to_h.weight',  .....


@lugimzzz   模型加载的时候 很多权重没有正常初始化，这个会不会有影响呀

**Comment by lugimzzz** [comment]
你看一下config文件是不是有问题，建议直接把原目录删除，重新下载

**Comment by xieyu0214** [comment]
> 你看一下config文件是不是有问题，建议直接把原目录删除，重新下载

确实 是配置有问题！ 看起来是large模型的配置。谢谢

**Comment by ljtlrh** [comment]
GLM-10b_Chinese 如何多卡部署
