### ISSUE TITLE
[Question]: AI studio 上调用模型微调出错

### ISSUE THREAD

**Issue by cuyoo** [PaddlePaddle/PaddleNLP#5651]
### 请提出你的问题

运行的
!python finetune.py  \
    --device gpu \
    --logging_steps 5 \
    --save_steps 25 \
    --eval_steps 25 \
    --seed 42 \
    --model_name_or_path uie-x-base \
    --output_dir ./checkpoint/model_best \
    --train_path medical_checklist/train.txt \
    --dev_path medical_checklist/dev.txt  \
    --per_device_train_batch_size  16 \
    --per_device_eval_batch_size 16 \
    --num_train_epochs 5 \
    --learning_rate 1e-5 \
    --label_names 'start_positions' 'end_positions' \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir ./checkpoint/model_best \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1

输出的：
[2023-04-13 14:54:34,163] [ WARNING] - evaluation_strategy reset to IntervalStrategy.STEPS for do_eval is True. you can also set evaluation_strategy='epoch'.
[2023-04-13 14:54:34,164] [    INFO] - The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
[2023-04-13 14:54:34,164] [    INFO] - ============================================================
[2023-04-13 14:54:34,165] [    INFO] -      Model Configuration Arguments      
[2023-04-13 14:54:34,165] [    INFO] - paddle commit id              :3fa7a736e32508e797616b6344d97814c37d3ff8
[2023-04-13 14:54:34,165] [    INFO] - export_model_dir              :./checkpoint/model_best
[2023-04-13 14:54:34,165] [    INFO] - model_name_or_path            :uie-x-base
[2023-04-13 14:54:34,165] [    INFO] - 
[2023-04-13 14:54:34,165] [    INFO] - ============================================================
[2023-04-13 14:54:34,165] [    INFO] -       Data Configuration Arguments      
[2023-04-13 14:54:34,165] [    INFO] - paddle commit id              :3fa7a736e32508e797616b6344d97814c37d3ff8
[2023-04-13 14:54:34,165] [    INFO] - dev_path                      :medical_checklist/dev.txt
[2023-04-13 14:54:34,166] [    INFO] - max_seq_len                   :512
[2023-04-13 14:54:34,166] [    INFO] - train_path                    :medical_checklist/train.txt
[2023-04-13 14:54:34,166] [    INFO] - 
[2023-04-13 14:54:34,166] [ WARNING] - Process rank: -1, device: gpu, world_size: 1, distributed training: False, 16-bits training: False
[2023-04-13 14:54:34,168] [    INFO] - Model config ErnieLayoutConfig {
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "coordinate_size": 128,
  "enable_recompute": false,
  "eos_token_id": 2,
  "fuse": false,
  "gradient_checkpointing": false,
  "has_relative_attention_bias": true,
  "has_spatial_attention_bias": true,
  "has_visual_segment_embedding": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "image_feature_pool_shape": [
    7,
    7,
    256
  ],
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_2d_position_embeddings": 1024,
  "max_position_embeddings": 514,
  "max_rel_2d_pos": 256,
  "max_rel_pos": 128,
  "model_type": "ernie_layout",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_past": true,
  "pad_token_id": 1,
  "paddlenlp_version": null,
  "pool_act": "tanh",
  "rel_2d_pos_bins": 64,
  "rel_pos_bins": 32,
  "shape_size": 128,
  "task_id": 0,
  "task_type_vocab_size": 3,
  "type_vocab_size": 100,
  "use_task_id": true,
  "vocab_size": 250002
}

Traceback (most recent call last):
  File "finetune.py", line 192, in <module>
    main()
  File "finetune.py", line 106, in main
    model = UIEX.from_pretrained(model_args.model_name_or_path)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 485, in from_pretrained
    pretrained_model_name_or_path, from_hf_hub=from_hf_hub, subfolder=subfolder, *args, **kwargs
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 1358, in from_pretrained_v2
    model_state_dict = paddle.load(model_weight_file, return_numpy=load_state_as_np)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py", line 1055, in load
    load_result[key], config.return_numpy
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py", line 455, in _ndarray_to_tensor
    return paddle.to_tensor(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py", line 546, in to_tensor
    return _to_tensor_non_static(data, dtype, place, stop_gradient)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py", line 411, in _to_tensor_non_static
    stop_gradient=stop_gradient,
OSError: (External) CUDA error(214), uncorrectable ECC error encountered. 
  [Hint: Please search for the error code(214) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/fluid/platform/device/gpu/gpu_info.cc:142)

**Comment by 1649759610** [comment]
你好，这是什么案例呢？有重启AiStudio吗？

**Comment by cuyoo** [comment]
> 

重启了好几次呢。

案例是这个，我自己标注了新的数据。转换成功了，就是微调出现上面的问题。
https://aistudio.baidu.com/aistudio/projectdetail/5676627

**Comment by 1649759610** [comment]
项目看起来没有权限，在开发机上运行是否出现上述问题？

**Comment by cuyoo** [comment]
我什么都没动，现在居然好了，不知道为啥。
可能是资源冲突问题？
因为昨天启动运行环境经常不够，高级GPU-V100 16GB/32GB基本都没有，后来除了CPU其他都没了。
后来又有了，然后就又运行正常了，之前没运行过。

**Comment by cuyoo** [comment]
可能是底层其他偶发问题，现在已经不是问题。
