### ISSUE TITLE
uie-m-large 模型推理时报错 ，能够成功执行微调训练

### ISSUE THREAD

**Issue by 526872163** [PaddlePaddle/PaddleNLP#5695]
### 请提出你的问题

Traceback (most recent call last):
File "C:\tender\main.py", line 43, in
ie = Taskflow('information_extraction', schema=schema, position_prob=0.3,
File "C:\Users\Administrator\anaconda3\envs\tender\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 837, in init
self.task_instance = task_class(
File "C:\Users\Administrator\anaconda3\envs\tender\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 536, in init
self._get_inference_model()
File "C:\Users\Administrator\anaconda3\envs\tender\lib\site-packages\paddlenlp\taskflow\task.py", line 366, in _get_inference_model
self._prepare_static_mode()
File "C:\Users\Administrator\anaconda3\envs\tender\lib\site-packages\paddlenlp\taskflow\task.py", line 221, in _prepare_static_mode
self.predictor = paddle.inference.create_predictor(self._config)
RuntimeError: (Unavailable) An error occurred while loading model parameters. Please check whether the model file is complete or damaged.
[Hint: Expected static_cast(*buffer) == true, but received static_cast(*buffer):0 != true:1.] (at ..\paddle/fluid/operators/load_combine_op.h:86)
[operator < load_combine > error]

Process finished with exit code 1

测试过很多软件版本和cuda版本，显卡是3090 24G，内存32G，请问是显存或者内存不足导致的吗，

**Comment by wawltor** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/16698950/232488476-9394c7fc-7a37-4f30-9b30-1dcd64d30552.png">
微调后的模型是完整的模型吗？

**Comment by 526872163** [comment]
是完整的模型，没有微调前的模型也运行不了，从新下载也报相同的错误，已经根据之前的回答尝试重新下载新模型，其他模型：例如 uie-base uie-m-base 都能成功推理，唯有uie-m-large报错，会不会是显存或内存不足？

**Comment by wawltor** [comment]
> 是完整的模型，没有微调前的模型也运行不了，从新下载也报相同的错误，已经根据之前的回答尝试重新下载新模型，其他模型：例如 uie-base uie-m-base 都能成功推理，唯有uie-m-large报错，会不会是显存或内存不足？

可以再确认一下重新下载的模型参数md5值是否一样；显存不足也有可能，需要排查一下是否OOM了
