### ISSUE TITLE
[Question]: Ernie-vil2模型微调，测试集用acc评估，文搜图的label用的index，index是文本数据中【sep】token的下标，这个评测label是写错了吧？

### ISSUE THREAD

**Issue by will-wiki** [PaddlePaddle/PaddleNLP#5714]
### 请提出你的问题

文搜图的评测label应该用具体的batch中的索引吧

**Comment by will-wiki** [comment]
另外还有个问题，用paddle.distributed微调ernie-vil2模型，按照github推荐的脚本没啥问题，但是没有做测试集的评估，修改了下加入了测试集的评估
```
python -u -m paddle.distributed.launch --gpus "4,5" \
                --log_dir ${log_dir}  \
                run_finetune.py --output_dir output_pd \
                --train_data=${train_data} \
                --val_data=${val_data} \
                --do_train \
                --do_eval \
                --learning_rate 5e-5 \
                --warmup_steps 100 \
                --logging_steps 50 \
                --per_device_eval_batch_size  128 \
                --per_device_train_batch_size 128 \
                --dataloader_num_workers 8 \
                --eval_step 300 \
                --save_steps 300 \
                --num_train_epochs 5 \
                --weight_decay 0.001 \
                --save_total_limit 5 \
                --seed 1 \
                --label_names index \
                --data_root ./data \
                --lr_scheduler_type cosine \
                --load_best_model_at_end \
                --metric_for_best_model eval_accuracy \
                --greater_is_better true \
                --recompute
```
报错了，看样子是测试集两卡的变量不在同一个cuda上，想请教下这个需要怎么修改呢
```
Traceback (most recent call last):
  File "run_finetune.py", line 121, in <module>
    do_train()
  File "run_finetune.py", line 111, in do_train
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/CodeSpace/Ernie-paddlenlp/ERNIE-ViL2/PaddleNLP-Ernievil2/model_zoo/ernie-vil2.0/env37/lib/python3.7/site-packages/paddlenlp/trainer/trainer.py", line 716, in train
    self._maybe_log_save_evaluate(tr_loss, model, epoch, ignore_keys_for_eval, inputs=inputs)
  File "/home/CodeSpace/Ernie-paddlenlp/ERNIE-ViL2/PaddleNLP-Ernievil2/model_zoo/ernie-vil2.0/env37/lib/python3.7/site-packages/paddlenlp/trainer/trainer.py", line 848, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/home/CodeSpace/Ernie-paddlenlp/ERNIE-ViL2/PaddleNLP-Ernievil2/model_zoo/ernie-vil2.0/env37/lib/python3.7/site-packages/paddlenlp/trainer/trainer.py", line 1616, in evaluate
    metric_key_prefix=metric_key_prefix,
  File "/home/CodeSpace/Ernie-paddlenlp/ERNIE-ViL2/PaddleNLP-Ernievil2/model_zoo/ernie-vil2.0/env37/lib/python3.7/site-packages/paddlenlp/trainer/trainer.py", line 1739, in evaluation_loop
    labels = self._nested_gather(labels)
  File "/home/CodeSpace/Ernie-paddlenlp/ERNIE-ViL2/PaddleNLP-Ernievil2/model_zoo/ernie-vil2.0/env37/lib/python3.7/site-packages/paddlenlp/trainer/trainer.py", line 1954, in _nested_gather
    tensors = distributed_concat(tensors)
  File "/home/CodeSpace/Ernie-paddlenlp/ERNIE-ViL2/PaddleNLP-Ernievil2/model_zoo/ernie-vil2.0/env37/lib/python3.7/site-packages/paddlenlp/trainer/utils/helper.py", line 44, in distributed_concat
    dist.all_gather(output_tensors, tensor)
  File "/home/CodeSpace/Ernie-paddlenlp/ERNIE-ViL2/PaddleNLP-Ernievil2/model_zoo/ernie-vil2.0/env37/lib/python3.7/site-packages/paddle/distributed/collective.py", line 953, in all_gather
    task = group.process_group.all_gather(tensor, out)
ValueError: (InvalidArgument) All inputs should be in CudaPlace.
  [Hint: Expected CheckTensorsInCudaPlace(in_tensors) == true, but received CheckTensorsInCudaPlace(in_tensors):0 != true:1.] (at /paddle/paddle/fluid/distributed/collective/ProcessGroupNCCL.cc:950)
```

**Comment by will-wiki** [comment]
hello，请问有人吗
