### ISSUE TITLE
[Question]: text_to_image训练显存消耗过大 

### ISSUE THREAD

**Issue by zhangvia** [PaddlePaddle/PaddleNLP#5717]
### 请提出你的问题

我使用了ppdiffusers/examples/text_to_image_laion400m/中的训练脚本，训练命令即该文件夹下的单机多卡命令。其中修改了batchsize为4，机子是4张4090，batchsize为4的时候单张显存消耗已经达到14g以上。这真的能在40g的机子上16的batchsize跑起来？我使用了fp16后，显存消耗并没有明显变化

**Comment by JunnYu** [comment]
你好可以的，我这里训练的图像分辨率是256x256，显存占用快到了40G，但不会OOM，当前不太推荐使用fp16进行训练。
bs=8，256x256，需要32062MiB的显存，你可以开启recompute以求节省显存。

**Comment by zhangvia** [comment]
> 你好可以的，我这里训练的图像分辨率是256x256，显存占用快到了40G，但不会OOM，当前不太推荐使用fp16进行训练。 bs=8，256x256，需要32062MiB的显存，你可以开启recompute以求节省显存。

那在a100 40g上bs最多也只能调10，还是感觉有点小。另外想问下多机多卡下是采用的socket通信是吗，支持IB网络吗

**Comment by zhangvia** [comment]
> 你好可以的，我这里训练的图像分辨率是256x256，显存占用快到了40G，但不会OOM，当前不太推荐使用fp16进行训练。 bs=8，256x256，需要32062MiB的显存，你可以开启recompute以求节省显存。
另外想问一下，开启多机多卡训练，是不是需要在每台机子上部署项目的依赖环境以及项目代码？

**Comment by gg22mm** [comment]
报错怎么回事？
![图片](https://github.com/PaddlePaddle/PaddleNLP/assets/6648329/a4d76e92-982b-4000-9176-235e66adb56c)

2023-07-19 14:47:55,488] [    INFO] - world_size                    : 1
[2023-07-19 14:47:55,488] [    INFO] - 
Set <class 'ppdiffusers.models.vae.Encoder'> recompute False
Set <class 'ppdiffusers.models.vae.Decoder'> recompute False
Set <class 'paddle.nn.layer.transformer.TransformerEncoder'> recompute False
Set <class 'ppdiffusers.models.unet_2d_blocks.CrossAttnDownBlock2D'> recompute False
Set <class 'ppdiffusers.models.unet_2d_blocks.CrossAttnDownBlock2D'> recompute False
Set <class 'ppdiffusers.models.unet_2d_blocks.CrossAttnDownBlock2D'> recompute False
Set <class 'ppdiffusers.models.unet_2d_blocks.DownBlock2D'> recompute False
Set <class 'ppdiffusers.models.unet_2d_blocks.UpBlock2D'> recompute False
Set <class 'ppdiffusers.models.unet_2d_blocks.CrossAttnUpBlock2D'> recompute False
Set <class 'ppdiffusers.models.unet_2d_blocks.CrossAttnUpBlock2D'> recompute False
Set <class 'ppdiffusers.models.unet_2d_blocks.CrossAttnUpBlock2D'> recompute False
[2023-07-19 14:47:55,500] [    INFO] - ***** Running training *****
[2023-07-19 14:47:55,501] [    INFO] -   Num examples = 4000000000
[2023-07-19 14:47:55,501] [    INFO] -   Num Epochs = 9223372036854775807
[2023-07-19 14:47:55,501] [    INFO] -   Instantaneous batch size per device = 2
[2023-07-19 14:47:55,501] [    INFO] -   Total train batch size (w. parallel, distributed & accumulation) = 4
[2023-07-19 14:47:55,501] [    INFO] -   Gradient Accumulation steps = 2
[2023-07-19 14:47:55,501] [    INFO] -   Total optimization steps = 1000000000
[2023-07-19 14:47:55,501] [    INFO] -   Total num train samples = 4000000000
[2023-07-19 14:47:55,512] [    INFO] -   Number of trainable parameters = 1415195844 (per device)
  0%|                                                                                                                                                                                                                  | 0/1000000000 [00:00<?, ?it/s]dataset 0, local_rank: 0, worker_id: 0, worker_global_id: 0, file_range: (0, 60000)
lengths of self.file_ids in random_load: [60000]
Traceback (most recent call last):
  File "train_txt2img_laion400m_trainer.py", line 107, in <module>
    Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 536, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 674, in _get_data
    batch.reraise()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 172, in reraise
    raise self.exc_type(msg)
FileNotFoundError: DataLoader worker(0) caught FileNotFoundError with message:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 339, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 91, in fetch
    data.append(next(self.dataset_iter))
  File "/home/aistudio/PaddleNLP/ppdiffusers/examples/text_to_image_laion400m/ldm/text_image_pair_dataset.py", line 196, in shuffle
    buffer_list.append(next(iterator))
  File "/home/aistudio/PaddleNLP/ppdiffusers/examples/text_to_image_laion400m/ldm/text_image_pair_dataset.py", line 191, in random_load_from_multi_dataset
    yield next(sample_loader)
  File "/home/aistudio/PaddleNLP/ppdiffusers/examples/text_to_image_laion400m/ldm/text_image_pair_dataset.py", line 144, in sample_loader
    with gzip.open(filename, "rb") if filename.endswith(".gz") else open(filename, "rb") as f:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/laion400m/part-40583.gz'

main()

  File "train_txt2img_laion400m_trainer.py", line 101, in main
    trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/trainer/trainer.py", line 668, in train
    for step, inputs in enumerate(epoch_iterator):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 745, in __next__
    self._reader.read_next_list()[0])
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:175)

  0%|                                                                                                                                                                                                                  | 0/1000000000 [00:00<?, ?it/s]
aistudio@jupyter-3341709-6551183:~/PaddleNLP/ppdiffusers/examples/text_to_image_laion400m$ 


---------------


aistudio@jupyter-3341709-6551183:~/PaddleNLP/ppdiffusers/examples/text_to_image_laion400m$ pip list
Package                        Version
------------------------------ ---------------
absl-py                        0.8.1
aiofiles                       23.1.0
aiohttp                        3.8.3
aiosignal                      1.2.0
alembic                        1.8.1
altair                         4.2.0
antlr4-python3-runtime         4.9.3
anyio                          3.6.1
argon2-cffi                    21.3.0
argon2-cffi-bindings           21.2.0
aspy.yaml                      1.3.0
astor                          0.8.1
astroid                        2.4.1
async-generator                1.10
async-timeout                  4.0.2
asynctest                      0.13.0
attrs                          22.1.0
audioread                      2.1.8
autopep8                       1.6.0
Babel                          2.12.1
backcall                       0.1.0
backports.zoneinfo             0.2.1
bce-python-sdk                 0.8.53
beautifulsoup4                 4.11.1
bleach                         5.0.1
blinker                        1.5
cachetools                     4.0.0
certifi                        2019.9.11
certipy                        0.1.3
cffi                           1.15.1
cfgv                           2.0.1
chardet                        3.0.4
charset-normalizer             2.1.1
click                          8.0.4
cloudpickle                    1.6.0
cma                            2.7.0
colorama                       0.4.4
colorlog                       4.1.0
commonmark                     0.9.1
cryptography                   38.0.1
cycler                         0.10.0
Cython                         0.29
datasets                       2.7.0
debugpy                        1.6.0
decorator                      4.4.2
defusedxml                     0.7.1
dill                           0.3.3
easydict                       1.9
entrypoints                    0.4
et-xmlfile                     1.0.1
fastapi                        0.95.0
fastjsonschema                 2.16.1
ffmpy                          0.3.0
filelock                       3.0.12
fire                           0.5.0
flake8                         4.0.1
Flask                          2.2.5
flask-babel                    3.1.0
Flask-Cors                     3.0.8
forbiddenfruit                 0.1.3
frozenlist                     1.3.0
fsspec                         2022.11.0
ftfy                           6.1.1
funcsigs                       1.0.2
future                         0.18.0
gast                           0.3.3
gitdb                          4.0.5
GitPython                      3.1.14
google-auth                    1.10.0
google-auth-oauthlib           0.4.1
gradio                         3.19.1
graphviz                       0.13
greenlet                       1.1.3
grpcio                         1.35.0
gunicorn                       20.0.4
gym                            0.12.1
h11                            0.14.0
h5py                           2.9.0
httpcore                       0.16.3
httpx                          0.23.3
huggingface-hub                0.16.4
identify                       1.4.10
idna                           2.8
imageio                        2.6.1
imageio-ffmpeg                 0.3.0
importlib-metadata             4.2.0
importlib-resources            5.9.0
ipykernel                      6.9.1
ipython                        7.34.0
ipython-genutils               0.2.0
ipywidgets                     7.6.5
isort                          4.3.21
itsdangerous                   2.1.2
jdcal                          1.4.1
jedi                           0.17.2
jieba                          0.42.1
Jinja2                         3.1.2
joblib                         0.14.1
JPype1                         0.7.2
json5                          0.9.5
jsonschema                     4.16.0
jupyter-archive                3.2.1
jupyter_client                 7.3.5
jupyter-core                   4.11.1
jupyter-lsp                    1.5.1
jupyter-server                 1.16.0
jupyter-telemetry              0.1.0
jupyterhub                     1.3.0
jupyterlab                     3.4.5
jupyterlab-language-pack-zh-CN 3.4.post1
jupyterlab-pygments            0.2.2
jupyterlab-server              2.10.3
jupyterlab-widgets             3.0.3
kiwisolver                     1.1.0
lazy-object-proxy              1.4.3
librosa                        0.7.2
lightgbm                       3.1.1
linkify-it-py                  2.0.0
llvmlite                       0.31.0
lxml                           4.9.1
Mako                           1.2.2
Markdown                       3.1.1
markdown-it-py                 2.2.0
MarkupSafe                     2.1.3
matplotlib                     2.2.3
matplotlib-inline              0.1.6
mccabe                         0.6.1
mdit-py-plugins                0.3.3
mdurl                          0.1.1
mistune                        0.8.4
more-itertools                 7.2.0
moviepy                        1.0.1
multidict                      6.0.2
multiprocess                   0.70.11.1
nbclassic                      0.3.1
nbclient                       0.5.13
nbconvert                      6.4.4
nbformat                       5.5.0
nest-asyncio                   1.5.5
netifaces                      0.10.9
networkx                       2.4
nltk                           3.4.5
nodeenv                        1.3.4
notebook                       5.7.0
numba                          0.48.0
numpy                          1.19.5
oauthlib                       3.1.0
objgraph                       3.4.1
omegaconf                      2.3.0
opencv-python                  4.6.0.66
openpyxl                       3.0.5
opt-einsum                     3.3.0
orjson                         3.8.7
packaging                      21.3
paddle-bfloat                  0.1.7
paddle2onnx                    1.0.0
paddlefsl                      1.1.0
paddlehub                      2.3.0
paddlenlp                      2.6.0rc0
paddlepaddle-gpu               2.4.0.post112
pamela                         1.0.0
pandas                         1.1.5
pandocfilters                  1.5.0
parl                           1.4.1
parso                          0.7.1
pathlib                        1.0.1
pexpect                        4.7.0
pickleshare                    0.7.5
Pillow                         8.2.0
pip                            22.1.2
pkgutil_resolve_name           1.3.10
plotly                         5.8.0
pluggy                         1.0.0
ppdiffusers                    0.16.1
pre-commit                     1.21.0
prettytable                    0.7.2
proglog                        0.1.9
prometheus-client              0.14.1
prompt-toolkit                 2.0.10
protobuf                       3.20.2
psutil                         5.7.2
ptyprocess                     0.7.0
py4j                           0.10.9.2
pyarrow                        10.0.0
pyasn1                         0.4.8
pyasn1-modules                 0.2.7
pybboxes                       0.1.1
pycodestyle                    2.8.0
pycparser                      2.21
pycryptodome                   3.9.9
pydantic                       1.10.6
pydeck                         0.8.0
pydocstyle                     5.0.2
pydub                          0.25.1
pyflakes                       2.4.0
pyglet                         1.4.5
Pygments                       2.13.0
pyhumps                        3.8.0
pylint                         2.5.2
Pympler                        1.0.1
pynvml                         8.0.4
pyOpenSSL                      22.0.0
pyparsing                      3.0.9
pypmml                         0.9.11
pyrsistent                     0.18.1
python-dateutil                2.8.2
python-json-logger             2.0.4
python-jsonrpc-server          0.3.4
python-language-server         0.33.0
python-lsp-jsonrpc             1.0.0
python-lsp-server              1.5.0
python-multipart               0.0.6
pytz                           2023.3
pytz-deprecation-shim          0.1.0.post0
PyYAML                         5.1.2
pyzmq                          23.2.1
rarfile                        3.1
recordio                       0.1.7
regex                          2023.6.3
requests                       2.24.0
requests-oauthlib              1.3.0
resampy                        0.2.2
responses                      0.18.0
rfc3986                        1.5.0
rich                           12.6.0
rope                           0.17.0
rsa                            4.0
ruamel.yaml                    0.17.21
ruamel.yaml.clib               0.2.6
safetensors                    0.3.1
sahi                           0.10.1
scikit-learn                   0.24.2
scipy                          1.6.3
seaborn                        0.10.0
semver                         2.13.0
Send2Trash                     1.8.0
sentencepiece                  0.1.96
seqeval                        1.2.2
setuptools                     56.2.0
shapely                        2.0.0
shellcheck-py                  0.7.1.1
simplegeneric                  0.8.1
six                            1.16.0
sklearn                        0.0
smmap                          3.0.5
sniffio                        1.3.0
snowballstemmer                2.0.0
SoundFile                      0.10.3.post1
soupsieve                      2.3.2.post1
SQLAlchemy                     1.4.41
starlette                      0.26.1
streamlit                      1.13.0
streamlit-image-comparison     0.0.3
tabulate                       0.8.3
tb-nightly                     1.15.0a20190801
tb-paddle                      0.3.6
tenacity                       8.0.1
tensorboard                    2.1.0
tensorboardX                   1.8
termcolor                      1.1.0
terminado                      0.15.0
terminaltables                 3.1.10
testpath                       0.4.2
threadpoolctl                  2.1.0
tinycss2                       1.1.1
toml                           0.10.0
toolz                          0.12.0
tornado                        6.2
tqdm                           4.64.1
traitlets                      5.4.0
typed-ast                      1.4.1
typer                          0.9.0
typing_extensions              4.3.0
tzdata                         2022.7
tzlocal                        4.2
uc-micro-py                    1.0.1
ujson                          1.35
urllib3                        1.25.11
uvicorn                        0.21.1
validators                     0.20.0
virtualenv                     16.7.9
visualdl                       2.5.3
watchdog                       2.2.0
wcwidth                        0.2.6
webencodings                   0.5.1
websocket-client               1.4.1
websockets                     10.4
Werkzeug                       2.2.3
whatthepatch                   1.0.2
wheel                          0.36.2
widgetsnbextension             3.5.2
wrapt                          1.12.1
xarray                         0.16.2
xgboost                        1.3.3
xlrd                           1.2.0
xxhash                         3.1.0
yapf                           0.26.0
yarl                           1.7.2
zipp                           3.8.1
