### ISSUE TITLE
[Question]:  pipe.apply_lora  :doesn't stop gradient can't use inplace strategy

### ISSUE THREAD

**Issue by wuliebucha** [PaddlePaddle/PaddleNLP#5723]
### 请提出你的问题

**code：**
```python
from ppdiffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_pretrained("./stable-diffusion-2-1", from_hf_hub=True, from_diffusers=True)
pipe.apply_lora("./sd2_res/Moxin_10.safetensors",from_hf_hub=True, from_diffusers=True)
pipe = pipe.to("gpu")
```

**error：**
```python
Traceback (most recent call last):
  File "/*/aigc/pp_diffusers.py", line 6, in <module>
    pipe.apply_lora("./sd2_res/Moxin_10.safetensors",from_hf_hub=True, from_diffusers=True)
  File "/*/miniconda3/envs/pp/lib/python3.10/site-packages/ppdiffusers/patches/webui_lora_patch_utils.py", line 257, in apply_lora
    kaiming_uniform_(child_module.lora_down.weight, a=math.sqrt(5))
  File "/*/miniconda3/envs/pp/lib/python3.10/site-packages/ppdiffusers/utils/initializer_utils.py", line 234, in kaiming_uniform_
    return _no_grad_uniform_(tensor, -k, k)
  File "/*/miniconda3/envs/pp/lib/python3.10/site-packages/ppdiffusers/utils/initializer_utils.py", line 44, in _no_grad_uniform_
    tensor.uniform_(min=a, max=b)
  File "/*/miniconda3/envs/pp/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/*/miniconda3/envs/pp/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/*/miniconda3/envs/pp/lib/python3.10/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/*/miniconda3/envs/pp/lib/python3.10/site-packages/paddle/tensor/random.py", line 624, in uniform_
    return _C_ops.uniform_random_inplace_(x, 'min', min, 'max', max, 'seed',
ValueError: (InvalidArgument) Leaf Var (linear_362.w_0) that doesn't stop gradient can't use inplace strategy.
  [Hint: Expected X->IsLeaf() && !X->OverridedStopGradient() == false, but received X->IsLeaf() && !X->OverridedStopGradient():1 != false:0.] (at /paddle/paddle/fluid/pybind/op_function_impl.h:7579)
```

**Comment by JunnYu** [comment]
建议更新ppdiffusers后进行尝试，当前ppdiffusers及paddlepaddle是什么版本呢？目前我这里是无法复现出这个问题的
