### ISSUE TITLE
[Bug]: dll load failed 动态链接库dll初始化例程失败

### ISSUE THREAD

**Issue by SmallICeplay** [PaddlePaddle/PaddleNLP#5732]
### 软件环境

```Markdown
paddle                1.0.2
paddle-bfloat         0.1.7
paddle2onnx           1.0.6
paddlefsl             1.1.0
paddlenlp             2.5.2
paddlepaddle          2.4.2
```

### 重复问题

- [x] I have searched the existing issues

### 错误描述

```Markdown
(python37) C:\Users\Administrator\Desktop>python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:35:01) [MSC
v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from paddlenlp import Taskflow
Error: Can not import paddle core while this file exists: D:\Anaconda3\envs\pyth
on37\lib\site-packages\paddle\fluid\libpaddle.pyd
Traceback (most recent call last):
  File "D:\Anaconda3\envs\python37\lib\site-packages\paddle\fluid\core.py", line
 274, in <module>
    from . import libpaddle
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\python37\lib\site-packages\paddlenlp\__init__.py", lin
e 33, in <module>
    import paddle
  File "D:\Anaconda3\envs\python37\lib\site-packages\paddle\__init__.py", line 2
5, in <module>
    from .framework import monkey_patch_variable
  File "D:\Anaconda3\envs\python37\lib\site-packages\paddle\framework\__init__.p
y", line 17, in <module>
    from . import random  # noqa: F401
  File "D:\Anaconda3\envs\python37\lib\site-packages\paddle\framework\random.py"
, line 16, in <module>
    import paddle.fluid as fluid
  File "D:\Anaconda3\envs\python37\lib\site-packages\paddle\fluid\__init__.py",
line 36, in <module>
    from . import framework
  File "D:\Anaconda3\envs\python37\lib\site-packages\paddle\fluid\framework.py",
 line 37, in <module>
    from . import core
  File "D:\Anaconda3\envs\python37\lib\site-packages\paddle\fluid\core.py", line
 333, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined
```

### 稳定复现步骤 & 代码

from paddlenlp import Taskflow

**Comment by gongel** [comment]
重新安装下PaddlePaddle

**Comment by SmallICeplay** [comment]
> 重新安装下PaddlePaddle

谢谢你的回答。 paddlepaddle在本地环境一切正常，但是服务器不行，由于服务器没有外网环境，所以是直接将本地的conda/envs放到服务器，请问会不会是这个操作有问题。 并且服务器cpu型号较老，指令集只有MMX,SSE,SSE2,SSE3,EM64T 是否也与这有关。 非常感谢你的耐心解答

**Comment by gg22mm** [comment]
有些电脑很矫情，像我公司电脑死活都完不上，最后还得用虚拟机解决。。 我在家里的电脑主没事，不行建议重新装好靠谱的完整版系统。。 有些是被阉割了

**Comment by surevision** [comment]
检查一下你的paddlepaddle 2.4.2 是不是 noavx 版本的，看你的描述cpu不支持avx指令集
