### ISSUE TITLE
PaddleNLP SimpleServing 的服务化部署无法本地部署调用问题

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#5752]
### 请提出你的问题

参考：[https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/zero_shot_text_classification/deploy/simple_serving/README.md](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/zero_shot_text_classification/deploy/simple_serving/README.md)

进行部署，在AIstudio可以正常部署。效果如下
![image](https://user-images.githubusercontent.com/34392683/233820845-05785b9f-1f28-4164-ac29-df65152ca533.png)

在本地尝试部署时，首先将paddlenlp升级到了2.5.2版本，但在执行
```
paddlenlp server server:app --workers 1 --host 0.0.0.0 --port 8190
```
没有paddlenlp这个指令，

经过调整使用：
```
python server.py server:app --workers 1 --host 0.0.0.0 --port 8190
```
本地终端结果显示：
```
D:\Anaconda\envs\paddlenlp\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-04-23 12:58:10,790] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'utc-pico'.
[2023-04-23 12:58:10,792] [    INFO] - Already cached C:\Users\admin\.paddlenlp\models\utc-pico\utc_pico_vocab.txt
[2023-04-23 12:58:10,835] [    INFO] - tokenizer config file saved in C:\Users\admin\.paddlenlp\models\utc-pico\tokenizer_config.json
[2023-04-23 12:58:10,844] [    INFO] - Special tokens file saved in C:\Users\admin\.paddlenlp\models\utc-pico\special_tokens_map.json
[2023-04-23 12:58:10,863] [    INFO] - Assigning ['[O-MASK]'] to the additional_special_tokens key of the tokenizer
E0423 12:58:10.940794 24212 analysis_config.cc:855] EnableMKLDNN() only works when IR optimization is enabled.
[2023-04-23 12:58:11,038] [    INFO] -    Taskflow  request [path]=/taskflow/utc is genereated.
```

并未出现在aistudio上启动服务后结果
![image](https://user-images.githubusercontent.com/34392683/233820912-f6968929-b66d-4634-86f0-13032136b991.png)

没能常驻，对部署这块还是有挺多不懂得。

之后调用：python client.py
```
 File "client.py", line 28, in <module>
    r = requests.post(url=url, headers=headers, data=json.dumps(data))
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8190): Max retries exceeded with url: /taskflow/utc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FF786FBBB0>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。'))
```

使用Fastploy本地部署方式可行，就是server失败了，对这块不太了解还望指教，谢谢。

**Comment by LemonNoel** [comment]
没有paddlenlp命令可能是版本没有正确更新，可以用`pip show paddlenlp`看下当前安装版本

**Comment by tingaicompass** [comment]
> 没有paddlenlp命令可能是版本没有正确更新，可以用`pip show paddlenlp`看下当前安装版本

Name: paddlenlp
Version: 2.5.2
Summary: Easy-to-use and powerful NLP library with Awesome model zoo, supporting wide-range of NLP tasks from research to industrial applications, including Neural Search, Question Answering, Information Extraction and Sentiment Analysis end-to-end system.
Home-page: https://github.com/PaddlePaddle/PaddleNLP
Author: PaddleNLP Team
Author-email: paddlenlp@baidu.com
License: Apache 2.0
Location: c:\users\admin\appdata\roaming\python\python38\site-packages
Requires: colorama, colorlog, datasets, dill, fastapi, Flask-Babel, huggingface-hub, jieba, multiprocess, paddle2onnx, paddlefsl, rich, sentencepiece, seqeval, tqdm, typer, uvicorn, visualdl
Required-by: paddlehub

>paddlenlp server server:app --workers 1 --host 0.0.0.0 --port 8190
执行后
'paddlenlp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

Windows环境下的，相关系统路径也添加了。

**Comment by wj-Mcat** [comment]
你其中一个问题在于你安装完 paddlenlp 之后对应的命令无法找到，是由于相关路径没有添加到环境变量中去：

推荐阅读: https://stackoverflow.com/a/65312196

对应着你的环境，应该是需要将：c:\users\admin\appdata\roaming\python\python38\scripts （你自己注意大小写） 添加到path 路径当中去就行了。

**Comment by wj-Mcat** [comment]
请问解决了你的问题了吗？

也非常欢迎在这里分享你的方案，这样其他开发者也可以知道如何解决比问题，非常感谢！

**Comment by dingidng** [comment]
> 你其中一个问题在于你安装完 paddlenlp 之后对应的命令无法找到，是由于相关路径没有添加到环境变量中去：
> 
> 推荐阅读: https://stackoverflow.com/a/65312196
> 
> 对应着你的环境，应该是需要将：c:\users\admin\appdata\roaming\python\python38\scripts （你自己注意大小写） 添加到path 路径当中去就行了。

您好非常感谢，之前我添加路径只添加了anaconda下的python路径；这次添加后可以使用paddlenlp指令并且服务也调度起来了。
```
[2023-04-24 14:08:07,756] [    INFO] - Assigning ['[O-MASK]'] to the additional_special_tokens key of the tokenizer
E0424 14:08:07.897694 16868 analysis_config.cc:855] EnableMKLDNN() only works when IR optimization is enabled.
[2023-04-24 14:08:08,157] [    INFO] -    Taskflow  request [path]=/taskflow/utc is genereated.
INFO:     Started server process [15756]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8190 (Press CTRL+C to quit)
```
但是在Client请求启动时仍报错，链接请求无效
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 28, in <module>
    r = requests.post(url=url, headers=headers, data=json.dumps(data))
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8190): Max retries exceeded with url: /taskflow/utc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DCF888CBB0>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效。'))
```

**Comment by tingaicompass** [comment]
> 您好非常感谢，之前我添加路径只添加了anaconda下的python路径；这次添加后可以使用paddlenlp指令并且服务也调度起来了。

您好非常感谢，之前我添加路径只添加了anaconda下的python路径；这次添加c:\users\admin\appdata\roaming\python\python38\scripts 后可以使用paddlenlp指令并且服务也调度起来了。

同时第二个问题在于本地host不同，C:\Windows\System32\drivers\etc\hosts 修改一下即可

![image](https://user-images.githubusercontent.com/34392683/233928841-a222ba3b-ec29-46fa-a601-eddb7fd72630.png)
