### ISSUE TITLE
[Bug]: 无法适配python3.10

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleNLP#5764]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/__init__.py", line 35, in <module>
    from . import (
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/ops/__init__.py", line 22, in <module>
    from .fast_transformer.transformer.decoding import *
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/ops/fast_transformer/transformer/decoding.py", line 25, in <module>
    from paddlenlp.ops.ext_utils import LOADED_EXT, load
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/ops/ext_utils.py", line 21, in <module>
    from distutils.dep_util import newer_group
ModuleNotFoundError: No module named 'distutils.dep_util'
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/__init__.py", line 35, in <module>
    from . import (
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/ops/__init__.py", line 22, in <module>
    from .fast_transformer.transformer.decoding import *
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/ops/fast_transformer/transformer/decoding.py", line 25, in <module>
    from paddlenlp.ops.ext_utils import LOADED_EXT, load
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/ops/ext_utils.py", line 21, in <module>
    from distutils.dep_util import newer_group
ModuleNotFoundError: No module named 'distutils.dep_util'
```

### 稳定复现步骤 & 代码

from paddlenlp import Taskflow

**Comment by linjieccc** [comment]
请问paddlenlp和paddle的版本号是多少
