### ISSUE TITLE
[Question]: 使用示例代码code_generation时报错MemoryError: (ResourceExhausted) Fail to alloc memory of 520505472 size, error code is 12.

### ISSUE THREAD

**Issue by s290305915** [PaddlePaddle/PaddleNLP#5788]
### 请提出你的问题

使用的示例代码
from paddlenlp import Taskflow
prompt = "def lengthOfLongestSubstring(self, s: str) -> int:"
codegen = Taskflow("code_generation", model="Salesforce/codegen-2B-mono",decode_strategy="greedy_search", repetition_penalty=1.0)
print(codegen(prompt))

机器内存16G，非GPU

在加载模型的时候报错

[2023-04-26 12:00:56,418] [    INFO] - Found /root/.paddlenlp/models/Salesforce/codegen-2B-mono/model_state.pdparams
Traceback (most recent call last):
  File "/data/download/cdg2.py", line 3, in <module>
    codegen = Taskflow("code_generation", model="Salesforce/codegen-2B-mono",decode_strategy="greedy_search", repetition_penalty=1.0)
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/taskflow/taskflow.py", line 837, in __init__
    self.task_instance = task_class(
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/taskflow/code_generation.py", line 59, in __init__
    self._construct_model(model)
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/taskflow/code_generation.py", line 65, in _construct_model
    self._model = CodeGenForCausalLM.from_pretrained(model)
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/model_utils.py", line 484, in from_pretrained
    return cls.from_pretrained_v2(
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/model_utils.py", line 1362, in from_pretrained_v2
    model = cls(config, *init_args, **model_kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/codegen/modeling.py", line 539, in __init__
    self.transformer = CodeGenModel(config)
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/codegen/modeling.py", line 334, in __init__
    self.h = nn.LayerList([CodeGenBlock(config) for _ in range(config.n_layer)])
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/codegen/modeling.py", line 334, in <listcomp>
    self.h = nn.LayerList([CodeGenBlock(config) for _ in range(config.n_layer)])
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/codegen/modeling.py", line 245, in __init__
    self.mlp = CodeGenMLP(config)
  File "/root/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/codegen/modeling.py", line 227, in __init__
    self.fc_out = nn.Linear(inner_dim, config.n_embd)
  File "/root/anaconda3/lib/python3.10/site-packages/paddle/nn/layer/common.py", line 160, in __init__
    self.weight = self.create_parameter(
  File "/root/anaconda3/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 471, in create_parameter
    return self._helper.create_parameter(
  File "/root/anaconda3/lib/python3.10/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/root/anaconda3/lib/python3.10/site-packages/paddle/fluid/framework.py", line 3988, in create_parameter
    initializer(param, self)
  File "/root/anaconda3/lib/python3.10/site-packages/paddle/fluid/initializer.py", line 56, in __call__
    return self.forward(param, block)
  File "/root/anaconda3/lib/python3.10/site-packages/paddle/fluid/initializer.py", line 614, in forward
    out_var = _C_ops.uniform_random(out_var.shape, out_dtype,
MemoryError: (ResourceExhausted) Fail to alloc memory of 520505472 size, error code is 12.
  [Hint: Expected error == 0, but received error:12 != 0:0.] (at /paddle/paddle/fluid/memory/allocation/system_allocator.cc:71)

**Comment by wawltor** [comment]
显存不够导致的OOM

**Comment by s290305915** [comment]
已解决

**Comment by EvilCalf** [comment]
> 已解决

请问是怎么解决的，cpu上推理，我也报了这个错

**Comment by caochao18** [comment]
> 已解决

怎么解决的啊， 我和你同样的问题， 望回复

**Comment by ptucptujkv20609** [comment]
> 

加大内存

**Comment by caochao18** [comment]
版本不对
