### ISSUE TITLE
[Bug]: 同一个脚本先加载uie-x,再加载uie，报错KeyError: 'sentencepiece_model_file'

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/PaddleNLP#5795]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.3.1-gpu-cuda11.2-cudnn8
- paddlenlp: 2.3.1.post112
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
同一个脚本先加载uie-x,再加载uie，报错KeyError: 'sentencepiece_model_file'
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    uie = Taskflow("information_extraction", schema=schema, task_path=uie_path)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/taskflow.py", line 838, in __init__
    model=self.model, task=self.task, priority_path=self.priority_path, from_hf_hub=from_hf_hub, **self.kwargs
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/information_extraction.py", line 507, in __init__
    self._check_task_files()
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/task.py", line 135, in _check_task_files
    url = self.resource_files_urls[self.model][file_id][0]
KeyError: 'sentencepiece_model_file'

反之先加载uie，再加在uie-x则不出错
```

### 稳定复现步骤 & 代码

uie_path = "/paddlenlp_latest/uie"
from paddlenlp import Taskflow
schema = ['时间']
uie_x_path = "/paddlenlp_latest/checkpoint/model_best"
uie_x = Taskflow("information_extraction", model="uie-x-base", schema=schema, task_path=uie_x_path, precision='fp32')
uie = Taskflow("information_extraction", schema=schema, task_path=uie_path)

**Comment by linjieccc** [comment]
@zhiyongLiu1114 你好，这个问题目前修复了，可以尝试安装下最新的develop版本

```shell
pip install --pre --upgrade paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```
