### ISSUE TITLE
[Bug]: 使用PaddleNLP进行文本预测，推理时报错json.decoder.JSONDecodeError: Extra data

### ISSUE THREAD

**Issue by lucky0604** [PaddlePaddle/PaddleNLP#5800]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.2
- paddlenlp: 2.5.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
根据[示例](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/few-shot#readme)的步骤完整进行，在最后`gpu端推理`时报错
Traceback (most recent call last):
  File "/root/workspace/nlp/PaddleNLP/applications/text_classification/multi_class/few-shot/infer.py", line 216, in <module>
    predictor = MultiClassPredictor(args)
  File "/root/workspace/nlp/PaddleNLP/applications/text_classification/multi_class/few-shot/infer.py", line 118, in __init__
    self.template, self.labels, self.input_handles = self.post_init()
  File "/root/workspace/nlp/PaddleNLP/applications/text_classification/multi_class/few-shot/infer.py", line 136, in post_init
    prompt = json.load(fp)
  File "/root/miniconda3/envs/paddle/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/root/miniconda3/envs/paddle/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/miniconda3/envs/paddle/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 72)
```

### 训练：
```shell
python train.py \
--device gpu \
--data_dir ./data \
--output_dir ./checkpoints/ \
--prompt "这条新闻标题的主题是" \
--max_seq_length 128  \
--learning_rate 3e-6 \
--ppt_learning_rate 3e-5 \
--do_train \
--do_eval \
--use_rdrop \
--max_steps 1000 \
--eval_steps 10 \
--logging_steps 5 \
--save_total_limit 1 \
--load_best_model_at_end True \
--per_device_eval_batch_size 32 \
--per_device_train_batch_size 8 \
--do_predict \
--do_export
```

### 评估
```shell
python train.py --do_predict --data_dir ./data --output_dir ./predict_checkpoint --resume_from_checkpoint ./checkpoints/ --max_seq_length 128
```

### GPU端推理
```shell
python infer.py --model_path_prefix checkpoints/export/model --data_dir ./data --batch_size 32 --device gpu --device_id 0
```

**Comment by LemonNoel** [comment]
可以将`checkpoints/export/template_config.json`文件中第二行删除。

**Comment by lucky0604** [comment]
已解决，感谢。
