### ISSUE TITLE
[Question]: 下载链接失效

### ISSUE THREAD

**Issue by InvertedForest** [PaddlePaddle/PaddleNLP#5830]
### 请提出你的问题

**报错：**
[ WARNING] - file<https://bj.bcebos.com/paddlenlp/models/community/bert/vocab.txt> not exist
**自检**
网络无问题，paddlenlp版本为develop的最新版（2023年5月5日13点31分）
**debug**
链接来自于[此行](https://github.com/PaddlePaddle/PaddleNLP/blob/9a8769e7f3794e10d04bbd473cce74eebaf95be9/ppdiffusers/ppdiffusers/utils/download_utils.py#L110)

**Comment by InvertedForest** [comment]
更详细的tracback
```
Traceback (most recent call last):                                                                                                                 
  File "./run_glue_ofa.py", line 488, in <module>                                                                                                  
    do_train(args)                                                                                                                                 
  File "./run_glue_ofa.py", line 288, in do_train                                                                                                  
    tokenizer = tokenizer_class.from_pretrained(args.model_name_or_path)                                                                           
  File "/home/wt/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp-2.5.2.post0-py3.7.egg/paddlenlp/transformers/tokenizer_utils_base.py"
, line 1587, in from_pretrained                                                                                                                    
    tokenizer = cls(*init_args, **init_kwargs)                                                                                                     
  File "/home/wt/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp-2.5.2.post0-py3.7.egg/paddlenlp/transformers/utils.py", line 172, in 
__impl__                                                                                                                                           
    init_func(self, *args, **kwargs)                                                                                                               
  File "/home/wt/miniconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp-2.5.2.post0-py3.7.egg/paddlenlp/transformers/bert/tokenizer.py", line
 423, in __init__                                                                                                                                  
    if not os.path.isfile(vocab_file):                                                                                                             
  File "/home/wt/miniconda3/envs/paddle/lib/python3.7/genericpath.py", line 30, in isfile                                                          
    st = os.stat(path)                                                                                                                             
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by InvertedForest** [comment]
个人启动命令失误，bert的model name有多个名称 ：）
![image](https://user-images.githubusercontent.com/44810687/236391348-b3df48a4-04b4-4df0-98ab-1d7ec5b90a46.png)
