### ISSUE TITLE
[Bug]: 调试UIE infer.py 运行到from paddlenlp.transformers import AutoTokenizer 出现段错误 

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#5852]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu:              2.4.2.post116

- paddlenlp: 2.5.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
调试UIE infer.py 运

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

### 稳定复现步骤 & 代码

运行infer.py出现断错 然后

单步调试UIE infer.py  发现运行到from paddlenlp.transformers import AutoTokenizer 出现段错误 

Traceback (most recent call last):
  File "paddleprj/PaddleNLP/model_zoo/uie/deploy/python/infer.py", line 25, in <module>
    from paddlenlp.transformers import AutoTokenizer
  File ".local/lib/python3.10/site-packages/paddlenlp/__init__.py", line 33, in <module>
    import paddle
  File ".local/lib/python3.10/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File ".local/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File ".local/lib/python3.10/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File ".local/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 52, in <module>
    from . import io
  File ".local/lib/python3.10/site-packages/paddle/fluid/io.py", line 31, in <module>
    from paddle.fluid import layers
  File ".local/lib/python3.10/site-packages/paddle/fluid/layers/__init__.py", line 29, in <module>
    from . import math_op_patch
  File ".local/lib/python3.10/site-packages/paddle/fluid/layers/math_op_patch.py", line 24, in <module>
    from paddle.fluid.dygraph.base import in_declarative_mode
  File ".local/lib/python3.10/site-packages/paddle/fluid/dygraph/__init__.py", line 35, in <module>
    from . import checkpoint
  File ".local/lib/python3.10/site-packages/paddle/fluid/dygraph/checkpoint.py", line 26, in <module>
    from paddle.fluid.dygraph.jit import _SaveLoadConfig
  File ".local/lib/python3.10/site-packages/paddle/fluid/dygraph/jit.py", line 34, in <module>
    from paddle.fluid.dygraph.dygraph_to_static import logging_utils
  File ".local/lib/python3.10/site-packages/paddle/fluid/dygraph/dygraph_to_static/__init__.py", line 29, in <module>
    from . import program_translator
  File ".local/lib/python3.10/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 38, in <module>
    from paddle.fluid.dygraph.dygraph_to_static.partial_program import partial_program_from
  File ".local/lib/python3.10/site-packages/paddle/fluid/dygraph/dygraph_to_static/partial_program.py", line 36, in <module>
    from paddle.fluid.contrib.mixed_precision.decorator import (
  File ".local/lib/python3.10/site-packages/paddle/fluid/contrib/__init__.py", line 31, in <module>
    from . import mixed_precision
  File ".local/lib/python3.10/site-packages/paddle/fluid/contrib/mixed_precision/__init__.py", line 17, in <module>
    from . import decorator
  File ".local/lib/python3.10/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 22, in <module>
    from . import fp16_utils
  File ".local/lib/python3.10/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 23, in <module>
    from .fp16_lists import AutoMixedPrecisionLists
  File ".local/lib/python3.10/site-packages/paddle/fluid/contrib/mixed_precision/fp16_lists.py", line 186, in <module>
    _, _, _sys_unsupported_fp16_list = core.op_supported_infos(
RuntimeError: Invalid enum data type `255`.
  [/paddle/paddle/phi/common/data_type.h:210]

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by linjieccc** [comment]
@cqray1990 你好，请尝试下执行`paddle.utils.run_check()`，另外可以试下安装nightly build版本 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
