### ISSUE TITLE
[Bug]: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by SolarKnight1** [PaddlePaddle/PaddleNLP#5906]
### 软件环境

```Markdown
- paddlepaddle:2.4.2
- paddlepaddle-gpu: 2.4.2
- paddlenlp: 2.5.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
nlp新手。。。
Traceback (most recent call last):
  File "/tmp/pycharm_project_599/document/finetune.py", line 176, in <module>
    main()
  File "/tmp/pycharm_project_599/document/finetune.py", line 114, in main
    train_ds = load_dataset(reader, data_path=data_args.train_path, max_seq_len=data_args.max_seq_len, lazy=False)
  File "/root/anaconda3/envs/qihangf/lib/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 186, in load_dataset
    return reader_instance.read(**custom_kwargs)
  File "/root/anaconda3/envs/qihangf/lib/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 768, in read
    return MapDataset(list(examples))
  File "/tmp/pycharm_project_599/document/utils.py", line 31, in reader
    json_line = json.loads(line)
  File "/root/anaconda3/envs/qihangf/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/qihangf/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/envs/qihangf/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

### 稳定复现步骤 & 代码

python finetune.py      --device gpu     --logging_steps 5     --save_steps 25     --eval_steps 25     --seed 42     --model_name_or_path uie-x-base     --output_dir ./checkpoint/model_best     --train_path data/train.txt     --dev_path data/dev.txt      --max_seq_len 512      --per_device_train_batch_size  8     --per_device_eval_batch_size 8     --num_train_epochs 10     --learning_rate 1e-5     --do_train     --do_eval     --do_export     --export_model_dir ./checkpoint/model_best     --overwrite_output_dir     --disable_tqdm True     --metric_for_best_model eval_f1     --load_best_model_at_end  True     --save_total_limit 1

**Comment by super-tian** [comment]
数据集构建的方式有问题，检查分隔符是不是错了，或者初始的清洗原始数据的代码是不是有问题
