### ISSUE TITLE
[Question]: ppdiffusion根据text_to_image训练1000多步后报错

### ISSUE THREAD

**Issue by WX45459** [PaddlePaddle/PaddleNLP#5912]
### 请提出你的问题

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/PIL/ImageFile.py", line 249, in load
    s = read(self.decodermaxblock)
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 941, in load_read
    cid, pos, length = self.png.read()
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 178, in read
    length = i32(s)
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/PIL/_binary.py", line 85, in i32be
    return unpack_from(">I", c, o)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2709, in __getitem__
    return self._getitem(key)
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2694, in _getitem
    formatted_output = format_table(
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 634, in format_table
    return formatter(pa_table, query_type=query_type)
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 406, in __call__
    return self.format_row(pa_table)
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 490, in format_row
    formatted_batch = self.format_batch(pa_table)
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 519, in format_batch
    batch = self.python_features_decoder.decode_batch(batch)
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 231, in decode_batch
    return self.features.decode_batch(batch) if self.features else batch
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/features/features.py", line 1907, in decode_batch
    [
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/features/features.py", line 1908, in <listcomp>
    decode_nested_example(self[column_name], value, token_per_repo_id=token_per_repo_id)
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/features/features.py", line 1308, in decode_nested_example
    return schema.decode_example(obj, token_per_repo_id=token_per_repo_id)
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/datasets/features/image.py", line 178, in decode_example
    image.load()  # to avoid "Too many open files" errors
  File "/home/b212/miniconda3/envs/paddle/lib/python3.9/site-packages/PIL/ImageFile.py", line 256, in load
    raise OSError(msg) from e
OSError: image file is truncated

**Comment by JunnYu** [comment]
你好，你使用的是《宝可梦》的数据集吗？如果是的话，可以试一下重新下载运行看看，这个数据集主要是使用Huggingface的datasets库来处理的，可以去datasets库搜一下这个问题

**Comment by WX45459** [comment]
使用的是个人数据集，train文件夹下存放metadata.jsonl和53475张Png图片。
数据集的处理会在开始训练后报错吗？运行了几次，在不同的训练步数（300，500等）会报相同的错误。

**Comment by JunnYu** [comment]
建议可以检查一下你的53475张Png图片，看看哪个图片是存在破损？

**Comment by WX45459** [comment]
确实是有一张图片损坏了，感谢帮助！
