### ISSUE TITLE
[Question]: 求回复！跑duee句子级事件抽取，报错ValueError

### ISSUE THREAD

**Issue by awhathell** [PaddlePaddle/PaddleNLP#5913]
### 跑duee句子级事件抽取，使用原始数据集，报错如下：
Traceback (most recent call last):
  File "sequence_labeling.py", line 343, in <module>
    do_train()
  File "sequence_labeling.py", line 240, in do_train
    loss = paddle.mean(criterion(logits, labels.reshape([-1])))
  File "/home/wmy/anaconda3/envs/duee/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/wmy/anaconda3/envs/duee/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/wmy/anaconda3/envs/duee/lib/python3.8/site-packages/paddle/nn/layer/loss.py", line 397, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "/home/wmy/anaconda3/envs/duee/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 1735, in cross_entropy
    _, out = _C_ops.softmax_with_cross_entropy(
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:3184 != labels_dims[i]:3232.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:164)
  [operator < softmax_with_cross_entropy > error]
打印了logits和label的shape发现确实不一样。奇怪的是，我删掉这条数据后，接下来还会有同样的其他的句子出错，而且可能之前没出错的也会出错。
环境为：paddlepaddle-gpu==2.4.1；paddlenlp==2.5.2；
查询了历史问题，发现有两个类似的问题，但是都未给出解决方案。

**Comment by awhathell** [comment]
我需要你的帮助

**Comment by zlyir** [comment]
hi 我也遇到了同样的问题，请问你这边解决了吗
