### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by wanglaiqi** [PaddlePaddle/PaddleNLP#5983]
### 请提出你的问题

基于pegasus模型的动态图转静态图不成功。 报以下错误
[ 55%] Linking CUDA static library ../../lib/libonline_softmax_beamsearch.a
[ 55%] Built target online_softmax_beamsearch
Scanning dependencies of target encoder_gemm_func
[ 57%] Building CXX object fastertransformer/gemm_test/CMakeFiles/encoder_gemm_func.dir/encoder_gemm_func.cc.o
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc: In function ‘int fastertransformer::printPerfStructure(int, int, int, int, int, int, int, const fastertransformer::customMatmulPerf_t&, FILE*, int, int)’:
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:36:56: error: ‘CUBLASLT_ALGO_CONFIG_STAGES_ID’ was not declared in this scope; did you mean ‘CUBLASLT_ALGO_CONFIG_TILE_ID’?
   36 |     cublasLtMatmulAlgoConfigGetAttribute( matmulAlgo,  CUBLASLT_ALGO_CONFIG_STAGES_ID, &stages, sizeof(stages), NULL);
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                        CUBLASLT_ALGO_CONFIG_TILE_ID
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc: In function ‘int fastertransformer::LtHgemmCustomFind(cublasLtHandle_t, int, int, int, int, int, int, int, const T*, const T*, const T*, const T*, T*, void*, size_t, FILE*, fastertransformer::customMatmulPerf_t*, int)’:
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:192:5: error: ‘cublasComputeType_t’ was not declared in this scope; did you mean ‘cublasDataType_t’?
  192 |     cublasComputeType_t computeType;
      |     ^~~~~~~~~~~~~~~~~~~
      |     cublasDataType_t
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:200:7: error: ‘computeType’ was not declared in this scope
  200 |       computeType = CUBLAS_COMPUTE_32F;
      |       ^~~~~~~~~~~
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:200:21: error: ‘CUBLAS_COMPUTE_32F’ was not declared in this scope
  200 |       computeType = CUBLAS_COMPUTE_32F;
      |                     ^~~~~~~~~~~~~~~~~~
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:207:7: error: ‘computeType’ was not declared in this scope
  207 |       computeType = CUBLAS_COMPUTE_16F;
      |       ^~~~~~~~~~~
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:207:21: error: ‘CUBLAS_COMPUTE_16F’ was not declared in this scope
  207 |       computeType = CUBLAS_COMPUTE_16F;
      |                     ^~~~~~~~~~~~~~~~~~
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:216:55: error: ‘computeType’ was not declared in this scope
  216 |     status = cublasLtMatmulDescCreate(&operationDesc, computeType, scaleType); //  creates a matrix multiply descriptor
      |                                                       ^~~~~~~~~~~
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:263:50: error: ‘CUBLASLT_ALGO_CAP_STAGES_IDS’ was not declared in this scope; did you mean ‘CUBLASLT_ALGO_CAP_TILE_IDS’?
  263 |         cublasLtMatmulAlgoCapGetAttribute(&algo, CUBLASLT_ALGO_CAP_STAGES_IDS, NULL, 0, &sizeWritten);
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  CUBLASLT_ALGO_CAP_TILE_IDS
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:267:26: error: ‘CUBLASLT_MATMUL_STAGES_UNDEFINED’ was not declared in this scope; did you mean ‘CUBLASLT_MATMUL_TILE_UNDEFINED’?
  267 |             stagesA[0] = CUBLASLT_MATMUL_STAGES_UNDEFINED;
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          CUBLASLT_MATMUL_TILE_UNDEFINED
/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration/build/temp.linux-x86_64-cpython-37/third-party/source/fastertransformer/fastertransformer/gemm_test/encoder_gemm_func.cc:286:57: error: ‘CUBLASLT_ALGO_CONFIG_STAGES_ID’ was not declared in this scope; did you mean ‘CUBLASLT_ALGO_CONFIG_TILE_ID’?
  286 |             cublasLtMatmulAlgoConfigSetAttribute(&algo, CUBLASLT_ALGO_CONFIG_STAGES_ID, &stagesA[stagesIdx], sizeof(stagesA[stagesIdx]));
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                         CUBLASLT_ALGO_CONFIG_TILE_ID
make[5]: *** [fastertransformer/gemm_test/CMakeFiles/encoder_gemm_func.dir/build.make:63: fastertransformer/gemm_test/CMakeFiles/encoder_gemm_func.dir/encoder_gemm_func.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:552: fastertransformer/gemm_test/CMakeFiles/encoder_gemm_func.dir/all] Error 2
make[3]: *** [Makefile:84: all] Error 2
make[2]: *** [CMakeFiles/extern_fastertransformer.dir/build.make:112: third-party/src/extern_fastertransformer-stamp/extern_fastertransformer-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/extern_fastertransformer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
[33m[2023-05-10 04:05:45,585] [ WARNING][0m - FastGeneration is not available due to build errors.[0m
Traceback (most recent call last):
  File "FastGeneration_setup.py", line 11, in <module>
    output_dir=r'/home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration')
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 198, in build_extensions
    ext.build_with_command(self)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 176, in build_with_command
    raise e
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 165, in build_with_command
    super(FasterTransformerExtension, self).build_with_command(ext_builder)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 116, in build_with_command
    ["cmake", "--build", "."] + build_args, cwd=ext_builder.build_temp, stdout=stdout, stderr=stdout
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
Namespace(decoding_strategy='beam_search', diversity_rate=0.0, export_output_dir='./model_inference/pegasus_base', length_penalty=0.0, max_out_len=30, min_out_len=1, model_name_or_path='IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese', num_beams=4, num_return_sequence=1, num_return_sequences=1, temperature=1.0, topk=4, topp=1.0, use_fp16_decoding=True)
Compiling user custom op, it will cost a few seconds.....
Traceback (most recent call last):
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1148, in run_cmd
    command, shell=True, stderr=subprocess.STDOUT)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration && /home/wanglaiqi/miniconda3/envs/pytorch_env/bin/python FastGeneration_setup.py build' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_model.py", line 131, in <module>
    do_predict(args)
  File "export_model.py", line 75, in do_predict
    pegasus = FasterPegasus(model=model, use_fp16_decoding=args.use_fp16_decoding, trans_out=True)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/fast_transformer/transformer/fast_transformer.py", line 1818, in __init__
    hidden_act=model.pegasus.config["activation_function"],
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/fast_transformer/transformer/decoding.py", line 4316, in __init__
    load("FastGeneration", verbose=True)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 53, in _impl
    func(*args, **kwargs)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddlenlp/ops/ext_utils.py", line 307, in load
    _jit_compile(file_path, verbose)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1112, in _jit_compile
    run_cmd(compile_cmd, verbose)
  File "/home/wanglaiqi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1154, in run_cmd
    compile, error))
RuntimeError: Failed to run command: <built-in function compile>, errors: Command 'cd /home/wanglaiqi/.paddlenlp/extensions/249691cd5786face2a90a37d9fbf9fca/FastGeneration && /home/wanglaiqi/miniconda3/envs/pytorch_env/bin/python FastGeneration_setup.py build' returned non-zero exit status 1.

**Comment by gongel** [comment]
CUDA版本多少呀？

**Comment by wanglaiqi** [comment]
***@***.***
 
From: gongenlei
Date: 2023-05-23 10:44
To: PaddlePaddle/PaddleNLP
CC: wanglaiqi; Author
Subject: Re: [PaddlePaddle/PaddleNLP] [Question]: (Issue #5983)
CUDA版本多少呀？

**Comment by wanglaiqi** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/9366714/32272ced-2474-473c-92d9-353fb8eca05e)
