### ISSUE TITLE
[Question]: paddleocr训练自己的数据集时报错

### ISSUE THREAD

**Issue by 18374100906aaa** [PaddlePaddle/PaddleNLP#6002]
### 请提出你的问题

Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 52, in main
    train_dataloader = build_dataloader(config, 'Train', device, logger)
  File "D:\cv\project\PaddleOCR-release-2.6\ppocr\data\__init__.py", line 83, in build_dataloader
    drop_last=drop_last)
  File "D:\anaconda\Lib\site-packages\paddle\fluid\dataloader\batch_sampler.py", line 233, in __init__
    "shuffle should be a boolean value"
AssertionError: shuffle should be a boolean value

**Comment by 18374100906aaa** [comment]
paddleocr训练自己的数据集时报错

**Comment by sijunhe** [comment]
您好，PaddleOCR的问题请移步 https://github.com/PaddlePaddle/PaddleOCR 的issue区，谢谢
