### ISSUE TITLE
[Question]: paddleocr训练时发出调用Python对象时超过的最大递归深度的报错

### ISSUE THREAD

**Issue by 18374100906aaa** [PaddlePaddle/PaddleNLP#6006]
### 请提出你的问题
```python
Traceback (most recent call last):
  File "D:\anaconda\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\anaconda\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\anaconda\Lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "D:\anaconda\Lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "D:\cv\project\PaddleOCR-release-2.6\ppocr\data\simple_dataset.py", line 147, in __getitem__
    return self.__getitem__(rnd_idx)
  File "D:\cv\project\PaddleOCR-release-2.6\ppocr\data\simple_dataset.py", line 147, in __getitem__
    return self.__getitem__(rnd_idx)
  File "D:\cv\project\PaddleOCR-release-2.6\ppocr\data\simple_dataset.py", line 147, in __getitem__
    return self.__getitem__(rnd_idx)
  [Previous line repeated 976 more times]
  File "D:\cv\project\PaddleOCR-release-2.6\ppocr\data\simple_dataset.py", line 141, in __getitem__
    data_line, traceback.format_exc()))
  File "D:\anaconda\lib\logging\__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "D:\anaconda\lib\logging\__init__.py", line 1514, in _log
    self.handle(record)
  File "D:\anaconda\lib\logging\__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "D:\anaconda\lib\logging\__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "D:\anaconda\lib\logging\__init__.py", line 894, in handle
    self.emit(record)
  File "D:\anaconda\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "D:\anaconda\Lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "D:\anaconda\Lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "D:\anaconda\Lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "D:\anaconda\Lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by austin0072009** [comment]
同样遇到这个错误

**Comment by 18374100906aaa** [comment]
难搞哦

**Comment by heyudage** [comment]
前面遇到类似的问题，已解决，不知道和你的是否一样。
https://blog.csdn.net/HEYUDAGE/article/details/126219497
