### ISSUE TITLE
Issues of AMP+FP16 training for BERT-base on GLUE [Static Graph]

### ISSUE THREAD

**Issue by mingxu1067** [PaddlePaddle/PaddleNLP#604]
I am attempting to apply AMP+fp16 training to BERT GLUE finetuning, but encounter some dtype issues.
- Base script: [run_glue.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/bert/static/run_glue.py)
- How I implemented
1. Added `paddle.static.amp.fp16_guard()` to BertForSequenceClassification
```python
class BertForSequenceClassification(BertPretrainedModel):
def __init__(self, bert, num_classes=2, dropout=None):
    super(BertForSequenceClassification, self).__init__()
    self.num_classes = num_classes
    self.bert = bert  # allow bert to be config
    self.dropout = nn.Dropout(dropout if dropout is not None else
                              self.bert.config["hidden_dropout_prob"])
    self.classifier = nn.Linear(self.bert.config["hidden_size"],
                                num_classes)
    self.apply(self.init_weights)

def forward(self,
            input_ids,
            token_type_ids=None,
            position_ids=None,
            attention_mask=None):
    with paddle.static.amp.fp16_guard():
        _, pooled_output = self.bert(
            input_ids,
            token_type_ids=token_type_ids,
            position_ids=position_ids,
            attention_mask=attention_mask)

        pooled_output = self.dropout(pooled_output)
        logits = self.classifier(pooled_output)
        return logits
```
2. Added optimizer's decorator by `paddle.static.amp.AutoMixedPrecisionLists`
```python
# amp_list is refer to run_pretrain.py
amp_list = paddle.static.amp.AutoMixedPrecisionLists(
                    custom_white_list=['softmax', 'layer_norm', 'gelu'],
                    custom_black_list=['lookup_table', 'lookup_table_v2'])
optimizer = paddle.static.amp.decorate(
    optimizer,
    amp_list,
    init_loss_scaling=args.scale_loss,
    use_dynamic_loss_scaling=True,
    use_pure_fp16=args.use_pure_fp16)
```
3. Called `optimizer.amp_init` to cast model before training
```python
optimizer.amp_init(place)
```

- What are the issues?
1. `paddle.argsort` in Mcc metric of GLUE does not support `float16`.
```python
TypeError: The data type of 'x' in argsort must be ['float32', 'float64', 'int16', 'int32', 'int64', 'uint8'], but received float16.
```
If added a cast layer in front of metric computing, then encounter type error.
```python
with paddle.static.program_guard(dev_program, startup_program):
        metric = metric_class()
        logits_fp32 = paddle.fluid.layers.cast(x=logits, dtype="float32")
        correct = metric.compute(logits_fp32, labels)
```
```
Traceback (most recent call last):
  File "./run_glue.py", line 569, in <module>
    do_train(args)
  File "./run_glue.py", line 537, in do_train
    all_accuracy.append(evaluate(exe, metric, loss, correct, dev_program,
  File "./run_glue.py", line 239, in evaluate
    exe.run(dev_program, feed=batch, \
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.8/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1098, in run
    return self._run_impl(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1231, in _run_impl
    return self._run_program(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1328, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
ValueError:

  Compile Traceback (most recent call last):
    File "./run_glue.py", line 569, in <module>
      do_train(args)
    File "./run_glue.py", line 433, in do_train
      logits = model(input_ids, segment_ids)
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/sparsity/PaddleNLP/paddlenlp/transformers/bert/modeling.py", line 401, in forward
      _, pooled_output = self.bert(
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/sparsity/PaddleNLP/paddlenlp/transformers/bert/modeling.py", line 346, in forward
      encoder_outputs = self.encoder(embedding_output, attention_mask)
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/transformer.py", line 683, in forward
      output = mod(output, src_mask=src_mask)
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/transformer.py", line 567, in forward
      src = self.self_attn(src, src, src, src_mask)
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/transformer.py", line 394, in forward
      q, k, v = self._prepare_qkv(query, key, value, cache)
    File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/transformer.py", line 220, in _prepare_qkv
      q = self.q_proj(query)
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/common.py", line 128, in forward
      out = F.linear(
    File "/usr/local/lib/python3.8/dist-packages/paddle/nn/functional/common.py", line 1469, in linear
      helper.append_op(
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 2883, in append_op
      op = Operator(
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 1961, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string > > const&, bool, bool)
1   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
2   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
3   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
7   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const
8   float const* paddle::framework::Tensor::data<float>() const
9   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
10  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Tensor holds the wrong type, it holds ::paddle::platform::float16, but desires to be float.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at /paddle/sparsity/paddle/paddle/fluid/framework/tensor_impl.h:33)
  [operator < matmul > error]
```

**Comment by ZeyuChen** [comment]
@guoshengCS Please look into this issues.

**Comment by guoshengCS** [comment]
Can you try to use `amp.init(test_program=dev_program)` when calling `amp.init`, it seems the program for validation should be provided here. Refer to https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/mixed_precision/decorator.py#L206 . Or whether the same errors occurs when removing the validation `dev_program`.
