### ISSUE TITLE
词性标注多卡训练报错

### ISSUE THREAD

**Issue by wdhxek** [PaddlePaddle/PaddleNLP#61]
paddle gpu 2.0.0
paddlenlp 2.0.0rc5
cuda 10.1
cudnn: 7.6.5
nccl 2.7.3

按照[文档教程](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/lexical_analysis)进行多卡训练报错
$ python train.py         --data_dir ./lexical_analysis_dataset_tiny         --model_save_dir ./save_dir         --epochs 10         --batch_size 32         --n_gpu 2     
-----------------------------------------------

W0303 17:54:08.340672 24268 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.1
W0303 17:54:08.344925 24268 device_context.cc:372] device: 0, cuDNN Version: 7.6.
W0303 17:54:08.365159 24269 device_context.cc:362] Please NOTE: device: 1, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.1
W0303 17:54:08.369661 24269 device_context.cc:372] device: 1, cuDNN Version: 7.6.
I0303 17:54:11.289988 24268 nccl_context.cc:189] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
I0303 17:54:11.290007 24269 nccl_context.cc:189] init nccl context nranks: 2 local rank: 1 gpu id: 1 ring id: 0
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/10
/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is depr
ecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is depr
ecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
Traceback (most recent call last):
  File "train.py", line 116, in <module>
    paddle.distributed.spawn(train, args=(args, ), nprocs=args.n_gpu)
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 449, in spawn
    while not context.join():
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 255, in join
    self._throw_exception(error_index)
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 273, in _throw_exception
    raise Exception(msg)
Exception: 

----------------------------------------------
Process 0 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 204, in _func_wrapper
    result = func(*args)
  File "/public/data_sharing/gsliu/codes/PaddleNLP/examples/lexical_analysis/train.py", line 110, in train
    callbacks=callbacks)
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/hapi/model.py", line 1495, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/hapi/model.py", line 1802, in _run_one_epoch
    data[len(self._inputs):])
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/hapi/model.py", line 941, in train_batch
    loss = self._adapter.train_batch(inputs, labels)
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/hapi/model.py", line 661, in train_batch
    final_loss.backward()
  File "<decorator-gen-114>", line 2, in backward
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/public/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 175, in backward
    retain_graph)
RuntimeError: (PreconditionNotMet) Rebuild vars's number should be equal to original vars'number, expect it to be 20, but got 21.
  [Hint: Expected rebuild_vars_.size() == vars_.size(), but received rebuild_vars_.size():21 != vars_.size():20.] (at /paddle/paddle/fluid/imperative/reducer.cc:512)

**Comment by wdhxek** [comment]
单卡训练无问题。

**Comment by kinghuin** [comment]
Hi，欢迎使用PaddleNLP，感谢您反馈问题~

我们已在最新使用示例中修复了多卡训练问题，请使用[最新代码](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/lexical_analysis)启动训练、评估、预测。
