### ISSUE TITLE
 [Question]: UIE-X 在 GPU 上 finetune 后，使用 CPU 加载出错

### ISSUE THREAD

**Issue by horizonwht** [PaddlePaddle/PaddleNLP#6100]
### 请提出你的问题

用cpu加载已经在GPU上finetune过的模型进行预测，报下列错误
错误如下：

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2023-06-05 16:39:26,313] [    INFO] - We are using <class 'paddlenlp.transformers.ernie_layout.tokenizer.ErnieLayoutTokenizer'> to load '/PaddleNlP/applications/information_extraction/model_best'.
Traceback (most recent call last):
  File "client_base64_2.py", line 16, in <module>
    results = ie({"doc": image_data, "layout":layout})
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/taskflow/taskflow.py", line 603, in __call__
    results = self.task_instance(inputs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/taskflow/task.py", line 439, in __call__
    outputs = self._run_model(inputs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/taskflow/information_extraction.py", line 941, in _run_model
    results = self._multi_stage_predict(_inputs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/taskflow/information_extraction.py", line 1039, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/taskflow/information_extraction.py", line 851, in _single_stage_predict
    self.predictor.run()
ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 1024, but got -48. Please check input value.
  [Hint: Expected ids[i] >= 0, but received ids[i]:-48 < 0:0.] (at /paddle/paddle/phi/kernels/cpu/embedding_kernel.cc:76)
  [operator < lookup_table_v2 > error]

**Comment by linjieccc** [comment]
麻烦提供下paddle paddlenlp的版本信息
