### ISSUE TITLE
[Question]:  ptq量化时报错：Operator (fusion_unified_decoding) is not registered.

### ISSUE THREAD

**Issue by Ji-Tian** [PaddlePaddle/PaddleNLP#6105]
### 请提出你的问题

使用paddleslim 量化unimo时报错：Operator (fusion_unified_decoding) is not registered.
转为静态图后好像不支持’fusion_unified_decoding‘算子，有什么办法可以支持该算子（例如如何register）？

> Preparation stage, Run batch:|                                            | 0/10
> Traceback (most recent call last):
>   File "ptq.py", line 28, in <module>
>     batch_nums=10)
>   File "/home/cciip/Application/miniconda3/envs/aigc/lib/python3.7/site-packages/paddleslim/quant/quanter.py", line 627, in quant_post_static
>     post_training_quantization.quantize()
>   File "/home/cciip/Application/miniconda3/envs/aigc/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 401, in quantize
>     scope=self._scope)
>   File "/home/cciip/Application/miniconda3/envs/aigc/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1463, in run
>     six.reraise(*sys.exc_info())
>   File "/home/cciip/Application/miniconda3/envs/aigc/lib/python3.7/site-packages/six.py", line 719, in reraise
>     raise value
>   File "/home/cciip/Application/miniconda3/envs/aigc/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1459, in run
>     return_merged=return_merged)
>   File "/home/cciip/Application/miniconda3/envs/aigc/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1641, in _run_impl
>     self.place, scope)
>   File "/home/cciip/Application/miniconda3/envs/aigc/lib/python3.7/site-packages/paddle/fluid/executor.py", line 745, in get_program_and_executor
>     fetch_var_name, place, scope))
>   File "/home/cciip/Application/miniconda3/envs/aigc/lib/python3.7/site-packages/paddle/fluid/executor.py", line 808, in _get_program_and_executor
>     skip_var_names)
>   File "/home/cciip/Application/miniconda3/envs/aigc/lib/python3.7/site-packages/paddle/fluid/executor.py", line 411, in _apply_inplace_addto_pass
>     attr_types)
>   File "/home/cciip/Application/miniconda3/envs/aigc/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4359, in _apply_pass
>     attrs = core.apply_pass(
> RuntimeError: (NotFound) Operator (fusion_unified_decoding) is not registered.
>   [Hint: op_info_ptr should not be null.] (at /paddle/paddle/fluid/framework/op_info.h:156)

**Comment by w5688414** [comment]
算子不支持的问题，请升级一下paddleslim的版本试试
