### ISSUE TITLE
[Bug]: ernie-3.0-base-zh pretrain Host端oom被kill

### ISSUE THREAD

**Issue by Aganlengzi** [PaddlePaddle/PaddleNLP#6156]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.4.2.post117
- paddlenlp: 2.5.2.post0


$ python
Python 3.8.16 (default, Mar  2 2023, 03:21:46) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0613 08:43:23.632794 12283 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.7, Runtime API Version: 11.7
W0613 08:43:23.647663 12283 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
/data/application/xxx/anaconda3/envs/paddle_ernie/lib/python3.8/site-packages/paddle/fluid/executor.py:1583: UserWarning: Standalone executor is not used for data parallel
  warnings.warn(
W0613 08:43:51.855218 12283 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 8 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

```
Tue Jun 13 08:46:41 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:13:00.0 Off |                    0 |
| N/A   25C    P0    61W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:19:00.0 Off |                    0 |
| N/A   24C    P0    62W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000000:48:00.0 Off |                    0 |
| N/A   25C    P0    62W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000000:4D:00.0 Off |                    0 |
| N/A   26C    P0    58W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM...  On   | 00000000:89:00.0 Off |                    0 |
| N/A   26C    P0    61W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM...  On   | 00000000:8E:00.0 Off |                    0 |
| N/A   25C    P0    63W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM...  On   | 00000000:AD:00.0 Off |                    0 |
| N/A   25C    P0    63W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  On   | 00000000:B3:00.0 Off |                    0 |
| N/A   26C    P0    61W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
```

背景是做复现：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/README.md
按照文档准备了ernie-3.0的数据集，clue_corpus_small_14g，运行32w step正常

运行脚本：
```
python -u  -m paddle.distributed.launch \
    --gpus "0,1,2,3,4,5,6,7" \
    --log_dir "output/ernie-3.0-base-zh-dp8-gb512/log" \
    run_pretrain.py \
    --model_type "ernie" \
    --model_name_or_path "ernie-3.0-base-zh" \
    --tokenizer_name_or_path "ernie-3.0-base-zh" \
    --input_dir "./data" \
    --output_dir "output/ernie-3.0-base-zh-dp8-gb512" \
    --split 949,50,1 \
    --max_seq_len 512 \
    --micro_batch_size 64 \
    --use_amp true \
    --fp16_opt_level O1 \
    --max_lr 0.0001 \
    --min_lr 0.00001 \
    --max_steps 1000000 \
    --save_steps 50000 \
    --checkpoint_steps 5000 \
    --decay_steps 990000 \
    --weight_decay 0.01 \
    --warmup_rate 0.01 \
    --grad_clip 1.0 \
    --logging_freq 20 \
    --num_workers 2 \
    --eval_freq 1000 \
    --device "gpu" \
    --share_folder false 
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "run_pretrain.py", line 761, in <module>
    do_train(config)
  File "run_pretrain.py", line 590, in do_train
    scaler.scale(tr_loss_step).backward()
  File "/data/application/zhangtj/anaconda3/envs/paddle_ernie/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/application/zhangtj/anaconda3/envs/paddle_ernie/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/application/zhangtj/anaconda3/envs/paddle_ernie/lib/python3.8/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/data/application/zhangtj/anaconda3/envs/paddle_ernie/lib/python3.8/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 297, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
  File "/data/application/zhangtj/anaconda3/envs/paddle_ernie/lib/python3.8/site-packages/paddle/fluid/multiprocess_utils.py", line 135, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 88037) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:188)

LAUNCH INFO 2023-06-13 07:25:49,349 Exit code -15

```
查询系统日志：
```
[296038.233997] Out of memory: Kill process 76353 (python) score 120 or sacrifice child
```

### 稳定复现步骤 & 代码

以上复现两次错误均相同，
GPU查看显存正常，执行的日志看loss趋势正常。

系统内存：
```
              total        used        free      shared  buff/cache   available
Mem:           2.0T         69G        1.9T        139M        2.9G        1.9T
Swap:          443M        210M        233M

```

在不同step查看确实看到内存在不断增长。

related: https://github.com/PaddlePaddle/PaddleNLP/issues/5942

**Comment by ZHUI** [comment]
你好，请问 你的机器 支持 mmap 吗？数据集是通过 mmap load数据的。

**Comment by tiandou-tangdou** [comment]
> 你好，请问 你的机器 支持 mmap 吗？数据集是通过 mmap load数据的。

@ZHUI 你好，支持的，跑Resnet50、llama模型都是正常的
