### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ocrifydotnet** [PaddlePaddle/PaddleNLP#6198]
### 软件环境

```Markdown
- paddlepaddle:2.4.2
- paddlepaddle-gpu: 2.4.2
- paddlenlp: 2.5.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
When use PaddleNlp UIE-X 2.5.2 with GPU 
Here is the code:
from paddlenlp import Taskflow

task_instance = Taskflow(
    "information_extraction",
    model="uie-m-base")

Here is error from the console:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\MSI GF63\AppData\Roaming\Python\Python39\site-packages\paddlenlp\taskflow\taskflow.py", line 837, in __init__
    self.task_instance = task_class(
  File "C:\Users\MSI GF63\AppData\Roaming\Python\Python39\site-packages\paddlenlp\taskflow\information_extraction.py", line 536, in __init__
    self._get_inference_model()
  File "C:\Users\MSI GF63\AppData\Roaming\Python\Python39\site-packages\paddlenlp\taskflow\task.py", line 366, in _get_inference_model
    self._prepare_static_mode()
  File "C:\Users\MSI GF63\AppData\Roaming\Python\Python39\site-packages\paddlenlp\taskflow\task.py", line 221, in _prepare_static_mode
    self.predictor = paddle.inference.create_predictor(self._config)
ValueError: (InvalidArgument) The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm_0.w_2
  [Hint: Expected std::isfinite(variance_array[i]) == true, but received std::isfinite(variance_array[i]):0 != true:1.] (at ..\paddle\fluid\framework\ir\conv_bn_fuse_pass.cc:131)
```

### 稳定复现步骤 & 代码

I don't know Chinese.

**Comment by gongel** [comment]
你好，可参考：https://github.com/PaddlePaddle/PaddleSeg/issues/3326
