### ISSUE TITLE
[Question]: 使用pipelines docker搭建服务，当并发达到20的时候，会报ValueError: generator already executing

### ISSUE THREAD

**Issue by yi1991er** [PaddlePaddle/PaddleNLP#6212]
### 请提出你的问题

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pipelines/pipelines/base.py", line 445, in run
    node_output, stream_id = self.graph.nodes[node_id]["component"]._dispatch_run(**node_input)
  File "/usr/local/lib/python3.7/dist-packages/pipelines/nodes/base.py", line 120, in _dispatch_run
    return self._dispatch_run_general(self.run, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipelines/nodes/base.py", line 164, in _dispatch_run_general
    output, stream = run_method(**run_inputs, **run_params)
  File "/usr/local/lib/python3.7/dist-packages/pipelines/nodes/retriever/base.py", line 130, in run
    query=query, query_type=query_type, filters=filters, top_k=top_k, index=index, headers=headers
  File "/usr/local/lib/python3.7/dist-packages/pipelines/nodes/retriever/base.py", line 108, in wrapper
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipelines/nodes/retriever/base.py", line 175, in run_query
    query=query, query_type=query_type, filters=filters, top_k=top_k, index=index, headers=headers
  File "/usr/local/lib/python3.7/dist-packages/pipelines/nodes/retriever/dense.py", line 199, in retrieve
    query_emb = self.embed_queries(texts=[query])
  File "/usr/local/lib/python3.7/dist-packages/pipelines/nodes/retriever/dense.py", line 331, in embed_queries
    result = self._get_predictions(queries)["query"]
  File "/usr/local/lib/python3.7/dist-packages/pipelines/nodes/retriever/dense.py", line 310, in _get_predictions
    cls_embeddings = self.query_encoder(datasets[i : i + self.batch_size])
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/taskflow.py", line 850, in __call__
    results = self.task_instance(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/task.py", line 516, in __call__
    outputs = self._run_model(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/text_feature_extraction.py", line 267, in _run_model
    with static_mode_guard():
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/taskflow/utils.py", line 118, in static_mode_guard
    paddle.enable_static()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 227, in disable_dygraph
    _functional_dygraph_context_manager.__exit__(*sys.exc_info())
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
ValueError: generator already executing

**Comment by w5688414** [comment]
请问您需要达到多大的并发呢？可以接入fastdeploy进行优化

**Comment by yi1991er** [comment]
补充下：
我想把项目中的[faq](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/FAQ)项目部署到生产环境，单节点支持20个并发；
部署完成后做压力测试，会报上述的错误，请问下有没有办法优化

**Comment by w5688414** [comment]
> 

可以使用fastdeploy来进行优化，这需要您一点开发成本，融合onnx或者tensorrt。实现方式请参考https://github.com/PaddlePaddle/PaddleNLP/pull/5884
