### ISSUE TITLE
[Bug]:文档信息抽取报错

### ISSUE THREAD

**Issue by zhong16602192407** [PaddlePaddle/PaddleNLP#6220]
### 软件环境

```Markdown
paddle-bfloat         0.1.7
paddle2onnx           1.0.6
paddlefsl             1.1.0
paddlenlp             2.6.0rc0
paddleocr             2.6.1.3
paddlepaddle-gpu      2.4.2.post117
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
执行PaddleNLP/applications/information_extraction
/label_studio_doc.md 里面的步骤，参照关系抽取生成label_studio.json
后开始训练模型报错如下：
Traceback (most recent call last):
  File "/u01/script/PaddleNLP-develop/applications/information_extraction/document/finetune.py", line 177, in <module>
    main()
  File "/u01/script/PaddleNLP-develop/applications/information_extraction/document/finetune.py", line 147, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/u01/soft/anaconda3/envs/paddle_ocr_env/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 788, in train
    self._maybe_log_save_evaluate(tr_loss, model, epoch, ignore_keys_for_eval, inputs=inputs)
  File "/u01/soft/anaconda3/envs/paddle_ocr_env/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 930, in _maybe_log_save_evaluate
    self._save_checkpoint(model, metrics=metrics)
  File "/u01/soft/anaconda3/envs/paddle_ocr_env/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 1659, in _save_checkpoint
    metric_value = metrics[metric_to_check]
KeyError: 'eval_f1'
------------------------------------------------------------------------
是添加了关系才导致的问题，用的是devlop分支
```

### 稳定复现步骤 & 代码

无

**Comment by linjieccc** [comment]
@zhong16602192407 你好，麻烦提供一下复现方式哈

**Comment by DouLiu95** [comment]
是否和这个是同样的问题？https://github.com/PaddlePaddle/PaddleNLP/issues/5350
