### ISSUE TITLE
[Question]: NER任务不支持批量输入了么？

### ISSUE THREAD

**Issue by Math312** [PaddlePaddle/PaddleNLP#6238]
### 请提出你的问题

根据文档：[命名实体识别](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#%E5%91%BD%E5%90%8D%E5%AE%9E%E4%BD%93%E8%AF%86%E5%88%AB)中的

`from paddlenlp import Taskflow

ner = Taskflow("ner", entity_only=False, use_gpu=False)
results = ner(["热梅茶是一道以梅子为主要原料制作的茶饮", "《孤女》是2010年九州出版社出版的小说，作者是余兼羽"])
print(results)`

跑的例子，报错如下：

`Traceback (most recent call last):
  File "D:\File\竞赛\FNDEE\process\test.py", line 4, in <module>
    results = ner(["热梅茶是一道以梅子为主要原料制作的茶饮", "《孤女》是2010年九州出版社出版的小说，作者是余兼羽"])
  File "D:\Tool\miniconda3\envs\fndee\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 850, in __call__
    results = self.task_instance(inputs)
  File "D:\Tool\miniconda3\envs\fndee\lib\site-packages\paddlenlp\taskflow\task.py", line 516, in __call__
    outputs = self._run_model(inputs)
  File "D:\Tool\miniconda3\envs\fndee\lib\site-packages\paddlenlp\taskflow\knowledge_mining.py", line 464, in _run_model
    self.predictor.run()
ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 512, but got 4440227630765077628. Please check input value.
  [Hint: Expected ids[i] < row_number, but received ids[i]:4440227630765077628 >= row_number:512.] (at ..\paddle\phi\kernels\cpu\embedding_kernel.cc:67)
  [operator < lookup_table_v2 > error]

Process finished with exit code 1
`

我的paddle相关包的版本:

包名|版本号
---|---
paddle-bfloat |0.1.7
paddle2onnx |1.0.6
paddlefsl|1.1.0
paddlenlp|2.5.2
paddlepaddle|2.5.0
pandas|2.0.2

系统：Win11

**Comment by linjieccc** [comment]
你好，请尝试执行``paddle.utils.run_check()``验证下安装正确性 @Math312

**Comment by Math312** [comment]
首先，我添加了`paddle.utils.run_check()`，结果如下：

```
Running verify PaddlePaddle program ... 
I0625 15:09:05.933393 26404 interpretercore.cc:237] New Executor is Running.
I0625 15:09:05.945360 26404 interpreter_util.cc:518] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
[2023-06-25 15:09:07,361] [    INFO] - Already cached C:\Users\89468\.paddlenlp\models\wordtag\vocab.txt
[2023-06-25 15:09:07,373] [    INFO] - tokenizer config file saved in C:\Users\89468\.paddlenlp\models\wordtag\tokenizer_config.json
[2023-06-25 15:09:07,374] [    INFO] - Special tokens file saved in C:\Users\89468\.paddlenlp\models\wordtag\special_tokens_map.json
[('热梅茶是一道以', '饮食类_饮品'), ('梅', '信息资料_性别'), ('子为主要原料制作的茶饮', '文化类_姓氏与人名')]
Traceback (most recent call last):
  File "D:\test.py", line 7, in <module>
    results = ner("热梅茶是一道以梅子为主要原料制作的茶饮", "《孤女》是2010年九州出版社出版的小说，作者是余兼羽")
  File "D:\Tool\miniconda3\envs\fndee\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 850, in __call__
    results = self.task_instance(inputs)
  File "D:\Tool\miniconda3\envs\fndee\lib\site-packages\paddlenlp\taskflow\task.py", line 516, in __call__
    outputs = self._run_model(inputs)
  File "D:\Tool\miniconda3\envs\fndee\lib\site-packages\paddlenlp\taskflow\knowledge_mining.py", line 464, in _run_model
    self.predictor.run()
ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 512, but got 4440227630765077628. Please check input value.
  [Hint: Expected ids[i] < row_number, but received ids[i]:4440227630765077628 >= row_number:512.] (at ..\paddle\phi\kernels\cpu\embedding_kernel.cc:67)
  [operator < lookup_table_v2 > error]
```

我的本地代码如下:

```python
from paddlenlp import Taskflow
import paddle
paddle.utils.run_check()
ner = Taskflow("ner", entity_only=True, use_gpu=True)
results = ner("热梅茶是一道以梅子为主要原料制作的茶饮", "《孤女》是2010年九州出版社出版的小说，作者是余兼羽")
print(results)
results = ner("热梅茶是一道以梅子为主要原料制作的茶饮", "《孤女》是2010年九州出版社出版的小说，作者是余兼羽")
print(results)
```

稳定复现该bug，只要调用第二次就会出问题，而且不知道为何，没有用我的GPU

**Comment by linjieccc** [comment]
可以参考这里安装gpu版本的paddle https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html
