### ISSUE TITLE
ErnieGramForSequenceClassification 代码示例报错

### ISSUE THREAD

**Issue by kobe24o** [PaddlePaddle/PaddleNLP#625]
D:\ProgramData\Anaconda3\envs\pp21\Lib\site-packages\paddlenlp\transformers\ernie_gram\modeling.py

line 547 - 560 

 Example:
        """

                import paddle
                from paddlenlp.transformers import ErnieGramForSequenceClassification, ErnieGramTokenizer

                tokenizer = ErnieGramTokenizer.from_pretrained('ernie-gram-zh')
                model = ErnieGramForSequenceClassification.from_pretrained('ernie-gram-zh')

                inputs = tokenizer("这是个测试样例")
                inputs = {k:paddle.to_tensor(v) for (k, v) in inputs.items()}
                logits = model(**inputs)

        """

运行该段代码后报错了，环境安装没有问题。求解答。多谢大佬！

[2021-06-24 18:31:53,940] [    INFO] - Found C:\Users\**\.paddlenlp\models\ernie-gram-zh\vocab.txt
[2021-06-24 18:31:53,954] [    INFO] - Already cached C:\Users\**\.paddlenlp\models\ernie-gram-zh\ernie_gram_zh.pdparams
W0624 18:31:53.955507 48468 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 5.0, Driver API Version: 11.2, Runtime API Version: 10.2
W0624 18:31:53.975438 48468 device_context.cc:422] device: 0, cuDNN Version: 7.6.
D:\ProgramData\Anaconda3\envs\pp21\lib\site-packages\paddle\fluid\dygraph\layers.py:1297: UserWarning: Skip loading for classifier.weight. classifier.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
D:\ProgramData\Anaconda3\envs\pp21\lib\site-packages\paddle\fluid\dygraph\layers.py:1297: UserWarning: Skip loading for classifier.bias. classifier.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
Traceback (most recent call last):
  File "D:/huohua/classroom-interaction/common/test.py", line 7, in <module>
    logits = model(**inputs)
  File "D:\ProgramData\Anaconda3\envs\pp21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\pp21\lib\site-packages\paddlenlp\transformers\ernie_gram\modeling.py", line 561, in forward
    _, pooled_output = self.ernie_gram(
  File "D:\ProgramData\Anaconda3\envs\pp21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\pp21\lib\site-packages\paddlenlp\transformers\ernie_gram\modeling.py", line 284, in forward
    embedding_output = self.embeddings(
  File "D:\ProgramData\Anaconda3\envs\pp21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\pp21\lib\site-packages\paddlenlp\transformers\ernie_gram\modeling.py", line 61, in forward
    seq_length = paddle.cumsum(ones, axis=1)
  File "D:\ProgramData\Anaconda3\envs\pp21\lib\site-packages\paddle\tensor\math.py", line 1753, in cumsum
    return core.ops.cumsum(x, 'axis', axis, 'flatten', flatten)
IndexError: (OutOfRange) Attr(axis) is out of range, It's expected to be in range of [-1, 0]. But received Attr(axis) = 1.
  [Hint: Expected axis < out_dims.size() && axis >= (0 - out_dims.size()) == true, but received axis < out_dims.size() && axis >= (0 - out_dims.size()):0 != true:1.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/cumsum_op.cu:205)
  [operator < cumsum > error]

Process finished with exit code 1

**Comment by Steffy-zxf** [comment]
@kobe24o 你好！感谢反馈！请按照以下代码示例尝试运行：
```python
import paddle
from paddlenlp.transformers import ErnieGramForSequenceClassification, ErnieGramTokenizer

tokenizer = ErnieGramTokenizer.from_pretrained('ernie-gram-zh')
model = ErnieGramForSequenceClassification.from_pretrained('ernie-gram-zh', num_classes=2)

inputs = tokenizer("这是个测试样例")
inputs = {k:paddle.to_tensor([v]) for (k, v) in inputs.items()}
logits = model(**inputs)
```

代码示例我们将会修正，再次感谢反馈！

**Comment by kobe24o** [comment]
> @kobe24o 你好！感谢反馈！请按照以下代码示例尝试运行：
> 
> ```python
> import paddle
> from paddlenlp.transformers import ErnieGramForSequenceClassification, ErnieGramTokenizer
> 
> tokenizer = ErnieGramTokenizer.from_pretrained('ernie-gram-zh')
> model = ErnieGramForSequenceClassification.from_pretrained('ernie-gram-zh', num_classes=2)
> 
> inputs = tokenizer("这是个测试样例")
> inputs = {k:paddle.to_tensor([v]) for (k, v) in inputs.items()}
> logits = model(**inputs)
> ```
> 
> 代码示例我们将会修正，再次感谢反馈！

多谢大佬！
