### ISSUE TITLE
[Bug]: AttributeError: 'ModelArguments' object has no attribute 'use_fused_rms_norm'

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/PaddleNLP#6366]
### 软件环境

```Markdown
- paddlepaddle: develop latest
- paddlepaddle-gpu: develop latest
- paddlenlp: develop
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Python代码有错误，按gpt教程输入 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/gpt/README.md

cd model_zoo/gpt
CUDA_VISIBLE_DEVICES=0 python run_pretrain_trainer.py \
    --model_type "gpt" \
    --model_name_or_path "gpt2-en" \
    --tokenizer_name_or_path "gpt2-en" \
    --input_dir "./data" \
    --output_dir "output" \
    --split 949,50,1 \
    --max_seq_length 1024 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --fp16  \
    --fp16_opt_level "O2"  \
    --learning_rate 0.0001 \
    --min_learning_rate 0.00001 \
    --max_steps 10000 \
    --save_steps 5000 \
    --weight_decay 0.01 \
    --warmup_ratio 0.01 \
    --max_grad_norm 1.0 \
    --logging_steps 20 \
    --dataloader_num_workers 1 \
    --eval_steps 1000 \
    --report_to "visualdl" \
    --disable_tqdm true \
    --do_train \
    --do_eval \
    --device "gpu"



```

出现错误，ModelArguments缺少属性 use_fused_rms_norm
```
[2023-07-12 09:15:13,801] [    INFO] - Reset vocab size to 50304 for batter amp peformance.
Traceback (most recent call last):
  File "/mnt/sda/public/github/PaddleNLP/model_zoo/gpt/run_pretrain_trainer.py", line 474, in <module>
    main()
  File "/mnt/sda/public/github/PaddleNLP/model_zoo/gpt/run_pretrain_trainer.py", line 390, in main
    config.use_fused_rms_norm = model_args.use_fused_rms_norm
AttributeError: 'ModelArguments' object has no attribute 'use_fused_rms_norm'

```

### 稳定复现步骤 & 代码

```shell
cd model_zoo/gpt
CUDA_VISIBLE_DEVICES=0 python run_pretrain_trainer.py \
    --model_type "gpt" \
    --model_name_or_path "gpt2-en" \
    --tokenizer_name_or_path "gpt2-en" \
    --input_dir "./data" \
    --output_dir "output" \
    --split 949,50,1 \
    --max_seq_length 1024 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --fp16  \
    --fp16_opt_level "O2"  \
    --learning_rate 0.0001 \
    --min_learning_rate 0.00001 \
    --max_steps 10000 \
    --save_steps 5000 \
    --weight_decay 0.01 \
    --warmup_ratio 0.01 \
    --max_grad_norm 1.0 \
    --logging_steps 20 \
    --dataloader_num_workers 1 \
    --eval_steps 1000 \
    --report_to "visualdl" \
    --disable_tqdm true \
    --do_train \
    --do_eval \
    --device "gpu"
```

**Comment by w5688414** [comment]
现在使用一下最新的代码试试：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/gpt-3

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm/gpt-3
