### ISSUE TITLE
[Question]: PaddleNLP 安装失败

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/PaddleNLP#6377]
### 请提出你的问题

本机window环境信息:
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/49382323/f6a1a122-35df-450f-b75d-4498488e0b44)

执行安装指令:
```
pip install --upgrade paddlenlp
```

报错信息如下(安装最新 develop 分支代码报错也一样):
```
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting paddlenlp
  Using cached http://mirrors.aliyun.com/pypi/packages/e4/67/f97788181e3a49afcdf8ffa162a335c21d18a55387bae85be24b01383165/paddlenlp-2.5.2-py3-none-any.whl (2.3 MB)
Collecting jieba (from paddlenlp)
  Using cached http://mirrors.aliyun.com/pypi/packages/c6/cb/18eeb235f833b726522d7ebed54f2278ce28ba9438e3135ab0278d9792a2/jieba-0.42.1.tar.gz (19.2 MB)
  Preparing metadata (setup.py) ... done
Collecting colorlog (from paddlenlp)
  Using cached http://mirrors.aliyun.com/pypi/packages/58/43/a363c213224448f9e194d626221123ce00e3fb3d87c0c22aed52b620bdd1/colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: colorama in c:\users\aoc\.conda\envs\paddle_env\lib\site-packages (from paddlenlp) (0.4.6)
Collecting seqeval (from paddlenlp)
  Using cached http://mirrors.aliyun.com/pypi/packages/9d/2d/233c79d5b4e5ab1dbf111242299153f3caddddbb691219f363ad55ce783d/seqeval-1.2.2.tar.gz (43 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
      ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
      ERROR: No matching distribution found for setuptools_scm
      C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\setuptools\installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\aoc\\.conda\\envs\\paddle_env\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\aoc\\AppData\\Local\\Temp\\tmp5_r635pa', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\aoc\AppData\Local\Temp\pip-install-b3cedr3u\seqeval_fd250cb0a23749199ee09c35e9b34fff\setup.py", line 27, in <module>
          setup(
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\setuptools\__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\setuptools\__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\setuptools\__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\setuptools\dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\setuptools\installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\pkg_resources\__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\pkg_resources\__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\pkg_resources\__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\pkg_resources\__init__.py", line 1145, in obtain
          return installer(requirement)
        File "C:\Users\aoc\.conda\envs\paddle_env\lib\site-packages\setuptools\installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['C:\\Users\\aoc\\.conda\\envs\\paddle_env\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\aoc\\AppData\\Local\\Temp\\tmp5_r635pa', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tianchiguaixia** [comment]
pip install -r requirements.txt
pip install paddlenlp==2.5.2

**Comment by kerry-weic** [comment]
@tianchiguaixia  一样，报同样的错误

**Comment by CYTand** [comment]
相同问题，通过这个方法解决了：
先安装 setuptools_scm
再安装 seqeval
最后安装 paddlenlp
```shell
pip install setuptools_scm
pip install seqeval
pip install paddlenlp
``` 

参考自：
https://blog.csdn.net/qq_34451909/article/details/123629121

**Comment by kerry-weic** [comment]
> 相同问题，通过这个方法解决了： 先安装 setuptools_scm 再安装 seqeval 最后安装 paddlenlp
> 
> ```shell
> pip install setuptools_scm
> pip install seqeval
> pip install paddlenlp
> ```
> 
> 参考自： https://blog.csdn.net/qq_34451909/article/details/123629121

@CYTand 按此方法已安装成功，感谢~
