### ISSUE TITLE
[Bug]: model export failed with error: "ValueError: The feeded_var_names[0]: 'input_ids' doesn't exist in pruned inference program. Please check whether 'input_ids' is a valid feed_var name, or remove it from feeded_var_names if 'input_ids' is not involved in the target_vars calculation."

### ISSUE THREAD

**Issue by zorro-gridi** [PaddlePaddle/PaddleNLP#6467]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 0.0.0
- paddlenlp: 2.6
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
# Export.
    if training_args.do_export:
        input_spec = [
            InputSpec(shape=[None, None], dtype="int64", name="input_ids"),
            InputSpec(shape=[None, None], dtype="int64", name="token_type_ids"),
            InputSpec(shape=[None, None], dtype="int64", name="position_ids"),
            InputSpec(shape=[None, None, None, None], dtype="float32", name="attention_mask"),
            InputSpec(shape=[None, None], dtype="int64", name="omask_positions"),
            InputSpec(shape=[None], dtype="int64", name="cls_positions"),
        ]
        export_model(trainer.pretrained_model, input_spec, model_args.export_model_dir, model_args.export_type)
```

### 稳定复现步骤 & 代码

Traceback (most recent call last):
  File "PaddleNLP/applications/zero_shot_text_classification/run_train.py", line 154, in <module>
    main()
  File "PaddleNLP/applications/zero_shot_text_classification/run_train.py", line 150, in main
    export_model(trainer.pretrained_model, input_spec, model_args.export_model_dir, model_args.export_type)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/export.py", line 59, in export_model
    paddle.jit.save(model, save_path)
  File "<decorator-gen-290>", line 2, in save
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/jit/api.py", line 752, in wrapper
    func(layer, path, input_spec, **configs)
  File "<decorator-gen-289>", line 2, in save
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/jit/api.py", line 1208, in save
    clip_extra=configs.clip_extra,
  File "<decorator-gen-39>", line 2, in save_inference_model
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 473, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 315, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 92, in prepend_feed_ops
    i=i, name=name
ValueError: The feeded_var_names[0]: 'input_ids' doesn't exist in pruned inference program. Please check whether 'input_ids' is a valid feed_var name, or remove it from feeded_var_names if 'input_ids' is not involved in the target_vars calculation.

**Comment by gridizorro** [comment]
done

**Comment by zorro-gridi** [comment]
paddlepaddle-gpu安装了dev版导致错误，安装正式版本就可以了
