### ISSUE TITLE
[Question]: 网盘地址的模型配置文件404了

### ISSUE THREAD

**Issue by longtong99** [PaddlePaddle/PaddleNLP#6476]
### 请提出你的问题

`# 训练模型，这里用的是宝可梦的数据
!export MODEL_NAME="CompVis/stable-diffusion-v1-4"
!export dataset_name="lambdalabs/pokemon-blip-captions"

!python -u train_text_to_image.py \
   --pretrained_model_name_or_path=$MODEL_NAME \
   --dataset_name=$dataset_name \
   --resolution=512 --center_crop --random_flip \
   --train_batch_size=1 \
   --gradient_accumulation_steps=4 \
   --gradient_checkpointing \
   --max_train_steps=15000 \
   --learning_rate=1e-05 \
   --max_grad_norm=1 \
   --lr_scheduler="constant" --lr_warmup_steps=0 \
   --output_dir="sd-pokemon-model"`

想使用这个模型进行训练，但是飞桨加载模型的时候直接404了，这是异常

`/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-07-24 14:42:33,349] [ WARNING] - Detected that datasets module was imported before paddlenlp. This may cause PaddleNLP datasets to be unavalible in intranet. Please import paddlenlp before datasets module to avoid download issues
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://bj.bcebos.com/paddlenlp/models/community//scheduler/scheduler_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/ppdiffusers/utils/download_utils.py", line 523, in bos_hf_download
    model_file = ppdiffusers_bos_download(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/ppdiffusers/utils/download_utils.py", line 327, in ppdiffusers_bos_download
    http_get(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 514, in http_get
    hf_raise_for_status(r)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 404 Client Error: Not Found for url: https://bj.bcebos.com/paddlenlp/models/community//scheduler/scheduler_config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aistudio/train_text_to_image.py", line 816, in <module>
    main()
  File "/home/aistudio/train_text_to_image.py", line 426, in main
    noise_scheduler = DDPMScheduler.from_pretrained(args.pretrained_model_name_or_path, subfolder="scheduler")
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/ppdiffusers/schedulers/scheduling_utils.py", line 141, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/ppdiffusers/configuration_utils.py", line 358, in load_config
    config_file = bos_hf_download(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/ppdiffusers/utils/download_utils.py", line 535, in bos_hf_download
    raise EnvironmentError(
OSError: 404 Client Error: Not Found for url: https://bj.bcebos.com/paddlenlp/models/community//scheduler/scheduler_config.json!
There was a specific connection error when trying to load ''! We couldn't connect to 'https://bj.bcebos.com/paddlenlp' to load this model, couldn't find it in the cached files and it looks like '' is not the path to a directory containing a file named 'scheduler_config.json'.`

想请问下是模型地址改了吗，要怎么升级呢

**Comment by sijunhe** [comment]
麻烦 @JunnYu 看下

**Comment by JunnYu** [comment]
你在jupyter 里面不能通过 !export MODEL_NAME="CompVis/stable-diffusion-v1-4" 设置环境变量，这样改一下
```sh
!python -u train_text_to_image.py
--pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4"
--dataset_name="lambdalabs/pokemon-blip-captions"
--resolution=512 --center_crop --random_flip
--train_batch_size=1
--gradient_accumulation_steps=4
--gradient_checkpointing
--max_train_steps=15000
--learning_rate=1e-05
--max_grad_norm=1
--lr_scheduler="constant" --lr_warmup_steps=0
--output_dir="sd-pokemon-model" 
```
