### ISSUE TITLE
[Bug]:windows系统按指导步骤搭建端到端语义检索系统，在步骤1.3与1.4.2处均报错，无法正常运行

### ISSUE THREAD

**Issue by Starbeginforward** [PaddlePaddle/PaddleNLP#6482]
### 软件环境

```Markdown
- paddlepaddle:2.5.0
- paddlepaddle-gpu: cpu版
- paddlenlp: 2.5.2
- paddle-bfloat                  0.1.7
- paddle-pipelines               0.5.3
- paddle2onnx                    1.0.6
- paddlefsl                      1.1.0
- paddleocr                      2.6.1.3
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
我尝试过很多次，均严格安装指南进行操作，但就是进行报错，换了个电脑跑还是一样的结果
步骤1.3的报错为
Traceback (most recent call last):
  File "examples/semantic-search/semantic_search_example.py", line 202, in <module>
    semantic_search_tutorial()
  File "examples/semantic-search/semantic_search_example.py", line 174, in semantic_search_tutorial
    retriever = get_faiss_retriever(use_gpu)
  File "examples/semantic-search/semantic_search_example.py", line 81, in get_faiss_retriever
    retriever = DensePassageRetriever(
TypeError: __init__() got an unexpected keyword argument 'pooling_mode'

步骤1.4.2的报错为:
Traceback (most recent call last):
  File "utils/offline_ann.py", line 20, in <module>
    from pipelines.utils.preprocessing import convert_files_to_dicts_splitter
ImportError: cannot import name 'convert_files_to_dicts_splitter' from 'pipelines.utils.preprocessing' (F:\dev\anaconda\envs\paddle_search\lib\site-packages\pipelines\utils\preprocessing.py)

请帮我解答，有没有可能是pipelines的版本问题。
```

### 稳定复现步骤 & 代码

步骤均按指南一步一步操作，指南链接：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/examples/semantic-search/Install_windows.md。报错结果如错误描述所表示。

**Comment by w5688414** [comment]
请安装develop版本：

```
git clone https://github.com/PaddlePaddle/PaddleNLP.git
cd PaddleNLP/pipelines
python setup.py install
```

**Comment by Starbeginforward** [comment]
您好，感谢您的回复，我运行了您提供给我的代码，然后再运行步骤1.3处的代码：python examples/semantic-search/semantic_search_example.py --device cpu
现在依旧报错，与原来的错误一致：
Traceback (most recent call last):
  File "examples/semantic-search/semantic_search_example.py", line 202, in <module>
    semantic_search_tutorial()
  File "examples/semantic-search/semantic_search_example.py", line 174, in semantic_search_tutorial
    retriever = get_faiss_retriever(use_gpu)
  File "examples/semantic-search/semantic_search_example.py", line 81, in get_faiss_retriever
    retriever = DensePassageRetriever(
TypeError: __init__() got an unexpected keyword argument 'pooling_mode'

这是我运行pip list | grep paddle 的运行结果：
paddle-bfloat                  0.1.7
paddle-pipelines               0.5.3
paddle2onnx                    1.0.6
paddlefsl                      1.1.0
paddlenlp                      2.5.2
paddleocr                      2.6.1.3
paddlepaddle                   2.5.0

请问还有什么解决方法没有？

**Comment by w5688414** [comment]
> 您好，感谢您的回复，我运行了您提供给我的代码，然后再运行步骤1.3处的代码：python examples/semantic-search/semantic_search_example.py --device cpu 现在依旧报错，与原来的错误一致： Traceback (most recent call last): File "examples/semantic-search/semantic_search_example.py", line 202, in semantic_search_tutorial() File "examples/semantic-search/semantic_search_example.py", line 174, in semantic_search_tutorial retriever = get_faiss_retriever(use_gpu) File "examples/semantic-search/semantic_search_example.py", line 81, in get_faiss_retriever retriever = DensePassageRetriever( TypeError: **init**() got an unexpected keyword argument 'pooling_mode'
> 
> 这是我运行pip list | grep paddle 的运行结果： paddle-bfloat 0.1.7 paddle-pipelines 0.5.3 paddle2onnx 1.0.6 paddlefsl 1.1.0 paddlenlp 2.5.2 paddleocr 2.6.1.3 paddlepaddle 2.5.0
> 
> 请问还有什么解决方法没有？

```
pip install git+https://github.com/PaddlePaddle/PaddleNLP.git
```

**Comment by skywalk163** [comment]
我也碰到了楼主的问题，环境是AIStudio里的linux，在使用上面pip install git+https://github.com/PaddlePaddle/PaddleNLP.git 安装PaddleNLP新版本，pooling_mode报错问题解决。
现在出现新的报错：FileNotFoundError: [Errno 2] No such file or directory: '/home/aistudio/.paddlenlp/taskflow/rocketqa-zh-nano-query-encoder/onnx/text'

**Comment by w5688414** [comment]
> pip install git+https://github.com/PaddlePaddle/PaddleNLP.git

bug已修复。https://github.com/PaddlePaddle/PaddleNLP/pull/6521

**Comment by 1042312930** [comment]
我也遇到了
cannot import name 'convert_files_to_dicts_splitter' from 'pipelines.utils.preprocessing

**Comment by w5688414** [comment]
那个是新加的功能，升级一下paddle-pipelines的版本试一下
