### ISSUE TITLE
[Question]: PaddleNLP SimpleServing 的服务化部署后服务端报错

### ISSUE THREAD

**Issue by yunguanglu501** [PaddlePaddle/PaddleNLP#6592]
### 请提出你的问题

[paddlenlp s](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/document/deploy/simple_serving)
按这个教程部署后,服务端报错.python 版本 3.7,paddlenlp 2.5.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.7/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 300, in app
    is_coroutine=is_coroutine,
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 166, in serialize_response
    exclude_none=exclude_none,
  File "/usr/local/lib/python3.7/dist-packages/fastapi/_compat.py", line 149, in serialize
    exclude_none=exclude_none,
  File "/usr/local/lib/python3.7/dist-packages/pydantic/type_adapter.py", line 278, in dump_python
    warnings=warnings,
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: 0.43126274478055393

**Comment by yunguanglu501** [comment]
已解决,把fastapi版本降级下就可以了.
python -m pip install fastapi==0.97.0 -i https://mirror.baidu.com/pypi/simple

**Comment by 396523088** [comment]
有用

**Comment by achial** [comment]
大佬，你是怎么排查出这个错误的

**Comment by achial** [comment]
有用，已经解决
