### ISSUE TITLE
使用文本生成训练的模型无法加载进行预测

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleNLP#660]
使用ernie-gen脚本训练好模型后，再次加载就会报错

raceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py", line 791, in load
    f, encoding='latin1')
_pickle.UnpicklingError: pickle data was truncated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py", line 816, in load
    tensor, _ = _load_selected_rows(path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py", line 476, in _load_selected_rows
    _seek = core._load_selected_rows(temp_sr, file_name)
ValueError: (InvalidArgument) Only version 0 SelectedRows is supported.
  [Hint: Expected version == 0U, but received version:1904018048 != 0U:0.] (at /paddle/paddle/fluid/framework/selected_rows.cc:139)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py", line 820, in load
    tensor, _ = _load_lod_tensor(path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py", line 461, in _load_lod_tensor
    _seek = paddle.fluid.core._load_lod_tensor(temp_t, file_name)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 1904018048 found).
  [Hint: Expected version == 0U, but received version:1904018048 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:329)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py", line 832, in load
    program_desc_str)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 5080, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:103)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./predict.py", line 149, in <module>
    predict()
  File "./predict.py", line 98, in predict
    model_state = paddle.load(args.init_checkpoint)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/io.py", line 837, in load
    path))
ValueError: `paddle.load` can not parse the file:/home/aistudio/PaddleNLP/examples/text_generation/ernie-gen/tmp/cur_model/model_state.pdparams.

**Comment by ZHUI** [comment]
您好，请问您的 Paddle 版本是？
加载的参数的paddle版本，跟训练使用的paddle版本是一致的吗？

**Comment by thunder95** [comment]
> 您好，请问您的 Paddle 版本是？
> 加载的参数的paddle版本，跟训练使用的paddle版本是一致的吗？

同一个版本,  在aistudio上运行的， 版本是2.1.0，我可以稍后再次确认一下

**Comment by ZHUI** [comment]
> 版本是2.1.0

建议下载model_state.pdparams到本地试一下，或者再重新checkpoint试一下。保证paddle版本一致。看报错像是文件解析错误了，可能跟版本会有一些关系。
方便的话，可以给一个 model_state.pdparams 的下载链接，我们这边也试一下

**Comment by thunder95** [comment]
> > 版本是2.1.0
> 
> 建议下载model_state.pdparams到本地试一下，或者再重新checkpoint试一下。保证paddle版本一致。看报错像是文件解析错误了，可能跟版本会有一些关系。
> 方便的话，可以给一个 model_state.pdparams 的下载链接，我们这边也试一下

@ZHUI nlp和paddle都使用最新版本后 重新训练 就没出现这个问题了
