### ISSUE TITLE
[Question]: 语义检索报错 ：conflicts with existing mapper:\n\tCannot update parameter [dims] from [768] to [312]')

### ISSUE THREAD

**Issue by mrliangcb** [PaddlePaddle/PaddleNLP#6600]
### 请提出你的问题

按照该指示部署语义检索系统 : https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/examples/semantic-search/Install_windows.md

软件环境:
paddle-bfloat 0.1.7
paddle-pipelines 0.5.3
paddle2onnx 1.0.6
paddlefsl 1.1.0
paddlenlp 2.6.0rc0.post0
paddleocr 2.6.1.3
paddlepaddle-gpu 2.5.0.post116
onnx 1.14.0
onnxconverter-common 1.13.0
onnxruntime-gpu 1.15.1
paddle2onnx 1.0.6

python examples/semantic-search/semantic_search_example.py --device gpu
运行正常

Query: 亚马逊河流的介绍

{   'content': '亚马逊河大部分在巴西境内.巴西人自豪地称之为“河海”.亚马逊河是拉丁美洲人民的骄傲.亚马逊河滋润着南美洲的 广袤土地,孕育了世界最大的热带雨林,使这一片地域成为世界上公认的最神秘的“生命王国”.亚马逊河 '
               '维基百科,自由的百科全书 跳转到:导航,搜索 亚马孙河 全长 6,296 km 源头海拔高度 5,597 m 平均流量 '
               '219,000 m&sup3;/s 流域面积 6,915,000 km&sup2; 源头 奈瓦多·米斯米峰 出海口 大西洋 '
               '流经国家 '
               '亚马逊河(大陆官方译名亚马孙河)位于南美洲,虽然长度在世界上处于第二位,但流量是世界上最大的,比其他三条大河:尼罗河、密西西比河和长江的流量总和还要大,亚马逊河的流域面积也是世界上最大的.亚马逊河向大西洋排放的水量达到了每秒18万4千 立方米,相当于全世界所有河流向海洋排放的淡水总量的五分之一,从亚马逊河口直到肉眼看不到海岸的地方,海洋中的',
    'name': 'dev27.txt'}
……

运行命令
$env:PIPELINE_YAML_PATH='rest_api/pipeline/semantic_search.yaml'
python rest_api/application.py 8891

报错为:
Traceback (most recent call last):
  File "D:\my_pipelines\paddlegit\PaddleNLP-develop\pipelines\rest_api\application.py", line 29, in <module>
    from rest_api.controller.router import router as api_router
  File ".\rest_api\controller\router.py", line 17, in <module>
    from rest_api.controller import file_upload, search, feedback, document
  File ".\rest_api\controller\file_upload.py", line 70, in <module>
    INDEXING_PIPELINE = Pipeline.load_from_yaml(Path(PIPELINE_YAML_PATH), pipeline_name=INDEXING_PIPELINE_NAME)
  File "D:\anaconda3\envs\pipe-gpu2\lib\site-packages\paddle_pipelines-0.5.3-py3.9.egg\pipelines\pipelines\base.py", line 265, in load_from_yaml
    return cls.load_from_config(
  File "D:\anaconda3\envs\pipe-gpu2\lib\site-packages\paddle_pipelines-0.5.3-py3.9.egg\pipelines\pipelines\base.py", line 759, in load_from_config
    component = cls._load_or_get_component(name=name, definitions=component_definitions, components=components)
  File "D:\anaconda3\envs\pipe-gpu2\lib\site-packages\paddle_pipelines-0.5.3-py3.9.egg\pipelines\pipelines\base.py", line 796, in _load_or_get_component
    raise Exception(f"Failed loading pipeline component '{name}': {e}")
Exception: Failed loading pipeline component 'Retriever': Failed loading pipeline component 'DocumentStore': RequestError(400, 'illegal_argument_exception', 'Mapper for [embedding] conflicts with existing mapper:\n\tCannot update parameter [dims] from [768] to [312]')

**Comment by w5688414** [comment]
请确保使用的是同一个模型，nano模型的维度是312，base模型的维度是768
