### ISSUE TITLE
[Bug]: AttributeError: 'paddle.fluid.libpaddle.AnalysisConfig' object has no attribute 'enable_npu'

### ISSUE THREAD

**Issue by BrightXiaoHan** [PaddlePaddle/PaddleNLP#6623]
### 软件环境

```Markdown
paddle-custom-npu   0.0.0
paddle2onnx         1.0.5
paddlefsl           1.1.0
paddlenlp           2.5.2
paddlepaddle        0.0.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
我在昇腾环境按照https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md
编译了paddle，并安装了paddlenlp
执行Taskflow API报了以下错误

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddlenlp/taskflow/taskflow.py", line 837, in __init__
    self.task_instance = task_class(
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddlenlp/taskflow/information_extraction.py", line 536, in __init__
    self._get_inference_model()
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddlenlp/taskflow/task.py", line 366, in _get_inference_model
    self._prepare_static_mode()
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddlenlp/taskflow/task.py", line 199, in _prepare_static_mode
    self._config.enable_npu(self.kwargs["device_id"])
AttributeError: 'paddle.fluid.libpaddle.AnalysisConfig' object has no attribute 'enable_npu'
>>> client_loop: send disconnect: Broken pipe
```

### 稳定复现步骤 & 代码

```
schema = ['时间', '选手', '赛事名称']
from paddlenlp import Taskflow
ie = Taskflow('information_extraction', schema=schema)
```
完整输出
```
(.venv) [ma-user npu]$python
Python 3.9.17 (main, Jul 31 2023, 14:08:44)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ^[[A^[[A^[[A^C
KeyboardInterrupt
>>> schema = ['时间', '选手', '赛事名称']
>>> from paddlenlp import Taskflow
I0805 01:51:40.542229 24803 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddle_custom_device
I0805 01:51:40.542289 24803 init.cc:145] Try loading custom device libs from: [/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddle_custom_device]
I0805 01:51:41.062960 24803 custom_device.cc:1112] Successed in loading custom runtime in lib: /home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0805 01:51:41.069720 24803 custom_kernel.cc:76] Successed in loading 325 custom kernel(s) from loaded lib(s), will be used like native ones.
I0805 01:51:41.069873 24803 init.cc:157] Finished in LoadCustomDevice with libs_path: [/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddle_custom_device]
I0805 01:51:41.069908 24803 init.cc:245] CustomDevice: npu, visible devices count: 1
>>> ie = Taskflow('information_extraction', schema=schema)
[2023-08-05 01:51:54,462] [    INFO] - Downloading model_state.pdparams from https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_base_v1.1/model_state.pdparams
100%|████████████████████████████████████████████████████████████████████████| 450M/450M [00:16<00:00, 28.3MB/s]
[2023-08-05 01:52:13,069] [    INFO] - Downloading config.json from https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_base/config.json
100%|██████████████████████████████████████████████████████████████████████████| 610/610 [00:00<00:00, 3.34MB/s]
[2023-08-05 01:52:13,251] [    INFO] - Downloading vocab.txt from https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_base/vocab.txt
100%|█████████████████████████████████████████████████████████████████████████| 182k/182k [00:00<00:00, 889kB/s]
[2023-08-05 01:52:13,725] [    INFO] - Downloading special_tokens_map.json from https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_base/special_tokens_map.json
100%|███████████████████████████████████████████████████████████████████████████| 112/112 [00:00<00:00, 556kB/s]
[2023-08-05 01:52:13,911] [    INFO] - Downloading tokenizer_config.json from https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_base/tokenizer_config.json
100%|███████████████████████████████████████████████████████████████████████████| 172/172 [00:00<00:00, 933kB/s]
[2023-08-05 01:52:14,141] [    INFO] - loading configuration file /home/ma-user/.paddlenlp/taskflow/information_extraction/uie-base/config.json
[2023-08-05 01:52:14,143] [    INFO] - Model config ErnieConfig {
  "architectures": [
    "UIE"
  ],
  "attention_probs_dropout_prob": 0.1,
  "dtype": "float32",
  "enable_recompute": false,
  "fuse": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 2048,
  "model_type": "ernie",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "paddlenlp_version": null,
  "pool_act": "tanh",
  "task_id": 0,
  "task_type_vocab_size": 3,
  "type_vocab_size": 4,
  "use_task_id": true,
  "vocab_size": 40000
}

[2023-08-05 01:53:05,058] [    INFO] - All model checkpoint weights were used when initializing UIE.

[2023-08-05 01:53:05,059] [    INFO] - All the weights of UIE were initialized from the model checkpoint at /home/ma-user/.paddlenlp/taskflow/information_extraction/uie-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use UIE for predictions without further training.
[2023-08-05 01:53:05,062] [    INFO] - Converting to the inference model cost a little time.
I0805 01:53:09.457243 24803 program_interpreter.cc:173] New Executor is Running.
[2023-08-05 01:53:15,365] [    INFO] - The inference model save in the path:/home/ma-user/.paddlenlp/taskflow/information_extraction/uie-base/static/inference
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddlenlp/taskflow/taskflow.py", line 837, in __init__
    self.task_instance = task_class(
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddlenlp/taskflow/information_extraction.py", line 536, in __init__
    self._get_inference_model()
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddlenlp/taskflow/task.py", line 366, in _get_inference_model
    self._prepare_static_mode()
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/.venv/lib/python3.9/site-packages/paddlenlp/taskflow/task.py", line 199, in _prepare_static_mode
    self._config.enable_npu(self.kwargs["device_id"])
AttributeError: 'paddle.fluid.libpaddle.AnalysisConfig' object has no attribute 'enable_npu'
```

**Comment by BrightXiaoHan** [comment]
安装develop分支的最新代码解决了此问题
