### ISSUE TITLE
[Question]: ModuleNotFoundError: No module named 'paddle.nn.layer.layers'

### ISSUE THREAD

**Issue by xiaoligang2000** [PaddlePaddle/PaddleNLP#6665]
### 请提出你的问题

环境：
paddle-bfloat                            0.1.7
paddle-custom-npu                        0.0.0
paddle2onnx                              1.0.5
paddlefsl                                1.1.0
paddlenlp                                2.6.0rc0.post0
paddlepaddle                             0.0.0

报错如下：
I0809 16:35:35.324618 80794 init.cc:266] ENV [CUSTOM_DEVICE_ROOT]=/home/ma-user/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle-plugins
I0809 16:35:35.324676 80794 init.cc:150] Try loading custom device libs from: [/home/ma-user/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle-plugins]
I0809 16:35:35.885361 80794 custom_device.cc:1045] Successed in loading custom runtime in lib: /home/ma-user/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle-plugins/libpaddle-custom-npu.so
I0809 16:35:35.898605 80794 custom_kernel.cc:76] Successed in loading 296 custom kernel(s) from loaded lib(s), will be used like native ones.
I0809 16:35:35.898782 80794 init.cc:162] Finished in LoadCustomDevice with libs_path: [/home/ma-user/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle-plugins]
I0809 16:35:35.898820 80794 init.cc:272] CustomDevice: npu, visible devices count: 1
/home/ma-user/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "llamaTest.py", line 6, in <module>
    from paddlenlp.transformers import LlamaForCausalLM, LlamaConfig, LlamaTokenizer
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddlenlp/__init__.py", line 35, in <module>
    from . import (
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddlenlp/data/__init__.py", line 16, in <module>
    from .data_collator import *
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddlenlp/data/data_collator.py", line 26, in <module>
    from ..transformers import BertTokenizer
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py", line 17, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 63, in <module>
    from .generation_utils import GenerationMixin
  File "/home/ma-user/.local/lib/python3.7/site-packages/paddlenlp/transformers/generation_utils.py", line 29, in <module>
    from paddle.nn.layer.layers import in_declarative_mode
ModuleNotFoundError: No module named 'paddle.nn.layer.layers'

**Comment by CarlZhang12** [comment]
same error to me when try to install paddlehub in env, finally find out the version paddlenlp ~=2.6 is incompatible in my env based on paddlepaddle ~2.4,so you can try to reinstall paddlenlp ~=2.5
my env works fine:
env gpu:
paddle-bfloat        0.1.7
paddle2onnx          1.0.9
paddlefsl            1.1.0
paddlehub            2.3.1
paddlenlp            2.5.0
paddlepaddle-gpu     2.4.2.post117

**Comment by mxzgn** [comment]
me too

**Comment by mxzgn** [comment]
更改为paddlenlp 2.5.2版本可以

**Comment by whisky-12** [comment]
更改为paddlenlp 2.5.2版本可以
----------------------------------------->
在OCR中遇到的问题 没想到在NLP中解决了 多谢

**Comment by sunqinbo** [comment]
1 AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20;
由于 paddlespeech 依赖中要求 librosa 版本0.8.1，而且 librosa库使用个了NumPy1.20之前的API导致的

pip install librosa==0.10.1
pip install numpy==1.26.2

2 ModuleNotFoundError: No module named 'paddle.nn.layer.layers' 
由于 paddlepaddle 依赖中paddlenlp 1.26.1 ，降级 paddlenlp 版本到 2.5.2问题得到解决
pip install paddlenlp==2.5.2

**Comment by sunqinbo** [comment]
安装
pip install paddlepaddle==2.5.2 -i https://mirror.baidu.com/pypi/simple
pip install pytest-runner -i https://pypi.tuna.tsinghua.edu.cn/simple 
pip install paddlespeech==1.4.1 -i https://pypi.tuna.tsinghua.edu.cn/simple

修复报错

1 AttributeError: module 'numpy' has no attribute 'complex'.
np.complex was a deprecated alias for the builtin complex. To avoid this error in existing code, use complex by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.complex128 here.
The aliases was originally deprecated in NumPy 1.20;
由于 paddlespeech 依赖中要求 librosa 版本0.8.1，而且 librosa库使用个了NumPy1.20之前的API导致的

pip install librosa==0.10.1
pip install numpy==1.26.2

2 ModuleNotFoundError: No module named 'paddle.nn.layer.layers'
由于 paddlepaddle 依赖中paddlenlp 1.26.1 ，降级 paddlenlp 版本到 2.5.2问题得到解决
pip install paddlenlp==2.5.2

**Comment by sunqinbo** [comment]
安装版本 
(speech_env) dongao@deepin207:/data/works/html/data/source$ pip list|grep paddle
paddle-bfloat               0.1.7
paddle2onnx                 1.1.0
paddleaudio                 1.1.0
paddlefsl                   1.1.0
paddlenlp                   2.5.2
paddlepaddle                2.5.2
paddlesde                   0.2.5
paddleslim                  2.4.1
paddlespeech                1.4.1
paddlespeech-ctcdecoders    0.2.0
paddlespeech-feat           0.1.0

问题处理：
1 AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20;
由于 paddlespeech 依赖中要求 librosa 版本0.8.1，而且 librosa库使用个了NumPy1.20之前的API导致的

pip install librosa==0.10.1

2 报错信息提示：ModuleNotFoundError: No module named 'paddle.nn.layer.layers' 
  报错信息：IndexError: list index out of range
由于 paddlepaddle 	 2.6.1版本 ，降级 paddlenlp 版本到 2.5.2问题得到解决
pip install paddlenlp==2.5.2


运行例子
 paddlespeech text --task punc -v --input "你知道吗大部分时候你都在假装学习你在年初提出了一整面墙的todo list到了九月还没打上几个钩你的书架上陈列着全网最畅销的专业书籍"
[2023-12-20 17:56:18,543] [    INFO] - loading configuration file /home/dongao/.paddlespeech/models/ernie_linear_p7_wudao-punc-zh/1.0/ernie_linear_p7_wudao-punc-zh.tar/ckpt/config.json
[2023-12-20 17:56:18,545] [    INFO] - Model config ErnieConfig {
  "architectures": [
    "ErnieForTokenClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "enable_recompute": false,
  "fuse": false,
  "hidden_act": "relu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5",
    "6": "LABEL_6",
    "7": "LABEL_7"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4,
    "LABEL_5": 5,
    "LABEL_6": 6,
    "LABEL_7": 7
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 513,
  "model_type": "ernie",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "paddlenlp_version": null,
  "pool_act": "tanh",
  "task_id": 0,
  "task_type_vocab_size": 3,
  "type_vocab_size": 2,
  "use_task_id": false,
  "vocab_size": 18000
}

[2023-12-20 17:56:33,740] [    INFO] - All model checkpoint weights were used when initializing ErnieForTokenClassification.

[2023-12-20 17:56:33,740] [    INFO] - All the weights of ErnieForTokenClassification were initialized from the model checkpoint at /home/dongao/.paddlespeech/models/ernie_linear_p7_wudao-punc-zh/1.0/ernie_linear_p7_wudao-punc-zh.tar/ckpt.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ErnieForTokenClassification for predictions without further training.
[2023-12-20 17:56:33,761] [    INFO] - Already cached /home/dongao/.paddlenlp/models/ernie-1.0/vocab.txt
[2023-12-20 17:56:33,776] [    INFO] - tokenizer config file saved in /home/dongao/.paddlenlp/models/ernie-1.0/tokenizer_config.json
[2023-12-20 17:56:33,777] [    INFO] - Special tokens file saved in /home/dongao/.paddlenlp/models/ernie-1.0/special_tokens_map.json
你知道吗？大部分时候，你都在假装学习。你在年初提出了一整面墙的todolist，到了九月，还没打上几个钩。你的书架上，陈列着全网最畅销的专业书籍。
