### ISSUE TITLE
[Question]: 报错：ModuleNotFoundError: No module named 'paddle.fluid.layers.utils'，可能是paddlepaddle-gpu和 paddlenlp版本不适配

### ISSUE THREAD

**Issue by MooTong123** [PaddlePaddle/PaddleNLP#6677]
### 请提出你的问题

运行paddlenlp2.5的文本分类训练代码时，报错：
```
Traceback (most recent call last):
  File "/home/sda/app/nlp/text_classification_oneLabel/train.py", line 17, in <module>
    from paddlenlp.data import DataCollatorWithPadding
  File "/data/miniconda3/envs/SDA_automodel_gpu/lib/python3.8/site-packages/paddlenlp/__init__.py", line 29, in <module>
    from . import (
  File "/data/miniconda3/envs/SDA_automodel_gpu/lib/python3.8/site-packages/paddlenlp/data/__init__.py", line 16, in <module>
    from .data_collator import *
  File "/data/miniconda3/envs/SDA_automodel_gpu/lib/python3.8/site-packages/paddlenlp/data/data_collator.py", line 23, in <module>
    from ..transformers.tokenizer_utils_base import BatchEncoding, PretrainedTokenizerBase, PaddingStrategy
  File "/data/miniconda3/envs/SDA_automodel_gpu/lib/python3.8/site-packages/paddlenlp/transformers/__init__.py", line 17, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "/data/miniconda3/envs/SDA_automodel_gpu/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 66, in <module>
    from .generation_utils import GenerationMixin
  File "/data/miniconda3/envs/SDA_automodel_gpu/lib/python3.8/site-packages/paddlenlp/transformers/generation_utils.py", line 24, in <module>
    from paddle.fluid.layers.utils import map_structure
ModuleNotFoundError: No module named 'paddle.fluid.layers.utils'
```
我猜测的原因可能是paddlepaddle-gpu的版本太高？和paddlenlp不适配？所以paddlepaddle-gpu的版本应该调整到多少？

我的安装命令是根据官网进行安装的：
```
python3 -m pip install paddlepaddle-gpu==2.5.1.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```

版本：
paddlepaddle-gpu=2.5.1.post117
paddlenlp=2.5.0

**Comment by JunnYu** [comment]
paddle 2.4.2  paddlenlp 2.5.0
paddle 2.5.1  paddlenlp develop

**Comment by JasonChenJC** [comment]
> paddle 2.4.2 paddlenlp 2.5.0 paddle 2.5.1 paddlenlp develop

paddle 2.4.1, paddlenlp应该是多少？
