### ISSUE TITLE
[Bug]: ernie预训练报错

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#6735]
### 软件环境

```Markdown
- paddlepaddle:2.5.1
- paddlepaddle-gpu: 2.5.1
- paddlenlp: develop
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "run_pretrain.py", line 760, in <module>
    do_train(config)
  File "run_pretrain.py", line 627, in do_train
    log_info_dict[k] = all_gather(v) / args.logging_freq / args.accumulate_steps
  File "run_pretrain.py", line 198, in all_gather
    concat = paddle.concat(ret, axis=0)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 1121, in concat
    return _C_ops.concat(input, axis)
ValueError: (InvalidArgument) The axis is expected to be in range of [0, 0), but got 0
  [Hint: Expected axis >= -rank && axis < rank == true, but received axis >= -rank && axis < rank:0 != true:1.] (at ../paddle/phi/infermeta/multiary.cc:961)
```

### 稳定复现步骤 & 代码

训练脚本
python -u  -m paddle.distributed.launch     --gpus "0,1"     --log_dir "output/ernie-3.0-mini-zh/log"     run_pretrain.py     --model_type "ernie"     --model_name_or_path "./ernie-3.0-mini-zh"     --tokenizer_name_or_path "./ernie-3.0-mini-zh"     --input_dir "./train_data"     --output_dir "output/ernie-3.0-mini-zh"     --split 949,50,1     --max_seq_len 512     --micro_batch_size 16     --use_amp true     --fp16_opt_level O2     --max_lr 0.0001     --min_lr 0.00001     --max_steps 1000000     --save_steps 50000     --checkpoint_steps 5000     --decay_steps 990000     --weight_decay 0.01     --warmup_rate 0.01     --grad_clip 1.0     --logging_freq 20     --num_workers 2     --eval_freq 1000     --device "gpu"     --share_folder false --use_recompute false

**Comment by w5688414** [comment]
paddle和paddlenlp develop版本都升级到最新版本试试
