### ISSUE TITLE
[Question]: No module named 'paddle.nn.layer.layers'

### ISSUE THREAD

**Issue by yunqi777** [PaddlePaddle/PaddleNLP#6847]
### 请提出你的问题

请问如何解决这个问题？

**Comment by papersuper** [comment]
+1

**Comment by sijunhe** [comment]
请给出更多报错和复现的信息

**Comment by papersuper** [comment]
您好，我是在运行  hub install deploy/hubserving/kie_ser/   时出现的
paddlehub==2.1.0
paddlepaddle-gpu==2.3.2
cuda=10.1



Traceback (most recent call last):
  File "/home/dongguanghui/anaconda3/bin/hub", line 5, in <module>
    from paddlehub.commands.utils import execute
  File "/home/dongguanghui/anaconda3/lib/python3.10/site-packages/paddlehub/__init__.py", line 31, in <module>
    from paddlehub import datasets
  File "/home/dongguanghui/anaconda3/lib/python3.10/site-packages/paddlehub/datasets/__init__.py", line 16, in <module>
    from paddlehub.datasets.chnsenticorp import ChnSentiCorp
  File "/home/dongguanghui/anaconda3/lib/python3.10/site-packages/paddlehub/datasets/chnsenticorp.py", line 19, in <module>
    from paddlehub.datasets.base_nlp_dataset import TextClassificationDataset
  File "/home/dongguanghui/anaconda3/lib/python3.10/site-packages/paddlehub/datasets/base_nlp_dataset.py", line 21, in <module>
    import paddlenlp
  File "/home/dongguanghui/anaconda3/lib/python3.10/site-packages/paddlenlp/__init__.py", line 35, in <module>
    from . import (
  File "/home/dongguanghui/anaconda3/lib/python3.10/site-packages/paddlenlp/data/__init__.py", line 16, in <module>
    from .data_collator import *
  File "/home/dongguanghui/anaconda3/lib/python3.10/site-packages/paddlenlp/data/data_collator.py", line 26, in <module>
    from ..transformers import BertTokenizer
  File "/home/dongguanghui/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/__init__.py", line 17, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "/home/dongguanghui/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/model_utils.py", line 63, in <module>
    from .generation_utils import GenerationMixin
  File "/home/dongguanghui/anaconda3/lib/python3.10/site-packages/paddlenlp/transformers/generation_utils.py", line 29, in <module>
    from paddle.nn.layer.layers import in_declarative_mode
ModuleNotFoundError: No module named 'paddle.nn.layer.layers'

**Comment by sijunhe** [comment]
升级paddlepaddle-gpu版本到最新吧

**Comment by papersuper** [comment]
Successfully installed httpcore-0.17.3 paddlepaddle-gpu-2.5.1 protobuf-4.24.2
 运行hub install deploy/hubserving/kie_ser/
还是报这个错

**Comment by papersuper** [comment]
我电脑和服务器上都这样，请问可以加一下联系方式吗

**Comment by Jacoo520** [comment]
＋1
