### ISSUE TITLE
unimo-text的“FastGeneration加速及模型静态图导出”报错

### ISSUE THREAD

**Issue by 178255733** [PaddlePaddle/PaddleNLP#6848]
### 请提出你的问题

我在生成模型静态图时，遇到如下报错，实在找不到报错原因，过来请教大家，先行感谢。
系统：win10，显存12G

报错如下：
(nlp) C:\coding_projects\NLP\unimo-text>python export_model.py --model_name_or_path unimo-text-1.0-summary --decoding_strategy beam_search --inference_model_dir ./inference_model --max_out_len 30
C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Namespace(decoding_strategy='beam_search', diversity_rate=0.0, inference_model_dir='./inference_model', max_out_len=30, min_out_len=1, model_name_or_path='unimo-text-1.0-summary', num_beams=4, num_return_sequence=1, num_return_sequences=1, temperature=1.0, topk=4, topp=1.0, use_fp16_decoding=False)
[2023-08-29 10:00:48,483] [    INFO] - Already cached C:\Users\Administrator\.paddlenlp\models\unimo-text-1.0-summary\model_state.pdparams
[2023-08-29 10:00:48,484] [    INFO] - Loading weights file model_state.pdparams from cache at C:\Users\Administrator\.paddlenlp\models\unimo-text-1.0-summary\model_state.pdparams
[2023-08-29 10:00:48,677] [    INFO] - Loaded weights file from disk, setting weights to model.
W0829 10:00:48.678098  4020 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 11.7
W0829 10:00:48.681099  4020 gpu_resources.cc:149] device: 0, cuDNN Version: 8.8.
[2023-08-29 10:00:50,058] [    INFO] - All model checkpoint weights were used when initializing UNIMOLMHeadModel.

[2023-08-29 10:00:50,058] [    INFO] - All the weights of UNIMOLMHeadModel were initialized from the model checkpoint at unimo-text-1.0-summary.
If your task is similar to the task the model of the checkpoint was trained on, you can already use UNIMOLMHeadModel for predictions without further training.
[2023-08-29 10:00:50,079] [    INFO] - Already cached C:\Users\Administrator\.paddlenlp\models\unimo-text-1.0-summary\unimo-text-1.0-vocab.txt
[2023-08-29 10:00:50,096] [    INFO] - tokenizer config file saved in C:\Users\Administrator\.paddlenlp\models\unimo-text-1.0-summary\tokenizer_config.json
[2023-08-29 10:00:50,097] [    INFO] - Special tokens file saved in C:\Users\Administrator\.paddlenlp\models\unimo-text-1.0-summary\special_tokens_map.json
2023-08-29 10:00:50,121 - INFO - Using Python interpreter: C:\ProgramData\Anaconda3\envs\nlp\python.exe, version: Python 3.8.17
Compiling user custom op, it will cost a few seconds.....
2023-08-29 10:00:50,121 - INFO - execute command: cd /d C:\Users\Administrator\.paddlenlp\extensions\8c3ce701cffcf33cba6b919c37db0670\FastGeneration && C:\ProgramData\Anaconda3\envs\nlp\python.exe FastGeneration_setup.py build
running build
running build_ext
[2023-08-29 10:00:52,505] [ WARNING] - FastGeneration is not available due to build errors.
Traceback (most recent call last):
  File "FastGeneration_setup.py", line 4, in <module>
    setup(
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
    self.run_command(cmd_name)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddlenlp\ops\ext_utils.py", line 238, in build_extensions
    ext.build_with_command(self)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddlenlp\ops\ext_utils.py", line 216, in build_with_command
    raise e
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddlenlp\ops\ext_utils.py", line 205, in build_with_command
    super(FasterTransformerExtension, self).build_with_command(ext_builder)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddlenlp\ops\ext_utils.py", line 131, in build_with_command
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1374, in run_cmd
    return subprocess.check_call(
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /d C:\Users\Administrator\.paddlenlp\extensions\8c3ce701cffcf33cba6b919c37db0670\FastGeneration && C:\ProgramData\Anaconda3\envs\nlp\python.exe FastGeneration_setup.py build' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_model.py", line 114, in <module>
    do_predict(args)
  File "export_model.py", line 73, in do_predict
    unimo_text = FasterUNIMOText(model=model, use_fp16_decoding=args.use_fp16_decoding, trans_out=True)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddlenlp\transformers\utils.py", line 249, in __impl__
    init_func(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddlenlp\ops\fast_transformer\transformer\fast_transformer.py", line 1126, in __init__
    self.decoding = InferUnifiedDecoding(
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddlenlp\ops\fast_transformer\transformer\decoding.py", line 3182, in __init__
    load(
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddlenlp\ops\ext_utils.py", line 52, in _impl
    func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddlenlp\ops\ext_utils.py", line 347, in load
    _jit_compile(file_path, verbose)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1339, in _jit_compile
    run_cmd(compile_cmd, verbose)
  File "C:\ProgramData\Anaconda3\envs\nlp\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1381, in run_cmd
    raise RuntimeError(f"Failed to run command: {compile}, errors: {error}")
RuntimeError: Failed to run command: <built-in function compile>, errors: Command 'cd /d C:\Users\Administrator\.paddlenlp\extensions\8c3ce701cffcf33cba6b919c37db0670\FastGeneration && C:\ProgramData\Anaconda3\envs\nlp\python.exe FastGeneration_setup.py build' returned non-zero exit status 1.

**Comment by DrownFish19** [comment]
不支持win的msvc编译器，只能换linux。
https://github.com/PaddlePaddle/PaddleNLP/blob/d6815b38de11a6e67cdb6902cd9988d98fa6b48b/paddlenlp/ops/ext_utils.py#L130-L131

当前更换linux也会出现报错，已经提交修复pr，暂时未merge。参考#6812
