### ISSUE TITLE
[Bug]: GPT-3 model training failure with sharding level = stage3

### ISSUE THREAD

**Issue by Tom-Zheng** [PaddlePaddle/PaddleNLP#6860]
### 软件环境

```Markdown
- paddlepaddle: - 
- paddlepaddle-gpu: 2.5.0
- paddlenlp: 2.6.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
GPT-3 model training will fail with sharding level = stage3

Error message: 

RuntimeError: (PreconditionNotMet) Tensor not initialized yet when DenseTensor::place() is called.
  [Hint: holder_ should not be null.] (at /opt/paddle/paddle/paddle/phi/core/dense_tensor_impl.cc:58)
```

### 稳定复现步骤 & 代码

Command:

```bash
#!/bin/bash

set -ex

task_name="gpt3_debug"
log_dir="log"
rm -rf $log_dir

python -u  -m paddle.distributed.launch \
    --gpus "0,1" \
    --log_dir ${log_dir} \
    run_pretrain.py \
    --model_type "gpt" \
    --model_name_or_path gpt2-medium-en \
    --tokenizer_name_or_path gpt2-medium-en \
    --input_dir "<path to dataset>" \
    --output_dir "output/$task_name" \
    --split 949,50,1 \
    --max_seq_length 512 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --tensor_parallel_degree 1 \
    --pipeline_parallel_degree 1 \
    --fuse_attention_qkv 1 \
    --use_flash_attention 0 \
    --bf16  \
    --fp16_opt_level "O2"  \
    --scale_loss 1024 \
    --learning_rate 0.00001 \
    --min_learning_rate 0.000005 \
    --max_steps 10000 \
    --save_steps 5000 \
    --weight_decay 0.01 \
    --warmup_ratio 0.01 \
    --max_grad_norm 1.0 \
    --logging_steps 200 \
    --dataloader_num_workers 1 \
    --sharding "stage3" \
    --eval_steps 1000 \
    --report_to "visualdl" \
    --disable_tqdm true \
    --recompute 0 \
    --gradient_accumulation_steps 1 \
    --do_train \
    --do_eval \
    --device "gpu"
```

Full error log:

```
Traceback (most recent call last):
  File "/home/projects/PaddleNLP/llm/gpt-3/run_pretrain.py", line 466, in <module>
    main()
  File "/home/projects/PaddleNLP/llm/gpt-3/run_pretrain.py", line 453, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/projects/PaddleNLP/paddlenlp/trainer/trainer.py", line 759, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/home/projects/PaddleNLP/paddlenlp/trainer/trainer.py", line 1648, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/projects/PaddleNLP/paddlenlp/trainer/trainer.py", line 1601, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_stage3.py", line 296, in forward
    fw = self._layer(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/projects/PaddleNLP/llm/gpt-3/modeling.py", line 857, in forward
    logits = parallel_matmul(hidden_states, self.gpt.embeddings.word_embeddings.weight, tensor_parallel_output)
  File "/home/projects/PaddleNLP/llm/gpt-3/modeling.py", line 82, in parallel_matmul
    logits = paddle.matmul(x, y, transpose_y=True)
  File "/usr/local/lib/python3.10/dist-packages/paddle/tensor/linalg.py", line 234, in matmul
    return _C_ops.matmul(x, y, transpose_x, transpose_y)
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when DenseTensor::place() is called.
  [Hint: holder_ should not be null.] (at /opt/paddle/paddle/paddle/phi/core/dense_tensor_impl.cc:58)
```

**Comment by DrownFish19** [comment]
当前gpt-3使用的modeling文件已经合入paddlenlp, #6858 修复了stage3的问题。

**Comment by Tom-Zheng** [comment]
@DrownFish19 但`llm/gpt-3/modeling.py` 还是没有修正?

**Comment by FeixLiu** [comment]
develop的paddle+develop的paddlenlp应该已经修复了这个问题了。
<img width="1594" alt="340c593cbf6eef8784001dc31bfaffae" src="https://github.com/PaddlePaddle/PaddleNLP/assets/25279174/0108c237-f60d-4e09-82ee-32a4972a8e3a">

**Comment by DrownFish19** [comment]
> @DrownFish19 但`llm/gpt-3/modeling.py` 还是没有修正?

当前llm/gpt-3/modeling 已经合入paddlenlp/transformers/gpt/modeling，前者已经删除，后续gpt模型初始化全部调用后者。
