### ISSUE TITLE
[Bug]: FSDP has poor compatibility with DP/TP/PP

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/PaddleNLP#6938]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.5.0
- paddlenlp: 2.6.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

I got 3 different errors with different parallel configs.

- Error1: (FSDP>1 PP>1 stage2)
```Markdown
Traceback (most recent call last):
  File "/workspace/paddlenlp/llm/gpt-3/run_pretrain.py", line 527, in <module>
    main()
  File "/workspace/paddlenlp/llm/gpt-3/run_pretrain.py", line 354, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/workspace/paddlenlp/paddlenlp/trainer/argparser.py", line 223, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 87, in __init__
  File "/workspace/paddlenlp/paddlenlp/trainer/training_args.py", line 817, in __post_init__
    raise ValueError(
ValueError: pipeline parallel is not compatible for sharding stage2 or stage3, please using sharding stage1
```

- Error2:  (FSDP>1  DP>1  stage1)
```
Traceback (most recent call last):
  File "/workspace/paddlenlp/llm/gpt-3/run_pretrain.py", line 527, in <module>
    main()
  File "/workspace/paddlenlp/llm/gpt-3/run_pretrain.py", line 354, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/workspace/paddlenlp/paddlenlp/trainer/argparser.py", line 223, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 87, in __init__
  File "/workspace/paddlenlp/paddlenlp/trainer/training_args.py", line 810, in __post_init__
    assert self.data_parallel_degree == 1, "sharding stage1 can not coexist with dp for now"
AssertionError: sharding stage1 can not coexist with dp for now
```

- Error 3: (FSDP>1 PP>1 DP=1 stage1)
```
Traceback (most recent call last):
  File "/workspace/paddlenlp/llm/gpt-3/run_pretrain.py", line 527, in <module>
    main()
  File "/workspace/paddlenlp/llm/gpt-3/run_pretrain.py", line 514, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/workspace/paddlenlp/paddlenlp/trainer/trainer.py", line 817, in train
    self.optimizer._inner_opt.reduce_gradients(list(parameters_list), self.optimizer._hcg)
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py", line 213, in __getattr__
    return getattr(self._inner_optimizer, item)
AttributeError: 'AdamW' object has no attribute 'reduce_gradients'
```
```


### 稳定复现步骤 & 代码

Run llm/gpt-3 pretraining scripts on 8xA100 with the following parallel config: 
-  `--sharding_parallel_degree 2  --tensor_parallel_degree 2   --sharding stage2`
-  `--sharding_parallel_degree 2  --tensor_parallel_degree 1   --pipeline_parallel_degree 1 --sharding stage1`
-  `--sharding_parallel_degree 4  --tensor_parallel_degree 1   --pipeline_parallel_degree 2`

**Comment by Wong4j** [comment]
第三个问题在paddle develop中已经修复。主要是前两个问题，导致我们现在可测试的parallel组合很少。
