### ISSUE TITLE
[Bug]: GPU导出facebook/llama-7b模型出错

### ISSUE THREAD

**Issue by zhjc** [PaddlePaddle/PaddleNLP#6952]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: develop分支 12301bc5337fa3bc2d07050d240fbac3689fa9ce
- paddlenlp: develop分支 a6e3ec7c0e21a9df1d00be26a378067c628ed569
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "export_model.py", line 64, in <module>
    main()
  File "export_model.py", line 56, in main
    get_infer_model_path(export_args.output_path, predictor_args.model_prefix), {"dtype": predictor_args.dtype}
  File "/xxx/PaddleNLP/paddlenlp/transformers/generation/utils.py", line 1308, in to_static
    paddle.jit.save(model, path)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/api.py", line 795, in wrapper
    func(layer, path, input_spec, **configs)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/api.py", line 1137, in save
    inner_input_spec, is_prim_infer=is_prim_infer
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 973, in concrete_program_specify_input_spec
    is_prim_infer=is_prim_infer,
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 835, in get_concrete_program
    args, kwargs
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/function_spec.py", line 90, in unified_args_and_kwargs
    raise ValueError(error_msg)
ValueError: The decorated function `generate` requires 4 arguments: ['input_ids', 'generation_config', 'stopping_criteria', 'streamer'], but received 26 with (InputSpec(shape=(-1, -1), dtype=paddle.int64, name=None, stop_gradient=False), InputSpec(shape=(-1, -1), dtype=paddle.int64, name=None, stop_gradient=False), None, InputSpec(shape=(1,), dtype=paddle.int64, name=None, stop_gradient=False), 0, 'sampling', InputSpec(shape=(1,), dtype=paddle.float32, name=None, stop_gradient=False), 0, InputSpec(shape=(1,), dtype=paddle.float32, name=None, stop_gradient=False), 1, 1, 1, 0.0, False, 0, 0, 0, None, None, None, None, 1, 0.0, True, False, False).
```

### 稳定复现步骤 & 代码

编译安装Paddle-GPU：
```
cmake -DWITH_DISTRIBUTE=ON -DPY_VERSION=3.7 -DWITH_GPU=ON -DWITH_PSCORE=ON ..
```

导出命令：
```
cd llm
python export_model.py     --model_name_or_path facebook/llama-7b     --output_path ./inference     --dtype float16
```

**Comment by MARD1NO** [comment]
> 

您好这个动态图散op确实存在问题，对于推理我们优化过模型导出需要加 --inference_model

```shell
python export_model.py \
    --model_name_or_path xxxxx \
    --output_path ./inference \
    --max_batch_size 1 \
    --dtype float16 \
    --inference_model
```

**Comment by yangjq0630** [comment]
您好，我也遇到同样的问题，模型使用的是chatglm，请问有解决办法吗？
有尝试使用paddle Nightly build，最终效果是一样的，似乎并没有修复。

**Comment by linan142857** [comment]
遇到同样的问题，什么时候能够修复
