### ISSUE TITLE
[Question]: llama动转静失败

### ISSUE THREAD

**Issue by zhaohaixu** [PaddlePaddle/PaddleNLP#7107]
我尝试使用[export_model.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/export_model.py)来对我自己预训练的llama的checkpoint进行动态图到静态图的转换，目前碰到了这个错误：
![17d44bb76b4afa3fc54023725cae3c76](https://github.com/PaddlePaddle/PaddleNLP/assets/49297029/53a2701d-a28e-4f16-92a2-7e779c68f0e5)
分析后发现在[utils.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/generation/utils.py)中self.generate的参数为：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/49297029/dc6f7867-aaaf-4ae2-97ee-3b5fec0b26a7)
而在传入input_spec时却是：
`
        input_spec = [
            paddle.static.InputSpec(shape=[None, None], dtype="int64"),  # input_ids
            paddle.static.InputSpec(shape=[None, None], dtype="int64"),  # attention_mask
            None,  # position_ids
            paddle.static.InputSpec(shape=[1], dtype="int64"),  # max_length
            0,  # min_length
            "sampling",  # decode_strategy
            temperature,  # temperature
            top_k_spec,  # top_k
            top_p_spec,  # top_p
            1,  # repetition_penalty
            # num_beams
            1,
            # num_beam_groups
            1,
            # length_penalty
            0.0,
            # early_stopping
            False,
            # bos_token_id
            config.get("bos_token_id", 0),
            # eos_token_id
            config.get("eos_token_id", 0),
            # pad_token_id
            config.get("pad_token_id", 0),
            # decoder_start_token_id
            None,
            # forced_bos_token_id
            None,
            # forced_eos_token_id
            None,
            # no_repeat_ngram_size
            None,
            # num_return_sequences
            1,
            # diversity_rate
            0.0,
            # use_cache
            True,
            # use_fast=False,
            False,
            # use_fp16_decoding=False,
            False,
        ]
`
这是否意味着任意动转静过程都会涉及到该传参错误呢？
或者是否是我的checkpoint中的model_state生成有误呢？

**Comment by wj-Mcat** [comment]
你更新一下本地 paddlenlp 最新的版本，这个已经在上周的 pr https://github.com/PaddlePaddle/PaddleNLP/pull/6971 中解决了的。

**Comment by zhaohaixu** [comment]
@wj-Mcat 感谢您的指导，更新后该问题修复，但在模型保存时碰到了如下的错误：

/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/api.py:989: UserWarning: What you save is a function, and `jit.save` will generate the name of the model file according to `path` you specify. When loading these files with `jit.load`, you get a `TranslatedLayer` whose inference result is the same as the inference result of the function you saved.
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'dtype' in fill_constant only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/framework.py:2938: UserWarning: The Attr(force_cpu) of Op(fill_constant) will be deprecated in the future, please use 'device_guard' instead. 'device_guard' has higher priority when they are used at the same time.
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/framework.py:2938: UserWarning: The Attr(force_cpu) of Op(fill_constant) will be deprecated in the future, please use 'device_guard' instead. 'device_guard' has higher priority when they are used at the same time.
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/tensor/creation.py:2229: UserWarning: paddle.assign doesn't support float64 input now due to current platform protobuf data limitation, we convert it to float32
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/static/nn/control_flow.py:1427: UserWarning: the input shapes of select_input should have the same rank, but get (1,), (-1, 1, -1, -1)
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'dtype' in cast only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'x' in linear only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'dtype' in linear only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'x' in reshape only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'input' in shape only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'dtype' in cast only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'input' in squeeze only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'x' in transpose only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'x' in gather_np only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'input' in unsqueeze only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'input' in shape only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'input[0]' in concat only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'input[1]' in concat only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'input' in shape only support float16 in GPU now. 
  warnings.warn(
/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/data_feeder.py:202: UserWarning: The data type of 'input' in shape only support float16 in GPU now. 
  warnings.warn(
Traceback (most recent call last):
  File "export_model.py", line 96, in <module>
    main()
  File "export_model.py", line 84, in main
    predictor.model.to_static(
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/generation/utils.py", line 1255, in to_static
    paddle.jit.save(model, path)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/api.py", line 795, in wrapper
    func(layer, path, input_spec, **configs)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/api.py", line 1136, in save
    static_func.concrete_program_specify_input_spec(
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/program_translator.py", line 969, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/program_translator.py", line 859, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/program_translator.py", line 1452, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/program_translator.py", line 1396, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/program_translator.py", line 1227, in from_func_spec
    error_data.raise_new_exception()
  File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/error.py", line 452, in raise_new_exception
    raise new_exception from None
ValueError: In transformed code:

    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/generation/utils.py", line 1364, in sample_d2s
        outputs = _forward_(**model_kwargs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/generation/utils.py", line 1309, in _forward_
        return self(**model_inputs, **immutable)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/transformers/llama/modeling.py", line 1475, in forward
        outputs = self.llama(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/transformers/llama/modeling.py", line 1251, in forward
        for idx, (decoder_layer) in enumerate(self.layers):
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/transformers/llama/modeling.py", line 1257, in forward
        if (
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/transformers/llama/modeling.py", line 1274, in forward
        layer_outputs = decoder_layer(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/transformers/llama/modeling.py", line 872, in forward
        if (
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/transformers/llama/modeling.py", line 890, in forward
        outputs = self.self_attn(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/transformers/llama/modeling.py", line 771, in forward
        if (
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/transformers/llama/modeling.py", line 790, in forward
        outputs = scaled_dot_product_attention(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/transformers/llama/modeling.py", line 190, in scaled_dot_product_attention
        if config.use_flash_attention and flash_attention:
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/transformers/llama/modeling.py", line 198, in scaled_dot_product_attention
            raise ValueError("Flash Attention does not support ALiBi yet")

        attn_output, attn_weights = flash_attention(
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            query_states,
            key_states,

    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/functional/flash_attention.py", line 231, in flash_attention
        helper.append_op(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/layer_helper.py", line 45, in append_op
        return self.main_program.current_block().append_op(*args, **kwargs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/framework.py", line 4368, in append_op
        op = Operator(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/framework.py", line 3113, in __init__
        self.desc.check_attrs()

    ValueError: (InvalidArgument) Found Attribute('causal') with type(Variable), but it doesn't support phi::DenseTensor type.
  [Hint: Expected attr_->support_tensor() == true, but received attr_->support_tensor():0 != true:1.] (at ../paddle/fluid/framework/attribute_checker.h:251)

该动转静过程使用了自己预训练生成的200步checkpoint，预训练脚本参照[run_pretrain.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/llama/run_pretrain.py).

**Comment by tiandou-tangdou** [comment]
@wj-Mcat 遇到相同问题
