### ISSUE TITLE
[Bug]: ValueError: substring not found

### ISSUE THREAD

**Issue by psc0606** [PaddlePaddle/PaddleNLP#7128]
### 软件环境

```Markdown
- paddle-bfloat:            0.1.7
- paddle2onnx:              1.0.9
- paddlefsl:                1.1.0
- paddlenlp:                2.6.1
- paddlepaddle:             2.5.1
- paddlepaddle-gpu:         2.5.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/taskflow/taskflow.py", line 817, in __call__
    results = self.task_instance(inputs, **kwargs)
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/taskflow/task.py", line 527, in __call__
    outputs = self._run_model(inputs, **kwargs)
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/taskflow/information_extraction.py", line 1068, in _run_model
    results = self._multi_stage_predict(_inputs)
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/taskflow/information_extraction.py", line 1166, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/taskflow/information_extraction.py", line 947, in _single_stage_predict
    infer_ds = load_dataset(reader, inputs=short_inputs, lazy=self._lazy_load)
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/datasets/dataset.py", line 191, in load_dataset
    return reader_instance.read(**custom_kwargs)
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/datasets/dataset.py", line 781, in read
    return MapDataset(list(examples))
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/taskflow/information_extraction.py", line 728, in text_reader
    encoded_inputs = self._tokenizer(
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2210, in __call__
    return self.batch_encode(
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2494, in batch_encode
    return self._batch_encode_plus(
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 1084, in _batch_encode_plus
    batch_outputs = self._batch_prepare_for_model(
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 1219, in _batch_prepare_for_model
    encoded_inputs = self.prepare_for_model(
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2865, in prepare_for_model
    token_pair_offset_mapping = self.get_offset_mapping(text_pair) if text_pair is not None else None
  File "/home/deploy/anaconda3/envs/hanlp/lib/python3.10/site-packages/paddlenlp/transformers/ernie_m/tokenizer.py", line 145, in get_offset_mapping
    start = text[offset:].index(token) + offset
ValueError: substring not found

我发现一些相关的issue，但无法解决这个case:
* https://github.com/PaddlePaddle/PaddleNLP/issues/2854
* https://github.com/PaddlePaddle/PaddleNLP/issues/4113
* https://github.com/PaddlePaddle/PaddleNLP/issues/3959
```

### 稳定复现步骤 & 代码
使用的模型为中英文 uie-m-base，自己加了20条语料微调的。
`
from paddlenlp import Taskflow
schema = ['作品名', '角色', '作者', '风格']
my_ie = Taskflow("information_extraction", schema=schema, task_path='./PaddleNLP/model_zoo/uie/checkpoint/model_best')
my_ie("想自己画漫画ｸﾞｯ!(๑•̀ㅂ•́)و✧,最后一张乱入  ᶘ ᵒᴥᵒᶅ ")
`

**Comment by huanghao128** [comment]
“ｸﾞｯ!(๑•̀ㅂ•́)و✧”，“  ᶘ ᵒᴥᵒᶅ ”这两段文本有不在模型vocab.txt中的字符，或者读入时字符编码有问题，直接过滤就可以了吧

**Comment by psc0606** [comment]
目前过滤掉就没问题了

**Comment by mfxss** [comment]
这个问题也没解决呀
