### ISSUE TITLE
[Bug]: 在llm中使用float16精度推理出现nan，导致multinomial报错。

### ISSUE THREAD

**Issue by GuPeijian** [PaddlePaddle/PaddleNLP#7132]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.5
- paddlenlp: 2.6.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
在llm中使用float16精度推理出现nan，导致multinomial报错，使用float32精度则不会出现。同时paddle处理nan的方法nan_to_num在float16下不适用。
```

### 稳定复现步骤 & 代码

目前是个别example出现。

**Comment by zhaohaixu** [comment]
我也在llama静态图推理时碰到了相同的错误，运行脚本为：python predictor.py --model_name_or_path ./inference_gpu/inference/ --batch_size 1 --dtype "float16" --mode "static"
```
Traceback (most recent call last):
  File "predictor.py", line 888, in <module>
    predict()
  File "predictor.py", line 832, in predict
    outputs = predictor.predict(batch_source_text)
  File "predictor.py", line 180, in predict
    predictions = self._infer(tokenized_source)
  File "predictor.py", line 283, in _infer
    self.predictor.run()
ValueError: In user code:

    File "export_model.py", line 96, in <module>
      main()
    File "export_model.py", line 84, in main
      predictor.model.to_static(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/generation/utils.py", line 1254, in to_static
      paddle.jit.save(model, path)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/api.py", line 795, in wrapper
      func(layer, path, input_spec, **configs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/dygraph/base.py", line 75, in __impl__
      return func(*args, **kwargs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/api.py", line 1136, in save
      static_func.concrete_program_specify_input_spec(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/program_translator.py", line 969, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/program_translator.py", line 859, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/program_translator.py", line 1452, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/program_translator.py", line 1396, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/dygraph/base.py", line 75, in __impl__
      return func(*args, **kwargs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/program_translator.py", line 1220, in from_func_spec
      outputs = static_func(*inputs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/generation/utils.py", line 1385, in sample_d2s
      if hasattr(paddle.framework, "_no_check_dy2st_diff"):
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/convert_operators.py", line 371, in convert_ifelse
      out = _run_py_ifelse(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/convert_operators.py", line 453, in _run_py_ifelse
      py_outs = true_fn() if pred else false_fn()
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/generation/utils.py", line 1390, in sample_d2s
      while cur_len < max_new_tokens and paddle.any(unfinished_flag):
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/convert_operators.py", line 134, in convert_while_loop
      _run_paddle_while(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/convert_operators.py", line 190, in _run_paddle_while
      loop_vars = while_loop(new_cond_fn, new_body_fn, loop_vars)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/static/nn/control_flow.py", line 694, in while_loop
      output_vars = body(*new_loop_vars)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/convert_operators.py", line 170, in new_body_fn
      body()
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/generation/utils.py", line 1391, in sample_d2s
      input_ids, scores, unfinished_flag, model_kwargs = _post_process_(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/generation/utils.py", line 1331, in _post_process_
      if use_top_p:
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/convert_operators.py", line 371, in convert_ifelse
      out = _run_py_ifelse(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/convert_operators.py", line 453, in _run_py_ifelse
      py_outs = true_fn() if pred else false_fn()
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/generation/utils.py", line 1333, in _post_process_
      if is_paddlenlp_ops_available():
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/convert_operators.py", line 371, in convert_ifelse
      out = _run_py_ifelse(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/jit/dy2static/convert_operators.py", line 453, in _run_py_ifelse
      py_outs = true_fn() if pred else false_fn()
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddlenlp-2.6.0.post0-py3.8.egg/paddlenlp/generation/utils.py", line 1338, in _post_process_
      next_tokens = paddle.multinomial(probs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/tensor/random.py", line 197, in multinomial
      helper.append_op(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/framework.py", line 4368, in append_op
      op = Operator(
    File "/data/user/work/miniconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/base/framework.py", line 2906, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The input of multinomial distribution should be >= 0, but got nan.
      [Hint: Expected prob_value >= 0.0, but received prob_value:nan < 0.0:0.] (at /root/paddle/paddle/phi/kernels/funcs/multinomial_functor.h:47)
      [operator < multinomial > error]
```
llama静态模型配置配置如下：
```
{
  "alibi": false,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "fuse_attention_ffn": false,
  "fuse_attention_qkv": false,
  "fuse_sequence_parallel_allreduce": false,
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 1024,
  "model_type": "llama",
  "no_recompute_layers": null,
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "paddlenlp_version": null,
  "pp_recompute_interval": 1,
  "recompute_granularity": "full",
  "rms_norm_eps": 1e-06,
  "rope_fusion_level": null,
  "rope_scaling_factor": 1.0,
  "rope_scaling_type": null,
  "seq_length": 2048,
  "sequence_parallel": false,
  "tensor_parallel_degree": 1,
  "tensor_parallel_output": false,
  "tie_word_embeddings": false,
  "use_flash_attention": false,
  "use_fused_rms_norm": false,
  "use_fused_rope": false,
  "use_high_performance_gemm": false,
  "use_normal_precision_align_tool": false,
  "use_recompute": false,
  "virtual_pp_degree": 1,
  "vocab_size": 32000
}

```
目前可稳定复现
