### ISSUE TITLE
[Question]: llama静态图推理偶发cudaErrorLaunchFailure报错

### ISSUE THREAD

**Issue by zhaohaixu** [PaddlePaddle/PaddleNLP#7144]
### 请提出你的问题

我尝试使用lama预训练200步的checkpoint来做动转静，进而进行静态图推理，推理时会偶发以下报错：

```
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [2048] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [2048] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [2048] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [2048] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [2048] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [2048] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [2048] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [2048] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [2048] and greater than or equal to 0, but received [0]
Traceback (most recent call last):
  File "predictor.py", line 884, in <module>
    predict()
  File "predictor.py", line 828, in predict
    outputs = predictor.predict(batch_source_text)
  File "predictor.py", line 180, in predict
    predictions = self._infer(tokenized_source)
  File "predictor.py", line 279, in _infer
    self.predictor.run()
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:272)
  [operator < slice > error]
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ../paddle/fluid/platform/device/gpu/gpu_info.cc:271)

Aborted (core dumped)
```

预训练的配置如下(https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/llama/run_pretrain.py)：

```
python -u  -m paddle.distributed.launch \
    --gpus "0,1,2,3,4,5,6,7" \
    --log_dir "output/$task_name""_log" \
    run_pretrain.py \
    --model_type "llama" \
    --model_name_or_path "facebook/llama-7b" \
    --tokenizer_name_or_path "facebook/llama-7b" \
    --input_dir "./data" \
    --output_dir "output/$task_name" \
    --split 949,50,1 \
    --max_seq_length 2048 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --use_flash_attention 0 \
    --use_fused_rms_norm 0 \
    --fp16  \
    --fp16_opt_level "O2"  \
    --scale_loss 1024 \
    --learning_rate 0.00001 \
    --min_learning_rate 0.000005 \
    --lr_scheduler_type "cosine" \
    --max_steps 200 \
    --save_steps 200 \
    --weight_decay 0.01 \
    --warmup_ratio 0.01 \
    --max_grad_norm 1.0 \
    --logging_steps 20\
    --dataloader_num_workers 1 \
    --sharding "stage2" \
    --eval_steps 1000 \
    --report_to "visualdl" \
    --disable_tqdm true \
    --continue_training 1\
    --recompute 1 \
    --do_train \
    --do_eval \
    --device "gpu" \
    --data_impl "mmap"
```

静态图推理运行（https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/predictor.py）：python predictor.py --model_name_or_path ./llama/inference/ --batch_size 1 --dtype "float16" --mode "static"
其中用来推理的文本如果填充超过一条，必现该错误；只有一条时，偶现该错误：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/49297029/449498a6-54f5-414f-ac11-02d780971db1)
我参考了这个issue：https://github.com/PaddlePaddle/PaddleNLP/issues/6440
是否是pretrain预训练参数不支持seq_length自定义导致的呢，或者这个错误应该怎么解决已支持多条文本推理呢？

**Comment by wj-Mcat** [comment]
这个是训练完之后导出静态图模型来推理的时候出现了问题吗？  推理的时候是多卡还是单卡？  然后你尝试安装一下最新 paddle 包试一试，因为推理模型最新的 feature 都是在 develop paddle 上面的。

**Comment by zhaohaixu** [comment]
> 这个是训练完之后导出静态图模型来推理的时候出现了问题吗？ 推理的时候是多卡还是单卡？ 然后你尝试安装一下最新 paddle 包试一试，因为推理模型最新的 feature 都是在 develop paddle 上面的。

对的，静态模型推理出的问题，推理时使用单卡。我今天尝试更换了develop(neightly build)，还是会偶现这个报错:(
