### ISSUE TITLE
[Question]: 使用ernie-layout算法微调遇到的问题

### ISSUE THREAD

**Issue by PancakeAwesome** [PaddlePaddle/PaddleNLP#7145]
### 请提出你的问题
运行官方ernie-layout微调命令出错

#### 系统环境
linux-centos7
cuda11.7
cudnn8.9.1.23
openssl 1.1.1
#### python 环境
python=3.8
paddlepaddle-gpu: 2.5.1-post117
paddleocr:2.7.0.3
paddlenlp:2.6.1
### 运行出错的日志
`  0%|                                                                                                                                                                | 0/20000 [00:00<?, ?it/s]Exception in thread Thread-9:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/io/dataloader/dataloader_iter.py", line 235, in _thread_loop
    batch = self._dataset_fetcher.fetch(
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/io/dataloader/fetcher.py", line 86, in fetch
    data = self.collate_fn(data)
  File "/ossfs/workspace/PaddleNLP-develop/model_zoo/ernie-layout/data_collator.py", line 64, in __call__
    feat["bbox"] = feat["bbox"] + [[0, 0, 0, 0] for _ in range(self.max_length - len(feat["bbox"]))]
KeyError: 'bbox'`
# 运行出错的代码
来自：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/README_ch.md#41-%E6%96%87%E6%A1%A3%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96%E4%BB%BB%E5%8A%A1
文档信息抽取任务的微调，数据集是教程中默认下载的xfunzh数据集
`python -u run_ner.py --model_name_or_path ./ernie-layoutx-base-uncased --output_dir ./ernie-layoutx-base-uncased/models/xfund_zh/ --dataset_name xfund_zh --do_train --do_eval --lang "ch" --max_steps 20000 --eval_steps 100 --save_steps 100 --save_total_limit 1 --load_best_model_at_end --pattern ner-bio --preprocessing_num_workers 4 --overwrite_cache false --use_segment_box --doc_stride 128 --target_size 1000 --per_device_train_batch_size 4 --per_device_eval_batch_size 4 --learning_rate 1e-5 --lr_scheduler_type constant --gradient_accumulation_steps 1 --seed 1000 --metric_for_best_model eval_f1 --greater_is_better true --overwrite_output_dir`

**Comment by PancakeAwesome** [comment]
@linjiecc
辛苦帮忙看一下，这个问题已经困扰我很多天了。谢谢🙏
所有的ernie-layout的下游任务在按照官方文档finetune的时候都会出现以上的错误。

**Comment by PancakeAwesome** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/3828
#4599
