### ISSUE TITLE
关于cuda库的问题

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#715]
在申请的GPU上训练时，出现以下问题：

# python skep_sentiment_classification.py
{'text': '选择珠江花园的原因就是方便，有电动扶梯直接到达海边，周围餐馆、食廊、商场、超市、摊位一应俱全。酒店装修一般，但还算整洁。 泳池在大堂的屋顶，因此很小，不过女儿倒是喜欢。 包的早餐是西式的，还算丰富。 服务吗，一般', 'label': 1, 'qid': ''}
{'text': '<荐书> 推荐所有喜欢<红楼>的红迷们一定要收藏这本书,要知道当年我听说这本书的时候花很长时间去图书馆找和借都没能如愿,所以这次一看到当当有,马上买了,红迷们也要记得备货哦!', 'label': 1, 'qid': '1'}
{'text': '这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般', 'label': '', 'qid': '0'}
9600
1200
1200
[2021-07-08 09:22:15,340] [    INFO] - Already cached /root/.paddlenlp/models/skep_ernie_1.0_large_ch/skep_ernie_1.0_large_ch.pdparams
W0708 09:22:15.341675   132 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.0
W0708 09:22:15.341985   132 dynamic_loader.cc:267] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "skep_sentiment_classification.py", line 66, in <module>
    model = SkepForSequenceClassification.from_pretrained(pretrained_model_name_or_path="skep_ernie_1.0_large_ch",
  File "/opt/conda/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 281, in from_pretrained
    base_model = cls.base_model_class(*base_args, **base_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 83, in __impl__
    init_func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/paddlenlp/transformers/skep/modeling.py", line 250, in __init__
    self.embeddings = SkepEmbeddings(
  File "/opt/conda/lib/python3.8/site-packages/paddlenlp/transformers/skep/modeling.py", line 42, in __init__
    self.word_embeddings = nn.Embedding(
  File "/opt/conda/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1343, in __init__
    self.weight = self.create_parameter(
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2858, in create_parameter
    initializer(param, self)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 561, in __call__
    op = block.append_op(
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2884, in append_op
    _dygraph_tracer().trace_op(type,
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:59)
  [operator < uniform_random > error]

环境中的CUDA等也都在。

**Comment by LangDaoAI** [comment]
我这边主要是运行在容器中，容器镜像预设的是基于pytorch， 所以cuda和cudnn虽然有，但是共享库libcudnn.so确没有， 我在尝试下载安装，同时，paddle最新版本自己有没有镜像我们可以下载内含这些依赖，谢谢！

**Comment by FrostML** [comment]
Paddle 这里的镜像可以在这里找到 [DockerHub](https://hub.docker.com/r/paddlepaddle/paddle/tags/?page=1&ordering=last_updated)

**Comment by LangDaoAI** [comment]
嗯嗯，感谢！
