### ISSUE TITLE
目前padddleNLP是否提供了gpt3-13B-en的权重[Question]: 

### ISSUE THREAD

**Issue by CX26-CX** [PaddlePaddle/PaddleNLP#7176]
### 请提出你的问题

目前padddleNLP是否提供了gpt3-13B-en的权重，运行PaddleNIP/examples/benchmark/peft/paddle/benchmark.py的时候显示
Traceback (most recent call last):
  File "/work_code/PaddleNLP/paddlenlp/transformers/model_utils.py", line 1480, in _resolve_model_file_path
    resource_file_url = cls.pretrained_resource_files_map["model_state"][
KeyError: 'gpt3-13B-en'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/benchmark/peft/paddle/benchmark.py", line 326, in <module>
    main()
  File "examples/benchmark/peft/paddle/benchmark.py", line 93, in main
    model = GPTForCausalLM.from_pretrained(
  File "/work_code/PaddleNLP/paddlenlp/transformers/model_utils.py", line 2002, in from_pretrained
    resolved_archive_file, sharded_metadata, is_sharded = cls._resolve_model_file_path(
  File "/work_code/PaddleNLP/paddlenlp/transformers/model_utils.py", line 1536, in _resolve_model_file_path
    raise EnvironmentError(
OSError: Can't load the model for 'gpt3-13B-en'. If you were trying to load it from 'https://paddlenlp.bj.bcebos.com'
I1009 11:35:11.759379 2757205 tcp_store.cc:273] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2023-10-09 11:35:12,257 Exit code 1

如果不提供，PaddleNIP/examples/benchmark/peft/README.md实现的gpt3-13B是怎么实现的

**Comment by ZHUI** [comment]
抱歉，这个没有预训练模型，是用来随机初始化的config。
