### ISSUE TITLE
[Question]: 离线将Pytorch格式的LLM转换成Paddle格式如何操作？

### ISSUE THREAD

**Issue by liguodongiot** [PaddlePaddle/PaddleNLP#7221]
### 请提出你的问题

目前只看到在使用AutoModelForCausalLM在加载模型时，自动下载通过convert_from_torch参数转换。用于服务器无法访问外网，我手动下载的Hugingface上面的模型到本地，然后加载，发现加载本地模型转换就会报一些奇奇怪怪的错误，目前使用bloom、llama和baichuan，都没有转换成功？

我看同类的框架（hf transformers、mindformers）中很多都有相应的转换：
transformers中的转换：
https://github.com/huggingface/transformers/blob/d085662c596066bad82942b1e15819f675cbd15e/src/transformers/models/llama/convert_llama_weights_to_hf.py#L39

mindformers中的转换：
https://gitee.com/mindspore/mindformers/blob/dev/mindformers/models/glm/convert_weight.py

请问目前PaddleNLP中支持的LLM，有提供对应的模型的模型格式转换方法吗？

**Comment by DrownFish19** [comment]
1. 可以先在本地机器通过from_pretrain()加载bloom、llama和baichuan，然后将下载的模型放到离线机器的～/.paddlenlp下。
2. 能把报错日志和运行代码贴一下吗？

**Comment by liguodongiot** [comment]
@DrownFish19 您好：

1. 我用的mac m1 paddlenlp安装不上

2. 对应的代码及报错日志：

模型文件：
```
> ll /home/guodong.li/workspace/model/bloomz-3b
total 5878672
-rwxrwxrwx 1 root root        715 Sep 29 17:48 config.json
-rwxrwxrwx 1 root root 6005243331 Sep 29 18:17 pytorch_model.bin
-rwxrwxrwx 1 root root         85 Sep 29 17:48 special_tokens_map.json
-rwxrwxrwx 1 root root        196 Oct 13 11:18 tokenizer_config.json
-rwxrwxrwx 1 root root   14500438 Sep 29 17:48 tokenizer.json

```

加载Tokenizer：
```
>>> tokenizer = AutoTokenizer.from_pretrained("/home/guodong.li/workspace/model/bloomz-3b")
[2023-10-13 18:59:54,375] [    INFO] - We are using <class 'paddlenlp.transformers.bloom.tokenizer.BloomTokenizer'> to load '/home/guodong.li/workspace/model/bloomz-3b'.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guodong.li/virtual-venv/paddle-venv-py310-cu117/lib/python3.10/site-packages/paddlenlp/transformers/auto/tokenizer.py", line 345, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home/guodong.li/virtual-venv/paddle-venv-py310-cu117/lib/python3.10/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 1593, in from_pretrained
    tokenizer = cls(*init_args, **init_kwargs)
  File "/home/guodong.li/virtual-venv/paddle-venv-py310-cu117/lib/python3.10/site-packages/paddlenlp/transformers/utils.py", line 253, in __impl__
    init_func(self, *args, **kwargs)
TypeError: BloomTokenizer.__init__() missing 2 required positional arguments: 'vocab_file' and 'merges_file'


```

加载模型：
```
>>> model = AutoModelForCausalLM.from_pretrained("/home/guodong.li/workspace/model/bloomz-3b", convert_from_torch=True)
[2023-10-13 18:59:54,384] [    INFO] - We are using <class 'paddlenlp.transformers.bloom.modeling.BloomForCausalLM'> to load '/home/guodong.li/workspace/model/bloomz-3b'.
[2023-10-13 18:59:54,385] [    INFO] - Loading configuration file /home/guodong.li/workspace/model/bloomz-3b/config.json
[2023-10-13 18:59:54,390] [    INFO] - Starting to convert pytorch weight file</home/guodong.li/workspace/model/bloomz-3b/pytorch_model.bin> to paddle weight file</home/guodong.li/workspace/model/bloomz-3b/model_state.pdparams> ...
[2023-10-13 19:00:09,126] [ WARNING] - key<transformer.word_embeddings.weight> not in the pytorch weight file.
...
2023-10-13 19:00:09,213] [ WARNING] - --- h.20.self_attention.query_key_value.weight
[2023-10-13 19:00:09,213] [ WARNING] - --- h.28.mlp.dense_h_to_4h.weight
[2023-10-13 19:00:09,213] [ WARNING] - --- h.2.input_layernorm.weight
W1013 19:00:13.083036 13205 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.0, Runtime API Version: 11.7
W1013 19:00:13.100634 13205 gpu_resources.cc:149] device: 0, cuDNN Version: 8.8.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guodong.li/virtual-venv/paddle-venv-py310-cu117/lib/python3.10/site-packages/paddlenlp/transformers/auto/modeling.py", line 819, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home/guodong.li/virtual-venv/paddle-venv-py310-cu117/lib/python3.10/site-packages/paddlenlp/transformers/auto/modeling.py", line 336, in _from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home/guodong.li/virtual-venv/paddle-venv-py310-cu117/lib/python3.10/site-packages/paddlenlp/transformers/model_utils.py", line 2000, in from_pretrained
    model, missing_keys, unexpected_keys, mismatched_keys = cls._load_pretrained_model(
  File "/home/guodong.li/virtual-venv/paddle-venv-py310-cu117/lib/python3.10/site-packages/paddlenlp/transformers/model_utils.py", line 1760, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for BloomForCausalLM:
        Skip loading for h.0.self_attention.query_key_value.weight. h.0.self_attention.query_key_value.weight receives a shape [7680, 2560], but the expected shape is [2560, 7680].
        Skip loading for h.0.mlp.dense_h_to_4h.weight. h.0.mlp.dense_h_to_4h.weight receives a shape [10240, 2560], but the expected shape is [2560, 10240].
        Skip loading for h.0.mlp.dense_4h_to_h.weight. h.0.mlp.dense_4h_to_h.weight receives a shape [2560, 10240], but the expected shape is [10240, 2560].
        Skip loading for h.1.self_attention.query_key_value.weight. h.1.self_attention.query_key_value.weight receives a shape [7680, 2560], but the expected shape is [2560, 7680].
        Skip loading for h.1.mlp.dense_h_to_4h.weight. h.1.mlp.dense_h_to_4h.weight receives a shape [10240, 2560], but the expected shape is [2560, 10240].
        Skip loading for h.1.mlp.dense_4h_to_h.weight. h.1.mlp.dense_4h_to_h.weight receives a shape [2560, 10240], but the expected shape is [10240, 2560].
        Skip loading for h.2.self_attention.query_key_value.weight. h.2.self_attention.query_key_value.weight receives a shape [7680, 2560], but the expected shape is [2560, 7680].
        Skip loading for h.2.mlp.dense_h_to_4h.weight. h.2.mlp.dense_h_to_4h.weight receives a shape [10240, 2560], but the expected shape is [2560, 10240].
        Skip loading for h.2.mlp.dense_4h_to_h.weight. h.2.mlp.dense_4h_to_h.weight receives a shape [2560, 10240], but the expected shape is [10240, 2560].
        Skip loading for h.3.self_attention.query_key_value.weight. h.3.self_attention.query_key_value.weight receives a shape [7680, 2560], but the expected shape is [2560, 7680].
        Skip loading for h.3.mlp.dense_h_to_4h.weight. h.3.mlp.dense_h_to_4h.weight receives a shape [10240, 2560], but the expected shape is [2560, 10240].
        Skip loading for h.3.mlp.dense_4h_to_h.weight. h.3.mlp.dense_4h_to_h.weight receives a shape [2560, 10240], but the expected shape is [10240, 2560].
        Skip loading for h.4.self_attention.query_key_value.weight. h.4.self_attention.query_key_value.weight receives a shape [7680, 2560], but the expected shape is [2560, 7680].
        Skip loading for h.4.mlp.dense_h_to_4h.weight. h.4.mlp.dense_h_to_4h.weight receives a shape [10240, 2560], but the expected shape is [2560, 10240].
        Skip loading for h.4.mlp.dense_4h_to_h.weight. h.4.mlp.dense_4h_to_h.weight receives a shape [2560, 10240], but the expected shape is [10240, 2560].
...
        Skip loading for h.29.mlp.dense_h_to_4h.weight. h.29.mlp.dense_h_to_4h.weight receives a shape [10240, 2560], but the expected shape is [2560, 10240].
        Skip loading for h.29.mlp.dense_4h_to_h.weight. h.29.mlp.dense_4h_to_h.weight receives a shape [2560, 10240], but the expected shape is [10240, 2560].
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

麻烦帮忙看下

**Comment by liguodongiot** [comment]
另外，Paddle这边有类似Hugingface、魔塔对应modelhub吗？可以直接在网页下载模型或者git-lfs下载llm。

**Comment by DrownFish19** [comment]
1.  我在m1的机器上试了，可以安装paddlenlp
* 安装命令
```shell
2088  conda create -n paddle-paddlenlp python=3.10
2089  conda activate paddle-paddlenlp
2090  python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/mac/cpu/develop.html
2091  pip install --pre --upgrade paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```
* 测试
```python
>>> import paddlenlp
/Users/drownfish19/anaconda3/envs/paddle-paddlenlp/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
from pprint import pprint
>>> from pprint import pprint
>>> from paddlenlp import Taskflow
>>> schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
>>> ie = Taskflow('information_extraction', schema=schema)
[2023-10-16 10:10:34,972] [    INFO] - Downloading model_state.pdparams from https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_base_v1.1/model_state.pdparams
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 450M/450M [00:52<00:00, 8.91MB/s]
[2023-10-16 10:11:29,378] [    INFO] - Downloading config.json from https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_base/config.json
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 610/610 [00:00<00:00, 1.09MB/s]
[2023-10-16 10:11:29,784] [    INFO] - Downloading vocab.txt from https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_base/vocab.txt
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 182k/182k [00:00<00:00, 235kB/s]
[2023-10-16 10:11:30,941] [    INFO] - Downloading special_tokens_map.json from https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_base/special_tokens_map.json
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 112/112 [00:00<00:00, 189kB/s]
[2023-10-16 10:11:31,289] [    INFO] - Downloading tokenizer_config.json from https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_base/tokenizer_config.json
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 172/172 [00:00<00:00, 348kB/s]
[2023-10-16 10:11:31,616] [    INFO] - Loading configuration file /Users/drownfish19/.paddlenlp/taskflow/information_extraction/uie-base/config.json
[2023-10-16 10:11:31,618] [    INFO] - Loading weights file /Users/drownfish19/.paddlenlp/taskflow/information_extraction/uie-base/model_state.pdparams
[2023-10-16 10:11:32,114] [    INFO] - Loaded weights file from disk, setting weights to model.
[2023-10-16 10:11:35,319] [    INFO] - All model checkpoint weights were used when initializing UIE.

[2023-10-16 10:11:35,319] [    INFO] - All the weights of UIE were initialized from the model checkpoint at /Users/drownfish19/.paddlenlp/taskflow/information_extraction/uie-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use UIE for predictions without further training.
[2023-10-16 10:11:35,320] [    INFO] - Converting to the inference model cost a little time.
I1016 10:11:36.071406 3703689984 program_interpreter.cc:187] New Executor is Running.
[2023-10-16 10:11:37,625] [    INFO] - The inference model save in the path:/Users/drownfish19/.paddlenlp/taskflow/information_extraction/uie-base/static/inference
E1016 10:11:37.625696 3703689984 analysis_config.cc:652] Please compile with MKLDNN first to use MKLDNN
[2023-10-16 10:11:37,894] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load '/Users/drownfish19/.paddlenlp/taskflow/information_extraction/uie-base'.
>>> pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
/Users/drownfish19/anaconda3/envs/paddle-paddlenlp/lib/python3.10/site-packages/paddlenlp/transformers/tokenizer_utils_base.py:2478: FutureWarning: The `max_seq_len` argument is deprecated and will be removed in a future version, please use `max_length` instead.
  warnings.warn(
/Users/drownfish19/anaconda3/envs/paddle-paddlenlp/lib/python3.10/site-packages/paddlenlp/transformers/tokenizer_utils_base.py:1878: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(
[{'时间': [{'end': 6,
          'probability': 0.9857378532924486,
          'start': 0,
          'text': '2月8日上午'}],
  '赛事名称': [{'end': 23,
            'probability': 0.8503090565403681,
            'start': 6,
            'text': '北京冬奥会自由式滑雪女子大跳台决赛'}],
  '选手': [{'end': 31,
          'probability': 0.898154745730146,
          'start': 28,
          'text': '谷爱凌'}]}]
```

**Comment by DrownFish19** [comment]
2. paddle和pytorch的linear权重是相互转置的，paddlenlp已经在代码中进行了转置，参考下方代码。可以试试删除`transpose`。
https://github.com/PaddlePaddle/PaddleNLP/blob/70e750c02c824aecd364ca131fc90693738ccb51/paddlenlp/transformers/bloom/modeling.py#L711-L739
3. 可以尝试自行下载paddlenlp提供的模型，当前每一个模型的下载链接可以在paddlenlp/transformers/xx/configuration.py中查到，参考这里：
https://github.com/PaddlePaddle/PaddleNLP/blob/70e750c02c824aecd364ca131fc90693738ccb51/paddlenlp/transformers/bloom/configuration.py#L36
4. 附上我的运行log，你可以按照这个log找对应文件下载
```python
>>> tokenizer = AutoTokenizer.from_pretrained("bigscience/bloomz-3b")
[2023-10-16 10:34:11,527] [    INFO] - Downloading tokenizer_config.json from https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/tokenizer_config.json
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 254/254 [00:00<00:00, 27.1kB/s]
[2023-10-16 10:34:25,919] [    INFO] - We are using <class 'paddlenlp.transformers.bloom.tokenizer.BloomTokenizer'> to load 'bigscience/bloomz-3b'.
[2023-10-16 10:34:25,923] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/vocab.json and saved to /Users/drownfish19/.paddlenlp/models/bigscience/bloomz-3b
[2023-10-16 10:34:26,085] [    INFO] - Downloading vocab.json from https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/vocab.json
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.26M/6.26M [00:00<00:00, 18.6MB/s]
[2023-10-16 10:34:26,670] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/merges.txt and saved to /Users/drownfish19/.paddlenlp/models/bigscience/bloomz-3b
[2023-10-16 10:34:26,795] [    INFO] - Downloading merges.txt from https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/merges.txt
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.98M/3.98M [00:00<00:00, 16.3MB/s]
[2023-10-16 10:34:27,242] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/tokenizer.json and saved to /Users/drownfish19/.paddlenlp/models/bigscience/bloomz-3b
[2023-10-16 10:34:27,362] [    INFO] - Downloading tokenizer.json from https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/tokenizer.json
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13.8M/13.8M [00:00<00:00, 41.9MB/s]
[2023-10-16 10:34:27,879] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/added_tokens.json and saved to /Users/drownfish19/.paddlenlp/models/bigscience/bloomz-3b
[2023-10-16 10:34:27,983] [ WARNING] - file<https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/added_tokens.json> not exist
[2023-10-16 10:34:27,984] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/special_tokens_map.json and saved to /Users/drownfish19/.paddlenlp/models/bigscience/bloomz-3b
[2023-10-16 10:34:28,103] [    INFO] - Downloading special_tokens_map.json from https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/special_tokens_map.json
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 96.0/96.0 [00:00<00:00, 464kB/s]
[2023-10-16 10:34:28,298] [    INFO] - Already cached /Users/drownfish19/.paddlenlp/models/bigscience/bloomz-3b/tokenizer_config.json
```

```python
>>> model = AutoModelForCausalLM.from_pretrained("bigscience/bloomz-3b")
[2023-10-16 10:28:49,350] [    INFO] - Downloading config.json from https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/config.json
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 745/745 [00:00<00:00, 618kB/s]
[2023-10-16 10:28:49,660] [    INFO] - We are using <class 'paddlenlp.transformers.bloom.modeling.BloomForCausalLM'> to load 'bigscience/bloomz-3b'.
[2023-10-16 10:28:49,661] [    INFO] - Found /Users/drownfish19/.paddlenlp/models/bigscience/bloomz-3b/config.json
[2023-10-16 10:28:49,662] [    INFO] - Loading configuration file /Users/drownfish19/.paddlenlp/models/bigscience/bloomz-3b/config.json
[2023-10-16 10:28:50,055] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/model_state.pdparams
[2023-10-16 10:28:50,056] [    INFO] - Downloading model_state.pdparams from https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-3b/model_state.pdparams
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.59G/5.59G [01:41<00:00, 59.1MB/s]
[2023-10-16 10:30:32,044] [    INFO] - Loading weights file model_state.pdparams from cache at /Users/drownfish19/.paddlenlp/models/bigscience/bloomz-3b/model_state.pdparams
[2023-10-16 10:30:42,877] [    INFO] - Loaded weights file from disk, setting weights to model.
[2023-10-16 10:31:35,015] [    INFO] - All model checkpoint weights were used when initializing BloomForCausalLM.

[2023-10-16 10:31:35,016] [    INFO] - All the weights of BloomForCausalLM were initialized from the model checkpoint at bigscience/bloomz-3b.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BloomForCausalLM for predictions without further training.
[2023-10-16 10:31:35,185] [    INFO] - Generation config file not found, using a generation config created from the model config.
```

**Comment by liguodongiot** [comment]
@DrownFish19 谢谢指导， 本地 mac m1 下载不会有问题，但是这里有点小问题，离线环境PretrainedTokenizerBase类会去下载added_tokens.json，而导致中断；**直接加载本地目录是可以的**。

```
>>> from paddlenlp.transformers.bloom.tokenizer import BloomTokenizer
>>> 
>>> tokenizer = BloomTokenizer.from_pretrained("bigscience/bloomz-560m")
[2023-10-16 19:21:30,408] [    INFO] - Already cached /Users/liguodong/.paddlenlp/models/bigscience/bloomz-560m/vocab.json
[2023-10-16 19:21:30,409] [    INFO] - Already cached /Users/liguodong/.paddlenlp/models/bigscience/bloomz-560m/merges.txt
[2023-10-16 19:21:30,409] [    INFO] - Already cached /Users/liguodong/.paddlenlp/models/bigscience/bloomz-560m/tokenizer.json
[2023-10-16 19:21:30,410] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-560m/added_tokens.json and saved to /Users/liguodong/.paddlenlp/models/bigscience/bloomz-560m
[2023-10-16 19:21:30,628] [ WARNING] - file<https://bj.bcebos.com/paddlenlp/models/community/bigscience/bloomz-560m/added_tokens.json> not exist
[2023-10-16 19:21:30,628] [    INFO] - Already cached /Users/liguodong/.paddlenlp/models/bigscience/bloomz-560m/special_tokens_map.json
[2023-10-16 19:21:30,628] [    INFO] - Already cached /Users/liguodong/.paddlenlp/models/bigscience/bloomz-560m/tokenizer_config.json
```

https://github.com/PaddlePaddle/PaddleNLP/blob/dd9bec075cf030dff88dafe23e6f9d541b3e43cf/paddlenlp/transformers/tokenizer_utils_base.py#L1292

<img width="835" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/13220186/5aaca65c-e8f1-4da4-a32a-8fc37a113ec9">

https://github.com/PaddlePaddle/PaddleNLP/blob/e73834944d8f8a1d0376664f579fa513db411c8f/paddlenlp/utils/downloader.py#L427

<img width="906" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/13220186/d0babeec-bef9-4361-a821-393eb8d58514">

<img width="670" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/13220186/977e3c1d-6ccd-4464-8cc0-7faf84cbe3f9">
