### ISSUE TITLE
[Question]: MemoryError: (ResourceExhausted) Fail to alloc memory of 4131529007104 size, error code is 12.

### ISSUE THREAD

**Issue by wencan** [PaddlePaddle/PaddleNLP#7231]
### 请提出你的问题
fedora 38
Python 3.11.6
paddlenlp                              2.6.1.post0
no gpu

执行：
ie = Taskflow('information_extraction', schema=['组织', '人名'])
ie('本书由百度官方出品，百度公司CTO王海峰博士作序，张钹院士、李未院士、百度集团副总裁吴甜联袂推荐。')

得到输出：
```
/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/transformers/tokenizer_utils_base.py:2484: FutureWarning: The `max_seq_len` argument is deprecated and will be removed in a future version, please use `max_length` instead.
  warnings.warn(
/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/transformers/tokenizer_utils_base.py:1884: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/taskflow/taskflow.py", line 822, in __call__
    results = self.task_instance(inputs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/taskflow/task.py", line 527, in __call__
    outputs = self._run_model(inputs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/taskflow/information_extraction.py", line 1068, in _run_model
    results = self._multi_stage_predict(_inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/taskflow/information_extraction.py", line 1166, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/taskflow/information_extraction.py", line 979, in _single_stage_predict
    self.predictor.run()
MemoryError: (ResourceExhausted) Fail to alloc memory of 4131529007104 size, error code is 12.
  [Hint: Expected error == 0, but received error:12 != 0:0.] (at /paddle/paddle/fluid/memory/allocation/cpu_allocator.cc:50)
  [operator < fill_constant > error]

```

4131529007104 这个数太夸张了吧？

如果是执行文档上的示例
>>> schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
>>> ie = Taskflow('information_extraction', schema=schema)
>>> pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
也是一样的输出：
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/taskflow/taskflow.py", line 822, in __call__
    results = self.task_instance(inputs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/taskflow/task.py", line 527, in __call__
    outputs = self._run_model(inputs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/taskflow/information_extraction.py", line 1068, in _run_model
    results = self._multi_stage_predict(_inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/taskflow/information_extraction.py", line 1166, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wencan/.local/lib/python3.11/site-packages/paddlenlp/taskflow/information_extraction.py", line 979, in _single_stage_predict
    self.predictor.run()
MemoryError: (ResourceExhausted) Fail to alloc memory of 4131529007104 size, error code is 12.
  [Hint: Expected error == 0, but received error:12 != 0:0.] (at /paddle/paddle/fluid/memory/allocation/cpu_allocator.cc:50)
  [operator < fill_constant > error]

```

**Comment by wencan** [comment]
同一系统，换成Python 3.8.18，是同样的错误

**Comment by wencan** [comment]
切换到有显卡的机器上，正常

**Comment by wencan** [comment]
无gpu机器，切换到 paddlenlp==2.4.0 paddlepaddle==2.4.2 
也正常
