### ISSUE TITLE
利用ernie gen作诗的思路，换了数据集，gpu报错

### ISSUE THREAD

**Issue by hl123-123** [PaddlePaddle/PaddleNLP#724]
该行        optimizer.step()报错
显存才占用20%，运行两个step报错，
好像和batch_size有关，设为1,则运行340个step报错
报错信息：
SystemError: (Fatal) Operator elementwise_max raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

**Comment by wawltor** [comment]
@hl123-123 麻烦提供一下PaddlePaddle的以及PaddleNLP的版本？

**Comment by orlando1986** [comment]
> @hl123-123 麻烦提供一下PaddlePaddle的以及PaddleNLP的版本？
我也碰到了相同的问题，我用的是
PaddlePaddle 2.1.2
paddlenlp 2.1.1

**Comment by ZHUI** [comment]
> > @hl123-123 麻烦提供一下PaddlePaddle的以及PaddleNLP的版本？
> > 我也碰到了相同的问题，我用的是
> > PaddlePaddle 2.1.2
> > paddlenlp 2.1.1

是否有更多报错信息？

**Comment by orlando1986** [comment]
> 是否有更多报错信息？

Traceback (most recent call last):
  File "/home/aistudio/work/ernie_gen/train.py", line 271, in <module>
    train()
  File "/home/aistudio/work/ernie_gen/train.py", line 252, in train
    optimizer.step()
  File "<decorator-gen-198>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-196>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 366, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 793, in _apply_optimize
    params_grads = self._grad_clip(params_grads)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/clip.py", line 134, in __call__
    return self._dygraph_clip(params_grads)
  File "<decorator-gen-102>", line 2, in _dygraph_clip
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/clip.py", line 435, in _dygraph_clip
    x=global_norm_var, y=max_global_norm))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 11858, in elementwise_max
    x, y, axis=axis, act=act, op_name='elementwise_max')
  File "<decorator-gen-28>", line 2, in _elementwise_op_in_dygraph
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 205, in _elementwise_op_in_dygraph
    out = op(x, y, 'axis', axis, 'use_mkldnn', use_mkldnn)
SystemError: (Fatal) Operator elementwise_max raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

**Comment by orlando1986** [comment]
我设置了max encode length和max decode length都是512，batch=8，在186步的时候就报错了。把max encode length和max decode length都设500，batch=8，在604步报错

**Comment by ZHUI** [comment]
能否 `cuda-memcheck python xxx.py` 跑一下程序试试，这个对于cuda的内存访问会严格check。或者开启 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/flags/others_cn.html#flags-benchmark 试一试？

**Comment by orlando1986** [comment]
打的log比较多，我这只取了最后一段
Traceback (most recent call last):
  File "/home/aistudio/work/ernie_gen/train.py", line 271, in <module>
    train()
  File "/home/aistudio/work/ernie_gen/train.py", line 242, in train
    tgt_labels, tgt_pos)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/ernie_gen/model.py", line 41, in forward
    encode_only=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/ernie_gen/modeling.py", line 651, in forward
    encoded, info = ErnieModel.forward(self, *args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/ernie_gen/modeling.py", line 558, in forward
    sent_embedded = self.sent_emb(sent_ids)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 1358, in forward
    name=self._name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/input.py", line 200, in embedding
    'remote_prefetch', False, 'padding_idx', padding_idx)
OSError: (External)  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)
  [operator < lookup_table_v2 > error]
========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to "unspecified launch failure" on CUDA API call to cuModuleUnload. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuModuleUnload + 0x162) [0x25a722]
=========     Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa87a0f]
=========     Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa88d50]
=========     Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa8dbf7]
=========     Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa8e012]
=========     Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa7f2b6]
=========     Host Frame:/usr/local/cuda/lib64/libcusolver.so [0xa7fae5]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 [0x39ff8]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 [0x3a045]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf7) [0x20837]
=========     Host Frame:python [0x1db062]

**Comment by ZHUI** [comment]
具体到这里报错的：
```
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/input.py", line 200, in embedding
'remote_prefetch', False, 'padding_idx', padding_idx)
OSError: (External) Cuda error(719), unspecified launch failure.
```
对应代码是取embeding的index出现了问题
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/input.py#L200 

再看：
```
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/ernie_gen/modeling.py", line 558, in forward
sent_embedded = self.sent_emb(sent_ids)
```
这里的sent_ids，看起来是有问题的
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie_gen/modeling.py#L558

sent_emb的大小是`type_vocab_size=4`，你可以检查一些是不是出现`sent_ids`出现了`>=4`的情况。
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie_gen/modeling.py#L234

**Comment by orlando1986** [comment]
> sent_emb的大小是`type_vocab_size=4`，你可以检查一些是不是出现`sent_ids`出现了`>=4`的情况。

多谢指点。
我这边用的是咱们PADDLENLP/examples里的代码，直接copy过来的，外面只是调用。调用方式为：
!python /home/aistudio/work/ernie_gen/train.py --model_name_or_path="ernie-1.0" --train_data_path="/home/aistudio/data/data113203/chinese-news-title/train_data.json" --test_data_path="/home/aistudio/data/data113203/chinese-news-title/test_data.json" --output_dir="/home/aistudio/work/checkpoint/" --max_encode_len=512 --max_decode_len=512 --num_epochs=5 --save_steps=1000 --save_dir="/home/aistudio/work/model"

代码改动了一点点，是为了适配我的数据集：
diff --git a/encode.py b/encode.py
index 1faffd8..50286c0 100644
\--- a/encode.py
\+++ b/encode.py
@@ -27,8 +27,8 @@ def convert_example(tokenizer,
                     use_random_noice=False):
     def warpper(example):
         """convert an example into necessary features"""
\-        tokens = example['tokens']
\-        labels = example['labels']
\+        tokens = example['title']
\+        labels = example['content']
         encoded_src = tokenizer(
             tokens, max_seq_len=max_encode_len, pad_to_max_seq_len=False)
         src_ids, src_sids = encoded_src["input_ids"], encoded_src[

\--- a/train.py
\+++ b/train.py
@@ -17,6 +17,7 @@ import ast
 import time
 import argparse
 import logging
\+import json
 
 import paddle
 from tqdm import tqdm
@@ -36,6 +37,8 @@ from model import StackModel
 parser = argparse.ArgumentParser('seq2seq model with ERNIE-GEN')
 parser.add_argument("--model_name_or_path", default=None, type=str, required=True, help="Path to pre-trained model or shortcut name selected in the list: "+ ", ".join(list(ErnieTokenizer.pretrained_init_configuration.keys())))
\+parser.add_argument("--train_data_path", default=None, type=str, required=True, help="Path of data set to be used to train")
\+parser.add_argument("--test_data_path", default=None, type=str, required=True, help="Path of data set to be used to test")
 parser.add_argument("--output_dir", default=None, type=str, required=True, help="The output directory where the model predictions and checkpoints will be written.",)
 parser.add_argument('--max_encode_len', type=int, default=5, help="The max encoding sentence length")
 parser.add_argument('--max_decode_len', type=int, default=5, help="The max decoding sentence length")
@@ -120,6 +123,12 @@ def evaluate(model, data_loader, tokenizer, rouge1, rouge2, attn_id,
  
\+def read(data_path):
\+    with open(data_path, "r", encoding="utf-8") as f:
\+        raw = f.read()
\+        json_data = str(raw)
\+        articals = json.loads(json_data)
\+    return articals
 
 def train():
     paddle.set_device(args.device)
@@ -141,8 +150,8 @@ def train():
         model_state = paddle.load(args.init_checkpoint)
         model.set_state_dict(model_state)
 
\-    train_dataset, dev_dataset = load_dataset(
\-        'poetry', splits=('train', 'dev'), lazy=False)
\+    train_dataset = load_dataset(read, data_path=args.train_data_path, lazy=False)
\+    dev_dataset = load_dataset(read, data_path=args.test_data_path, lazy=False)
     attn_id = tokenizer.vocab[
         '[ATTN]'] if '[ATTN]' in tokenizer.vocab else tokenizer.vocab['[MASK]']
     tgt_type_id = model.sent_emb.weight.shape[0] - 1


请问你有aistudio的账号吗，我这边可以给你share一下我的项目。

**Comment by hl123-123** [comment]
这个我现在在搞CV GAN 先停了nlp训练，这个代码我忘了，很尴尬

**Comment by hl123-123** [comment]
这个问题对大家有帮助就好

**Comment by ZHUI** [comment]
> 请问你有aistudio的账号吗，我这边可以给你share一下我的项目。

这个是我的账户地址
https://aistudio.baidu.com/aistudio/personalcenter/thirdview/301792

**Comment by orlando1986** [comment]
> > 请问你有aistudio的账号吗，我这边可以给你share一下我的项目。
> 
> 这个是我的账户地址 https://aistudio.baidu.com/aistudio/personalcenter/thirdview/301792

在aistudio上没法给你留言和分享，我又提了一个issue来跟踪吧，不在人家下面发问了
https://github.com/PaddlePaddle/PaddleNLP/issues/1252
