### ISSUE TITLE
动态图导出为静态图 报错

### ISSUE THREAD

**Issue by xujiang1** [PaddlePaddle/PaddleNLP#7298]
### 请提出你的问题

当我使用  python export_model.py     --model_name_or_path ./checkpoints/opt_sft_ckpts_125m      --output_path ./inference     --dtype float16  导出 opt 125m 时报错如下：
```
Traceback (most recent call last):
  File "/hy-tmp/PaddleNLP/llm/export_model.py", line 98, in <module>
    main()
  File "/hy-tmp/PaddleNLP/llm/export_model.py", line 84, in main
    predictor.model.to_static(
  File "/usr/local/miniconda3/envs/paddlenlp/lib/python3.10/site-packages/paddlenlp/generation/utils.py", line 1240, in to_static
    model_inputs_spec["attention_mask"],  # attention_mask
KeyError: 'attention_mask'
```
./checkpoints/opt_sft_ckpts_125m为 sft训练结果

**Comment by xujiang1** [comment]
在 paddlenlp/transformers/opt/modeling.py 中  class OPTForCausalLM(OPTPretrainedModel): 中 重写了 

```
    def _get_model_inputs_spec(self, dtype: str):
        return {
            "input_ids": paddle.static.InputSpec(shape=[None, None], dtype="int64"),
        }
```
但没有写 attention_mask 这个key  不知道是漏了 还是逻辑上不能使用 attention_mask
