### ISSUE TITLE
skep/deploy/python/predict.py 运行出现异常

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#732]
skep/deploy/python/predict.py 运行出现异常，请team帮忙看一下这个问题

Traceback (most recent call last):
  File "D:\PVoc\skep\deploy\python\predict.py", line 195, in <module>
    results = predictor.predict(
  File "D:\PVoc\skep\deploy\python\predict.py", line 168, in predict
    self.predictor.run()
ValueError: In user code:

    File "D:\PVoc\skep\export_model.py", line 59, in <module>
      paddle.jit.save(model, args.output_path)
    File "<decorator-gen-67>", line 2, in save

    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\jit.py", line 718, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 487, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 698, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-65>", line 2, in from_func_spec

   File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "D:\SensitiveWords\venv\lib\site-packages\paddlenlp\transformers\skep\modeling.py", line 405, in forward
      _, pooled_output = self.skep(
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\W50010~1\AppData\Local\Temp\tmpr5ufnu4l.py", line 63, in forward
      attention_mask = paddle.jit.dy2static.convert_ifelse(attention_mask is
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\SensitiveWords\venv\lib\site-packages\paddlenlp\transformers\skep\modeling.py", line 322, in forward
      ).astype(self.pooler.dense.weight.dtype) * -1e9,
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 300, in __impl__
      current_block(self).append_op(
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\framework.py", line 2899, in append_op
      op = Operator(
    File "D:\SensitiveWords\venv\lib\site-packages\paddle\fluid\framework.py", line 1977, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The DataType of equal Op's duplicable Variable Y must be consistent. The current variable type is (int64_t), but the previous variable type is (int). (at C
:\home\workspace\Paddle_release\paddle\fluid\framework\operator.cc:1579)
      [operator < equal > error]

**Comment by Steffy-zxf** [comment]
你好！是否方便提供最小复现代码及环境？我们需要复现，调试看看问题。

**Comment by LangDaoAI** [comment]
> 你好！是否方便提供最小复现代码及环境？我们需要复现，调试看看问题。

经过线下沟通，可能windows和linux环境差异，我把export_model.py中的导出的数据类型修改为int， 问题解决了， 先关闭问题了，感谢回复。

**Comment by BaiIIzt** [comment]
![image](https://user-images.githubusercontent.com/75989862/166445936-5ba084fb-5d49-4423-a61a-2bb2430267fa.png)
是这里修改为int吗
