### ISSUE TITLE
[Question]: llama static graph infer failed

### ISSUE THREAD

**Issue by gtgtgt1117** [PaddlePaddle/PaddleNLP#7352]
### 请提出你的问题

参考llm 的README 中llama静态图推理，报错信息如下
(paddleslim) :~/PaddleNLP/llm# python export_model.py --model_name_or_path meta-llama/Llama-2-7b-chat --output_path ./inference -
/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
model_args ModelArgument(model_type=None, data_file=None, output_file='output.json') PredictorArgument(model_name_or_path='meta-llama/Llama-2-7b-chat', mogth=1024, max_length=2048, top_k=0, top_p=0.7, temperature=0.95, repetition_penalty=1.0, device='gpu', dtype='float16', lora_path=None, export_precache=Fade_strategy='sampling', mode='dynamic', inference_model=False, quant_type='None', batch_size=1, benchmark=False, enable_memory_optim=True, init_fleet_work
[2023-11-01 14:31:43,871] [    INFO] - Found /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/tokenizer_config.json
[2023-11-01 14:31:43,871] [    INFO] - We are using <class 'paddlenlp.transformers.llama.tokenizer.LlamaTokenizer'> to load 'meta-llama/Llama-2-7b-chat'.
[2023-11-01 14:31:43,872] [    INFO] - Already cached /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/sentencepiece.bpe.model
[2023-11-01 14:31:43,872] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/meta-llama/Llama-2-7b-chat/added_tokens.json and saved/meta-llama/Llama-2-7b-chat
[2023-11-01 14:31:45,489] [ WARNING] - file<https://bj.bcebos.com/paddlenlp/models/community/meta-llama/Llama-2-7b-chat/added_tokens.json> not exist
[2023-11-01 14:31:45,489] [    INFO] - Already cached /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/special_tokens_map.json
[2023-11-01 14:31:45,490] [    INFO] - Already cached /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/tokenizer_config.json
[2023-11-01 14:31:45,501] [   ERROR] - Using pad_token, but it is not set yet.
[2023-11-01 14:31:48,204] [    INFO] - Found /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/config.json
[2023-11-01 14:31:48,205] [    INFO] - We are using <class 'paddlenlp.transformers.llama.modeling.LlamaForCausalLM'> to load 'meta-llama/Llama-2-7b-chat'.
[2023-11-01 14:31:50,384] [    INFO] - Found /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/config.json
[2023-11-01 14:31:50,385] [    INFO] - Loading configuration file /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/config.json
[2023-11-01 14:31:55,444] [    INFO] - Already cached /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/model_state.pdparams
[2023-11-01 14:31:55,445] [    INFO] - Loading weights file model_state.pdparams from cache at /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/model_st
[2023-11-01 14:33:07,557] [    INFO] - Loaded weights file from disk, setting weights to model.
Traceback (most recent call last):
  File "/root/xygao/LLM/PaddleNLP/llm/export_model.py", line 97, in <module>
    main()
  File "/root/xygao/LLM/PaddleNLP/llm/export_model.py", line 81, in main
    predictor = create_predictor(predictor_args, model_args, tensor_parallel_degree, tensor_parallel_rank)
  File "/root/xygao/LLM/PaddleNLP/llm/predictor.py", line 702, in create_predictor
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/auto/modeling.py", line 819, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/auto/modeling.py", line 373, in _from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py", line 1992, in from_pretrained
    model = cls(config, *init_args, **model_kwargs)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/utils.py", line 253, in __impl__
    init_func(self, *args, **kwargs)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/llama/modeling.py", line 1386, in __init__
    self.llama = LlamaModel(config)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/utils.py", line 256, in __impl__
    post_init_func(self, init_func, *args, **kwargs)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py", line 907, in _post_init
    self.init_weights()
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py", line 932, in init_weights
    self.apply(self._initialize_weights)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 583, in apply
    layer.apply(fn)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 585, in apply
    fn(self)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py", line 921, in _initialize_weights
    self._init_weights(layer)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/llama/modeling.py", line 1046, in _init_weights
    paddle.tensor.normal(
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/tensor/random.py", line 660, in normal
    return gaussian(shape=shape, mean=mean, std=std, name=name)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/tensor/random.py", line 370, in gaussian
    return _C_ops.gaussian(
RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), float16) of kernel `gaussian` is not registered. Selected wrong DataType `float16 DataTypes: float64, float32.
  [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kerd::CPU:1 == true:1.] (at /paddle/paddle/phi/core/kernel_factory.cc:262)

修改dtype为 float32后，报错信息如下
(paddleslim) root:~/PaddleNLP/llm# python export_model.py --model_name_or_path meta-llama/Llama-2-7b-chat --output_path ./inference -
/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
model_args ModelArgument(model_type=None, data_file=None, output_file='output.json') PredictorArgument(model_name_or_path='meta-llama/Llama-2-7b-chat', mogth=1024, max_length=2048, top_k=0, top_p=0.7, temperature=0.95, repetition_penalty=1.0, device='gpu', dtype='float32', lora_path=None, export_precache=Fade_strategy='sampling', mode='dynamic', inference_model=False, quant_type='None', batch_size=1, benchmark=False, enable_memory_optim=True, init_fleet_work
[2023-11-01 14:36:02,437] [    INFO] - Found /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/tokenizer_config.json
[2023-11-01 14:36:02,438] [    INFO] - We are using <class 'paddlenlp.transformers.llama.tokenizer.LlamaTokenizer'> to load 'meta-llama/Llama-2-7b-chat'.
[2023-11-01 14:36:02,438] [    INFO] - Already cached /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/sentencepiece.bpe.model
[2023-11-01 14:36:02,438] [    INFO] - Downloading https://bj.bcebos.com/paddlenlp/models/community/meta-llama/Llama-2-7b-chat/added_tokens.json and saved/meta-llama/Llama-2-7b-chat
[2023-11-01 14:36:04,029] [ WARNING] - file<https://bj.bcebos.com/paddlenlp/models/community/meta-llama/Llama-2-7b-chat/added_tokens.json> not exist
[2023-11-01 14:36:04,030] [    INFO] - Already cached /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/special_tokens_map.json
[2023-11-01 14:36:04,030] [    INFO] - Already cached /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/tokenizer_config.json
[2023-11-01 14:36:04,042] [   ERROR] - Using pad_token, but it is not set yet.
[2023-11-01 14:36:06,395] [    INFO] - Found /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/config.json
[2023-11-01 14:36:06,397] [    INFO] - We are using <class 'paddlenlp.transformers.llama.modeling.LlamaForCausalLM'> to load 'meta-llama/Llama-2-7b-chat'.
[2023-11-01 14:36:07,796] [    INFO] - Found /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/config.json
[2023-11-01 14:36:07,797] [    INFO] - Loading configuration file /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/config.json
[2023-11-01 14:36:10,681] [    INFO] - Already cached /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/model_state.pdparams
[2023-11-01 14:36:10,682] [    INFO] - Loading weights file model_state.pdparams from cache at /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/model_st
[2023-11-01 14:37:22,104] [    INFO] - Loaded weights file from disk, setting weights to model.
[2023-11-01 14:41:56,383] [    INFO] - All model checkpoint weights were used when initializing LlamaForCausalLM.

[2023-11-01 14:41:56,383] [    INFO] - All the weights of LlamaForCausalLM were initialized from the model checkpoint at meta-llama/Llama-2-7b-chat.
If your task is similar to the task the model of the checkpoint was trained on, you can already use LlamaForCausalLM for predictions without further train
[2023-11-01 14:41:57,853] [    INFO] - Downloading generation_config.json from https://bj.bcebos.com/paddlenlp/models/community/meta-llama/Llama-2-7b-chat
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 132
[2023-11-01 14:41:59,361] [    INFO] - Loading configuration file /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/generation_config.json
[2023-11-01 14:42:01,367] [    INFO] - Found /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/config.json
[2023-11-01 14:42:01,368] [    INFO] - We are using <class 'paddlenlp.transformers.llama.configuration.LlamaConfig'> to load 'meta-llama/Llama-2-7b-chat'.
[2023-11-01 14:42:02,685] [    INFO] - Found /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/config.json
[2023-11-01 14:42:02,685] [    INFO] - Loading configuration file /root/.paddlenlp/models/meta-llama/Llama-2-7b-chat/config.json
/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/jit/dy2static/program_translator.py:692: UserWarning: full_graph=False don't support il not produce any effect.
You can set full_graph=True, then you can assign input spec.

  warnings.warn(
/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/jit/api.py:1006: UserWarning: What you save is a function, and `jit.save` will generate according to `path` you specify. When loading these files with `jit.load`, you get a `TranslatedLayer` whose inference result is the same as the inferenou saved.
  warnings.warn(
Traceback (most recent call last):
  File "/root/xygao/LLM/PaddleNLP/llm/export_model.py", line 97, in <module>
    main()
  File "/root/xygao/LLM/PaddleNLP/llm/export_model.py", line 83, in main
    predictor.model.to_static(
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/generation/utils.py", line 1326, in to_static
    paddle.jit.save(model, path)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/base/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/jit/api.py", line 813, in wrapper
    func(layer, path, input_spec, **configs)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/base/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/base/dygraph/base.py", line 68, in __impl__
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/jit/api.py", line 1153, in save
    static_func.concrete_program_specify_input_spec(
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/jit/dy2static/program_translator.py", line 964, in concrete_program_specify_in
    concrete_program, _ = self.get_concrete_program(
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/jit/dy2static/program_translator.py", line 829, in get_concrete_program
    args, kwargs = self._function_spec.unified_args_and_kwargs(
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddle/jit/dy2static/function_spec.py", line 92, in unified_args_and_kwargs
    raise ValueError(error_msg)
ValueError: The decorated function `generate` requires 4 arguments: ['input_ids', 'generation_config', 'stopping_criteria', 'streamer'], but received 26 w1), dtype=paddle.int64, name=None, stop_gradient=False), InputSpec(shape=(-1, -1), dtype=paddle.int64, name=None, stop_gradient=False), None, InputSpec(sh4, name=None, stop_gradient=False), 0, 'sampling', InputSpec(shape=(1,), dtype=paddle.float32, name=None, stop_gradient=False), 0, InputSpec(shape=(1,), done, stop_gradient=False), 1, 1, 1, 0.0, False, 0, 0, 0, None, None, None, None, 1, 0.0, True, False, False).

paddlepaddle 和 paddleslim 都是安装develop版本
Package             Version
------------------- ------------
aiohttp             3.8.6
aiosignal           1.3.1
annotated-types     0.6.0
anyio               3.7.1
astor               0.8.1
async-timeout       4.0.3
attrs               23.1.0
Babel               2.13.1
bce-python-sdk      0.8.92
blinker             1.6.3
certifi             2023.7.22
charset-normalizer  3.3.1
click               8.1.7
colorama            0.4.6
colorlog            6.7.0
conda-pack          0.7.1
contourpy           1.1.1
cycler              0.12.1
datasets            2.14.6
decorator           5.1.1
dill                0.3.4
exceptiongroup      1.1.3
fastapi             0.104.1
filelock            3.13.1
Flask               3.0.0
flask-babel         4.0.0
fonttools           4.43.1
frozenlist          1.4.0
fsspec              2023.10.0
future              0.18.3
h11                 0.14.0
httpcore            0.18.0
httpx               0.25.0
huggingface-hub     0.18.0
idna                3.4
importlib-metadata  6.8.0
importlib-resources 6.1.0
itsdangerous        2.1.2
jieba               0.42.1
Jinja2              3.1.2
joblib              1.3.2
kiwisolver          1.4.5
markdown-it-py      3.0.0
MarkupSafe          2.1.3
matplotlib          3.8.0
mdurl               0.1.2
multidict           6.0.4
multiprocess        0.70.12.2
numpy               1.26.1
onnx                1.15.0
opencv-python       4.6.0.66
opt-einsum          3.3.0
packaging           23.2
paddle2onnx         1.1.0
paddlefsl           1.1.0
paddlenlp           2.6.1
paddlepaddle        0.0.0
paddleslim          0.0.0.dev0
pandas              2.1.2
Pillow              10.1.0
pip                 23.3
protobuf            3.20.2
psutil              5.9.6
pyarrow             13.0.0
pybind11            2.11.1
pycryptodome        3.19.0
pydantic            2.4.2
pydantic_core       2.10.1
Pygments            2.16.1
pyparsing           3.1.1
python-dateutil     2.8.2
pytz                2023.3.post1
PyYAML              6.0.1
pyzmq               25.1.1
rarfile             4.1
requests            2.31.0
rich                13.6.0
rouge               1.0.1
safetensors         0.4.0
scikit-learn        1.3.2
scipy               1.11.3
sentencepiece       0.1.99
seqeval             1.2.2
setuptools          68.0.0
six                 1.16.0
sniffio             1.3.0
starlette           0.27.0
swig                4.1.1
threadpoolctl       3.2.0
tool-helpers        0.1.1
tqdm                4.66.1
typer               0.9.0
typing_extensions   4.8.0
tzdata              2023.3
urllib3             2.0.7
uvicorn             0.23.2
visualdl            2.5.3
Werkzeug            3.0.1
wheel               0.41.2
xxhash              3.4.1
yarl                1.9.2
zipp                3.17.0

**Comment by DesmonDay** [comment]
我正在尝试看能否复现，稍等

**Comment by DesmonDay** [comment]
![截屏2023-11-01 下午5 09 59](https://github.com/PaddlePaddle/PaddleNLP/assets/20554008/3b0268b5-e3bd-4446-9e7c-a50ddd12f17f)
我这边可以跑通。我们这边推测是由于你实际跑的paddlenlp版本有问题，你可以参考我这样加一个PYTHONPATH来设置paddlenlp版本。

**Comment by gtgtgt1117** [comment]
> ![截屏2023-11-01 下午5 09 59](https://user-images.githubusercontent.com/20554008/279627919-3b0268b5-e3bd-4446-9e7c-a50ddd12f17f.png) 我这边可以跑通。我们这边推测是由于你实际跑的paddlenlp版本有问题，你可以参考我这样加一个PYTHONPATH来设置paddlenlp版本。

好的，非常感谢，paddlenlp更换为develop版本可以跑通

**Comment by gtgtgt1117** [comment]
> ![截屏2023-11-01 下午5 09 59](https://user-images.githubusercontent.com/20554008/279627919-3b0268b5-e3bd-4446-9e7c-a50ddd12f17f.png) 我这边可以跑通。我们这边推测是由于你实际跑的paddlenlp版本有问题，你可以参考我这样加一个PYTHONPATH来设置paddlenlp版本。

是否可以看一下 Ernie3.5转静态图的问题
(paddleslim) root@:~/PaddleNLP/llm# python export_model.py --model_name_or_path ./ernie-3.5-se/ernie-tokenizer/ --output_path ./inference --dtype float32
/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
model_args ModelArgument(model_type=None, data_file=None, output_file='output.json') PredictorArgument(model_name_or_path='./ernie-3.5-se/ernie-tokenizer/', model_prefix='model', src_  length=1024, max_length=2048, top_k=0, top_p=0.7, temperature=0.95, repetition_penalty=1.0, device='gpu', dtype='float32', lora_path=None, export_precache=False, prefix_path=None, dec  ode_strategy='sampling', mode='dynamic', inference_model=False, quant_type='None', batch_size=1, benchmark=False, enable_memory_optim=True, init_fleet_worker=True)
Traceback (most recent call last):
  File "/root/xygao/LLM/PaddleNLP/llm/export_model.py", line 97, in <module>
    main()
  File "/root/xygao/LLM/PaddleNLP/llm/export_model.py", line 81, in main
    predictor = create_predictor(predictor_args, model_args, tensor_parallel_degree, tensor_parallel_rank)
  File "/root/xygao/LLM/PaddleNLP/llm/predictor.py", line 667, in create_predictor
    tokenizer = AutoTokenizer.from_pretrained(predictor_args.model_name_or_path)
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/auto/tokenizer.py", line 341, in from_pretrained
    tokenizer_class = cls._get_tokenizer_class_from_config(
  File "/root/miniconda3/envs/paddleslim/lib/python3.9/site-packages/paddlenlp/transformers/auto/tokenizer.py", line 197, in _get_tokenizer_class_from_config
    class_name = cls._name_mapping[init_class]
KeyError: 'Ernie35Tokenizer'
