### ISSUE TITLE
[Bug]: BLOOM Belle7b模型finetune存在显存泄露问题

### ISSUE THREAD

**Issue by chen-zhiyu** [PaddlePaddle/PaddleNLP#7363]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.5.2.post112
- paddlenlp: 2.6.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
使用finetune_generation.py进行finetune，在完成不到一个epoch都会导致显存泄露
使用标准的belle7b模型，在A100 40G单卡上训练

具体配置如下：
{
    "model_name_or_path": "bellegroup/belle-7b-2m",
    "dataset_name_or_path": "./afs/data/belle7b_2m",
    "output_dir": "./output",
    "per_device_train_batch_size": 4,
    "gradient_accumulation_steps": 4,
    "per_device_eval_batch_size": 4,
    "eval_accumulation_steps":8,
    "num_train_epochs": 16,
    "learning_rate": 3e-05,
    "weight_decay": 0.01,
    "warmup_steps": 30,
    "logging_steps": 10,
    "evaluation_strategy": "epoch",
    "save_strategy": "epoch",
    "src_length": 1024,
    "max_length": 2048,
    "fp16": true,
    "fp16_opt_level": "O2",
    "do_train": true,
    "do_eval": true,
    "disable_tqdm": true,
    "load_best_model_at_end": true,
    "eval_with_do_generation": false,
    "metric_for_best_model": "accuracy",
    "recompute": true,
    "save_total_limit": 1,
    "tensor_parallel_degree": 1,
    "pipeline_parallel_degree": 1,
    "lora": true,
    "lora_rank": 8
  }

错误信息：
[32m[2023-11-02 14:47:52,503] [    INFO][0m - loss: 2.07404957, learning_rate: 1e-05, global_step: 10, interval_runtime: 32.1541, interval_samples_per_second: 4.976032409252679, interval_steps_per_second: 0.31100202557829243, ppl: 7.95698031126018, epoch: 0.0001[0m
[32m[2023-11-02 14:48:19,550] [    INFO][0m - loss: 2.04764957, learning_rate: 2e-05, global_step: 20, interval_runtime: 27.0473, interval_samples_per_second: 5.915554736282556, interval_steps_per_second: 0.36972217101765975, ppl: 7.749664638675427, epoch: 0.0002[0m
[32m[2023-11-02 14:48:54,032] [    INFO][0m - loss: 1.99810467, learning_rate: 3e-05, global_step: 30, interval_runtime: 34.4816, interval_samples_per_second: 4.640160972266738, interval_steps_per_second: 0.29001006076667113, ppl: 7.375064662617582, epoch: 0.0002[0m
[32m[2023-11-02 14:49:26,270] [    INFO][0m - loss: 1.92708473, learning_rate: 3e-05, global_step: 40, interval_runtime: 32.2385, interval_samples_per_second: 4.963003220511881, interval_steps_per_second: 0.3101877012819926, ppl: 6.86945470691259, epoch: 0.0003[0m
[32m[2023-11-02 14:49:51,861] [    INFO][0m - loss: 1.76772423, learning_rate: 3e-05, global_step: 50, interval_runtime: 25.5908, interval_samples_per_second: 6.252255044710063, interval_steps_per_second: 0.39076594029437894, ppl: 5.85750784085584, epoch: 0.0004[0m
[32m[2023-11-02 14:50:19,470] [    INFO][0m - loss: 1.73606091, learning_rate: 3e-05, global_step: 60, interval_runtime: 27.609, interval_samples_per_second: 5.795207809644054, interval_steps_per_second: 0.36220048810275335, ppl: 5.674945217404047, epoch: 0.0005[0m
Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/finetune_generation.py", line 452, in <module>
    main()
  File "/root/paddlejob/workspace/env_run/finetune_generation.py", line 339, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/lib/python3.9/dist-packages/paddlenlp/trainer/trainer.py", line 795, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.9/dist-packages/paddlenlp/trainer/trainer.py", line 1719, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.9/dist-packages/paddlenlp/trainer/trainer.py", line 1672, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.9/dist-packages/paddle/nn/layer/layers.py", line 1343, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddlenlp/transformers/bloom/modeling.py", line 1184, in forward
    lm_logits = self.lm_head(hidden_states, self.config.tensor_parallel_output)
  File "/usr/local/lib/python3.9/dist-packages/paddle/nn/layer/layers.py", line 1343, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddlenlp/transformers/bloom/modeling.py", line 1006, in forward
    logits = parallel_matmul(hidden_states, self.decoder_weight, parallel_output=parallel_output)
  File "/usr/local/lib/python3.9/dist-packages/paddlenlp/transformers/bloom/modeling.py", line 77, in parallel_matmul
    logits = paddle.matmul(x, y, transpose_y=True)
  File "/usr/local/lib/python3.9/dist-packages/paddle/tensor/linalg.py", line 238, in matmul
    return _C_ops.matmul(x, y, transpose_x, transpose_y)
MemoryError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::eager_api_matmul(_object*, _object*, _object*)
1   matmul_ad_func(paddle::Tensor const&, paddle::Tensor const&, bool, bool)
2   matmul_ad_func(paddle::Tensor const&, paddle::Tensor const&, bool, bool)
3   paddle::experimental::matmul(paddle::Tensor const&, paddle::Tensor const&, bool, bool)
4   void phi::MatmulKernel<phi::dtype::float16, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, bool, bool, phi::DenseTensor*)
5   void phi::MatMulFunctionImplWithBlas<phi::GPUContext, phi::dtype::float16>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<long, std::allocator<long> > const&, std::vector<long, std::allocator<long> > const&, phi::DenseTensor*, bool, bool, bool, phi::funcs::MatmulPlanner*)
6   phi::dtype::float16* phi::DeviceContext::Alloc<phi::dtype::float16>(phi::TensorBase*, unsigned long, bool) const
7   phi::DeviceContext::Impl::Alloc(phi::TensorBase*, phi::Place const&, phi::DataType, unsigned long, bool, bool) const
8   phi::DenseTensor::AllocateFrom(phi::Allocator*, phi::DataType, unsigned long, bool)
9   paddle::memory::allocation::Allocator::Allocate(unsigned long)
10  paddle::memory::allocation::StatAllocator::AllocateImpl(unsigned long)
11  paddle::memory::allocation::Allocator::Allocate(unsigned long)
12  paddle::memory::allocation::Allocator::Allocate(unsigned long)
13  paddle::memory::allocation::Allocator::Allocate(unsigned long)
14  paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
15  std::string phi::enforce::GetCompleteTraceBackString<std::string >(std::string&&, char const*, int)
16  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 3.497276GB memory on GPU 0, 36.359375GB memory has been allocated and available memory is only 3.226746GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
 (at ../paddle/fluid/memory/allocation/cuda_allocator.cc:86)

2023-11-02 14:51:03 [ERROR] [/root/paddlejob/run.sh: 380] [start_user_cmd] execute user cmd failed, Thu Nov  2 14:51:03 CST 2023
~/paddlejob/workspace
2023-11-02 14:51:03 [INFO] [/root/paddlejob/run.sh: 325] [start_user_end_hook_process] /root/paddlejob/workspace/lock/prestop_end_hook.lock does not exist, start to generate run_end_hook.lock
~/paddlejob/workspace/env_run ~/paddlejob/workspace
~/paddlejob/workspace
2023-11-02 14:51:03 [INFO] [/root/paddlejob/run.sh: 338] [start_user_end_hook_process] user end_hook finished, start to generate run_end_hook_done.lock
~/paddlejob/workspace ~/paddlejob/workspace
2023-11-02 14:51:03 [INFO] [/root/paddlejob/tools/end_hook.sh: 14] [start_umount_afs] starting umount afs
afs_mount       193P  154P   39P  81% /root/paddlejob/workspace/env_run/afs
start umount afs ...
umount afs success
2023-11-02 14:51:03 [INFO] [/root/paddlejob/tools/end_hook.sh: 21] [start_umount_afs] finished umount afs
2023-11-02 14:51:03 [INFO] [/root/paddlejob/tools/end_hook.sh: 30] [data_clean] data_clear start ...
2023-11-02 14:51:03 [INFO] [/root/paddlejob/tools/end_hook.sh: 32] [data_clean] data_clear end ...
~/paddlejob/workspace
```

### 稳定复现步骤 & 代码

```bash
python finetune_generation.py lora.json
```

lora.json
```json
{
    "model_name_or_path": "bellegroup/belle-7b-2m",
    "dataset_name_or_path": "./afs/data/belle7b_2m",
    "output_dir": "./output",
    "per_device_train_batch_size": 4,
    "gradient_accumulation_steps": 4,
    "per_device_eval_batch_size": 4,
    "eval_accumulation_steps":8,
    "num_train_epochs": 16,
    "learning_rate": 3e-05,
    "weight_decay": 0.01,
    "warmup_steps": 30,
    "logging_steps": 10,
    "evaluation_strategy": "epoch",
    "save_strategy": "epoch",
    "src_length": 1024,
    "max_length": 2048,
    "fp16": true,
    "fp16_opt_level": "O2",
    "do_train": true,
    "do_eval": true,
    "disable_tqdm": true,
    "load_best_model_at_end": true,
    "eval_with_do_generation": false,
    "metric_for_best_model": "accuracy",
    "recompute": true,
    "save_total_limit": 1,
    "tensor_parallel_degree": 1,
    "pipeline_parallel_degree": 1,
    "lora": true,
    "lora_rank": 8
  }
```

**Comment by chen-zhiyu** [comment]
不到60个step就崩溃了，第一个step时，GPU是31G，过了几个step显存就涨到了37G后面就立刻崩溃了~

**Comment by chen-zhiyu** [comment]
paddle 0.0.0/2.5.1/2.5.2 paddlenlp 2.6.0/2.6.1都存在此问题~

**Comment by chen-zhiyu** [comment]
唯一修改了一下字段读取 llm/data.py
```
def tokenize_example(tokenizer, example, data_args):
      if "src" in example and "tgt" in example:
          source = example["src"][0] if isinstance(example["src"], list) else example["src"]
          target = example["tgt"][0] if isinstance(example["tgt"], list) else example["tgt"]
      elif "instruction" in example and "output" in example:
          source = example["instruction"]
          target = example["output"]
      else:
          raise DataFormatError(
              f"Example format is wrong, please check: {example} or rewrite tokenize_example in data.py "
          )
```

**Comment by chen-zhiyu** [comment]
数据集是：https://huggingface.co/datasets/BelleGroup/train_2M_CN

**Comment by guoshengCS** [comment]
试了下这个不是泄露了，是belle-2m那个数据集里有比较长的显存占用超过咱们机器的40G了，可以先调小下src_length和max_length吧，改成1024的显存稳定在不到30G
