### ISSUE TITLE
[Question]: 运行LLM显示ModuleNotFoundError: No module named 'paddlenlp_ops'

### ISSUE THREAD

**Issue by Fordacre** [PaddlePaddle/PaddleNLP#7378]
### 请提出你的问题

在使用LLM时，执行命令：
```
python predictor.py \
    --model_name_or_path meta-llama/Llama-2-7b-chat \
    --dtype float16 \
    --max_length 1024 \
    --mode "dynamic" \
    --inference_model
```
显示错误：
```
Traceback (most recent call last):
  File "predictor.py", line 669, in <module>
    predict()
  File "predictor.py", line 635, in predict
    predictor = create_predictor(predictor_args, model_args)
  File "predictor.py", line 567, in create_predictor
    from paddlenlp.experimental.transformers import (
  File "/usr/local/lib/python3.8/site-packages/paddlenlp/experimental/transformers/__init__.py", line 15, in <module>
    from .bloom import *
  File "/usr/local/lib/python3.8/site-packages/paddlenlp/experimental/transformers/bloom/__init__.py", line 15, in <module>
    from .modeling import *
  File "/usr/local/lib/python3.8/site-packages/paddlenlp/experimental/transformers/bloom/modeling.py", line 21, in <module>
    from paddlenlp_ops import get_padding_offset
ModuleNotFoundError: No module named 'paddlenlp_ops'
```
环境：
paddle2.5.2
paddlenlp2.6.1
麻烦帮忙看看是什么原因导致的呢。

**Comment by DesmonDay** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/csrc 到这个目录下，根据readme来安装

**Comment by Fordacre** [comment]
@DesmonDay 安装失败了，帮忙看看什么原因呢。之前没安装csrc跑成功过一次，后面就不行了，是环境问题么。这个和cuda还有gpu有关系么。
```
/usr/local/lib/python3.8/site-packages/setuptools_scm/integration.py:17: RuntimeWarning:
ERROR: setuptools==41.2.0 is used in combination with setuptools_scm>=6.x

Your build configuration is incomplete and previously worked by accident!


This happens as setuptools is unable to replace itself when a activated build dependency
requires a more recent setuptools version
(it does not respect "setuptools>X" in setup_requires).


setuptools>=31 is required for setup.cfg metadata support
setuptools>=42 is required for pyproject.toml configuration support

Suggested workarounds if applicable:
 - preinstalling build dependencies like setuptools_scm before running setup.py
 - installing setuptools_scm using the system package manager to ensure consistency
 - migrating from the deprecated setup_requires mechanism to pep517/518
   and using a pyproject.toml to declare build dependencies
   which are reliably pre-installed before running the build tools

  warnings.warn(
running install
/usr/local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing paddlenlp_ops.egg-info/PKG-INFO
writing dependency_links to paddlenlp_ops.egg-info/dependency_links.txt
writing top-level names to paddlenlp_ops.egg-info/top_level.txt
listing git files failed - pretending there aren't any
reading manifest file 'paddlenlp_ops.egg-info/SOURCES.txt'
writing manifest file 'paddlenlp_ops.egg-info/SOURCES.txt'
installing library code to build/paddlenlp_ops/bdist.linux-x86_64/egg
running install_lib
running build_ext
Compiling user custom op, it will cost a few seconds.....
building 'paddlenlp_ops' extension
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.8/site-packages/paddle/include -I/usr/local/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda/include -I/usr/local/include/python3.8 -I/usr/local/include/python3.8 -c /ssd3/jincece/workspace/baidu/kg-base/gen-kg/model_train/PaddleNLP-release-2.6/csrc/generation/encode_rotary_qk.cu -o /ssd3/jincece/workspace/baidu/kg-base/gen-kg/model_train/PaddleNLP-release-2.6/csrc/build/paddlenlp_ops/lib.linux-x86_64-cpython-38/encode_rotary_qk.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
In file included from /ssd3/jincece/workspace/baidu/kg-base/gen-kg/model_train/PaddleNLP-release-2.6/csrc/generation/encode_rotary_qk.cu:15:
/ssd3/jincece/workspace/baidu/kg-base/gen-kg/model_train/PaddleNLP-release-2.6/csrc/generation/helper.h:18:10: fatal error: cub/cub.cuh: No such file or directory
 #include <cub/cub.cuh>
          ^~~~~~~~~~~~~
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1
```

**Comment by DesmonDay** [comment]
你跑通的环境和现在的是同一个么，也可能你之前跑通的版本没有加inference_model参数。这个和环境有关，先确认paddle和GPU是可用的，简单测试一下。

**Comment by Fordacre** [comment]
确实是inference_model参数的差异。inference_model参数是infer加速使用的么，训练会有同样的问题么。
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/12699033/cad15285-5cfd-4255-90f8-2f6cfe16f3f0)

**Comment by DesmonDay** [comment]
这块只有推理的时候会用，训练不会用。

**Comment by Fordacre** [comment]
okay，多谢。
