### ISSUE TITLE
NLP finetune时提示错误

### ISSUE THREAD

**Issue by heyuqi1970** [PaddlePaddle/PaddleNLP#7463]
### 请提出你的问题

在做uie-x的finetune时提示错误：

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 256, in __getitem__
    return self._transform(self.new_data[idx]) if self._transform_pipline else self.new_data[idx]
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 248, in _transform
    data = fn(data)
  File "/home/aistudio/utils.py", line 156, in convert_example
    c_sep_index = attention_mask.index(0)
ValueError: 0 is not in list
```

>

**Comment by heyuqi1970** [comment]
这是不是在数据分割时，encode没有补0？
有没有哪位能给解释一下

**Comment by ajialala** [comment]
同问
