### ISSUE TITLE
PaddleNLP/ examples / dialogue / unified_transformer / interaction.py 在win10,py3.7，paddle相关包都是最新版本，运行报错

### ISSUE THREAD

**Issue by timohaha** [PaddlePaddle/PaddleNLP#751]
我的环境是win10+python3.7+PaddleNLP 2.0.5，PaddlePaddle2.1.1
在复现问答系统unified_transformer中interaction.py时，代码报错，错误代码如下：
`
[2021-07-15 10:34:09,523] [    INFO] - Already cached C:\Users\Administrator\.paddlenlp\models\plato-mini\plato-mini.pdparams
W0715 10:34:09.525503 13588 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.1, Runtime API Version: 10.1

W0715 10:34:09.531487 13588 device_context.cc:422] device: 0, cuDNN Version: 7.6.

[2021-07-15 10:34:13,912] [    INFO] - Found C:\Users\Administrator\.paddlenlp\models\plato-mini\plato-mini-vocab.txt

[2021-07-15 10:34:13,928] [    INFO] - Found C:\Users\Administrator\.paddlenlp\models\plato-mini\plato-mini-spm.model

Enter [EXIT] to quit the interaction, [NEXT] to start a new conversation.

[1m[31m[Human]: [0m我饿了

Building prefix dict from the default dictionary ...

Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache

Loading model cost 0.522 seconds.

Prefix dict has been built successfully.

Traceback (most recent call last):
  File "interaction.py", line 101, in <module>
    main(args)
  File "interaction.py", line 95, in main
    interaction(args, model, tokenizer)
  File "interaction.py", line 65, in interaction
    num_return_sequences=args.num_return_sequences)
  File "<decorator-gen-270>", line 2, in generate
  File "H:\anaconda\envs\pei\lib\site-packages\paddle\fluid\dygraph\base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "H:\anaconda\envs\pei\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 620, in generate
    temperature, **model_kwargs)
  File "H:\anaconda\envs\pei\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 793, in sample
    input_ids = paddle.concat([input_ids, next_tokens], axis=1)
  File "H:\anaconda\envs\pei\lib\site-packages\paddle\tensor\manipulation.py", line 121, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
  File "H:\anaconda\envs\pei\lib\site-packages\paddle\fluid\layers\tensor.py", line 307, in concat
    return core.ops.concat(input, 'axis', axis)

ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int64_t, but desires to be int.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at C:\home\workspace\Paddle_release2\paddle/fluid/framework/tensor_impl.h:33)
  [operator < concat > error]
`
这个问题应该如何解决，感谢。

**Comment by ZeyuChen** [comment]
@timohaha 请clone下最新代码尝试下，我们解决了一些windows不兼容的问题。

**Comment by timohaha** [comment]
> @timohaha 请clone下最新代码尝试下，我们解决了一些windows不兼容的问题。

谢谢，程序复现成功。
