### ISSUE TITLE
以单机多卡形式运行，from_pretrained出错

### ISSUE THREAD

**Issue by Junshuai-Song** [PaddlePaddle/PaddleNLP#756]
版本：paddlenlp 2.0.5

test_connection.py文件内容：
import paddlenlp as ppnlp
tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')

命令：python -m paddle.distributed.launch test_connection.py

报错信息：
[2021-07-15 18:06:21,923] [    INFO] - Downloading vocab.txt from https://paddlenlp.bj.bcebos.com/models/transformers/ernie/vocab.txt
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/root/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/root/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/root/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/root/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5248ec050>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='paddlenlp.bj.bcebos.com', port=443): Max retries exceeded with url: /models/transformers/ernie/vocab.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5248ec050>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_connection.py", line 2, in <module>
    tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')
  File "/root/anaconda3/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 465, in from_pretrained
    None)
  File "/root/anaconda3/lib/python3.7/site-packages/paddlenlp/utils/downloader.py", line 162, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "/root/anaconda3/lib/python3.7/site-packages/paddlenlp/utils/downloader.py", line 196, in _download
    req = requests.get(url, stream=True)
  File "/root/anaconda3/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='paddlenlp.bj.bcebos.com', port=443): Max retries exceeded with url: /models/transformers/ernie/vocab.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5248ec050>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
INFO 2021-07-15 18:06:26,775 launch_utils.py:327] terminate all the procs
ERROR 2021-07-15 18:06:26,776 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-07-15 18:06:29,779 launch_utils.py:327] terminate all the procs

**Comment by Junshuai-Song** [comment]
如果有预下载的vocab.txt文件，需要先删除

**Comment by wawltor** [comment]
> 如果有预下载的vocab.txt文件，需要先删除

请问一下，因为看报错的话是网络有问题，删除vocab.txt就能正常下载？

**Comment by wawltor** [comment]
> > 如果有预下载的vocab.txt文件，需要先删除
> 
> 请问一下，因为看报错的话是网络有问题，想问一下 删除vocab.txt就能正常下载？

**Comment by Junshuai-Song** [comment]
@wawltor 
不是 上面说到“删除vocab.txt”只是为了复现我遇到的问题。

我这里本地环境第一次运行上述代码，即需要从网上下载vocab.txt文件时，会报上述错误；如果预先下载的有vocab.txt，默认会跳过download过程，就不会报错了

**Comment by Junshuai-Song** [comment]
以单机多卡模式运行才会报上述错误，即运行命令为：python -m paddle.distributed.launch test_connection.py

如果直接python test_connection.py，我这里没有报错。

所以猜测可能为单机多卡模式下的问题。

**Comment by wawltor** [comment]
> 以单机多卡模式运行才会报上述错误，即运行命令为：python -m paddle.distributed.launch test_connection.py
> 
> 如果直接python test_connection.py，我这里没有报错。
> 
> 所以猜测可能为单机多卡模式下的问题。

我在自己的机器上没有复现这个问题，请问一下，您的环境是windows环境吗？

**Comment by Junshuai-Song** [comment]
> > 以单机多卡模式运行才会报上述错误，即运行命令为：python -m paddle.distributed.launch test_connection.py
> > 如果直接python test_connection.py，我这里没有报错。
> > 所以猜测可能为单机多卡模式下的问题。
> 
> 我在自己的机器上没有复现这个问题，请问一下，您的环境是windows环境吗？

我是linux环境，CentOS 7.2

**Comment by wawltor** [comment]
> > > 以单机多卡模式运行才会报上述错误，即运行命令为：python -m paddle.distributed.launch test_connection.py
> > > 如果直接python test_connection.py，我这里没有报错。
> > > 所以猜测可能为单机多卡模式下的问题。
> > 
> > 
> > 我在自己的机器上没有复现这个问题，请问一下，您的环境是windows环境吗？
> 
> 我是linux环境，CentOS 7.2

麻烦再提供一下PaddlePaddle的版本

**Comment by Junshuai-Song** [comment]
> > > > 以单机多卡模式运行才会报上述错误，即运行命令为：python -m paddle.distributed.launch test_connection.py
> > > > 如果直接python test_connection.py，我这里没有报错。
> > > > 所以猜测可能为单机多卡模式下的问题。
> > > 
> > > 
> > > 我在自己的机器上没有复现这个问题，请问一下，您的环境是windows环境吗？
> > 
> > 
> > 我是linux环境，CentOS 7.2
> 
> 麻烦再提供一下PaddlePaddle的版本

paddlepaddle-gpu==2.1.1.post101

**Comment by wawltor** [comment]
抱歉 我们这边在内部的多个机器上和云上的机器都没有复现您的问题，可能还是和设备的网络连接有一定的关系

**Comment by Junshuai-Song** [comment]
> 抱歉 我们这边在内部的多个机器上和云上的机器都没有复现您的问题，可能还是和设备的网络连接有一定的关系

好的  暂时的解决方式就是先单卡运行一遍保证数据已下载。
那我先close，感谢回复！

**Comment by zhangluustb** [comment]
下载数据、pretrain模型等都需要网络连接，没网络的情况下，可以先下载好数据和权重，采用 -o pretrain_weights=your_pdparams 的方式训练
