### ISSUE TITLE
[Question]: 微调chatglm2-6b报错module 'paddlenlp.transformers.chatglm_v2.modeling' has no attribute 'ChatGLMv2ForConditionalGeneration'

### ISSUE THREAD

**Issue by anchorone** [PaddlePaddle/PaddleNLP#7572]
### 请提出你的问题

在ai studio上用paddlenlp-2.6.1的源码的 llm/glm/finetune_generation.py 文件进行chatglm2-6b模型微调测试，但多次出现找不到ChatGLMv2ForConditionalGeneration类的报错，找了好多信息还是没有解决。部分信息如下：

部分环境信息如下：
```
paddlenlp                  2.6.1.post0
paddlepaddle-gpu           2.5.2
```

测试代码信息：
```
!pip uninstall paddlenlp -y
# !unzip PaddleNLP-2.6.0.zip
!cd /home/aistudio/PaddleNLP-2.6.1/
!pip install  -e . 
```
```
py_path = '/home/aistudio/PaddleNLP-2.6.1/llm/glm'
%cd $py_path

!python finetune_generation.py \
--model_name_or_path /home/aistudio/.paddlenlp/models/THUDM/chatglm2-6b \
--output_dir /home/aistudio/chatglm2-lora \
--task_name /home/aistudio/data/data250175 \
--per_device_eval_batch_size 1 \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 1\
--eval_accumulation_steps 1\
--num_train_epochs 3\
--learning_rate 3e-04 \
--warmup_ratio 0.06 \
--warmup_steps 30\
--weight_decay 0.1 \
--label_smoothing 0.1 \
--save_steps 100 \
--logging_steps 1 \
--eval_steps 100 \
--src_length 1024 \
--tgt_length 1024 \
--min_tgt_length 55 \
--length_penalty 0.7 \
--no_repeat_ngram_size 3 \
--num_beams 5 \
--select_topk True \
--max_grad_norm 1.0 \
--lr_scheduler_type linear \
--evaluation_strategy epoch \
--save_strategy epoch \
--disable_tqdm True \
--load_best_model_at_end True \
--metric_for_best_model accuracy \
--save_total_limit 1 \
--tensor_parallel_degree 1\
--pipeline_parallel_degree 1\
--fp16 \
--fp16_opt_level O2 \
--recompute \
--do_train \
--do_eval \
--lora True
```

在飞浆平台上微调模型的时候报错，找不到ChatGLMv2ForConditionalGeneration这个类。报错信息如下：
```
[2023-12-03 21:15:33,953] [   ERROR] - module 'paddlenlp.transformers.chatglm_v2.modeling' has no attribute 'ChatGLMv2ForConditionalGeneration'
Traceback (most recent call last):
  File "/home/aistudio/.local/lib/python3.10/site-packages/paddlenlp-2.6.1.post0-py3.10.egg/paddlenlp/transformers/auto/modeling.py", line 243, in _get_model_class_from_config
    model_class = getattr(import_class, init_class)
AttributeError: module 'paddlenlp.transformers.chatglm_v2.modeling' has no attribute 'ChatGLMv2ForConditionalGeneration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aistudio/PaddleNLP-2.6.1/llm/glm/finetune_generation.py", line 189, in <module>
    main()
  File "/home/aistudio/PaddleNLP-2.6.1/llm/glm/finetune_generation.py", line 108, in main
    model = AutoModelForConditionalGeneration.from_pretrained(
  File "/home/aistudio/.local/lib/python3.10/site-packages/paddlenlp-2.6.1.post0-py3.10.egg/paddlenlp/transformers/auto/modeling.py", line 1040, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home/aistudio/.local/lib/python3.10/site-packages/paddlenlp-2.6.1.post0-py3.10.egg/paddlenlp/transformers/auto/modeling.py", line 334, in _from_pretrained
    model_class = cls._get_model_class_from_config(pretrained_model_name_or_path, config_file)
  File "/home/aistudio/.local/lib/python3.10/site-packages/paddlenlp-2.6.1.post0-py3.10.egg/paddlenlp/transformers/auto/modeling.py", line 249, in _get_model_class_from_config
    raise AttributeError(
AttributeError: module 'paddlenlp.transformers.chatglm_v2.modeling' only supports the following classes: ChatGLMv2Model, ChatGLMv2PretrainedModel, ChatGLMv2ForCausalLM
Hint: you can use interface AutoModel.from_pretrained or AutoModelForCausalLM.from_pretrained to load '/home/aistudio/.paddlenlp/models/THUDM/chatglm2-6b'
```
有大佬知道如何解决吗， (;﹏;)

**Comment by sijunhe** [comment]
`ChatGLMv2ForConditionalGeneration`这个类早就改成`ChatGLMv2ForCausalLM `了。估计是你那边的代码比较老.
比如你报错信息里面的
```
File "/home/aistudio/PaddleNLP-2.6.1/llm/glm/finetune_generation.py", line 108, in main
    model = AutoModelForConditionalGeneration.from_pretrained(
```
这一段，当前 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/finetune_generation.py 是没有的

**Comment by Anchorone** [comment]
> `ChatGLMv2ForConditionalGeneration`这个类早就改成`ChatGLMv2ForCausalLM `了。估计是你那边的代码比较老. 比如你报错信息里面的
> 
> ```
> File "/home/aistudio/PaddleNLP-2.6.1/llm/glm/finetune_generation.py", line 108, in main
>     model = AutoModelForConditionalGeneration.from_pretrained(
> ```
> 
> 这一段，当前 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/finetune_generation.py 是没有的

**Comment by anchorone** [comment]
> `ChatGLMv2ForConditionalGeneration`这个类早就改成`ChatGLMv2ForCausalLM `了。估计是你那边的代码比较老. 比如你报错信息里面的
> 
> ```
> File "/home/aistudio/PaddleNLP-2.6.1/llm/glm/finetune_generation.py", line 108, in main
>     model = AutoModelForConditionalGeneration.from_pretrained(
> ```
> 
> 这一段，当前 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/finetune_generation.py 是没有的

对，这也是我疑惑的，`ChatGLMv2ForConditionalGeneration`在我使用的paddlenlp-2.6.1版中已经被`ChatGLMv2ForCausalLM `替换了。但在使用源码的`llm/glm/`目录下的`finetune_generation.py `文件还是会出现找不到`ChatGLMv2ForConditionalGeneration`的报错。不知道之前我是不是使用错了文件，今天我用`llm/`目录下的`finetune_generation.py`进行微调测试的时候就能跑通。

此外，`AutoModelForConditionalGeneration`这个类在paddlenlp-2.6.1源码的`llm/glm/`目录下的`finetune_generation.py`文件还是有使用的。

**Comment by sijunhe** [comment]
> 此外，`AutoModelForConditionalGeneration`这个类在paddlenlp-2.6.1源码的`llm/glm/`目录下的`finetune_generation.py`文件还是有使用的。

这个确实是有些歧义。GLM和ChatGLM不是同一个模型。`llm/glm/`这个目录下的是给老的GLM(比如THUDM/glm-10b-chinese)用的。ChatGLM直接用`llm/finetune_generation.py`即可
