### ISSUE TITLE
[Bug]:  使用 PaddleNLP/llm/inference.md 安装推理优化，运行时报错 cannot import name 'top_p_sampling' from 'paddlenlp_ops'

### ISSUE THREAD

**Issue by Eric-github1** [PaddlePaddle/PaddleNLP#7666]
### 软件环境

```Markdown
- paddlepaddle: 0.0.0
- paddlepaddle-gpu: 0.0.0.post118
- paddlenlp: 2.6.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
PredictorArgument(model_name_or_path='./models/inference_model', model_prefix='model', src_length=2048, max_length=4096, top_k=1, top_p=1.0, temperature=0.95, repetition_penalty=1.3, device='gpu', dtype='float16', lora_path=None, prefix_path=None, decode_strategy='sampling', mode='dynamic', inference_model=True, batch_size=1, max_batch_size=None)
ModelArgument(gpt=False, ernie=False, data_file=None, output_file='output.json')

Traceback (most recent call last):
  File "/home/work/liyuchou/deploy/pd_llama2_pd_develop/models/env/lib/python3.9/site-packages/paddlenlp/experimental/transformers/generation_utils.py", line 32, in <module>
    from paddle import top_p_sampling
ImportError: cannot import name 'top_p_sampling' from 'paddle' (/home/work/liyuchou/deploy/pd_llama2_pd_develop/models/env/lib/python3.9/site-packages/paddle/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/work/liyuchou/deploy/pd_llama2_pd_develop/predictor.py", line 676, in <module>
    predictor = create_predictor(predictor_args, model_args)
  File "/home/work/liyuchou/deploy/pd_llama2_pd_develop/predictor.py", line 567, in create_predictor
    from paddlenlp.experimental.transformers import (
  File "/home/work/liyuchou/deploy/pd_llama2_pd_develop/models/env/lib/python3.9/site-packages/paddlenlp/experimental/transformers/__init__.py", line 15, in <module>
    from .bloom import *
  File "/home/work/liyuchou/deploy/pd_llama2_pd_develop/models/env/lib/python3.9/site-packages/paddlenlp/experimental/transformers/bloom/__init__.py", line 15, in <module>
    from .modeling import *
  File "/home/work/liyuchou/deploy/pd_llama2_pd_develop/models/env/lib/python3.9/site-packages/paddlenlp/experimental/transformers/bloom/modeling.py", line 26, in <module>
    from paddlenlp.experimental.transformers.generation_utils import (
  File "/home/work/liyuchou/deploy/pd_llama2_pd_develop/models/env/lib/python3.9/site-packages/paddlenlp/experimental/transformers/generation_utils.py", line 34, in <module>
    from paddlenlp_ops import top_p_sampling
ImportError: cannot import name 'top_p_sampling' from 'paddlenlp_ops' (/home/work/liyuchou/deploy/pd_llama2_pd_develop/models/env/lib/python3.9/site-packages/paddlenlp_ops-0.0.0-py3.9-linux-x86_64.egg/paddlenlp_ops.py)
```

### 稳定复现步骤 & 代码

(已配置 "inference_model": true)
python predictor.py

**Comment by Xiaopu17** [comment]
请问一下, csrc中的编译cuda算子生成paddlenlp_ops库部分，作者用的什么版本的cuda以及相关库，我现在用的cuda:11.6， nvcc:11.6，python3.9.18，paddlepaddle-gpu.0.0.0.post116, paddlenlp 2.6.1.post0，没有生成成功，尝试了好多种办法

**Comment by w5688414** [comment]
请问是什么类型的显卡，现在适配的都是A100系列的显卡

**Comment by w5688414** [comment]
推荐使用paddle的docker先跑通：

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html
