### ISSUE TITLE
[Question]: 加载预训练模型出错

### ISSUE THREAD

**Issue by lznext** [PaddlePaddle/PaddleNLP#7685]
### 请提出你的问题

paddlenlp            2.5.0
paddlepaddle         2.5.2
paddlepaddle-gpu     2.5.1.post120
cuda V12.0.140
对于项目https://aistudio.baidu.com/projectdetail/7285982 的main.ipynb，执行!python evaluate.py \
    --model_path ./checkpoint/model_best \
    --test_path ./data/dev.txt \
    --batch_size 8 \
    --max_seq_len 256。报错信息如下C:\ProgramData\anaconda3\envs\py37\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "evaluate.py", line 8, in <module>
    from paddlenlp.datasets import load_dataset, MapDataset
  File "C:\ProgramData\anaconda3\envs\py37\lib\site-packages\paddlenlp\__init__.py", line 29, in <module>
    from . import (
  File "C:\ProgramData\anaconda3\envs\py37\lib\site-packages\paddlenlp\data\__init__.py", line 16, in <module>
    from .data_collator import *
  File "C:\ProgramData\anaconda3\envs\py37\lib\site-packages\paddlenlp\data\data_collator.py", line 23, in <module>
    from ..transformers.tokenizer_utils_base import BatchEncoding, PretrainedTokenizerBase, PaddingStrategy
  File "C:\ProgramData\anaconda3\envs\py37\lib\site-packages\paddlenlp\transformers\__init__.py", line 17, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "C:\ProgramData\anaconda3\envs\py37\lib\site-packages\paddlenlp\transformers\model_utils.py", line 66, in <module>
    from .generation_utils import GenerationMixin
  File "C:\ProgramData\anaconda3\envs\py37\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 24, in <module>
    from paddle.fluid.layers.utils import map_structure
ModuleNotFoundError: No module named 'paddle.fluid.layers.utils'
改用最新版本的paddlenlp 2.6.1，执行同样命令，报错C:\ProgramData\anaconda3\envs\py37\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-12-20 11:54:00,847] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load './checkpoint/model_best'.
Traceback (most recent call last):
  File "evaluate.py", line 95, in <module>
    do_eval()
  File "evaluate.py", line 44, in do_eval
    model = UIE.from_pretrained(args.model_path)
AttributeError: type object 'UIE' has no attribute 'from_pretrained'.请问各位大佬如何解决

**Comment by lznext** [comment]
这个项目https://aistudio.baidu.com/projectdetail/7285982 的代码太老了，换了[PaddleNLP](https://github.com/PaddlePaddle/PaddleNLP)的uie代码，训练成功了。问题解决。
可参考：https://zhuanlan.zhihu.com/p/623996244
