### ISSUE TITLE
[Bug]: FileNotFoundError: configuration file<config.json> or <model_config.json> not found

### ISSUE THREAD

**Issue by WanfuVictor** [PaddlePaddle/PaddleNLP#7698]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.5.2.post120
- paddlenlp: 2.6.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
原来的环境都是稳定版的。windows11环境下，照着信息抽取模型微调的例子做的。个人数据用label-studio做的标注，能够执行label-studio.py进行生成数据集。在paddlenlp/application/document执行的命令。
启动训练的时候，就报错没有配置文件。

document目录下的finetune.py执行就会报缺配置文件的错，在回复底部有样例，但是用model_zoo/uie/finetune.py或者text/finetune.py去执行又不会报缺配置文件。--model_name_or_path uie-base的uie-base换成uie-x-uie也不会报错。

执行命令：
python finetune.py --device gpu --logging_steps 10 --save_steps 100 --eval_steps 100 --seed 1000 --model_name_or_path uie-base --output_dir ./checkpoint/model_best --train_path data/train.txt --dev_path data/dev.txt --max_seq_len 512 --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --num_train_epochs 20 --learning_rate 1e-5 --do_train --do_eval --do_export --export_model_dir ./checkpoint/model_best --overwrite_output_dir --disable_tqdm True --metric_for_best_model eval_f1 --load_best_model_at_end True --save_total_limit 1

报错信息：
[2023-12-21 16:15:52,459] [ WARNING] - Process rank: -1, device: gpu, world_size: 1, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "D:\Games\codeSource\PaddleNLP\applications\information_extraction\document\finetune.py", line 177, in <module>
    main()
  File "D:\Games\codeSource\PaddleNLP\applications\information_extraction\document\finetune.py", line 111, in main
    model = UIEX.from_pretrained(model_args.model_name_or_path)
  File "C:\Python310\lib\site-packages\paddlenlp\transformers\model_utils.py", line 1894, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "C:\Python310\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 749, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Python310\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 775, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(
  File "C:\Python310\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 850, in _get_config_dict
    raise FileNotFoundError(f"configuration file<{CONFIG_NAME}> or <{LEGACY_CONFIG_NAME}> not found")
FileNotFoundError: configuration file<config.json> or <model_config.json> not found
```

### 稳定复现步骤 & 代码

- paddlepaddle-gpu: 2.5.2.post120
- paddlenlp: 2.6.1

paddlenlp/application/document/finetune.py

python finetune.py --device gpu --logging_steps 10 --save_steps 100 --eval_steps 100 --seed 1000 --model_name_or_path uie-base --output_dir ./checkpoint/model_best --train_path data/train.txt --dev_path data/dev.txt --max_seq_len 512 --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --num_train_epochs 20 --learning_rate 1e-5 --do_train --do_eval --do_export --export_model_dir ./checkpoint/model_best --overwrite_output_dir --disable_tqdm True --metric_for_best_model eval_f1 --load_best_model_at_end True --save_total_limit 1

**Comment by WanfuVictor** [comment]
眼花看错了。不好意思
