### ISSUE TITLE
[Bug]: 语义检索BUGFailed to import 'Milvus2DocumentStore', which is an optional component in pipelines.

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#7706]
### 软件环境

```Markdown
- paddlepaddle:2.5.2
- paddlepaddle-gpu: 
- paddlenlp: 2.6.0rc0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "utils/offline_ann.py", line 241, in <module>
    delete_data(args.index_name)
  File "utils/offline_ann.py", line 159, in delete_data
    document_store = MilvusDocumentStore(
  File "/root/anaconda3/envs/paddlenlp_2.6.0_test/lib/python3.8/site-packages/pipelines/utils/import_utils.py", line 54, in __init__
    _optional_component_not_installed(classname, dep_group, import_error)
  File "/root/anaconda3/envs/paddlenlp_2.6.0_test/lib/python3.8/site-packages/pipelines/utils/import_utils.py", line 63, in _optional_component_not_installed
    raise ImportError(
ImportError: Failed to import 'Milvus2DocumentStore', which is an optional component in pipelines.

之前安装的还好的的，后面新拉分支下来都报这个错误
```
通过打印查看加载模块发现就Milvus2DocumentStore不存在
```
dict_keys(['AnswerExtractor', 'AnswerExtractorPreprocessor', 'QAFilter', 'QAFilterPostprocessor', 'DocOCRProcessor', 'DocPrompter', 'FileTypeClassifier', 'BaseConverter', 'MarkdownConverter', 'MarkdownRawTextConverter', 'ImageToTextCon
verter', 'PDFToTextConverter', 'PDFToTextOCRConverter', 'DocxToTextConverter', 'DocxTotxtConverter', 'TextConverter', 'ChatGLMBot', 'ErnieBot', 'TruncatedConversationHistory', 'LLMPromptTemplate', 'Docs2Answers', 'JoinDocuments', 'Rout
eDocuments', 'JoinAnswers', 'BasePreProcessor', 'PreProcessor', 'TextSplitter', 'CharacterTextSplitter', 'RecursiveCharacterTextSplitter', 'SpacyTextSplitter', 'MarkdownHeaderTextSplitter', 'ChatGLMInvocationLayer', 'ErnieBotInvocation
Layer', 'PromptModel', 'Shaper', 'BaseOutputParser', 'AnswerParser', 'BasePromptTemplate', 'PromptTemplate', 'PromptNode', 'QuestionGenerator', 'BaseRanker', 'ErnieRanker', 'BaseReader', 'BaseKnowledgeGraph', 'BaseDocumentStore', 'Keyw
ordDocumentStore', 'ElasticsearchDocumentStore', 'OpenSearchDocumentStore', 'OpenDistroElasticsearchDocumentStore', 'BaiduElasticsearchDocumentStore', 'ErnieReader', 'BaseGraphRetriever', 'BaseRetriever', 'DensePassageRetriever', 'Dens
eRetriever', 'EmbeddingRetriever', 'MultiModalRetriever', 'ParallelRetriever', 'BM25Retriever', 'WebSearch', 'WebRetriever', 'UIESenta', 'SentaProcessor', 'SentaVisualization', 'ErnieTextToImageGenerator', 'SQLDocumentStore', 'RootNode
', 'SampleComponent'])
```

### 稳定复现步骤 & 代码

python utils/offline_ann.py --index_name dureader_index --doc_dir data/data_new_dt  --query_embedding_model rocketqa-zh-nano-query-encoder --passage_embedding_model rocketqa-zh-nano-para-encoder --embedding_dim 312 --delete_index --search_engine milvus --device cpu

**Comment by seetimee** [comment]
请问这个解决了吗
