### ISSUE TITLE
[Question]: 使用ernie-ctm进行ner自定义训练时报错，ErnieCtmWordtagModel对应shape不匹配

### ISSUE THREAD

**Issue by yuhao0926** [PaddlePaddle/PaddleNLP#7786]
### 在tags不一致的情况下，该如何自主训练？

报错日志：
```
Traceback (most recent call last):
  File "./ner/ernie-ctm/train.py", line 203, in <module>
    do_train(args)
  File "./ner/ernie-ctm/train.py", line 104, in do_train
    model = ErnieCtmWordtagModel.from_pretrained("wordtag", num_labels=len(tags_to_idx))
  File "/usr/local/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py", line 2000, in from_pretrained
    model, missing_keys, unexpected_keys, mismatched_keys = cls._load_pretrained_model(
  File "/usr/local/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py", line 1760, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for ErnieCtmWordtagModel:
	Skip loading for tag_classifier.weight. tag_classifier.weight receives a shape [768, 369], but the expected shape is [768, 37].
	Skip loading for tag_classifier.bias. tag_classifier.bias receives a shape [369], but the expected shape is [37].
	Skip loading for crf.transitions. crf.transitions receives a shape [369, 369], but the expected shape is [37, 37].
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

由于我的自定义tags文件和预训练的数据不一样，所以我能够理解这个报错的来源
然后我按照提示，在train.py和predict.py对应的行增加了ignore_mismatched_sizes=True，就可以正常进行
但是最后的预测数据十分不准确，请问在自定义tags的情况下，应当如何进行训练？我在文档中没有找到对应的说明，谢谢！

**Comment by w5688414** [comment]
模型的tags数固定了，可以试一下这个：

```
ErnieCtmWordtagModel.from_pretrained("wordtag",num_labels=369)
```

<img width="886" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/12107462/79aec76d-8589-4182-b164-fb67c1b3abad">
