### ISSUE TITLE
TypeError: LoRAConfig.__init__() got an unexpected keyword argument 'do_qat'[Question]: 

### ISSUE THREAD

**Issue by 111wukong** [PaddlePaddle/PaddleNLP#7791]
### 请提出你的问题

Generating train split: 206 examples [00:00, 50584.08 examples/s]
Traceback (most recent call last):
  File "/home/aistudio/PaddleNLP/llm/finetune_generation.py", line 626, in <module>
    main()
  File "/home/aistudio/PaddleNLP/llm/finetune_generation.py", line 412, in main
    lora_config = LoRAConfig(
TypeError: LoRAConfig.__init__() got an unexpected keyword argument 'do_qat'

**Comment by lugimzzz** [comment]
安装develop的paddlenlp版本可以解决这个问题
