### ISSUE TITLE
[Bug]: CCKS 2022 通用信息抽取 -- 基于UIE的基线系统

### ISSUE THREAD

**Issue by Snailser** [PaddlePaddle/PaddleNLP#7799]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
在模型训练过程中，先报错：AssertionError: bos_token_id has to be defined. In T5 it is usually set to the pad_token_id. See T5 docs for more information
解决：在run_seq2struct.py中添加一行 model.config.bos_token_id = model.config.pad_token_id

之后又报错：
```python
[2024-01-08 20:14:15,953] [    INFO] run_seq2struct.py:380 -   Total optimization steps = 25440
Exception in thread Thread-2:
Traceback (most recent call last):
  File "H:\SunJF\envs\uie_paddle\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "H:\SunJF\envs\uie_paddle\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddle\io\dataloader\dataloader_iter.py", line 235, in _thread_loop
    batch = self._dataset_fetcher.fetch(
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddle\io\dataloader\fetcher.py", line 85, in fetch
    data = self.collate_fn(data)
  File "H:\SunJF\data\pycharm\DuUIE\uie\seq2struct\data_collator.py", line 502, in __call__
    decoder_input_ids = self.model.prepare_decoder_input_ids_from_labels(labels=batch["labels"])
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddlenlp\transformers\t5\modeling.py", line 1785, in prepare_decoder_input_ids_from_labels
    return self._shift_right(labels)
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddlenlp\transformers\t5\modeling.py", line 900, in _shift_right
    shifted_input_ids = paddle.zeros_like(input_ids)
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddle\tensor\creation.py", line 1152, in zeros_like
    return full_like(x=x, fill_value=0, dtype=dtype, name=name)
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddle\tensor\creation.py", line 840, in full_like
    return _C_ops.full_like(x, fill_value, dtype, x.place)
AttributeError: 'numpy.ndarray' object has no attribute 'place'
```
不知道该如何解决？

### 稳定复现步骤 & 代码

```python
[2024-01-08 20:14:15,953] [    INFO] run_seq2struct.py:380 -   Total optimization steps = 25440
Exception in thread Thread-2:
Traceback (most recent call last):
  File "H:\SunJF\envs\uie_paddle\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "H:\SunJF\envs\uie_paddle\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddle\io\dataloader\dataloader_iter.py", line 235, in _thread_loop
    batch = self._dataset_fetcher.fetch(
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddle\io\dataloader\fetcher.py", line 85, in fetch
    data = self.collate_fn(data)
  File "H:\SunJF\data\pycharm\DuUIE\uie\seq2struct\data_collator.py", line 502, in __call__
    decoder_input_ids = self.model.prepare_decoder_input_ids_from_labels(labels=batch["labels"])
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddlenlp\transformers\t5\modeling.py", line 1785, in prepare_decoder_input_ids_from_labels
    return self._shift_right(labels)
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddlenlp\transformers\t5\modeling.py", line 900, in _shift_right
    shifted_input_ids = paddle.zeros_like(input_ids)
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddle\tensor\creation.py", line 1152, in zeros_like
    return full_like(x=x, fill_value=0, dtype=dtype, name=name)
  File "H:\SunJF\envs\uie_paddle\lib\site-packages\paddle\tensor\creation.py", line 840, in full_like
    return _C_ops.full_like(x, fill_value, dtype, x.place)
AttributeError: 'numpy.ndarray' object has no attribute 'place'
```

**Comment by ZHUI** [comment]
你看一下 collate_fn 出来的数据应该是 tensor，不应该是 numpy
