### ISSUE TITLE
import paddle的时候报错PermissionError: [Errno 13] Permission denied: '/.cache'

### ISSUE THREAD

**Issue by songsurging** [PaddlePaddle/PaddleNLP#7833]
## 本机GPU 驱动版本 470.86 cuda 11.4  ，然后在服务上部署，服务器GPU版本 525.105 cuda 12 ，对应的镜像推过去，报错如下
[2024-01-09 09:26:59,693](ERROR)(MainProcess)(7): Traceback (most recent call last):
File "/data/mathartsys/mysite/polls/global_instance.py", line 49, in init_global_instance
load_model = importlib.import_module("mathartsys.mysite.polls.scripts.{}".format(config.ALGO_LOADMODEL_FILENAME))
File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/data/mathartsys/mysite/polls/scripts/load_model.py", line 12, in <module>
from algorithm.sentence_embeddings import SentenceEmbeddings
File "/data/mathartsys/mysite/polls/scripts/algorithm/sentence_embeddings.py", line 5, in <module>
import paddle
File "/opt/conda/lib/python3.7/site-packages/paddle/__init__.py", line 59, in <module>
import paddle.dataset # noqa: F401
File "/opt/conda/lib/python3.7/site-packages/paddle/dataset/__init__.py", line 18, in <module>
import paddle.dataset.mnist # noqa: F401
File "/opt/conda/lib/python3.7/site-packages/paddle/dataset/mnist.py", line 23, in <module>
import paddle.dataset.common
File "/opt/conda/lib/python3.7/site-packages/paddle/dataset/common.py", line 50, in <module>
must_mkdirs(DATA_HOME)
File "/opt/conda/lib/python3.7/site-packages/paddle/dataset/common.py", line 43, in must_mkdirs
os.makedirs(DATA_HOME)
File "/opt/conda/lib/python3.7/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/opt/conda/lib/python3.7/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/opt/conda/lib/python3.7/os.py", line 223, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'

**Comment by w5688414** [comment]
看上去是路径不对或者没有权限，请检查一下DATA_HOME
