### ISSUE TITLE
[Question]: windows安装PaddleNLP Pipelines 语义检索,前端访问报错 An error occurred during the request.

### ISSUE THREAD

**Issue by caolongwei** [PaddlePaddle/PaddleNLP#7835]
### 请提出你的问题

conda环境
<img width="725" alt="2" src="https://github.com/PaddlePaddle/PaddleNLP/assets/88644350/e8c8f384-60e0-4d0d-9926-bbb9e31a602a">
<img width="476" alt="1" src="https://github.com/PaddlePaddle/PaddleNLP/assets/88644350/579411b8-39a8-491a-ace8-a4d9ad87290b">

python 3.9.18
paddlenlp 2.5.2

RestAPI 输出报错信息如下：

INFO:     127.0.0.1:52552 - "POST /query HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\pipelines\base.py", line 446, in run
    node_output, stream_id = self.graph.nodes[node_id]["component"]._dispatch_run(**node_input)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\base.py", line 120, in _dispatch_run
    return self._dispatch_run_general(self.run, **kwargs)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\base.py", line 164, in _dispatch_run_general
    output, stream = run_method(**run_inputs, **run_params)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\retriever\base.py", line 132, in run
    output, stream = run_query_timed(
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\retriever\base.py", line 110, in wrapper
    ret = fn(*args, **kwargs)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\retriever\base.py", line 185, in run_query
    documents = self.retrieve(query=query, filters=filters, top_k=top_k, index=index, headers=headers, **kwargs)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\retriever\dense.py", line 217, in retrieve
    documents = self.document_store.query_by_embedding(
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\document_stores\elasticsearch.py", line 1360, in query_by_embedding
    raise e
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\document_stores\elasticsearch.py", line 1350, in query_by_embedding
    result = self.client.search(index=index, body=body, request_timeout=600, headers=headers)["hits"]["hits"]
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\client\utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\client\__init__.py", line 1657, in search
    return self.transport.perform_request(
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\transport.py", line 415, in perform_request
    raise e
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 273, in perform_request
    self._raise_error(response.status, raw_data)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\connection\base.py", line 322, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'x_content_parse_exception', "[1:219] Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 219]")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\pipelines24\PaddleNLP\pipelines\.\rest_api\controller\search.py", line 100, in query
    result = _process_request(PIPELINE, request)
  File "E:\pipelines24\PaddleNLP\pipelines\.\rest_api\controller\search.py", line 219, in _process_request
    result = pipeline.run(query=request.query, params=params, debug=request.debug)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\pipelines\base.py", line 449, in run
    raise Exception(
Exception: Exception while running node `Retriever` with input `{'root_node': 'Query', 'params': {'filters': {}, 'Retriever': {'top_k': 30, 'debug': False}, 'Ranker': {'top_k': 3}, 'Query': {'debug': False}}, 'query': '衡量酒水的价格的因素 有哪些?', 'node_id': 'Retriever'}`: RequestError(400, 'x_content_parse_exception', "[1:219] Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 219]"), full stack trace: Traceback (most recent call last):
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\pipelines\base.py", line 446, in run
    node_output, stream_id = self.graph.nodes[node_id]["component"]._dispatch_run(**node_input)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\base.py", line 120, in _dispatch_run
    return self._dispatch_run_general(self.run, **kwargs)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\base.py", line 164, in _dispatch_run_general
    output, stream = run_method(**run_inputs, **run_params)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\retriever\base.py", line 132, in run
    output, stream = run_query_timed(
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\retriever\base.py", line 110, in wrapper
    ret = fn(*args, **kwargs)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\retriever\base.py", line 185, in run_query
    documents = self.retrieve(query=query, filters=filters, top_k=top_k, index=index, headers=headers, **kwargs)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\nodes\retriever\dense.py", line 217, in retrieve
    documents = self.document_store.query_by_embedding(
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\document_stores\elasticsearch.py", line 1360, in query_by_embedding
    raise e
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\pipelines\document_stores\elasticsearch.py", line 1350, in query_by_embedding
    result = self.client.search(index=index, body=body, request_timeout=600, headers=headers)["hits"]["hits"]
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\client\utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\client\__init__.py", line 1657, in search
    return self.transport.perform_request(
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\transport.py", line 415, in perform_request
    raise e
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 273, in perform_request
    self._raise_error(response.status, raw_data)
  File "D:\dev\anaconda3\envs\paddlepipline\lib\site-packages\elasticsearch\connection\base.py", line 322, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'x_content_parse_exception', "[1:219] Non-standard token 'NaN': 
enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\n 

at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 219]")
<img width="616" alt="pipelines_webui" src="https://github.com/PaddlePaddle/PaddleNLP/assets/88644350/d33acaa6-7a04-4775-8daa-53fc3d172b01">

**Comment by caolongwei** [comment]
<img width="616" alt="pipelines_webui" src="https://github.com/PaddlePaddle/PaddleNLP/assets/88644350/8f6f5888-6e62-4140-8efd-60c14f53eec6">

**Comment by caolongwei** [comment]
<img width="725" alt="2" src="https://github.com/PaddlePaddle/PaddleNLP/assets/88644350/e55cae42-4abb-40af-8423-8d07ac5cb0f2">

**Comment by caolongwei** [comment]
<img width="476" alt="1" src="https://github.com/PaddlePaddle/PaddleNLP/assets/88644350/d643ee4f-46f6-4941-bdd8-0e8eda2be55d">

**Comment by liudonglei** [comment]
遇到同样的问题，无解

**Comment by w5688414** [comment]
看一下后台的log日志，一般是后台的包缺失的问题
