### ISSUE TITLE
[Bug]: convert_from_torch 导致本地模型文件夹下模型无法再次加载

### ISSUE THREAD

**Issue by chen-zhiyu** [PaddlePaddle/PaddleNLP#7864]
### 软件环境

```Markdown
paddle2onnx         1.1.0
paddlefsl           1.1.0
paddlenlp           2.7.0.post0
paddlepaddle-gpu    2.6.0.post117
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "tiny_llama.py", line 25, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/work/venv/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 857, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home/work/venv/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 298, in _from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home/work/venv/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 2191, in from_pretrained
    raise ValueError(f"Unexpected file: {resolved_archive_file} for weight conversion.")
ValueError: Unexpected file: /home/work/TinyLlama-1.1B-Chat-v1.0/model_state.pdparams for weight conversion.
```

### 稳定复现步骤 & 代码

#model_name="TinyLlama/TinyLlama-1.1B-Chat-v1.0"
model_name="/home/work/TinyLlama-1.1B-Chat-v1.0"  #下载到本地的模型，重复下面的代码就会重现
 model = AutoModelForCausalLM.from_pretrained(
        model_name,
        convert_from_torch=True,
        #ignore_mismatched_sizes=True,
        #from_hf_hub=from_hf_hub,
        )

**Comment by JunnYu** [comment]
你好，
（1）能提供一下`/home/work/TinyLlama-1.1B-Chat-v1.0`目录下有啥文件吗？
（2）提供一下paddle版本，paddlenlp版本，使用命令 
```python
import paddle
print(paddle.__version__, paddle.__git_commit__)
import paddlenlp
print(paddlenlp.__version__, paddlenlp.version.commit)
```
(3) 可尝试使用最新的develop的paddlenlp，重新运行一下上面的命令

**Comment by chen-zhiyu** [comment]
> 你好， （1）能提供一下`/home/work/TinyLlama-1.1B-Chat-v1.0`目录下有啥文件吗？ （2）提供一下paddle版本，paddlenlp版本，使用命令
> 
> ```python
> import paddle
> print(paddle.__version__, paddle.__git_commit__)
> import paddlenlp
> print(paddlenlp.__version__, paddlenlp.version.commit)
> ```
> 
> (3) 可尝试使用最新的develop的paddlenlp，重新运行一下上面的命令

In [1]: import paddle
   ...: print(paddle.__version__, paddle.__git_commit__)
   ...: import paddlenlp
   ...: print(paddlenlp.__version__, paddlenlp.version.commit)
2.6.0 e032331bf78b0f9b51806c6761254c8b977f02b4
/home/work/venv/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2.7.0.post 16d3c49d2b8d0c7e56d1be8d7f6f2ca20aac80cb

**Comment by JunnYu** [comment]
从本地目录进行转换：
```python
from paddlenlp.transformers import AutoModelForCausalLM
model_name="/home/work/TinyLlama-1.1B-Chat-v1.0" #下载到本地的模型，重复下面的代码就会重现
model = AutoModelForCausalLM.from_pretrained(
model_name,
convert_from_torch=True,)
# 将转换后的权重保存到另一个目录
model.save_pretrained("TinyLlama-1.1B-Chat-v1.0_paddle")
```
下一次加载的时候直接加载转换后的目录
```python
from paddlenlp.transformers import AutoModelForCausalLM
model_name="TinyLlama-1.1B-Chat-v1.0_paddle" #下载到本地的模型，重复下面的代码就会重现
model = AutoModelForCausalLM.from_pretrained(model_name)
```

**Comment by chen-zhiyu** [comment]
[2024-01-19 12:34:37,163] [ WARNING] - Process rank: -1, device: gpu, world_size: 1, distributed training: False, 16-bits training: True
[2024-01-19 12:34:37,164] [    INFO] - We are using <class 'paddlenlp.transformers.llama.configuration.LlamaConfig'> to load '/root/chenzhiyu/TinyLlama-1.1B-Chat-v1.0'.
[2024-01-19 12:34:37,164] [    INFO] - Loading configuration file /root/chenzhiyu/TinyLlama-1.1B-Chat-v1.0/config.json
[2024-01-19 12:34:37,164] [    INFO] - We are using <class 'paddlenlp.transformers.llama.modeling.LlamaForCausalLM'> to load '/root/chenzhiyu/TinyLlama-1.1B-Chat-v1.0'.
[2024-01-19 12:34:37,165] [    INFO] - Loading weights file /root/chenzhiyu/TinyLlama-1.1B-Chat-v1.0/model.safetensors
Traceback (most recent call last):
  File "../paddlenlp/llm/finetune_generation.py", line 457, in <module>
    main()
  File "../paddlenlp/llm/finetune_generation.py", line 136, in main
    convert_from_torch=model_args.convert_from_torch,
  File "/root/chenzhiyu/venv/lib/python3.7/site-packages/paddlenlp/transformers/auto/modeling.py", line 857, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/root/chenzhiyu/venv/lib/python3.7/site-packages/paddlenlp/transformers/auto/modeling.py", line 298, in _from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/root/chenzhiyu/venv/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 2204, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/root/chenzhiyu/venv/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 335, in load_state_dict
    f"The safetensors archive passed at {checkpoint_file} does not contain the valid metadata. Make sure "
OSError: The safetensors archive passed at /root/chenzhiyu/TinyLlama-1.1B-Chat-v1.0/model.safetensors does not contain the valid metadata. Make sure you save your model with the `save_pretrained` method.

**Comment by chen-zhiyu** [comment]
转换完成后，再载会提示这个错误
(venv) work@linux-dev:~/TinyLlama-1.1B-Chat-v1.0$ ll
total 4299452
drwxrwxr-x  3 work work       4096 1月  19 10:53 ./
drwxr-xr-x 43 work work       4096 1月  19 10:43 ../
-rw-rw-r--  1 work work        608 1月  18 15:28 config.json
-rw-rw-r--  1 work work        566 1月  18 15:28 eval_results.json
-rw-rw-r--  1 work work        124 1月  18 15:28 generation_config.json
drwxrwxr-x  9 work work       4096 1月  18 15:41 .git/
-rw-rw-r--  1 work work       1519 1月  18 15:28 .gitattributes
-rw-rw-r--  1 work work 2200119864 1月  18 15:41 model.safetensors
-rw-rw-r--  1 work work 2200118134 1月  19 10:53 model_state.pdparams
-rw-rw-r--  1 work work       3136 1月  18 15:28 README.md
lrwxrwxrwx  1 work work         15 1月  18 15:53 sentencepiece.bpe.model -> tokenizer.model
-rw-rw-r--  1 work work        551 1月  18 15:28 special_tokens_map.json
-rw-rw-r--  1 work work       1289 1月  18 15:28 tokenizer_config.json
-rw-rw-r--  1 work work    1842767 1月  18 15:28 tokenizer.json
-rw-rw-r--  1 work work     499723 1月  18 15:28 tokenizer.model

**Comment by chen-zhiyu** [comment]
model = AutoModelForCausalLM.from_pretrained(
model_name,
convert_from_torch=True,) 
现在是只要加载时选择了convert，不保存就会存在当前模型文件夹下一个转换后的模型。
这个导致，下次就加载不了

**Comment by chen-zhiyu** [comment]
转换后的文件夹，
drwxrwxr-x  2 work work       4096 1月  19 14:17 ./
drwxr-xr-x 44 work work       4096 1月  19 14:17 ../
-rw-rw-r--  1 work work       1107 1月  19 14:17 config.json
-rw-rw-r--  1 work work        124 1月  19 14:17 generation_config.json
-rw-rw-r--  1 work work 2200118440 1月  19 14:17 model_state.pdparams
-rw-rw-r--  1 work work     499723 1月  19 14:17 sentencepiece.bpe.model
-rw-rw-r--  1 work work        444 1月  19 14:17 special_tokens_map.json
-rw-rw-r--  1 work work       1318 1月  19 14:17 tokenizer_config.json

加载这个文件夹时就会提示以下错误：
[2024-01-19 14:18:19,386] [    INFO] - Loading configuration file /home/work/TinyLlama-1.1B-Chat-v1.0-paddle/config.json
Traceback (most recent call last):
  File "finetune.py", line 554, in <module>
    main()
  File "finetune.py", line 260, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/work/venv/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 857, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home/work/venv/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 298, in _from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home/work/venv/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 2191, in from_pretrained
    raise ValueError(f"Unexpected file: {resolved_archive_file} for weight conversion.")
ValueError: Unexpected file: /home/work/TinyLlama-1.1B-Chat-v1.0-paddle/model_state.pdparams for weight conversion.
