### ISSUE TITLE
[Question]: 使用label_studio.py微调时报错 KeyError: 'text'

### ISSUE THREAD

**Issue by Vivi529** [PaddlePaddle/PaddleNLP#7918]
### 请提出你的问题

您好，我正在进行在线评论的实体识别和意见提取任务，已经使用lable studio进行标记，并导出有标签的json文件，但运行报错：Traceback (most recent call last):
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 738, in <module>
    do_convert()
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 698, in do_convert
    train_examples = convertor.convert_cls_examples(raw_examples[:p1], data_flag="Train")
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 103, in convert_cls_examples
    items = self.process_text_tag(line, task_type="cls")
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 64, in process_text_tag
    items["text"] = line["data"]["text"]
KeyError: 'text'
请问标记过程中，对于一个句子，实体和观点词必须同时具备并且每个打标签的词语必须包含关系吗？我不知道这个报错是不是由于下面几种标记产生的：
<img width="265" alt="3ab0fed315757c288d3f2e8b57b35b8" src="https://github.com/PaddlePaddle/PaddleNLP/assets/120614875/6c20dae0-4cd6-4279-8fa5-5b9f2d2decd3">
<img width="566" alt="b31f2948a8536f38863523177e4dbfd" src="https://github.com/PaddlePaddle/PaddleNLP/assets/120614875/6817856c-4bdd-468b-b7fd-ad064e38dc3a">
请懂的大佬解答一下！万分感激！

**Comment by wawltor** [comment]
<img width="1056" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/16698950/90c244f2-ab8d-4e52-b8a6-c20f6e292085">
看起来是一个属性抽取相关任务，需要把task_type改成ext

**Comment by Vivi529** [comment]
> <img alt="image" width="1056" src="https://private-user-images.githubusercontent.com/16698950/302514673-90c244f2-ab8d-4e52-b8a6-c20f6e292085.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDcwODUsIm5iZiI6MTcwNzMwNjc4NSwicGF0aCI6Ii8xNjY5ODk1MC8zMDI1MTQ2NzMtOTBjMjQ0ZjItYWI4ZC00ZTUyLWI4YTYtYzIwZjZlMjkyMDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDExNTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDZlNzY5NDE2YzRhYjA5YTdiZTM2ZjRjZWI2Njk3NjhlMTNmNjRiZjFiZWQyZmIxMzMzZDJkNTEzNWE5MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nWUcb7RuSoJOpMYKDg-B70yCEwHZmfwwNJyCTMVAsH0"> 看起来是一个属性抽取相关任务，需要把task_type改成ext

非常感谢您的回复和更正！我尝试运行了一下，同样的问题还是存在：Traceback (most recent call last):
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 738, in <module>
    do_convert()
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 673, in do_convert
    train_examples = convertor.convert_ext_examples(
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 158, in convert_ext_examples
    items = self.process_text_tag(line, task_type="ext")
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 64, in process_text_tag
    items["text"] = line["data"]["text"]
KeyError: 'text'
请问我图中的标记方式是否本来应该是可以存在的？我想知道是标记出了问题还是其他地方存在问题

> <img alt="image" width="1056" src="https://private-user-images.githubusercontent.com/16698950/302514673-90c244f2-ab8d-4e52-b8a6-c20f6e292085.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDcyMTksIm5iZiI6MTcwNzMwNjkxOSwicGF0aCI6Ii8xNjY5ODk1MC8zMDI1MTQ2NzMtOTBjMjQ0ZjItYWI4ZC00ZTUyLWI4YTYtYzIwZjZlMjkyMDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDExNTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNGYxMWVkZWQ4MzM1ZjI0YTljMzUyYjY1NWRlOGUyZDZlYTNhNDc5NTQyZDgxYzFkOGJlZGIwYjg4ZDg0YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.we5Mm5PJHOUHRV9hTo3RK4BVrAYZigSP5XvbdeEnw_g"> 看起来是一个属性抽取相关任务，需要把task_type改成ext

非常感谢您的回复和更正！我尝试运行了一下，同样的问题还是存在：Traceback (most recent call last):
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 738, in <module>
    do_convert()
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 673, in do_convert
    train_examples = convertor.convert_ext_examples(
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 158, in convert_ext_examples
    items = self.process_text_tag(line, task_type="ext")
  File "D:\AAApaper\online review\unified info extra\label_studio.py", line 64, in process_text_tag
    items["text"] = line["data"]["text"]
KeyError: 'text'
请问我图中的标记方式是否本来应该是可以存在的？我想知道是标记出了问题还是其他地方存在问题
