### ISSUE TITLE
[Bug]: 使用默认量化配置ptq_argument.json量化的llama-2-7b模型无法推理

### ISSUE THREAD

**Issue by 1826133674** [PaddlePaddle/PaddleNLP#7937]
### 软件环境

```Markdown
paddle-bfloat            0.1.7
paddle2onnx              1.1.0
paddlefsl                1.1.0
paddlenlp                2.7.0.post0
paddlepaddle-gpu         2.6.0.post112
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Error1: predictor.py 推理错误

Traceback (most recent call last):
  File "/PaddleNLP-develop/llm/predictor.py", line 1619, in <module>
    predict()
  File "/PaddleNLP-develop/llm/predictor.py", line 1547, in predict
    outputs = predictor.predict(batch_source_text)
  File "/PaddleNLP-develop/llm/predictor.py", line 259, in predict
    predictions = self._infer(tokenized_source)
  File "/anaconda3/envs/padllm/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/anaconda3/envs/padllm/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 352, in _decorate_function
    return func(*args, **kwargs)
  File "/PaddleNLP-develop/llm/predictor.py", line 306, in _infer
    result = self.model.generate(
  File "/anaconda3/envs/padllm/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/anaconda3/envs/padllm/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 352, in _decorate_function
    return func(*args, **kwargs)
  File "/anaconda3/envs/padllm/lib/python3.10/site-packages/paddlenlp/generation/utils.py", line 939, in generate
    return self.sample(
  File "/anaconda3/envs/padllm/lib/python3.10/site-packages/paddlenlp/generation/utils.py", line 1211, in sample
    next_tokens = paddle.multinomial(probs)
  File "/anaconda3/envs/padllm/lib/python3.10/site-packages/paddle/tensor/random.py", line 210, in multinomial
    return _C_ops.multinomial(x, num_samples, replacement)
ValueError: (InvalidArgument) Each element of multinomial'input must >= 0, but got nan.
  [Hint: Expected static_cast<MT>(weight) >= 0, but received static_cast<MT>(weight):nan < 0:0.] (at ../paddle/phi/kernels/gpu/multinomial_kernel.cu:166)

Error 2:pipline对话推理结果异常

(Tensor(shape=[1, 128], dtype=int64, place=Place(gpu:3), stop_gradient=True,
       [[31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744,
         31744, 31744, 31744, 31744, 31744, 31744, 31744, 31744]]), Tensor(shape=[1, 1], dtype=float32, place=Place(gpu:3), stop_gradient=True,
       [[nan]]))
ans ['忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠忠']
```

### 稳定复现步骤 & 代码

浮点llama-2-7B-chat文件夹结构：
- chat_template.json
- config.json
- model_state.pdparams
- sentencepiece.bpe.model
- special_tokens_map.json
- tokenizer_config.json

量化配置文件ptq_argument.json
{
  "model_name_or_path": "./llama/meta-llama/Llama-2-7b-chat",
  "per_device_train_batch_size": 8,
  "per_device_eval_batch_size": 8,
  "eval_accumulation_steps":16,
  "src_length": 1024,
  "max_length": 2048,
  "fp16": true,
  "fp16_opt_level": "O2",
  "dataset_name_or_path": "./data",
  "output_dir": "./llama/Llama-2-7b-chat_ptq_ckpts",
  "do_eval": true,
  "eval_with_do_generation": false,
  "do_ptq": true,
  "ptq_step": 16,
  "smooth": true,
  "smooth_step": 16,
  "smooth_all_linears": true,
  "smooth_piecewise_search": true,
  "smooth_k_piece": 3,
  "smooth_search_piece": true
}

 python finetune_generation.py ./llama/ptq_argument.json

Error1 复现：
python predictor.py --model_name_or_path ./llama/Llama-2-7b-chat_ptq_ckpts --data_file ./data/dev.json --dtype float16

Error2 复现：
from paddlenlp.transformers import AutoModelForCausalLM, AutoTokenizer
paddle.set_device("gpu:3")
print("paddle.device",paddle.get_device())
# fp_model_path = "/projects/pdllm/PaddleNLP-develop/llm/llama/meta-llama/Llama-2-7b-chat"
a8w8_path = "/projects/pdllm/PaddleNLP-develop/llm/llama/Llama-2-7b-chat_ptq_ckpts"
model_path = a8w8_path
model = AutoModelForCausalLM.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)
input_features = tokenizer("introduce your self!", return_tensors="pd")

outputs = model.generate(**input_features, max_new_tokens=128)
print(outputs)
ans = tokenizer.batch_decode(outputs[0])
print("ans",ans)

**Comment by 1826133674** [comment]
动态模式推理已经可以使用了，解决方案是安装paddlenlp中的自定义高性能算子库。
建议在量化模型推理的文档中加上，量化模型推理必须提前安装自定义的高性能算子库的提示。
