### ISSUE TITLE
[Bug]: TypeError: 'float' object is not iterable

### ISSUE THREAD

**Issue by lizexu123** [PaddlePaddle/PaddleNLP#8024]
### 软件环境

```Markdown
- paddlepaddle:2.6.0
- paddlepaddle-gpu: 2.6.0
- paddlenlp: 2.7.2
- paddleslim:2.6.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "run.py", line 384, in <module>
    main()
  File "run.py", line 377, in main
    ac.compress()
  File "/root/.conda/envs/lzx/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 586, in compress
    self.single_strategy_compress(strategy, config, strategy_idx,
  File "/root/.conda/envs/lzx/lib/python3.8/site-packages/paddleslim/auto_compression/compressor.py", line 753, in single_strategy_compress
    metric = self.eval_function(self._exe, inference_program,
  File "run.py", line 278, in eval_function
    res = metric.accumulate()
  File "/root/.conda/envs/lzx/lib/python3.8/site-packages/paddlenlp/metrics/glue.py", line 371, in accumulate
    preds = [item for sublist in self.preds for item in sublist]
  File "/root/.conda/envs/lzx/lib/python3.8/site-packages/paddlenlp/metrics/glue.py", line 371, in <listcomp>
    preds = [item for sublist in self.preds for item in sublist]
TypeError: 'float' object is not iterable
```

### 稳定复现步骤 & 代码

https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/pytorch_huggingface 
在使用PaddleSlim，进行自动压缩时，python run.py --config_path=./config/stsb.yaml --save_dir='./output/stsb'
stsb.yaml，改成了
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/39205361/41352cfb-e0f4-49bd-935e-d01315ef5e83)

**Comment by lugimzzz** [comment]
压缩相关issue请到paddleslim提问https://github.com/PaddlePaddle/PaddleSlim/issues
