### ISSUE TITLE
[Bug]: 数据增强报错

### ISSUE THREAD

**Issue by guishilike** [PaddlePaddle/PaddleNLP#8043]
### 软件环境

```Markdown
- paddlepaddle:2.6
- paddlepaddle-gpu: 2.6
- paddlenlp: 2.6
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
[2024-03-01 17:04:26,294] [    INFO] - We are using <class 'paddlenlp.transformers.roformer.modeling.RoFormerForCausalLM'> to load 'roformer-chinese-sim-char-base'.
[2024-03-01 17:04:26,295] [    INFO] - Already cached C:\Users\lenovo\.paddlenlp\models\roformer-chinese-sim-char-base\model_state.pdparams
[2024-03-01 17:04:26,295] [    INFO] - Loading weights file model_state.pdparams from cache at C:\Users\lenovo\.paddlenlp\models\roformer-chinese-sim-char-base\model_state.pdparams
[2024-03-01 17:04:26,743] [    INFO] - Loaded weights file from disk, setting weights to model.
Traceback (most recent call last):
  File "F:/project/FaultSelfDiagnosis/tools/similar_text_generator/ts.py", line 9, in <module>
    aug = SentenceGenerate(create_n=2, generate_n=5, max_length=128, top_p=0.95)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\paddlenlp\dataaug\sentence.py", line 63, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(self.model_name)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\paddlenlp\transformers\auto\modeling.py", line 818, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\paddlenlp\transformers\auto\modeling.py", line 327, in _from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\paddlenlp\transformers\model_utils.py", line 1956, in from_pretrained
    model, missing_keys, unexpected_keys, mismatched_keys = cls._load_pretrained_model(
  File "D:\anaconda3\envs\pytorch\lib\site-packages\paddlenlp\transformers\model_utils.py", line 1722, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for RoFormerForCausalLM:
	Skip loading for cls.predictions.decoder_weight. cls.predictions.decoder_weight receives a shape [768, 12000], but the expected shape is [12000, 768].
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

### 稳定复现步骤 & 代码

# -- coding:utf-8 --
from paddlenlp.dataaug import SentenceGenerate

s = ["人类语言是抽象的信息符号，其中蕴含着丰富的语义信息，人类可以很轻松地理解其中的含义。", "而计算机只能处理数值化的信息，无法直接理解人类语言，所以需要将人类语言进行数值化转换。"]
import paddle

paddle.set_device("gpu")
aug = SentenceGenerate(create_n=2, generate_n=5, max_length=128, top_p=0.95)
augmented = aug.augment(s[0])
print(augmented)

**Comment by Dineshkumar-Anandan-ZS0367** [comment]
Avoid this error, while passing this ignore_mismatched_sizes=True, while loading the nlp model.

I also used this Params for same in donut pretrained model.
