### ISSUE TITLE
[Bug]: prompts api学习报异常 AttributeError: 'tuple' object has no attribute 'skip_memory_metrics'

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleNLP#8050]
### 软件环境

```Markdown
paddlenlp                  2.6.1.post0
paddlepaddle-gpu           2.5.2
或者
paddlenlp                  2.7.0
paddlepaddle-gpu           2.6.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
按照教程https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/advanced_guide/prompt.md#prompttrainer%E5%8F%82%E6%95%B0%E5%88%97%E8%A1%A8
详细报错信息
Traceback (most recent call last):
  File "/home/aistudio/fs_train.py", line 105, in <module>
    trainer = PromptTrainer(model=prompt_model,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddlenlp/prompt/prompt_trainer.py", line 68, in __init__
    super(PromptTrainer, self).__init__(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddlenlp/trainer/trainer.py", line 269, in __init__
    self._memory_tracker = TrainerMemoryTracker(self.args.skip_memory_metrics)
AttributeError: 'tuple' object has no attribute 'skip_memory_metrics'
```

### 稳定复现步骤 & 代码

aistudio环境，启动命令
[files.zip](https://github.com/PaddlePaddle/PaddleNLP/files/14479554/files.zip)

```
!python3 /home/aistudio/fs_train.py --output_dir /home/aistudio/output \
--do_train True \
--do_eval True \
--evaluation_strategy epoch \
--per_device_train_batch_size 8 \
--per_device_eval_batch_size 8 \
--learning_rate 5e-05 \
--num_train_epochs 10 \
--warmup_ratio 0.05 \
--save_strategy epoch \
--seed 2222 
```
py文件和data文件见附件

**Comment by DesmonDay** [comment]
prompt文件夹下面的功能我们已经较长时间未进行维护了，可以考虑用paddlenlp 2.3和paddle 2.3或者 paddlenlp2.4和paddle 2.4来跑，回退版本。

**Comment by zouhan6806504** [comment]
> prompt文件夹下面的功能我们已经较长时间未进行维护了，可以考虑用paddlenlp 2.3和paddle 2.3或者 paddlenlp2.4和paddle 2.4来跑，回退版本。

是代码的问题，
parser = PdArgumentParser((PromptTuningArguments,))
training_args = parser.parse_args_into_dataclasses()[0]
返回的配置是一个tuple，需要指定

还有个问题，如果我想运行https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/few_shot/pet
自定义的prompt是
`"类型“{'text': 'category_name'}”的定义是：{'text': 'category_description'}事例：{'text': 'example'}该事例{'mask'}符合给定类型的定义"`
需要怎么读取数据？这里面的dataloader读的格式我不太熟悉
