### ISSUE TITLE
[Question]: llama2训练dataset报错

### ISSUE THREAD

**Issue by ShawnNew** [PaddlePaddle/PaddleNLP#8057]
### 请提出你的问题

按照 [官方文档](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm#1-%E9%A2%84%E8%AE%AD%E7%BB%83) 准备的数据集和使用脚本，做llama2 tp4 sd2的预训练时报错数据集格式不对。观察了一下该位置是进行`print_dataset`的操作，但是`train_dataset`变量是`GPTDataset`类型而非`list`。

```
Traceback (most recent call last):
  File "/workspace/algorithm/paddle/PaddleNLP/llm/run_pretrain.py", line 594, in <module>
    main()
  File "/workspace/algorithm/paddle/PaddleNLP/llm/run_pretrain.py", line 538, in main
    train_dataset, eval_dataset, test_dataset, data_collator = create_pretrained_dataset(
  File "/workspace/algorithm/paddle/PaddleNLP/llm/run_pretrain.py", line 274, in create_pretrained_dataset
    print_dataset(train_dataset[0], "train")
  File "/workspace/algorithm/paddle/PaddleNLP/paddlenlp/data/causal_dataset.py", line 372, in __getitem__
    sample, mask = self.indexed_dataset.get(self.doc_idx[doc_index_f], offset=offset_f)
ValueError: too many values to unpack (expected 2)

```

**Comment by wawltor** [comment]
辛苦更新到最新版本的PaddleNLP，上面的问题已经进行了修复 https://github.com/PaddlePaddle/PaddleNLP/pull/8049/files

**Comment by wawltor** [comment]
如无问题我们将关闭该issue，后续有问题的话可以再次打开，谢谢~
