### ISSUE TITLE
[Bug]: uie模型训练后添加压缩参数报错

### ISSUE THREAD

**Issue by wanshichenguang** [PaddlePaddle/PaddleNLP#8083]
### 软件环境

```Markdown
paddle-bfloat         0.1.7
paddle2onnx           1.1.0
paddlefsl             1.1.0
paddlenlp             2.7.2
paddleocr             2.6.1.3
paddlepaddle-gpu      2.6.0
paddleslim            2.6.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
运行uie的微调脚本：
export finetuned_model=./checkpoint/model_best

python finetune.py  \
    --device gpu \
    --logging_steps 10 \
    --save_steps 500 \
    --eval_steps 500 \
    --seed 42 \
    --model_name_or_path /root/source/nlp/PaddleNLP-develop/model_zoo/uie/checkpoint/model_best/checkpoint-65851 \
    --output_dir $finetuned_model \
    --train_path data/train.txt \
    --dev_path data/dev.txt  \
    --max_seq_length 64   \
    --per_device_eval_batch_size 64 \
    --per_device_train_batch_size  64 \
    --num_train_epochs 1 \
    --learning_rate 1e-5 \
    --label_names "start_positions" "end_positions" \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir $finetuned_model \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1 \
    --do_compress 
微调完压缩的时候报错：
[2024-03-09 09:29:55,826] [    INFO] - Exporting inference model to ./checkpoint/model_best/model
I0309 09:29:56.815759 16404 program_interpreter.cc:212] New Executor is Running.
[2024-03-09 09:29:57,240] [    INFO] - Inference model exported.
[2024-03-09 09:29:57,240] [    INFO] - tokenizer config file saved in ./checkpoint/model_best/tokenizer_config.json
[2024-03-09 09:29:57,240] [    INFO] - Special tokens file saved in ./checkpoint/model_best/special_tokens_map.json
Sat Mar 09 09:29:57 Dynamic-to-Static INFO: (Level -1) Not recommend to deepcopy 'UIE' decorated with @to_static, it has side effect that will rollback into original state before @to_static. Please deepcopy 'UIE' before applying @to_static.
/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py:2538: FutureWarning: The `max_seq_len` argument is deprecated and will be removed in a future version, please use `max_length` instead.
/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/transformers/tokenizer_utils_base.py:1938: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
Traceback (most recent call last):
  File "/root/source/nlp/PaddleNLP-develop/model_zoo/uie/finetune.py", line 262, in <module>
    main()
  File "/root/source/nlp/PaddleNLP-develop/model_zoo/uie/finetune.py", line 258, in main
    trainer.compress(custom_evaluate=custom_evaluate)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/trainer/trainer_compress.py", line 73, in compress
    _dynabert(self, self.model)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/trainer/trainer_compress.py", line 158, in _dynabert
    ofa_model, teacher_model = _dynabert_init(self, model, eval_dataloader)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/trainer/trainer_compress.py", line 300, in _dynabert_init
    head_importance, neuron_importance = compute_neuron_head_importance(
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/transformers/ofa_utils.py", line 307, in compute_neuron_head_importance
    logits = model(**batch)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/transformers/ernie/modeling.py", line 1269, in forward
    sequence_output, _ = self.ernie(
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1431, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1410, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/trainer/trainer_compress.py", line 907, in auto_model_dynabert_forward
    embedding_output = self.embeddings(**embedding_kwargs)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1431, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1410, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddlenlp/transformers/ernie/modeling.py", line 127, in forward
    embeddings = self.layer_norm(embeddings)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddlenlp/lib/python3.9/site-packages/paddleslim/nas/ofa/layers.py", line 1301, in forward
    out, _, _ = paddle._C_ops.layer_norm(
ValueError: too many values to unpack (expected 3)
```

### 稳定复现步骤 & 代码

python finetune.py  \
    --device gpu \
    --logging_steps 10 \
    --save_steps 500 \
    --eval_steps 500 \
    --seed 42 \
    --model_name_or_path /root/source/nlp/PaddleNLP-develop/model_zoo/uie/checkpoint/model_best/checkpoint-65851 \
    --output_dir $finetuned_model \
    --train_path data/train.txt \
    --dev_path data/dev.txt  \
    --max_seq_length 64   \
    --per_device_eval_batch_size 64 \
    --per_device_train_batch_size  64 \
    --num_train_epochs 1 \
    --learning_rate 1e-5 \
    --label_names "start_positions" "end_positions" \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir $finetuned_model \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1 \
    --do_compress

**Comment by gongel** [comment]
你好，建议降低PaddlePaddle版本

**Comment by wanshichenguang** [comment]
> 你好，建议降低PaddlePaddle版本

可以给一个版本配置吗，哪个版本的paddle和paddlenlp、paddleslim可以正常压缩。

**Comment by gongel** [comment]
先更新PaddleSlim==2.4.1试试，其次PaddlePaddle 2.4.2，PaddleNLP 2.5.0，
