### ISSUE TITLE
[Question]: pipelines.document_stores.faiss -  document_cnt:0	embedding_cnt:0

### ISSUE THREAD

**Issue by justforyou2017** [PaddlePaddle/PaddleNLP#8147]
### 请提出你的问题

运行python examples/semantic-search/semantic_search_example.py --device cpu报如下错误：

INFO - pipelines.document_stores.faiss -  document_cnt:0	embedding_cnt:0
Traceback (most recent call last):
  File "D:\application\eclipse\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\pydevd.py", line 3616, in <module>
    main()
  File "D:\application\eclipse\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\pydevd.py", line 3609, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\application\eclipse\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\pydevd.py", line 2626, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\application\eclipse\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\pydevd.py", line 2634, in _exec
    globals = pydevd_runpy.run_path(file, globals, '__main__')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\application\eclipse\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\application\eclipse\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\application\eclipse\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "D:\project\DAG\examples\semantic-search\semantic_search_example.py", line 205, in <module>
    semantic_search_tutorial()
  File "D:\project\DAG\examples\semantic-search\semantic_search_example.py", line 177, in semantic_search_tutorial
    retriever = get_faiss_retriever(use_gpu)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\DAG\examples\semantic-search\semantic_search_example.py", line 82, in get_faiss_retriever
    document_store.write_documents(dicts)
  File "D:\project\DAG\pipelines\document_stores\faiss.py", line 285, in write_documents
    add_vectors = False if document_objects[0].embedding is None else True
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'embedding' ，为何没有做向量转换？这个是什么问题呢？

**Comment by justforyou2017** [comment]
为何你们的说明文档里没有说下载向量转换的模型权重，是自动下载了吗？
