### ISSUE TITLE
[Bug]: OSError: (External) CUBLAS error(1).   [Hint: 'CUBLAS_STATUS_NOT_INITIALIZED'.  The cuBLAS library was not initialized. 

### ISSUE THREAD

**Issue by Walker-DJ1** [PaddlePaddle/PaddleNLP#8207]
### 软件环境

```Markdown
- paddlepaddle:2.6.1
- paddlepaddle-gpu: 2.6.1
- paddlenlp: 2.7.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
model：uie-base设置max_seq_length=512或者1024能正常运行，model：uie-m-large设置max_seq_length=512能正常运行，设置max_seq_length=1024出现bug
Error: ../paddle/phi/kernels/gpu/embedding_kernel.cu:45 Assertion `id < N` failed. Id should smaller than 514 but received an id value: 980. return _C_ops.linear(x, weight, bias) OSError: (External) CUBLAS error(1).   [Hint: 'CUBLAS_STATUS_NOT_INITIALIZED'.  The cuBLAS library was not initialized. This is usually caused by the lack of a prior cublasCreate() call, an error in the CUDA Runtime API called by the cuBLAS routine, or an error in the hardware setup.  To correct: call cublasCreate() prior to the function call; and check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed.  ] (at ../paddle/phi/backends/gpu/gpu_resources.cc:235)   [operator < linear > error]
```

### 稳定复现步骤 & 代码

Traceback (most recent call last):
  File "/data/xx/08paddle_nlp/PaddleNLP/model_zoo/uie/finetune.py", line 262, in <module>
    main()
  File "/data/xx/08paddle_nlp/PaddleNLP/model_zoo/uie/finetune.py", line 193, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 924, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 1955, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 1899, in compute_loss
    outputs = model(**inputs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/distributed/parallel.py", line 528, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddlenlp/transformers/ernie_m/modeling.py", line 822, in forward
    sequence_output, _ = self.ernie_m(
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddlenlp/transformers/ernie_m/modeling.py", line 302, in forward
    encoder_outputs = self.encoder(
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddlenlp/transformers/model_outputs.py", line 304, in _transformer_encoder_fwd
    layer_outputs = mod(
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddlenlp/transformers/model_outputs.py", line 83, in _transformer_encoder_layer_fwd
    attn_outputs = self.self_attn(src, src, src, src_mask, cache)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/layer/transformer.py", line 411, in forward
    q, k, v = self._prepare_qkv(query, key, value, cache)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/layer/transformer.py", line 243, in _prepare_qkv
    q = self.q_proj(query)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/layer/common.py", line 185, in forward
    out = F.linear(
  File "/data/xx/anaconda3/envs/paddle_nlp/lib/python3.9/site-packages/paddle/nn/functional/common.py", line 1960, in linear
    return _C_ops.linear(x, weight, bias)
OSError: (External) CUBLAS error(1).
  [Hint: 'CUBLAS_STATUS_NOT_INITIALIZED'.  The cuBLAS library was not initialized. This is usually caused by the lack of a prior cublasCreate() call, an error in the CUDA Runtime API called by the cuBLAS routine, or an error in the hardware setup.  To correct: call cublasCreate() prior to the function call; and check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed.  ] (at ../paddle/phi/backends/gpu/gpu_resources.cc:235)
  [operator < linear > error]

**Comment by DesmonDay** [comment]
这边建议是回退paddle和paddlenlp版本哈，推荐paddle使用2.3/2.4 paddlenlp使用2.5.1
