### ISSUE TITLE
调用uie-m-large时报错

### ISSUE THREAD

**Issue by jianxiaojin** [PaddlePaddle/PaddleNLP#8236]
```python
C:\Users\wangjin\.conda\envs\uie\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.   
warnings.warn("Setuptools is replacing distutils.") device： cpu 
Traceback (most recent call last):   

File "G:\develop\PycharmProjects\pythonProject\PaddleNLP\uie_m_large_test01.py", line 8, 
in <module>     
ie = Taskflow('information_extraction', schema=schema, model="uie-m-large", schema_lang="en" ) # , schema_lang="en"   

File "C:\Users\wangjin\.conda\envs\uie\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 804, in __init__ 
    self.task_instance = task_class(   File "C:\Users\wangjin\.conda\envs\uie\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 536, in __init__ 
    self._get_inference_model()   

File "C:\Users\wangjin\.conda\envs\uie\lib\site-packages\paddlenlp\taskflow\task.py", line 372, in _get_inference_model
     self._prepare_static_mode()   

File "C:\Users\wangjin\.conda\envs\uie\lib\site-packages\paddlenlp\taskflow\task.py", line 227, in _prepare_static_mode     

self.predictor = paddle.inference.create_predictor(self._config) 

RuntimeError: (Unavailable) An error occurred while loading model parameters. Please check whether the model file is complete or damaged.   

[Hint: Expected static_cast<bool>(*buffer) == true, but received static_cast<bool>(*buffer):0 != true:1.] (at ..\paddle/fluid/operators/load_combine_op.h:93)   [operator < load_combine > error]
```

**Comment by ZHUI** [comment]
请问你使用的paddle版本是？尝试换一个paddle版本呢？

**Comment by jianxiaojin** [comment]
> 请问你使用的paddle版本是？尝试换一个paddle版本呢？

好的。我用了两台设备，一台paddlepaddle和paddlenlp都是2.6.1，一台paddlepaddle-gpu是2.6.0，paddlenlp是2.6.1,都报这个错。

**Comment by jianxiaojin** [comment]
> 请问你使用的paddle版本是？尝试换一个paddle版本呢？

两个包一起换了2.5.2, 2.4.0, 2.4.2, 2.2.1这几个版本，还是报一样的错

**Comment by ZHUI** [comment]
你好，可能是权重下载不完整，您试试 清空一下 `~/.paddlenlp/`目录试试？

**Comment by masknugget** [comment]
最后怎么解决的，方便透露一下嘛
