### ISSUE TITLE
[Question]: 老版本报错InvalidArgumentError: Axis should be less than 2, but received axis is 2.

### ISSUE THREAD

**Issue by hurui79** [PaddlePaddle/PaddleNLP#8243]
### 请提出你的问题

因为要给服务器部署环境，由于环境恶劣，服务器cpu不支持avx指令集。
特意找的 win-cpu-mkl-noavx版本 paddlepaddle-2.4.2-cp38-cp38-win_amd64.whl
paddlenlp 是安装的2.5.2版本。
![2c9dcfe0d0f7fb1ffcd1561e37e6e35](https://github.com/PaddlePaddle/PaddleNLP/assets/16483840/c7134152-7a50-4f76-bc5d-747f59415443)
程序启动正常。
uie 真正去 抽取实体的时候报错

`Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\paddlenoavx\lib\site-packages\label_studio_ml\exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\paddlenoavx\lib\site-packages\label_studio_ml\api.py", line 51, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "D:\ProgramData\anaconda3\envs\paddlenoavx\lib\site-packages\label_studio_ml\model.py", line 617, in predict
    predictions = cls._current_model.model.predict(tasks, **kwargs)
  File "D:\KnowledgeGraph\label-studio-ml-backend\my_ml_backend\my_ml_backend.py", line 91, in predict
    uie = model(text)[0]
  File "D:\ProgramData\anaconda3\envs\paddlenoavx\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 850, in __call__
    results = self.task_instance(inputs)
  File "D:\ProgramData\anaconda3\envs\paddlenoavx\lib\site-packages\paddlenlp\taskflow\task.py", line 516, in __call__
    outputs = self._run_model(inputs)
  File "D:\ProgramData\anaconda3\envs\paddlenoavx\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 1066, in _run_model
    results = self._multi_stage_predict(_inputs)
  File "D:\ProgramData\anaconda3\envs\paddlenoavx\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 1164, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
  File "D:\ProgramData\anaconda3\envs\paddlenoavx\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 977, in _single_stage_predict
    self.predictor.run()
ValueError: In user code:

    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\threading.py", line 937, in _bootstrap
      self._bootstrap_inner()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\threading.py", line 980, in _bootstrap_inner
      self.run()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\threading.py", line 917, in run
      self._target(*self._args, **self._kwargs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\socketserver.py", line 683, in process_request_thread
      self.finish_request(request, client_address)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\socketserver.py", line 360, in finish_request
      self.RequestHandlerClass(request, client_address, self)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\socketserver.py", line 747, in __init__
      self.handle()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\werkzeug\serving.py", line 390, in handle
      super().handle()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\http\server.py", line 425, in handle
      self.handle_one_request()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\http\server.py", line 413, in handle_one_request
      method()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
      execute(self.server.app)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\werkzeug\serving.py", line 323, in execute
      application_iter = app(environ, start_response)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\flask\app.py", line 1478, in __call__
      return self.wsgi_app(environ, start_response)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\flask\app.py", line 1455, in wsgi_app
      response = self.full_dispatch_request()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
      rv = self.dispatch_request()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\flask\app.py", line 852, in dispatch_request
      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\label_studio_ml\exceptions.py", line 39, in exception_f
      return f(*args, **kwargs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\label_studio_ml\api.py", line 70, in _setup
      model = _manager.fetch(project, schema, force_reload,
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\label_studio_ml\model.py", line 537, in fetch
      model = cls.model_class(label_config=label_config, **kwargs)
    File "D:\KnowledgeGraph\label-studio-ml-backend\my_ml_backend\my_ml_backend.py", line 82, in __init__
      self.model = Taskflow("information_extraction", schema=self.labels, schema_lang="en", model="uie-m-base", task_path= './checkpoint/model_best')
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 804, in __init__
      self.task_instance = task_class(
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 536, in __init__
      self._get_inference_model()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddlenlp\taskflow\task.py", line 343, in _get_inference_model
      self._convert_dygraph_to_static()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddlenlp\taskflow\task.py", line 389, in _convert_dygraph_to_static
      paddle.jit.save(static_model, self.inference_model_path)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\base\wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\jit\api.py", line 809, in wrapper
      func(layer, path, input_spec, **configs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\base\wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\base\dygraph\base.py", line 68, in __impl__
      return func(*args, **kwargs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\jit\api.py", line 1104, in save
      static_func.concrete_program_specify_input_spec(
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\jit\dy2static\program_translator.py", line 986, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\jit\dy2static\program_translator.py", line 875, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\jit\dy2static\program_translator.py", line 1648, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\jit\dy2static\program_translator.py", line 1575, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\base\wrapped_decorator.py", line 26, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\base\dygraph\base.py", line 68, in __impl__
      return func(*args, **kwargs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\jit\dy2static\program_translator.py", line 1339, in from_func_spec
      outputs = static_func(*inputs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddlenlp\transformers\ernie_m\modeling.py", line 822, in forward
      sequence_output, _ = self.ernie_m(
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\nn\layer\layers.py", line 1431, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\nn\layer\layers.py", line 1410, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddlenlp\transformers\ernie_m\modeling.py", line 278, in forward
      if attention_mask is None:
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\jit\dy2static\convert_operators.py", line 398, in convert_ifelse
      out = _run_py_ifelse(
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\jit\dy2static\convert_operators.py", line 487, in _run_py_ifelse
      py_outs = true_fn() if pred else false_fn()
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddlenlp\transformers\ernie_m\modeling.py", line 280, in forward
      attention_mask = paddle.unsqueeze(
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\base\layers\math_op_patch.py", line 595, in __impl__
      current_block(self).append_op(
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\base\framework.py", line 4467, in append_op
      op = Operator(
    File "D:\ProgramData\anaconda3\envs\labelstudio\lib\site-packages\paddle\base\framework.py", line 3016, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: Axis should be less than 2, but received axis is 2.
      [Hint: Expected axis < max_dim, but received axis:2 >= max_dim:2.] (at C:\home\workspace\Paddle\paddle/phi/kernels/funcs/common_shape.h:53)
      [operator < equal > error]`
然后我就懵逼了。。。

**Comment by w5688414** [comment]
您好，UIE已经停止更新了，请问有完整的代码吗？

**Comment by hurui79** [comment]
大概知道咋回事了，我把模型删了，重新自动下载就好了

**Comment by sph116** [comment]
> 大概知道咋回事了，我把模型删了，重新自动下载就好了

您好 我也遇到相同问题 方便告知原因吗
