### ISSUE TITLE
[Question]: chatglm预训练失败，attention_mask为None

### ISSUE THREAD

**Issue by zhaogf01** [PaddlePaddle/PaddleNLP#8248]
### 请提出你的问题

paddlenlp是否还不支持对chatglm预训练，按照大模型预训练的流程尝试显示attention_mask为None

**Comment by w5688414** [comment]
chatglm还不支持预训练，因为预训练没有公开

**Comment by zhaogf01** [comment]
> chatglm还不支持预训练，因为预训练没有公开

好的，谢谢。再请教一个问题。
我是用寒武纪的显卡，使用对应的paddlecustomdevice编译的mlu的device，在跑bauchuan2-7B（缩减了一下模型大小）的时候遇到以下问题，请问您知道问题出在哪吗？

**error log：**
[2024-04-11 06:38:03,200] [    INFO] - ***** Running training *****
[2024-04-11 06:38:03,200] [    INFO] -   Num examples = 86,400
[2024-04-11 06:38:03,200] [    INFO] -   Num Epochs = 1
[2024-04-11 06:38:03,200] [    INFO] -   Instantaneous batch size per device = 1
[2024-04-11 06:38:03,200] [    INFO] -   Total train batch size (w. parallel, distributed & accumulation) = 8
[2024-04-11 06:38:03,200] [    INFO] -   Gradient Accumulation steps = 4
[2024-04-11 06:38:03,200] [    INFO] -   Total optimization steps = 10,000
[2024-04-11 06:38:03,200] [    INFO] -   Total num train samples = 80,000
[2024-04-11 06:38:03,201] [   DEBUG] -   Number of trainable parameters = 179,709,696 (per device)
[2024-04-11 06:38:03,223] [   DEBUG] -   Number of trainable parameters = 359,419,392 (all devices, roughly)
Traceback (most recent call last):
  File "/workspace/PaddleNLP/llm/run_pretrain.py", line 595, in <module>
    main()
  File "/workspace/PaddleNLP/llm/run_pretrain.py", line 573, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/PaddleNLP/paddlenlp/trainer/trainer.py", line 762, in train
    return self._inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/PaddleNLP/paddlenlp/trainer/trainer.py", line 889, in _inner_training_loop
  File "/workspace/PaddleNLP/paddlenlp/data/dist_dataloader.py", line 161, in __next__
    paddle.distributed.broadcast_object_list(data_keys_size, src=self.mp_src_rank, group=self.mp_group)
  File "/opt/conda/lib/python3.11/site-packages/paddle/distributed/communication/broadcast.py", line 134, in broadcast_object_list
    object_list[i] = convert_tensor_to_object(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/paddle/distributed/communication/serialization_utils.py", line 35, in convert_tensor_to_object
    return _unpickler(io.BytesIO(tensor.numpy()[:len_of_tensor])).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
I0411 06:38:04.468253 2761037 tcp_store.cc:289] receive shutdown event and so quit from MasterDaemon run loop
[4-11 14:38:4] [LOG_CNCL] [Warning]: There exist cnclComms that have not been destroyed yet. Make sure that all cnclComms have been destroyed or freed!
LAUNCH INFO 2024-04-11 06:38:05,621 Exit code 1


**预训练参数配置：**
{
    "model_name_or_path": "baichuan-inc/Baichuan2-7B-Base",
    "tokenizer_name_or_path": "baichuan-inc/Baichuan2-7B-Base",
    "input_dir": "./data",
    "output_dir": "./checkpoints/baichuan_pretrain_ckpts",
    "per_device_train_batch_size": 1,
    "gradient_accumulation_steps": 4,
    "per_device_eval_batch_size": 1,
    "tensor_parallel_degree": 2,
    "pipeline_parallel_degree": 1,
    "virtual_pp_degree": 1,
    "sequence_parallel": 0,   
    "use_flash_attention": true,
    "use_fused_rms_norm": true,
    "use_fused_rope": true,
    "max_seq_length": 4096,
    "learning_rate": 3e-05,
    "min_learning_rate": 3e-06,
    "warmup_steps": 30,
    "logging_steps": 1,
    "max_steps": 10000,
    "save_steps": 5000,
    "eval_steps": 1000,
    "weight_decay": 0.01,
    "bf16": 0,
    "fp16_opt_level": "O0",
    "warmup_ratio": 0.01,
    "max_grad_norm": 1.0,
    "dataloader_num_workers": 1,
    "continue_training": 0,
    "do_train": true,
    "do_eval": true,
    "do_predict": true,
    "disable_tqdm": true,
    "recompute": false,
    "distributed_dataloader": 1,
    "recompute_granularity": "full",
    "save_total_limit": 2,
    "device":"mlu"
  }


**模型config：**
{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "tokenizer_class": "LlamaTokenizer",
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "_from_model_config": true,
  "tie_word_embeddings": false,
  "dtype": "bfloat16",
  "use_cache": true,
  "vocab_size": 125696
}

**Comment by w5688414** [comment]
可以尝试以下的操作debug一下：

1. 不削减模型大小，只改变batch size那些呢，加recompute来节省显存，看看有没有问题。

2. 或者随机初始化一个llama模型，不用加载预训练权重试一下。
