### ISSUE TITLE
安装完成后直接把paddle环境破坏了

### ISSUE THREAD

**Issue by linghaolu** [PaddlePaddle/PaddleNLP#825]
python 3.6.0  
paddle1.8.5
按照说明安装完成 paddlenlp，导致paddle包无法正常加载

/home/work/opt/python3.6/lib/python3.6/site-packages/paddle/fluid/core.py:194: UserWarning: Load /usr/lib64/libgomp.so.1 failed
  warnings.warn("Load {} failed".format(dso_absolute_path))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/opt/python3.6/lib/python3.6/site-packages/paddle/__init__.py", line 37, in <module>
    import paddle.complex
  File "/home/work/opt/python3.6/lib/python3.6/site-packages/paddle/complex/__init__.py", line 15, in <module>
    from . import tensor
  File "/home/work/opt/python3.6/lib/python3.6/site-packages/paddle/complex/tensor/__init__.py", line 15, in <module>
    from . import math
  File "/home/work/opt/python3.6/lib/python3.6/site-packages/paddle/complex/tensor/math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "/home/work/opt/python3.6/lib/python3.6/site-packages/paddle/common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "/home/work/opt/python3.6/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/home/work/opt/python3.6/lib/python3.6/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/work/opt/python3.6/lib/python3.6/site-packages/paddle/fluid/core.py", line 273, in <module>
    raise e
  File "/home/work/opt/python3.6/lib/python3.6/site-packages/paddle/fluid/core.py", line 243, in <module>
    from .core_avx import *
ImportError: dlopen: cannot load any more object with static TLS

**Comment by ZeyuChen** [comment]
@linghaolu 请使用paddlepaddle 2.1.0以上版本。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/windows-conda.html
请参考安装文档
