### ISSUE TITLE
[Question]: ValueError: No node(s) or global parameter(s) named Ranker found in pipeline.

### ISSUE THREAD

**Issue by q798269** [PaddlePaddle/PaddleNLP#8262]
### 请提出你的问题

HI team:
 我这边碰到一个报错,有老师能麻烦看一下吗
 报错步骤:
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/77d2a525-805d-4459-bcd4-37dfc92b1693)

环境配置
os ubuntu22.04
python3.8
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/b2611e0d-7e37-46f5-a928-c6170ffe45af)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/3ecbae47-015e-48f8-8912-56564e033609)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/576056dd-c14b-4e7b-8caf-c327b1cc4092)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/5e46795a-a02b-471b-8e7a-7263811002a6)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/225c2045-9471-428e-83cd-f48c41d2dc2c)

cuda 12.2
cudnn 9.0
=

报错如下
WARNING - pipelines.pipelines.base -  YAML version (1.1.0) does not match with pipelines version (0.6.2). Issues may occur during loading. To fix this warning, save again this pipeline with the current pipelines version using Pipeline.save_to_yaml(), or downgrade to pipelines version 0.6.2.
WARNING - pipelines -  Request pipeline ('query_qa_pairs: is null'). 
INFO:     Started server process [62162]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8892 (Press CTRL+C to quit)
INFO:     127.0.0.1:49096 - "POST /query HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/tesla/nlp/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/tesla/nlp/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/home/tesla/nlp/lib/python3.8/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/tesla/nlp/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tesla/nlp/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/tesla/nlp/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/tesla/nlp/lib/python3.8/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/tesla/nlp/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/tesla/nlp/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/tesla/nlp/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/tesla/nlp/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/tesla/nlp/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/tesla/nlp/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/tesla/nlp/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/tesla/nlp/lib/python3.8/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/tesla/nlp/lib/python3.8/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/tesla/nlp/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/tesla/nlp/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/tesla/nlp/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/tesla/nlp/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/tesla/PaddleNLP/pipelines/./rest_api/controller/search.py", line 100, in query
    result = _process_request(PIPELINE, request)
  File "/home/tesla/PaddleNLP/pipelines/./rest_api/controller/search.py", line 219, in _process_request
    result = pipeline.run(query=request.query, params=params, debug=request.debug)
  File "/home/tesla/nlp/lib/python3.8/site-packages/pipelines/pipelines/base.py", line 407, in run
    raise ValueError(
ValueError: No node(s) or global parameter(s) named Ranker found in pipeline.

**Comment by w5688414** [comment]
请问你运行的代码是什么？

**Comment by q798269** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/f0b22cbd-fdf7-48a5-9c8c-a215aa2245da)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/8f58f7b3-d42e-498a-ae11-4b293ff8a174)

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/d472f9d3-42e4-474e-bb38-ceffec2a00b1)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/2de7f6bf-7829-4342-9e89-d7de943b0b61)

**Comment by q798269** [comment]
@w5688414 发在上边了老哥

**Comment by w5688414** [comment]
检查一下你建库的时候使用的模型和yaml里面使用的模型是否一致。

https://github.com/PaddlePaddle/PaddleNLP/blob/0d055448c3a65644fa842f89431ece9441df67d0/pipelines/utils/offline_ann.py#L44

https://github.com/PaddlePaddle/PaddleNLP/blob/0d055448c3a65644fa842f89431ece9441df67d0/pipelines/rest_api/pipeline/dense_qa.yaml#L16

目前默认是不一致的

**Comment by q798269** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/3e19b838-6459-489d-a132-40c37fb18c30)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/0fe09fd1-bceb-489f-8410-f3720a89d449)

**Comment by q798269** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/c8f74173-c48e-452b-9114-79d3ac1b380f)
修改成一样的模型还是同样的错误


![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/91c2fb89-a37b-45f3-ac1d-c47a1228a531)

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/22145019/f4ecbc6c-4107-4277-bb61-6ad1c0e60cea)
@w5688414

**Comment by w5688414** [comment]
nano模型的embedding dim是312，所以embedding_dim需要改为312，另外你的query_embedding_model也需要修改成nano
