### ISSUE TITLE
[Bug]: 关于训练PaddleNLP/model_zoo /ernie-layout/下面 XFUND-ZH Train出现的问题。

### ISSUE THREAD

**Issue by m5061125** [PaddlePaddle/PaddleNLP#8328]
### 软件环境

```Markdown
paddle-bfloat                  0.1.7
paddle-pipelines               0.6.2
paddle2onnx                    1.0.6
paddlefsl                      1.1.0
paddlenlp                      2.6.1
paddleocr                      2.6.1.3
paddlepaddle                   2.5.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
PS D:\Project\UIE\PaddleNLP\model_zoo\ernie-layout>  d:; cd 'd:\Project\UIE\PaddleNLP\model_zoo\ernie-layout'; & 'c:\ProgramData\Anaconda3\envs\GPT\python.exe' 'c:\Users\WLL\.vscode\extensions\ms-python.debugpy-2024.4.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '54956' '--' 'D:\Project\UIE\PaddleNLP\model_zoo\ernie-layout\run_ner.py' '--model_name_or_path' './ernie-layoutx-base-uncased/' '--output_dir' './ernie-layoutx-base-uncased/models/xfund_zh/' '--dataset_name' 'xfund_zh' '--do_train' '--do_eval' '--device' 'cpu' '--lang' 'ch' '--max_steps' '20000' '--save_steps' '1000' '--save_total_limit' '1' '--load_best_model_at_end' '--pattern' 'ner-bio' '--preprocessing_num_workers' '4' '--overwrite_cache' 'false' '--use_segment_box' '--doc_stride' '128' '--target_size' '1000' '--per_device_train_batch_size' '4' '--per_device_eval_batch_size' '4' '--learning_rate' '1e-5' '--lr_scheduler_type' 'constant' '--gradient_accumulation_steps' '1' '--seed' '1000' '--metric_for_best_model' 'eval_f1' '--greater_is_better' 'true' '--overwrite_output_dir'
C:\Users\WLL\AppData\Roaming\Python\Python38\site-packages\_distutils_hack\__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2024-04-25 09:46:02,684] [ WARNING] - evaluation_strategy reset to IntervalStrategy.STEPS for do_eval is True. you can also set evaluation_strategy='epoch'.
[2024-04-25 09:46:02,685] [    INFO] - using `logging_steps` to initialize `eval_steps` to 500
[2024-04-25 09:46:02,685] [    INFO] - The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same 
behavior as now. You should start updating your code and make this info disappear :-).
[2024-04-25 09:46:02,686] [    INFO] - ============================================================
[2024-04-25 09:46:02,686] [    INFO] -      Model Configuration Arguments
[2024-04-25 09:46:02,687] [    INFO] - paddle commit id              : 41ba14f30600373df53839dbf763405cfacb5c92
[2024-04-25 09:46:02,687] [    INFO] - cache_dir                     : None
[2024-04-25 09:46:02,687] [    INFO] - config_name                   : None
[2024-04-25 09:46:02,687] [    INFO] - model_name_or_path            : ./ernie-layoutx-base-uncased/
[2024-04-25 09:46:02,687] [    INFO] - tokenizer_name                : None
[2024-04-25 09:46:02,688] [    INFO] -
[2024-04-25 09:46:02,688] [    INFO] - ============================================================
[2024-04-25 09:46:02,688] [    INFO] -       Data Configuration Arguments
[2024-04-25 09:46:02,689] [    INFO] - paddle commit id              : 41ba14f30600373df53839dbf763405cfacb5c92
[2024-04-25 09:46:02,689] [    INFO] - dataset_config_name           : None
[2024-04-25 09:46:02,690] [    INFO] - dataset_name                  : xfund_zh
[2024-04-25 09:46:02,690] [    INFO] - doc_stride                    : 128
[2024-04-25 09:46:02,690] [    INFO] - label_all_tokens              : False
[2024-04-25 09:46:02,691] [    INFO] - lang                          : ch
[2024-04-25 09:46:02,691] [    INFO] - max_seq_length                : 512
[2024-04-25 09:46:02,692] [    INFO] - max_test_samples              : None
[2024-04-25 09:46:02,693] [    INFO] - max_train_samples             : None
[2024-04-25 09:46:02,693] [    INFO] - max_val_samples               : None
[2024-04-25 09:46:02,693] [    INFO] - overwrite_cache               : False
[2024-04-25 09:46:02,694] [    INFO] - pad_to_max_length             : True
[2024-04-25 09:46:02,694] [    INFO] - pattern                       : ner-bio
[2024-04-25 09:46:02,695] [    INFO] - preprocessing_num_workers     : 4
[2024-04-25 09:46:02,695] [    INFO] - return_entity_level_metrics   : False
[2024-04-25 09:46:02,695] [    INFO] - rst_converter                 : None
[2024-04-25 09:46:02,696] [    INFO] - target_size                   : 1000
[2024-04-25 09:46:02,696] [    INFO] - task_name                     : ner
[2024-04-25 09:46:02,697] [    INFO] - task_type                     : ner
[2024-04-25 09:46:02,697] [    INFO] - train_log_file                : None
[2024-04-25 09:46:02,698] [    INFO] - train_nshard                  : 1
[2024-04-25 09:46:02,698] [    INFO] - use_segment_box               : True
[2024-04-25 09:46:02,698] [    INFO] -
Found cached dataset xfund_zh (C:/Users/WLL/.cache/huggingface/datasets/xfund_zh/xfund_zh/1.0.0/264368adf5cb59b348e36f78428c3063ed51480f009c4965366ecfca3d903359)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 19.05it/s] 
[2024-04-25 09:46:02,971] [    INFO] - We are using <class 'paddlenlp.transformers.ernie_layout.tokenizer.ErnieLayoutTokenizer'> to load './ernie-layoutx-base-uncased/'.
[2024-04-25 09:46:03,509] [ WARNING] - ./ernie-layoutx-base-uncased/config.json  is not a valid path to a model config file
Traceback (most recent call last):
  File "D:\Project\UIE\PaddleNLP\model_zoo\ernie-layout\run_ner.py", line 214, in <module>
    main()
  File "D:\Project\UIE\PaddleNLP\model_zoo\ernie-layout\run_ner.py", line 77, in main
    model.config["has_visual_segment_embedding"] = False
AttributeError: 'NoneType' object has no attribute 'config'
```

### 稳定复现步骤 & 代码

你好，在尝试训练https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout#41的时候出现上述问题，感觉应该是没有找到config.json这个文件，在那个路径下也确实没有这个文件，不知道是不是版本问题，请指导一下，感谢。

**Comment by m5061125** [comment]
补充下，相关路径内容如下：
 C:\Users\WLL\.paddlenlp\models\ernie-layoutx-base-uncased 的目录

2024/04/23  15:30    <DIR>          .
2024/04/23  15:30    <DIR>          ..
2024/04/23  15:30    <DIR>          .lock
2024/04/23  15:30         5,069,051 sentencepiece.bpe.model
2024/04/23  17:30               200 special_tokens_map.json
2024/04/23  17:30               237 tokenizer_config.json
2024/04/23  15:30         2,831,350 vocab.txt
               4 个文件      7,900,838 字节
               3 个目录 747,039,612,928 可用字节

**Comment by m5061125** [comment]
我想我找到问题所在了，需要到https://huggingface.co/PaddlePaddle/ernie-layoutx-base-uncased/tree/main这里手动下载config和model两个文件，放到目录里才可以。
