### ISSUE TITLE
[Question]: UIE模型做信息抽取时如何设置嵌套关系的schema

### ISSUE THREAD

**Issue by lululiu2323** [PaddlePaddle/PaddleNLP#8388]
### 请提出你的问题

我在用UIE-base模型做信息抽取，现在信息标注到抽取都跑通了，准确率也不错。但是，现在遇到个问题，我想设置嵌套关系的schema，但是好像UIE不支持，请问应该怎么调整？我想用“储层”作为“油田区块”的子实体，结果报错如下：
>>> schema ={'油田区块': {'储层': ['地面原油密度', '地面原油粘度', '含硫量', '含蜡量']}}
>>> ie.set_schema(schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/taskflow.py", line 862, in set_schema
    self.task_instance.set_schema(schema)
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/information_extraction.py", line 549, in set_schema
    self._schema_tree = self._build_tree(schema)
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/information_extraction.py", line 1307, in _build_tree
    raise TypeError(
TypeError: Invalid schema, value for each key:value pairs should be list or stringbut <class 'dict'> received

**Comment by w5688414** [comment]
UIE不支持嵌套实体识别，需要做一些后处理策略，目前没有相关的开发计划，欢迎开发者贡献。

https://github.com/PaddlePaddle/PaddleNLP/issues/4503
