### ISSUE TITLE
[Question]: [Hint: Expected meta_.is_contiguous() == true, but received meta_.is_contiguous():0 != true:1.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:283)   [operator < reshape2 > error]

### ISSUE THREAD

**Issue by SiqinLv** [PaddlePaddle/PaddleNLP#8521]
### 请提出你的问题
运行cls = Taskflow("zero_shot_text_classification",schema=schema)  cls ('很好') 报错
报以下错误，输入其他文本也是：
```sh
[2024-05-31 17:11:56,645] [   ERROR] app.py:828 - Exception on /getText [POST]
Traceback (most recent call last):
  File "/home/bml/mnt/data/paddlepaddle_env_v2/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bml/mnt/data/paddlepaddle_env_v2/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bml/mnt/data/paddlepaddle_env_v2/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/bml/mnt/data/paddlepaddle_env_v2/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/bml/mnt/data/run_v4.py", line 430, in getText
    cur_cls = cls(utext)
  File "/home/bml/mnt/data/paddlepaddle_env_v2/lib/python3.9/site-packages/paddlenlp/taskflow/taskflow.py", line 822, in __call__
  File "/home/bml/mnt/data/paddlepaddle_env_v2/lib/python3.9/site-packages/paddlenlp/taskflow/zero_shot_text_classification.py", line 389, in _run_model
    self.predictor.run()
ValueError: (InvalidArgument) Right now Resize is only supported for contiguous Tensor. Tensor dims is 1, 7, 768, Tensor layout is NCHW, Tensor stride is 768, 1. New dims is -1, -1, 768.
  File "/home/bml/mnt/data/paddlepaddle_env_v2/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
    rv = self.dispatch_request()
  File "/home/bml/mnt/data/paddlepaddle_env_v2/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
  File "/home/bml/mnt/data/paddlepaddle_env_v2/lib/python3.9/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
    results = self.task_instance(inputs, **kwargs)
  File "/home/bml/mnt/data/paddlepaddle_env_v2/lib/python3.9/site-packages/paddlenlp/taskflow/task.py", line 527, in __call__
    outputs = self._run_model(inputs, **kwargs)
  [Hint: Expected meta_.is_contiguous() == true, but received meta_.is_contiguous():0 != true:1.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:283)
  [operator < reshape2 > error]
```

**Comment by w5688414** [comment]
请问您的paddle和paddlenlp的环境是什么？可以降低paddle版本试一下

**Comment by henryli2002** [comment]
遇到类似问题，回滚paddle至2.5.2解决了，注意一下依赖问题（我直接重装了）
