### ISSUE TITLE
[Question]: PaddleNLP 报错OSError: (External) CUBLAS error(1).

### ISSUE THREAD

**Issue by bella-cc** [PaddlePaddle/PaddleNLP#8657]
### 请提出你的问题

cuda 11.7；cudnn 8.4.1；python 3.11
paddlepaddle-gpu 2.5.2 post117 （显示成功安装）
![微信图片_20240625143625](https://github.com/PaddlePaddle/PaddleNLP/assets/173467536/458cd948-0c27-4b0e-b790-e0b68c0c1bdb)

paddlenlp 2.5.2
输入代码：
from pprint import pprint
from paddlenlp import Taskflow
schema = ['时间', '选手', '赛事名称']
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))

报错如下：
[2024-06-25 14:38:44,992] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'C:\Users\ADMIN\.paddlenlp\taskflow\information_extraction\uie-base'.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\embedding_kernel.cu:45 Assertion `id < N` failed. Id should smaller than 40000 but received an id value: 6875154315333164900.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\embedding_kernel.cu:45 Assertion `id < N` failed. Id should smaller than 40000 but received an id value: 6875154315333164900.
......
Traceback (most recent call last):
  File "D:\pythonproject\pythonProject1\check.py", line 10, in <module>
    pprint(ie("2月8日北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\Lib\site-packages\paddlenlp\taskflow\taskflow.py", line 850, in __call__
    results = self.task_instance(inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\Lib\site-packages\paddlenlp\taskflow\task.py", line 516, in __call__
    outputs = self._run_model(inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\Lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 1066, in _run_model
    results = self._multi_stage_predict(_inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\Lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 1164, in _multi_stage_predict
    result_list = self._single_stage_predict(examples)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\Lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 977, in _single_stage_predict
    self.predictor.run()

OSError: (External) CUBLAS error(1). 
  [Hint: 'CUBLAS_STATUS_NOT_INITIALIZED'.  The cuBLAS library was not initialized. This is usually caused by the lack of a prior cublasCreate() call, an error in the CUDA Runtime API called by the cuBLAS routine, or an error in the hardware setup.  To correct: call cublasCreate() prior to the function call; and check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed.  ] (at ..\paddle\phi\backends\gpu\gpu_resources.cc:214)
  [operator < multihead_matmul > error]

Process finished with exit code -1073740791 (0xC0000409)

**Comment by zhanghengjiayou** [comment]
我也是这个错误，请问你解决了嘛

**Comment by qinhuangdaoStation** [comment]
同样的问题，请问有解决的吗？

**Comment by zhanghengjiayou** [comment]
重建虚拟环境，重新安装
