### ISSUE TITLE
https://gitee.com/paddlepaddle/PaddleNLP/tree/develop/examples/semantic_indexing 转静态模型报错

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#866]
batch_neg_v1.0 | margin:0.2 scale:30 epoch:3 lr:5E-5 bs:128 max_len:64 | 单卡v100-16g | da1bb1487bd3fd6a53b8ef95c278f3e6
hardest_neg_v1.0 | margin:0.2 epoch:3 lr:5E-5 bs:128 max_len:64 | 单卡v100-16g | b535d890110ea608c8562c525a0b84b5

batch_neg_v1.0 转换成静态模型时报错，转换代码如下：
``def main():
    # Constructs the newtork.
    # Load pretrained semantic model
    pretrained_model = ppnlp.transformers.ErnieModel.from_pretrained(
        "ernie-1.0")
    model = SemanticIndexBase(
        pretrained_model, output_emb_size=args.output_emb_size)

    # Load model parameters.
    state_dict = paddle.load(args.params_path)
    model.set_dict(state_dict)
    model.eval()

    # Convert to static graph with specific input description
    model = paddle.jit.to_static(model, input_spec=[])
    # Save in static graph model.
    paddle.jit.save(model, args.output_path)``

报错

2021-08-09 17:37:35,336 Dynamic-to-Static WARNING: Output of traced function contains non-tensor type values: [<class 'NoneType'>]. Currently, We don't support to update them while training and will return what we first saw. Please try to return them as tensor.
Traceback (most recent call last):
  File "E:/quadtalent/16_work_order_consolidation_disposal/update_mart/export_model.py", line 55, in <module>
    main()
  File "E:/quadtalent/16_work_order_consolidation_disposal/update_mart/export_model.py", line 51, in main
    paddle.jit.save(model, args.output_path)
  File "<decorator-gen-67>", line 2, in save
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\dygraph\jit.py", line 819, in save
    program_only=configs._program_only)
  File "<decorator-gen-87>", line 2, in save_inference_model
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\framework.py", line 236, in __impl__
    return func(*args, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\io.py", line 1312, in save_inference_model
    raise ValueError("'target_vars' should be a list of Variable.")
ValueError: 'target_vars' should be a list of Variable.

**Comment by tianxin1860** [comment]
加载 `BatchNeg` 模型的时候应该用这个类
 `    
model = SemanticIndexBatchNeg(
        pretrained_model,
        margin=args.margin,
        scale=args.scale,
        output_emb_size=args.output_emb_size)
`
