### ISSUE TITLE
[Bug]: RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), float16) of kernel `multiply` is not registered. 

### ISSUE THREAD

**Issue by zhanland** [PaddlePaddle/PaddleNLP#8686]
### 软件环境

```Markdown
paddle2onnx        1.2.4
paddlefsl          1.1.0
paddlenlp          3.0.0b0
paddlepaddle       3.0.0b0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2024-06-30 00:30:54,539] [ WARNING] - if you run ring_flash_attention.py, please ensure you install the paddlenlp_ops by following the instructions provided at https://github.com/PaddlePaddle/PaddleNLP/blob/develop/csrc/README.md
[2024-06-30 00:30:56,533] [    INFO] - We are using <class 'paddlenlp.transformers.qwen2.tokenizer.Qwen2Tokenizer'> to load 'Qwen/Qwen2-0.5B'.
[2024-06-30 00:30:56,695] [    INFO] - The `unk_token` parameter needs to be defined: we use `eos_token` by default.
[2024-06-30 00:30:56,890] [    INFO] - Adding <|im_start|> to the vocabulary
[2024-06-30 00:30:56,890] [    INFO] - Adding <|im_end|> to the vocabulary
[2024-06-30 00:30:56,890] [    INFO] - Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[2024-06-30 00:30:56,891] [    INFO] - We are using <class 'paddlenlp.transformers.qwen2.modeling.Qwen2ForCausalLM'> to load 'Qwen/Qwen2-0.5B'.
[2024-06-30 00:30:56,891] [    INFO] - Loading configuration file /home/liang/.paddlenlp/models/Qwen/Qwen2-0.5B/config.json
[2024-06-30 00:30:56,892] [    INFO] - Loading weights file from cache at /home/liang/.paddlenlp/models/Qwen/Qwen2-0.5B/model.safetensors
[2024-06-30 00:30:57,622] [    INFO] - Loaded weights file from disk, setting weights to model.
[2024-06-30 00:31:40,997] [    INFO] - All model checkpoint weights were used when initializing Qwen2ForCausalLM.

[2024-06-30 00:31:41,001] [ WARNING] - Some weights of Qwen2ForCausalLM were not initialized from the model checkpoint at Qwen/Qwen2-0.5B and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[2024-06-30 00:31:41,002] [    INFO] - Loading configuration file /home/liang/.paddlenlp/models/Qwen/Qwen2-0.5B/generation_config.json
W0630 00:31:41.038244 50710 multiply_fwd_func.cc:75] got different data type, run type promotion automatically, this may cause data type been changed.
Traceback (most recent call last):
  File "/home/liang/paddle/main.py", line 5, in <module>
    outputs = model.generate(**input_features, max_length=128)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddle/base/dygraph/base.py", line 337, in _decorate_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddlenlp/generation/utils.py", line 918, in generate
    return self.greedy_search(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddlenlp/generation/utils.py", line 1072, in greedy_search
    outputs = self(**model_inputs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1426, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddlenlp/transformers/qwen2/modeling.py", line 1337, in forward
    outputs = self.qwen2(
              ^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1426, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddlenlp/transformers/qwen2/modeling.py", line 1068, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1426, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddlenlp/transformers/qwen2/modeling.py", line 655, in forward
    hidden_states = self.input_layernorm(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1426, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liang/miniconda3/envs/paddle_cpu/lib/python3.11/site-packages/paddlenlp/transformers/qwen2/modeling.py", line 304, in forward
    return hidden_states * self.weight
           ~~~~~~~~~~~~~~^~~~~~~~~~~~~
RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), float16) of kernel `multiply` is not registered. Selected wrong DataType `float16`. Paddle support following DataTypes: int64, float64, complex128, float32, complex64, int32, bfloat16, bool.
  [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /paddle/paddle/phi/core/kernel_factory.cc:287)
```

### 稳定复现步骤 & 代码

from paddlenlp.transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-0.5B")
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B",dtype='float16')
input_features = tokenizer("你好！请自我介绍一下。", return_tensors="pd")
outputs = model.generate(**input_features, max_length=128)
tokenizer.batch_decode(outputs[0])
# ['我是一个AI语言模型，我可以回答各种问题，包括但不限于：天气、新闻、历史、文化、科学、教育、娱乐等。请问您有什么需要了解的吗？']

**Comment by DrownFish19** [comment]
1. 在CPU环境调用时，模型支持`dtype`为`float32`或者`float64`;
2. 在GPU环境（非Ampere架构）调用时，模型支持`dtype`为`float16`、`float32`或者`float64`;
3. 在GPU环境（Ampere及后续架构）调用时，模型支持`dtype`为`bfloat16`、`float16`、`float32`或者`float64`;

**Comment by zhanland** [comment]
感谢 ！  可以了

**Comment by shrek-dior** [comment]
你好，可以麻烦问一下是怎么解决这个问题的吗？
W0708 10:27:36.466545 14708 multiply_fwd_func.cc:64] got different data type, run type protmotion automatically, this may cause data type been changed.
W0708 10:27:36.466545 14708 multiply_fwd_func.cc:64] got different data type, run type protmotion automatically, this may cause data type been changed.
W0708 10:27:36.468546 14708 dygraph_functions.cc:52641] got different data type, run type protmotion automatically, this may cause data type been changed.
W0708 10:27:36.469051 14708 dygraph_functions.cc:52641] got different data type, run type protmotion automatically, this may cause data type been changed.

**Comment by DrownFish19** [comment]
> 你好，可以麻烦问一下是怎么解决这个问题的吗？ W0708 10:27:36.466545 14708 multiply_fwd_func.cc:64] got different data type, run type protmotion automatically, this may cause data type been changed. W0708 10:27:36.466545 14708 multiply_fwd_func.cc:64] got different data type, run type protmotion automatically, this may cause data type been changed. W0708 10:27:36.468546 14708 dygraph_functions.cc:52641] got different data type, run type protmotion automatically, this may cause data type been changed. W0708 10:27:36.469051 14708 dygraph_functions.cc:52641] got different data type, run type protmotion automatically, this may cause data type been changed.

这个是warning。Paddle在类型转换后，如float16和bfloat16，和float32类型进行计算时，会出现以上warning。在Paddle中仅会出现从低精度到高精度的转换，因此计算精度不会损失。在Qwen2中具体代码如下：
```python
class Qwen2RMSNorm(nn.Layer):
    def __init__(self, config: Qwen2Config):
        """
        Qwen2RMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        ...
        self.variance_epsilon = config.rms_norm_eps
        ...

    def forward(self, hidden_states):
        if paddle.in_dynamic_mode():
            with paddle.amp.auto_cast(False):
                # variance类型为float32
                variance = hidden_states.astype("float32").pow(2).mean(-1, keepdim=True) 
                # 计算过程为 （paddle.float32+float value) * paddle.float16 或者 paddle.bfloat16，hidden_states最终为float32
                hidden_states = paddle.rsqrt(variance + self.variance_epsilon) * hidden_states  
        else:
            variance = hidden_states.astype("float32").pow(2).mean(-1, keepdim=True)
            hidden_states = paddle.rsqrt(variance + self.variance_epsilon) * hidden_states

        if self.weight.dtype in [paddle.float16, paddle.bfloat16]:
            hidden_states = paddle.cast(hidden_states, self.weight.dtype)
        return hidden_states * self.weight
```
