### ISSUE TITLE
[Bug]: 例子（信息抽取）报错

### ISSUE THREAD

**Issue by Verrev00** [PaddlePaddle/PaddleNLP#8780]
### 软件环境

```Markdown
- paddlepaddle: 3.0.0b0
- paddlepaddle-gpu: 
- paddlenlp:  3.0.0b0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "D:\MyPlace\code\python\PaddlenlpDemo\nlpdemo\text_summarization.py", line 5, in <module>
    ie = Taskflow('information_extraction', schema=schema)
  File "D:\MyPlace\code\python\PaddlenlpDemo\.venv\Lib\site-packages\paddlenlp\taskflow\taskflow.py", line 809, in __init__
    self.task_instance = task_class(                   
  File "D:\MyPlace\code\python\PaddlenlpDemo\.venv\Lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 538, in __init__
    self._construct_tokenizer()
  File "D:\MyPlace\code\python\PaddlenlpDemo\.venv\Lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 595, in _construct_tokenizer
    self._tokenizer = AutoTokenizer.from_pretrained(             
  File "D:\MyPlace\code\python\PaddlenlpDemo\.venv\Lib\site-packages\paddlenlp\transformers\auto\tokenizer.py", line 223, in from_pretrained
    raise ValueError("use_fast is deprecated")
ValueError: use_fast is deprecated
```

### 稳定复现步骤 & 代码

from pprint import pprint

from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称']  # Define the schema for entity extraction
ie = Taskflow("information_extraction", schema=schema, model="uie-x-base")
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))

**Comment by DrownFish19** [comment]
非常抱歉，这个问题已经在develop分支修复https://github.com/PaddlePaddle/PaddleNLP/commit/cf57f86755c02860aedc7c65b0a6d51b1d55dbf4 ，可以通过安装最新预览版进行解决，命令如下：
```
pip install --pre --upgrade paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```
