### ISSUE TITLE
[Bug]: llama开启block_attntion后，temperature设置0时出错

### ISSUE THREAD

**Issue by wojiaoshihua** [PaddlePaddle/PaddleNLP#8830]
### 软件环境

```Markdown
- paddlepaddle-gpu: 3.0.0.dev20240728
- paddlenlp: 3.0.0b0.post0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
运行示例代码开启block_attn时，动态图报错如下：
Traceback (most recent call last):
  File "/root/llava3_0/PaddleNLP-release-3.0-beta/llm/./predict/predictor.py", line 1710, in <module>
    predict()
  File "/root/llava3_0/PaddleNLP-release-3.0-beta/llm/./predict/predictor.py", line 1655, in predict
    outputs = predictor.predict(batch_source_text)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 387, in _decorate_function
    return func(*args, **kwargs)
  File "/root/llava3_0/PaddleNLP-release-3.0-beta/llm/./predict/predictor.py", line 1058, in predict
    self._infer(self.inputs)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 387, in _decorate_function
    return func(*args, **kwargs)
  File "/root/llava3_0/PaddleNLP-release-3.0-beta/llm/./predict/predictor.py", line 1039, in _infer
    self.model.generate(
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 387, in _decorate_function
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/generation_utils.py", line 605, in generate
    ret = self.sample(
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/generation_utils.py", line 709, in sample
    outputs = _forward_(**model_kwargs)  # [bs, 1, dim_embed]
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/generation_utils.py", line 628, in _forward_
    return self(**model_inputs)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1529, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/llama/modeling.py", line 1611, in forward
    outputs = self.llama(
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1529, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/llama/modeling.py", line 1111, in forward
    hidden_states, _ = self.transformer_block(
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1529, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/fused_transformer_layers.py", line 835, in forward
    out_linear_out = self.compute_attn(
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/fused_transformer_layers.py", line 1531, in compute_attn
    fmha_out = paddle.incubate.nn.functional.block_multihead_attention(
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/incubate/nn/functional/block_multihead_attention.py", line 285, in block_multihead_attention
    return _C_ops.block_multihead_attention_(
OSError: (External) Error in Flash-Attention, detail information is: `is_sm8x || is_sm90` check failed at /paddle/third_party/flashattn/csrc/capi/flash_attn.cu:711
  [Hint: Expected status == true, but received status:0 != true:1.] (at ../paddle/phi/kernels/gpu/flash_attn_utils.h:360)

Process Process-1:
Traceback (most recent call last):
  File "/root/anaconda3/envs/visual/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/visual/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/llava3_0/PaddleNLP-release-3.0-beta/llm/utils/utils.py", line 761, in read_res
    output_tensor = tensor_queue.get(timeout=1)
  File "/root/anaconda3/envs/visual/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/incubate/multiprocessing/reductions.py", line 130, in _rebuild_lodtensor_filename
    lodtensor = cls._new_shared_filename(
RuntimeError: (Unavailable) File descriptor /paddle_22726_0_766758490 open failed, unable in read-write mode
  [Hint: Expected fd != -1, but received fd:-1 == -1:-1.] (at ../paddle/fluid/memory/allocation/mmap_allocator.cc:85)

temperature=0，且用静态图时，会报如下错误：
Error: ../paddle/phi/kernels/gpu/embedding_kernel.cu:40 Assertion `id >= 0` failed. Id should no less than 0 but received an id value: -1.
Traceback (most recent call last):
  File "/root/MedMLLM/projects/hcg_skin/service/serv_py.py", line 198, in infer_model
    content, core_time_cost = self.model.generate(user_prompt, image_enc)
  File "/root/MedMLLM/projects/hcg_skin/service/inference_static.py", line 420, in generate
    outputs, core_time = self.predictor.predict(query, image_enc)
  File "/root/MedMLLM/projects/hcg_skin/service/inference_static.py", line 328, in predict
    generate_ids, _ = self.generate_with_image_features(
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 387, in _decorate_function
    return func(*args, **kwargs)
  File "/root/MedMLLM/projects/hcg_skin/service/inference_static.py", line 247, in generate_with_image_features
    self.second_predictor.run(inputs)
OSError: In user code:

    File "/root/personal-code/llava_paddle_static/deploy/llava/export_model.py", line 109, in <module>
      export_encode_text(model, config, compute_dtype)
    File "/root/personal-code/llava_paddle_static/deploy/llava/export_model.py", line 30, in export_encode_text
      model.to_static(save_path, config, compute_dtype)
    File "/root/personal-code/llava_paddle_static/deploy/llava/llama_inference_model.py", line 143, in to_static
      paddle.jit.save(model, output_path, skip_prune_program=True)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/wrapped_decorator.py", line 40, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/api.py", line 900, in wrapper
      func(layer, path, input_spec, **configs)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/wrapped_decorator.py", line 40, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 94, in __impl__
      return func(*args, **kwargs)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/api.py", line 1262, in save
      static_func.concrete_program_specify_input_spec(
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 993, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 881, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1628, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1574, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/wrapped_decorator.py", line 40, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 94, in __impl__
      return func(*args, **kwargs)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1335, in from_func_spec
      outputs = static_func(*inputs)
    File "/root/.cache/paddle/to_static_tmp/47551/generate_text_with_image_features6kh2oyjt.py", line 73, in generate_text_with_image_features
      return _jst.Ld(_decoedby_no_grad)(_jst.Ld(self), _jst.Ld(input_ids), _jst.Ld(image_features), _jst.Ld(img_pos), _jst.Ld(attention_mask), _jst.Ld(position_ids), _jst.Ld(penalty_score), _jst.Ld(frequency_score), _jst.Ld(presence_score), _jst.Ld(min_length), _jst.Ld(max_length), _jst.Ld(temperature), _jst.Ld(top_p), _jst.Ld(eos_token_id), _jst.Ld(seq_len_encoder), _jst.Ld(seq_len_decoder), _jst.Ld(step_idx), _jst.Ld(stop_flags), _jst.Ld(tgt_ids), _jst.Ld(tgt_pos), _jst.Ld(tgt_generation_mask), _jst.Ld(pre_ids), _jst.Ld(stop_nums), _jst.Ld(cache_kvs))
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 387, in _decorate_function
      return func(*args, **kwargs)
    File "/root/personal-code/llava_paddle_static/deploy/llava/llama_inference_model.py", line 66, in generate_text_with_image_features
      outputs = self.generate(
    File "/root/.cache/paddle/to_static_tmp/47551/generatex295by9a.py", line 39, in generate
      return _jst.Ld(_decoedby_no_grad)(_jst.Ld(self), _jst.Ld(input_ids), _jst.Ld(attention_mask), _jst.Ld(position_ids), _jst.Ld(penalty_score), _jst.Ld(frequency_score), _jst.Ld(presence_score), _jst.Ld(min_length), _jst.Ld(max_length), _jst.Ld(temperature), _jst.Ld(top_p), _jst.Ld(eos_token_id), _jst.Ld(seq_len_encoder), _jst.Ld(seq_len_decoder), _jst.Ld(step_idx), _jst.Ld(stop_flags), _jst.Ld(tgt_ids), _jst.Ld(tgt_pos), _jst.Ld(tgt_generation_mask), _jst.Ld(pre_ids), _jst.Ld(stop_nums), _jst.Ld(cache_kvs), _jst.Ld(inputs_embeds), _jst.Ld(logits_processors), _jst.Ld(pre_caches))
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 387, in _decorate_function
      return func(*args, **kwargs)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/generation_utils.py", line 177, in generate
      ret = self.sample(
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/generation_utils.py", line 378, in sample
      while paddle.less_than(
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/dy2static/convert_operators.py", line 185, in convert_while_loop
      _run_paddle_while(
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/dy2static/convert_operators.py", line 244, in _run_paddle_while
      loop_vars = while_loop(new_cond_fn, new_body_fn, loop_vars)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/static/nn/control_flow.py", line 871, in while_loop
      output_vars = body(*new_loop_vars)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/dy2static/convert_operators.py", line 226, in new_body_fn
      body()
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/generation_utils.py", line 382, in sample
      next_tokens, model_kwargs = _post_process_(
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp/experimental/transformers/generation_utils.py", line 352, in _post_process_
      save_with_output(
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp_ops-0.0.0-py3.10-linux-x86_64.egg/paddlenlp_ops.py", line 696, in save_with_output
      if in_dynamic_or_pir_mode():
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/dy2static/convert_operators.py", line 425, in convert_ifelse
      out = _run_py_ifelse(
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/jit/dy2static/convert_operators.py", line 514, in _run_py_ifelse
      py_outs = true_fn() if pred else false_fn()
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddlenlp_ops-0.0.0-py3.10-linux-x86_64.egg/paddlenlp_ops.py", line 715, in save_with_output
      helper.append_op(type="save_with_output", inputs=ins, outputs=outs, attrs={'file_path' : file_path,'rank_id' : rank_id})
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/layer_helper.py", line 50, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/framework.py", line 4651, in append_op
      op = Operator(
    File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/base/framework.py", line 3204, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDA error(719), unspecified launch failure. 
      [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:265)
      [operator < save_with_output > error]
```

### 稳定复现步骤 & 代码

示例代码：python ./predict/predictor.py --model_name_or_path meta-llama/Llama-2-7b-chat --inference_model --dtype float16 --block_attn

将predictor.py文件中的temperature设置为0即可复现。

**Comment by wojiaoshihua** [comment]
设置参数错误，实际上与block_attn无关，只是在inference model下缺少对temperature=0的判断。在generation_utils文件中，添加`if temperature is not None and temperature != 0:
                logits = logits / temperature`
即可
