### ISSUE TITLE
export_model失败

### ISSUE THREAD

**Issue by 44show** [PaddlePaddle/PaddleNLP#908]
>>> import paddle
>>> import paddlenlp
>>> paddle.__version__
'2.1.1'
>>> paddlenlp.__version__
'2.0.7'
paddlenlp的同学，你们好。
自定义训练数据，模型训练完毕，GPU环境下导出报错，把模型拷到本地CPU导出不报错，但是即便用训练集去评测也是效果很差跟随机差不多，GPU导出时错误如下：
root@9cda29d248ff:/opt/worker/pp/PaddleNLP/examples/information_extraction# python3 waybill_ie/export_model.py --params_path ernie_crf_ckpt/model_21780
[2021-08-20 06:31:16,795] [    INFO] - Already cached /root/.paddlenlp/models/ernie-1.0/ernie_v1_chn_base.pdparams
W0820 06:31:16.796620  4819 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W0820 06:31:16.801761  4819 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Loaded parameters from ernie_crf_ckpt/model_21780
Traceback (most recent call last):
  File "waybill_ie/export_model.py", line 56, in <module>
    paddle.jit.save(model, save_path)
  File "<decorator-gen-67>", line 2, in save
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/jit.py", line 719, in save
    inner_input_spec)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AttributeError: In transformed code:

    File "/usr/local/lib/python3.6/dist-packages/paddlenlp/transformers/ernie/modeling.py", line 622, in forward (* user code *)
        sequence_output, _ = self.ernie(
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 228, in convert_call
        forward_func = convert_to_static(forward_func)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 141, in convert_to_static
        static_func = _FUNCTION_CACHE.convert_with_cache(function)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 78, in convert_with_cache
        static_func = self._convert(func)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 122, in _convert
        create_and_update_origin_info_map(root_wrapper.node, static_func)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/origin_info.py", line 163, in create_and_update_origin_info_map
        for t_node, s_node in ast_walk(transformed_node, static_node):
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/origin_info.py", line 241, in ast_walk
        t_node_child = getattr(t_node, field)
    AttributeError: 'Assign' object has no attribute 'type_comment'

**Comment by 44show** [comment]
升级paddle 2.1.1 -> 2.1.2 就能过了。
