### ISSUE TITLE
ErnieCrfForTokenClassification 模型的导出问题

### ISSUE THREAD

**Issue by 44show** [PaddlePaddle/PaddleNLP#911]
基于 waybill_ie run_ernie_crf.py 训练的模型，应该怎么导出呢？demo中的export_model只支持“ErnieForTokenClassification”
我修改为：    
model = ppnlp.transformers.ErnieForTokenClassification.from_pretrained(
        "ernie-1.0", num_classes=len(label_vocab))
    model = ErnieCrfForTokenClassification(model)
报错：
Traceback (most recent call last):
  File "/Users/DF-WS/WS/Work4/pp/PaddleNLP/examples/information_extraction/waybill_ie/export_model.py", line 59, in <module>
    paddle.jit.save(model, save_path)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 726, in save
    inner_input_spec)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 491, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 705, in _build_once
    class_instance=cache_key.class_instance)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 661, in from_func_spec
    error_data.raise_new_exception()
  File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AttributeError: In transformed code:

    File "/var/folders/m2/w41j79015n7c584j6xd7s38c0000gn/T/tmp920boutq.py", line 32, in forward
	__return_value_0,))
    File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
	return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/Users/DF-WS/WS/Work4/pp/PaddleNLP/examples/information_extraction/waybill_ie/model.py", line 83, in forward (* user code *)
	_, prediction = self.viterbi_decoder(logits, lengths)
    File "/Users/DF-WS/anaconda2/envs/py37_pp_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/Users/DF-WS/WS/Work4/pp/PaddleNLP/paddlenlp/layers/crf.py", line 386, in forward (* user code *)
	left_length = lengths.clone()
    AttributeError: 'NoneType' object has no attribute 'clone'

**Comment by 44show** [comment]
import paddle
import paddlenlp
paddle.version
'2.1.2'
paddlenlp.version
'2.0.7'

**Comment by joey12300** [comment]
@44show 您好，由于examples中所示的是`ErnieForTokenClassification`，其forward的参数与`ErnieCrfForTokenClassification`不同，需要在export_model.py的InputSpec中添加参数声明。

## ErnieForTokenClassification
```
  model = paddle.jit.to_static(
      model,
      input_spec=[
          paddle.static.InputSpec(
              shape=[None, None], dtype="int64"),  # input_ids
          paddle.static.InputSpec(
              shape=[None, None], dtype="int64")  # segment_ids
      ])

```

**经过修改后：**

## ErnieCrfForTokenClassification
```
model = paddle.jit.to_static(
    model,
    input_spec=[
        paddle.static.InputSpec(
            shape=[None, None], dtype="int64"),  # input_ids
        paddle.static.InputSpec(
            shape=[None, None], dtype="int64"),  # segment_ids
        paddle.static.InputSpec(
            shape=[None], dtype="int64")  # length
    ])

```

**Comment by 44show** [comment]
问题解决了，谢谢。
