### ISSUE TITLE
ernie-doc的演示脚本读取数据格式不对路径不对跑不起来

### ISSUE THREAD

**Issue by AntikaSmith** [PaddlePaddle/PaddleNLP#944]
在自己下载了iflytek的数据并放到data下之后，运行sh scripts/run_iflytek.sh 日志里显示
`
Traceback (most recent call last):
  File "./run_classifier.py", line 306, in <module>
    main(args)
  File "./run_classifier.py", line 128, in main
    phase="train")
  File "/data/hanzhang/ernie/ERNIE/ernie-doc/reader/task_reader.py", line 243, in data_generator
    examples = self._read_tsv(input_file)
  File "/data/hanzhang/ernie/ERNIE/ernie-doc/reader/task_reader.py", line 277, in _read_tsv
    with open(input_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/finetune/task_data//iflytek/train/1'
`
这path拼接的完全不对啊，肯定是跑不起来的。
发布方之前运行iflytek的时候使用的不是这个分支的代码？

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-doc
请试用下paddlenlp的这个版本。@AntikaSmith
