### ISSUE TITLE
[GPT pretrain] RuntimeError: std::future_error: No associated state

### ISSUE THREAD

**Issue by duchengyao** [PaddlePaddle/PaddleNLP#946]
运行gpt数小时后，出现以下错误，是什么原因呢。

```
 python -m paddle.distributed.launch --gpus "0,1,2,3,4,5,6,7" run_pretrain.py     --model_type gpt     --model_name_or_path gpt2-en     --input_dir "../data_tools/gpt_openwebtext"    --output_dir "output"    --weig
ht_decay 0.01    --grad_clip 1.0    --max_steps 500000    --save_steps 5000    --decay_steps 320000    --warmup_rate 0.01    --micro_batch_size 8    --device gpu
```

```
[2021-08-30 17:40:34,014] [    INFO] - global step 84498, epoch: 0, batch: 84497, loss: 3.752200842, speed: 3.85 step/s, ips: 252204 tokens/s, learning rate: 1.61551e-05
[2021-08-30 17:40:34,267] [    INFO] - global step 84499, epoch: 0, batch: 84498, loss: 3.602007151, speed: 3.96 step/s, ips: 259658 tokens/s, learning rate: 1.61553e-05
[2021-08-30 17:40:34,527] [    INFO] - global step 84500, epoch: 0, batch: 84499, loss: 3.798186541, speed: 3.86 step/s, ips: 252832 tokens/s, learning rate: 1.61554e-05
Traceback (most recent call last):
  File "run_pretrain.py", line 262, in <module>
    do_train(args)
  File "run_pretrain.py", line 229, in do_train
    run_evaluate(valid_data_loader, model, criterion,
  File "<decorator-gen-275>", line 2, in run_evaluate
  File "/home/duchengyao/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "run_pretrain.py", line 60, in run_evaluate
    for eval_step, batch in enumerate(data_loader):
  File "/home/duchengyao/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 197, in __next__
    data = self._reader.read_next_var_list()
RuntimeError: std::future_error: No associated state
INFO 2021-08-30 17:40:46,168 launch_utils.py:327] terminate all the procs
ERROR 2021-08-30 17:40:46,168 launch_utils.py:582] ABORT!!! Out of all 8 trainers, the trainer process with rank=[0, 1, 2, 3, 4, 5, 6, 7] was aborted. Please check its log.
INFO 2021-08-30 17:40:49,172 launch_utils.py:327] terminate all the procs
```

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/939 十分抱歉，昨天修复了一个小bug，可能是这个bug。你修改试试

**Comment by ZHUI** [comment]
如果你需要重启训练，可以参考 ernie1.0 的脚本，重checkpoint处，恢复数据集。

**Comment by duchengyao** [comment]
> 如果你需要重启训练，可以参考 ernie1.0 的脚本，重checkpoint处，恢复数据集。

刚想问您这个问题，谢谢啦～

**Comment by ZHUI** [comment]
> > 如果你需要重启训练，可以参考 ernie1.0 的脚本，重checkpoint处，恢复数据集。
> 
> 刚想问您这个问题，谢谢啦～
主要是计算 consumed_samples 传入进去
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/ernie-1.0/run_pretrain_static.py#L126
另外lr_scheduler也需要重启
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/ernie-1.0/run_pretrain_static.py#L434

**Comment by ZHUI** [comment]
后续，我们会将GPT重启训练这一块的功能完善下来。

**Comment by duchengyao** [comment]
> #939 十分抱歉，昨天修复了一个小bug，可能是这个bug。你修改试试

merge 了新分支后貌似问题解决了。如果问题复现会重新开启这个issue ^_^

**Comment by chenxiaozeng** [comment]
@duchengyao 您好，根据你提出的需求，我们想进一步和您沟通下需求背景以及使用场景，以便更好得解答您的问题。这是我们的联系方式：邮箱paddlenlp@baidu.com，方便的话可以留下您的联系方式，我们 1 对 1 沟通下，谢谢！
