### ISSUE TITLE
[Bug]: cannot import name 'switch_rng_state_tracker' from 'paddle.distributed.fleet.recompute.recompute'

### ISSUE THREAD

**Issue by moyanxinxu** [PaddlePaddle/PaddleNLP#9564]
### 软件环境

```Markdown
paddle2onnx               1.3.1
paddlefsl                 1.1.0
paddlenlp                 2.8.1
paddlepaddle              2.6.2
paddlepaddle-gpu          2.6.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
https://github.com/PaddlePaddle/PaddleNLP/blob/a5ec6bf623ce8e68ce84e0620d1e195072b25643/paddlenlp/transformers/refined_recompute.py#L33


这个代码好像写错了

应该是
from paddle.distributed.fleet.recompute.recompute import swith_rng_state_tracker
而不是
from paddle.distributed.fleet.recompute.recompute import switch_rng_state_tracker
```

### 稳定复现步骤 & 代码

from paddlenlp import Taskflow

导包即错误

**Comment by DesmonDay** [comment]
有报错信息么？我看了下代码这个写法是正确的

**Comment by yes-github** [comment]
Z:\>paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav
C:\ProgramData\Anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
C:\Users\Yes\AppData\Roaming\Python\Python39\site-packages\_distutils_hack\__init__.py:36: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\paddlespeech.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlespeech\cli\entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlespeech\cli\tts\__init__.py", line 14, in <module>
    from .infer import TTSExecutor
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlespeech\cli\tts\infer.py", line 33, in <module>
    from paddlespeech.t2s.exps.syn_utils import get_am_inference
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlespeech\t2s\exps\syn_utils.py", line 35, in <module>
    from paddlespeech.t2s.frontend.mix_frontend import MixFrontend
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlespeech\t2s\frontend\mix_frontend.py", line 22, in <module>
    from paddlespeech.t2s.frontend.zh_frontend import Frontend
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlespeech\t2s\frontend\zh_frontend.py", line 31, in <module>
    from paddlespeech.t2s.frontend.g2pw import G2PWOnnxConverter
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlespeech\t2s\frontend\g2pw\__init__.py", line 1, in <module>
    from .onnx_api import G2PWOnnxConverter
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlespeech\t2s\frontend\g2pw\onnx_api.py", line 28, in <module>
    from paddlenlp.transformers import BertTokenizer
  File "C:\Users\Yes\AppData\Roaming\Python\Python39\site-packages\paddlenlp\__init__.py", line 46, in <module>
    from . import (
  File "C:\Users\Yes\AppData\Roaming\Python\Python39\site-packages\paddlenlp\data\__init__.py", line 18, in <module>
    from .data_collator import *
  File "C:\Users\Yes\AppData\Roaming\Python\Python39\site-packages\paddlenlp\data\data_collator.py", line 26, in <module>
    from ..transformers import BertTokenizer
  File "C:\Users\Yes\AppData\Roaming\Python\Python39\site-packages\paddlenlp\transformers\__init__.py", line 99, in <module>
    from .deepseek_v2.modeling import *
  File "C:\Users\Yes\AppData\Roaming\Python\Python39\site-packages\paddlenlp\transformers\deepseek_v2\__init__.py", line 17, in <module>
    from .tokenizer_fast import *
  File "C:\Users\Yes\AppData\Roaming\Python\Python39\site-packages\paddlenlp\transformers\deepseek_v2\tokenizer_fast.py", line 16, in <module>
    from ..llama import LlamaTokenizerFast
  File "C:\Users\Yes\AppData\Roaming\Python\Python39\site-packages\paddlenlp\transformers\llama\__init__.py", line 16, in <module>
    from .modeling import *
  File "C:\Users\Yes\AppData\Roaming\Python\Python39\site-packages\paddlenlp\transformers\llama\modeling.py", line 33, in <module>
    from paddlenlp.transformers.refined_recompute import (
  File "C:\Users\Yes\AppData\Roaming\Python\Python39\site-packages\paddlenlp\transformers\refined_recompute.py", line 33, in <module>
    from paddle.distributed.fleet.recompute.recompute import switch_rng_state_tracker
ImportError: cannot import name 'switch_rng_state_tracker' from 'paddle.distributed.fleet.recompute.recompute' (C:\ProgramData\Anaconda3\lib\site-packages\paddle\distributed\fleet\recompute\recompute.py)

**Comment by moyanxinxu** [comment]
把源码改成这个swith_rng_state_tracker之后呢 @yes-github

**Comment by aixingxy** [comment]
> 把源码改成这个swith_rng_state_tracker之后呢 [@yes-github](https://github.com/yes-github)


"""
from paddle.distributed.fleet.recompute.recompute import swith_rng_state_tracker
而不是
from paddle.distributed.fleet.recompute.recompute import switch_rng_state_tracker
"""
改成swith_rng_state_tracker就没问题了
