### ISSUE TITLE
[Question]: 在编译ops的gpu算子时遇到的问题。

### ISSUE THREAD

**Issue by aooxin** [PaddlePaddle/PaddleNLP#9583]
### 在编译ops的gpu算子时遇到的问题

# 命令
python setup_cuda.py install 

# 环境
## pip list
Package            Version
------------------ -----------
aiohappyeyeballs   2.4.4
aiohttp            3.11.10
aiosignal          1.3.1
aistudio-sdk       0.2.6
annotated-types    0.7.0
anyio              4.6.2.post1
astor              0.8.1
attrs              24.2.0
babel              2.16.0
bce-python-sdk     0.9.23
blinker            1.9.0
blobfile           3.0.0
certifi            2024.8.30
charset-normalizer 3.4.0
click              8.1.7
colorama           0.4.6
colorlog           6.9.0
contourpy          1.3.1
cycler             0.12.1
datasets           3.1.0
decorator          5.1.1
dill               0.3.4
fast_dataindex     0.1.2
fastapi            0.115.6
filelock           3.16.1
Flask              3.1.0
flask-babel        4.0.0
fonttools          4.55.2
frozenlist         1.5.0
fsspec             2024.9.0
future             1.0.0
h11                0.14.0
httpcore           1.0.7
httpx              0.28.0
huggingface-hub    0.26.5
idna               3.10
itsdangerous       2.2.0
jieba              0.42.1
Jinja2             3.1.4
joblib             1.4.2
kiwisolver         1.4.7
lxml               5.3.0
markdown-it-py     3.0.0
MarkupSafe         3.0.2
matplotlib         3.9.3
mdurl              0.1.2
multidict          6.1.0
multiprocess       0.70.12.2
networkx           3.4.2
numpy              1.26.4
onnx               1.17.0
opencv-python      4.10.0.84
opt-einsum         3.3.0
packaging          24.2
paddle2onnx        1.3.1
paddlefsl          1.1.0
paddlenlp          3.0.0b2
paddlepaddle-gpu   0.0.0
pandas             2.2.3
pillow             11.0.0
pip                24.2
prettytable        3.12.0
propcache          0.2.1
protobuf           5.29.1
psutil             6.1.0
pyarrow            18.1.0
pybind11           2.13.6
pybind11-stubgen   2.5.1
pycryptodome       3.21.0
pycryptodomex      3.21.0
pydantic           2.10.3
pydantic_core      2.27.1
Pygments           2.18.0
pyparsing          3.2.0
python-dateutil    2.9.0.post0
pytz               2024.2
PyYAML             6.0.2
rarfile            4.2
regex              2024.11.6
requests           2.32.3
rich               13.9.4
safetensors        0.4.5
scikit-learn       1.5.2
scipy              1.14.1
sentencepiece      0.2.0
seqeval            1.2.2
setuptools         75.6.0
shellingham        1.5.4
six                1.17.0
sniffio            1.3.1
starlette          0.41.3
threadpoolctl      3.5.0
tiktoken           0.8.0
tokenizers         0.21.0
tqdm               4.67.1
typer              0.15.1
typing_extensions  4.12.2
tzdata             2024.2
urllib3            2.2.3
uvicorn            0.32.1
visualdl           2.5.3
wcwidth            0.2.13
Werkzeug           3.1.3
wheel              0.45.1
xxhash             3.5.0
yarl               1.18.3

## cuda
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

## GCC
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc-8.2/libexec/gcc/x86_64-pc-linux-gnu/8.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-8.2.0/configure --prefix=/usr/local/gcc-8.2 --enable-threads=posix --disable-checking --disable-multilib
Thread model: posix
gcc version 8.2.0 (GCC)

# 日志
Received len(custom_op) =  38, using custom operator
[2024-12-09 05:40:42,800] [    INFO] util.py:477 - byte-compiling build/paddlenlp_ops/bdist.linux-x86_64/egg/paddlenlp_ops.py to paddlenlp_ops.cpython-312.pyc
[2024-12-09 05:40:42,817] [    INFO] file_util.py:130 - copying paddlenlp_ops.egg-info/PKG-INFO -> build/paddlenlp_ops/bdist.linux-x86_64/egg/EGG-INFO
[2024-12-09 05:40:42,817] [    INFO] file_util.py:130 - copying paddlenlp_ops.egg-info/SOURCES.txt -> build/paddlenlp_ops/bdist.linux-x86_64/egg/EGG-INFO
[2024-12-09 05:40:42,817] [    INFO] file_util.py:130 - copying paddlenlp_ops.egg-info/dependency_links.txt -> build/paddlenlp_ops/bdist.linux-x86_64/egg/EGG-INFO
[2024-12-09 05:40:42,817] [    INFO] file_util.py:130 - copying paddlenlp_ops.egg-info/not-zip-safe -> build/paddlenlp_ops/bdist.linux-x86_64/egg/EGG-INFO
[2024-12-09 05:40:42,817] [    INFO] file_util.py:130 - copying paddlenlp_ops.egg-info/top_level.txt -> build/paddlenlp_ops/bdist.linux-x86_64/egg/EGG-INFO
[2024-12-09 05:40:42,818] [    INFO] bdist_egg.py:210 - writing build/paddlenlp_ops/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
[2024-12-09 05:40:42,818] [    INFO] bdist_egg.py:459 - creating 'dist/paddlenlp_ops-0.0.0-py3.12-linux-x86_64.egg' and adding 'build/paddlenlp_ops/bdist.linux-x86_64/egg' to it
Traceback (most recent call last):
  File "/ssd1/liuyuanle/doing_1205/PaddleNLP/csrc/setup_cuda.py", line 154, in <module>
    setup(
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/paddle/utils/cpp_extension/cpp_extension.py", line 247, in setup
    setuptools.setup(**attr)
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/dist.py", line 995, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/command/install.py", line 109, in run
    self.do_egg_install()
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/command/install.py", line 167, in do_egg_install
    self.run_command('bdist_egg')
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/dist.py", line 995, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/command/bdist_egg.py", line 233, in run
    make_zipfile(
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/command/bdist_egg.py", line 474, in make_zipfile
    visit(z, dirname, files)
  File "/root/anaconda3/envs/d_1205/lib/python3.12/site-packages/setuptools/command/bdist_egg.py", line 467, in visit
    z.write(path, p)
  File "/root/anaconda3/envs/d_1205/lib/python3.12/zipfile/__init__.py", line 1835, in write
    with open(filename, "rb") as src, self.open(zinfo, 'w') as dest:
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/d_1205/lib/python3.12/zipfile/__init__.py", line 1589, in open
    return self._open_to_write(zinfo, force_zip64=force_zip64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/d_1205/lib/python3.12/zipfile/__init__.py", line 1690, in _open_to_write
    return _ZipWriteFile(self, zinfo, zip64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/d_1205/lib/python3.12/zipfile/__init__.py", line 1176, in __init__
    self._compressor = _get_compressor(zinfo.compress_type,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/d_1205/lib/python3.12/zipfile/__init__.py", line 738, in _get_compressor
    return zlib.compressobj(zlib.Z_DEFAULT_COMPRESSION, zlib.DEFLATED, -15)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid initialization option

感觉会不会是setuptools的版本问题

**Comment by DrownFish19** [comment]
看日志情况，应该是编译已经完成，打包过程成失败，可以试着更新pip和setuptools后再重新编译试试看。

**Comment by aooxin** [comment]
> 看日志情况，应该是编译已经完成，打包过程成失败，可以试着更新pip和setuptools后再重新编译试试看。

换了一个机器，已解决
