### ISSUE TITLE
[Question]: Taskflow 在 NPU上运行information_extraction报错

### ISSUE THREAD

**Issue by liujiachang** [PaddlePaddle/PaddleNLP#9691]
### 请提出你的问题

```
Taskflow(
    task="information_extraction",
    model="uie-base",
    precison='fp16',
    device_id=0,
    use_fast=True,
)
```
RuntimeError: (PreconditionNotMet) op [pd_op.full_with_tensor] kernel output args (0) defs should equal op outputs (1)
  [Hint: Expected op_item->num_results() == output_defs.size(), but received op_item->num_results():1 != output_defs.size():0.] (at /paddle/paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc:2468)

paddle-custom-npu  3.0.0b2
paddlenlp          3.0.0b2
paddlepaddle       3.0.0b2
CANN 8.0.RC1

**Comment by liujiachang** [comment]
运行`python -c "import paddle; paddle.utils.run_check()"`
提示：
/root/.local/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:686: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
I1225 10:55:24.539517  4353 init.cc:236] ENV [CUSTOM_DEVICE_ROOT]=/root/.local/lib/python3.10/site-packages/paddle_custom_device
I1225 10:55:24.539584  4353 init.cc:145] Try loading custom device libs from: [/root/.local/lib/python3.10/site-packages/paddle_custom_device]
I1225 10:55:26.426545  4353 custom_device.cc:1099] Succeed in loading custom runtime in lib: /root/.local/lib/python3.10/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I1225 10:55:26.522809  4353 custom_kernel.cc:63] Succeed in loading 357 custom kernel(s) from loaded lib(s), will be used like native ones.
I1225 10:55:26.523063  4353 init.cc:157] Finished in LoadCustomDevice with libs_path: [/root/.local/lib/python3.10/site-packages/paddle_custom_device]
I1225 10:55:26.523133  4353 init.cc:242] CustomDevice: npu, visible devices count: 1
Running verify PaddlePaddle program ... 
I1225 10:55:29.212662  4353 pir_interpreter.cc:1480] New Executor is Running ...
I1225 10:55:29.215441  4353 pir_interpreter.cc:1506] pir interpreter is running by multi-thread mode ...
W1225 10:55:33.030699  4643 pir_interpreter.cc:1980] Instruction OP id: 7, Ir OP id: 66, pd_op.sum_grad raises an EnforceNotMet exception common::enforce::EnforceNotMet
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/lib/python3.10/site-packages/paddle/utils/install_check.py", line 273, in run_check
    _run_static_single(use_cuda, use_xpu, use_custom, custom_device_name)
  File "/root/.local/lib/python3.10/site-packages/paddle/utils/install_check.py", line 153, in _run_static_single
    exe.run(
  File "/root/.local/lib/python3.10/site-packages/paddle/base/executor.py", line 1896, in run
    res = self._run_pir_impl(
  File "/root/.local/lib/python3.10/site-packages/paddle/base/executor.py", line 2242, in _run_pir_impl
    ret = new_exe.run(list(feed.keys()), return_numpy)
  File "/root/.local/lib/python3.10/site-packages/paddle/base/executor.py", line 845, in run
    tensors = self._new_exe.run(
OSError: In user code:
    ExternalError:  ACL error, the error code is : 500001.  (at /paddle/backends/npu/kernels/funcs/npu_op_runner.cc:445)
      [operator < pd_kernel.phi_kernel > error]

**Comment by ZHUI** [comment]
你的paddle环境有问题，鉴于您去paddle repo询问
