### ISSUE TITLE
[Question]: Taskflow如何指定模型路径，task为information_extraction

### ISSUE THREAD

**Issue by liujiachang** [PaddlePaddle/PaddleNLP#9698]
### 请提出你的问题

我通过task_path和home_path设定均会报错
```
Traceback (most recent call last):
  File "/root/work/filestorage/liujc/paddle/main.py", line 7, in <module>
    model = Taskflow(
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/taskflow.py", line 809, in __init__
    self.task_instance = task_class(
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/information_extraction.py", line 536, in __init__
    self._get_inference_model()
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/task.py", line 372, in _get_inference_model
    self._prepare_static_mode()
  File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/task.py", line 227, in _prepare_static_mode
    self.predictor = paddle.inference.create_predictor(self._config)
RuntimeError: (Unavailable) Not allowed to load partial data via load_combine_op, please use load_op instead.
  [Hint: Expected buffer->eof() == true, but received buffer->eof():0 != true:1.] (at /paddle/paddle/phi/kernels/impl/load_combine_kernel_impl.h:81)
  [operator < load_combine > error]
```

而且保存的模型路径中，缺失了inference.pdmodel文件。

**Comment by wawltor** [comment]
你的paddle是什么版本？

**Comment by Decade-rider** [comment]
> ### 请提出你的问题
> 我通过task_path和home_path设定均会报错
> 
> ```
> Traceback (most recent call last):
>   File "/root/work/filestorage/liujc/paddle/main.py", line 7, in <module>
>     model = Taskflow(
>   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/taskflow.py", line 809, in __init__
>     self.task_instance = task_class(
>   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/information_extraction.py", line 536, in __init__
>     self._get_inference_model()
>   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/task.py", line 372, in _get_inference_model
>     self._prepare_static_mode()
>   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/task.py", line 227, in _prepare_static_mode
>     self.predictor = paddle.inference.create_predictor(self._config)
> RuntimeError: (Unavailable) Not allowed to load partial data via load_combine_op, please use load_op instead.
>   [Hint: Expected buffer->eof() == true, but received buffer->eof():0 != true:1.] (at /paddle/paddle/phi/kernels/impl/load_combine_kernel_impl.h:81)
>   [operator < load_combine > error]
> ```
> 
> 而且保存的模型路径中，缺失了inference.pdmodel文件。

请问您找到在哪里下载inference.pdmodel文件了吗

**Comment by liujiachang** [comment]
paddlepaddle        3.0.0.dev20241225
paddle-custom-npu   3.0.0.dev20241226
paddlenlp           3.0.0b3

通过设置环境变量
export FLAGS_enable_pir_api=0
修复了该问题

**Comment by liujiachang** [comment]
> > ### 请提出你的问题
> > 我通过task_path和home_path设定均会报错
> > ```
> > Traceback (most recent call last):
> >   File "/root/work/filestorage/liujc/paddle/main.py", line 7, in <module>
> >     model = Taskflow(
> >   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/taskflow.py", line 809, in __init__
> >     self.task_instance = task_class(
> >   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/information_extraction.py", line 536, in __init__
> >     self._get_inference_model()
> >   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/task.py", line 372, in _get_inference_model
> >     self._prepare_static_mode()
> >   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/task.py", line 227, in _prepare_static_mode
> >     self.predictor = paddle.inference.create_predictor(self._config)
> > RuntimeError: (Unavailable) Not allowed to load partial data via load_combine_op, please use load_op instead.
> >   [Hint: Expected buffer->eof() == true, but received buffer->eof():0 != true:1.] (at /paddle/paddle/phi/kernels/impl/load_combine_kernel_impl.h:81)
> >   [operator < load_combine > error]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 而且保存的模型路径中，缺失了inference.pdmodel文件。
> 
> 请问您找到在哪里下载inference.pdmodel文件了吗

该文件不是下载下来的, static/目录是生成的

**Comment by Decade-rider** [comment]
我的意思是多次下载不成功，就想自己手动下载放到相应地址，但是没找到在仓库的哪里进行下载



---Original---
From: ***@***.***&gt;
Sent at: 2025年1月2日(Thu) AM8:41
To: ***@***.***&gt;;
Cc: "Chonglin ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleNLP] [Question]: Taskflow如何指定模型路径，task为information_extraction (Issue #9698)




   
请提出你的问题
 
我通过task_path和home_path设定均会报错
 Traceback (most recent call last):   File "/root/work/filestorage/liujc/paddle/main.py", line 7, in <module&gt;     model = Taskflow(   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/taskflow.py", line 809, in __init__     self.task_instance = task_class(   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/information_extraction.py", line 536, in __init__     self._get_inference_model()   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/task.py", line 372, in _get_inference_model     self._prepare_static_mode()   File "/usr/local/lib/python3.10/dist-packages/paddlenlp/taskflow/task.py", line 227, in _prepare_static_mode     self.predictor = paddle.inference.create_predictor(self._config) RuntimeError: (Unavailable) Not allowed to load partial data via load_combine_op, please use load_op instead.   [Hint: Expected buffer-&gt;eof() == true, but received buffer-&gt;eof():0 != true:1.] (at /paddle/paddle/phi/kernels/impl/load_combine_kernel_impl.h:81)   [operator < load_combine &gt; error]  
而且保存的模型路径中，缺失了inference.pdmodel文件。
  
请问您找到在哪里下载inference.pdmodel文件了吗
  
该文件不是下载下来的, static/目录是生成的

**Comment by liujiachang** [comment]
模型文件只有model_state.pdparams，static目录中的inference.pdmodel是运行taskflow代码生成的，他会自动检测你有没有inference.pdmodel这个文件，正常情况没有会主动生成，但是由于某些错误（我通过export FLAGS_enable_pir_api=0修复成功），没有生成，官方应该并没有提供该文件。

**Comment by Decade-rider** [comment]
好的，非常感谢



---Original---
From: ***@***.***&gt;
Sent at: 2025年1月2日(Thu) AM10:04
To: ***@***.***&gt;;
Cc: "Chonglin ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleNLP] [Question]: Taskflow如何指定模型路径，task为information_extraction (Issue #9698)




 
模型文件只有model_state.pdparams，static目录中的inference.pdmodel是运行taskflow代码生成的，他会自动检测你有没有inference.pdmodel这个文件，正常情况没有会主动生成，但是由于某些错误（我通过export FLAGS_enable_pir_api=0修复成功），没有生成，官方应该并没有提供该文件。

**Comment by Decade-rider** [comment]
> 模型文件只有model_state.pdparams，static目录中的inference.pdmodel是运行taskflow代码生成的，他会自动检测你有没有inference.pdmodel这个文件，正常情况没有会主动生成，但是由于某些错误（我通过export FLAGS_enable_pir_api=0修复成功），没有生成，官方应该并没有提供该文件。
非常感谢，在试了多次无果后，我重新配置了cuda、paddle，现在暂时问题解决了
