### ISSUE TITLE
vocab加载失败

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleNLP#970]
加载vocab文件:  "https://huggingface.co/google/mobilebert-uncased/blob/main/vocab.txt"
使用最新的develop分支

Traceback (most recent call last):
  File "/f/pd_match/papers_reproduce/PaddleNLP/tokenizer_test.py", line 4, in <module>
    tokenizer = MobileBertTokenizer('/home/hl/.paddlenlp/models/mobilebert-uncased/vocab.txt', do_lower_case=True)
  File "/f/pd_match/papers_reproduce/PaddleNLP/paddlenlp/transformers/utils.py", line 83, in __impl__
    init_func(self, *args, **kwargs)
  File "/f/pd_match/papers_reproduce/PaddleNLP/paddlenlp/transformers/utils.py", line 83, in __impl__
    init_func(self, *args, **kwargs)
  File "/f/pd_match/papers_reproduce/PaddleNLP/paddlenlp/transformers/bert/tokenizer.py", line 387, in __init__
    self.vocab = self.load_vocabulary(vocab_file, unk_token=unk_token)
  File "/f/pd_match/papers_reproduce/PaddleNLP/paddlenlp/transformers/tokenizer_utils.py", line 680, in load_vocabulary
    **kwargs)
  File "/f/pd_match/papers_reproduce/PaddleNLP/paddlenlp/data/vocab.py", line 436, in from_dict
    **kwargs)
  File "/f/pd_match/papers_reproduce/PaddleNLP/paddlenlp/data/vocab.py", line 93, in __init__
    special_token)
AssertionError: [UNK] is not in token_to_idx

**Comment by lxw0109** [comment]
遇到同样的问题，请问有人能解答下吗？

**Comment by davidgonghs** [comment]
File "/home/smartdataetl/miniconda3/envs/paddlenlp-gpu/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/smartdataetl/miniconda3/envs/paddlenlp-gpu/lib/python3.8/site-packages/paddlenlp/transformers/ernie/tokenizer.py", line 346, in __init__
    self.vocab = self.load_vocabulary(vocab_file, unk_token=unk_token)
  File "/home/smartdataetl/miniconda3/envs/paddlenlp-gpu/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 867, in load_vocabulary
    vocab = Vocab.from_dict(
  File "/home/smartdataetl/miniconda3/envs/paddlenlp-gpu/lib/python3.8/site-packages/paddlenlp/data/vocab.py", line 419, in from_dict
    vocab = cls(
  File "/home/smartdataetl/miniconda3/envs/paddlenlp-gpu/lib/python3.8/site-packages/paddlenlp/data/vocab.py", line 99, in __init__
    assert special_token in token_to_idx, "{} is not in token_to_idx".format(special_token)
AssertionError: [UNK] is not in token_to_idx

I also got same problem, not sure how to fix it

**Comment by JoshonSmith** [comment]
I also got same problem, not sure how to fix it
